### ISSUE TITLE
Anbox EGL doesn't support surfaceless context error

### ISSUE THREAD

**Issue by xeon-zolt** [anbox/anbox#100]
ANBOX_LOG_LEVEL=debug anbox session-manager        
[DD 2017-04-14 18:58:07] [gl_renderer_server.cpp:82@GLRendererServer] Using GLES-to-GL translator for rendering
[DD 2017-04-14 18:58:07] [Renderer.cpp:113@initialize] EGL doesn't support surfaceless context
[DD 2017-04-14 18:58:07] [Renderer.cpp:249@initialize] Successfully initialized EGL
[1]    7134 segmentation fault (core dumped)  ANBOX_LOG_LEVEL=debug anbox session-manager

**Additional info:**
machine  - Arch Linux
using intel gpu

**Comment by subjectdenied** [comment]
did you already try this?

ANBOX_LOG_LEVEL=debug anbox session-manager --gles-driver=host

**Comment by xeon-zolt** [comment]
@subjectdenied yup i already tried that 
and the error was
ANBOX_LOG_LEVEL=debug anbox session-manager --gles-driver=host
[EE 2017-04-14 19:33:14] [Renderer.cpp:105@initialize] Failed to initialize EGL
[1]    12941 segmentation fault (core dumped)  ANBOX_LOG_LEVEL=debug anbox session-manager --gles-driver=host

**Comment by morphis** [comment]
> [DD 2017-04-14 18:58:07] [Renderer.cpp:113@initialize] EGL doesn't support surfaceless context

Isn't a problem here. The renderer checks for different capabilities and will choose a proper fallback if certain features are not supported.

**Comment by xeon-zolt** [comment]
i managed to launch session manager with nvidia proprietary drivers only once 
but then i am not able to start anbox launch 
it started but closed immediately

**Comment by morphis** [comment]
@xeon-zolt This seems to be a different bug but is for sure not related to the one described in the title which is a pure debug message. Can you check if any of the other open bugs matches the problem you're seeing?

**Comment by LinArcX** [comment]
i have same issue on my arch linux too:
```
 ❯ ANBOX_LOG_LEVEL=debug anbox session-manager                                                                        [14:50:04]
[DD 2017-04-25 10:20:04] [gl_renderer_server.cpp:82@GLRendererServer] Using GLES-to-GL translator for rendering
[DD 2017-04-25 10:20:04] [Renderer.cpp:113@initialize] EGL doesn't support surfaceless context
[DD 2017-04-25 10:20:04] [Renderer.cpp:249@initialize] Successfully initialized EGL
[1]    7071 segmentation fault (core dumped)  ANBOX_LOG_LEVEL=debug anbox session-manager

```
