### ISSUE TITLE
4.19.x 4.20.x kernels not supported by dkms

### ISSUE THREAD

**Issue by stuaxo** [anbox/anbox#1000]
Hi,
    I have various 4.19.x kernels and a 4.20rc kernes installed (on the way to finding an amd gfx driver that works).

When I try to build dkms, they 
They all complain along the lines of:

```
Building module:
cleaning build area...
make -j8 KERNELRELEASE=4.19.6 -C /lib/modules/4.19.6/build M=/var/lib/dkms/virtualbox/5.2.18/build......(bad exit status: 2)
ERROR (dkms apport): kernel package linux-headers-4.19.6 is not supported
Error! Bad return status for module build on kernel: 4.19.6 (x86_64)
Consult /var/lib/dkms/virtualbox/5.2.18/build/make.log for more information.
                                                                         [ OK ]
 * dkms: running auto installation service for kernel 4.20.0-rc3                
Kernel preparation unnecessary for this kernel.  Skipping...
```

Not sure if this is a problem anbox can deal with or if dkms takes a while to catch up with kernels (these are from PPA).

**Comment by parithy** [comment]
this seems to be related to virtualbox kernal module. could you clarify how anbox is related to this?

**Comment by stuaxo** [comment]
Good point.   This where dkms build stops,  but I think it's a general dkms issue on this kernel,  not anbox, closing.
