### ISSUE TITLE
Feature request : ndk_translation

### ISSUE THREAD

**Issue by parithy** [anbox/anbox#1001]
This is a feature request, so standard template doesn't apply.
Currently, there is an option to trigger a script and install libhoudini support to have some of the apps containing ARM binary in amd64 boards. But this ticket has been raised to consider ndk_translation which is used in the official arc++ of Chrome OS to be more aligned with upstream in terms android runtime compatability.

**Comment by morphis** [comment]
@parithy You have any links to what you call "ndk_translation"?

**Comment by parithy** [comment]
Or may be we have to take in the qemu's arm to x86 translators for arm ndk binaries.

**Comment by parithy** [comment]
keepping it from being stale so it can be tracked
