### ISSUE TITLE
Feature reqeust: VPN

### ISSUE THREAD

**Issue by parithy** [anbox/anbox#1004]
This is a feature request so not following standard template

There are myriad of VPN apps in the android ecosystem. To take advantage of that in regular non android apps running in the host, the VPN tunnel configuration of the app has to percolate to the host network configuration. 

There is already bug where its reported that vpn settings are not working within the anbox container. Once that is fixed by properly having the tunnels working within the container, it would be helpful if Anbox exposes an option to seamless bring the VPN tunnels to the non android apps using distro vpn configurations. I am not sure how ,much a restriction being in snap framework would affect the feasibility, but this certainly qualifies as important enterprise feature.

**Comment by mariocornejo3** [comment]
I second this. I'm visiting outside the US and would like to use the variety of VPN apps available on Android.

**Comment by parithy** [comment]
@morphis Could we have "enhancement" tag for this?

**Comment by lygstate** [comment]
Yeap, how to enable VPN of this?

**Comment by mikma** [comment]
> There is already bug where its reported that vpn settings are not working within the anbox container. 

PR #1086 (partly) allows you to use VPN apps within the anbox container. You also you need an updated android.img, or running a small script after starting the container. What's missing is VpnService.protect() which doesn't seem to work. Tested with the Wireguard App.

**Comment by martynhare** [comment]
We still want this.
