### ISSUE TITLE
anbox in ubuntu 16.04 32bit.

### ISSUE THREAD

**Issue by stilnk** [anbox/anbox#1006]
Hello!
I have installed ubuntu 16.04 version 32 bit. My processor does not support 64 bits. I really need to install Anbox on 32 bits. Help me how to do it. Thank you.

**Comment by stilnk** [comment]
My computer only supports 32 bits. The computer is old. I can not buy a new computer. I don’t know what to do now. I just believe that there may be an Anbox version for 32 bits. I really need it. Maybe there is an old Anbox version that I can install? I believe that you will help me with advice. Thank you.

**Comment by morphis** [comment]
@stilnk I am sorry, but we wont support 32 bit as its too much effort for a too small user base.

**Comment by rpntech821** [comment]
i have samé problem

**Comment by rpntech821** [comment]
please make 32bit version

**Comment by shagle** [comment]
A sigh. If possible...
