### ISSUE TITLE
anbox not starting ubuntu 18.04

### ISSUE THREAD

**Issue by variagH** [anbox/anbox#1007]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
 anbox.appmgr 
[ 2018-12-25 12:28:40] [launch.cpp:182@operator()] Session manager is not yet running, trying to start it
[ 2018-12-25 12:28:40] [launch.cpp:116@launch_session_manager] Started session manager, will now try to connect ..
[ 2018-12-25 12:29:05] [launch.cpp:127@try_launch_activity] Sending launch intent [ package=org.anbox.appmgr component=org.anbox.appmgr.AppViewActivity ] to Android ..

5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**

anbox system-info
version: 4
snap-revision: 166
cpu:
  arch:  x86
  brand:       Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
os:
  name: Ubuntu
  version: 18.04.1 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.15.0-43-generic (buildd@lgw01-amd64-001) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.4
    extensions:
      - EGL_NV_system_time
      - EGL_KHR_surfaceless_context
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_config_attribs
      - EGL_KHR_fence_sync
      - EGL_NV_sync
      - EGL_KHR_reusable_sync
      - EGL_KHR_create_context
      - EGL_EXT_create_context_robustness
      - EGL_KHR_stream
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_stream_consumer_gltexture
      - EGL_NV_stream_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_IMG_context_priority
      - EGL_NV_post_sub_buffer
      - EGL_KHR_image_pixmap
      - EGL_EXT_buffer_age
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 3.1 340.107
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_color_buffer_float
      - GL_EXT_color_buffer_half_float
      - GL_EXT_copy_image
      - GL_EXT_debug_label
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_implicit_conversions
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shadow_samplers
      - GL_EXT_sRGB
      - GL_EXT_sRGB_write_control
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_storage
      - GL_EXT_texture_view
      - GL_EXT_unpack_subimage
      - GL_KHR_debug
      - GL_NV_bgr
      - GL_NV_blend_equation_advanced
      - GL_NV_copy_buffer
      - GL_NV_copy_image
      - GL_NV_draw_buffers
      - GL_NV_draw_instanced
      - GL_NV_draw_texture
      - GL_NV_EGL_stream_consumer_external
      - GL_NV_explicit_attrib_location
      - GL_NV_fbo_color_attachments
      - GL_NV_framebuffer_blit
      - GL_NV_framebuffer_multisample
      - GL_NV_generate_mipmap_sRGB
      - GL_NV_instanced_arrays
      - GL_NV_occlusion_query_samples
      - GL_NV_non_square_matrices
      - GL_NV_pack_subimage
      - GL_NV_packed_float
      - GL_NV_packed_float_linear
      - GL_NV_pixel_buffer_object
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_NV_shadow_samplers_array
      - GL_NV_shadow_samplers_cube
      - GL_NV_sRGB_formats
      - GL_NV_texture_array
      - GL_NV_texture_border_clamp
      - GL_NV_texture_compression_latc
      - GL_NV_texture_compression_s3tc
      - GL_NV_texture_compression_s3tc_update
      - GL_NV_timer_query
      - GL_KHR_blend_equation_advanced
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_depth32
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_EGL_image
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_surfaceless_context
      - GL_OES_texture_npot
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float

```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

Anbox is not starting. Where is the problem?

**What were you expecting?:**

**Additional info:**

**Comment by imShara** [comment]
@Anan5a How do you solved it actually?

**Comment by Anan5a** [comment]
@imShara I never solved it. Just stopped wasting my time
