### ISSUE TITLE
Feature request: Multiple app instance

### ISSUE THREAD

**Issue by parithy** [anbox/anbox#1008]
This is a feature request not a bug so standard template doesn't apply.

Use case scenario: 
1) two text documents to be opened and viewed simultaneously in same app
2) two webpages to be opened and viewed in the same app

Current behavior:
Only one instance of an app instance is allowed to run at any given time. This is the case even in the Chromebook/Android phones. So i am not sure if this would require too much of deviation from the upstream code. If it is better to track this as sort of upstream feature request. if it can be done at the anbox layer, then its a anbox feature request. Either way, this is potential desktop feature.

**Comment by morphis** [comment]
As long this isn't directly supported by Android we will not be able to make it available through Anbox. Given the limited developers we have I don't see this happen any time soon unless Android supports this in a future relese.

**Comment by yogita3279** [comment]
Is it possible to run and view the same android app simultaneously at same time using anbox?
If it is so? then what is the procedure.
