### ISSUE TITLE
SHA sum does not fit at installation

### ISSUE THREAD

**Issue by Acromonkey** [anbox/anbox#101]
I just installed the snap version of anbox. When I run anbox-installer, everything worked fine until the following lines appeared:

**Description of the problem:**

+ sudo modprobe binder_linux
+ sudo modprobe ashmem_linux
+ snap info anbox
+ grep -q installed:
+ sudo snap install --edge --devmode anbox
error: cannot perform the following tasks:
- Download snap "anbox" (15) from channel "edge" (sha3-384 mismatch after patching "anbox": got 4718a69fedbc592d5c028e7a07faf6d2f1577b03be06d0e5511760b3f974e4c6808b12182abe4f2cfad0f1e7b7bc9b1f but expected db75d2f3a58b4590db1b491190f4437f5ca3cf0cabd4cdf8197de3992cee2cbbf3d86f961b084b9c628c119d781d1f14)

Then the program stops.

**Anbox release (`anbox version`) and system info (`anbox system-info`):**
Anbox snap version on Linux Mint 18.1

**Comment by morphis** [comment]
This is most likely an temporary issue with your network connection that a bit shifted during the download of the anbox.snap. This is someething the upstream snapd project needs to deal better with. However in our case this is nothing we can influence and we can only make our installer more robust against such cases which we have ongoing work for. Taking this bug by its summary, we can't fix this as its an upstream issue.
