### ISSUE TITLE
transfer files from linux to anbox

### ISSUE THREAD

**Issue by bouhmidi** [anbox/anbox#1010]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by morphis** [comment]
Please describe more in detail what you want to have as feature. Just a title isn't really enough.

**Comment by bouhmidi** [comment]
whenever i try to copy paste linux files into anbox directories it refuses to complete it .
i know its not a good idea but i really want to send some files to anbox's emulated storage if you know how to do it i would be grateful

**Comment by Arucard1983** [comment]
From my experience, use the adb tool to upload or download files.

To upload files, use: `adb push <files> '/sdcard/Download'`
Examples:
`adb push *.mp4 '/sdcard/Movies'`
`adb push * sdcard/Download'`

To download files, use `adb pull '/sdcard/Download/ .`
Examples:
`adb pull '/sdcard/Movies' .`

And so on, as long you start Anbox first of all, or the adb bridge tools will fail to connect the virtual storage.

**Comment by ajvsol** [comment]
It would be great to have it at the point where there's drag-and-drop functionality.

**Comment by parithy** [comment]
@morphis Should this still have "needs info" tag instead of "enhancement"

**Comment by shemgp** [comment]
You may use adbfs to mount the anbox filesystem in linux so that you may drag and drop files using nautilus: https://github.com/spion/adbfs-rootless

**Comment by z0xyz** [comment]
https://youtu.be/gyAPpnnQocw

**Comment by z0xyz** [comment]
Install "X-plore file manager" on anbox , after opening it ,click on "Wifi file sharing" and then activate wifi server .. 
open the ip address:port on your linux machine's browser ...and start drag and drop files

**Comment by 5p4r70n** [comment]
sudo setfacl -m 'u:username:rwx' /var/snap/anbox/common/data/media
 
 with this command i can able to access the anbox filesystem in linux.. 
 then create a link or shortcut of the folder then we can drag and drop files..  :)

**Comment by LunyCipres** [comment]
--to get access to anbox directory
sudo chown -R _username_ /var/snap/anbox/common/data/media
so that media folder can be read, otherwise all files inside it "don't exist"
sudo ln -s /var/snap/anbox/common/data/media/0 /home/_username_

although this is a bit of a brute force considering you are taking ownership of media folder, it works

**Comment by ProgrammingLife** [comment]
Tried all those things but my Downloads folder is still empty.
Anbox installed with snap.
```
adb push 1.apk '/sdcard/Download'

sudo chown -R _username_ /var/snap/anbox/common/data/media
sudo cp 1.apk /var/snap/anbox/common/data/media
```

**Comment by LunyCipres** [comment]
> Tried all those things but my Downloads folder is still empty. Anbox installed with snap.
> 
> ```
> $ adb push 1.apk '/sdcard/Download'
> ...copying ...
> 
> $ adb devices
> List of devices attached
> emulator-5558	device
> 
> $ sudo chown -R _username_ /var/snap/anbox/common/data/media
> $ sudo cp 1.apk /var/snap/anbox/common/data/media
> $ sudo cp 1.apk /var/snap/anbox/common/data/media/0/Download/
> ```

Hmm, I'm not on Linux anymore so I cannot test it, but did you replace _username_ with your username in chown command?
Also try restarting a box after moving files.

**Comment by LauDoev** [comment]
I have the same issue, but by coincidence I found a workaround. When I adb push a file to /sdcard/Download, the file doesn't appear in the default file manager's Download folder, but when I go to Settings>Storage>Explore, I can see a number of folders, also one called 'Download', and this one does contain the pushed file.

**Comment by Shanmukhsvstp** [comment]
This Workef For Me:
1. Goto Filesystem --> var --> snap --> anbox --> common --> data --> media (You may need to enter your password authentication here) --> 0 --> Download 
2. You can drag and drop here. I dont think paste option works here.
3. Optional Below:
4. I also found new easiest way to deploy nextjs app on firebase hosting. Check my channel here: https://www.youtube.com/@Apps_By_PSS
