### ISSUE TITLE
Errors installing anbox (Ubuntu 18.04)

### ISSUE THREAD

**Issue by rndbroom** [anbox/anbox#1011]
I am new to Linux and not sure how to fix these problems.
I have attached an image showing the two problems while running the following commands
$ sudo apt install linux-headers-generic anbox-modules-dkms
$ snap install --devmode --beta anbox
I am running the update command as well. It returns there are 317 packages that could be updated. I run the command to see the list, but not sure how to install the updates.

https://i.stack.imgur.com/Pbmwo.png (IMAGE OF TERMINAL ERRORS)

**Comment by morphis** [comment]
Something seems to be wrong with your system and this is more an issue with snapd. Please ask at https://forum.snapcraft.io/ for help.
