### ISSUE TITLE
Internet connection problem ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by piusalfred** [anbox/anbox#1012]
I have problem accessing the internet from anbox every time the host computer restart. If I uninstall it and reinstall it works perfectly but if the computer restarts internet connection becomes a problem

**Comment by mishra283** [comment]
Hi, did you get any solution? @piusalfred

**Comment by piusalfred** [comment]
@mishra283 I installed anbox via snap, and it seems every time I restart my computer or the computer shut down unexpectedly, anbox fails to access the internet. stop and restarting anbox did the magic.
run
`sudo snap stop anbox`
and then
`sudo snap start anbox`
