### ISSUE TITLE
anbox and input devices

### ISSUE THREAD

**Issue by frenzisys** [anbox/anbox#1014]
Is there any version of ubuntu in which anbox works?

**Comment by rizzini** [comment]
It's working like a charm here. Kubuntu 18.10 - 64bits.

**Comment by morphis** [comment]
@frenzisys You need to describe a bit more what doesn't work for you before we can help.

**Comment by sstahl4006** [comment]
Mouse and keyboard working. Thank you all.

**Comment by bdutta** [comment]
Lubuntu 18.04, working for apps not needing audio. Can't get audio to work. Starting basic recorder crashes it.
