### ISSUE TITLE
I really appriciate you guys for the awesome work beinging done on Anbox. I am new to linux and programming. I installed Anbox on my manjaro via AUR and it works perfectly fine. I sent a music file into the Anbox via google drive, but i observed that music does not play smoothly ( plays 2 secs and stops and repeats the sequence again. I played music using Vlc app) and all my language learning app does not have sound. (Even when i installed google tts to it). kind regards

### ISSUE THREAD

**Issue by elfg** [anbox/anbox#1017]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by agucova** [comment]
As a small sidenote, all the general comment should probably go in the issue's description, not title.
