### ISSUE TITLE
Unable to install on Linux Mint 19

### ISSUE THREAD

**Issue by xifi-kif** [anbox/anbox#1024]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
Command 'anbox' is available in '/snap/bin/anbox'
The command could not be located because '/snap/bin' is not included in the PATH environment variable.
anbox: command not found

```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**
After installation as described in the website, at first start this error comes out:

Command 'anbox' is available in '/snap/bin/anbox'
The command could not be located because '/snap/bin' is not included in the PATH environment variable.
anbox: command not found


**What were you expecting?:**
Andbox should start

**Additional info:**
[Uploading anbox-system-diagnostics-2019-01-14.zip…]()

**Comment by Genxster1998** [comment]
Try launching from /snap bin directory different shortcuts

**Comment by lbrunkho** [comment]
just ran into this issue, simple fix just append `export PATH="/snap/bin:$PATH"` to your `~/.bashrc`

reboot or run `source .bashrc`
