### ISSUE TITLE
Cannot build Anbox for ARM64

### ISSUE THREAD

**Issue by HarleyPato** [anbox/anbox#1026]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**
Hi. I'm trying to build anbox for ARM64 in my Ubuntu 18.04 (x86_64), but when typing:

root@enrique-Lenovo-G500:/home/enrique/anbox# ./cross-compile-chroot.sh -a arm64 -d bionic

I get this

Building for distro: bionic
Using AC_NDK_PATH: /root/.cache/anbox-arm64-chroot-bionic
Target architecture: arm64
Target machine: aarch64-linux-gnu
Using PKG_CONFIG_PATH: /root/.cache/anbox-arm64-chroot-bionic/usr/lib/pkgconfig:/root/.cache/anbox-arm64-chroot-bionic/usr/lib/aarch64-linux-gnu/pkgconfig
Using PKG_CONFIG_EXECUTABLE: /usr/bin/pkg-config
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/aarch64-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/aarch64-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:59 (find_package)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:59 (find_package)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:59 (find_package)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:59 (find_package)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:59 (find_package)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:59 (find_package)

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Could NOT find Boost
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find EGL (missing: EGL_LIBRARY EGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindEGL.cmake:22 (find_package_handle_standard_args)
  CMakeLists.txt:62 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/enrique/anbox/build-arm64-bionic/CMakeFiles/CMakeOutput.log".
See also "/home/enrique/anbox/build-arm64-bionic/CMakeFiles/CMakeError.log".

**What were you expecting?:**
Building anbox for arm64

**Additional info:**
Is it possible to make an snap out of this for arm64?

**Comment by HarleyPato** [comment]
Closing since it was related to missing libraries.

**Comment by sewonist** [comment]
Hi, @HarleyPato 
I also try to install anbox to linux on ARM. I've searched post and yours also. I'm very interesting in #1043 
I try your way. Unfortunately, I have same error like this post. How to fix related to missing libraries?? I try to install EGL Library but it didn't work.

**Comment by Frankdwu** [comment]
I have the same problem as yours:
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find EGL (missing: EGL_LIBRARY EGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindEGL.cmake:22 (find_package_handle_standard_args)
  CMakeLists.txt:62 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/deqiangw/anbox/build-arm64-bionic/CMakeFiles/CMakeOutput.log".
See also "/home/deqiangw/anbox/build-arm64-bionic/CMakeFiles/CMakeError.log"

I checked the installed EGL package on my PC, it looks like the related EGL package is installed, why it still report erros?:
deqiangw@WIN-7BUT4G6S50C:/usr/include$ apt list --installed |grep -i egl

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libegl-mesa0/bionic-updates,bionic-security,now 19.2.8-0ubuntu0~18.04.2 arm64 [installed,automatic]
libegl1/bionic-updates,now 1.0.0-2ubuntu2.3 arm64 [installed,automatic]
libegl1-mesa-dev/bionic-updates,bionic-security,now 19.2.8-0ubuntu0~18.04.2 arm64 [installed]
libwayland-egl1/bionic-updates,bionic-security,now 1.16.0-1ubuntu1.1~18.04.3 arm64 [installed,automatic]
deqiangw@WIN-7BUT4G6S50C:/usr/include$

**Comment by oyzw0720** [comment]
Hi @HarleyPato ,
I've got the same error with you, how did you fix these? Thanks

**Comment by Theslees** [comment]
> Closing since it was related to missing libraries.

@oyzw0720 It was due to missing libraries, so you need to install them with your package manager.
