### ISSUE TITLE
not able to activate device admin

### ISSUE THREAD

**Issue by didlich** [anbox/anbox#1027]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

I've installed anbox as described in your guide, then
I installed outlook APK, but its not possible to activate the Security->Device administrators
If I click on the "Outlook Device Policy" -> "Activate this device administrator" the screen redirects to "Outlook Device Policy"  again but this is not selected. The same happens if I try to activate administrator in Outlook.

**Comment by Genxster1998** [comment]
# device admin feature is disabled in anbox 
you can try editing 
```
/system/etc/permisssions/anbox.xml
```

**Comment by Zecknaal** [comment]
Sorry if I am resurrecting a dead issue - I followed the suggestion of Genxster1998 and used the instructions [here](https://docs.anbox.io/userguide/advanced/rootfs_overlay.html) to enable the rootfs-overlay and I was able to enable the device admin settings.
