### ISSUE TITLE
Anbox won't run (container problem)

### ISSUE THREAD

**Issue by HarleyPato** [anbox/anbox#1036]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
version: local-bbf05d8
cpu:
  arch:  
  brand: 
  features: 
os:
  name: Ubuntu
  version: 18.04.1 LTS (Bionic Beaver)
  snap-based: false
kernel:
  version: Linux version 4.16.0-rc1+ (root@enrique-Lenovo-G500) (gcc version 7.3.0 (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04)) #1 SMP PREEMPT Sun Jan 20 20:09:48 CET 2019
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: NVIDIA
    vendor: OpenGL ES 3.1 Mesa 18.2.0-devel
    extensions:
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_norm16
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_EXT_window_rectangles
      - GL_KHR_blend_equation_advanced
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_image_formats
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_image_external_essl3
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_get_program_binary
      - GL_OES_gpu_shader5
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_primitive_bounding_box
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array

**Please describe your problem:**
Hi. When I run anbox session-manager command (not root) I get this error:

dbus[19950]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

[ 2019-01-23 13:04:51] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to set config item lxc.pts
[ 2019-01-23 13:04:51] [session_manager.cpp:145@operator()] Lost connection to container manager, terminating.
[ 2019-01-23 13:04:52] [daemon.cpp:61@Run] Container is not running
[ 2019-01-23 13:04:52] [session_manager.cpp:145@operator()] Lost connection to container manager, terminating.
Stack trace (most recent call last) in thread 19961:

**What were you expecting?:**
Running anbox on arm64.

**Additional info:**
Also, when I run anbox launch, I get this:

switch@switch:~$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
dbus[26097]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

[ 2019-01-23 13:09:54] [daemon.cpp:61@Run] Failed to retrieve ready property from application manager

Also I have to say, that when running an anbox window pops up (starting...) and then close when appearing: [ 2019-01-23 13:09:54] [daemon.cpp:61@Run] Failed to retrieve ready property from application manager

Could this be a problem when I use an old android image version of anbox for arm64?

I used this image to setup the container:

https://build.anbox.io/android-images/2017/08/04/

Greetings!

PD: here's the container's config:

lxc.mount.auto = proc:mixed sys:mixed cgroup:mixed
lxc.autodev = 1
lxc.pty.max = 1024
lxc.tty.max = 0
lxc.uts.name = anbox
lxc.environment = PATH=/system/bin:/system/sbin:/system/xbin
lxc.init.cmd = /anbox-init.sh
lxc.rootfs.path = /var/lib/anbox/rootfs
lxc.log.level = 0
lxc.log.file = /var/lib/anbox/logs/container.log
lxc.console.logfile = /var/lib/anbox/logs/console.log
lxc.console.rotate = 1
lxc.apparmor.profile = unconfined
lxc.idmap = u 0 100000 999
lxc.idmap = g 0 100000 999
lxc.idmap = u 1000 1000 1
lxc.idmap = g 1000 1000 1
lxc.idmap = u 1001 101001 64535
lxc.idmap = g 1001 101001 64535
lxc.mount.entry = /run/user/1000/anbox/sockets/qemu_pipe /var/lib/anbox/rootfs/dev/qemu_pipe none bind,create=file,optional 0 0
lxc.mount.entry = /run/user/1000/anbox/sockets/anbox_audio /var/lib/anbox/rootfs/dev/anbox_audio none bind,create=file,optional 0 0
lxc.mount.entry = /run/user/1000/anbox/input /var/lib/anbox/rootfs/dev/input none bind,create=dir,optional 0 0
lxc.mount.entry = /run/user/1000/anbox/sockets/anbox_bridge /var/lib/anbox/rootfs/dev/anbox_bridge none bind,create=file,optional 0 0
lxc.mount.entry = /var/lib/anbox/devices/zero dev/zero none bind,create=file,optional 0 0
lxc.mount.entry = /var/lib/anbox/devices/urandom dev/urandom none bind,create=file,optional 0 0
lxc.mount.entry = /var/lib/anbox/devices/random dev/random none bind,create=file,optional 0 0
lxc.mount.entry = /var/lib/anbox/devices/ashmem dev/ashmem none bind,create=file,optional 0 0
lxc.mount.entry = /var/lib/anbox/devices/fuse dev/fuse none bind,create=file,optional 0 0
lxc.mount.entry = /var/lib/anbox/devices/binder dev/binder none bind,create=file,optional 0 0
lxc.mount.entry = /var/lib/anbox/devices/console dev/console none bind,create=file,optional 0 0
lxc.mount.entry = /var/lib/anbox/devices/full dev/full none bind,create=file,optional 0 0
lxc.mount.entry = /var/lib/anbox/devices/tty dev/tty none bind,create=file,optional 0 0
lxc.mount.entry = /var/lib/anbox/state/default.prop /var/lib/anbox/rootfs/default.prop none bind,optional,ro 0 0

**Comment by iam-alex** [comment]
Hi!, I'm also facing the same issue upon running anbox session-manager.

[ 2019-01-30 05:28:16] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to set config item lxc.pty.max
[ 2019-01-30 05:28:16] [session_manager.cpp:145@operator()] Lost connection to container manager, terminating.
[ 2019-01-30 05:28:17] [daemon.cpp:61@Run] Container is not running
[ 2019-01-30 05:28:17] [session_manager.cpp:145@operator()] Lost connection to container manager, terminating.
