### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by xzghk2017** [anbox/anbox#1043]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by xzghk2017** [comment]
# snap install --devmode --beta anbox
error: snap "anbox" is not available on beta for this architecture (arm64) but exists on other
       architectures (amd64).

# uname -a
Linux hxt-2 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:41:03 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

**Comment by xzghk2017** [comment]
failed to snap install anbox on arm64 ubuntu18.04.1 LTS

**Comment by HarleyPato** [comment]
Well.

The snap is for AMD64, not for ARM64, so obviously it won't work.

You will have to build a snap for that architecture.

I was the one trying to do so, but I didn't success, yet.

See: https://launchpadlibrarian.net/408421254/buildlog_snap_ubuntu_xenial_arm64_anbox-2-arm64_BUILDING.txt.gz

Same error as bionic.

Greetings.

**Comment by HarleyPato** [comment]
I have successfully built an Anbox snap for ARM64.

Here you have: https://code.launchpad.net/~patosublime/+snap/anbox-2-arm64/+build/449602

Note: It ONLY works for Ubuntu 16.04, but if you succeed on installing 1.58.0 libboost libraries on 18.04 (bionic) then it would work, too.

Greetings!

**Comment by HarleyPato** [comment]
Aaaand this snap is for Ubuntu 18.04.

I didn't test it yet, but at least it does install.

https://launchpad.net/~patosublime/+snap/anbox-4-arm64/+build/450757

Any problem you have please tell me.

Greetings!

**Comment by itdaniher** [comment]
Looking at https://github.com/anbox/anbox/blob/master/src/anbox/cmds/check_features.cpp I'm not sure it'll run as expected.

**Comment by xzghk2017** [comment]
thanks，PAto.
I will do the test after our Chinese spring festival might Feb,19th.

Thanks again!

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Pato <notifications@github.com>
发送时间: 星期一, 二月 4, 2019 05:48
收件人: anbox/anbox
抄送: xzghk2017; Author
主题: Re: [anbox/anbox] arm64 (#1043)


Aaaand this snap is for Ubuntu 18.04.

I didn't test it yet, but at least it does install.

https://launchpad.net/~patosublime/+snap/anbox-4-arm64/+build/450757

Any problem you have please tell me.

Greetings!

―

**Comment by xzghk2017** [comment]
Hi  Pato,

I download the build you provided and installed it on my host as below,
#snap install --dangerous --devmode  anbox_4-fbe87ab_arm64.snap

then I check this snap anbox version using the common command, and find the not supported architecture info, I'll do more check for this build later.

root@hxt-2:~/snap# anbox check-features
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
You're running Anbox on a not yet supported architecture
root@hxt-2:~/snap# anbox wait-ready
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
[ 2019-02-19 09:59:29] [daemon.cpp:61@Run] Failed to connect to DBus
root@hxt-2:~/snap# anbox version
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
anbox 4
root@hxt-2:~/snap# snap list
Name             Version    Rev   Tracking  Publisher   Notes
anbox            4-fbe87ab  x2    -         -           devmode
anbox-installer  1          31    stable    morphis     classic
core             16-2.37.2  6410  stable    canonical✓  core
core18           18         722   stable    canonical✓  base

thanks a lot!
zhigang

________________________________
发件人: xiao zhigang <xzghk@hotmail.com>
发送时间: 2019年2月4日 9:16
收件人: anbox/anbox; anbox/anbox
抄送: Author
主题: Re: [anbox/anbox] arm64 (#1043)

thanks，PAto.
I will do the test after our Chinese spring festival might Feb,19th.

Thanks again!

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Pato <notifications@github.com>
发送时间: 星期一, 二月 4, 2019 05:48
收件人: anbox/anbox
抄送: xzghk2017; Author
主题: Re: [anbox/anbox] arm64 (#1043)


Aaaand this snap is for Ubuntu 18.04.

I didn't test it yet, but at least it does install.

https://launchpad.net/~patosublime/+snap/anbox-4-arm64/+build/450757

Any problem you have please tell me.

Greetings!

**Comment by HarleyPato** [comment]
Yeah, just forgot to say that it doesnt work.

I solved that, though, by removing hooks, so that it doesnt check for cpu features.

The real problema here, is libSDL2. There is a bug in 18.04 that prevents anbox from working. So I backported it, but we have to bundle the snap with it. 

For that reason, I am not releasing anything until I get It working.

Greetings

**Comment by itdaniher** [comment]
@HarleyPato Thanks for looking into this, makes sense that it doesn't work based on those CPU checks. Glad it seems to be as simple as patching them out. Have you tried 18.10 for libSDL2? Cheers!

**Comment by sshock** [comment]
see also #833

**Comment by zphj1987** [comment]
@HarleyPato 
anbox need  1.58.0 libboost libraries,but the snap core do not have it ,how to install it?

**Comment by Frankdwu** [comment]
@HarleyPato Do you have some activity for this issue?
