### ISSUE TITLE
Failed to build snap file with exit code 2 on "make -j8"

### ISSUE THREAD

**Issue by ZZZXXX0110** [anbox/anbox#1050]
**Please describe your problem:**
Unable to build snap installer from source with current version, error message:

cc1plus: all warnings being treated as errors
make[5]: *** [CMakeFiles/gmock_main.dir/build.make:89: CMakeFiles/gmock_main.dir/src/gmock_main.cc.o] Error 1
make[5]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
make[5]: *** [CMakeFiles/gmock_main.dir/build.make:76: CMakeFiles/gmock_main.dir/src/gmock-all.cc.o] Error 1
cc1plus: all warnings being treated as errors
make[5]: *** [CMakeFiles/gmock.dir/build.make:76: CMakeFiles/gmock.dir/src/gmock-all.cc.o] Error 1
make[5]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
make[5]: *** [CMakeFiles/gmock_main.dir/build.make:63: CMakeFiles/gmock_main.dir/usr/src/googletest/googletest/src/gtest-all.cc.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:73: CMakeFiles/gmock_main.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
make[5]: *** [gtest/CMakeFiles/gtest.dir/build.make:63: gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:204: gtest/CMakeFiles/gtest.dir/all] Error 2
cc1plus: all warnings being treated as errors
make[5]: *** [CMakeFiles/gmock.dir/build.make:63: CMakeFiles/gmock.dir/usr/src/googletest/googletest/src/gtest-all.cc.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:110: CMakeFiles/gmock.dir/all] Error 2
make[3]: *** [Makefile:130: all] Error 2
make[2]: *** [CMakeFiles/GMock.dir/build.make:111: GMock-prefix/src/GMock-stamp/GMock-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:649: CMakeFiles/GMock.dir/all] Error 2
cc1plus: all warnings being treated as errors
make[2]: *** [external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/build.make:76: external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/posix/child_process.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1104: external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Failed to run 'make -j8' for 'anbox': Exited with code 2.

Verify that the part is using the correct parameters and try again. 
**What were you expecting?:**
Build process able to complete itself.

**Additional info:**

**Comment by ZZZXXX0110** [comment]
Here are more logs on a different computer that gives similar error:

[ 27%] Performing build step for 'GMock'
cc1plus: all warnings being treated as errors
make[2]: *** [external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/build.make:76: external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/posix/child_process.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Scanning dependencies of target gtest
Scanning dependencies of target gmock_main
Scanning dependencies of target gmock
[  9%] Building CXX object gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
make[1]: *** [CMakeFiles/Makefile2:1104: external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/all] Error 2
[ 18%] Building CXX object CMakeFiles/gmock.dir/usr/src/googletest/googletest/src/gtest-all.cc.o
[ 27%] Building CXX object CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
[ 36%] Building CXX object CMakeFiles/gmock_main.dir/src/gmock-all.cc.o
[ 45%] Building CXX object CMakeFiles/gmock.dir/src/gmock-all.cc.o
[ 54%] Building CXX object CMakeFiles/gmock_main.dir/usr/src/googletest/googletest/src/gtest-all.cc.o
In file included from /usr/src/googletest/googletest/src/gtest.cc:63:0,
                 from /usr/src/googletest/googletest/src/gtest-all.cc:42:
/mnt/Programs/anbox/parts/anbox/install/usr/include/limits.h:124:3: error: #include_next is a GCC extension [-Werror]
 # include_next <limits.h>
   ^~~~~~~~~~~~
In file included from /usr/src/googletest/googlemock/include/gmock/gmock-cardinalities.h:41:0,
                 from /usr/src/googletest/googlemock/include/gmock/gmock.h:59,
                 from /usr/src/googletest/googlemock/src/gmock-all.cc:40:
/mnt/Programs/anbox/parts/anbox/install/usr/include/limits.h:124:3: error: #include_next is a GCC extension [-Werror]
 # include_next <limits.h>
   ^~~~~~~~~~~~
In file included from /usr/src/googletest/googlemock/include/gmock/gmock-cardinalities.h:41:0,
                 from /usr/src/googletest/googlemock/include/gmock/gmock.h:59,
                 from /usr/src/googletest/googlemock/src/gmock_main.cc:33:
/mnt/Programs/anbox/parts/anbox/install/usr/include/limits.h:124:3: error: #include_next is a GCC extension [-Werror]
 # include_next <limits.h>
   ^~~~~~~~~~~~
In file included from /usr/src/googletest/googlemock/include/gmock/gmock-cardinalities.h:41:0,
                 from /usr/src/googletest/googlemock/include/gmock/gmock.h:59,
                 from /usr/src/googletest/googlemock/src/gmock-all.cc:40:
/mnt/Programs/anbox/parts/anbox/install/usr/include/limits.h:124:3: error: #include_next is a GCC extension [-Werror]
 # include_next <limits.h>
   ^~~~~~~~~~~~
In file included from /usr/src/googletest/googletest/src/gtest.cc:63:0,
                 from /usr/src/googletest/googletest/src/gtest-all.cc:42:
/mnt/Programs/anbox/parts/anbox/install/usr/include/limits.h:124:3: error: #include_next is a GCC extension [-Werror]
 # include_next <limits.h>
   ^~~~~~~~~~~~
In file included from /usr/src/googletest/googletest/src/gtest.cc:63:0,
                 from /usr/src/googletest/googletest/src/gtest-all.cc:42:
/mnt/Programs/anbox/parts/anbox/install/usr/include/limits.h:124:3: error: #include_next is a GCC extension [-Werror]
 # include_next <limits.h>
   ^~~~~~~~~~~~
In file included from /mnt/Programs/anbox/parts/anbox/install/usr/include/features.h:424:0,
                 from /mnt/Programs/anbox/parts/anbox/install/usr/include/errno.h:25,
                 from /usr/src/googletest/googlemock/include/gmock/gmock-actions.h:40,
                 from /usr/src/googletest/googlemock/include/gmock/gmock.h:58,
                 from /usr/src/googletest/googlemock/src/gmock-all.cc:40:
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/sys/cdefs.h:293:63: error: ‘int stat(const char*, stat*)’ hides constructor for ‘struct stat’ [-Werror=shadow]
 # define __nonnull(params) __attribute__ ((__nonnull__ params))
                                                               ^
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/sys/stat.h:206:43: note: in expansion of macro ‘__nonnull’
    struct stat *__restrict __buf) __THROW __nonnull ((1, 2));
                                           ^~~~~~~~~
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/sys/cdefs.h:293:63: error: ‘int stat64(const char*, stat64*)’ hides constructor for ‘struct stat64’ [-Werror=shadow]
 # define __nonnull(params) __attribute__ ((__nonnull__ params))
                                                               ^
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/sys/stat.h:225:47: note: in expansion of macro ‘__nonnull’
      struct stat64 *__restrict __buf) __THROW __nonnull ((1, 2));
                                               ^~~~~~~~~
In file included from /mnt/Programs/anbox/parts/anbox/install/usr/include/features.h:424:0,
                 from /mnt/Programs/anbox/parts/anbox/install/usr/include/errno.h:25,
                 from /usr/src/googletest/googlemock/include/gmock/gmock-actions.h:40,
                 from /usr/src/googletest/googlemock/include/gmock/gmock.h:58,
                 from /usr/src/googletest/googlemock/src/gmock-all.cc:40:
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/sys/cdefs.h:293:63: error: ‘int stat(const char*, stat*)’ hides constructor for ‘struct stat’ [-Werror=shadow]
 # define __nonnull(params) __attribute__ ((__nonnull__ params))
                                                               ^
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/sys/stat.h:206:43: note: in expansion of macro ‘__nonnull’
    struct stat *__restrict __buf) __THROW __nonnull ((1, 2));
                                           ^~~~~~~~~
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/sys/cdefs.h:293:63: error: ‘int stat64(const char*, stat64*)’ hides constructor for ‘struct stat64’ [-Werror=shadow]
 # define __nonnull(params) __attribute__ ((__nonnull__ params))
                                                               ^
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/sys/stat.h:225:47: note: in expansion of macro ‘__nonnull’
      struct stat64 *__restrict __buf) __THROW __nonnull ((1, 2));
                                               ^~~~~~~~~
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/sys/cdefs.h:293:63: error: ‘int statx(int, const char*, int, unsigned int, statx*)’ hides constructor for ‘struct statx’ [-Werror=shadow]
 # define __nonnull(params) __attribute__ ((__nonnull__ params))
                                                               ^
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/bits/statx.h:89:11: note: in expansion of macro ‘__nonnull’
   __THROW __nonnull ((2, 5));
           ^~~~~~~~~
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/sys/cdefs.h:293:63: error: ‘int statx(int, const char*, int, unsigned int, statx*)’ hides constructor for ‘struct statx’ [-Werror=shadow]
 # define __nonnull(params) __attribute__ ((__nonnull__ params))
                                                               ^
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/bits/statx.h:89:11: note: in expansion of macro ‘__nonnull’
   __THROW __nonnull ((2, 5));
           ^~~~~~~~~
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/sys/cdefs.h:61:27: error: ‘int sigaction(int, const sigaction*, sigaction*)’ hides constructor for ‘struct sigaction’ [-Werror=shadow]
 #   define __THROW throw ()
                           ^
/mnt/Programs/anbox/parts/anbox/install/usr/include/signal.h:241:46: note: in expansion of macro ‘__THROW’
         struct sigaction *__restrict __oact) __THROW;
                                              ^~~~~~~
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/sys/cdefs.h:61:27: error: ‘int sigaction(int, const sigaction*, sigaction*)’ hides constructor for ‘struct sigaction’ [-Werror=shadow]
 #   define __THROW throw ()
                           ^
/mnt/Programs/anbox/parts/anbox/install/usr/include/signal.h:241:46: note: in expansion of macro ‘__THROW’
         struct sigaction *__restrict __oact) __THROW;
                                              ^~~~~~~
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/sys/cdefs.h:251:66: error: ‘int sigstack(sigstack*, sigstack*)’ hides constructor for ‘struct sigstack’ [-Werror=shadow]
 # define __attribute_deprecated__ __attribute__ ((__deprecated__))
                                                                  ^
/mnt/Programs/anbox/parts/anbox/install/usr/include/signal.h:336:14: note: in expansion of macro ‘__attribute_deprecated__’
      __THROW __attribute_deprecated__;
              ^~~~~~~~~~~~~~~~~~~~~~~~
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/sys/cdefs.h:251:66: error: ‘int sigstack(sigstack*, sigstack*)’ hides constructor for ‘struct sigstack’ [-Werror=shadow]
 # define __attribute_deprecated__ __attribute__ ((__deprecated__))
                                                                  ^
/mnt/Programs/anbox/parts/anbox/install/usr/include/signal.h:336:14: note: in expansion of macro ‘__attribute_deprecated__’
      __THROW __attribute_deprecated__;
              ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/bits/fcntl.h:61:0,
                 from /mnt/Programs/anbox/parts/anbox/install/usr/include/fcntl.h:35,
                 from /usr/src/googletest/googletest/src/gtest.cc:62,
                 from /usr/src/googletest/googletest/src/gtest-all.cc:42:
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h:355:27: error: ISO C++ forbids zero-size array ‘f_handle’ [-Werror=pedantic]
   unsigned char f_handle[0];
                           ^
In file included from /mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/bits/fcntl.h:61:0,
                 from /mnt/Programs/anbox/parts/anbox/install/usr/include/fcntl.h:35,
                 from /usr/src/googletest/googletest/src/gtest.cc:62,
                 from /usr/src/googletest/googletest/src/gtest-all.cc:42:
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h:355:27: error: ISO C++ forbids zero-size array ‘f_handle’ [-Werror=pedantic]
   unsigned char f_handle[0];
                           ^
In file included from /mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/bits/fcntl.h:61:0,
                 from /mnt/Programs/anbox/parts/anbox/install/usr/include/fcntl.h:35,
                 from /usr/src/googletest/googletest/src/gtest.cc:62,
                 from /usr/src/googletest/googletest/src/gtest-all.cc:42:
/mnt/Programs/anbox/parts/anbox/install/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h:355:27: error: ISO C++ forbids zero-size array ‘f_handle’ [-Werror=pedantic]
   unsigned char f_handle[0];
                           ^
cc1plus: all warnings being treated as errors
make[5]: *** [CMakeFiles/gmock_main.dir/build.make:89: CMakeFiles/gmock_main.dir/src/gmock_main.cc.o] Error 1
make[5]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
make[5]: *** [CMakeFiles/gmock.dir/build.make:76: CMakeFiles/gmock.dir/src/gmock-all.cc.o] Error 1
make[5]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
make[5]: *** [CMakeFiles/gmock_main.dir/build.make:76: CMakeFiles/gmock_main.dir/src/gmock-all.cc.o] Error 1
cc1plus: all warnings being treated as errors
make[5]: *** [gtest/CMakeFiles/gtest.dir/build.make:63: gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:204: gtest/CMakeFiles/gtest.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
cc1plus: all warnings being treated as errors
make[5]: *** [CMakeFiles/gmock.dir/build.make:63: CMakeFiles/gmock.dir/usr/src/googletest/googletest/src/gtest-all.cc.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:110: CMakeFiles/gmock.dir/all] Error 2
make[5]: *** [CMakeFiles/gmock_main.dir/build.make:63: CMakeFiles/gmock_main.dir/usr/src/googletest/googletest/src/gtest-all.cc.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:73: CMakeFiles/gmock_main.dir/all] Error 2
make[3]: *** [Makefile:130: all] Error 2
make[2]: *** [CMakeFiles/GMock.dir/build.make:111: GMock-prefix/src/GMock-stamp/GMock-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:649: CMakeFiles/GMock.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Failed to run 'make -j12' for 'anbox': Exited with code 2.
Verify that the part is using the correct parameters and try again.

**Comment by HarleyPato** [comment]
Well.

`cc1plus: all warnings being treated as errors`

There you have. Edit the CMakeLists.txt in /path/to/anbox (or /path/to/anbox/src/anbox) and search for the flag -Werror, then remove it or just replace it for -Wno-Error instead (that's what I did and it worked for me).

Then try again.

Greetings!

**Comment by ZZZXXX0110** [comment]
> Well.
> 
> `cc1plus: all warnings being treated as errors`
> 
> There you have. Edit the CMakeLists.txt in /path/to/anbox (or /path/to/anbox/src/anbox) and search for the flag -Werror, then remove it or just replace it for -Wno-Error instead (that's what I did and it worked for me).
> 
> Then try again.
> 
> Greetings!

Thank you for the response!
I have no CMakeList.txt file in /path/to/anbox/src/anbox
I'm still getting the same error after modifying the CMakeList.txt in /path/to/anbox  :/

**Comment by ZZZXXX0110** [comment]
I do get simpler error output at least, now it's simply these:

[100%] Linking CXX static library libgtest_main.a
[100%] Built target gtest_main
[ 30%] No install step for 'GMock'
[ 31%] Completed 'GMock'
[ 31%] Built target GMock
make: *** [Makefile:141: all] Error 2
Failed to run 'make -j12' for 'anbox': Exited with code 2.
Verify that the part is using the correct parameters and try again.

**Comment by ZZZXXX0110** [comment]
Here's a similar error on another computer:
```
[100%] Linking CXX static library libgtest_main.a
[100%] Built target gtest_main
[ 21%] No install step for 'GMock'
[ 22%] Completed 'GMock'
[ 22%] Built target GMock
make: *** [Makefile:141: all] Error 2
Failed to run 'make -j8' for 'anbox': Exited with code 2.
Verify that the part is using the correct parameters and try again.
```

**Comment by HarleyPato** [comment]
I see. :shrek:

Well if I were you I would use the command `snapcraft` in order to build the snap. You're just building the anbox part. That sounds like a mess to me. :>

As I said run `snapcraft` in the Terminal.

You have to get rid of this part:

if (${Werror})
    message(STATUS "Treat warnings as errors")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Werror")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")
  if ("${cmake_build_type_lower}" STREQUAL "release" OR "${cmake_build_type_lower}" STREQUAL "relwithdebinfo")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-error=deprecated-declarations")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-error=deprecated-declarations")
  endif()
endif()

And use this instead:

if (${Werror})
    message(STATUS "Treat warnings as errors")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-error")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-error")
  if ("${cmake_build_type_lower}" STREQUAL "release" OR "${cmake_build_type_lower}" STREQUAL "relwithdebinfo")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-error=deprecated-declarations")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-error=deprecated-declarations")
  endif()
endif()

Greetings!

**Comment by ZZZXXX0110** [comment]
> @ZZZXXX0110
> 
> I see. :shrek:
> 
> Well if I were you I would use the command `snapcraft` in order to build the snap. You're just building the anbox part. That sounds like a mess to me. :>
> 
> As I said run `snapcraft` in the Terminal.
> 
> You have to get rid of this part:
> 
> if (${Werror})
> message(STATUS "Treat warnings as errors")
> set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Werror")
> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")
> if ("${cmake_build_type_lower}" STREQUAL "release" OR "${cmake_build_type_lower}" STREQUAL "relwithdebinfo")
> set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-error=deprecated-declarations")
> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-error=deprecated-declarations")
> endif()
> endif()
> 
> And use this instead:
> 
> if (${Werror})
> message(STATUS "Treat warnings as errors")
> set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-error")
> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-error")
> if ("${cmake_build_type_lower}" STREQUAL "release" OR "${cmake_build_type_lower}" STREQUAL "relwithdebinfo")
> set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-error=deprecated-declarations")
> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-error=deprecated-declarations")
> endif()
> endif()
> 
> So that warnings will be treated as such, warnings.
> 
> Greetings!

I am indeed using "snapcraft", and I did exactly the same changes to the CMakeList.txt.

I'm running snapcraft in the anbox root folder though, did I miss anything there?

**Comment by HarleyPato** [comment]
Try git cloning it again and try with the changed I just posted above then.

**Comment by ZZZXXX0110** [comment]
Exactly the same error :(
