### ISSUE TITLE
When building snap package on Ubuntu 18.10, it requires obsolete packages that cannot be found.

### ISSUE THREAD

**Issue by ZZZXXX0110** [anbox/anbox#1051]
**Please describe your problem:**
When attempt to build snap package on Ubuntu 18.10, it requires obsolete packages such as "libboost-iostreams1.58.0", which is already replaced with newer versions in the repository, and thus it cannot find the packages, and give an error message such as this:

Failed to fetch stage packages: Error downloading packages for part 'anbox': The package 'libboost-iostreams1.58.0' was not found..

**What were you expecting?:**
Build process to complete successfully.

**Additional info:**

**Comment by HarleyPato** [comment]
Change them in your snapcraft.

**Comment by artivision** [comment]
Hello how can i fix liboost.58 with binaries from Edge? I have 69.
