### ISSUE TITLE
Snapshot Support?

### ISSUE THREAD

**Issue by afjoseph** [anbox/anbox#1061]
Hey guys. This is more of an inquiry rather than an issue, so forgive me if this is the wrong place to ask.

Is there any snapshot support for Anbox? Can I take a snapshot of the system, do something, and then restore the snapshot to come back to the original point in time? Kinda like how virtualization solutions can take "snapshots" of different points and states in time?

**Comment by baptx** [comment]
+1 this would be useful to use WhatsApp with several phone numbers.
Related: https://github.com/anbox/anbox/issues/1008 https://github.com/anbox/anbox/issues/1038

**Comment by rizzini** [comment]
You can setup multiple Anbox configurations playing with the `/var/snap/anbox/common` folder.

All constumized settings and files are located at `/var/snap/anbox/common`. You can mess around with it no problem. For example, If you delete the `commom` folder and restart the anbox it will be created again from scratch. It's like a Factory data reset(https://cdn57.androidauthority.net/wp-content/uploads/2017/05/Samsung-Galaxy-S8-reset-screenshot-AA-2-copy.jpg).

I'll give here my case:

I needed a scenario that allows me to switch beteween two Anbox setups that I created. One with Whatsapp and the other one with an app called Happn. I didn't want the two apps together for personal and practical reasons. 

With that in mind I created a script that switch the `/var/snap/anbox/common` folder for the `common` I created before with the respective setups, Whatsapp or Happn.


```
#!/bin/bash

happn_or_whatsapp=$(sudo find  /var/snap/anbox/common -type d -name *com.ftw_and_co.happn*)

if [ -z "$happn_or_whatsapp" ]
then
    happn_or_whatsapp="happn"
else
   happn_or_whatsapp="whatsapp"
fi


case "$happn_or_whatsapp" in
    happn)
        kdesu -c  "snap stop anbox.container-manager; tar cpf /var/snap/anbox/whatsapp.tar.gz /var/snap/anbox/common; rm -Rf /var/snap/anbox/common; tar xf /var/snap/anbox/happn.tar.gz -C /; snap start anbox.container-manager"
        if [ $? = 0 ]
        then    
            temp=$(cat ~/.config/kwinrulesrc  | sed -e "s/desktop=2/\desktop=1\ /g")
            echo "$temp" > ~/.config/kwinrulesrc
            chmod 400 ~/.config/kwinrulesrc
            kwin --replace &
            sleep 1 &&
            chmod 600 ~/.config/kwinrulesrc
            kstart --desktop 1 anbox session-manager --single-window --window-size=800,800
        fi
    ;;
    whatsapp)
        kdesu -c "snap stop anbox.container-manager; tar cpf /var/snap/anbox/happn.tar.gz /var/snap/anbox/common; rm -Rf /var/snap/anbox/common; tar xf /var/snap/anbox/whatsapp.tar.gz -C /; snap start anbox.container-manager"
        if [ $? = 0 ]
        then        
            temp=$(cat ~/.config/kwinrulesrc | sed -e "s/desktop=1/\desktop=2\ /g"  | sed -e "s/skiptaskbar=true/\skiptaskbar=false\ /g" | sed -e "s/skiptaskbarrule=2/\skiptaskbarrule=0\ /g")
            echo "$temp" > ~/.config/kwinrulesrc
            chmod 400 ~/.config/kwinrulesrc
            kwin --replace &
            sleep 1 &&
            chmod 600 ~/.config/kwinrulesrc
            kstart --skiptaskbar --desktop 2 anbox session-manager --single-window --window-size=800,800
        fi
    ;;
esac
```

**Comment by baptx** [comment]
@rizzini thanks, I did not think about switching the `/var/snap/anbox/common` system folder. But when I switch the folder with another one, I cannot use the new snapshot unless I reboot. I tried command `sudo snap stop anbox` and `sudo snap start anbox` but it only works if I keep the original folder, not the new one. How are you restarting anbox after switching the folder?
I am not using KDE so your kstart command will not work for me.

**Comment by baptx** [comment]
@rizzini thanks, I did not think about switching the `/var/snap/anbox/common` system folder.
I think we can say it is now possible to do a snapshot even if not officially supported with Anbox. Here is how I switch a folder:
`sudo mv /var/snap/anbox/common ~/Documents/anbox/common.bak`
`sudo mv ~/Documents/anbox/common.bak /var/snap/anbox/common`
Then we can stop Anbox with command `sudo snap stop anbox` and start it with command `sudo snap start anbox` (https://github.com/anbox/anbox/issues/933#issuecomment-429625431) before launching anbox through the system shortcut or with a command like `anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity`.

**Comment by baptx** [comment]
@rizzini by the way, how did you make the app Happn work with Anbox? I downloaded it from Aptoide but it freezes when I start it, probably due to a screen rotation like Instagram which fails too.

**Comment by shvchk** [comment]
I've made a [script](https://gist.github.com/shvchk/4e375a7c0a43b7f6e25fc9cdb24e75d6) to easily manage Anbox environments (there's also a [10-lines simplified version](https://gist.github.com/shvchk/461b6a0ab0ef11780a956448125eb6e0), which does roughly the same, just without some precautions, bells and whistles): put it somewhere in your PATH and `anbox-env --help`:

```
Usage: anbox-env [options] NAME
NAME is an environment name, corresponding to existing '/var/snap/anbox/common-NAME' directory

Options:
-c, --clean     Clean Anbox log files from old environment before unplugging
-h, --help      Show this help

Example:
You have 'whatsapp' environment plugged ('/var/snap/anbox/common-whatsapp'),
and wish to clean its logs, unplug and plug 'signal' environment instead:

anbox-env --clean signal

This will stop Anbox service, clean logs from the old environment ('/var/snap/anbox/common-whatsapp'), remove link to old environment from '/var/snap/anbox', create link to new environment and start Anbox.

Since it requires root privileges, use 'sudo anbox-env ...' to launch this script if it's in root's PATH, otherwise use 'pkexec anbox-env ...' or 'sudo env PATH=$PATH anbox-env ...'.
```
