### ISSUE TITLE
COMPATIBILITY:  Can't find correct anbox executable to run. Found /memfd:liblxc (deleted) but does not exist.

### ISSUE THREAD

**Issue by Kreyren** [anbox/anbox#1064]
### Disclaimer: Created new issues since #450 is closed as stale.

Based on https://github.com/anbox/anbox#supported-linux-distributions only ubuntu 16.04 and 18.04 is supported -> Using unsupported OS (Debian buster) by upstream.

---

### ISSUE
I'm having same issue as https://github.com/anbox/anbox/issues/450 on `Linux debian 4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64 GNU/Linux` on `anbox 0.0~git20181210-1-Debian` with those packages http://ix.io/1CJI.

Results in 
```
kreyren@debian:~$ anbox launch
[ 2019-03-06 22:38:20] [launch.cpp:169@operator()] The intent you provided is invalid. Please provide a correct launch intent.
[ 2019-03-06 22:38:20] [launch.cpp:170@operator()] For example to launch the application manager, run:
[ 2019-03-06 22:38:20] [launch.cpp:171@operator()] $ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
```

Suggested command results in:
```
kreyren@debian:~$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[ 2019-03-06 22:38:54] [launch.cpp:71@launch_session_manager] Can't find correct anbox executable to run. Found /memfd:liblxc (deleted) but does not exist
```

---

### Steps to reproduce
- Install `anbox`
- Invoke `anbox launch`

---

#### 01
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923403&fbclid=IwAR0gP56iy6e_esSPu8Wp1p4QtO5dsbd1KhgOORQ3rjFHrpXFw9eiyu-5YtE
> We believe that the bug you reported is fixed in the latest version of
anbox, which is due to be installed in the Debian FTP archive.

From 
```
01> kreyren: I don' tsee how that bug report is related to the cve, this seems to be a different bug
18<0118> also that report says the bug is fixed in 0.0~git20190124-1, which is the current version available in buster.
````

Bug fix not sufficient?

#### 02
https://github.com/anbox/anbox/issues/1057?fbclid=IwAR3NEkXbfsledFSzSKZOYvgr0qLUpoViFVJ2PasRYUfTAI-9odryz2pJakg
> /memfd:liblxc (deleted) but does not exist

Is same error

#### 03
https://linuxaria.com/howto/how-to-install-a-single-package-from-debian-sid-or-debian-testing 
- Testing anbox from *the one who's name shall not be spoken* (Unstable Debian)
- Downloaded from https://packages.debian.org/sid/anbox which results in
```
kreyren@debian:~$ sudo dpkg -i Downloads/anbox_0.0_git20190124-1_amd64.deb 
[sudo] password for kreyren: 
Selecting previously unselected package anbox.
(Reading database ... 238458 files and directories currently installed.)
Preparing to unpack .../anbox_0.0_git20190124-1_amd64.deb ...
Unpacking anbox (0.0~git20190124-1) ...
dpkg: dependency problems prevent configuration of anbox:
 anbox depends on libboost-log1.67.0; however:
  Package libboost-log1.67.0 is not installed.
 anbox depends on libboost-program-options1.67.0; however:
  Package libboost-program-options1.67.0 is not installed.
 anbox depends on libboost-regex1.67.0 (>= 1.67.0-10); however:
  Package libboost-regex1.67.0 is not installed.
 anbox depends on libboost-serialization1.67.0; however:
  Package libboost-serialization1.67.0 is not installed.
 anbox depends on liblxc1 (>= 1:3.0.2); however:
  Package liblxc1 is not installed.
 anbox depends on libsdl2-image-2.0-0 (>= 2.0.2); however:
  Package libsdl2-image-2.0-0 is not installed.
 anbox depends on lxc (>= 1:3.0.0); however:
  Package lxc is not installed.

dpkg: error processing package anbox (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.31.4-3) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 anbox
```

---

#### **CONCLUSION**

Based on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923403&fbclid=IwAR0gP56iy6e_esSPu8Wp1p4QtO5dsbd1KhgOORQ3rjFHrpXFw9eiyu-5YtE the issue is fixed in 'the one who's name shall not be spoken'. -> Should be present in testing in few days.

#### **ALTERNATIVE**:
Install anbox from sid on buster (stable?), using container?

**Comment by zhsj** [comment]
Hi, the Debian package maintainer here. Please wait some days to have the fixed version in buster, since we are in the freeze period, the fixed version in unstable needs 10 days to migrate to buster.

I have opened #1057 already, there is no need to open new one. The fix in Debian is an unsafe workaround, thus the patch is not  proposed in upstream.

**Comment by zhsj** [comment]
And please keep the Debian specific problems on Debian BTS, it's not appreciate to disturb these problems for upstream.

**Comment by Kreyren** [comment]
Obsolete by https://github.com/anbox/anbox/issues/1057 based on https://github.com/anbox/anbox/issues/1064?fbclid=IwAR1Gi5-_4iYzgddkFK8F8zK0iJSvuIV0rNWZViv6iy4RvWeYqeA01yWEebM#issuecomment-470353714.

**Comment by Kreyren** [comment]
> And please keep the Debian specific problems on Debian BTS, it's not appreciate to disturb these problems for upstream.

Noted, mension that you are maintainer next time so that i woudn't have to self-diagnose issues alike. ty
