### ISSUE TITLE
ERROR: could not insert 'ashmem_linux': Operation not permitted

### ISSUE THREAD

**Issue by BoseSean** [anbox/anbox#1070]
I am installing anbox on Ubuntu
```
# cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
And I got the following error:
```
# sudo modprobe ashmem_linux              
[sudo] password for xxx: 
modprobe: ERROR: could not insert 'ashmem_linux': Operation not permitted

# sudo modprobe binder_linux
modprobe: ERROR: could not insert 'binder_linux': Operation not permitted
```
How should I solve the problem?

**Comment by Maniumn** [comment]
Same issue on xubuntu 18.04
I have followed the guide https://docs.anbox.io/userguide/install_kernel_modules.html

**Comment by penfold45** [comment]
I have the same problem :(

**Comment by aroslanov** [comment]
Same problem here. Ubuntu 18.04 lts.

**Comment by aroslanov** [comment]
Found workaround here: https://wiki.ubuntu.com/UEFI/SecureBoot/DKMS

**Comment by BoseSean** [comment]
> Found workaround here: https://wiki.ubuntu.com/UEFI/SecureBoot/DKMS

Thanks. Solved!

**Comment by ernestomonroy** [comment]
Is the only way to disable secure boot?

**Comment by ljr** [comment]
> Is the only way to disable secure boot?

You can sign the module by yourself:

    kmodsign sha512 /var/lib/shim-signed/mok/MOK.priv /var/lib/shim-signed/mok/MOK.der /lib/modules/`uname -r`/kernel/drivers/staging/android/ashmem_linux.ko

However, I suggest use the `anbox-modules-dkms`, see:

    https://github.com/anbox/anbox/blob/master/docs/install.md

**Comment by bgalvao** [comment]
from https://wiki.ubuntu.com/UEFI/SecureBoot/DKMS

> Simply install the package you need. Packages that make use of DKMS should prompt you to create a new Machine-Owner key (it will be done for you), and will guide you through the steps to enroll that key in your system's firmware.

So, was `anbox-modules-dkms` supposed to prompt? I did not see anything from the terminal
