### ISSUE TITLE
archlinux adb install apk failure

### ISSUE THREAD

**Issue by vamur** [anbox/anbox#108]
On Archlinux, running adb install VLC-Android-2.0.6-x86_64.apk

`Failed to install VLC-Android-2.0.6-x86_64.apk: Error: failed to write; posix_fallocate failed: ENOTSUP (Operation not supported on transport endpoint)`

and 'install VLC-Android-2.0.6-x86_64.apk'

`java.lang.IllegalStateException: No suitable external storage available`

In adb /storage is mounted to tmpfs

**Comment by JTG7600** [comment]
Hey Vamur,

I am getting the exact same issue, did you manage to solve it? I been searching for a solution without much success. Any tips you can throw my way? Cheers!

**Comment by asm2620** [comment]
I have this problem in Ubuntu 17.04,
with any apks
```

mohammad@mohammadpc:~/Downloads$ adb install Bazaar-7.12.1.apk 
Failed to install Bazaar-7.12.1.apk: Error: failed to write; posix_fallocate failed: ENOTSUP (Operation not supported on transport endpoint)

```

**Comment by morphis** [comment]
> Error: failed to write; posix_fallocate failed: ENOTSUP (Operation not supported on transport endpoint)

Whoever gets this is running his system on a filesystem which doesn't support the `posix_fallocate` operation. See http://man7.org/linux/man-pages/man3/posix_fallocate.3.html for details. ZFS is one of these. 

Android requires `posix_fallocate` to be implemented for certain system operations.

There is not much Anbox can do to help you with this problem. Easiest way to solve this problem is to migrate /var/snap/ onto a non ZFS partition or loop back mounted file (will decrease performance in some use cases).

**Comment by asm2620** [comment]
Thanks, But I didn't undrestand what must I do,
My /var is a part of my root partition and It's ext3.
I have to change it?
What I have to do?
```
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
/dev/sda8 on / type ext3 (rw,relatime,errors=remount-ro,data=ordered)
/var/lib/snapd/snaps/core_2774.snap on /snap/core/2774 type squashfs (ro,relatime)
/var/lib/snapd/snaps/anbox_60.snap on /snap/anbox/60 type squashfs (ro,nodev,relatime)
tmpfs on /run/user/120 type tmpfs (rw,nosuid,nodev,relatime,size=400324k,mode=700,uid=120,gid=127)
tmpfs on /run/snapd/ns type tmpfs (rw,nosuid,noexec,relatime,size=400328k,mode=755)
nsfs on /run/snapd/ns/anbox.mnt type nsfs (rw)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=400324k,mode=700,uid=1000,gid=1000)
```

**Comment by tuxflo** [comment]
Happens to me too, running anbox with an standard ext3 Filesystem so I'm not sure this is a "ZFS only" issue.

**Comment by Pastens** [comment]
Happens to me too, running with a standard ext4 Filesystem on Ubuntu 16.04.3 LTS.

**Comment by emorice** [comment]
Happened here too, on an ext3 filesystem on Debian 9.3 .

**Solved** :
Apparently, ext3 does not support fallocate and/or posix_fallocate though I cannot find reliable information about it. Wherever I am on my system I can reproduce : 
```
$ fallocate -l 1 foo
fallocate: fallocate failed: Operation not supported
```

Once this fact was established, the workaround proposed by @morphis did the thing : creating an ext4 filesystem (for instance) in a loop back mounted file and using it as the --data-path for container-manager solved the issue.
