### ISSUE TITLE
mimic device behaviour 

### ISSUE THREAD

**Issue by molekel** [anbox/anbox#1082]
google play doesnt allow installing their apps on anbox. 
fdroid works ...
Maybe this could be improved by mimicking a specific device.

**Comment by tuxflo** [comment]
Emulating devices does not change the expected behavior from Google Play Store and services. However it is possible to get the services running as explained here: https://www.linuxuprising.com/2018/07/anbox-how-to-install-google-play-store.html (also check the related links in the article).

**Comment by molekel** [comment]
ok haven't tried yet but thanks

**Comment by molekel** [comment]
however i don't have to use playstore. either install apk or use
