### ISSUE TITLE
'[daemon.cpp:61@Run] Failed to connect to DBus' error

### ISSUE THREAD

**Issue by Londino** [anbox/anbox#1088]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `
[anbox-system-diagnostics-2019-03-27.zip](https://github.com/anbox/anbox/files/3015025/anbox-system-diagnostics-2019-03-27.zip)

6. ** Please paste the result of `anbox system-info` below:**
```
I think this is included in the attached zip file so i'll skip pasting it for now.
```

**Please describe your problem:**
Can't seem to be able to launch Anbox. It is not even in my start manager. Also, the path must be misconfigured as i get 'anbox: command not found' error everytime i try to launch it via cmd with my user whereas if i try doing the same as root i get '[daemon.cpp:61@Run] Failed to connect to DBus' error

**What were you expecting?:**
To be able to launch anbox although not entirely sure how to go about it.

**Additional info:**
If it helps, the only alarming output during install was the following:
```
DKMS: install completed.
Setting up linux-headers-4.4.0-143 (4.4.0-143.169) ...
Setting up linux-headers-4.4.0-143-generic (4.4.0-143.169) ...
/etc/kernel/header_postinst.d/dkms:
Error! Bad return status for module build on kernel: 4.4.0-143-generic (x86_64)
Consult /var/lib/dkms/nvidia-384/384.130/build/make.log for more information.
Setting up linux-headers-generic (4.4.0.143.151) ...
```

**Comment by sheldonmaschmeyer** [comment]
Check that you are not running anbox.appmgr as root (it must be run in the local user environment). When you run as sudo, the error occurs. Also, if you are logged into snapcraft from ubuntu software, you don't have to run refresh --devmode --edge anbox or install --devmode --edge anbox as sudo. Try removing anbox and installing again, without sudo.

**Comment by Londino** [comment]
Wow! Can't believe that a simple thing such as running the command in local environment did the trick! I can now even see it in my start manager's list of applications. Thanks a bunch! Will now give this a test-run :-)
