### ISSUE TITLE
installing Failed Ubunto 19.04  Disco Dingo (development branch)

### ISSUE THREAD

**Issue by arashsoftco** [anbox/anbox#1091]
first i try to install using Ubuntu store but when i run i will close just showing loading screen(starting......)
then i try to install using snap but
necessary kernel modules doesn't Release (look likes)
V: 0.0~git20190124-1
Err:5 http://ppa.launchpad.net/morphis/anbox-support/ubuntu disco Release
  404  Not Found [IP: 91.189.95.83 80]
Hit:6 http://ir.archive.ubuntu.com/ubuntu disco-backports InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu disco Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

After installing by snap :
snap info anbox
name:      anbox
summary:   Android in a Box
publisher: morphis
contact:   https://anbox.io
license:   unset
description: |
  Runtime for Android applications which runs a full Android system
  in a container using Linux namespaces (user, ipc, net, mount) to
  separate the Android system fully from the host.
  
  You can find further details in our documentation at
  https://github.com/anbox/anbox/blob/master/README.md
commands:
  - anbox
  - anbox.android-settings
  - anbox.appmgr
  - anbox.collect-bug-info
  - anbox.shell
services:
  anbox.container-manager: simple, enabled, active
snap-id:      Nr9K6UJaIOD8wHpDEQl16nabFFt9LLEQ
tracking:     beta
refresh-date: today at 11:57 +0430
channels:
  stable:    –                                
  candidate: –                                
  beta:      4-e1ecd04 2018-10-17 (158) 391MB devmode
  edge:      4-d521e28 2019-03-13 (173) 391MB devmode
installed:   4-e1ecd04            (158) 391MB devmode

*** When I run it still have crash just showing starting... then exit

**Comment by neb15161718** [comment]
go to software an updates and set the distro for the anbox ppa to bionic

**Comment by marataziat** [comment]
try this https://github.com/anbox/anbox/issues/1096#issuecomment-480560409

**Comment by arashsoftco** [comment]
> distro

Tnx  ¯\_(ツ)_/¯

**Comment by arashsoftco** [comment]
> try this [#1096 (comment)](https://github.com/anbox/anbox/issues/1096#issuecomment-480560409)

I also test this solution it works too 
Tnx
Anbox started but have this problem when : **### apt-get update**
: 
`
arashsoft@arashsoft-X456UR:~$ sudo apt-get update
Hit:1 http://ir.archive.ubuntu.com/ubuntu disco InRelease
Hit:2 http://ir.archive.ubuntu.com/ubuntu disco-updates InRelease        
Hit:3 http://ir.archive.ubuntu.com/ubuntu disco-backports InRelease      
Hit:4 http://security.ubuntu.com/ubuntu disco-security InRelease
Hit:5 http://ppa.launchpad.net/morphis/anbox-support/ubuntu cosmic InRelease
Ign:6 http://ppa.launchpad.net/morphis/anbox-support/ubuntu disco InRelease
Hit:7 http://ppa.launchpad.net/obsproject/obs-studio/ubuntu disco InRelease
Ign:8 http://ppa.launchpad.net/slgobinath/uget-chrome-wrapper/ubuntu disco InRelease
Err:9 http://ppa.launchpad.net/morphis/anbox-support/ubuntu disco Release
  404  Not Found [IP: 91.189.95.83 80]
Err:10 http://ppa.launchpad.net/slgobinath/uget-chrome-wrapper/ubuntu disco Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu disco Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/slgobinath/uget-chrome-wrapper/ubuntu disco Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

**Comment by lovetocode999** [comment]
I had the same exact problem! To fix it you have to replace the word disco with the word bionic in /etc/apt/sources.list.d/morphis-ubuntu-anbox-support-disco.list and /etc/apt/sources.list.d/morphis-ubuntu-anbox-support-disco.list.save
Afterward, the files should look something like this
```
deb http://ppa.launchpad.net/morphis/anbox-support/ubuntu zesty main
# deb-src http://ppa.launchpad.net/morphis/anbox-support/ubuntu zesty main
deb http://ppa.launchpad.net/morphis/anbox-support/ubuntu bionic main
# deb-src http://ppa.launchpad.net/morphis/anbox-support/ubuntu bionic main
```
Once you have fixed the files, proceed with installation normally.

**Comment by SmartBoy84** [comment]
Any progress?

**Comment by arashsoftco** [comment]
nop
