### ISSUE TITLE
Installation fails on ubuntu 19.04

### ISSUE THREAD

**Issue by neb15161718** [anbox/anbox#1093]
When I try to install anbox on ubuntu 19.04 I get an error: e: the repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu disco release' does not have a release file.

Can you fix the install on 19.04?

**Comment by rizzini** [comment]
Add this to your sources.list:
`deb http://ppa.launchpad.net/morphis/anbox-support/ubuntu/ cosmic main`
