### ISSUE TITLE
Can't set lock screen

### ISSUE THREAD

**Issue by marataziat** [anbox/anbox#1098]
![Screenshot from 2019-04-07 12-21-46](https://user-images.githubusercontent.com/18484996/55683561-c3cff980-5930-11e9-8d75-c45747a8bb12.png)
![Screenshot from 2019-04-07 12-21-27](https://user-images.githubusercontent.com/18484996/55683574-d77b6000-5930-11e9-9b78-168ba294edc4.png)
I can't set any security, How to bypass it? Anbox makes infinite loading when I set password / pin  :(

**Comment by marataziat** [comment]
http://dpaste.com/3G3EV8C crash log!

**Comment by baptx** [comment]
Same problem, I cannot set a PIN or password and this is needed to install mitmproxy CA certificate. Is there a workaround to set the PIN / password or directly install a CA certificate?

**Comment by marataziat** [comment]
Nope, you must have root to put certs to authorities ssl directory. But anbox dont have root :) even with su you cant put them to the ssl directory
