### ISSUE TITLE
Waze crashing at start-up

### ISSUE THREAD

**Issue by Flyman81** [anbox/anbox#1099]
Hello,

I installed Anbox on a fresh install of Ubports for Nexus 5 (16.04 stable channel).
Then I installed the latest stable apk of Waze (4.49.1.2) but it keeps crashing at start-up.

At the beginning I had a pop-up asking to grant access to localization that I was unable to accept (it had no effect when clicking) but I went around this allowing directly rights to Waze in anbox settings.

Now I'm passed that, but Anbox is looping a couple of time at Waze start-up, the last display shows the lower bar of Waze, but then it crashes definitively.
I tried several times, after reboot as well: same behavior.

I hope there is a way to make Waze work on Anbox, it is really the only application that is missing for me on Ubuntu Touch.

I think it is easy and systematic to reproduce but let me know if you need any more data from me.

FYI I already reported this issue on ubports side in anbox section, but I had no feedback : https://github.com/ubports/anbox/issues/35

As I just tried Sailfish on another phone and Waze is working just fine there, I would like to know if Waze should work soon with Anbox on UT, or if I should take the Sailfish option as well.

Thanks in advance for your support!

**Comment by zvova7890** [comment]
Hello guys. I have good news! I have run Waze successfully on my arch linux:

1. For some reason, MESA doesn't like EGL_SAMPLE_BUFFERS attribute and always fail context. But Waze using that attribute, and always fail on my system. With nvidia it some how works. I'm create patch that remove this attribute from the context creation [fix-sample-buffers.txt](https://github.com/anbox/anbox/files/5276361/fix-sample-buffers.txt)
2. Waze require ARM architecture, and doesn't run on pure x86 hardware, it's require emulation layer like houdini. This arch pkgbuild already has this features with builin gapps https://aur.archlinux.org/packages/anbox-image-gapps/. After installation we need register in binfmt subsystem our emulation layers. It can be done by simply writing /proc/sys/fs/binfmt_misc/register this lines(with root)
`
:arm_exe:M::\x7f\x45\x4c\x46\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28::/system/lib/arm/houdini:P
:arm_dyn:M::\x7f\x45\x4c\x46\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x28::/system/lib/arm/houdini:P
:arm64_exe:M::\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7::/system/lib64/arm64/houdini64:P
:arm64_dyn:M::\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\xb7::/system/lib64/arm64/houdini64:P
`
OR if you want permanent effect - just create /etc/binfmt.d/anbox.conf and paste this lines. Also, don't forget restart systemd-binfmt or reboot the system.
3. Then run container and session manager, go to settings -> apps -> find google services and google play and check all permissions to true
4. Sign in google account, and install Waze from play store. It's important, waze doesn't show maps without this
5. Finally, run Waze :)

![Screenshot_20200924_163014](https://user-images.githubusercontent.com/15130560/94151606-492bce80-fe83-11ea-964f-3abd6c09ad4a.png)
