### ISSUE TITLE
Why I'm root, but I get Operation not permitted?

### ISSUE THREAD

**Issue by marataziat** [anbox/anbox#1100]
```
1|x86_64:/system/etc/security/cacerts # mount -o rw,remount -t yaffs2 /dev/loop12                                                                                 
mount: '/dev/loop12'->'/': Operation not permitted
1|x86_64:/system/etc/security/cacerts # whami
/system/bin/sh: whami: not found
127|x86_64:/system/etc/security/cacerts # whoami                                                                                                                  
root
x86_64:/system/etc/security/cacerts # 
```
I'm root, why I cant edit /dev/loop12?

**Comment by ipfgao** [comment]
it's not real root.

**Comment by baptx** [comment]
Is it planned to have a real root account so we can install SSL certificates in `/system/etc/security/cacerts/`?

**Comment by morphis** [comment]
We run Android in an unprivileged container where root is mapped to an unprivileged user ID on the host. If you want to change `/system/etc/security/cacerts/`, have a look at https://docs.anbox.io/userguide/advanced/rootfs_overlay.html
