### ISSUE TITLE
can't install .apk app

### ISSUE THREAD

**Issue by tranhoaison** [anbox/anbox#1107]
Hello,

i can't install this app: https://github.com/anyonecore/AnyoneBinary/releases/download/0.16.3.1/Anyone-3.3.4.0.apk

when i run: adb install Anyone-3.3.4.0.apk
it show:
 `adb: failed to install Anyone-3.3.4.0.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]`

how i can fix it?
thank you for reading!

**Comment by morphis** [comment]
You can't. You're trying to install an APK which doesn't support your host architecture (x86?). Most likely case is that you're trying to install an ARM-only APK on your x86 machine. There is nothing we can do to solve this.

**Comment by cjp-luany** [comment]
> 

Does it support on ubuntu 20.04 in vmware, because I try it don't work when it is in vmware.

**Comment by Fuseteam** [comment]
@cjp-luany care to be more descriptive?
