### ISSUE TITLE
The CPU of your computer (Intel(R) Core(TM)2 Quad CPU    Q8400  @ 2.66GHz) does not support all

### ISSUE THREAD

**Issue by Jireh2009** [anbox/anbox#1109]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```Dont have results because i cant install anbox
```

**Please describe your problem:**
snap install --devmode --beta anbox
error: cannot perform the following tasks:
- Run install hook of "anbox" snap if present (run hook "install": 
-----
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
The CPU of your computer (Intel(R) Core(TM)2 Quad CPU    Q8400  @ 2.66GHz) does not support all
features Anbox requires.
It is missing support for the following features: SSE 4.2
You can for example find more information about SSE
here https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions
-----)

**What were you expecting?:**
Any Ideas to use anbox to ubuntu 18.04

**Additional info:**

**Comment by morphis** [comment]
There is nothing we can do about this your physical CPU does not support all required features.
