### ISSUE TITLE
Can't install snap package on Ubuntu 16.10

### ISSUE THREAD

**Issue by acrap** [anbox/anbox#111]
I try this:
sudo snap install --classic anbox-installer && anbox-installer
But i get the error:
snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks

I think it may be snapd issue...

**Comment by morphis** [comment]
As I can't really help with any snapd releated issues here, can you ask at https://forum.snapcraft.io/ for help? Thanks!
