### ISSUE TITLE
Unable to install using snap. Ubuntu 18.04

### ISSUE THREAD

**Issue by AlexeyFilich** [anbox/anbox#1125]
alexey@pc:~$ sudo snap install --beta --devmode anbox
ошибка: cannot perform the following tasks:
- Run install hook of "anbox" snap if present (run hook "install": 
-----
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
The CPU of your computer (AMD Athlon(tm) 64 X2 Dual Core Processor 6000+) does not support all
features Anbox requires.
It is missing support for the following features: SSE 4.1, SSE 4.2, SSSE 3
You can for example find more information about SSE
here https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions
-----)
alexey@pc:~$ snap refresh --devmode --edge anbox
snap "anbox" is not installed

I don't know so much about linux... So may be there is an easy fix :D

Any ways to install it manually?

**Comment by 1nv1zzz** [comment]
Try to install without sudo.
`snap install --devmode --beta anbox`

**Comment by AlexeyFilich** [comment]
Nope. Same thing

**Comment by sheldonmaschmeyer** [comment]
This seems to be a similar issue to threads linked below: seems to be unresolved, might be incompatible since the processor does not have SSSE 3+.
https://github.com/anbox/anbox/issues/499
https://github.com/anbox/anbox/issues/945

**Comment by bustosv** [comment]
no have way to solve that ? :(
