### ISSUE TITLE
How much data will I consume when I download android sources? 

### ISSUE THREAD

**Issue by summertime-saga** [anbox/anbox#1127]
I'm trying to build anbox from source and I noticed that it takes a long time to download the android sources, I'm afraid that I'll end up consuming all my internet plan.

**Comment by awaken1ng** [comment]
A lot, don't remember the exact number, but it was around 80-100 GB

**Comment by summertime-saga** [comment]
woah! thats huge. Is that for the android sources needed by anbox alone or the whole aosp?

**Comment by awaken1ng** [comment]
Pretty sure there was more than Anbox needed, thinking about it, that size might also include the checkout as well
