### ISSUE TITLE
Installation failed Linux mint mate 19

### ISSUE THREAD

**Issue by Qtamo** [anbox/anbox#1128]
I get this error when running the command anbox in the terminal after following the installation instructions:
Command 'anbox' is available in '/snap/bin/anbox'
The command could not be located because '/snap/bin' is not included in the PATH environment variable.

Also the Anbox app is nowhere to be found in the application menu.

I hope this is an actual bug and I haven't just messed up something (I'm a bit of a noob) :D

Edit: I ran these commands in the terminal (if I remember correctly):
export PATH=$PATH:/snap/bin
echo 'export PATH=$PATH:/snap/bin' >> ~/.profile
source ~/.profile

(The first command of the three commands might be useless idk.)
Then I restarted my computer. Now it works :D

Thanks to this article: https://www.putorius.net/set-path-variable-linux.html

**Comment by JoshuaDoes** [comment]
Make sure to close this issue now that it's resolved c:

**Comment by Qtamo** [comment]
True. But if it messes up the path during installation would that not count as a bug? Even if there is a relatively easy fix?
