### ISSUE TITLE
APK does not install

### ISSUE THREAD

**Issue by lhow** [anbox/anbox#1132]
For testing I installed anbox in Linux Mint running in a virtual machine. I tried Linux Mint 19.1, and Linux Mint 18.3. Anbox seemed to install smoothly. For a special purpose I wanted to install anton.apk 1.3.5. with "adb install my-app.apk". The installer started but stopped with an error message:

Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

Under Linux I could extract the apk-file. Under both Linux versions I had the same error message. Both of them running in Virtualbox.

**Comment by abdo1819** [comment]
try using a (x86) Architecture of the app

**Comment by meoxtma** [comment]
look at [(https://www.apkmirror.com)] they have difference Versions of APKs x86 and armeabi-v7a works fine for me on disco...
