### ISSUE TITLE
File manager unable to acces system storage

### ISSUE THREAD

**Issue by suryansh738** [anbox/anbox#1135]
I recently installed CZ file manager thinking that I can use it the way i uses it on my android device but however after installation when I opened it and tried to access the system storage it said  acess denied.
So is there any solution to this problem if then please let me know
Thanks in advance

**Comment by awaken1ng** [comment]
You can use [rootfs overlay](https://docs.anbox.io/userguide/advanced/rootfs_overlay.html) or repack the Android image with `unsquashfs` and `mksquashfs`, if for some reason overlay doesn't work

**Comment by sasha-ch** [comment]
@awaken1ng , @morphis :   
 I have same issue with another app #1131 . 
"rootfs overlay" enabled, it works, but don't help with storage issue.

```sh
root@dell# ll /var/snap/anbox/common/rootfs-overlay/storage/emulated/0/Download/
total 1.4M
drwxr-xr-x 2 100000 100000 4.0K May 31 16:24 .
drwxr-xr-x 3 100000 100000 4.0K May 31 16:17 ..
-rw-r--r-- 1 100000 100000    0 May 31 16:18 3.txt
-rw-r--r-- 1 100000 100000 1.4M May 31 16:24 IMG_0496.JPG
root@dell# ll /var/snap/anbox/common/combined-rootfs/storage/emulated/0/Download/
total 1.4M
drwxr-xr-x 2 100000 100000 4.0K May 31 16:24 .
drwxr-xr-x 3 100000 100000 4.0K May 31 16:17 ..
-rw-r--r-- 1 100000 100000    0 May 31 16:18 3.txt
-rw-r--r-- 1 100000 100000 1.4M May 31 16:24 IMG_0496.JPG
```
(created mannually and map ok).
But apps inside anbox don't see these files (and folder):
![Screenshot from 2019-05-31 16-27-13](https://user-images.githubusercontent.com/8925015/58710333-bda44980-83c4-11e9-9c4c-5a8d51abfebf.png)
![Screenshot from 2019-05-31 16-56-36](https://user-images.githubusercontent.com/8925015/58710487-17a50f00-83c5-11e9-87c0-9e9eb4077b34.png)

How to enable storage or check if it works?

**Comment by theWebalyst** [comment]
I'm stuck with accessing host storage too, and am not sure if I have rootfs-overlay working. I enabled rootfs-overlay as in the docs, and then effectively did:
```
cd /var/snap/anbox/common/rootfs-overlay
sudo mkdir -p storage/emulated/0/Download/
sudo chmod -R a+rw storage
sudo snap restart anbox.container-manager
```
But `combined-rootfs` is still empty.
