### ISSUE TITLE
Android image does not exist at path "/var/lib/anbox/android.img"

### ISSUE THREAD

**Issue by mosaic141688** [anbox/anbox#114]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the
list of open bugs at https://github.com/anbox/anbox/issues

**Anbox release (`anbox version`) and system info (`anbox system-info`):**
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.4.0-72-generic (buildd@lcy01-17) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

**Description of the problem:**
When I run anbox container-manager I get [EE 2017-04-15 18:50:42] [container_manager.cpp:90@setup_mounts] Android image does not exist at path "/var/lib/anbox/android.img
on the output

**Expected:**
I expected anbox to come with the android image, or instructions on how to get one

**Additional info:**

**Comment by gasinvein** [comment]
You can get one [here](http://build.anbox.io/android-images/).

**Comment by mosaic141688** [comment]
Thank you Fillippe

**Comment by hemangjoshi37a** [comment]
@gasinvein @mosaic141688 
I pasted the image on the location **/var/lib/anbox/android.img"** but it still shows the same error.
does it works for you any of guys??

**Comment by gasinvein** [comment]
@hemangjoshi37a, works for me. Is your image path really exactly same as on one in error message? Maybe you should try providing your actual path as option `--android-image=` to container-manager.

**Comment by hemangjoshi37a** [comment]
okay let me try... and I have 

And when I mount it on my Linux Mint 18.1 there seems to be two literally same 326mb volumes which should be only one 326mb volume?? Could there be any glitch at the time making the image??

**Comment by hemangjoshi37a** [comment]
yes all the same error... 
here is the link to the error pictures... http://hemangjoshi.blogspot.in/2017/04/error.html

**Comment by hub2git** [comment]
@gasinvein,
Re https://github.com/anbox/anbox/issues/114#issuecomment-294313186,
Do you know why anbox-installer doesn't automatically download the image as part of the installation?

**Comment by hemangjoshi37a** [comment]
It does but there is some coding glitch in the installer script. Actually I opened the installer script and then copied the lines from 151 to end and made new installer.sh file and than ran it which downloaded 300+ some mb file. I think that must be the Android file.
I have created a issue in the anbox-installer repository recently which you can follow if you want to.

**Comment by hub2git** [comment]
@hemangjoshi37a, thank you for your reply. You're right that the http://build.anbox.io/android-images/2017/04/12/android_1_amd64.img is about a 300-megabyte file. 

When you say "coding glitch in the installer script", do you mean that it affects everyone trying to use that script? Do you mean that the developers should fix it? Or is the problem on our end (i.e. users' end)?

**Comment by hemangjoshi37a** [comment]
Actually I tested by putting many other Android images in the folder from my collection of different Android versions but any of that doesn't seems to be working. It shows the same error every time.

**Comment by hub2git** [comment]
>  I have created a issue in the anbox-installer repository recently which you can follow if you want to.

Link, please.

**Comment by hemangjoshi37a** [comment]
When I say coding glitch, there is problem on developer side. Don't bother your PC is alright.. lol... And ya it affects everyone of course.
I don't know how @gesinvein got it working. But we will find a way soon.
It is a big breakthrough if it turns out to be working.. I actually want to run it on my Raspberry Pi if it successfully works on my Linux mint.

**Comment by hub2git** [comment]
@hemangjoshi37a , yeah, i also don't get it how ppl are able to get AnBox working if they don't have the Android image. I'm on Linux Mint too (18.1 xfce). So excited for Anbox development. 👍

**Comment by hemangjoshi37a** [comment]
@gasinvein are you using Ubuntu??

**Comment by Gazzasore** [comment]
It does install the Android Image if you use the installer script 
$ wget https://raw.githubusercontent.com/anbox/anbox-installer/master/installer.sh -O anbox-installer

From https://github.com/anbox/anbox/blob/master/README.md

It also says these are needed 

$ sudo apt install build-essential cmake cmake-data debhelper dbus google-mock \
    libboost-dev libboost-filesystem-dev libboost-log-dev libboost-iostreams-dev \
    libboost-program-options-dev libboost-system-dev libboost-test-dev \
    libboost-thread-dev libcap-dev libdbus-1-dev libdbus-cpp-dev libegl1-mesa-dev \
    libgles2-mesa-dev libglib2.0-dev libglm-dev libgtest-dev liblxc1 \
    libproperties-cpp-dev libprotobuf-dev libsdl2-dev lxc-dev pkg-config \
    protobuf-compiler

I have done all this but Anbox still doesn't start

**Comment by smy20011** [comment]
Same issue, It seems that the anbox cannot find the correct android image. I think It's related to the snap sandbox & permission problem.

**Comment by hemangjoshi37a** [comment]
@Gazzascore, you need those file only if you want to build the installation from source. You won't need that extra file for directly installing from snap or from anbox-installer.sh

**Comment by gasinvein** [comment]
@hemangjoshi37a Nope, I use openSUSE. Also I didn't use snap and and install script.

**Comment by hemangjoshi37a** [comment]
@gasinvein okay

**Comment by Connor124** [comment]
If you use `anbox container-manager --android-image=/snap/anbox/x1/android.img` as root then the container manager starts correctly.

**Comment by hemangjoshi37a** [comment]
Okay @Connor124 I will give it a shot next morning

**Comment by Gazzasore** [comment]
Same result 

anbox container-manager --android-image=/snap/anbox/x1/android.img
[EE 2017-04-17 01:11:36] [container_manager.cpp:90@setup_mounts] Android image does not exist at path "/snap/anbox/x1/android.img"
gazza@gazza-Alienware-18 ~ $ sudo anbox container-manager --android-image=/snap/anbox/x1/android.img
[sudo] password for gazza: 
[EE 2017-04-17 01:12:00] [container_manager.cpp:90@setup_mounts] Android image does not exist at path "/snap/anbox/x1/android.img"

**Comment by Connor124** [comment]
Your paths may be different, maybe. Try digging around a bit and finding where `android.img` lives.

**Comment by Gazzasore** [comment]
I did it made no difference
Will have to wait for the Guru's to work it out
I'm not even sure if mine installed correctly as the Terminal disappeared right at the end of the installation
I have installed it Uninstalled it deleted all files linked to Anbox
Reinstalled it ..........
But doesn't make any difference

**Comment by Connor124** [comment]
Ah, sorry.

**Comment by Gazzasore** [comment]
No worries we can only try
When it all finally works it will be Magical

**Comment by hub2git** [comment]
@Gazzasore I gave a thumbs-down to your comment containing

> 
> I have installed it Uninstalled it deleted all files linked to Anbox
> Reinstalled it ..........
> But doesn't make any difference

Because I am sad with you. I suspect the problem lies with the code. Hopefully the developers will fix all the kinks so you and I and others can use anbox :)

**Comment by edivaldo-amaral** [comment]
Deu certo :-)
Ao executar o comando **anbox container-manager**, aparecia a seguinte mensagem:
```
anbox container-manager
[EE 2017-04-19 01:56:47] [container_manager.cpp:90@setup_mounts] Android image does not exist at path "/var/lib/anbox/android.img"
**find -name android.img** 
```
Então pesquisei na raiz do sistema se havia o arquivo android.img 
**sudo find -name android.img**
Encontrei no diretório:
**./snap/anbox/15/android.img**

Copiei o arquivo para o diretório que estava faltando:
**sudo cp android.img /var/lib/anbox/**

Depois executei o comando:
**anbox session-manager**

Agora pode clicar no ícone do Anbox no menu que ele irá abrir. :+1: 


---
Ainda não sei como instalar programas do Android nele.

**Comment by hemangjoshi37a** [comment]
Please write in English....

**Comment by Gazzasore** [comment]
I put in all those commands and got 

anbox container-manager
[EE 2017-04-19 03:07:21] [container_manager.cpp:90@setup_mounts] Android image does not exist at path "/var/lib/anbox/android.img"
gazza@gazza-Alienware-18 ~ $ sudo find -name android.img
[sudo] password for gazza: 
gazza@gazza-Alienware-18 ~ $ /snap/anbox/15/android.img
bash: /snap/anbox/15/android.img: Permission denied
gazza@gazza-Alienware-18 ~ $ sudo cp android.img /var/lib/anbox/
cp: cannot stat 'android.img': No such file or directory
gazza@gazza-Alienware-18 ~ $ anbox session-manager
[EE 2017-04-19 03:08:59] [session_manager.cpp:119@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded

I found this one interesting   " /snap/anbox/15/android.img: Permission denied  "

**Comment by edivaldo-amaral** [comment]
@Gazzasore, está indo bem. Você localizou o arquivo android.img. Agora faça o seguinte:
**sudo cp /snap/anbox/15/android.img /var/lib/anbox/**
Depois execute:
**anbox session-manager**

Após este comando, minimize o terminal e abra o Anbox clicando em seu ícone no menu. 

------
@hemangjoshi37a Desculpe, quero muito saber inglês mas por enquanto conto com a ajuda do meu amigo Google Tradutor.

**Comment by Gazzasore** [comment]
@hemangjoshi37a
I have no idea what you have just said
Cheers

**Comment by Gazzasore** [comment]
@edivaldo-amaral
Woops wrong person
I can only read English buddy sorry

**Comment by Gazzasore** [comment]
Translated

está indo bem. Você localizou o arquivo android.img. Agora faça o seguinte:
sudo cp /snap/anbox/15/android.img /var/lib/anbox/
Depois execute:
anbox session-manager

Após este comando, minimize o terminal e abra o Anbox clicando em seu ícone no menu

Is doing well. You located the file android.img. Now do the following:
Sudo cp /snap/anbox/15/android.img / var / lib / anbox /
Then run:
Anbox session-manager

After this command, minimize the terminal and open Anbox by clicking its icon in the menu

But did nothing on my Rig

**Comment by gasinvein** [comment]
>cp /snap/anbox/15/android.img / var / lib / anbox /

That was pretty close to rm -rf /usr /lib/nvidia-current/xorg/xorg

**Comment by Connor124** [comment]
This guy has prebuilt packages for Debian. Check it out: https://ftp.ustclug.org/~zsj/anbox/

**Comment by hub2git** [comment]
@Connor124 ,do those prebuilt Debian packages work on Linux Mint 18.1?

**Comment by Connor124** [comment]
I don't know, I could fire up a Mint machine. But, seeing as you're probably on Mint, you could do it for me :)

**Comment by hub2git** [comment]
OK. Will do, since I'm itching to get anbox running on my computer's!

**Comment by davidelang** [comment]
I'm having the same problem on ubuntu 17.04

```
dlang@dlang-laptop:~/anbox-work$ anbox container-manager
[EE 2017-04-24 10:51:36] [container_manager.cpp:90@setup_mounts] Android image does not exist at path "/var/lib/anbox/android.img"
dlang@dlang-laptop:~/anbox-work$ ls -l /var/lib/anbox/android.img
-rw-rw-rw- 1 root root 325906432 Apr 24 03:48 /var/lib/anbox/android.img
dlang@dlang-laptop:~/anbox-work$ anbox container-manager --android-image=android_1_amd64.img 
[EE 2017-04-24 10:54:19] [container_manager.cpp:76@operator()] boost::filesystem::create_directory: Permission denied: "/var/lib/anbox/rootfs"
dlang@dlang-laptop:~/anbox-work$ anbox container-manager --android-image=./android_1_amd64.img 
[EE 2017-04-24 10:54:27] [container_manager.cpp:76@operator()] boost::filesystem::create_directory: Permission denied: "/var/lib/anbox/rootfs"
dlang@dlang-laptop:~/anbox-work$ ls -l
total 318296
-rw-rw-r-- 1 dlang dlang 325906432 Apr 21 10:37 android_1_amd64.img

```

It looks like if I run it as root it gets past the rootfs error (even if I chmod 777 /var/lib/anbox it doesn't work as non-root), but then it hits "address already in use"

where are options like --android-image documented?

**Comment by Connor124** [comment]
@hub2git Yeah, they work for me while the official way doesn't. But I'm on Debian, so I can't really speak for Ubuntu (even though it's based on Debian)

**Comment by hub2git** [comment]
@Connor124 I reached a roadblock. https://gist.github.com/hub2git/de5b3b2bd6520cc62e25a98d12f947bf

**Comment by Connor124** [comment]
I DO NOT RECOMMEND THIS

You could add the Debian repos to your sources file then run the command. DO NOT run an upgrade or dist-upgrade. Make sure to remove the entries afterwards. 

Or you could wait 'til Wednesday and I'll fire up a Mint machine to have a look.

**Comment by hub2git** [comment]
@connor124, I can wait 'til Wednesday. :) Thank you, my fellow Mint user
and fellow Anbox fan. :) :zap: :v:

**Comment by p1gd0g** [comment]
Same issue, linuxmint 18.1.
Is this the downloading process of android.img?
>+ sudo snap install --edge --devmode anbox
>anbox 42.39 MB / 341.22 MB [==================

**Comment by morphis** [comment]
Closing this as the original issue was that `anbox container-manager` was executed without the use of the `--android-image` parameter which is required if the android.img doesn't exists at the default location in /var/lib/anbox/android.img

**Comment by Connor124** [comment]
@hub2git

I followed the DO NOT TRY instructions on my earlier post and it worked fine, otherwise it didn't. I still do not recommend doing it though.

**Comment by hub2git** [comment]
@Connor124 My face still looks like this: 😕 .

> it worked fine, otherwise it didn't. 

❓ ❔

**Comment by DinicChen** [comment]
> You can get one [here](http://build.anbox.io/android-images/2017/04/12/android_1_amd64.img).

Where should I put this file?

**Comment by yskvl** [comment]
> @gasinvein @mosaic141688
> I pasted the image on the location **/var/lib/anbox/android.img** but it still shows the same error.
> does it work for you any of guys??

how do i put android.img in /var/lib/anbox/ it wont let me
