### ISSUE TITLE
Can anbox be built without systemd installed?

### ISSUE THREAD

**Issue by mgcyung** [anbox/anbox#1140]
Can anbox be built without systemd installed?

**Comment by aurora-of-earth** [comment]
@mgcyung Why though?

**Comment by mgcyung** [comment]
I am using openrc instead of systemd.

On Sat, 01 Jun 2019 20:22:44 +0800,
Aurora of Earth wrote:

**Comment by nkichukov** [comment]
Can this be reopened? Why not remove the systemd dependency and make it a configuration option instead?

**Comment by vidalh** [comment]
Helo

As nkichukov say, a configuration or greater a compilation option will be a very good choice for all of those doesn't use systemd.

Personaly I'm using s6 on obarun

**Comment by felixbecker2** [comment]
Same here, I fail to use anbox because of systemd dependencies.

**Comment by agausmann** [comment]
I have the same problem, it's unfortunate that this depends on systemd and is distributed only with snap (which also depends on systemd), it is a huge limitation for many people that would otherwise use it.

**Comment by agausmann** [comment]
Anyone else who stumbles upon this - take a look at [Waydroid](https://github.com/waydroid/waydroid) as an alternative
