### ISSUE TITLE
anbox will not launch on kde neon

### ISSUE THREAD

**Issue by 2635599** [anbox/anbox#1144]
i've installed anbox and it will not launch. i've included the logs below. if you need further info please let me know. thanks

[anbox-system-diagnostics-2019-05-15.zip](https://github.com/anbox/anbox/files/3187764/anbox-system-diagnostics-2019-05-15.zip)

**Comment by awaken1ng** [comment]
> binder: false
> ashmem: false

Looks like you're missing [kernel modules](https://github.com/anbox/anbox-modules)
