### ISSUE TITLE
Anbox does not start: "Application manager service is not running yet" 

### ISSUE THREAD

**Issue by Kreyren** [anbox/anbox#1149]
As refferenced on https://github.com/anbox/anbox/issues/781#issuecomment-475916754_ same issue here, @morphis  asked to re-open the issue which OP didn't -> making new.

![image](https://user-images.githubusercontent.com/11302521/54873379-f88a6f80-4dcc-11e9-9aa0-ccf995c16b43.png)

kreyren@dreamon:-$ anbox system-info | ix
http://ix.io/1BM0
kreyren@dreamon:-$ anbox version
anbox 0.0~git20190124-1-Debian
kreyren@dreamon:-$ anbox check-features
Your computer does meet all requirements to run Anbox

--- 

### 01
From https://github.com/anbox/anbox#requirements trying presented command to install all dependencies. -> Was successful -> Same issue -> Not dependency issue.

kreyren@dreamon:~$ anbox check-features
Your computer does meet all requirements to run Anbox

### 02

---

## QA
@morphis Why is this issue closed? There is like 15 ppl having this issue.. Or is this issue ignored?

_Originally posted by @Kreyren in https://github.com/anbox/anbox/issues/781#issuecomment-475916754_

---

## REFERENCES
https://github.com/anbox/anbox/issues/781
The problem should be fixed with the latest snap version. Please retest. If it still exists we can reopen the issue.

_Originally posted by @morphis in https://github.com/anbox/anbox/issues/781#issuecomment-406036085_

**Comment by neculaesei** [comment]
Here's how I got it working on arch (5.1.5-arch1-2-ARCH  x86_64 GNU/Linux)
- install linux-headers
- install anbox-git
- install dkms modules from https://github.com/86423355844265459587182778/anbox-modules
- **remember to start the anbox service**: `sudo systemctl start anbox-container-manager.service`
And it should work.

**Comment by luntik2012** [comment]
doesn't work with arch 5.1.7

**Comment by neculaesei** [comment]
> doesn't work with arch 5.1.7

It works if you start the service. If the dkms modules don't work for you use the ones posted in my previous comment.

![2019-06-06_11-20](https://user-images.githubusercontent.com/3195552/59017798-1f453780-884d-11e9-9154-cca81408c0bc.png)

**Comment by luntik2012** [comment]
worked with this
https://github.com/86423355844265459587182778/anbox-modules

**Comment by ltsdw** [comment]
**anbox session-manager** output:
```
[ 2019-06-10 17:54:10] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[ 2019-06-10 17:54:10] [session_manager.cpp:148@operator()] Lost connection to container manager, terminating.
[ 2019-06-10 17:54:11] [daemon.cpp:61@Run] Container is not running
[ 2019-06-10 17:54:11] [session_manager.cpp:148@operator()] Lost connection to container manager, terminating.
Stack trace (most recent call last) in thread 1875:
```
sometimes this:
```
[ 2019-06-10 17:53:55] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[ 2019-06-10 17:53:55] [session_manager.cpp:148@operator()] Lost connection to container manager, terminating.
[ 2019-06-10 17:53:56] [daemon.cpp:61@Run] Container is not running
terminate called after throwing an instance of 'boost::wrapexcept<boost::log::v2_mt_posix::system_error>'
  what():  Failed to set TLS value: Invalid argument
Stack trace (most recent call last) in thread 1849:
```

also have tried **anbox session-manager --gles-driver=host** and I can assure that I'm running **anbox container-manager --daemon --privileged --data-path=/var/lib/anbox** before trying session-manager. The output is the same for starting services and checking status with **systemctl --user start anbox-session-manager.service**

**Comment by geofarce** [comment]
I am experiencing same issue, Ubuntu 18.04.2 LTS however I do not have any anbox services installed at all so I imagine that is the issue,  I have installed kernel modules and installed beta via snap.

$ sudo systemctl start anbox-container-manager.service
Failed to start anbox-container-manager.service: Unit anbox-container-manager.service not found.

geofarce@u5438cc86fd1951:~$ anbox.appmgr
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
[ 2019-07-08 13:48:08] [daemon.cpp:61@Run] Failed to retrieve ready property from application manager

**Comment by acomagu** [comment]
Same issue at 4.19.62-1-MANJARO.

I tried Anbox at c732719, cd829e9 and ea2b7a3, with latest anbox-modules.

`anbox launch` fails every time, first time shows `Application manager servise is not running yet` and later it shows `Failed to retrieve ready property from application manager`.

```
$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[ 2019-08-10 15:05:34] [daemon.cpp:61@Run] Application manager service is not running yet
$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[ 2019-08-10 15:15:00] [daemon.cpp:61@Run] Failed to retrieve ready property from application manager
```

`anbox session-manager` fails every time with `Failed to start container`.

```
$ anbox session-manager
[ 2019-08-10 15:18:51] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[ 2019-08-10 15:18:51] [session_manager.cpp:148@operator()] Lost connection to container manager, terminating.
[ 2019-08-10 15:18:52] [daemon.cpp:61@Run] Container is not running
[ 2019-08-10 15:18:52] [session_manager.cpp:148@operator()] Lost connection to container manager, terminating.
```

`anbox-container-manager` service seems to work correctly.

```
$ env LC_ALL=C sudo systemctl status anbox-container-manager
* anbox-container-manager.service - Anbox Container Manager
   Loaded: loaded (/usr/lib/systemd/system/anbox-container-manager.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2019-08-11 00:20:27 JST; 11s ago
 Main PID: 13239 (anbox)
    Tasks: 9 (limit: 4915)
   Memory: 1.8M
   CGroup: /system.slice/anbox-container-manager.service
           `-13239 /usr/bin/anbox container-manager --daemon --privileged --data-path=/var/lib/anbox

Aug 11 00:20:27 acm-manjaro systemd[1]: Started Anbox Container Manager.
```

`ashmem_linux` and `binder_linux` kernel modules loaded without error.

Any help?

**Comment by huataihuang** [comment]
@acomagu I have problem same as you, and foudn in /var/lib/anbox/logs/container.log:

```
   lxc 20191009031012.568 INFO     cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1405 - The monitor process uses "lxc.monitor/default" as cgroup
   lxc 20191009031012.587 ERROR    cgfsng - cgroups/cgfsng.c:__do_cgroup_enter:1500 - No space left on device - Failed to enter cgroup "/sys/fs/cgroup/cpuset//lxc.monitor/default/cgroup.procs"
```

Solve my problem as refer to https://github.com/lxc/lxd/issues/6257

```
echo 1 | sudo tee /sys/fs/cgroup/cpuset/cgroup.clone_children
```

**Comment by acomagu** [comment]
@huataihuang It solves also my problem! Thank you so much!!

**Comment by SoHeil-SS** [comment]
not working ubuntu 20.04

**Comment by Zahid-BM** [comment]
Not working on Linux mint 20 cinnamon. Can you plz help me out on this?

**Comment by whynnot** [comment]
> Not working on Linux mint 20 cinnamon. Can you plz help me out on this?

Same here. 

I had it running on Mint 18 and then I upgraded to Linux Mint 20 via a clean install. i tried both Anbox versions: enabling Snap first and then installing, and also from the Software Manager. At times, they would start and work. But once I reboot the machine the service doesn't start at all. 

At other times they just wouldn't start at all. The one thing I couldn't get my head around was installing from source.

After three days of trying to get it work (just because I want to run WhatsApp) I gave up and did a clean install of Mint 19.3. Fortunately, my /home is on a separate partition so the system was back up within two or so hours. And I was able to install Anbox via Snap. It runs without a problem.


> Not working on Linux mint 20 cinnamon. Can you plz help me out on this?

**Comment by steelcowboy** [comment]
Maybe it was just from me trying to force stop anbox as a whole, but when I ran into this problem I ended up running:
```
snap start anbox
```
And it resolved this issue for me. I'm on Ubuntu 20.10

**Comment by xcodz-dot** [comment]
Looks like I have currupted my systemd service file, Can someone please share a copy of `/etc/systemd/system/anbox-container-manager.service`.

**Comment by smellymoo** [comment]
yup, same on Fedora 35.

can we all agree that Snap is hot-garbage, and move on to build anbox properly for each distro?

**Comment by Fuseteam** [comment]
Then poke the fedora devs to "build anbox properly". It is the responsibility of the distro maintainer to build packages for their distros. Always has been.

**Comment by Rushikesh-Tanpure** [comment]
Same issue tried all suggestions

**Comment by Fuseteam** [comment]
unfortunately, anbox is no longer supported. please see https://anbox.io for more info

**Comment by Rushikesh-Tanpure** [comment]
Thanks @Fuseteam
