### ISSUE TITLE
request... for appimage

### ISSUE THREAD

**Issue by datamaskinen** [anbox/anbox#1152]
I do not know where to make feature request but i try here...

Have you been thinking of making appimages of this ...would be nice to have redy made appimages for arm and x86.... klick and run

**Comment by aurora-of-earth** [comment]
I request for Debian packages too.

**Comment by JasMich** [comment]
You'll find Debian packages: https://packages.debian.org/sid/anbox **Note**: *Seems to be only in sid yet.*
They're included in current Ubuntu & Mint as well.

They were built in January. That's why I currently try to offer more current builds in my own PPA. I'll let you know when I finished.

Appimage will be difficult because it needs kernel modules. I'm not sure how far it will work.

**Comment by JasMich** [comment]
> arm and x86

Nope: only x86_64, armhf & arm64

**Comment by mibry** [comment]
I had a look and unable to build arm64 rootfs.

**Comment by JasMich** [comment]
> I had a look at your link and I have been unable to build anbox arm64 rootfs.

The script is made for AMD64. Did you change the following line from
```
sudo docker run -it -v ${WD}/android-work/:/src android-build-trusty bash -c "cd /src; source build/envsetup.sh; lunch anbox_x86_64-userdebug; make -j${SYNC}"
```
to
```
sudo docker run -it -v ${WD}/android-work/:/src android-build-trusty bash -c "cd /src; source build/envsetup.sh; lunch anbox_arm64-userdebug; make -j${SYNC}"
```
?

**Comment by Cloud-Mak** [comment]
Appimage will be supercool. I say got for it.  Would be nice to run Anbox as portable on any Linux desktop.
+:100:

**Comment by JasMich** [comment]
I see. I will try to setup a OBS for an AppImage. I will let you know if it works.

**Comment by Cloud-Mak** [comment]
@JasMich 
Have you tried this? any luck?

**Comment by JasMich** [comment]
No, it doesn't work due to the kernel modules.

**Comment by CEHitchens** [comment]
I would like to chime in and express that I would like to see a non-snap version as well. Appimage, PPA or even one that we could build ourselves would certainly be a nice alternative to snap. Snap(d) permissions are quite far reaching, just to name one downside. Thanks.
