### ISSUE TITLE
Anbox compile error

### ISSUE THREAD

**Issue by lyndalopez544** [anbox/anbox#1153]
<pre>
In file included from /home/aurora/A.Code/C++/anbox/src/anbox/dbus/skeleton/application_manager.cpp:20:
/home/aurora/A.Code/C++/anbox/src/anbox/dbus/sd_bus_helpers.h: In function ‘constexpr sd_bus_vtable anbox::dbus::sdbus::vtable::start(uint64_t)’:
/home/aurora/A.Code/C++/anbox/src/anbox/dbus/sd_bus_helpers.h:33:56: error: missing initializer for member ‘sd_bus_vtable::<unnamed union>::<unnamed struct>::features’ [-Werror=missing-field-initializers]
   33 |   v.x.start = decltype(v.x.start){sizeof(sd_bus_vtable)};
      |                                                        ^
/home/aurora/A.Code/C++/anbox/src/anbox/dbus/sd_bus_helpers.h: In function ‘constexpr sd_bus_vtable anbox::dbus::sdbus::vtable::method_o(const char*, const char*, const char*, sd_bus_message_handler_t, size_t, uint64_t)’:
/home/aurora/A.Code/C++/anbox/src/anbox/dbus/sd_bus_helpers.h:52:79: error: missing initializer for member ‘sd_bus_vtable::<unnamed union>::<unnamed struct>::names’ [-Werror=missing-field-initializers]
   52 |   v.x.method = decltype(v.x.method){member, signature, result, handler, offset};
      |                                                                               ^
/home/aurora/A.Code/C++/anbox/src/anbox/dbus/sd_bus_helpers.h: In function ‘constexpr sd_bus_vtable anbox::dbus::sdbus::vtable::signal(const char*, const char*, uint64_t)’:
/home/aurora/A.Code/C++/anbox/src/anbox/dbus/sd_bus_helpers.h:67:54: error: missing initializer for member ‘sd_bus_vtable::<unnamed union>::<unnamed struct>::names’ [-Werror=missing-field-initializers]
   67 |   v.x.signal = decltype(v.x.signal){member, signature};
      |                                                      ^
cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/anbox-core.dir/build.make:466: src/CMakeFiles/anbox-core.dir/anbox/dbus/skeleton/application_manager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1944: src/CMakeFiles/anbox-core.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
</pre>

Built on Debian 10 with gcc 9.1.0

**Comment by sevu** [comment]
It's only a compile error because of `cc1plus: all warnings being treated as errors`
