### ISSUE TITLE
Anbox-modules-dkms don't compile Linux 5.1 kernel

### ISSUE THREAD

**Issue by torbol** [anbox/anbox#1155]
Hello, Anbox-modules-dkms doesn't compile with linux kernel 5.1:
[make.log](https://github.com/anbox/anbox/files/3249747/make.log)

It gives an error and the log that i've attached above. Might you make it compatible?

**Comment by 86423355844265459587182778** [comment]
This issue has been reported before:
#1130 anbox/anbox-modules#17

See anbox/anbox-modules#19 for a possible fix.
