### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by jackzhp** [anbox/anbox#1165]
can someone tell me how to run it?

I have followed the "Install Anbox" page, and it is installed.
I am not familiar with snap, so how to bring it up? it will be great if the command used to bring it up can be in the "Install Anbox" page. Thanks in advance.

by now, I have the following:
$ snap info anbox
name:      anbox
summary:   Android in a Box
publisher: morphis
contact:   https://anbox.io
license:   GPL-3.0+
description: |
  Runtime for Android applications which runs a full Android system
  in a container using Linux namespaces (user, ipc, net, mount) to
  separate the Android system fully from the host.
  
  You can find further details in our documentation at
  https://github.com/anbox/anbox/blob/master/README.md
snap-id: Nr9K6UJaIOD8wHpDEQl16nabFFt9LLEQ
channels:
  stable:    –                                
  candidate: –                                
  beta:      4-e1ecd04 2018-10-17 (158) 391MB devmode
  edge:      4-ea2b7a3 2019-05-03 (176) 391MB devmode

**Comment by jackzhp** [comment]
By the way, this same question was asked before, but for long time, nobody answered, and docs are not improved, so I asked again. Hope the docs can be improved, so people won't have this problem in the future.

**Comment by Yousefjb** [comment]
```anbox.appmgr``` will start the application manager which is the main screen for anbox.  
from there you can start any application you've installed.
