### ISSUE TITLE
technical sensors support?

### ISSUE THREAD

**Issue by annopnod** [anbox/anbox#1168]
anbox possible sensors support using usb io module+ arduino sensors module

usb to i2c 
https://aliexpress.com/item/32925779617.html
![g1](https://user-images.githubusercontent.com/6957642/59344603-a35d5a80-8d38-11e9-9dbb-9584c91ef6f3.jpg)

accelerometer use arduino module
https://www.aliexpress.com/item/1858984311.html
![g2](https://user-images.githubusercontent.com/6957642/59344647-ba9c4800-8d38-11e9-91b6-074926cd2ad1.jpg)

**Comment by JasMich** [comment]
I think that will be difficult to implement but year, it would be helpful. If you want to write the necessary code, I'm sure the the maintainers would accept it.
