### ISSUE TITLE
[feature-request]: Minimize button in app bar

### ISSUE THREAD

**Issue by JasMich** [anbox/anbox#1175]
![image](https://user-images.githubusercontent.com/29313398/59926692-223e4b80-943b-11e9-8bd4-5e4bc4568aa3.png)
In the title bar, there are only buttons for maximize and close.
As usually, the windows manager offer still a button for minimize, such one would be useful for Anbox too.
I know, currently the window's top bar is just the one we know from Android freeform mode. This means the code changes are nacesary in the android source code. Does anyone know where to find them? I would be interested in creating one.

**Comment by zeitue** [comment]
+1 this feature is needed, at least for every desktop using the standard window button setup.

**Comment by RingyRing** [comment]
Can we reopen this issue and stop the stale bot from re-flagging it, please? Adding this would be quite useful.

**Comment by yanike** [comment]
This is a joke right! How do you build a desktop application without a minimize feature? This needs to be high priority.

**Comment by TheOneWithTheBraid** [comment]
@yanike I think it should work if we could provide an Android 10 rootfs. There, in freeform mode, windows have a minimize button.

**Comment by yanike** [comment]
> @yanike I think it should work if we could provide an Android 10 rootfs. There, in freeform mode, windows have a minimize button.

I still new to Anbox on Ubuntu Linux. How do you active freeform mode?

**Comment by TheOneWithTheBraid** [comment]
Anbox already uses apps in a freeform-like mode. The problem is that our current rootfs is Android 7 based and not Android 10.

**Comment by Adyan424** [comment]
Any solution ??????

**Comment by savinov** [comment]
Workaround for Ubuntu users: Ctrl +Alt +0

**Comment by Rajssss** [comment]
In xfce alt+f9 and right click in panel then minimize works too.

**Comment by paulsybrandy** [comment]
Or just click the app (twice if not already selected) on the taskbar/panel will minimize as well.

**Comment by Fuseteam** [comment]
@TheOneWithTheBraid i thought android 10 didn't have a freeform mode 🤔
