### ISSUE TITLE
Anbox not starting/opening

### ISSUE THREAD

**Issue by the-walkersingh** [anbox/anbox#1176]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**
anbox session-manager
[ 2019-06-21 23:17:35] [Renderer.cpp:102@initialize] Failed to Initialize backend EGL display
[ 2019-06-21 23:17:35] [service.cpp:41@Service] Successfully acquired DBus service name
Stack trace (most recent call last) in thread 7131:
#7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f4c2994e41c, in clone
#5    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7f4c2b4006b9, in 
#4    Object "/snap/anbox/158/usr/bin/anbox", at 0x57c3b0, in emugl::Thread::thread_main(void*)
#3    Object "/snap/anbox/158/usr/bin/anbox", at 0x4a696c, in RenderThread::main()
#2    Object "/snap/anbox/158/usr/bin/anbox", at 0x578b6a, in renderControl_decoder_context_t::decode(void*, unsigned long, IOStream*)
#1    Object "/snap/anbox/158/usr/bin/anbox", at 0x502d4e, in 
#0    Object "/snap/anbox/158/usr/bin/anbox", at 0x505a05, in RendererConfigList::getPackInfo(int*, int*) const
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault (core dumped)

$ anbox system-info
version: 4
snap-revision: 158
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 18.04.2 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.18.0-22-generic (buildd@lgw01-amd64-033) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #23~18.04.1-Ubuntu SMP Thu Jun 6 08:37:25 UTC 2019
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

**Comment by Holyprogrammer** [comment]
Please enclose debug messages in backtics ``` like so```.
You have accidentally referenced issues 1 to 7 and 23

**Comment by the-walkersingh** [comment]
sir its already pasted above

**Comment by AiyionPrime** [comment]
@the-walkersingh he is not asking for the messages, but for you to escape them correctly using backticks. The way you pasted the messages may lead to confusion on other issue threads.
