### ISSUE TITLE
keyserver receive failed: Server indicated a failure

### ISSUE THREAD

**Issue by fribosko** [anbox/anbox#1180]
Hi, I think Anbox is a great idea. For several days now I cannot cross the following hurdle:

$ sudo add-apt-repository ppa:morphis/anbox-support
[sudo] password for chitra:     
You are about to add the following PPA:
 More info: https://launchpad.net/~morphis/+archive/ubuntu/anbox-support
Press Enter to continue or Ctrl+C to cancel

Executing: /tmp/apt-key-gpghome.WYD0rp41GR/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys CFD4CCDE77B82D4FA3B113E521C6044A875B67B7
gpg: keyserver receive failed: Server indicated a failure

I read somewhere else that this might be a common problem with the overloaded key server. Would it not be a good idea to fix that?

Thanks for looking into it

**Comment by morphis** [comment]
The keyserver is operated by Ubuntu not us so there is nothing we can do about this.

**Comment by spider4216** [comment]
the same issue :(

**Comment by spider4216** [comment]
I added ppa manually.
First I added ppa into `/etc/apt/source.list`
For Ubuntu Bionic 18.04 it looks like this
```
deb http://ppa.launchpad.net/morphis/anbox-support/ubuntu bionic main 
deb-src http://ppa.launchpad.net/morphis/anbox-support/ubuntu bionic main 
```
After that I Imported GPG Key
```
sudo apt-key adv -v --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CFD4CCDE77B82D4FA3B113E521C6044A875B67B7
```
Attention, as a protocol I used `hkp` and also I specified port `80` and it works fine

P.S. I don't exactly understand why this problem appeared but it to do with DNS
more:
https://unix.stackexchange.com/questions/399027/gpg-keyserver-receive-failed-server-indicated-a-failure
