### ISSUE TITLE
Can't install on Linux 4.9.140-tegra aarch64

### ISSUE THREAD

**Issue by pintov** [anbox/anbox#1185]
Hello!

I'm trying to install Anbox on NVIDIA Jetson Nano.
I did these steps and everything was fine:
`sudo add-apt-repository ppa:morphis/anbox-support`
`sudo apt update`

But this command failed:
`sudo apt install linux-headers-generic anbox-modules-dkms`

I got the error:
`ERROR (dkms apport): kernel package linux-headers-4.9.140-tegra is not supported
Error! Bad return status for module build on kernel: 4.9.140-tegra (aarch64)`
Also I've attached [make.log](https://github.com/anbox/anbox/files/3362814/make.log)

Am I right in saying that there is no way to use Anbox on Jetson Nano?
Will it work in future?

**What were you expecting?:**
I'm expecting successful installation.

Thank you for your time!

**Comment by troopermax** [comment]
I don't think the Jetson kernel/headers can be updated/installed through the package manager. You should definitely be able to get past this if you build the kernel yourself, as others have done for other reasons: https://www.jetsonhacks.com/2019/04/25/jetson-nano-run-on-usb-drive/
That's definitely overkill though - there should be a way to get the headers and just build the modules, just don't think it is the usual way you were trying to do. I think they're actually provided by NVIDIA as part of the L4T (Linux for Tegra)/JetPack SDK, but haven't worked through this yet - I was also hoping to try out Anbox on the Jetson Nano as well.

**Comment by troopermax** [comment]
Following the directions in:
https://github.com/anbox/anbox-modules

I had to make a few tweaks to binder.c as detailed in the new issue I created:
https://github.com/anbox/anbox-modules/issues/26

With those tweaks I was able to build/insert both modules.

However, I could not install the anbox snap, as it looks like it isn't being built for arm64 anymore?
