### ISSUE TITLE
A new Chinese "anbox"?

### ISSUE THREAD

**Issue by AkariMarisa** [anbox/anbox#1187]
I found a Chinese version of "anbox", this is the URL: [https://www.linzhuotech.com](https://www.linzhuotech.com). Is that legit or not?

**Comment by danperks** [comment]
I've never heard of it, but I'm installing it as we speak. Will update later.

**Comment by AkariMarisa** [comment]
I downloaded and uploaded to my dropbox, here is the link [https://www.dropbox.com/s/k3ze0tno0r7dk66/xDroidInstall-x86_64-v2.7000-20190621155253.tar.gz?dl=0](https://www.dropbox.com/s/k3ze0tno0r7dk66/xDroidInstall-x86_64-v2.7000-20190621155253.tar.gz?dl=0)

**Comment by danperks** [comment]
I don't even know how you did that but I won't ask. 
I'll install it now.

**Comment by danperks** [comment]
After installing through the conveniently English installer, I can say it's basically a chinese version of Bluestacks for Linux. The whole program does actually load quicker than Anbox and it has it's own Chinese app store built in.

It detected and supports running my apps through my graphics card, which I don't think even Bluestacks does yet. Also, it has support for controller mapping and a few various other things that I understand. To be honest, this isn't a bad program.

**Comment by danperks** [comment]
Screenshots:
Main page - 
![image](https://user-images.githubusercontent.com/49082234/60805136-2d051a00-a177-11e9-8633-1a4a9cef6342.png)
App store - 
![image](https://user-images.githubusercontent.com/49082234/60805151-342c2800-a177-11e9-9876-b16e5c131cbb.png)

**Comment by danperks** [comment]
After a few minutes playing around with it, it seems the program is unable to install any apps.
Both my own APKs and apps from the built in app store all come up as faied to install.

Now I have to figure out how to uninstall this in Chinese -_-

**Comment by AkariMarisa** [comment]
Seems you can run install.sh to uninstall. Here I found the wiki about this program. [https://linzhuotech.com/Public/Home/img/gitbook/user_manual/_book/part2/xiezai.html](https://linzhuotech.com/Public/Home/img/gitbook/user_manual/_book/part2/xiezai.html).
Thank you very much for taking the time to help me answer my doubts.
BTW: I'm a chinese so I can read chinese, does that sound magic? :smile:

**Comment by tuxflo** [comment]
@danperks have you tried to install an apk via `adb`?

**Comment by danperks** [comment]
No, the software had a APK installer built in. It just failed every time.

**Comment by tuxflo** [comment]
I installed this inside a VM. I'm pretty sure that this is based on the anbox sources since it uses exactly the same directory layout and a whole lot of files are equal. Also they're using `ashmem` and `binder` too.

@morphis You should contact them about this potential GPL violation. Maybe also contact the Free Software Foundation or https://gpl-violations.org for more legal help about such issues.
