### ISSUE TITLE
The linker version '2.23' used by the base 'core' is incompatible with files in this snap: /home/test/WorkSpace/AnboxSpace/anbox/prime/lib/liblxc.so.1.4.0 (2.27)

### ISSUE THREAD

**Issue by jsnjkl** [anbox/anbox#1188]
I got a fatal error when snapcraft the Anbox
"The linker version '2.23' used by the base 'core' is incompatible with files in this snap: /home/test/WorkSpace/AnboxSpace/anbox/prime/lib/liblxc.so.1.4.0 (2.27)"

-My env is Ubuntu 18.04, and I followed steps in readme step by step strictly, except
:
changeing libboost version, since 1.58 could not be found on ub18.04
ibboost-log1.58.0 -> - libboost-log1.62.0
libboost-iostreams1.58.0 -> - libboost-iostreams1.62.0
libboost-program-options1.58.0 -> - libboost-program-options1.62.0
libboost-thread1.58.0 -> - libboost-thread1.62.0

-I am using a prebuilt android image at:
https://build.anbox.io/android-images/2018/07/19/android_amd64.img

-Tried several method like installing lxd, using 'snapcraft cleanbuild', however, no one yet works.

-I can install the prebuilt anbox binary by $snap install --devmode --beta anbox. And the pre-built anbox runs work.

-I'm able to build the anbox by 
git clone https://github.com/anbox/anbox.git
...
sudo make install

Did anyone meet similar problems, could you please provide any clues on this?
Or could you suggest how to run anbox by scripts directly without snap support?

Thanks,
JasonJin

**Comment by Disctanger** [comment]
@jsnjkl I am having exact same problem with you.

>

>  -My env is Ubuntu 18.04, and I followed steps in readme step by step strictly, except
> :
> changeing libboost version, since 1.58 could not be found on ub18.04
> ibboost-log1.58.0 -> - libboost-log1.62.0
> libboost-iostreams1.58.0 -> - libboost-iostreams1.62.0
> libboost-program-options1.58.0 -> - libboost-program-options1.62.0
> libboost-thread1.58.0 -> - libboost-thread1.62.0

I also tried the above method. It did not help me as well.
Prebuilt snap is working like a charm.

Even following method did not help
https://github.com/anbox/anbox/issues/1076
(Here i am having same error related to the linker version)

**Comment by citrix123** [comment]
Do find any solution for this issue?
I am also getting same. Nothing work,

Even I see that snap CI also failing 
https://build.snapcraft.io/user/anbox/anbox

**Comment by chuanzhi** [comment]
anbox/snap/snapcraft.yaml
```
name: anbox
base: core18
version: 4
```

add ```base: core18``` to snapcraft.yaml

**Comment by yongsheng** [comment]
> anbox/snap/snapcraft.yaml
> 
> ```
> name: anbox
> base: core18
> version: 4
> ```
> 
> add `base: core18` to snapcraft.yaml

it works for me.
