### ISSUE TITLE
What about ARM support?

### ISSUE THREAD

**Issue by CODeRUS** [anbox/anbox#119]
Currently it's not possible to install ARM apps into anbox: `Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]`

Is there any possibility for anbox to implement ARM functionality? For example Genymotion emulator using libhoudini for this.

**Comment by aliceklipper** [comment]
Maybe, `binfmt_misc` with QEMU may help. But I don't know exactly, I didn't try this.

**Comment by fat-tire** [comment]
Out of curiosity what happens if you run ubuntu/anbox on an ARM device?

**Comment by iam070** [comment]
rebuild the android image with libhoudini maybe necessary

**Comment by chiel99** [comment]
Agree with @iam070 , while libhoudini works on Android-x86 (not 100% workable), maybe it is worth to porting it to Anbox.
Ref: http://www.android-x86.org/

**Comment by morphis** [comment]
libhoudini isn't freely available and Anbox promises to be 100% open source. We don't want to break this promise so we will not include any binary blobs in our default deliverable. If somebody wants to implement an open source version of libhoudini we can reconsider this in the future.

For now we wont do any work to make apps which require the execution of binaries which doesn't match the host arch work.

**Comment by M1cha** [comment]
I think that @aliceklipper s idea is the way to go here.
We could just provide zygote + all the ndk libraries compiled for ARM and run it using qemu-user-static.
Qemu generates native code to speed up emulation so it should actually run with a decent speed.(and effectively do the same as libhoudini, only on a lower level).

**Comment by morphis** [comment]
@M1cha Feel free to experiment with this. I don't have any plans to do that. PRs are welcome :-)

If you want open a discussion thread on https://discourse.anbox.io to get this discussed with more interested people.

**Comment by erenoglu** [comment]
So even if libhoudini can't be included in anbox as it's not open source, can't anbox provide at least some interfaces and some methods for users to add it themselves? 
Due to lack of this library, I am unable to run a critical app which does not have a linux version, and which was the main driver to try anbox on my linux system. Now I'm forced either to use Windows or to revert to a full virtualization solution like Genymotion :(

**Comment by danFromTelAviv** [comment]
I want to run anbox on an arm computer. The title fits my question perfectly, but it seems the discussion is about running arm apps on an x86 computer.  Am I correct? Is anbox supposed to work on arm computers ?

**Comment by WaseemAlkurdi** [comment]
@androidhut
Depends on the host you run it on, it downloads a system image for x86 or x86_64.

**Comment by afjoseph** [comment]
I guess this could be helpful for the folks looking to run ARM apps: https://www.linuxuprising.com/2018/07/anbox-how-to-install-google-play-store.html

**Comment by baptx** [comment]
Did someone manage to run Firefox Mobile ARM version without crash when using libhoudini on Anbox? (here is the script I used to install libhoudini: https://github.com/geeks-r-us/anbox-playstore-installer/blob/master/install-playstore.sh)
I can browse a few web pages but it crashes after a few seconds. I know there is an x86 / x86_64 version of Firefox Mobile but I wanted to test how good libhoudini works.
Do you know if the crashes are a problem of libhoudini or Anbox?
