### ISSUE TITLE
keymapper tool

### ISSUE THREAD

**Issue by eadmaster** [anbox/anbox#1193]
is there a compatible keymapper app i can use to map touch gestures to keyboard buttons?

**Comment by tuxflo** [comment]
I'm not sure how this is related to anbox but you could use tools like Easystroke and Touchegg on your "host" system for creating specific button mappings that you can use in anbox.

**Comment by eadmaster** [comment]
My aim is to play Android games with an USB gamepad not supported natively.
So i actually need the opposite: map buttons to touch gestures.
I've found some suggestions here:
https://superuser.com/questions/817141/xdotool-click-and-hold-and-move-the-mouse

**Comment by luqmanr** [comment]
Probably out of topic, but how about xinput or dinput on anbox? It doesn't support it right now, i think, but maybe a much better solution than a keymapper?
