### ISSUE TITLE
AMD Radeon card also (core dumped)

### ISSUE THREAD

**Issue by blambin** [anbox/anbox#120]
ANBOX_LOG_LEVEL=debug anbox session-manager  
                                                                                       
[DD 2017-04-16 09:00:41] [gl_renderer_server.cpp:82@GLRendererServer] Using GLES-to-GL translator for rendering
[DD 2017-04-16 09:00:41] [Renderer.cpp:113@initialize] EGL doesn't support surfaceless context
[DD 2017-04-16 09:00:41] [Renderer.cpp:249@initialize] Successfully initialized EGL
[EE 2017-04-16 09:00:46] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[WW 2017-04-16 09:00:46] [session_manager.cpp:140@operator()] Lost connection to container manager, terminating.
[WW 2017-04-16 09:00:46] [session_manager.cpp:140@operator()] Lost connection to container manager, terminating.
[1]    5766 segmentation fault (core dumped)  ANBOX_LOG_LEVEL=debug anbox session-manager

Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the
list of open bugs at https://github.com/anbox/anbox/issues

**Anbox release (`anbox version`) and system info (`anbox system-info`):**

anbox 0.1.0

**Description of the problem:**

the anbox system-info also [1]    
8415 segmentation fault (core dumped)  anbox system-info

**Expected:**

**Additional info:**

 OS: Arch Linux x86_64 
 Model: Vostro 1440 A05 
  Kernel: 4.10.9-1-ARCH 
 Packages: 1577 
 Shell: zsh 5.3.1 
 Resolution: 1366x768 
 DE: KDE 
 WM: KWin 
 WM Theme: Kwin.aurorae 
Theme: Breeze 
 Icons: Emoticonsbreeze 
Terminal: yakuake 
 CPU: Intel Celeron P4600 (2) @ 1.9GHz 
GPU: Intel Ironlake Mobile 
GPU: AMD Radeon HD 6400M/7400M Series 
Memory: 4237MiB / 5771MiB

**Comment by oleid** [comment]
Does ```anbox session-manager --gles-driver=host``` work for you? This is what I use on my Arch with Radeon GPU.

**Comment by blambin** [comment]
No, it only show me , [EE 2017-04-22 03:04:12] [Renderer.cpp:105@initialize] Failed to initialize EGL   and stuck there.
