### ISSUE TITLE
feature request... docker

### ISSUE THREAD

**Issue by zaoqi** [anbox/anbox#1202]
related issue: https://github.com/anbox/anbox/issues/584

**Comment by morphis** [comment]
Running Anbox or Android inside docker doesn't make sense as docker is a single process focused containerization technology. Something like LXD is more suitable for this.

**Comment by andrewleech** [comment]
Docker isn't just about single service runtimes, one of the biggest use cases of docker is for repeatable environments for CI use.

Having anbox in a docker image ready to be automatically started cleanly would be amazing for CI use in unit testing Android apps quickly and reliable.

**Comment by KINETIK-DEV** [comment]
> Running Anbox or Android inside docker doesn't make sense as docker is a single process focused containerization technology. Something like LXD is more suitable for this.

mmhh that is really sad...
