### ISSUE TITLE
uninstalled anbox, but network interface anbox0 appears after each restart

### ISSUE THREAD

**Issue by dreamcat4** [anbox/anbox#1204]
Hi there.
Removed anbox from my system. However there is still a networking interface named `anbox0` that comes up after each reboot on my system.

This is on ubuntu 19.04. SO, how to remove, once and for all?

**Comment by morphis** [comment]
I don't know how you installed Anbox but if you installed the snap package this shouldn't happen. If you installed it differently (debian package or manual install) ensure that all files are gone. We don't have any systemd configuration files our self (other than those snapd generates) so there might be something left from the packaging system you used. If not, this could be a snapd bug too.

**Comment by dreamcat4** [comment]
Thank you for getting back to me... indeed it turned out that I had only removed the debian packaged version. And had forgotten to remove anbox from snap (which was installed also). Just need to reboot now to make sure that it's gone.

**Comment by dreamcat4** [comment]
Yep it's gone now. Thank you again for your time. Closing.
