### ISSUE TITLE
x86_64 Android image on https://build.anbox.io/android-images/?

### ISSUE THREAD

**Issue by monperrus** [anbox/anbox#1205]
Hi, I'm looking for an x86_64 Android image (eg `android.img`).

It would make sense to find it on https://build.anbox.io/android-images/, but that's not the case.

Where can I find a recent x86_64 Android image for anbox?

Thanks for the great project.

**Comment by 86423355844265459587182778** [comment]
You can find the latest amd64 image at https://build.anbox.io/android-images/2018/07/19/android_amd64.img.

**Comment by monperrus** [comment]
Thanks! And what about the latest x86_64 image for intel processors?

**Comment by 86423355844265459587182778** [comment]
You can use that image for Intel x64 processors.

Using the term "AMD64" or "amd64" does not necessarily mean that a software/program is only compatible with AMD x64 processors.
More information: https://en.wikipedia.org/wiki/X86-64#Industry_naming_conventions

**Comment by monperrus** [comment]
Thanks for the clarification.

Is there a more recent image than this one from one year ago (July 2018)?
