### ISSUE TITLE
install problem in virtualbox

### ISSUE THREAD

**Issue by sacarde** [anbox/anbox#1210]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by sacarde** [comment]
in virtualbox ubuntu-18.04.2 , I try to install anbox:

sudo snap install --devmode --beta anbox

but I have this messages:

error: cannot perform the following tasks:
- Run install hook of "anbox" snap if present (run hook "install": 
-----
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
The CPU of your computer (AMD Phenom(tm) 9550 Quad-Core Processor) does not support all
features Anbox requires.
It is missing support for the following features: SSE 4.1, SSE 4.2, SSSE 3
You can for example find more information about SSE
here https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions
-----)

can I workaround this problem?

thank you

**Comment by morphis** [comment]
The error message is pretty clear as your CPU misses required features. Nothing we can do here.
