### ISSUE TITLE
NSD/Bonjour on Anbox -> Host Networking

### ISSUE THREAD

**Issue by PSGXerus** [anbox/anbox#1213]
Is it possible to configure Anbox with host networking (omit the bridge)?
I want to use NSD/Bonjour in my Anbox, but service discovery only succeeds on my host Ubuntu, not on any device in my local network. My current guess is, that NSD does not get past the network bridge. Therefore the question.

Thanks for help.

**Comment by PSGXerus** [comment]
I just implemented host networking on anbox. Just needs some minor changes, till i can add a pull request.

**Comment by Old-iddi** [comment]
can you share a path with the host networking, until there is pull request?

**Comment by PSGXerus** [comment]
Do you want the sources or the finished snap?
The branch with host networking can be found in my fork of the project. 
I can sent you the snap if you want to.

Pull request should not take too long.

**Comment by PSGXerus** [comment]
[https://syncandshare.lrz.de/dl/fiWAUth5iPrjvyJSbGyJwrnv/.zip](Download AnboxSnap.zip) (expires in 2 Weeks)

**Comment by PSGXerus** [comment]
In the ZIP, you'll also find an instructions.txt with the basic CLI usage

**Comment by Old-iddi** [comment]
thank you, will try with wifi, my app works through wifi too...

but tunnel I refer to can be setup only on host linux, I can’t setup this
tunnel in android (tunnel is actually interface to special hardware),
so problem of bringing host network interfaces to anbox still exists.

**Comment by morphis** [comment]
@PSGXerus Please do a PR when you're happy with your work.

**Comment by PSGXerus** [comment]
I'll send a PR next week. Cause for this feature I had to activate the wifi menu in Android. But if you are using the wifi menu with the old/classic bridged network, may cause problems.

**Comment by PSGXerus** [comment]
> thank you, will try with wifi, my app works through wifi too... but tunnel I refer to can be setup only on host linux, I can’t setup this tunnel in android (tunnel is actually interface to special hardware), so problem of bringing host network interfaces to anbox still exists.

You can give it a try, if you add the tunnel as my parameter and then $ anbox.shell into the anbox container and check if it has picked it up correctly.

**Comment by Old-iddi** [comment]
when i set Anbox to capture tunnel interface (it captured - disappears from host system) but in anbox.shell only uninitialised wlan0 appeared
when I try this with wifi interface anbox container don’t start, haven't figured out what happens - in syslog it only says Failed to start container: three times
[syslog.txt](https://github.com/anbox/anbox/files/3799000/syslog.txt)

**Comment by PSGXerus** [comment]
> when i set Anbox to capture tunnel interface (it captured - disappears from host system) but in anbox.shell only uninitialised wlan0 appeared
> when I try this with wifi interface anbox container don’t start, haven't figured out what happens - in syslog it only says Failed to start container: three times
> [syslog.txt](https://github.com/anbox/anbox/files/3799000/syslog.txt)

Oh damn I forgot: I rename every interface you put into Anbox to wlan0, so Android can use it's standard wpa_supplicant on the   interface (the driver that decrypts wpa wifi networks). So your tunnel interface is actually the one renamed to wlan0 in the container. 

What really surprises me is the fact, that you standard wifi interface did not work. Could be something about the wpa_supplicant...

**Comment by PSGXerus** [comment]
I am close to finishing. Just need to find a way to patch Android sources from within the build process. If this is done, I'll open a pull request. May happen this weekend.

**Comment by PSGXerus** [comment]
Pull request [1378](https://github.com/anbox/anbox/pull/1378) should fix this issue.

**Comment by Old-iddi** [comment]
Great, will check it out!

**Comment by Adobrinin** [comment]
> Pull request [1378](https://github.com/anbox/anbox/pull/1378) should fix this issue.

I spent a lot of time, but did not get it work. My host machine is still use bridged network, Wi-Fi settings are not available. You mentioned new snap variables, but I was not able to find in docs how to use it. Please advise. Thanks!

**Comment by y-shevchenko** [comment]
> You can give it a try, if you add the tunnel as my parameter and then $ anbox.shell into the anbox container and check if it has picked it up correctly.

What parameter are we talking about?
