### ISSUE TITLE
microphone not work

### ISSUE THREAD

**Issue by gzivdo** [anbox/anbox#1215]
After installing beta or edge via snap on cleanly installed ubuntu 19.04 there is no sound, no pulseaudio connection, still fix from https://github.com/anbox/anbox/issues/904 not integrated. But even after applying that fix microphone not work, only playback stream appears in pulse sinks.
Is it supposed to be working or not?

**Comment by rizzini** [comment]
Same thing here. After the applied fix https://github.com/anbox/anbox/issues/904, the playback works just fine, but the microphone still doesn't.

**Comment by xslendix** [comment]
Reviving this problem. Same situation on Arch linux
