### ISSUE TITLE
Cannot add PPA: 'ppa:~morphis/ubuntu/anbox-support'.

### ISSUE THREAD

**Issue by Jacky323** [anbox/anbox#1219]
hi, guys. 
I installed anbox in my first time, but In my Ubuntu virtualmachine, when I entered command "sudo add-apt-repository ppa:morphis/anbox-support", I received an ERROR like this:

Cannot add PPA: 'ppa:~morphis/ubuntu/anbox-support'.
ERROR: '~morphis' user or team does not exist.

anyone can help me ? thanks a lot☺☺☺

**Comment by rizzini** [comment]
Try to check if your name resolution is Ok. The ppa is fine.

**Comment by Theocrat** [comment]
I have just had this same problem. I think there is something wrong with the PPA. Can you double-check, please?

**Comment by viraj28** [comment]
> Try to check if your name resolution is Ok. The ppa is fine.

how to check that?

**Comment by rizzini** [comment]
> > Try to check if your name resolution is Ok. The ppa is fine.
> 
> how to check that?

@viraj28, If you Google it, you'll find tons of guides.
