### ISSUE TITLE
Install Bug with snap in Linux Mint 17.3

### ISSUE THREAD

**Issue by pdcxs** [anbox/anbox#122]
Install anbox with the following command:
`sudo snap install --classic anbox-installer && anbox-installer`

it prints the error:
```
modprobe: FATAL: Module binder_linux not found.
```

**Comment by kobeumut** [comment]
You firstly install snapd.
`sudo apt install snapd` then 
`sudo snap install --classic anbox-installer && anbox-installer`

This way the process is complete.

**Comment by morphis** [comment]
Can you try again with the latest version of the anbox snap? We fixed quite a few bugs and it is very likely your problem is now fixed. Please feel free to open another bug if it still doesn't work for you.
