### ISSUE TITLE
Google Opinion Rewards app

### ISSUE THREAD

**Issue by Joe23232** [anbox/anbox#1220]
If I were to run [Google Opinion Rewards](https://play.google.com/store/apps/details?id=com.google.android.apps.paidtasks) app on Anbox. would it run or is it dependent on some play store service or something that Anbox is not able to support?

**Comment by rizzini** [comment]
It doesn't work with or without google play..

**Comment by Joe23232** [comment]
@rizzini How come it doesn't work? Is there a way to make it work?

**Comment by rizzini** [comment]
I don't know. I'm just an enthusiast user. When I saw your issue, I happened to be testing some apps.

**Comment by Joe23232** [comment]
Oh I see, what error message did you see or something?

**Comment by rizzini** [comment]
I didn't do the troubleshoot. It just crashed.

**Comment by Joe23232** [comment]
I see.

**Comment by Joe23232** [comment]
https://www.linuxuprising.com/2018/07/anbox-how-to-install-google-play-store.html

I think this needs to be done first.

**Comment by rizzini** [comment]
> https://www.linuxuprising.com/2018/07/anbox-how-to-install-google-play-store.html
> 
> I think this needs to be done first.

I did that. That's why I could do the test with and without google play.

**Comment by Joe23232** [comment]
@rizzini Shit that's bad I thought you there was a lack of play services or something.
