### ISSUE TITLE
Is there any possibility that apps can access all my linux user data?

### ISSUE THREAD

**Issue by Hbzzw** [anbox/anbox#1221]

**Comment by rizzini** [comment]
This always has been a strugle with Android. Some ROMs are compilling CIFS within the kernel, but it's awfully rare to find it. The best way nowadays is to compilling it yourself. I had no ideia how to do that.

This way, you could mount a SAMBA share on your Android. Imagine how cool that would be?

https://www.google.com/search?ei=deFrXcKkDMem5OUPrJ-y2AY&q=smb+kernel+android+module&oq=smb+kernel+android+module&gs_l=psy-ab.3...2338.2338..2633...0.0..0.111.111.0j1......0....1..gws-wiz.sIu2uKb-brc&ved=0ahUKEwiCs9qH9q_kAhVHE7kGHayPDGsQ4dUDCAo&uact=5

**Comment by Hbzzw** [comment]
> This always has been a strugle with Android. Some ROMs are compilling CIFS within the kernel, but it's awfully rare to find it. The best way nowadays is to compilling it yourself. I had no ideia how to do that.
> 
> This way, you could mount a SAMBA share on your Android. Imagine how cool that would be..
> 
> https://www.google.com/search?ei=deFrXcKkDMem5OUPrJ-y2AY&q=smb+kernel+android+module&oq=smb+kernel+android+module&gs_l=psy-ab.3...2338.2338..2633...0.0..0.111.111.0j1......0....1..gws-wiz.sIu2uKb-brc&ved=0ahUKEwiCs9qH9q_kAhVHE7kGHayPDGsQ4dUDCAo&uact=5

Wow a bot.
