### ISSUE TITLE
Anbox não inicia.

### ISSUE THREAD

**Issue by GabrielGamer0** [anbox/anbox#1227]
Eu estou no Linux Mint 19.02 Mate, não estou conseguindo abrir,  a instalação ocorreu tudo certo, mais quando eu inicio ele aparece uma tela de start, logo apos facha sozinho.
auguem sabe como corrigir esse erro.

**Comment by rizzini** [comment]
Quando você vai criar um post tem algumas coisas escritas, certo? Segue aqueles passos para a galera aqui poder te ajudar. E tem que posta em inglês.

**Comment by morphis** [comment]
Please keep all issues in English, otherwise it gets hard for us to help you. Thanks!

**Comment by caasciiafricano** [comment]
can someone help, I having issues with Anbox, I get it from snap repositories and installed on Ubuntu OS all things was alright but when I try to run it stop after showing "Starting..."


![Screenshot from 2024-01-15 00-06-10](https://github.com/anbox/anbox/assets/91435078/0122b93c-7901-4b9c-8f5f-d3365175af93)
