### ISSUE TITLE
Failed to connect to socket /run/anbox-container.socket: No such file or directory

### ISSUE THREAD

**Issue by Connor124** [anbox/anbox#123]
**System**:
Running kernel: 4.9.0-2-amd64
Distro: Debian 9
Anbox: 0.1.0 ( The most recent at time of writing. )

**Problem:**
Binder_Linux was compiled from source because the precompiled version didn't play nice with my system.
Anbox was installed via the anbox-installer script that was modified slightly to allow installation on unsupported systems. (I added "Debian" in the supported distros list)
When I run `anbox session-manager` I get `Failed to connect to socket /run/anbox-container.socket: No such file or directory`
I have tried "reverse-engineering" the installer script and manually compiling everything.

Any help is appreciated.

**Comment by gasinvein** [comment]
Is container-manager running?

**Comment by Connor124** [comment]
No, `Android image does not exist at path "/var/lib/anbox/android.img"`

**Comment by gasinvein** [comment]
So try to place [image](http://build.anbox.io/android-images/2017/04/12/android_1_amd64.img) there, run `sudo anbox container-manager`, then `anbox session-manager`.

**Comment by Connor124** [comment]
Does the image need special permissions, etc. Because, it is still not found.

**Comment by gasinvein** [comment]
Maybe you should post there #114

**Comment by Connor124** [comment]
I posted a solution to #114. But now, of course, there's another error that happens when I run anbox launch: `Stop waiting as we're already waiting for too long. Something is wrong with your setup and the container may have failed to boot.`

**Comment by FHFS** [comment]
After fixing binder, i am running into the same problem.
> [fhfs@fhfs-Arch anbox-binder]$ anbox session-manager
[EE 2017-06-03 17:10:46] [daemon.cpp:58@Run] Failed to connect to socket /run/anbox-container.socket: No such file or directory

I do have the image.
> [fhfs@fhfs-Arch anbox-binder]$ ls /var/lib/anbox/
android.img

But i am unable to run container manager.
> [fhfs@fhfs-Arch anbox-binder]$ sudo anbox container-manager
[WW 2017-06-03 17:12:12] [container_manager.cpp:58@operator()] You are running the container manager manually which is most likely not
[WW 2017-06-03 17:12:12] [container_manager.cpp:59@operator()] what you want. The container manager is normally started by systemd or
[WW 2017-06-03 17:12:12] [container_manager.cpp:60@operator()] another init system. If you still want to run the container-manager
[WW 2017-06-03 17:12:12] [container_manager.cpp:61@operator()] you can get rid of this warning by starting with the --daemon option.
[WW 2017-06-03 17:12:12] [container_manager.cpp:62@operator()]
[EE 2017-06-03 17:12:12] [container_manager.cpp:97@operator()] boost::filesystem::create_directories: Invalid argument
[fhfs@fhfs-Arch anbox-binder]$ anbox launch
[WW 2017-06-03 17:13:19] [launch.cpp:111@operator()] Anbox session manager service isn't running, trying to start it.
[EE 2017-06-03 17:13:19] [daemon.cpp:58@Run] Could not create renderer

**Comment by Towdium** [comment]
Same problem as @FHFS . 

> [towdium@Towdium-PC ~]$ anbox session-manager[EE 2017-07-06 03:44:57] [daemon.cpp:58@Run] Failed to connect to socket /run/anbox-container.socket: No such file or directory
[towdium@Towdium-PC ~]$ sudo anbox container-manager --android-image=/var/lib/android.img
[WW 2017-07-06 03:45:03] [container_manager.cpp:58@operator()] You are running the container manager manually which is most likely not
[WW 2017-07-06 03:45:03] [container_manager.cpp:59@operator()] what you want. The container manager is normally started by systemd or
[WW 2017-07-06 03:45:03] [container_manager.cpp:60@operator()] another init system. If you still want to run the container-manager
[WW 2017-07-06 03:45:03] [container_manager.cpp:61@operator()] you can get rid of this warning by starting with the --daemon option.
[WW 2017-07-06 03:45:03] [container_manager.cpp:62@operator()] 
[EE 2017-07-06 03:45:03] [container_manager.cpp:97@operator()] boost::filesystem::create_directories: Invalid argument

When trying to launch, I get:

>[towdium@Towdium-PC ~]$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[WW 2017-07-06 03:44:35] [launch.cpp:116@operator()] Anbox session manager service isn't running, trying to start it.
[WW 2017-07-06 03:44:40] [launch.cpp:116@operator()] Anbox session manager service isn't running, trying to start it.
[WW 2017-07-06 03:44:45] [launch.cpp:116@operator()] Anbox session manager service isn't running, trying to start it.
[EE 2017-07-06 03:44:50] [launch.cpp:166@operator()] Couldn't get a connection with the session manager

I'm running archlinux(manjaro), all anbox packages are installed from AUR

**Comment by kriku** [comment]
same issue

[system-info](https://gist.github.com/kriku/e4f1358fce06da060247ac4939941575)

**Comment by gtcdevop** [comment]
any news on that?

**Comment by palxex** [comment]
Same Problem here. After some digging, I found the problem on my machine: the data_path_ is empty, complete blank( and android-image, privileged, daemon - all the same ). Don't know whether other guy has same reason.
Manjaro with AUR anbox-git.

**Comment by xsacha** [comment]
@palxex : I get the exact same issue. It appears to be related to boost and networking.
When it crashes, I also receive the following message in my container:
[ 2017-11-29 07:02:23] [lxc_container.cpp:93@setup_network] Anbox bridge interface 'anbox0' doesn't exist. Network functionality will not be available

**Comment by palxex** [comment]
@xsacha that could be eliminated by 
```
nmcli con add type bridge ifname anbox0 -- connection.id anbox-net ipv4.method shared ipv4.addresses 192.168.250.1/24
```
as mentioned in #270. But after that, the whole system still cannot work.

**Comment by xsacha** [comment]
Yeah just fixed the networking.
Pretty sure the thread local storage crash isn't the actual issue.

**Comment by mountaineerbr** [comment]
Same...

**Comment by GNUGradyn** [comment]
Same problem, arch linux

**Comment by genius-ua** [comment]
Arch, aur, still the same problem

**Comment by inanahammad** [comment]
same issue,manjaro

**Comment by fikimaul** [comment]
Same problem in manjaro. i using anbox-git from aur

**Comment by raulsaavedr** [comment]
Same problem here my system info:
version: 0.0~git20190124-1-Debian
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i5 CPU       M 460  @ 2.53GHz
  features: 
os:
  name: Debian GNU/Linux
  version: 10 (buster)
  snap-based: false
kernel:
  version: Linux version 4.19.0-5-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08)
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 2.0 Mesa 18.3.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_texture_3D
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
      - GL_OES_EGL_image
      - GL_OES_depth_texture
      - GL_OES_packed_depth_stencil
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_OES_get_program_binary
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_EXT_frag_depth
      - GL_NV_fbo_color_attachments
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_robustness
      - GL_EXT_texture_rg
      - GL_EXT_unpack_subimage
      - GL_NV_draw_buffers
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_EXT_draw_buffers
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_KHR_robustness
      - GL_OES_required_internalformat
      - GL_OES_surfaceless_context
      - GL_EXT_separate_shader_objects
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_texture_border_clamp
      - GL_KHR_blend_equation_advanced
      - GL_KHR_context_flush_control
      - GL_OES_draw_elements_base_vertex
      - GL_OES_texture_border_clamp
      - GL_KHR_no_error
      - GL_EXT_shader_framebuffer_fetch_non_coherent

**Comment by Yamboy1** [comment]
Still a problem from AUR

**Comment by Hyperborea284** [comment]
Same problem here in Debian 10, realized that about six months ago.

**Comment by droidmahn** [comment]
Running into this issue on debian 10 as well

**Comment by Dragon8oy** [comment]
Issue also present on Debian Sid

**Comment by ningacoding** [comment]
same issue on Fedoraremix

**Comment by mountaineerbr** [comment]
Clean up your environment, guys.

**Comment by eternalodball029** [comment]
kk

**Comment by eternalodball029** [comment]
> Clean up your environment, guys.

how?

**Comment by CHJ85** [comment]
Same problem here.
Ubuntu 20.10.
Tested both snap and apt version from the main repo.

**Comment by Spartan322** [comment]
Receiving this problem on Manjaro Arch Kernel: 5.4.80-2-MANJARO installed via anbox-git through aur

**Comment by tima-chan** [comment]
Linux Mint Lmde4, same problem...

**Comment by Pan00Pernicek** [comment]
same issue in Alpine

**Comment by Anhad-source** [comment]
in the /run directory, we could find the anbox-container.socket file and put in in that directory

**Comment by binarytrails** [comment]
Fixed it on Arch with: 
```sudo systemctl start anbox-container-manager```

see steps at: https://wiki.archlinux.org/title/Anbox#Install_Anbox

**Comment by Anhad-chugh** [comment]
We need the anbox-container.socket file to be installed. It needs to be in directory /run.
