### ISSUE TITLE
Can we run Anbox apps by typing a command in terminal

### ISSUE THREAD

**Issue by NewtronReal** [anbox/anbox#1231]
Can we run Anbox apps by typing a command in terminal

**Comment by PSGXerus** [comment]
Check out the command "anbox launch --help"

**Comment by Dimonoid1985** [comment]
Добрый день, прошу подсказать работает ли anbox без gui?
Моя система GA-e3000n, 4Gb, 2Tb, стоит ubuntu 18.04 LTS без gui.
Подключен мини-ПК к телевизору по hdmi, стоит kodi в автозапуске, transmission, samba.
Дети попросили расширить функционал до андройд приставки, я установил по инструкции anbox, но тот отказывается запускаться из терминала, выдает:
sudo anbox session-manager
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
Stack trace (most recent call last):
#26 Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in
#25 Object "/snap/anbox/158/usr/bin/anbox", at 0x4a8b28, in _start
#24 Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb67029e82f, in __libc_start_main
#23 Object "/snap/anbox/158/usr/bin/anbox", at 0x4a401e, in main
#22 Object "/snap/anbox/158/usr/bin/anbox", at 0x4bae57, in anbox::Daemon::Run(std::vector<std::__cxx11::basic_string<char, std::char_traits, std::allocator >, std::allocator<std::__cxx11::basic_string<char, std::char_traits, std::allocator > > > const&)
#21 Object "/snap/anbox/158/usr/bin/anbox", at 0x4b005f, in anbox::cli::CommandWithSubcommands::run(anbox::cli::Command::Context const&)
#20 Object "/snap/anbox/158/usr/bin/anbox", at 0x4afb21, in anbox::cli::CommandWithFlagsAndAction::run(anbox::cli::Command::Context const&)
#19 Object "/snap/anbox/158/usr/bin/anbox", at 0x4dd9a2, in
#18 Object "/snap/anbox/158/usr/bin/anbox", at 0x51c26b, in anbox::platform::create(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, std::shared_ptr const&, anbox::graphics::Rect const&, bool)
#17 Object "/snap/anbox/158/usr/bin/anbox", at 0x521a50, in anbox::platform::sdl::Platform::Platform(std::shared_ptr const&, anbox::graphics::Rect const&, bool)
#16 Object "/snap/anbox/158/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fb671b36396, in
#15 Object "/snap/anbox/158/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fb671bceee0, in
#14 Object "/snap/anbox/158/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fb671be27cc, in
#13 Object "/snap/anbox/158/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fb671be11d0, in
#12 Object "/snap/anbox/158/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fb671bcff22, in
#11 Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fb67122dfa0, in dlopen
#10 Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fb67122e570, in
#9 Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb6727da573, in
#8 Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fb67122df08, in
#7 Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb6727dedb8, in
#6 Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb6727da573, in
#5 Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb6727df8f1, in
#4 Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb6727da7da, in
#3 Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb6727da6c9, in
#2 Object "/snap/anbox/158/usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3", at 0x7fb66718d408, in
#1 Object "/snap/anbox/158/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9", at 0x7fb67100a832, in google::protobuf::internal::OnShutdown(void (*)())
#0 Object "/snap/anbox/158/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9", at 0x7fb67100a516, in google::protobuf::internal::Mutex::Lock()
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault

Если без GUI не работает, тогда прошу, подскажите легкую оболочку, безпроблемно отключаемую и не прописывающуюся в автозапуске.
Прошу помощи, я новичок, и найти не смог решения проблемы в интернете и на Вашем сайте.
Заранее спасибо.

**Comment by DrSensor** [comment]
>Check out the command "anbox launch --help"

```console
$ anbox launch --help
NAME:
launch - Launch an Activity by sending an intent

USAGE:
launch [command options] [arguments...]

OPTIONS:
--action                         Action of the intent
--type                           MIME type for the intent
--uri                            URI used as data within the intent
--package                        Package the intent should go to
--component                      Component of a package the intent should go
--use-system-dbus                Use system instead of session DBus
--stack                          Which window stack the activity should be started on. Possible: default, fullscreen, freeform
```
@PSGXerus How? :joy: 
<sub>let's say I want to run webview browser</sub>
```console
$ adb shell 'pm list packages | grep webview'
package:com.android.webview
package:org.chromium.webview_shell
```
