### ISSUE TITLE
Installer fails

### ISSUE THREAD

**Issue by richardxday** [anbox/anbox#124]
Installer running on Ubuntu 16.10 (64-bit) fails with 'bad file descriptor' error:

richard@richard-thinkpad:\~/Downloads
$ snap install --classic anbox-installer && anbox-installer
error: access denied (try with sudo)
richard@richard-thinkpad:\~/Downloads
$ sudo snap install --classic anbox-installer && anbox-installer
[sudo] password for richard: 
anbox-installer 1 from 'morphis' installed
cannot create user data directory: /home/richard/snap/anbox-installer/10: Bad file descriptor
richard@richard-thinkpad:\~/Downloads
richard@richard-thinkpad:\~/Downloads
$ ls -l ~/snap
total 4
drwxr-xr-x 4 richard richard 4096 Apr 16 23:27 anbox-installer
richard@richard-thinkpad:\~/Downloads
$ ls -l ~/snap/anbox-installer/
total 8
drwxr-xr-x 2 richard richard 4096 Apr 16 23:27 10
drwxr-xr-x 2 richard richard 4096 Apr 16 23:27 common
lrwxrwxrwx 1 richard richard    2 Apr 16 23:27 current -> 10
richard@richard-thinkpad:\~/Downloads
$ 

Any suggestions?

Thanks,
Richard.

**Comment by haywshau** [comment]
+1
Same thing is happening for me on Ubuntu 16.04.2 LTS (64-bit)

**Comment by anibyl** [comment]
I have this issue too. 
```
$ anbox-installer 
cannot create user data directory: /home/anibyl/snap/anbox-installer/10: Bad file descriptor

$ stat /home/anibyl/snap/anbox-installer/10/
  File: '/home/anibyl/snap/anbox-installer/10/'
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 821h/2081d	Inode: 467047      Links: 2
Access: (0755/drwxr-xr-x)  Uid: ( 1000/  anibyl)   Gid: ( 1000/  anibyl)
Access: 2017-04-13 15:43:05.393564008 +0300
Modify: 2017-04-13 15:43:05.393564008 +0300
Change: 2017-04-13 15:43:05.393564008 +0300
 Birth: -

$ ls -l /home
lrwxrwxrwx  1 root   root     26 Лют 21 16:59 anibyl -> /media/Termas/home/anibyl/

$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
My home dir is linked via `ln` from other drive.
