### ISSUE TITLE
Implement support for binderfs instead of hardcoded paths

### ISSUE THREAD

**Issue by KOLANICH** [anbox/anbox#1240]
In Ubuntu Disco new version of binder module is used that uses binderfs instead of `/dev/binder`. The benefit and drawback is that it has to be explicitly mounted and then the files created with some ioctls. This benefits isolation. But anbox currently only has the hardcoded files paths. This should be fixed.

**Comment by KOLANICH** [comment]
stalebot and lockbot are shit and shouldn't be used

**Comment by mrvik** [comment]
This is a real issue when using the linux builtin binderfs support.
A temporary workaround is to run (as root):

```
mount -t binder binder /dev/binderfs #Or the location you prefer
ln -s /dev/binderfs/binder /dev/ #Change /dev/binderfs to the location specified above
```
Anyway, this is a ugly hack

**Comment by paulvi** [comment]
#20 
#1309
