### ISSUE TITLE
getevent and sendevent not working ?

### ISSUE THREAD

**Issue by rezaxdi** [anbox/anbox#1242]
Hi there,

I was trying to use getevent but i find out that the two input device (/dev/input/event0 and /dev/input/event1) don't really exist. When I use adb shell to get root access I'm not able to use getevent or sendevent on any of the inputs. The error I get is :

`could not open /dev/input/event1, No such device or address`
`could not open /dev/input/event0, No such device or address`

So how can I control the anbox input ? adb input is just so slow and can not be used.

**Comment by codoqwe** [comment]
actually!

**Comment by codoqwe** [comment]
please open issue

**Comment by codoqwe** [comment]
I tried this https://github.com/anbox/anbox/issues/603#issuecomment-511185295

I tried this but unfortunately it didn't help. Please tell me what to do.

**Comment by maysara9900** [comment]
I think this issue is still relevant, it would be helpful if someone can reopen it

**Comment by Fuseteam** [comment]
you guys.....can you at least describe the issue your experiencing?
