### ISSUE TITLE
Xpad Support/Passthrough.

### ISSUE THREAD

**Issue by Epsilon1033** [anbox/anbox#1246]
Could you please add support for the xpad kernel module? This would enable a wide variety of apps to take advantage of gamepads connected to the linux host. One use case would be playing android games that don't need the google play services with a controller instead of relying on mouse input. Thanks.

**Comment by trymeouteh** [comment]
I would like this also for gaming.

**Comment by zwastik** [comment]
Is it possible to play android games having gamepad support with anbox? Currently I am unable to play Pokemon Revolution Online with a ps3 controller (the app has gamepad support).
Thanks

**Comment by zwastik** [comment]
What is the status on this? is it possible to use a gamepad with anbox?
