### ISSUE TITLE
On Ubuntu MATE 19.04, only /dev/ashmem is created, not binder

### ISSUE THREAD

**Issue by superian** [anbox/anbox#1248]
There's a package for 19.04 on Launchpad, but...

```
me@disco:$ sudo apt-get install linux-headers-generic anbox-modules-dkms 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
linux-headers-generic is already the newest version (5.0.0.29.30).
linux-headers-generic set to manually installed.
The following NEW packages will be installed
  anbox-modules-dkms
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
Need to get 38.2 kB of archives.
After this operation, 214 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://ppa.launchpad.net/morphis/anbox-support/ubuntu disco/main amd64 anbox-modules-dkms all 13~disco1 [38.2 kB]
Fetched 38.2 kB in 0s (452 kB/s)            
Selecting previously unselected package anbox-modules-dkms.
(Reading database ... 358057 files and directories currently installed.)
Preparing to unpack .../anbox-modules-dkms_13~disco1_all.deb ...
Unpacking anbox-modules-dkms (13~disco1) ...
Setting up anbox-modules-dkms (13~disco1) ...
Loading new anbox-1 DKMS files...
Building for 5.0.0-29-generic
Building initial module for 5.0.0-29-generic
Secure Boot not enabled on this system.
Done.

ashmem_linux.ko:
Running module version sanity check.
 - Original module
 - Installation
   - Installing to /lib/modules/5.0.0-29-generic/updates/dkms/

binder_linux.ko:
Running module version sanity check.
 - Original module
 - Installation
   - Installing to /lib/modules/5.0.0-29-generic/updates/dkms/

depmod...
Job for systemd-modules-load.service failed because the control process exited with error code.
See "systemctl status systemd-modules-load.service" and "journalctl -xe" for details.

DKMS: install completed.

me@disco:$ sudo modprobe ashmem_linux
me@disco:$ sudo modprobe binder_linux
modprobe: ERROR: could not insert 'binder_linux': Operation not permitted
```

**Comment by andrewfer000** [comment]
Do a uname -a  command please. I think its a kernel 5.0 issue

**Comment by superian** [comment]
Yes, as per the headers and modules, it's 5.0.0-29.

Linux punch 5.0.0-29-generic #31-Ubuntu SMP Thu Sep 12 13:05:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by andrewfer000** [comment]
Yea Kernel 5.0.0-29 does not like binder unfortunately. I've been trying to find a workaround but it has no success. You may be able to build the modules manually and insert them though.

**Comment by sevu** [comment]
You can use a newer kernel. Ubuntu 19.10 is out just now, if it's an issue with 5.0 then that should solve it. I have it running with kernel 5.3 elsewhere.

**Comment by kraduk** [comment]
running patch 19.10 same issue

scott@testicle:~$ anbox system-info
version: 0.0~git20190124-1-Ubuntu
cpu:
  arch:  x86
  brand:         Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
os:
  name: Ubuntu
  version: 19.10 (Eoan Ermine)
  snap-based: false
kernel:
  version: Linux version 5.3.0-18-generic (buildd@lcy01-amd64-027) (gcc version 9.2.1 20190909 (Ubuntu 9.2.1-8ubuntu1)) #19-Ubuntu SMP Tue Oct 8 20:14:06 UTC 2019
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.0 Mesa 19.2.1
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_rgtc
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_texture_3D
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
      - GL_EXT_texture_sRGB_decode
      - GL_OES_EGL_image
      - GL_OES_depth_texture
      - GL_OES_packed_depth_stencil
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_NV_conditional_render
      - GL_OES_get_program_binary
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_EXT_frag_depth
      - GL_NV_fbo_color_attachments
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_robustness
      - GL_EXT_texture_rg
      - GL_EXT_unpack_subimage
      - GL_NV_draw_buffers
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_EXT_draw_buffers
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_KHR_robustness
      - GL_OES_depth_texture_cube_map
      - GL_OES_required_internalformat
      - GL_OES_surfaceless_context
      - GL_EXT_color_buffer_float
      - GL_EXT_sRGB_write_control
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_INTEL_performance_query
      - GL_EXT_base_instance
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_texture_border_clamp
      - GL_KHR_blend_equation_advanced
      - GL_KHR_context_flush_control
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_multisample_interpolation
      - GL_OES_texture_border_clamp
      - GL_EXT_blend_func_extended
      - GL_EXT_float_blend
      - GL_KHR_no_error
      - GL_OES_EGL_image_external_essl3
      - GL_EXT_clip_cull_distance
      - GL_EXT_disjoint_timer_query
      - GL_EXT_texture_compression_s3tc_srgb
      - GL_MESA_shader_integer_functions
      - GL_EXT_clip_control
      - GL_EXT_texture_compression_bptc
      - GL_KHR_parallel_shader_compile
      - GL_EXT_shader_framebuffer_fetch_non_coherent
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_texture_shadow_lod
      - GL_EXT_depth_clamp
      - GL_EXT_texture_query_lod
cscott@testicle:~$ system-infosystem-infosystem-infosystem-info

**Comment by sevu** [comment]
> version: 0.0git20190124-1-Ubuntu

maybe due to that

**Comment by damian101** [comment]
I have the same problem in Ubuntu 18.04, kernel v5.3
