### ISSUE TITLE
Build fails on Arch

### ISSUE THREAD

**Issue by hflw** [anbox/anbox#1252]
Hi,

It looks like there's a line causing compilation to fail on Arch Linux when installing through AUR. There's a thread talking about the error and a fix here: https://bbs.archlinux.org/viewtopic.php?id=249747

Thanks!

**Comment by sevu** [comment]
The fix is now included, by PR #1254

**Comment by sevu** [comment]
It could just be closed anyway, without bot … 
_But yeah, I think the bot is going to do that in 4  months._

**Comment by kinggx9** [comment]
`make[2]: *** [src/CMakeFiles/anbox-core.dir/build.make:1002: src/CMakeFiles/anbox-core.dir/anbox/input/manager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1682: src/CMakeFiles/anbox-core.dir/all] Error 2
`
I also got the same error on arch linux
Who can help me?
Thanks
