### ISSUE TITLE
Anbox binder_linux module not found

### ISSUE THREAD

**Issue by Dhamma-valence** [anbox/anbox#1262]
This isn't a problem with Anbox per se, but a module needed to run it. After running 

`sudo add-apt-repository ppa:morphis/anbox-support`

`sudo apt update`

`sudo apt install anbox-modules-dkms`

I expected to be able to load `ashmem_linux` and `binder_linux` with modprobe. However, after doing so, `ls -1 /dev/{ashmem,binder}` gives me the output 
`ls: cannot access '/dev/binder': No such file or directory
/dev/ashmem`

**Comment by sevu** [comment]
#1248

**Comment by ckane** [comment]
Install from the latest sources in GitHub at https://github.com/anbox/anbox-modules, not the package built above. The version in the PPA doesn't have support for 5.1+ kernels, which was added more recently.

The relevant change:
https://github.com/anbox/anbox-modules/commit/ae35b8da224b7ba163ebc1b3cf94acc2b0da260b
