### ISSUE TITLE
Any chance of different package formats? AppImage? Can't even install on Xubuntu 16.04.3

### ISSUE THREAD

**Issue by DwarfFighterCleric** [anbox/anbox#1264]
Followed all installation procedures twice, installed libudev1 (it was already here, the it says it can't find it, so I tried installing it again...) dkms, linux-headers-generic, snap install, the whole thing, modules are loaded, libudev.so.1 was always present, but apparently the program can't find it, made the symlink to libudev.so.0, etc etc etc
What's going on? Why is the Core snap not finding this libudev?

> error: cannot perform the following tasks:
> - Run install hook of "anbox" snap if present (run hook "install": /snap/core/7917/usr/lib/snapd/snap-confine: error while loading shared libraries: libudev.so.1: cannot open shared object file: No such file or directory)

I have a copy of the Core and Anbox snaps downloaded here, is there a way I can unsquashfs and manually insert the libudev.so.1 there before it is installed? will snap be able to install this modified package? Any chance of providing other types of packages as a form of release?

**Comment by DwarfFighterCleric** [comment]
Can someone explain me how the app searches for libudev.so.1 so I can "trick" it into seeing it? That library is installed in my system, I even installed it again an updated version, same thing, the links are all there in the system directory. The problem is that I can't add symlinks into the "Snap Core" directory itself because it is read-only.
And speaking of "read only", the Core snap doesn't even let me uninstall it. I don't think this is the best method to distribute this app, through snaps, it's so contrived of a format.

**Comment by DwarfFighterCleric** [comment]
Or another way of going about it: How could I modify the "Core" Snap before installing it so it includes the symlinks to libudev.so.1 inside of it? (again: after installed, the Core snap is read-only, I can't modify its directories and snap doesn't even let me remove it, I'm trying to workaround all that) Xubuntu 16.04

**Comment by morphis** [comment]
You're running into an issue with snapd rather than Anbox. Please report an issue on https://bugs.launchpad.net/snappy
