### ISSUE TITLE
Build fails on Arch due to window.cpp

### ISSUE THREAD

**Issue by mzs112000** [anbox/anbox#1265]
I am attempting to build Anbox from the AUR, however the build fails once it reaches window.cpp.

This is the full error it gives me:
EDIT: Since I can't figure out how to paste the error message while keeping formatting/readability intact, I've attached a screenshot instead.
![Screenshot_20191018_121307](https://user-images.githubusercontent.com/8335935/67121609-ca251500-f1a0-11e9-971f-fa8288b086c3.png)

I have installed linux-headers, and all make dependencies.
Is there any way to bypass this since I don't use Wayland anyways, and as such I have no use for Wayland support?

**Comment by gameltb** [comment]
3487fbf6422c47b4b877f7b15c860b64370df33e
