### ISSUE TITLE
Support >=mesa-19.2 (EGL_BAD_CONFIG)

### ISSUE THREAD

**Issue by shiznix** [anbox/anbox#1266]
$ EGL_LOG_LEVEL="debug" anbox session-manager --gles-driver=host

libEGL debug: Native platform type: surfaceless (build-time configuration)
libEGL debug: pci id for fd 20: 8086:3ea0, driver i965
libEGL debug: MESA-LOADER: dlopen(/usr/lib64/dri/i965_dri.so)

libEGL debug: found extension `DRI_Core'
libEGL info: found extension DRI_Core version 2
libEGL debug: found extension `DRI_IMAGE_DRIVER'
libEGL info: found extension DRI_IMAGE_DRIVER version 1
libEGL debug: found extension `DRI_DRI2'
libEGL debug: found extension `DRI_DriverVtable'
libEGL debug: found extension `DRI_ConfigOptions'
libEGL debug: found extension `DRI_Core'
libEGL debug: found extension `DRI_IMAGE_DRIVER'
libEGL debug: found extension `DRI_DRI2'
libEGL debug: found extension `DRI_DriverVtable'
libEGL debug: found extension `DRI_ConfigOptions'
libEGL info: found extension DRI_ConfigOptions version 1
libEGL debug: found extension `DRI_TexBuffer'
libEGL info: found extension DRI_TexBuffer version 3
libEGL debug: found extension `DRI2_Fence'
libEGL debug: found extension `DRI2_Flush'
libEGL info: found extension DRI2_Flush version 4
libEGL debug: found extension `DRI_IMAGE'
libEGL info: found extension DRI_IMAGE version 16
libEGL debug: found extension `DRI_RENDERER_QUERY'
libEGL debug: found extension `DRI_MutableRenderBufferDriver'
libEGL debug: found extension `DRI_CONFIG_QUERY'
libEGL debug: found extension `DRI_Robustness'
libEGL debug: found extension `DRI_NoError'
libEGL debug: found extension `DRI2_Blob'
libEGL debug: found extension `DRI_TexBuffer'
libEGL debug: found extension `DRI2_Fence'
libEGL info: found extension DRI2_Fence version 2
libEGL debug: found extension `DRI2_Flush'
libEGL debug: found extension `DRI_IMAGE'
libEGL info: found extension DRI_IMAGE version 16
libEGL debug: found extension `DRI_RENDERER_QUERY'
libEGL info: found extension DRI_RENDERER_QUERY version 1
libEGL debug: found extension `DRI_MutableRenderBufferDriver'
libEGL info: found extension DRI_MutableRenderBufferDriver version 1
libEGL debug: found extension `DRI_CONFIG_QUERY'
libEGL info: found extension DRI_CONFIG_QUERY version 1
libEGL debug: found extension `DRI_Robustness'
libEGL info: found extension DRI_Robustness version 1
libEGL debug: found extension `DRI_NoError'
libEGL info: found extension DRI_NoError version 1
libEGL debug: found extension `DRI2_Blob'
libEGL info: found extension DRI2_Blob version 1
libEGL debug: did not find optional extension DRI2_BufferDamage version 1
libEGL debug: did not find optional extension DRI2_Interop version 1
libEGL debug: did not find optional extension DRI_FlushControl version 1
libEGL debug: EGL user error 0x3005 (EGL_BAD_CONFIG) in eglCreateContext

[ 2019-10-19 09:43:36] [Renderer.cpp:141@initialize] Failed to create context: error=0x3005
Stack trace (most recent call last) in thread 27403:
#7    Object "", at 0xffffffffffffffff, in 
#6    Object "/lib64/libc-2.29.so", at 0x7f0c4cea16ee, in __clone
#5    Object "/lib64/libpthread-2.29.so", at 0x7f0c4d264457, in start_thread
#4    Object "/usr/bin/anbox", at 0x557cdfbb8eac, in emugl::Thread::thread_main(void*)
#3    Object "/usr/bin/anbox", at 0x557cdfaf01fa, in RenderThread::main()
#2    Object "/usr/bin/anbox", at 0x557cdfbb0c30, in renderControl_decoder_context_t::decode(void*, unsigned long, IOStream*)
#1    Object "/usr/bin/anbox", at 0x557cdfb4657e, in 
#0    Object "/usr/bin/anbox", at 0x557cdfb48be5, in RendererConfigList::getPackInfo(int*, int*) const
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault (core dumped)

**Comment by shiznix** [comment]
Downgrading back to Mesa-19.1 and Anbox works again.

**Comment by okias** [comment]
> libEGL debug: Native platform type: surfaceless (build-time configuration)

this is caused by #1260 . Since Gentoo changed default order of -Dplatforms passed to mesa.

**workaround** `EGL_PLATFORM=x11 ./anbox` (or wayland)

**Comment by shiznix** [comment]
Awesome, thanks @okias :)

Closing now, apologies for the unecessary noise.

**Comment by okias** [comment]
noise is good, at least is visible that Anbox missing autodetection of EGL_PLATFORM can be painful in some cases and will be soon fixed.
Maybe there is much more unsuccessful trial to get it runing on some distros, which ends due this issue.
