### ISSUE TITLE
Anbox WIFI connection

### ISSUE THREAD

**Issue by lhow** [anbox/anbox#1267]
I have a new Internet radio that lets control it via UNDOK app with Android. I want to control this radio with Anbox, It works fine with a smartphone connected via WIFI. 
Finally I managed to connect Anbox to the private network using the shell I found in 'https://github.com/anbox/anbox/blob/master/scripts/anbox-bridge.sh'. But the app 'UNDOK', installed in Anbox,  refuses to connect to  the radio, disclaiming there is no WIFI connection. I guess this app looks for a dedicated WIFI connection rather than a network connection.

Is there any possibility to solve this problem?

**Comment by morphis** [comment]
Anbox provides a ethernet connection to the Android container. It's up to the application to deal correctly with that.
