### ISSUE TITLE
Not working on Debian 10

### ISSUE THREAD

**Issue by jasonbrown1965** [anbox/anbox#1268]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

Nothing related to beta rejecting i686 as i386 despite Snaps working:
"error: snap "anbox" is not available on beta for this architecture (i386) but exists on other architectures (amd64)"

2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`

Not possible due to anbox not installing.

3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`

See 2 above.

4. Reproduce the error while debug logs enabled.

See 2 above.

5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

See 2 above.

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

See 2 above.

**Please describe your problem:**

Not able to proceed with installation beyond DKMS. 

**What were you expecting?:**

To be able to install !

**Additional info:**

**Comment by PureTryOut** [comment]
> "error: snap "anbox" is not available on beta for this architecture (i386) but exists on other architectures (amd64)"

Anbox currently doesn't support 32-bit x86 installations. Any x86 system since about 2004 supports 64-bit so there is no good reason to support those either. Are you sure your PC can't run a 64-bit OS?

**Comment by EchedeyLR** [comment]
> > "error: snap "anbox" is not available on beta for this architecture (i386) but exists on other architectures (amd64)"
> 
> Anbox currently doesn't support 32-bit x86 installations. Any x86 system since about 2004 supports 64-bit so there is no good reason to support those either. Are you sure your PC can't run a 64-bit OS?

Many PCs with a 64-bit CPU is not capable to run a modern (style and commonly used applications) due to limitations in motherboard around until 3GB RAM support or just low-spec (or old processors) support.

**Comment by PureTryOut** [comment]
I'm not sure I understand. Computers with 64-bit CPU's can run 64-bit operating systems. Could you list a specific limitation of a motherboard that would prevent this from being true? The amount of RAM doesn't matter, 64-bit OS's can run fine on low amounts of RAM such as 3GB.

**Comment by EchedeyLR** [comment]
> I'm not sure I understand. Computers with 64-bit CPU's can run 64-bit operating systems. Could you list a specific limitation of a motherboard that would prevent this from being true? The amount of RAM doesn't matter, 64-bit OS's can run fine on low amounts of RAM such as 3GB.

Yes, with high resources usage in most cases than if you try a 32 bit OS. This is why I said "modern".

**Comment by PureTryOut** [comment]
Well, it doesn't change the fact that Anbox doesn't support 32-bit x86 atm.

**Comment by EchedeyLR** [comment]
That it's true. (Sorry for the specific offtopic)

I don't think it will be available in a future however.

**Comment by EchedeyLR** [comment]
> To be fair, if you have too less RAM to use the 64bit variant, you might as well have too less CPU power to run anbox. It takes quite a bit …

Yes, in most cases could be true.

**Comment by narcisgarcia** [comment]
Following steps work on Debian 10 from scratch:

sudo apt install anbox
sudo modprobe ashmem_linux
sudo modprobe binder_linux
# Download an Android image from https://build.anbox.io/android-images/
sudo wget -O /var/lib/anbox/android.img https://build.anbox.io/android-images/2018/07/19/android_amd64.img
systemctl start anbox-container-manager

**Comment by PureTryOut** [comment]
@narcisgarcia yes it works fine on Debian, but not on Debian for 32-bit. If you had read the comments after the initial issue, you would've known the actual issue he was having.

**Comment by narcisgarcia** [comment]
The Debian 10 I'm using for this is amd64.

**Comment by PureTryOut** [comment]
Well... Obviouly...
