### ISSUE TITLE
[wayland support] replacing pbuffers

### ISSUE THREAD

**Issue by okias** [anbox/anbox#1270]
Since pBuffers will probably newer be implemented in Wayland [1] (2012), I guess there is time to think about trying different approach.

I could try implement alternative handling instead of pBuffers, but would be probably wisely if someone with better knowledge of EGL do it :)
Examples: Mozilla Firefox transition [2], Chromium transition from pBuffers [3]

[1] https://lists.freedesktop.org/archives/wayland-devel/2012-April/002928.html
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1462642
[3] https://codereview.chromium.org/2387063002/

Ref: https://github.com/anbox/anbox/issues/109

**Comment by morphis** [comment]
Thanks @okias. I have this already on my list of things I want to change in Anbox when I have time again.

**Comment by okias** [comment]
valid placeholder

**Comment by necessarily-equal** [comment]
I second this. For Anbox use on a phone, this is quite important, as every mobile interface seem to use Wayland nowadays: Plasma Mobile, Phosh or even Ubuntu Touch. X clients are blurry and cause issues: for instance, they are flowing out of screen.

Please implement proper Wayland support :-)

**Comment by Qiangong2** [comment]
Any update on this @morphis Sorry for the ping

**Comment by paju1986** [comment]
this is quite important, for wayland support for the current linux phones pinephone and librem 5

**Comment by okias** [comment]
@morphis if you found some time for this issue to tackle, it would be likely very helpful on phones. Mostly due to fact, that using XWayland translation layer causing also higher power consumption on these devices, so fixing this could greatly improve battery life.

As a bonus fix issues like #1615 and probably other non-reported yet :) (since Anbox hype on phones just began :laughing: )

**Comment by marty1885** [comment]
I've limited experience with SDL2 and GL. There seems to be more to the problem. SDL refuses to create an actual window on Wayland without a proper GL context (assigned to the window itself). Forcing SDL to use the context from Renderer looks like a messy job as SDL assumes ownership. 

I'll also donate 10$ US to the bounty. Do anyone have a actionable plain?

**Comment by paju1986** [comment]
okias, what about opening a bounty for this on bountysource ?

**Comment by paju1986** [comment]
Also I can add 50€ to the bounty

**Comment by coolavery** [comment]
You can put me down for $20 CAD, but it would be great if there was a Bountysource!

**Comment by okias** [comment]
Bounty moved into: https://www.bountysource.com/issues/95431410-bountysource-implement-native-wayland-support

**Comment by niclashoyer** [comment]
can this be reopened? I think graphics performance on phones using wayland is crucial.
