### ISSUE TITLE
Anbox fails to start Ubuntu 19.04

### ISSUE THREAD

**Issue by aplatypus** [anbox/anbox#1272]
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.

Yes, that's all done (see below).

5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**

Anbox just doesn't start because or something in the context.  I can't find a working directory or something that is plainly there.

'''
 $ ll /home/william/snap/anbox/158
total 8
drwxr-xr-x 2 william william 4096 Oct 23 17:38 ./
drwxr-xr-x 4 william william 4096 Oct 23 17:38 ../
```

Sample output and diagnostics below.


```
 $ anbox system-info
2019/10/24 17:40:07.220959 cmd_run.go:884: WARNING: cannot create user data directory: failed to verify SELinux context of /home/william/snap: exec: "matchpathcon": executable file not found in $PATH
2019/10/24 17:40:07.221047 cmd_run.go:529: WARNING: XAUTHORITY environment value is not a clean path: "/data/home/william/.Xauthority"
cannot create user data directory: /home/william/snap/anbox/183: Not a directory```
</details>

**Please describe your problem:**

Won't run

**What were you expecting?:**

I expected something to run.  When I used help, I expected a usage message or something.  _Nada_

**Additional info:**

Here is all I know or can find.

```
$ anbox.appmgr --help
2019/10/24 17:35:50.186436 cmd_run.go:884: WARNING: cannot create user data directory: failed to verify SELinux context of /home/william/snap: exec: "matchpathcon": executable file not found in $PATH
2019/10/24 17:35:50.186488 cmd_run.go:529: WARNING: XAUTHORITY environment value is not a clean path: "/data/home/william/.Xauthority"
cannot create user data directory: /home/william/snap/anbox/183: Not a directory
 $ ll /home/william/snap/anbox/158
total 8
drwxr-xr-x 2 william william 4096 Oct 23 17:38 ./
drwxr-xr-x 4 william william 4096 Oct 23 17:38 ../
```

Bug-Info output

```
This script will collect a few interesting things which developers will
need to have a better insight into the Anbox system when something goes
wrong.

PLEASE NOTE: The collected log files may collect information about your
system. Please have a look before you're sending them to anyone!

Collecting anbox log files ... 

DONE!

Do you want to include the kernel log of your system? [y/N]
Generating archive with all log files in /var/lib/snapd/void ...
  adding: container-manager.log (deflated 24%)
  adding: kernel.log (deflated 78%)
  adding: system-info.log (deflated 74%)
DONE!

Now please take the ZIP archive generated in your current directory
and attach it to your bug report. Please don't hesitate to have a
look into the archive before you do so to verify you don't leak any
information you don't want!
```

**Comment by Haksdeveloper** [comment]
[anbox-system-diagnostics-2020-01-22.zip](https://github.com/anbox/anbox/files/4095934/anbox-system-diagnostics-2020-01-22.zip)
