### ISSUE TITLE
Return of issue #1071

### ISSUE THREAD

**Issue by Kusoneko** [anbox/anbox#1276]
Hello, I'm running on Arch Linux, and I was attempting to make this compile however, for some reason I'm getting the exact same error (by same, I mean, I looked at the log posted there, and it's the same as mine except for the location of the anbox source code) as the presumably fixed issue #1071
In that same thread the fixer @Firenox89 shows the results of `pacman -Q --info protobuf` at the end of the post where he/she shows the solution, resulting in protobuf version 3.7.0-1. I did the same after trying to get it to work for a bit, and got protobuf version 3.10.0-1. I have looked at the fix offered by Firenox89 and it is still in the files mentioned so I'm guessing something likely changed between protobuf v3.7.0 and v3.10.0.

**Comment by Firenox89** [comment]
cmakes GREATER comparison isn't as smart as I hoped it to be.
```cmake
if (("3.10" GREATER "3.7"))
    message(is greater)
else()
    message(is lesser)
endif()
```
Prints `is lesser`.
So we would need a better version comparison.
After commenting out line 97 and 99 in the `CMakeLists.txt`, i could build again so this seems to be the only issue.

**Comment by Java-C0der** [comment]
> cmakes GREATER comparison isn't as smart as I hoped it to be.
> 
> ```cmake
> if (("3.10" GREATER "3.7"))
>     message(is greater)
> else()
>     message(is lesser)
> endif()
> ```
> 
> Prints `is lesser`.
> So we would need a better version comparison.
> After commenting out line 97 and 99 in the `CMakeLists.txt`, i could build again so this seems to be the only issue.

Hi, how do I apply that patch? When I clone the repo from the AUR, that file isn't there, it only appears after I run `makepkg`, but if I patch the file mid-compilation it obviously won't work...
Sorry, new user here. :stuck_out_tongue:

**Comment by Firenox89** [comment]
This code snippet was just for me to test the how the `GREATER` comparison works.
Just found that there is also a `VERSION_GREATER` which seems to do the right thing, I created a pull request.

**Comment by Kusoneko** [comment]
@Java-C0der I'm gonna quote the comment I made on the AUR about the temporary patch I made for this using the info above: 

```I went looking into the arch-wiki, and I'm coming back with this: https://github.com/Kusoneko/anbox-git-AUR-fix a patch file and the patched PKGBUILD so it applies the patch before building, so you can just download these and drop them over the original PKGBUILD, (and edit the PKGBUILD file to make anbox depend on the anbox-image package variant you wish to use, if it's not the default anbox-image one) and then makepkg -si and it works (just tested it and it builds and installs properly).```

It should work fine until #1280 gets merged.
