### ISSUE TITLE
[Question] xposed on Anbox? Is possible?

### ISSUE THREAD

**Issue by marcussacana** [anbox/anbox#1282]
I need install the xposed in the anbox because a certain game with anti-cheat detect the anbox USB Debug, looks like we can hide using a certain xposed module, anyway, I have already rooted using the rootfs overlay, but I don't have lucky installing the xposed in the same method, to me looks like i'm using the wrong xposed build, or maybe there are more changes out the rootfs and I don't know.
I tested with the: https://dl-xda.xposed.info/framework/sdk25/x86/ and https://github.com/youling257/XposedTools/releases

**Comment by baptx** [comment]
@marcussacana I noticed you closed the issue. Did you get Xposed working on Anbox? It was not working for me so I used Frida to bypass certificate pinning and root detection.
Related: https://android.stackexchange.com/questions/184754/how-do-i-install-xposed-framework-on-android-x86-running-in-virtual-box
