### ISSUE TITLE
Having problems installing Anbox on WSL with Ubuntu

### ISSUE THREAD

**Issue by Joe23232** [anbox/anbox#1293]
On Windows I enabled the Linux subsystem and I did install Ubuntu 18.04 LTS.

So I installed the kernel modules
https://docs.anbox.io/userguide/install_kernel_modules.html

And I have restarted cmd, but then after that I tried to run this command

`$ sudo modprobe ashmem_linux`

and it failed to run. I get this error.

```
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module ashmem_linux not found in directory /lib/modules/4.4.0-17134-Q
```

Do you know what is going on?

**Comment by sonic414** [comment]
The title is misleading. It should say "Having problems installing Anbox on **WSL** with Ubuntu. "

Also, it seems "modprobe doesn't work on WSL" .  Refer https://github.com/Microsoft/WSL/issues/3497

**Comment by Joe23232** [comment]
@sonic414 

Ok I have changed the title.

>Also, it seems "modprobe doesn't work on WSL" . Refer microsoft/WSL#3497 and microsoft/WSL#1893

THanks mate.

**Comment by beyondwudge** [comment]
I'm having the same problem.

**Comment by gabixdev** [comment]
Anbox depends on REAL Linux kernel, not just syscall emulation, use WSL2 instead.

**Comment by mahfuzullah** [comment]
see https://github.com/anbox/anbox/issues/1115?fbclid=IwAR1HBvRX3q8hldtYbNPBPxGZW02BGf9RPEsmsSTS5hNHbOa_buc8fnzNHXM
