### ISSUE TITLE
how to run armeabi-v7a architecture apks on anbox?

### ISSUE THREAD

**Issue by LUCARiO-Griphook** [anbox/anbox#1295]
I want to run armeabi-v7a arcitecture apks with anbox on my ubuntu 18.04. The error terminal shows is 
`adb: failed to install app_name.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]`

for any armeabi-v7a arcitecture apk I am trying to run.

**Comment by julianpoelmann** [comment]
i have the same error, all x86 and x64 thinks work so i assume its not emulating a cpu? idk same stuff happens on my android x86 pc except it just cant install those apps

**Comment by morphis** [comment]
You can only run ARM applications on ARM and x86 applications on x86. Anbox doesn't support running ARM applications on x86 unless there is a free solution to use to emulate ARM.

**Comment by ImGGAAVVIINN** [comment]
Have you checked out this?
https://www.linuxuprising.com/2018/07/anbox-how-to-install-google-play-store.html

**Comment by rzr** [comment]
> Have you checked out this? https://www.linuxuprising.com/2018/07/anbox-how-to-install-google-play-store.html

Interesting with this work with current andbox ?

**Comment by Fuseteam** [comment]
@rzr yes, that should still work with the current anbox
