### ISSUE TITLE
How to get and install F-Droid

### ISSUE THREAD

**Issue by narcisgarcia** [anbox/anbox#1298]
I'm testing anbox from Debian GNU/Linux 10 repositories, and the image 2018/07/19/android_amd64.img

There is "WebView Browser Tester 52.0.2743.100" and I use it to open f-droid.org website. Its home page shows perfect. There, I press over "Download F-Droid" but no download is started.
"Downloads" folder remains empty too.

**Comment by iko1** [comment]
try install it with 'android device bridge' AKA the command adb, for example

`adb install f-droid.apk`

wherever the APK file you just downloaded with desktop browser is located.
that browser you mentioned doesn't support downloads

**Comment by narcisgarcia** [comment]
How do I can download files using anbox?

**Comment by iko1** [comment]
You should install browser that supports modern technologies like file
downloading.

One method to do that is to download the actual 'APK' for 'f-droid' from
their official website, and after that install it with 'adb' after that you
can easily download apps using the installed 'f-droid' direct to running
anbox image

**Comment by narcisgarcia** [comment]
Sorry for my english and for my sharp words:

If no one of the proposals can be performed from Anbox itself (like downloading those APK packages), then Anbox has no basis to be tried by normal users.

**Comment by iko1** [comment]
How did you install Anbox, and what Linux distribution do you use?

**Comment by freechelmi** [comment]
Well this issue is the very start for users, please Reopen.
