### ISSUE TITLE
How to crontab restart anbox?

### ISSUE THREAD

**Issue by tianlu1677** [anbox/anbox#1299]
in my terminal console, I run anbox commend i got this error.
```
root@anbox:~# sudo /snap/bin/anbox.appmgr
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[ 2019-12-03 02:09:41] [daemon.cpp:61@Run] Failed to connect to DBus

```

But in my ubuntu desktop
Running same commend and I can start anbox. So can I start an box in my terminal? Because adb will offline anbox after  20 minutes, I do not why, I what crontab restart anbox

**Comment by eduardogoncalves** [comment]
Hi @tianlu1677 were you able to start anbox.appmgr from crontab?
