### ISSUE TITLE
Modules unable to install

### ISSUE THREAD

**Issue by EdwardElric64** [anbox/anbox#1301]
[anbox-system-diagnostics-2019-12-05.zip](https://github.com/anbox/anbox/files/3924875/anbox-system-diagnostics-2019-12-05.zip)

**Please describe your problem:**
Original attempt to add the PPA repo spits out 404 IP not found, using --allow-insecure-repositories spits out an error a package file was not found, then when trying to install anbox modules "Error! Bad return status for module build on kernel: 5.3.0-24-generic (x86_64)
Consult /var/lib/dkms/anbox/1/build/make.log for more information.
dpkg: error processing package anbox-modules-dkms (--configure):
 installed anbox-modules-dkms package post-installation script subprocess return
ed error exit status 10
Errors were encountered while processing:
 anbox-modules-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)"

**What were you expecting?:**
Modules to install

**Additional info:**
Attempting to run the the modules anyways shows nothing in terminal, and no new folders are created

**Comment by morphis** [comment]
This looks like you're trying to install on Ubuntu 19.10 which we're not going to support with the PPA as the standard kernel comes with both binder and ashmem. We don't surface that to the user yet but it's being worked on.
