### ISSUE TITLE
How to launch container manager and other components from local build?

### ISSUE THREAD

**Issue by theres-waldo** [anbox/anbox#1303]
I'm trying to run Anbox from a local build.

The README says "Running Anbox from a local build requires a few more things you need to know about. Please have a look at the "Runtime Setup" documentation."

I did have a look at that page, which describes various components like the container manager and the session manager. However, it does not actually describe how to launch these components.

What are the commands to launch these various components?

**Comment by pkillnine** [comment]
I just found out by looking at the [arch package](https://aur.archlinux.org/cgit/aur.git/tree/anbox-container-manager.service?h=anbox-git) that you run `anbox container-manager`.

**Comment by theres-waldo** [comment]
I discovered this too after looking through the `scripts` directory. However, `anbox container-manager` requires some particular flags, and I guess `anbox session-manager` does as well; I haven't been able to get both of them to launch successfully yet.

**Comment by pkillnine** [comment]
I haven't been able to successfully launch the anbox application manager yet. I did have container-manager running, but the session-manager keeps failing to connect to it.

**Comment by suchb** [comment]
any update?

**Comment by xiaobai20181017** [comment]
Did you@theres-waldo solve the problem?can you share it

**Comment by xiaobai20181017** [comment]
> I discovered this too after looking through the scripts directory. However, anbox container-manager requires some particular flags, and I guess anbox session-manager does as well; I haven't been able to get both of them to launch successfully yet.

Did you solve this problem?can you share the steps?

**Comment by theres-waldo** [comment]
Sorry, I have not had a chance to look further at this. (And the lack of response from project maintainers / people familiar with how it works isn't very encouraging.)
