### ISSUE TITLE
MicroG integration

### ISSUE THREAD

**Issue by batonac** [anbox/anbox#131]
The microG Project is exploring open-source (re)implementation of all of Google's proprietary pieces of Android, including the potential for providing access to the Google Play Store to download and update applications.

It would be interesting to explore collaboration opportunities of merging these layers together for delivering Google Play apps in anbox: [microg.org](https://microg.org/)

**Comment by morphis** [comment]
See https://github.com/anbox/anbox/issues/27#issuecomment-293486105 for more details on this.
