### ISSUE TITLE
Ability to create prefixes (bottles)

### ISSUE THREAD

**Issue by trymeouteh** [anbox/anbox#1318]
WINE allows you to create prefixes which allow you to have several virtual C:/ drives so you can install each Windows application on a separate WINE prefix. Please allows this for Anbox.

I would like to make some Anbox prefixes have access to my Linux root folder, some prefixes will have games which will be locked down and sealed and some prefixes for other applications.

**Comment by morphis** [comment]
You can do this already today with the parallel install feature of snaps. See https://snapcraft.io/docs/parallel-installs for details.
