### ISSUE TITLE
Manage Anbox versions

### ISSUE THREAD

**Issue by trymeouteh** [anbox/anbox#1319]
PlayOnLinux allows us to download and manager different WINE versions which is helpful for having the best version of WINE for each application. I would like Anbox to have this also were you can choose what version of Anbox is used to run certain apps or within certain Anbox prefixes.

There are going to be may Android games that will not be updated to work on newer versions of Android and to be able to control your Anbox version will allow you to use older Android apps forever even when the modern day version of Android in the future is not compatible with the older app.

**Comment by morphis** [comment]
Anbox currently doesn't support more than a single Android version so there is no need for such a thing.  Anbox wants to provide a modern and up-to-date (ideally with latest security updates included) Android environment a user can trust. Providing more than a single Android version is unrealistic given that this is just a community project without much development capacity. WINE is completely different as they don't have to maintain a full OS but just their own reimplementation of the relevant Windows libraries.
