### ISSUE TITLE
Add to Debian and Arch repos and add PPA

### ISSUE THREAD

**Issue by trymeouteh** [anbox/anbox#1321]
I do think Anbox is gonna be huge and is essential just like WINE is for allowing Windows apps to run on Linux.

WINE is easily available in the Debian repos, arch repos and as a PPA. I think Anbox needs to do the same. Arch will have a bleeding edge version available in its repos, the Debian version will be outdated but stable, the PPA will be bleeding edge for those who wants the latest on Ubuntu.

Snaps are not the way to go or at least the only way to go.

**Comment by 86423355844265459587182778** [comment]
For Arch Linux:

- AUR package is available and you can install Anbox easily by using the binary package provided by the [unofficial [archlinuxcn] repository](https://github.com/archlinuxcn/repo).

- There are some rules for a packages to enter the community repo. See [How to get a PKGBUILD into the community repository?](https://wiki.archlinux.org/index.php/Arch_User_Repository#How_to_get_a_PKGBUILD_into_the_community_repository?) and [Rules for Packages Entering the community Repo](https://wiki.archlinux.org/index.php/AUR_Trusted_User_Guidelines#Rules_for_Packages_Entering_the_.5Bcommunity.5D_Repo) for more information.

**Comment by morphis** [comment]
> Snaps are not the way to go or at least the only way to go.

We don't have the capacity to support anything other than the snap format. The community is free to package Anbox in whatever package format necessary but the official package format will remain based on snaps.
