### ISSUE TITLE
Error: retrieving gpg key timed out.

### ISSUE THREAD

**Issue by HemantJangid** [anbox/anbox#1324]
**Please describe your problem:**
I am not able to install it whenever i try to add the ppa through 
sudo add-apt-repository ppa:morphis/anbox-support
I get this error 
Error: retrieving gpg key timed out

**Comment by morphis** [comment]
This isn't an issue with Anbox or the PPA we've setup but one either with your network connection or the Ubuntu servers being temporarily unavailable.
