### ISSUE TITLE
GPS for app in Anbox

### ISSUE THREAD

**Issue by MparkG** [anbox/anbox#1328]
just a quick question, while i wait for the download of anbox to get done... 
basically if this is not given i dont need to try further.

i wanna run osmand in anbox.
i need gps for that and also some way to have the largely sized maps folder mounted accessible to the app.
I have a usb to serial converting gps dongle, that delivers /dev/ttyUSB0, which can then again be hosted to some network address via gpsd.

Can apps inside get access to gps data of the host system? Is a shared folder for maps possible?

Thanks

**Comment by tomasz-grobelny** [comment]
Did you manage to get osmand with gps running in anbox?
