### ISSUE TITLE
The program starts but can not execute

### ISSUE THREAD

**Issue by fedromab** [anbox/anbox#133]
The program starts but can not execute. Simply for this moment and then for. I'm using Ubuntu Mate 17.04.
Maybe it could be something with the version.

**Comment by aqking** [comment]
I also am using Ubuntu Mate 17.04. 
I just installed the Anbox  using the snap instructions at anbox.io  
I click on  **Applications /  Other /  Anbox**   -  and nothing happens.  

I installed Wine on this system yesterday, and it works great! (so far)
I notice there is now a new 326 MB volume mounted on my desktop.  Is this the Anbox folder?

**Comment by hub2git** [comment]
@aqking in the most recent comment says:
>  I notice there is now a new 326 MB volume mounted on my desktop. Is this the Anbox folder?
I also have a 326 MB volume that I see in my File Explorer (Linux Mint 18.1 Selenah Xfce). I click it, and see that it opens up /media/me/disk/ (where "/me/" is the name of my home folder).

Running `ls`shows the following: https://gist.github.com/anonymous/8f7c617e6a50f32c4799f3baee50af04

**Comment by morphis** [comment]
We have a lot similar issues. Either pick one which comes close to your one or extend the bug report with all information asked for in the issue template (https://github.com/anbox/anbox/blob/master/.github/ISSUE_TEMPLATE.md) and reopen.
