### ISSUE TITLE
Anbox loads w/ graphical problems.

### ISSUE THREAD

**Issue by linuxhelper** [anbox/anbox#1335]
Anbox doesn't appear to load on first run - but shows in system monitor. Launches on second attempt - but the GUI only displays a border w/ an image of whatever was behind it at launch.

I have installed, rebooted, uninstalled & reinstalled. Can I install an apk and run it anway?

I'm trying to use Anbox to run Cricut Design Space for Android.

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 5 3600X 6-Core Processor             
    CPU Family:  0x17
    CPU Model:  0x71
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  3800 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 19.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.3.0-26-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12005000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20191210.1

Video Card:
    Driver:  NVIDIA Corporation GeForce RTX 2060 SUPER/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 440.48.02
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 143 Hz
    VendorID:  0x10de
    DeviceID:  0x1f47
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 4480 x 1440
    Primary Display Size: 27.44" x 15.43" (31.46" diag)
                                            69.7cm x 39.2cm (79.9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 8192 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Nvidia GPU 93 HDMI/DP

Memory:
    RAM:  32128 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  937262 Mb
    Largest Free Hard Disk Block:  874291 Mb
    VR Headset: None detected

Runtime information tool temporarily disabled.

**Comment by allquixotic** [comment]
I had to copy the Nvidia proprietary blobs into /var/lib/snapd/lib as follows:

/usr/lib/x86_64-linux-gnu/{*nv*, libGL*, libEGL*} -> /var/lib/snapd/lib AND /var/lib/snapd/lib/gl
/usr/lib/x86_64-linux-gnu/nvidia/xorg/nvidia_drv.so -> /var/lib/snapd/lib/gl/xorg/nvidia_drv.so
You have to do the same for /usr/lib/i386-linux-gnu into /var/lib/snapd/lib32 if you want to use 32-bit apps running OpenGL.

This fixed Stellarium, Anbox and Ohmygiraffe snaps for me. Stellarium and Ohmygiraffe use regular OpenGL; Anbox uses EGL/GLES.

This is obviously an awful hack that has to be maintained whenever I update driver versions, so snapd needs to handle this better.

**Comment by jelabarre59** [comment]
Nope, I symlinked those, didn't do anything.  Anbox just opens a blank white window with the "Anbox Application Manager" title.  Have tried rebooting after removing Anbox, then rebooted again after re-installing the snap.  Nothing is happening.

**Comment by jelabarre59** [comment]
[anbox-system-diagnostics-2020-02-04.zip](https://github.com/anbox/anbox/files/4154697/anbox-system-diagnostics-2020-02-04.zip)

**Comment by Linnxam** [comment]
Same problem here
Starts up fine but the window is just filled white, you can click in random places it'll open up new windows like Calculator or Calendar but they also have the graphical error. 
Important note: On startup, it displays the Android mascot, the graphics problem only appears once it's launched
Using Debian in a virtual machine with a Qubes OS host (also tried a Whonix-WS, same problem)

**Comment by Linnxam** [comment]
The solution is to enable software rendering, depending on the application it will lag though.

snap set anbox software-rendering.enable=true
snap restart anbox.container-manager
