### ISSUE TITLE
Question about Anbox Cloud

### ISSUE THREAD

**Issue by gsantner** [anbox/anbox#1338]
Hey, I just found the announcement about Anbox Cloud <https://anbox-cloud.io/> <https://ubuntu.com/blog/anbox-cloud-disrupts-mobile-user-experience>.

Is that using Anbox as it's base or just uses the same name? I'm just curious why it has the same name. If not, any chance that this anbox or the canonical one get issues due same naming?

**Comment by CodeJoule** [comment]
In my opinion, that sounds like a question for Canonical.

**Comment by articlecat** [comment]
According to the whitepaper, Ubuntu's Anbox Cloud has absolutely nothing to do with Anbox.

**Comment by gsantner** [comment]
The point is: This project has alive since quite some time, and now comes the canonical project with quite the same name. theres a chance that this project will need to change name as guess canonical will do some trademark or alike.

**Comment by morphis** [comment]
The name is fine. I am running the team at Canonical responsible for Anbox Cloud. Have a look at https://mm.gravedo.de/blog/posts/2020-01-21-taking-the-anbox-journey-to-the-next-level/
