### ISSUE TITLE
Feature request: Redirect notifications to host

### ISSUE THREAD

**Issue by unikatt** [anbox/anbox#1340]
This is a feature request not a bug so standard template doesn't work here.
When an app receives a system notification (either through Push like Google Firebase Messaging or timers), there should be a means to show them on the host system.
This is especially useful in cases the user runs a mobile messenger inside Anbox (WhatsApp/Signal/you name it) but having the window closed/minimized, received push notifications should appear on the host's/desktop environment's notification system (e.g. Ubuntu Touch) in order to notify the user.

**Comment by unikatt** [comment]
I am a developer myself and could implement that feature, but I need some advice on the architecture of the solution (especially where to look for grabbing that notification from the running Android system inside Anbox, and how to transport it to the host).
My naive assumption would be:
1) Provide an APK, which implements NotificationListenerService and forwards the notification through a socket to the host
2) Have a service running on the host (part of anbox binary?) which listens on the socket and calls a desktop-enviroment-specific implementation (separate package) to issue that notification.

Any comment or ideas on this?

**Comment by nachum37** [comment]
I think is a great idea.

**Comment by NickWilde263** [comment]
> I think is a great idea.

YES (my school demand me to read like every second for WhatsApp)
