### ISSUE TITLE
Feature request:sensors communication with arduino

### ISSUE THREAD

**Issue by annopnod** [anbox/anbox#1345]
sensors communication with arduino is easy way

![Untitled 1](https://user-images.githubusercontent.com/6957642/73323981-e9414180-427b-11ea-844d-7c8174f1ec19.jpg)

sensors.ini has structure this
[Sensor]
GYROSCOPE=ArduinoGYROSCOPE.so
ACCELEROMETER=ArduinoACCELEROMETER.so

**Comment by annopnod** [comment]
sensors.ini after install anbox
[Sensor]
GYROSCOPE=DummyGYROSCOPE.so
ACCELEROMETER=DummyACCELEROMETER.so

folder at module/sensor/ 
DummyGYROSCOPE.so
DummyACCELEROMETER.so

and has sdk for compile and install
sdk is Template code
DummyGYROSCOPE.c
DummyACCELEROMETER.c

**Comment by Fuseteam** [comment]
that's nice and all but mind being more specific on about what you want anbox to do exactly?
