### ISSUE TITLE
Custom android image

### ISSUE THREAD

**Issue by P0oOOOo0YA** [anbox/anbox#1346]
Officail android image used by anbox is android 7. Is it possible to load another android image?

**Comment by atiti** [comment]
Any ideas on this? I'm wondering about the same?

**Comment by moceap** [comment]
If there custom patches for Anbox. Shouldn't  depend on Android image version.

**Comment by BiatuAutMiahn** [comment]
What would be neat is a recovery app (`anbox.recovery` or `anbox.twrp`) that runs twrp against the android image. That way we can use the tradition methods of modifying the image. Just a thought :P

**Comment by necessarily-equal** [comment]
there is some WIP for anbox android10 support https://github.com/sageyun1057/anbox; but you can't use the current master to run android10, as it require support for extra things like /dev/hwbinder.
