### ISSUE TITLE
Processor problem

### ISSUE THREAD

**Issue by laszloatoth** [anbox/anbox#1347]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
laci@Ferike:~$ snap install --devmode --beta anbox
error: cannot perform the following tasks:
- Run install hook of "anbox" snap if present (run hook "install": 
-----
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
The CPU of your computer (Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz) does not support all
features Anbox requires.
It is missing support for the following features: SSE 4.1, SSE 4.2, SSSE 3
You can for example find more information about SSE
here https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions
-----)

<summary>It seems because of the mentioned type of Intel processor the script is failed
I followed the description has been created for Anbox environment install </summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**
I would like to install & run apk (ANdroid) based apps on Ubuntu 18 LTS. It seems Old Intel processor is an obstacle?

**What were you expecting?:**
verification on what is the source of problem and how to create a work-around.

**Additional info:**

**Comment by morphis** [comment]
As the error says, your processor missed mandatory features to run Android. There is nothing easy we can do about this.
