### ISSUE TITLE
Anbox doesn't work after update boost to 1.72

### ISSUE THREAD

**Issue by arbehert** [anbox/anbox#1350]
![Screenshot at 23-22-48](https://user-images.githubusercontent.com/25900147/73575728-75708600-4481-11ea-8a08-d3daf0b57e23.png)

**Comment by zwastik** [comment]
I am having the exact same problem as you

**Comment by necessarily-equal** [comment]
you need to recompile the package after updating a dependency. This is part of the reason why it's safer to use a package manager, and part of the reason why it's easier to put something on the AUR ;)
