### ISSUE TITLE
Install apk Failure INSTALL_FAILED_NO_MATCHING_ABIS

### ISSUE THREAD

**Issue by lvzongting** [anbox/anbox#136]
When I install a apk by adb install com.tencent.mobileqq.apk
I get the error message:

Failed to install com.tencent.mobileqq.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

the build.prop of android.img download from build.anbox.io say the arch is x86_64, 
Some apk only support arm or x86

Expect:  the android.img in build.anbox.io supports arm

**Comment by gasinvein** [comment]
See #33

**Comment by jilen** [comment]
I wonder if it is possible to use [android x86](http://www.android-x86.org) image ? So that we can use any apk ?

**Comment by morphis** [comment]
@jilen We don't have any plans to do that. Community contributions welcome.
