### ISSUE TITLE
[Question] Does Anbox support MESA on KMS/DRM?

### ISSUE THREAD

**Issue by vanfanel** [anbox/anbox#1360]
Hi!

I was thniking on using Anbox to deploy an Android developed app on a Raspberry Pi 3b that runs an Xorg-less enviroment where SDL2 runs on MESA and KMSDRM.
So, is it possible to build Anbox without any X dependencies or even libdbus?

**Comment by necessarily-equal** [comment]
You can run Anbox in Wayland, theoretically. On the other hand, I don't know of a framebuffer backend integration, even if SDL may support it. (so I think it wouldn't work)

**Comment by vanfanel** [comment]
@Well, SDL2 does run on KMS/DRM (framebuffer, no X server needed at all), so why shouldnt it work in such an enviroment?

**Comment by necessarily-equal** [comment]
Well, if you find a way to get an EGL surface (and display?), you could add a backend; but I don't think it would work already. Feel free to try.

https://github.com/anbox/anbox/blob/master/src/anbox/platform/sdl/window.cpp#L83-102
