### ISSUE TITLE
adb: failed to install /home/liaoran/桌面/110_81ebf466a81ff53bb0cea9f314b56bfb.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

### ISSUE THREAD

**Issue by liaoransky** [anbox/anbox#1366]
adb: failed to install /home/liaoran/桌面/110_81ebf466a81ff53bb0cea9f314b56bfb.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by morphis** [comment]
You're trying to install an ARM only APK on an x86 system or vice versa. That is not supported and not going to work. You can only install x86 APKs on x86 systems and ARM APKs on ARM system.
