### ISSUE TITLE
How do I build it for an Arch-based distro

### ISSUE THREAD

**Issue by Joe23232** [anbox/anbox#1379]
So I am using an Arch-based distro and Anbox is not available in the AUR. So I was wondering since I am a Linux noob over here, how would I exactly build Anbox?

**Comment by hyperak** [comment]
Anbox is available in the AUR under [anbox-git](https://aur.archlinux.org/packages/anbox-git/). Some people recommended to [install the system image](https://aur.archlinux.org/packages/anbox-image/) before the other package so do that for good measure.

**Comment by Joe23232** [comment]
Hi @hyperak what does the system image do exactly?

**Comment by Joe23232** [comment]
@hyperak Hey man when I tried to install `anbox-image` I am getting a few options to what specific package I want to install.

```
: There are 5 providers available for anbox-image:
:: Repository AUR
    1) anbox-image 2) anbox-image-gapps 3) anbox-image-gapps-rooted 4) anbox-image-houdini 5) anbox-image-houdini-rooted
```

Which one should I use. if I chose the first option, would I still get root access if I am using the Android image?

**Comment by hyperak** [comment]
IIRC Houdini is an emulator that lets you run ARM-built applications on x86. Also, all suffixes are quite self-explanatory: -gapps has GApps _and_ Houdini (Google Apps: Play Store, Google Play Services etc), -rooted means the image comes rooted with SuperSu preinstalled, and -houdini has Houdini. I use anbox-image-gapps-rooted.

**Comment by ecv80** [comment]
I'm jealous of those packages for Archish... what a nice package maintainer.
