### ISSUE TITLE
Debian make fails with "no rule to make target 'gmock/libgmock.a"

### ISSUE THREAD

**Issue by Aebian** [anbox/anbox#1382]
Only issue I found here on the tracker was for arch and not directly related to my issue.
### sudo ldconfig -v | grep gtest
```
libgtest.so -> libgtest.so
  libgtest_main.so -> libgtest_main.so
ldconfig: /lib/x86_64-linux-gnu/ld-2.29.so is the dynamic linker, ignoring
```

### sudo ldconfig -v | grep gmock
```
libgmock_main.so -> libgmock_main.so
ldconfig: /lib/x86_64-linux-gnu/ld-2.29.so is the dynamic linker, ignoring
        libgmock.so -> libgmock.so
```

### Extact error is: 

```
[  3%] Built target GMock
[ 10%] Built target process-cpp
[ 13%] Built target emugen
[ 15%] Built target OpenglCodecCommon
[ 16%] Built target renderControl_dec
[ 18%] Built target GLESv2_dec
[ 20%] Built target GLESv1_dec
[ 25%] Built target emugl_common
[ 27%] Built target OpenGLESDispatch
[ 29%] Built target xdg
[ 30%] Built target xdg_test
[ 31%] Built target backward
[ 31%] Built target backward_object
[ 36%] Built target cpu_features
[ 37%] Built target list_cpu_features
[ 40%] Built target anbox-protobuf
[ 89%] Built target anbox-core
[ 90%] Built target anbox
make[2]: *** No rule to make target 'gmock/libgmock.a', needed by 'tests/anbox/android/intent_tests'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:1919: tests/anbox/android/CMakeFiles/intent_tests.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

```

### Steps I did after all requirements where installed / built
1.) git clone <repo-url>
2.) cd anbox
3.) mkdir build 
4.) cd build
5.) cmake ..
6.) sudo make install

I have built gtest and gmock from source 

### How I built googletest
```
git clone https://github.com/google/googletest.git
cd googletest
mkdir build && cd build
cmake .. -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr
make -j8
sudo make install
sudo ldconfig
```
### Second Confirmation that gtest framework is installed:
```
→ pkg-config --libs --cflags gtest
-DGTEST_HAS_PTHREAD=1 -lpthread -I/usr/lib/x86_64-linux-gnu/pkgconfig/../../include -L/usr/lib/x86_64-linux-gnu/pkgconfig/../../lib/x86_64-linux-gnu -lgtest -lpthread

```

What more info do you need to help me out?

**Comment by zorvios** [comment]
I'm having the same problem with Kubuntu 20.04

**Comment by 4ifi** [comment]
I have same problem on debian sid.
Package: googletest
Version: 1.10.0-2
Package: libgtest-dev
Version: 1.10.0-2

**Comment by 4ifi** [comment]
Hi guys! Fixed this problem with: sudo apt install libgmock-dev

**Comment by Aebian** [comment]
Sadly this package is already installed on mine anf the issue is still present :( 
@4ifi Any special packages you installed as well?

**Comment by 4ifi** [comment]
@Aebian I installed patch. `wget https://gitlab.alpinelinux.org/alpine/aports/raw/master/testing/anbox/fix-gtest-use.patch && patch -p1 < fix-gtest-use.patch`

**Comment by Aebian** [comment]
@4ifi You're lifesaver. Worked like a charm!

**Comment by necessarily-equal** [comment]
great that you found a solution! I've made a PR that should be backward compatible a few days ago ^

**Comment by chantzish** [comment]
I had the same problem:
`make[2]: *** No rule to make target 'gmock/libgmock.a', needed by 'tests/anbox/android/intent_tests'.  Stop.`
As it turn out the file 'libgmock.a' is in package `libgmock-dev`
`sudo apt install libgmock-dev` fixed the problem (no need to build googletest).

**Comment by GabeIggy** [comment]
Do I need a special PPA?

```
$ sudo apt install libgmock-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libgmock-dev
```

Ubuntu 18.04 LTS

**Comment by necessarily-equal** [comment]
Ah, it exists in 20.04 at least.

```
libgmock-dev/focal,now 1.10.0-2 amd64 [installed]
  Google's framework for writing C++ tests
```

Maybe the `google-mock` package would do it?

Note that, IIRC, you need a more recent CMake version to build Anbox 
than what's in 18.04.

On Sa, Jan 23, 2021 at 10:45, Gabriel Iggy N.
