### ISSUE TITLE
Too big audio latency

### ISSUE THREAD

**Issue by nihonium113** [anbox/anbox#1389]
My anbox was compiled from AUR, audio is pure alsa (without pulseaudio).
When i tried to launch, for example, Girls' Frontline sound was playing with a too big latency (nearly 2 seconds) and in console was output which said something like "alsa underrun is occurred ". Same with Settings' sound, so it isn't GF' bug.
My alsa is properly configured and works just fine with another apps.
I think that the cause of such trouble is in anbox' code (maybe, in audio_hw.cpp in defines, or in the audio_sink.cpp).
How should i change numbers in source code to get audio works proper?

**Comment by 4ifi** [comment]
I have this issue too. My system is devuan linux distro with alsa and openrc.
My log:
`ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred`

**Comment by pingplug** [comment]
the fix has added in this PR #1034 last year

but this fix didn't merged for some reason (maybe need recompile android image?)

**Comment by nihonium113** [comment]
> the fix has added in this PR #1034 last year

Well, i've just patched and compiled anbox with that fix, but things became even worse - sound completely disappers after 4-5 seconds (if pulseaudio is used, configuration is default) or there is no sound at all (if pure alsa is used)
Also, message `ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred` is still here if PA is used.

**Comment by pingplug** [comment]
> Well, i've just patched and compiled anbox with that fix, but things became even worse - sound completely disappers after 4-5 seconds (if pulseaudio is used, configuration is default) or there is no sound at all (if pure alsa is used)
> Also, message `ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred` is still here if PA is used.

you also need rebuild android image with that PR

**Comment by nihonium113** [comment]
Sooo... I just should do this - https://github.com/anbox/anbox/blob/master/docs/build-android.md ?
And should i do any changes on that step?

**Comment by ssz66666** [comment]
In case anyone also came across this problem, I've rebuilt the android image myself [https://github.com/ssz66666/anbox/releases/tag/v0.1-with-pr1034](https://github.com/ssz66666/anbox/releases/tag/v0.1-with-pr1034).

It would be great if someone could test it out.

**Comment by modyar** [comment]
> In case anyone also came across this problem, I've rebuilt the android image myself https://github.com/ssz66666/anbox/releases/tag/v0.1-with-pr1034.
> 
> It would be great if someone could test it out.

How can i replace with this file?

**Comment by pingplug** [comment]
> In case anyone also came across this problem, I've rebuilt the android image myself https://github.com/ssz66666/anbox/releases/tag/v0.1-with-pr1034.
> 
> It would be great if someone could test it out.

works well

**Comment by nihonium113** [comment]
> In case anyone also came across this problem, I've rebuilt the android image myself https://github.com/ssz66666/anbox/releases/tag/v0.1-with-pr1034.
> 
> It would be great if someone could test it out.

Yeap, works well, thanks ;3
Problem is solved.

But i'am still wondering how i were supposed to compile android image?

**Comment by ssz66666** [comment]
> > In case anyone also came across this problem, I've rebuilt the android image myself https://github.com/ssz66666/anbox/releases/tag/v0.1-with-pr1034.
> > It would be great if someone could test it out.
> 
> Yeap, works well, thanks ;3
> Problem is solved.
> 
> But i'am still wondering how i were supposed to compile android image?

You can follow the guide in the repo that you posted earlier: https://github.com/anbox/anbox/blob/master/docs/build-android.md 
If you are building on Arch Linux like I did, my [note](https://gist.github.com/ssz66666/8422d46eae83ce7240f5547d129bf29c) might be helpful to avoid some pitfalls.

**Comment by zwastik** [comment]
> In case anyone also came across this problem, I've rebuilt the android image myself https://github.com/ssz66666/anbox/releases/tag/v0.1-with-pr1034.
> 
> It would be great if someone could test it out.
I installed the packages and replaced /var/lib/anbox/android.img with android-1edeb4f-with-pr1034_amd64.img

When I run anbox, a game I had installed "another eden" is missing. When I try to install it I get:

Performing Streamed Install                                                                                                                            
adb: failed to install ANOTHER EDEN The Cat Beyond Time and Space_v2.2.100_apkpure.com.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

**Comment by nihonium113** [comment]
> ANOTHER EDEN

Well, this game compiled only for arm-based cpu, not x86.
So it won't work on anbox installed on x86
For example, Girls' Frontline' developers provides both architecture versions
https://imgur.com/a/gbfcy5F

**Comment by sprdcyp** [comment]
> In case anyone also came across this problem, I've rebuilt the android image myself https://github.com/ssz66666/anbox/releases/tag/v0.1-with-pr1034.
> 
> It would be great if someone could test it out.

hi ssz66666 , 
I have build one x86_64 android.img, and when I start session manager, I experience the error:
 lxc_start -start.c No such file or directory - Failed to exec "/anbox-init.sh"

Do you have any suggestions?

**Comment by ibilux** [comment]
No new builds yet ?

**Comment by nihonium113** [comment]
> No new builds yet ?

Well, there is an answer - https://github.com/anbox/anbox/issues/1389#issuecomment-616785366
You can use this image, it works just fine as i know
Maybe, i'll even find my own modified PKGBUILD if you are into arch-based distros for building anbox-image
But it isn't very hard to implement this by yourself

**Comment by ibilux** [comment]
> > No new builds yet ?
> 
> Well, there is an answer - [#1389 (comment)](https://github.com/anbox/anbox/issues/1389#issuecomment-616785366)
> You can use this image, it works just fine as i know
> Maybe, i'll even find my own modified PKGBUILD if you are into arch-based distros for building anbox-image
> But it isn't very hard to implement this by yourself

I tried this image, but audio didn't work in it at all with the new anbox releases.
I think changes must be made to both image and anbox sources for this to work.
It would be better if PR #1034 get merged.
