### ISSUE TITLE
can i install anbox  with Intel(R) Core(TM)2 Duo CPU     E7500  @ 2.93GHz ?

### ISSUE THREAD

**Issue by isslam95** [anbox/anbox#1395]
i am new to linux , I tried to edited the check_features.cpp like this https://github.com/anbox/anbox/pull/1045/files#diff-62bad487c2c1fa22b8b3fa188d902543 but i doesn't work it still s hows 

The CPU of your computer (Intel(R) Core(TM)2 Duo CPU     E7500  @ 2.93GHz) does not support all
features Anbox requires.
It is missing support for the following features: SSE 4.2
You can for example find more information about SSE
here https://en.wikipedia.org/

**Comment by 86423355844265459587182778** [comment]
Unfortunately, no.

The problem of CPU not supporting SSE 4.2 cannot be solved by whitelisting it. Please read what @morphis said in https://github.com/anbox/anbox/pull/1045#issuecomment-468580012.
