### ISSUE TITLE
Feature request. unique WM_CLASS for each app.

### ISSUE THREAD

**Issue by ahmubashshir** [anbox/anbox#1398]
As DEs normally uses X11 WM_CLASS properties to differentiate windows, anbox apps are grouped together and shows anbox Icon instead of their own Icon.

**Comment by ahmubashshir** [comment]
I was able to set WM Class using [this](http://sprunge.us/9qMSnx) patch. but idk why, anbox crashes if I open a window.

**Comment by Armwillking** [comment]
Is this function realized now? I want every Android application to display the taskbar icon correctly on the Linux host。

**Comment by Fuseteam** [comment]
as you can see in the previous comment, yes there's a patch but it crashes anbox for some reason the issue author doesn't understand
