### ISSUE TITLE
INSTALLATION OF ANBOX ON NOT SUPPORTED DISTRIBUTION(ELEMENTARY OS)

### ISSUE THREAD

**Issue by As-SamirK** [anbox/anbox#14]
**Anbox release (`anbox 0.1.0`) and system info (`version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.4.0-72-generic (buildd@lcy01-17) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: X.Org
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp`):**

**Description of the problem:**
After executing the command `sudo anbox-installer`, it will show an error and would cease to further continue the installation.

**Expected:**
ERROR : You are running the installer on a not support distribution. 
                At the moment we only support Ubuntu.

**Additional info:**
Elementary OS 0.4 Loki was used which is based on Ubuntu 16.04.2 LTS.

**Comment by mfreeman72** [comment]
Same for Linux Mint 18.1. Also based on Ubuntu 16.04.

**Comment by MooShoe** [comment]
+1

**Comment by myb120** [comment]
after snap install on Linux Mint 18.1, anbox-installer: command not found

**Comment by wyhasany** [comment]
Solution for elementary os:
```
$ sudo apt update
$ sudo apt install snapd
$ snap install --classic anbox-installer
#reboot pc
$ anbox-installer
#ignore errors and reboot computer once more
exec /snap/bin/anbox session-manager
# run from start menu Anbox
```
For command `exec /snap/bin/anbox session-manager` you can make simple script and append it
to startup applications. That works at my elementary os 0.4 loki.

**Comment by morphis** [comment]
The official snapd documentation says

```
Once installed, logout and back in to ensure pulseaudio is running.
```

see https://snapcraft.io/docs/core/install-ubuntu for details. That is why you get the error

`anbox-installer: command not found`

The folder `/snap/bin` is simply not in your PATH but will once you log out and back in.

Support for Elementary OS will come soon.
