### ISSUE TITLE
Installing on Arch Linux (not using AUR)

### ISSUE THREAD

**Issue by phillip-kruger** [anbox/anbox#141]
Hi.
I am trying to install on Arch Linux using your instructions on the web 
(https://snapcraft.io/docs/core/install-arch-linux)

There is another bug logged, but that was for installing via AUR. 
(https://github.com/anbox/anbox/issues/117)

It seems like the install happened fine, but then I get this error:
```
cnf-lookup: error while loading shared libraries: libboost_system.so.1.60.0: cannot open shared object file: No such file or directory
bash: anbox-installer: command not found
```
I have boost-libs installed from Arch repo, however the version is different ?

```
sudo pacman -Ss boost-libs
extra/boost-libs 1.63.0-1 [installed]
    Free peer-reviewed portable C++ source libraries - runtime libraries
```
Any advice ?

**Comment by oleid** [comment]
Your boost  version is too new, you need boost-libs-1.60. The easiest way would be installing from AUR.

**Comment by phillip-kruger** [comment]
Great. Thanks. You might then want to update your website that links to the Arch Linux how-to install. As current arch repo is on 1.6.3
