### ISSUE TITLE
Problem executing sudo modprobe binder_linux

### ISSUE THREAD

**Issue by ferranrego** [anbox/anbox#1410]
I receive this result when I try to execute "sudo modprobe binder_linux" and "sudo modprobe ashmem_linux"

`libkmod: ERROR ../libkmod/libkmod-config.c:656 kmod_config_parse: /etc/modprobe.d/qemu-system-x86.conf line 2: ignoring bad line starting with 'group=kvm'`

I spent a couple of hours trying to see if someone had this error and if there is a solution on Internet but didn't find anything useful.

**Additional info:**
I'm on Elementary OS 5.1.2 (it's basically Ubuntu 18.04.3 LTS)

**Comment by Genxster1998** [comment]
Which kernel are you on ? Try latest 5.4 ,5.5 and make sure headers installed too .
