### ISSUE TITLE
Proposal: support non-100000 UID mapping using fuse-overlayfs

### ISSUE THREAD

**Issue by AkihiroSuda** [anbox/anbox#1417]
Currently, the UID of the userns root is hardcoded to 100000.
I suggest supporting non-default UIDs like `anbox container-manager --uidmap=0:420000:65536`.

The challenge is how to chown the rootfs. On Ubuntu we could use shiftfs, but shiftfs is not available on most of other distros. So my suggestion is to use [`fuse-overlayfs -o uidmapping=...`](https://github.com/containers/fuse-overlayfs).

**Comment by morphis** [comment]
@AkihiroSuda Good point, however using fuse-overlayfs sounds like a major performance overhead, doesn't it?

**Comment by morphis** [comment]
Otherwise, adding the `--uidmap` arguments sounds fine to me.

**Comment by AkihiroSuda** [comment]
Seems we need to solve https://github.com/anbox/anbox/issues/1428 first
