### ISSUE TITLE
Issue starting anbox after debian 10 installation

### ISSUE THREAD

**Issue by laborid** [anbox/anbox#1422]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:** Hi all, I'm pretty new to Linux so excuse me if I'm doing some newbie stuff. I wanted to install Anbox but realized that there's no official support for Debian 10, however I found a repository [here](https://packages.debian.org/buster/anbox) so I installed it and did follow the instructions in [read me.txt](https://github.com/anbox/anbox/files/4485188/read.me.txt). And here I found my first problem because I don't know what this part means or how to do it.

> Then start the anbox-container-manager.service and the
anbox-session-manager.service, anbox-session-manager.service is a systemd
user service.

I tried running the Anbox shortcut but all I got is this screen and after a while it disappeared. 

![Screenshot from 2020-04-16 02-10-54](https://user-images.githubusercontent.com/63771508/79420783-9ed08680-7f87-11ea-9476-d2b010c1ce40.png)

So what Am I doing wrong? I'm sorry if this is not the right place to post this, I'll appreciate any help.

EDIT: I already installed Snap, I forgot to mention that.

**What were you expecting?:**

**Additional info:** Debian 10.3

**Comment by laborid** [comment]
Hi all, I'm pretty new to Linux so excuse me if I'm doing some newbie stuff. I wanted to install Anbox but realized that there's no official support for Debian 10, however I found a repository [here](https://packages.debian.org/buster/anbox) so I installed it and did follow the instructions in 
[read me.txt](https://github.com/anbox/anbox/files/4485188/read.me.txt). And here I found my first problem because I don't what this part means.

> Then start the anbox-container-manager.service and the
anbox-session-manager.service, anbox-session-manager.service is a systemd
user service.

I tried running the Anbox shortcut but all I got is this screen and after a while it disappeared. 

![Screenshot from 2020-04-16 02-10-54](https://user-images.githubusercontent.com/63771508/79420783-9ed08680-7f87-11ea-9476-d2b010c1ce40.png)

So what Am I doing wrong? I'm sorry if this is not the right place to post this, I'll appreciate any help.

**Comment by necessarily-equal** [comment]
You seem to be using the debian package. While it works, it is outdated and doesn't include https://github.com/anbox/anbox/pull/1309. The thing is Debian replaced binder for binderfs support in their kernel so it can't work anymore.

You probably shouldn't install two different version of Anbox at the same time. To use the snap, remove the Debian package.

I think you should contact the Debian maintainer.

**Comment by clues4me** [comment]
follow this steps [Anbox Debian 10](https://github.com/anbox/anbox/issues/1268#issuecomment-560539232)
