### ISSUE TITLE
make failed to build some targets

### ISSUE THREAD

**Issue by Emedo80** [anbox/anbox#1424]
Hello, I wanted to install andbox but i need first so create an img of android.
While i use the command 'make -j8' i've got an error
can you help me ?

Emedo.

_______________________________________________________
including ./tools/external/fat32lib/Android.mk ...
including ./tools/test/connectivity/Android.mk ...
including ./vendor/anbox/Android.mk ...
*** Overlay change detected, clean shared intermediate files...
*** rm -rf out/target/common/obj/APPS/SettingsProvider_intermediates out/target/common/obj/APPS/SystemUI_intermediates out/target/common/obj/APPS/SystemUITests_intermediates
build/core/binary.mk:925: warning: overriding commands for target `out/target/product/x86_64/obj/STATIC_LIBRARIES/libv8_intermediates/src/base/atomicops_internals_x86_gcc.o'
build/core/binary.mk:925: warning: ignoring old commands for target `out/target/product/x86_64/obj/STATIC_LIBRARIES/libv8_intermediates/src/base/atomicops_internals_x86_gcc.o'
build/core/binary.mk:925: warning: overriding commands for target `out/target/product/x86_64/obj_x86/STATIC_LIBRARIES/libv8_intermediates/src/base/atomicops_internals_x86_gcc.o'
build/core/binary.mk:925: warning: ignoring old commands for target `out/target/product/x86_64/obj_x86/STATIC_LIBRARIES/libv8_intermediates/src/base/atomicops_internals_x86_gcc.o'
Starting build with ninja
ninja: Entering directory `.'
[  0% 17/46564] Lex: aidl <= system/tools/aidl/aidl_language_l.ll
FAILED: /bin/bash -c "prebuilts/misc/linux-x86/flex/flex-2.5.39 -oout/host/linux-x86/obj/STATIC_LIBRARIES/libaidl-common_intermediates/aidl_language_l.cpp system/tools/aidl/aidl_language_l.ll"
flex-2.5.39: loadlocale.c :130 : _nl_intern_locale_data:  l'assertion << cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0])) >> a ?chou?.
Aborted (core dumped)
[  0% 17/46564] build out/target/common/obj/all-event-log-tags.txt
system/bt/hci/../EventLogTags.logtags:36: warning: tag "bt_hci_timeout" (1010000) duplicated in system/bt/btif/../EventLogTags.logtags:36
system/bt/hci/../EventLogTags.logtags:37: warning: tag "bt_config_source" (1010001) duplicated in system/bt/btif/../EventLogTags.logtags:37
system/bt/hci/../EventLogTags.logtags:38: warning: tag "bt_hci_unknown_type" (1010002) duplicated in system/bt/btif/../EventLogTags.logtags:38
[  0% 17/46564] host C++: libbase <= system/core/base/logging.cpp
ninja: build stopped: subcommand failed.
build/core/ninja.mk:148: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1

#### make failed to build some targets (25 seconds) ####
___________________________________________

**Comment by ssz66666** [comment]
See https://github.com/sonyxperiadev/bug_tracker/issues/136 , namely
```
$ LC_ALL=C make -j8
```
