### ISSUE TITLE
setup_id_map: the number of mapped UIDs varies depending on creds._uid value

### ISSUE THREAD

**Issue by AkihiroSuda** [anbox/anbox#1428]
**Please describe your problem:**
The number of mapped UIDs varies depending on creds._uid value

base_id | android_system_id | max_id | creds._uid | number of mapped UIDs
--------|-------------------|--------|------------|------------------------
 100000 |              1000 | 100000 |       1000 | 999 + 1 + 98999 = 99999
 100000 |              1000 | 100000 |       2000 | 999 + 1 + 97999 = 98999

https://github.com/anbox/anbox/blob/1edeb4f07941aaa65624cea59f1f77c314ad1b97/src/anbox/container/lxc_container.cpp#L121-L140

e.g. when `creds._uid` is 2000, `/proc/PID/uid_map` is as follows:
```
$ cat /proc/self/uid_map
         0     100000        999
      1000       2000          1
      1001     101001      97999
```
**What were you expecting?:**
Should be consistent

**Comment by AkihiroSuda** [comment]
> ```
> $ cat /proc/self/uid_map
>          0     100000        999
>       1000       2000          1
>       1001     101001      97999
> ```

Also, this mapping doesn't utilize UID 100999 and UID 101000 on the parent user NS.

**Comment by morphis** [comment]
@AkihiroSuda You have time to cook up a fix for this?

**Comment by AkihiroSuda** [comment]
Yes, but I'm not sure what we should do for the host UID 100999 and 101000.
For compatibility, I guess we need to keep these holes?

**Comment by AkihiroSuda** [comment]
PR https://github.com/anbox/anbox/pull/1473
