### ISSUE TITLE
Error installing on 17.04

### ISSUE THREAD

**Issue by accesstech713** [anbox/anbox#143]
Has anyone tried installing on 17.04 yet? I keep getting the below error:

+ '[' '!' -e /etc/modules-load.d/anbox.conf ']'
+ sudo modprobe binder_linux
modprobe: ERROR: could not insert 'binder_linux': Invalid argument

I've tried uninstalling and reinstalling and I've refreshed the snap. Any suggestions would be greatly appreciated.

**Comment by Mistero5050** [comment]
I had the same error BUT I simply didn't care about it and anbox is installed. You sure anbox isn't installed? Try /snap/bin/anbox-instaler or anbox

**Comment by accesstech713** [comment]
Thanks for the reply. Running /snap/bin/anbox-installer gives me the same results and /snap/bin/anbox gives me No such file or directory. Was really looking forward to testing this system out verses using ARC Welder for Google Chrome.

**Comment by Mistero5050** [comment]
I have 2 PC with 17.04 and 16.10 and no errors. So it's not your system's fault.
Check if apt-get update have some errors.
Provide log here please

**Comment by zhengzhou** [comment]
I had the same error, and anbox not installed.

```
binder_linux:
Running module version sanity check.
Error! Module version D31F122C91F971928CE0CDC for binder_linux.ko
is not newer than what is already found in kernel 4.10.0-19-generic (D31F122C91F971928CE0CDC).
You may override by specifying --force.
depmod...

DKMS: install completed.
+ '[' '!' -e /etc/modules-load.d/anbox.conf ']'
+ sudo tee /etc/modules-load.d/anbox.conf
+ sudo modprobe binder_linux
modprobe: ERROR: could not insert 'binder_linux': Exec format error
```

**Comment by davidelang** [comment]
I'm running 17.04 and didn't have this problem (once I stopped pulling from 
broken repos)

David Lang

**Comment by Connor124** [comment]
Try compiling binder from source. Download the repo, then run make in the binder directory.

**Comment by caliston** [comment]
I had this problem. I managed to successfully install into a fresh Kubuntu 17.04 amd64 VM with:

```
sudo dkms remove anbox-modules-binder/4 --all
sudo dkms install -m anbox-modules-binder -v 4
sudo dkms remove anbox-modules-ashmem/4 --all
sudo dkms install -m anbox-modules-ashmem-v 4
sudo modprobe binder_linux
sudo modprobe ashmem_linux
anbox session-manager
```

and then launch anbox from the KDE menu.

**Comment by SferaDev** [comment]
@caliston That actually worked on Xubuntu 17.04, I still get loads of spam from AppArmor though but it launched whilst after running the default installer didn't (anbox errored out kernel was missing modules).

**Comment by acetheultimate** [comment]
was working good in 16.10, uninstalled don't know why, upgraded to 17.04 and there it is. :(

**Comment by accesstech713** [comment]
Thanks @caliston That has fixed the issue for me.

**Comment by adstanciu** [comment]
Thanks @caliston That has fixed the issue for me on Ubuntu 17.04

**Comment by Mistero5050** [comment]
Then we can close this

**Comment by Daniel-Gherard** [comment]
Thanks @caliston. That tip fixed the issue for me.
But, i had to change this line:
sudo dkms install -m anbox-modules-ashmem-v 4
to:
sudo dkms install -m anbox-modules-ashmem -v 4

Maybe you missed a space?
I'm using a Ubuntu Gnome 17.04.

**Comment by caliston** [comment]
Well spotted,  I was retyping it from a VM.  I've fixed it in my comment above for ease of cut-and-paste.

**Comment by Mistero5050** [comment]
we can close this, owner has found his solution

**Comment by wayneward** [comment]
i get :(

wayneward@shanghai:~$ sudo dkms remove anbox-modules-binder/4 --all
Error! Could not locate dkms.conf file.
File:  does not exist.
wayneward@shanghai:~$ sudo dkms install -m anbox-modules-ashmem -v 4
Error! Could not locate dkms.conf file.
File:  does not exist.

**Comment by Mistero5050** [comment]
@wayneward  please open your own issue, but first try this https://askubuntu.com/a/231908

**Comment by wayneward** [comment]
what is the command to run to rebuild dkms module 

i tried this and the modules are there 

wayneward@shanghai:~$ ls -R /var/lib/dkms
/var/lib/dkms:
anbox-modules-ashmem  anbox-modules-binder  dkms_dbversion

/var/lib/dkms/anbox-modules-ashmem:
4  6~zesty1  kernel-4.10.0-19-generic-x86_64  kernel-4.10.0-20-generic-x86_64

/var/lib/dkms/anbox-modules-ashmem/4:
4.10.0-19-generic  4.10.0-20-generic  source

/var/lib/dkms/anbox-modules-ashmem/4/4.10.0-19-generic:
x86_64

/var/lib/dkms/anbox-modules-ashmem/4/4.10.0-19-generic/x86_64:
log  module

/var/lib/dkms/anbox-modules-ashmem/4/4.10.0-19-generic/x86_64/log:
make.log

/var/lib/dkms/anbox-modules-ashmem/4/4.10.0-19-generic/x86_64/module:
ashmem_linux.ko

/var/lib/dkms/anbox-modules-ashmem/4/4.10.0-20-generic:
x86_64

/var/lib/dkms/anbox-modules-ashmem/4/4.10.0-20-generic/x86_64:
log  module

/var/lib/dkms/anbox-modules-ashmem/4/4.10.0-20-generic/x86_64/log:
make.log

/var/lib/dkms/anbox-modules-ashmem/4/4.10.0-20-generic/x86_64/module:
ashmem_linux.ko

/var/lib/dkms/anbox-modules-ashmem/6~zesty1:
4.10.0-20-generic  source

/var/lib/dkms/anbox-modules-ashmem/6~zesty1/4.10.0-20-generic:
x86_64

/var/lib/dkms/anbox-modules-ashmem/6~zesty1/4.10.0-20-generic/x86_64:
log  module

/var/lib/dkms/anbox-modules-ashmem/6~zesty1/4.10.0-20-generic/x86_64/log:
make.log

/var/lib/dkms/anbox-modules-ashmem/6~zesty1/4.10.0-20-generic/x86_64/module:
ashmem_linux.ko

/var/lib/dkms/anbox-modules-binder:
4  6~zesty1  kernel-4.10.0-19-generic-x86_64  kernel-4.10.0-20-generic-x86_64

/var/lib/dkms/anbox-modules-binder/4:
4.10.0-19-generic  4.10.0-20-generic  source

/var/lib/dkms/anbox-modules-binder/4/4.10.0-19-generic:
x86_64

/var/lib/dkms/anbox-modules-binder/4/4.10.0-19-generic/x86_64:
log  module

/var/lib/dkms/anbox-modules-binder/4/4.10.0-19-generic/x86_64/log:
make.log

/var/lib/dkms/anbox-modules-binder/4/4.10.0-19-generic/x86_64/module:
binder_linux.ko

/var/lib/dkms/anbox-modules-binder/4/4.10.0-20-generic:
x86_64

/var/lib/dkms/anbox-modules-binder/4/4.10.0-20-generic/x86_64:
log  module

/var/lib/dkms/anbox-modules-binder/4/4.10.0-20-generic/x86_64/log:
make.log

/var/lib/dkms/anbox-modules-binder/4/4.10.0-20-generic/x86_64/module:
binder_linux.ko

/var/lib/dkms/anbox-modules-binder/6~zesty1:
4.10.0-20-generic  source

/var/lib/dkms/anbox-modules-binder/6~zesty1/4.10.0-20-generic:
x86_64

/var/lib/dkms/anbox-modules-binder/6~zesty1/4.10.0-20-generic/x86_64:
log  module

/var/lib/dkms/anbox-modules-binder/6~zesty1/4.10.0-20-generic/x86_64/log:
make.log

/var/lib/dkms/anbox-modules-binder/6~zesty1/4.10.0-20-generic/x86_64/module:
binder_linux.ko

**Comment by wayneward** [comment]
and this 

wayneward@shanghai:~$ sudo dkms install -m anbox-modules-ashmemsudo dkms install -m anbox-modules-ashmem -v 4
Warning: I do not know how to handle dkms.
Error! Could not locate dkms.conf file.
File:  does not exist.
Error! Could not locate dkms.conf file.
File:  does not exist.

**Comment by wayneward** [comment]
modprobe: ERROR: could not insert 'binder_linux': Exec format error

**Comment by wayneward** [comment]
i think i now know the problem 
apparently secure boot must be enabled on the install?

**Comment by wayneward** [comment]
i tried reinstalling 17.04 with secure boot and it still doesnt work 
its to do with the modules not being installed properly
ive tried installing for ubuntu and tried from source as well :(

**Comment by Mistero5050** [comment]
i have secure boot disabled and uefi on, and it works

**Comment by wayneward** [comment]
ahhh ill try this now

**Comment by wayneward** [comment]
nice work that fixed it! so on ubuntu 17.04 install uefi but secure boot off !! thanks guys now how do we get more apps!!...

![screenshot-20170501154625-1920x1080](https://cloud.githubusercontent.com/assets/11428255/25581030/6f87ce02-2e85-11e7-911a-27741f3fb350.png)

**Comment by Mistero5050** [comment]
Adb install apkfile.apk

**Comment by wayneward** [comment]
as easy as that surely not!! thats great :)

**Comment by hub2git** [comment]
@caliston , I'm desperate to get Anbox working on my system. Do you think it will help my issue (#225)?

If I run your code and it doesn't work, how do I undo your code?

**Comment by caliston** [comment]
@hub2git my code only rebuilds the kernel modules, if you some reason the install failed to do that (I suspect due to a race between building the modules and a kernel update that happens to occur at the same time).  There's nothing to undo - it just retries something that the installer did.  You can uninstall anbox if you want to clean up.

I doubt it will help with your issue (which is that the container is dying for reasons unknown):
    `lxc_start - start.c:__lxc_start:1382 - Unknown exit status for container "default" init 4.`

**Comment by doubleYellow** [comment]
i solve by update kernel from 4.4.0 to 4.15.0
