### ISSUE TITLE
Can't start anbox on ubuntu 20.04 (anbox from ubuntu repo)

### ISSUE THREAD

**Issue by xlazom00** [anbox/anbox#1431]
I would like to run anbox on ubuntu 20.04 amd64
snap version is working just fine on ubuntu 20.04 amd64
but I would like to try version from repo
as I would like to try it on arm64 and anbox don't have snap version for arm64

anbox system-info
https://pastebin.com/19ehwgDt
lsmod | grep "linux"
binder_linux          180224  0
ashmem_linux           20480  0

sudo systemctl status anbox-container-manager
● anbox-container-manager.service - Anbox Container Manager
     Loaded: loaded (/lib/systemd/system/anbox-container-manager.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2020-04-19 12:07:53 PDT; 9min ago
       Docs: man:anbox(1)
    Process: 2265 ExecStartPre=/sbin/modprobe ashmem_linux (code=exited, status=0/SUCCESS)
    Process: 2266 ExecStartPre=/sbin/modprobe binder_linux (code=exited, status=0/SUCCESS)
    Process: 2269 ExecStartPre=/usr/share/anbox/anbox-bridge.sh start (code=exited, status=0/SUCCESS)
   Main PID: 2290 (anbox)
      Tasks: 9 (limit: 19116)
     Memory: 4.3M
     CGroup: /system.slice/anbox-container-manager.service
             └─2290 /usr/bin/anbox container-manager --daemon --privileged --data-path=/var/lib/anbox

but when I start anbox
anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity

I have this in syslog
ubuntu anbox: Failed to start as either binder or ashmem kernel drivers are not loaded

So how can I get better log from anbox??

**Comment by yunspace** [comment]
You will have to install the kernel modules specified here: https://github.com/anbox/anbox/blob/master/docs/install.md

However the current distribution caters for Ubuntu 19 disco only and not the 20.04 focal release.

**Comment by JamesSwift** [comment]
The kernel modules are already installed and loaded by default. Anbox is not detecting them.

**Comment by shrewdsri** [comment]
Was able to start the anbox after running the below command. Kernel modules are available as part of 20.04 but not loaded into the kernel by default

`sudo modprobe ashmem_linux`

Ref: https://github.com/anbox/anbox/blob/master/docs/install.md

**Comment by so-hard** [comment]
> Was able to start the anbox after running the below command. Kernel modules are available as part of 20.04 but not loaded into the kernel by default
> 
> `sudo modprobe ashmem_linux`
> 
> Ref: https://github.com/anbox/anbox/blob/master/docs/install.md

modprobe: ERROR: could not insert 'ashmem_linux': Operation not permitted ,can`t work
