### ISSUE TITLE
a proble of anbox session-manager

### ISSUE THREAD

**Issue by GitSoftwareNow** [anbox/anbox#1432]
when I run anbox session-manager but it sys "No runtime directory specified" on Ububtu system
use command line run "echo $XDG_RUNTIME_DIR" but it returns empty
which $XDG_RUNTIME_DIR in the enviroment?

**Comment by AkihiroSuda** [comment]
```console
$ export XDG_RUNTIME_DIR=/run/user/$(id -u)
$ export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
```

These env vars are automatically set if you login via systemd.
