### ISSUE TITLE
Anbox windows dont repaint windows when the xsever needs them to.

### ISSUE THREAD

**Issue by IMbackK** [anbox/anbox#1433]
Anbox windows don't respond to xdamage events, making Anbox windows display corrupted continence whenever a window is dragged over them in a non-composing window manager.

**Comment by cyberl33t** [comment]
Got anbox-git up and running on Arch Linux two days ago. Noticed the same exact problem immediately :(

**Comment by Genxster1998** [comment]
+1 here too , failed to update buffers

**Comment by ardasevinc** [comment]
+1. Can't play my game because of this. Unusable with tiling window managers.

**Comment by cyberpunkrocker-zero** [comment]
Well the issue has not been fixed yet!!!
I've been using anbox for some half an year already, and every release has the same issue: If I move to another workspace from the one where anbox is running, and back again, anbox shows only the desktop wallpaper, or a part of the previous workspace, until I 'wiggle' the app running in anbox, i.e. move it up or down with mouse. That means the xdamage support is still missing!!!
