### ISSUE TITLE
ls: cannot access '/dev/binder': No such file or directory

### ISSUE THREAD

**Issue by dredtaur** [anbox/anbox#1435]
Really too much trouble.
ls: cannot access '/dev/binder': No such file or directory

Can't overcome this issue. All of the prior suggested responses result in the same problem. Clearly this isn't developed enough, as I've wasted far too much time following steps that result in the exact same outcome.

**Comment by Thatoo** [comment]
I have the same issue

**Comment by humanchair** [comment]
+1

**Comment by Genxster1998** [comment]
@dredtaur cuz you don't have one try lsmod and see if you have the module installed or use pr template to report problem.

**Comment by jherbold113** [comment]
I have the same issue.  lsmod shows binder_linux and ashmem_linux are preset.
However '/dev/binder' does not exist.
I am using Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic

**Comment by amberisvibin** [comment]
I am also having the same issue. lsmod shows I have both binder_linux and ashmem_linux, but /dev/binder/ does not exist. anbox --system-info says ashmem is installed, but binder is not.
I am on Ubuntu 20.04.-

**Comment by morphis** [comment]
/dev/binder is gone with the latest kernels (starting Ubuntu 19.04) as we use binderfs now (https://www.kernel.org/doc/html/latest/admin-guide/binderfs.html). You will see a `/var/snap/anbox/common/binderfs` instead which will contain the binder device nodes.
