### ISSUE TITLE
Feature request: disable "toolbar" for WM's which doesn't need it

### ISSUE THREAD

**Issue by cyberl33t** [anbox/anbox#1438]
(By "toolbar" I mean here the area on top where the 'maximize' and 'close' buttons are. Maybe "buttonbar" is a better term?)

I suppose the original thought for including these buttons within the window area was to allow usage on desktop environments with the idiotic (sorry, Gnome developers...) Client Side Decoration enabled. Well, it works there, but in other environments / window managers it is just dead space needlessly duplicating functions already provided by the window manager (in my case Awesome WM).

Is there a way to manually disable this button area? If not, Anbox should detect whether it is running within Gnome DE or not, and enable / disable the button area accordingly.

**Comment by alxlg** [comment]
Duplicated: #961 and #1308

**Comment by Genxster1998** [comment]
There's already configurable option is in line to merge #1415

**Comment by morphis** [comment]
Both PRs are merged. Only need to rebuild a new Android image.
