### ISSUE TITLE
after unsquashing and squashing the android image, adb won't see the emulator device anymore

### ISSUE THREAD

**Issue by subjectdenied** [anbox/anbox#144]
**Anbox release (`anbox version`) and system info (`anbox system-info`):**
0.1.0

**Description of the problem:**
after unsquashing the android image, changing some values in default.props (for getting root access for an example), squashing it again, the emulator can't be reached again with adb, as the device isn't found

**Expected:**
unless i really messed up the image, the emulator should show up in adb list of attached devices

**Additional info:**
using latest adb on arch linux host:
Android Debug Bridge version 1.0.36
Revision 7.1.1_r13

**Comment by vamur** [comment]
Sometimes adb doesn't work, you could try restarting anbox..

**Comment by subjectdenied** [comment]
i think this happens if default.prop is manipulated, i did this again with only putting google apps into the image, and it works now also with adb connecting

**Comment by morphis** [comment]
If you modify the android.img on your own there are things which may go wrong. That is something we can provide much support for and can only help with obvious problems with the Anbox runtime itself.
