### ISSUE TITLE
Add a package for ubuntu eoan in the ppa

### ISSUE THREAD

**Issue by HassanZahin** [anbox/anbox#1440]
It seems like the ppa dont have a for ubuntu eoan
![image](https://user-images.githubusercontent.com/61543143/80781156-27a80e80-8b93-11ea-9d76-2217936cc1b9.png)

**Comment by morphis** [comment]
Ubuntu ships both binder and ashmem in its default kernel since 19.04. No need for the PPA to support eoan.
