### ISSUE TITLE
adb: failed to install /home/ria/tmp/apk/@Voice Aloud Reader_19.6.6_com.hyperionics.avar.0.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

### ISSUE THREAD

**Issue by igoryonya** [anbox/anbox#1447]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
[anbox-system-diagnostics-2020-05-06.zip](https://github.com/anbox/anbox/files/4584926/anbox-system-diagnostics-2020-05-06.zip)

<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**
Trying to install any apk file and always get an error such, as in title.

**What were you expecting?:**
an app to be installed successfuly

**Additional info:**

**Comment by morphis** [comment]
You're trying to run an ARM only application on an x86 system which is not going to work.

**Comment by igoryonya** [comment]
Oh, thanks, I didn't realize, there were different versions of packages for different processors.
