### ISSUE TITLE
unable to build on ubuntu 20.04

### ISSUE THREAD

**Issue by SViN24** [anbox/anbox#1448]
**Please describe your problem:**
seems like you are unable to build anbox at least on 20.04

**What were you expecting?:**
a successful compilation

**Additional info:**

`[ 38%] Built target xdg_test
[ 40%] Built target OpenGLESDispatch
[ 89%] Built target anbox-core
make[2]: *** No rule to make target 'gmock/libgmock.a', needed by 'tests/anbox/android/intent_tests'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:1919: tests/anbox/android/CMakeFiles/intent_tests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target 'gmock/libgmock.a', needed by 'tests/anbox/support/at_parser_tests'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:1995: tests/anbox/support/CMakeFiles/at_parser_tests.dir/all] Error 2
make[2]: *** No rule to make target 'gmock/libgmock.a', needed by 'tests/anbox/application/restricted_manager_tests'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:1957: tests/anbox/application/CMakeFiles/restricted_manager_tests.dir/all] Error 2
[ 90%] Built target anbox
make: *** [Makefile:141: all] Error 2
`

I have not tried it on other distros

**Comment by thdaemon** [comment]
Try this patch:
https://salsa.debian.org/zhsj/anbox/-/blob/5d296a71c2cf3bffa4623562a662d95e4221c1a4/debian/patches/0006-fix-gmock-lib-path.patch

**Comment by SViN24** [comment]
> Try this patch:
> https://salsa.debian.org/zhsj/anbox/-/blob/5d296a71c2cf3bffa4623562a662d95e4221c1a4/debian/patches/0006-fix-gmock-lib-path.patch

works perfectly now thank you very much

`$ anbox version
anbox local-73804a3
`

**Comment by Barbarosse** [comment]
Hi SViN24 ! I'm also in 19.04. How do you run Anbox after building it ? Thanks.

**Comment by JamesSwift** [comment]
Hi @SViN24, that patch worked for me too. But when I try to run it after building, it says that the ashmem and binder modules aren't loaded. However the modules are loaded... how did you get it to run?

**Comment by privateOmega** [comment]
@JamesSwift Did you build for `snap` or using `sudo make install`?

**Comment by JamesSwift** [comment]
I built then ran `sudo make install`, then ran `anbox session-manager`. The build instructions make no mention of an android image...

**Comment by privateOmega** [comment]
@JamesSwift I am also a fellow developer trying to build anbox from source. Even I built using `sudo make install` but wasn't sure if it shipped with an android image, but you could find one at [android images](https://build.anbox.io/android-images/) and also the snapcraft script mentions it [here](https://github.com/anbox/anbox/blob/3a54509bde5bde0a95c09afd4115d0c47159a7d2/snap/snapcraft.yaml#L136).

**Comment by privateOmega** [comment]
I am not super confident about this, but I have found some steps which might help.
```
$ datadir=$HOME/anbox-data
$ mkdir -p $datadir/rootfs
$ sudo anbox container-manager \
    --android-image=/path/to/android.img \
    --data-path=$datadir
```

**Comment by thdaemon** [comment]
> Hi @SViN24 and @thdaemon, that patch worked for me too. But when I try to run it after building, it says that the ashmem and binder modules aren't loaded. However the modules are loaded... how did you get it to run?

Are you using the modules provided by anbox (https://github.com/anbox/anbox-modules/) or the modules provided by your distro (finally from the Linux kernel tree)?

If the latter, you need to mount the binderfs file system for new distros
```
sudo mkdir /dev/binderfs
sudo mount -t binder binder /dev/binderfs
```

For more information see: https://github.com/anbox/anbox/pull/1309

**Comment by thdaemon** [comment]
> I built then ran `sudo make install`, then ran `anbox session-manager`. The build instructions make no mention of an android image...

session-manager is not enough, you need to start the container-manager first, my command is
```
anbox container-manager --daemon --privileged --data-path=/var/lib/anbox
```
and `android.img` is in /var/lib/anbox. You can download it from https://build.anbox.io/android-images/2018/07/19/

**Comment by thdaemon** [comment]
If there are more problems, I suggest to create a new issue to discuss.

**Comment by JamesSwift** [comment]
Thank you for your help. I was able to get a little further.

**Comment by necessarily-equal** [comment]
I believe the original issue was fixed in master by https://github.com/anbox/anbox/pull/1423 and that this should be closed. If you have an other issue, please make an other issue :wink:

**Comment by JamesSwift** [comment]
It was merged 30 minutes ago. So yes, this can be closed.

**Comment by carloscastillo03** [comment]
Saludos soy nuevo usando ubuntu y quisiera saber como puedo instalar el parche que recomiendan para solucionar este problema

**Comment by Common-D-Service** [comment]
@carloscastillo03 Seems that simply syncing the source code before compilation will work.

**Comment by kinggx9** [comment]
I also got the same error on arch linux
Who can help me?
Thanks
