### ISSUE TITLE
Unable to install anbox ubuntu 4.4.0-72-generic (16.04)

### ISSUE THREAD

**Issue by callerpj** [anbox/anbox#145]
snap -package anbox-install not found.

after getting with WGET
and starte, it is running up to
"sudo snap install --edge --devmode anbox"
--> error: cannot install "anbox": snap not found

snap/snapd version: 2.23.6

**Comment by WuerfelDev** [comment]
Do you  have a 32bit system? Then you can't run it yet

**Comment by callerpj** [comment]
Oh, yes I Just discoverd Most snaps are 64bit. So I switched the System. Thanks a lot

**Comment by Mistero5050** [comment]
I think we can close this 👍
