### ISSUE TITLE
Error while installing the kernel modules

### ISSUE THREAD

**Issue by avariado** [anbox/anbox#1452]
Hi, any thoughts on this? I'm trying to install the kernel modules on Lubuntu 20.04 LTS (Focal Fossa) from the Ubuntu Disco repository and the following error occurred (/var/lib/dkms/anbox/1/build/make.log):

DKMS make.log for anbox-1 for kernel 5.4.0-29-generic (x86_64)
dom 10 mai 2020 23:06:40 WEST
make: Entering directory '/var/lib/dkms/anbox/1/build/ashmem'
make -C /lib/modules/5.4.0-29-generic/build V=0 M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-29-generic'
  AR      /var/lib/dkms/anbox/1/build/ashmem/built-in.a
  CC [M]  /var/lib/dkms/anbox/1/build/ashmem/deps.o
  CC [M]  /var/lib/dkms/anbox/1/build/ashmem/ashmem.o
  LD [M]  /var/lib/dkms/anbox/1/build/ashmem/ashmem_linux.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC [M]  /var/lib/dkms/anbox/1/build/ashmem/ashmem_linux.mod.o
  LD [M]  /var/lib/dkms/anbox/1/build/ashmem/ashmem_linux.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-29-generic'
make: Leaving directory '/var/lib/dkms/anbox/1/build/ashmem'
make: Entering directory '/var/lib/dkms/anbox/1/build/binder'
make -C /lib/modules/5.4.0-29-generic/build V=0 M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-29-generic'
  AR      /var/lib/dkms/anbox/1/build/binder/built-in.a
  CC [M]  /var/lib/dkms/anbox/1/build/binder/deps.o
  CC [M]  /var/lib/dkms/anbox/1/build/binder/binder.o
In file included from ././include/linux/kconfig.h:5,
                 from <command-line>:
./include/generated/autoconf.h:4098: warning: "CONFIG_ANDROID_BINDER_DEVICES" redefined
 4098 | #define CONFIG_ANDROID_BINDER_DEVICES ""
      | 
<command-line>: note: this is the location of the previous definition
In file included from ././include/linux/kconfig.h:5,
                 from <command-line>:
./include/generated/autoconf.h:4098: warning: "CONFIG_ANDROID_BINDER_DEVICES" redefined
 4098 | #define CONFIG_ANDROID_BINDER_DEVICES ""
      | 
<command-line>: note: this is the location of the previous definition
/var/lib/dkms/anbox/1/build/binder/binder.c:3382:11: error: initialization of ‘vm_fault_t (*)(struct vm_fault *)’ {aka ‘unsigned int (*)(struct vm_fault *)’} from incompatible pointer type ‘int (*)(struct vm_fault *)’ [-Werror=incompatible-pointer-types]
 3382 |  .fault = binder_vm_fault,
      |           ^~~~~~~~~~~~~~~
/var/lib/dkms/anbox/1/build/binder/binder.c:3382:11: note: (near initialization for ‘binder_vm_ops.fault’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:273: /var/lib/dkms/anbox/1/build/binder/binder.o] Error 1
make[1]: *** [Makefile:1719: /var/lib/dkms/anbox/1/build/binder] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-29-generic'
make: *** [Makefile:8: all] Error 2
make: Leaving directory '/var/lib/dkms/anbox/1/build/binder'

**Comment by morphis** [comment]
Ubuntu ships both ashmem and binder with its default kernel since 19.10. Now need to install the DKMS modules.

**Comment by JayMcGann** [comment]
Lubuntu 20.04 focal does not include ashmem

$ lsmod | grep -e ashmem_linux -e binder_linux
binder_linux          188416  0

$ sudo add-apt-repository ppa:morphis/anbox-support
$ sudo apt update --allow-insecure-repositories

This yields error:

E: The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release' does not have a Release file.

**Comment by leijie2015** [comment]
> Lubuntu 20.04 focal does not include ashmem
> 
> $ lsmod | grep -e ashmem_linux -e binder_linux binder_linux 188416 0
> 
> $ sudo add-apt-repository ppa:morphis/anbox-support $ sudo apt update --allow-insecure-repositories
> 
> This yields error:
> 
> E: The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release' does not have a Release file.

hi, I found the same error, and I did something like following, it fix the problem for.

$ cd /etc/apt/sources.list.d
$ sudo vim morphis-ubuntu-anbox-support-focal.list
deb http://ppa.launchpad.net/morphis/anbox-support/ubuntu **focal** main      ## change focal to bionic -> save & exit
$ sudo apt-get update

**Comment by Fuseteam** [comment]
unless lubuntu ships with a different kernel than upstream ubuntu, you simply do not need the PPA
you can check for ashmem and binder with the following commands
```grep binder /proc/filesystems
grep ashmem /proc/misc```

**Comment by XploreSecF** [comment]
why so hard to install kernel:(

**Comment by Fuseteam** [comment]
ask your distro maintainer to ship the modules if installing the modules yourself is too hard ;)
