### ISSUE TITLE
error: cannot install "anbox-installer": snap not found

### ISSUE THREAD

**Issue by adamsson6** [anbox/anbox#146]
Hi, i'm trying to install anbox on xubuntu 16.04 32 bit and i get this message... 
Any help please ? thank you.

**Comment by adamsson6** [comment]
My snap version is 2.23.6

**Comment by Gara3987** [comment]
I originally ran into the same issue, and found out that snap is broken on the Ubuntu and Mint system; at least the version which is in the official repositories.  I followed these instructions [Install Snapd in Linux Mint 18](https://www.everything-linux-101.com/how-to/install-snapd-in-linux-mint-18/).  From there install `snapcraft` `snap` and `snapd.`  That should work.  Though a different issues I ran into is when trying to run the `anbox-installer` I get a message "anbox-installer: command not found."

**Comment by Pogodaanton** [comment]
The same thing happened to me, too. However, if I run `anbox-installer` with `sudo` then it will start. Of course, you won't be able to proceed like that either because the installer doesn't want to be started with root.

**Comment by WuerfelDev** [comment]
I had this too. The problem is 32bit is not supported yet. Because we can't know it I created an issue on the webpage so they may add a note that it is for 64bit currently only.
https://github.com/anbox/anbox.github.com/issues/2

**Comment by martinschayna** [comment]
My system is 64-bit and I also ran into this error:
```
$ uname -m
x86_64

$ sudo snap install --classic anbox-installer && anbox-installer
error: cannot install "anbox-installer": snap not found
```
The problem was in missing `snapd` package, I have only `snap` package installed. So, Ubuntu users, you have to install snap properly:
```
$ sudo apt-get install snap snapd
```
Hope this helps someone.

**Comment by Pogodaanton** [comment]
@Gara3987 interestingly enough anbox-installer is only "installed" (PATH wise) in root in this case. You can run the installer as a non-priviliged user by typing `snap run anbox-installer`

**Comment by morphis** [comment]
> The problem was in missing snapd package, I have only snap package installed. So, Ubuntu users, you have to install snap properly:

The `snap` package on Ubuntu doesn't have anything to do with `snapd`. It's description says: 
```
SNAP is a general purpose gene finding program suitable for both eukaryotic
 and prokaryotic genomes. SNAP is an acroynm for Semi-HMM-based Nucleic Acid
 Parser.
```

To comment on the original bug report: We don't support 32-bit x86 systems and don't have any plan to do so.

**Comment by neatville** [comment]
On Antergos (basically Arch) I get this when trying `snap run anbox-installer`. 
`error: cannot find current revision for snap anbox-installer: readlink /var/lib/snapd/snap/anbox-installer/current: no such file or directory`

**Comment by Kogam22** [comment]
@neatville 
Well, I Get The Same Thing On My 32 Bit Xubuntu.
Basically 32 Bit Isn't Supported. :(
