### ISSUE TITLE
Snapcraft build issue with swiftshader on Ubuntu 20.04

### ISSUE THREAD

**Issue by TimoPtr** [anbox/anbox#1469]
Impossible to build a snap base on the current commit use for swiftshader 

Failed to run 'cmake /root/anbox/parts/swiftshader/src -DCMAKE_INSTALL_PREFIX=' for 'swiftshader': Exited with code 1.
Verify that the part is using the correct parameters and try again.

**Comment by necessarily-equal** [comment]
the current workaround is to `git revert a2625551ca8cdc5924db9c4ca7d62a39a31b79c2`

**Comment by necessarily-equal** [comment]
(was fixed by https://github.com/anbox/anbox/pull/1489)

Le dim 11 oct. 2020 à 13:44, stale[bot] <notifications@github.com> a 
écrit :
