### ISSUE TITLE
anbox in windows 10

### ISSUE THREAD

**Issue by EnzoRimapa** [anbox/anbox#1472]
is there any way to get anbox to run from windows 10 bash?

**Comment by TheEssem** [comment]
there *might* be a slim chance if you're using WSL 2 but it's very unlikely

**Comment by EnzoRimapa** [comment]
I have this linux terminal in Windows 10

![image](https://user-images.githubusercontent.com/43084466/83169554-d1b68000-a0d8-11ea-848e-2f097512cedd.png)

**Comment by karuboniru** [comment]
It is possible...but buggy...

You can get a manual to get it running [here](https://www.reddit.com/r/bashonubuntuonwindows/comments/eofn5s/run_anbox_on_wsl_2/). 

Anbox on WSL is buggy now. You can run it but not "use" it.
