### ISSUE TITLE
[bug] Audio is far behind the video

### ISSUE THREAD

**Issue by SiamSami** [anbox/anbox#1487]
**Please describe your problem:**

If we play a video on Youtube, then the audio is far behind the video.

**What were you expecting?:**

Audio and the video should be playing simultaneously.

**Comment by necessarily-equal** [comment]
there's a fix here: https://github.com/anbox/anbox/pull/1034. Unfortunately, it requires building both anbox and the anbox image, so it hasn't been merged.
