### ISSUE TITLE
how can I debug android process of init?

### ISSUE THREAD

**Issue by GitSoftwareNow** [anbox/anbox#1491]
/mnt# strace ./init
execve("./init", ["./init"], [/* 23 vars */]) = -1 EINVAL (Invalid argument)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=0} ---
+++ killed by SIGSEGV +++
core dump

**Comment by necessarily-equal** [comment]
I've witnessed this error with the prebuilt aarch64 image. It is working for me on a more recent image build.
