### ISSUE TITLE
anbox: error while loading shared libraries: libprotobuf-lite.so.22: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by alsoGAMER** [anbox/anbox#1498]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
anbox: error while loading shared libraries: libprotobuf-lite.so.22: cannot open shared object file: No such file or directory
```
</details>

**Comment by mn26** [comment]
What distro are you on? This happens on Arch Linux/Manjaro. Tried to workaround by doing
`cp /usr/lib/libprotobuf.so.23 /usr/lib/libprotobuf.so.22` only to get a different error.

**Comment by alsoGAMER** [comment]
> What distro are you on? This happens on Arch Linux/Manjaro. Tried to workaround by doing
> `cp /usr/lib/libprotobuf.so.23 /usr/lib/libprotobuf.so.22` only to get a different error:
> `anbox: symbol lookup error: anbox: undefined symbol: _ZN6google8protobuf8internal17UnknownFieldParseEjPNS1_29InternalMetadataWithArenaLiteEPKcPNS1_12ParseContextE`

I'm on manjaro 20.x
I'll try later to do this method and I'll update this issue

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/85816946-d5e8c280-b796-11ea-8e5d-edec7f02e697.png)

**Comment by mn26** [comment]
I figured out how to fix this.
Download older version of protobuf c++ from github. I chose protobuf-3.11.0.
Extract to a folder and cd into it.
build:
```
./configure
make
make check        #I got errors but it worked anyways
sudo make install
sudo ldconfig
```
Link or copy file:
`sudo cp /usr/local/lib/libprotobuf-lite.so.22 /usr/lib/`

Now Anbox should work.

**Comment by alsoGAMER** [comment]
> Now Anbox should work.
Yes, now works. Thanks.

Now the problem is networking, and I don't know how to fix this.

**Comment by mn26** [comment]
Read the Arch wiki for Anbox.
https://wiki.archlinux.org/index.php/Anbox#Network

**Comment by alsoGAMER** [comment]
> Read the Arch wiki for Anbox.
> https://wiki.archlinux.org/index.php/Anbox#Network

Yeah, I know, actually reinstalling anbox-git has worked anyway for me.

**Comment by mahdi-ln** [comment]
I used [anbox-git AUR](https://aur.archlinux.org/packages/anbox-git/) and having same problem after recent system update

**Comment by alsoGAMER** [comment]
anbox isn't really supported on anything that isn't ubuntu, i mean, you can try the snap variant also on arch (with the zen kernel ofc), but i don't think it will work.

**Comment by Fuseteam** [comment]
the snap variant should work on any distro that has the kernel modules. tho atm there may be some glibc errors

**Comment by Hyperx837** [comment]
here's the solution
```
yay -S downgrader
downgrader protobuf
```
and you will get a list of versions that you can downgrade the package to. out of that choose the version that suits the requirement.
while the version for `libprotobuf-lite.so.22` is `3.11.4` I had to install `libprotobuf-lite.so.30` is 3.19
