### ISSUE TITLE
Anbox on Odroid N2

### ISSUE THREAD

**Issue by tomasz-grobelny** [anbox/anbox#1499]
Should it be possible to run Android in Anbox on Odroid N2 with newer kernel (5.4+)? I saw there were some Anbox Android x86 images, but nothing ready made for ARM (or am I missing something?) I also found [Android Image build instructions](https://github.com/anbox/anbox/blob/master/docs/build-android.md) but I am not sure which target should I use (anbox_armv7a_neon-userdebug or anbox_arm64-userdebug - Ordoid N2 is aarch64). Anyone tried? Should it theoretically be possible? Any hints?

**Comment by tomasz-grobelny** [comment]
I managed to compile anbox and now I am struggling to run it. I am trying to run in three terminals:
1. In one terminal I have `anbox container-manager --data-path=/empty/dir/ --android-image=/path/to/android.img --privileged`- Seems to run fine save for warning that it is not running as daemon and something about missing anbox0 and networking.
2. In the second I am trying to run `anbox session-manager` but I get "libEGL warning: DRI2: failed to authenticate"
3. In the third I tried to run ` anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity` but it fails with "Session manager failed to become ready".

Any hints how to run anbox or how to get more debugging info?

**Comment by tomasz-grobelny** [comment]
Got it running with software rendering and SwiftShader. So answering my first question: yes, running Android in Anbox on Odroid N2 is possible. Just in case someone looks for it.

**Comment by xlazom00** [comment]
@tomasz-grobelny Can you write step by step manual how Can run it on N2 ?

**Comment by RussianNeuroMancer** [comment]
Maybe hardware rendering would work with Panfrost?

**Comment by tomasz-grobelny** [comment]
I got anbox working with SwiftShader and software rendering but later it turned out that OsmAnd does not work (map was black). Then I removed the software rendering command line switch and OsmAnd started working. After further thought the most probable explanation is that I was interpreting the black screen as anbox not working whereas it just took some time to start. The above warning from libEGL is still there but it does not seem to matter.

@xlazom00 - for now I can only give a brief description of my configuration running OsmAnd: I am using self compiled 5.4.8 kernel on Ubuntu 20.04. If you have any issues with this configuration maybe I can assist. I am planning to write a guide one day, but cannot promise any timeline.

**Comment by RussianNeuroMancer** [comment]
It's seems like compiling Anbox manually for aarch64 shouldn't be necessary anymore as (fresh enough) build [is available as deb now](https://launchpad.net/ubuntu/+source/anbox/0.0~git20200526-1build1/+build/19641796) (link at the bottom of the page). To install it on Ubuntu 20.04 you'll also need [this](http://ports.ubuntu.com/ubuntu-ports/ubuntu-ports/pool/universe/libs/libsdl2/libsdl2-2.0-0_2.0.12+dfsg1-1ubuntu1_arm64.deb) and [this](http://ports.ubuntu.com/ubuntu-ports/ubuntu-ports/pool/main/p/protobuf/libprotobuf-lite23_3.12.3-2ubuntu2_arm64.deb) package.

@tomasz-grobelny if possible, could you please share your compiled android image?

**Comment by tomasz-grobelny** [comment]
> @tomasz-grobelny if possible, could you please share your compiled android image?

I used image from http://anbox.postmarketos.org/ - did not compile myself.
