### ISSUE TITLE
AnBox windows Freeze

### ISSUE THREAD

**Issue by dani0001414** [anbox/anbox#150]
**Anbox release: 0.1.0 and system info: Segmentation fault :( But i'm using Linux Mint 18.1 Kde

**Description of the problem:**
When i started anbox session-manager in the console and i open the AnBox from the Kde start menu the window freezed. I have to kill the application manuali.

**Comment by dani0001414** [comment]
I find the problem. It was issued with the nvidia driver.

**Comment by morphis** [comment]
We don't support the nvidia driver yet and there are other bugs which we will use to track to get it working.
