### ISSUE TITLE
One issue and one need help

### ISSUE THREAD

**Issue by JacobHornbeck** [anbox/anbox#1503]
Issue:
In the Network Configuration section of the Anbox documentation, it says:
`$ snap set anbox container.netwokr.address=192.168.250.10`
Shouldn't it say:
`$ snap set anbox container.network.address=192.168.250.10`

Need Help:
I am trying to connect Anbox to the internet, but it doesn't seem to be working, and I don't know if I am even doing it right... I am running it in Linux Mint, and I tried the network configuration, but I'm not sure what I am supposed to change it to.

**Comment by Xerusial** [comment]
For internet connectivity, you should not have to change a single setting. It should automatically connect. Do you see the network bridge in `ip -a`?
