### ISSUE TITLE
Can't compile the anbox modules on kernel 5.7. Can you fix this?

### ISSUE THREAD

**Issue by rizzini** [anbox/anbox#1504]
^

**Comment by jedi2light** [comment]
You should try rebuild linux kernel with upstream ANDROID_ and ASHMEM features
Take a look on installation section: https://wiki.archlinux.org/index.php/Anbox

**Comment by rizzini** [comment]
Oh my.. I use Anbox for years and for that I didn't check the installation instructions. Shame on me. Thank you, sir.
