### ISSUE TITLE
Does anbox support ubuntu arm64 platform?

### ISSUE THREAD

**Issue by suchb** [anbox/anbox#1505]
Hello,
Does anbox support ubuntu arm64 platform?

**Comment by tomasz-grobelny** [comment]
Supported would be too much to say, but I managed to start Anbox on Odroid N2.

**Comment by anta5010** [comment]
@tomasz-grobelny have you built Anbox yourself? The one available in ubuntu repo is not compatible with 5.* Linux kernel.
Have you also built an android image yourself?
Could you share the procedure you used

**Comment by tomasz-grobelny** [comment]
Yes, anbox built from source. I used image from http://anbox.postmarketos.org/ I also used self-compiled kernel.

**Comment by anta5010** [comment]
@tomasz-grobelny what do you get when run "anbox check-features" and "anbox system-info"


I've built an anbox snap file for Ubuntu20.04 on arm64.
anbox container-manager starts successfully, but "anbox session-manager" reports:
"[ 2020-07-21 17:52:14] [daemon.cpp:61@Run] Failed to initialize SDL: No available video device"

I don't know if it's unsupported video drivers on my server or arm64 support issue, or my snap...

**Comment by anta5010** [comment]
@tomasz-grobelny what do you get when run "anbox check-features" and "anbox system-info"


I've built an anbox snap file for Ubuntu20.04 on arm64.
anbox container-manager starts successfully, but "anbox session-manager" reports:
"[ 2020-07-21 17:52:14] [daemon.cpp:61@Run] Failed to initialize SDL: No available video device"

I don't know if it's unsupported video drivers on my server or arm64 support issue, or my snap...

**Comment by anta5010** [comment]
I managed to start android on Ubuntu20.04 on arm64. I needed to run:
- "defaults write org.macosforge.xquartz.X11 enable_iglx -bool true" on my macos and 
- "export XAUTHORITY=$HOME/.Xauthority/" in my "ssh -X" session.

**Comment by xuguozhen** [comment]
Hi,all 
Have you run anbox on ubuntu20 arm64?
