### ISSUE TITLE
INVALID_APP_CREDENTIAL : App validation failed. Is app running on a physical device?

### ISSUE THREAD

**Issue by baptx** [anbox/anbox#1529]
I tried to use an Android app that asked for my phone number to login.
With a tool like mitmproxy, I can see that my phone number is sent with an HTTP POST request to https://www.googleapis.com/identitytoolkit/v3/relyingparty/sendVerificationCode?alt=proto&key= (followed by a key). I also noticed an HTTP request header `X-Client-Version: Android/GmsCore/X19003001/FirebaseCore-Android`.
In the HTTP response, there is "400 Bad Request" status with an error `INVALID_APP_CREDENTIAL : App validation failed. Is app running on a physical device?`.
The issue seems related to this one that says it is a protection against emulators: https://github.com/firebase/FirebaseUI-Android/issues/790
However, is there any chance to bypass this error on Anbox?

Update: the User-Agent HTTP request header contains the word "Anbox". Maybe using an official user agent string could help?

**Comment by sprajagopal** [comment]
I'm curious about this also. Is there a way to change the user agent?

**Comment by baptx** [comment]
@stale UP
