### ISSUE TITLE
This PPA does not support focal. Installing on LM20

### ISSUE THREAD

**Issue by silocoder** [anbox/anbox#1532]
Im trying to install anbox on Linuxmint 20 Cinnamon.

When I attempt to add repository for kernel modules I get the following error:

```
~$ sudo add-apt-repository ppa:morphis/anbox-support
Cannot add PPA: ''This PPA does not support focal''
```
What is the issue and is there a workaround? Thanks!

**Comment by stevennyman** [comment]
On Ubuntu 19.10, 20.04 and newer the modules are included with the kernel. Since Linux Mint 20 Cinnamon is based on Ubuntu 20.04, I would assume the modules are pre-installed, and the repository is not necessary. If Anbox has problems running, you can try using some of these steps to troubleshoot them: https://github.com/anbox/anbox/issues/1517#issuecomment-660724590

**Comment by skarmiglione** [comment]
it dont work for me, ashmem dont load Failed to start as either binder or ashmem kernel drivers are not loaded
why alwayls are too hard... :'C

**Comment by mullerivan** [comment]
git clone https://github.com/anbox/anbox-modules.git
cd anbox-modules
sh INSTALL.sh
sudo modprobe ashmem_linux
sudo modprobe binder_linux
sudo reboot

Enjoy!

**Comment by rafikiphoto** [comment]
Any ideas for this one? I'm trying to install Everpad app:

sudo add-apt-repository ppa:nvbn-rm/ppa
[sudo] password for brian:     
Cannot add PPA: ''This PPA does not support focal''.

**Comment by moshebagelfresser** [comment]
Noobslab not supported either

**Comment by hs4842** [comment]
Same problem here....

**Comment by cestcela** [comment]
> git clone https://github.com/anbox/anbox-modules.git cd anbox-modules sh INSTALL.sh sudo modprobe ashmem_linux sudo modprobe binder_linux sudo reboot
> 
> Enjoy!

You are the best!

**Comment by englianhu** [comment]
> 

```diff
+:~$ git clone https://github.com/anbox/anbox-modules.git
Cloning into 'anbox-modules'...
remote: Enumerating objects: 132, done.
remote: Total 132 (delta 0), reused 0 (delta 0), pack-reused 132
Receiving objects: 100% (132/132), 68.65 KiB | 2.75 MiB/s, done.
Resolving deltas: 100% (48/48), done.
+:~$ cd anbox-modules
+:~/anbox-modules$ sh INSTALL.sh

Creating symlink /var/lib/dkms/anbox-ashmem/1/source ->
                 /usr/src/anbox-ashmem-1

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.15.7-051507-generic all KERNEL_SRC=/lib/modules/5.15.7-051507-generic/build...(bad exit status: 2)
-ERROR (dkms apport): binary package for anbox-ashmem: 1 not found
-Error! Bad return status for module build on kernel: 5.15.7-051507-generic (x86_64)
Consult /var/lib/dkms/anbox-ashmem/1/build/make.log for more information.

Creating symlink /var/lib/dkms/anbox-binder/1/source ->
                 /usr/src/anbox-binder-1

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.15.7-051507-generic all KERNEL_SRC=/lib/modules/5.15.7-051507-generic/build...(bad exit status: 2)
-ERROR (dkms apport): binary package for anbox-binder: 1 not found
-Error! Bad return status for module build on kernel: 5.15.7-051507-generic (x86_64)
Consult /var/lib/dkms/anbox-binder/1/build/make.log for more information.
-modprobe: FATAL: Module ashmem_linux not found in directory /lib/modules/5.15.7-051507-generic
-modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.7-051507-generic
-ls: cannot access '/dev/binder': No such file or directory
-ls: cannot access '/dev/ashmem': No such file or directory
+:~/anbox-modules$ sudo modprobe ashmem_linux
-modprobe: FATAL: Module ashmem_linux not found in directory /lib/modules/5.15.7-051507-generic
+:~/anbox-modules$ sudo modprobe binder_linux
-modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.7-051507-generic
```
https://github.com/geeks-r-us/anbox-playstore-installer/issues/76

**Comment by GoldenAJF** [comment]
> git clone https://github.com/anbox/anbox-modules.git cd anbox-modules sh INSTALL.sh sudo modprobe ashmem_linux sudo modprobe binder_linux sudo reboot
> 
> Enjoy!

This changed nothing for me and I am still having the same issues.

**Comment by Fuseteam** [comment]
people please read the documentation as mentioned [here](https://github.com/anbox/anbox/issues/1532#issuecomment-660725645) you do not need the modules on current ubuntu or mint

**Comment by GoldenAJF** [comment]
When I try to modprobe ashmem and binder, ashmem says it exists but binder doesn't and I can't find it anywhere on my system, is this normal?

**Comment by hs4842** [comment]
I'm running LM 20.3 w/ 5.16.15-051615-generic kernel. Some kernels have it, most don't. Anbox hasn't been updated to contend with this.--On 3/20/22, 12:03 AM Golden Boy 9000 ***@***.***> wrote:

   
  When I try to modprobe ashmem and binder, ashmem says it exists but binder doesn't and I can't find it anywhere on my system, is this normal?

**Comment by Fuseteam** [comment]
@GoldenAJF @hs4842 you can check if binder "exists" by running `grep binder /proc/filesystems`
unless mint is doing it's own special thing you should get the following output
```
nodev   binder
```
it has been part of the debian and ubuntu kernel since 2019
[![2022-03-20-024736_720x132_scrot](https://user-images.githubusercontent.com/10421851/159149990-61f0f594-b00f-4c5d-a12d-54cec27560b6.png)](https://docs.anbox.io/userguide/install_kernel_modules.html)

**Comment by GoldenAJF** [comment]
> @GoldenAJF @hs4842 you can check if binder "exists" by running `grep binder /proc/filesystems` unless mint is doing it's own special thing you should get the following output
> 
> ```
> nodev   binder
> ```
> 
> it has been part of the debian and ubuntu kernel since 2019 [![2022-03-20-024736_720x132_scrot](https://user-images.githubusercontent.com/10421851/159149990-61f0f594-b00f-4c5d-a12d-54cec27560b6.png)](https://docs.anbox.io/userguide/install_kernel_modules.html)

Thank you for this, it appears I have a different issue with anbox then.
