### ISSUE TITLE
How to spoof Device ID & IMEI in anbox?

### ISSUE THREAD

**Issue by lukedoomer** [anbox/anbox#155]
In normal android environment, I will get root permissions then install superSU and xprivacy to achieve this goal. How to spoof Device ID & IMEI in anbox? In other words, How to get root permission in anbox?

**Comment by morphis** [comment]
You can use something like 

```
$ adb shell
android$ su
```

to get root inside the container. Root permissions for apps isn't possible.

For what reason do you need the device-id and IMEI?

**Comment by lukedoomer** [comment]
I always feed some apps with the fake identity so that the apps always treat me a different newcomer. And the applications never know I am still using the same emulator or anbox or physical device. Would you mind explaining why root permission for app isn't possible? Is possible to inject SuperSU into default anbox image/rom?

**Comment by morphis** [comment]
@lukedoomer Our goal is to deliver a AOSP base experience with just as minimal additions on top. If you want to add something like SuperSU by default that is something you can easily do on your own by building your own android.img and doing any needed customization.

As we build the shipped android.img currently in userdebug mode there is still the ability for a user to get root via a shell and the included su binary in the image. For apps I can't say as that is something I never really looked into.
