### ISSUE TITLE
Launch anbox.appmgr via crontab

### ISSUE THREAD

**Issue by eduardogoncalves** [anbox/anbox#1552]
Hello, I'm able to launch anbox.appmgr from a SSH session using: `DISPLAY=:0 /snap/bin/anbox.appmgr`.
I'm also able to launch anbox.appmgr from a sh script:
```bash
#!/bin/bash
if ! pidof org.anbox.appmgr >/dev/null 2>&1;then DISPLAY=:0 /snap/bin/anbox.appmgr ;fi
```

But I can't figure out how to launch anbox.appmgr from crontab.

I tried:
```
* * * * * /bin/bash /home/username/./startAnbox.sh
* * * * * DISPLAY=:0 /bin/bash /home/username/./startAnbox.sh
* * * * * if ! pidof org.anbox.appmgr >/dev/null 2>&1;then DISPLAY=:0 /snap/bin/anbox.appmgr ;fi
* * * * * DISPLAY=:0 /snap/bin/anbox.appmgr
```
but all without success. Can someone point me how to achieve this?

**Comment by necessarily-equal** [comment]
you probably need to give it a dbus handle. For example, `dbus-run-session startAnbox.sh` will set the environment variables for a **new** dbus session. I'm not too sure how you would do that with the same session bus as your display though.
