### ISSUE TITLE
Implement lxc-checkpoint

### ISSUE THREAD

**Issue by jnnks** [anbox/anbox#1554]
[lxc-checkpoint](https://linuxcontainers.org/lxc/manpages/man1/lxc-checkpoint.1.html) can be used to suspend and restore an LXC containers. Loading the previous container state might be more performant than cold booting Android every time Anbox is launched.

API entries from `lxccontainer.h`:
```
/*!
* \brief Checkpoint a container.
*
* \param c Container.
* \param directory The directory to dump the container to.
* \param stop Whether or not to stop the container after checkpointing.
* \param verbose Enable criu's verbose logs.
*
* \return \c true on success, else \c false.
* present at compile time).
*/
bool (*checkpoint)(struct lxc_container *c, char *directory, bool stop, bool verbose);

/*!
* \brief Restore a container from a checkpoint.
*
* \param c Container.
* \param directory The directory to restore the container from.
* \param verbose Enable criu's verbose logs.
*
* \return \c true on success, else \c false.
*
*/
bool (*restore)(struct lxc_container *c, char *directory, bool verbose);
```

I'll hijack this thread as a report for insights, issues and the general research progress.

**Comment by jnnksdev** [comment]
The commandline tools for LXC are not able to create a container checkpoint with a basic setup.
I posted a Github issue and a StackOverflow question: 
* https://github.com/lxc/lxc/issues/3521#issue-679387746
* https://stackoverflow.com/questions/63424388/lxc-checkpoint-fails-with-ambiguous-error-message

This comment from the linuxcontainer.org forum might give more insight:
> The error is fairly clear, the stateful snapshot can’t be made because of CRIU’s inability to process nested containers of any kind.

this is from Stéphane Graber (LXC Maintainer): [Stateful snapshot not working: Can’t dump nested uts namespace](https://discuss.linuxcontainers.org/t/stateful-snapshot-not-working-cant-dump-nested-uts-namespace-cant-make-utsns-id/8564)

At this point it's not clear for me, wether this is blocking checkpoint/restore in Anbox context.

**Comment by jnnksdev** [comment]
## checkpointing and restoring Anbox
After playing around with the C API as well, the actual implementation is the next step. The goal is to decrease the startup time for Anbox. That will most likely come with complications and hurdles. The documentation here will not be too detailed as I expect it to change quite often.

### Step 1: Suitable places to checkpoint and restore
The Android system sends a message indicating, that the boot process is done. This is where the checkpointing will be implemented or at least invoked.
The container can be restored at the same place where it is started.


##### Step 2: Checkpointing the container state (soon)
##### Step 3: Restoring the container state (soon)

**Comment by dythebs** [comment]
Are there any new developments?Is there a way to execute lxc-checkpoint on the console? Thanks!
