### ISSUE TITLE
Anbox stuck at the starting screen and closes after a few

### ISSUE THREAD

**Issue by TanveerSwaich** [anbox/anbox#1560]
Did everything right and verified including starting up ashmem and binder kernel, also using the latest version with debugging enabled and posting the log below:
This script will collect a few interesting things which developers will
need to have a better insight into the Anbox system when something goes
wrong.

PLEASE NOTE: The collected log files may collect information about your
system. Please have a look before you're sending them to anyone!

Collecting anbox log files ... 
+ cp /var/snap/anbox/common/data/system.log /tmp/tmp.7LtLT5xWKA
cp: cannot stat '/var/snap/anbox/common/data/system.log': No such file or directory
+ true
+ cp /var/snap/anbox/common/containers/lxc-monitord.log /tmp/tmp.7LtLT5xWKA
cp: cannot stat '/var/snap/anbox/common/containers/lxc-monitord.log': No such file or directory
+ true
+ cp /var/snap/anbox/common/logs/container.log /tmp/tmp.7LtLT5xWKA
cp: cannot stat '/var/snap/anbox/common/logs/container.log': No such file or directory
+ true
+ cp /var/snap/anbox/common/logs/console.log* /tmp/tmp.7LtLT5xWKA
cp: cannot stat '/var/snap/anbox/common/logs/console.log*': No such file or directory
+ true
+ /snap/anbox/194/command-anbox.wrapper system-info
+ true
+ [ -e /etc/systemd/system/snap.anbox.container-manager.service ]
+ sudo journalctl --no-pager -u snap.anbox.container-manager.service
+ set +x

DONE!

Do you want to include the kernel log of your system? [y/N]

Generating archive with all log files in /home/reddragon ...
  adding: container-manager.log (deflated 93%)
  adding: system-info.log (deflated 39%)
DONE!

**Comment by epiixgd76** [comment]
Try reinstalling anbox.

**Comment by Saime-0** [comment]
> Try reinstalling anbox.

does not help, tried all the ways
