### ISSUE TITLE
how to compile anbox to run on mobile

### ISSUE THREAD

**Issue by sdksdk1986** [anbox/anbox#1566]
hi  as i known anbox can run on spetical mobile .but  how to compile the sourse step by step to run on mobile ,any one can tell me please? thanks!

**Comment by necessarily-equal** [comment]
if you don't hint at your distribution, nobody could answer unfortunately. postmarketOS and Arch Linux ARM have Anbox in their repositories, and mobian have some instructions on the pine64 forums, for example. Refer to your distribution's documentation.
