### ISSUE TITLE
On 20.04.1: ls -1 /dev/{ashmem,binder} yields anticipated result for /dev/ashmem, but an error for /dev/binder (also, Anbox runs with Secure Boot enabled!)

### ISSUE THREAD

**Issue by GizmoChicken** [anbox/anbox#1569]
# Background #

In a [post on AskUbuntu](https://askubuntu.com/questions/1267823/module-ashmem-doesnt-load-with-secure-boot-on-but-binder-does-load-with-se), I reported that:

>I'm running **Ubuntu 20.04.1** with default **kernel 5.4.0-42-generic** (installed from Main) on a UEFI system. I want to load two kernel modules ("**ashmem**" and "**binder**") with Secure Boot enabled. At least for me, "binder" loads fine with Secure Boot enabled, but "ashmem" does ***not*** load with Secure Boot enabled. *Both* modules load with Secure Boot disabled.

To the above, I’ll add that I had enabled Secure Boot (and enrolled MOK) during the *initial* clean  installation of Ubuntu 20.04. Even so, following the *excellent* suggestion provided by AskUbuntu user [Rinzwind](https://askubuntu.com/users/15811/rinzwind), I ran the following *after* the initial installation:

```
sudo kmodsign sha512 /var/lib/shim-signed/mok/MOK.priv /var/lib/shim-signed/mok/MOK.der /lib/modules/`uname -r`/kernel/drivers/staging/android/ashmem_linux.ko
```
And after running the above, I re-ran:

```
sudo modprobe ashmem_linux

sudo modprobe binder_linux

lsmod | grep -e ashmem_linux -e binder_linux
```

SUCCESS!  Both “ashmem” and “binder” loaded!  Thanks [Rinzwind](https://askubuntu.com/users/15811/rinzwind)!!

What’s more, [Anbox](https://anbox.io/) starts for me now with Secure Boot enabled, which was my end goal.  :)

# Error Message #

Although both “ashmem” and “binder” now load, and although [Anbox](https://anbox.io/) now starts (and seems to work properly) for me now with Secure Boot enabled, I still ran the following:

```
ls -1 /dev/{ashmem,binder}
```
And I obtained the following:

```
ls: cannot access '/dev/binder': No such file or directory
/dev/ashmem
```
Now, I’m still curious *why* I’m getting the above error ("cannot access '/dev/binder': No such file or directory") with regard to the “binder” module, and whether I should be concerned.

# Questions #

1.  Should /dev/binder be created upon loading the “binder” module?  (And should the error concern me?)
2.  If /dev/binder should be created upon loading the “binder” module, how can I force  /dev/binder to be created?
3.  And if /dev/binder should be created upon loading the “binder” module (that is, if I've discovered a bug), where on Launchpad should I report the error?

To reiterate, according to lsmod, both “ashmem” and “binder” load.  Also, [Anbox](https://anbox.io/) seems to be working properly for me now with Secure Boot enabled.  I’m posting here to (a) satisfy my own curiosity, (b) document this for others, and (c) determine whether a bug report should be filed regarding binder (and where to file it, if warranted).

**Comment by GizmoChicken** [comment]
Reviewing the [installation page for Anbox](https://github.com/anbox/anbox/blob/master/docs/install.md) more closely, I noticed the following:
 
>In Ubuntu 19.10 the binder driver doesn't create /dev/binder when loaded. That is intentional. Instead it provides support for binderfs ([see https://brauner.github.io/2019/01/09/android-binderfs.html](https://brauner.github.io/2019/01/09/android-binderfs.html)) which is instead since PR anbox/anbox#1309
 
Although the above doesn't specifically refer the situation for Ubuntu 20.04, I'm *guessing* that the same applies to it. With that in mind, here are proposed answers to my own questions:
 
 1. Nope, /dev/binder shouldn't be created upon loading the “binder” module? (And the error message shouldn't concern me.)
 2. There's no need (and probably no way) to force /dev/binder to be created.
 3. There's no need to report this error on Launchpad (or elsewhere).
 
Given the above, I've marked this issue as CLOSED.  Please feel free to reopen if appropriate.

@morphis 
 
Please note that I opened a *new* issue regarding the need for using “kmodsign” for the “ashmem” module when wanting to run Anbox on Ubuntu 20.04 with Secure Boot enabled.  Please see [Issue #1570](https://github.com/anbox/anbox/issues/1570).

**Comment by Screwitfix** [comment]
This answer is so wired:

Nope, /dev/binder shouldn't be created upon loading the “binder” module? (And the error message shouldn't concern me.)

Dune to that error message, anbox is not starting! If that is of no concern then scrap this project as it will not be usable under Ubuntu 2020.

**Comment by GizmoChicken** [comment]
>This answer is so wired:
>
>Nope, /dev/binder shouldn't be created upon loading the “binder” module? (And the error message shouldn't concern me.)

My *original* answer included a *typo*, in that I inadvertently ended the sentence with a question mark (?) rather than a period (.)
I edited the answer to replace the question mark with a period, and I believe the answer now makes sense.

>Dune to that error message, anbox is not starting! If that is of no concern then scrap this project as it will not be usable under Ubuntu 2020.

Actually, ***no***, if Anbox is failing to start for you, that failure is ***not*** likely due to the "ls: cannot access '/dev/binder': No such file or directory" error.   I say this because *Anbox starts for me*, even though I see the "ls: cannot access '/dev/binder': No such file or directory" error.  So again, that error does ***not*** seem to prevent Anbox from starting.

To reiterate, I discovered *after* posting my initial bug report that, according to the linked install page, "[binder driver doesn't create /dev/binder when loaded. That is intentional. Instead it provides support for binderfs](https://github.com/anbox/anbox/blob/master/docs/install.md)."  Hence, I closed my own bug report.

Why Anbox is failing to start for you, I can't say.  But you should confirm that "ashmem" is starting for you.  If "ashmem" isn't starting for you, perhaps you have Secure Boot enabled, which, at once time, was what prevented "ashmem" from starting for me.  But as I reported above (and [elsewhere](https://github.com/anbox/anbox/issues/1570)), I was able to start "ashmem" with Secure Boot enabled by using the appropriate "kmodsign" command.

**Comment by Screwitfix** [comment]
Sorry for my ruff comment - after 12 hours trying to get ANBOX to work I was slightly irritated. 
But the fact remains:
Instal via Ubuntu 20.04.1 repository demands /dev/binder so there is a BUG that needs attention. Easiest would be to remove ANBOX from the official Ubuntu repository. 
The SNAP --edge version comes also with issues. I tried to install ANBOX on two computers and on both the same issues came up. I managed to fix some but one - missing liblxc.so.1 - remained unfixable (for me). 
I filed an issue and hope for a solution.

**Comment by GizmoChicken** [comment]
>But the fact remains:
>Instal via Ubuntu 20.04.1 repository demands /dev/binder so there is a BUG that needs attention. 

I believe that you are confusing to things, namely: 
1.  the need for the starting the “binder” module; and 
2. the need for creating /dev/binder.

Yes, for Anbox to work, you *must* be able to start the “binder” module.

If not already started, you can start the “binder” module using the following:
```
sudo modprobe binder_linux
```
And you can verify that the “binder” module started using the following:
```
lsmod | grep -e binder_linux
```
After running the above, provided the “binder” module started, you'll see something like this:
```
binder_linux          [various numbers]  [various numbers]
```
If you see the above, you've successfully started the “binder” module.  And guess what: on Ubuntu 20.04.1, you can follow the above steps to start the “binder” module even if you haven't installed Anbox.

But regarding creating /dev/binder, as I mentioned before, *after* posting this "bug" report, I learned that, for **Ubuntu 19.10** and **Ubuntu 20.04**, creating /dev/binder is ***not*** necessary for Anbox to start and run.  That is, ***Anbox starts and runs for me on Ubuntu 20.04.1, even though I see the "ls: cannot access '/dev/binder': No such file or directory" error***. So again, for me, that error does ***not*** to prevent Anbox from starting and running on Ubuntu 20.04.1.  Hence, I closed my own bug report.

Please read this again:
>Why Anbox is failing to start for you, I can't say. But you should confirm that "ashmem" is starting for you. If "ashmem" isn't starting for you, perhaps you have Secure Boot enabled, which, at one time, was what prevented "ashmem" from starting for me. But as I reported above (and [elsewhere](https://github.com/anbox/anbox/issues/1570)), I was able to start "ashmem" with Secure Boot enabled by using the appropriate "kmodsign" command.

Apparently I can't emphasize this enough, I'll say it again: ***Anbox starts and runs for me on Ubuntu 20.04.1***, even though I see the "ls: cannot access '/dev/binder': No such file or directory" error. So once again, for me, that error does ***not*** to prevent Anbox from starting and running on Ubuntu 20.04.1.
