### ISSUE TITLE
If wanting to run Anbox on Ubuntu 20.04 with Secure Boot enabled (which is possible!), must use “kmodsign” for the “ashmem” module

### ISSUE THREAD

**Issue by GizmoChicken** [anbox/anbox#1570]
# Background #

In a [post on AskUbuntu](https://askubuntu.com/questions/1267823/module-ashmem-doesnt-load-with-secure-boot-on-but-binder-does-load-with-se), I reported that:

>I'm running **Ubuntu 20.04.1** with default **kernel 5.4.0-42-generic** (installed from Main) on a UEFI system. I want to load two kernel modules ("**ashmem**" and "**binder**") with Secure Boot enabled. At least for me, "binder" loads fine with Secure Boot enabled, but "ashmem" does ***not*** load with Secure Boot enabled. *Both* modules load with Secure Boot disabled.

To the above, I’ll add that I had enabled Secure Boot (and enrolled MOK) during the *initial* clean  installation of Ubuntu 20.04. Even so, following the *excellent* suggestion provided by [Rinzwind](https://askubuntu.com/users/15811/rinzwind), I ran the following *after* the initial installation:

```
sudo kmodsign sha512 /var/lib/shim-signed/mok/MOK.priv /var/lib/shim-signed/mok/MOK.der /lib/modules/`uname -r`/kernel/drivers/staging/android/ashmem_linux.ko
```
And after running the above, I re-ran:

```
sudo modprobe ashmem_linux

sudo modprobe binder_linux

lsmod | grep -e ashmem_linux -e binder_linux
```

SUCCESS!  Both “ashmem” and “binder” loaded!  Thanks [Rinzwind](https://askubuntu.com/users/15811/rinzwind)!!

What’s more, [Anbox](https://anbox.io/) starts for me now with Secure Boot enabled, which was my end goal.  :)

# Request #

@morphis 

I hope that you will please consider updating the Anbox installer to (when installing Anbox onto Ubuntu 20.04 with Secure Boot enabled) *automatically* run the following or similar:

```
sudo kmodsign sha512 /var/lib/shim-signed/mok/MOK.priv /var/lib/shim-signed/mok/MOK.der /lib/modules/`uname -r`/kernel/drivers/staging/android/ashmem_linux.ko
```
Also, please note that whether Secure Boot is enabled can be determined using the `sudo mokutil --sb-state` command.
For example, running `sudo mokutil --sb-state` on a computer having Secure Boot enabled should yield:
```
$ sudo mokutil --sb-state
SecureBoot enabled
```
And running `sudo mokutil --sb-state` on a computer having Secure Boot disabled should yield:
```
$ sudo mokutil --sb-state
SecureBoot disabled
```
Perhaps the installer could use the `mokutil --sb-state` command to determine whether the the installer should, or should not, run the `kmodsign` command.

Thanks!

**Comment by JonasVautherin** [comment]
I opened a PR to take that into account in the installation instructions. Feel free to review! https://github.com/anbox/anbox/pull/1588

**Comment by LucasPa** [comment]
Hi!

I can't load ashmem. So I tried to run as suggested: 

`sudo kmodsign sha512 /var/lib/shim-signed/mok/MOK.priv /var/lib/shim-signed/mok/MOK.der /lib/modules/`uname -r`/kernel/drivers/staging/android/ashmem_linux.ko`

But it fails with the following error:

> At main.c:248:
> - SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:69
> - SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:76
> kmodsign: /var/lib/shim-signed/mok/MOK.priv: No such file or directory

Does it make any sense to you?

**Comment by GizmoChicken** [comment]
>Does it make any sense to you?


Honestly, no, I have no idea what that error means.  But if you have Secure Boot enabled, and if suspect that having Secure Boot enabled is causing the error that you're seeing, I suggest:  

Disable Secure Boot  and see if that cures the problem. 

 If disabling Secure Boot cures the problem, then there's your solution.    If disabling Secure Boot fails to cure the problem, you'll need to look elsewhere for a solution.

**Comment by LucasPa** [comment]
Hi GizmoChicken,

Thanks for your answer. Disabling secure boot helped me to run successfully modprobe such that ```lsmod | grep -e ashmem_linux -e binder_linux``` now returns:
> ashmem_linux           20480  0
> binder_linux          180224  0

But launching anbox still fails. ```anbox system-info``` returns (in the kernel section):
>   version: Linux version 5.4.0-56-generic (buildd@lgw01-amd64-025) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020
>  binder: false
>  ashmem: true

Please note that I have the same issue on an other computer !

Lucas

**Comment by JamesB192** [comment]
Assuming (a can opener and) findutils installed could you run `find /lib/modules -iname ashmem_linux.ko` I think that arcane error is referring to a line in the OpenSSL source code where a failing fopen() call is and then where the function the call is in starts and that the `/var/lib/shim-signed/mok/MOK.priv` isn't there. D'oh. new plan try running `find /var/lib -iname MOK.priv` and probably installing shim or something.

**Comment by LucasPa** [comment]
Hi,

The command `/lib/modules -iname ashmem_linux.ko` returns

>
/lib/modules/5.4.0-56-generic/kernel/drivers/staging/android/ashmem_linux.ko
>
/lib/modules/5.4.0-58-generic/kernel/drivers/staging/android/ashmem_linux.ko
>
/lib/modules/5.4.0-54-generic/kernel/drivers/staging/android/ashmem_linux.ko

The command `find /var/lib -iname MOK.priv` returns

> /var/lib/shim-signed/mok/MOK.priv

Is there something I should to given those results ?

**Comment by JamesB192** [comment]
According to that the invocation from your Dec 03 post should probably just work (unless the /var/lib/shim-signed/mok/MOK.der is absent/bad or the corresponding .priv file is bad):

```console
sudo kmodsign sha512 /var/lib/shim-signed/mok/MOK.priv /var/lib/shim-signed/mok/MOK.der /lib/modules/`uname -r`/kernel/drivers/staging/android/ashmem_linux.ko
```

looking at [this](https://ubuntu.com/blog/how-to-sign-things-for-secure-boot) blog post is probably useful.

**Comment by dtantono** [comment]
since Windows 11 enforce Secure boot to be enabled. I think this will become problematic for dual boot users.

**Comment by AnishDe12020** [comment]
> since Windows 11 enforce Secure boot to be enabled. I think this will become problematic for dual boot users.

After installing Windows 11, i disabled secure boot and setup up a dual boot and it works fine so I guess people are good to go

**Comment by AnishDe12020** [comment]
> # Background
> In a [post on AskUbuntu](https://askubuntu.com/questions/1267823/module-ashmem-doesnt-load-with-secure-boot-on-but-binder-does-load-with-se), I reported that:
> 
> > I'm running **Ubuntu 20.04.1** with default **kernel 5.4.0-42-generic** (installed from Main) on a UEFI system. I want to load two kernel modules ("**ashmem**" and "**binder**") with Secure Boot enabled. At least for me, "binder" loads fine with Secure Boot enabled, but "ashmem" does _**not**_ load with Secure Boot enabled. _Both_ modules load with Secure Boot disabled.
> 
> To the above, I’ll add that I had enabled Secure Boot (and enrolled MOK) during the _initial_ clean installation of Ubuntu 20.04. Even so, following the _excellent_ suggestion provided by [Rinzwind](https://askubuntu.com/users/15811/rinzwind), I ran the following _after_ the initial installation:
> 
> ```
> sudo kmodsign sha512 /var/lib/shim-signed/mok/MOK.priv /var/lib/shim-signed/mok/MOK.der /lib/modules/`uname -r`/kernel/drivers/staging/android/ashmem_linux.ko
> ```
> 
> And after running the above, I re-ran:
> 
> ```
> sudo modprobe ashmem_linux
> 
> sudo modprobe binder_linux
> 
> lsmod | grep -e ashmem_linux -e binder_linux
> ```
> 
> SUCCESS! Both “ashmem” and “binder” loaded! Thanks [Rinzwind](https://askubuntu.com/users/15811/rinzwind)!!
> 
> What’s more, [Anbox](https://anbox.io/) starts for me now with Secure Boot enabled, which was my end goal. :)
> 
> # Request
> @morphis
> 
> I hope that you will please consider updating the Anbox installer to (when installing Anbox onto Ubuntu 20.04 with Secure Boot enabled) _automatically_ run the following or similar:
> 
> ```
> sudo kmodsign sha512 /var/lib/shim-signed/mok/MOK.priv /var/lib/shim-signed/mok/MOK.der /lib/modules/`uname -r`/kernel/drivers/staging/android/ashmem_linux.ko
> ```
> 
> Also, please note that whether Secure Boot is enabled can be determined using the `sudo mokutil --sb-state` command.
> For example, running `sudo mokutil --sb-state` on a computer having Secure Boot enabled should yield:
> 
> ```
> $ sudo mokutil --sb-state
> SecureBoot enabled
> ```
> 
> And running `sudo mokutil --sb-state` on a computer having Secure Boot disabled should yield:
> 
> ```
> $ sudo mokutil --sb-state
> SecureBoot disabled
> ```
> 
> Perhaps the installer could use the `mokutil --sb-state` command to determine whether the the installer should, or should not, run the `kmodsign` command.
> 
> Thanks!

I am getting this error upon trying the first command. Any fix? Did I go wrong somwhere?

![image](https://user-images.githubusercontent.com/63192115/124715714-e9d61100-df20-11eb-9fee-58471581187e.png)

**Comment by dtantono** [comment]
@AnishDe12020 I remembered that the current Windows 11 is still unfinished and I hope this behaviour persists until the final version is out.

**Comment by AnishDe12020** [comment]
> @AnishDe12020 I remembered that the current Windows 11 is still unfinished and I hope this behaviour persists until the final version is out.

Yes Windows 11 is still an Insiders Dev but yes we want nothing to break later on

**Comment by JeffRockatansky** [comment]
Has this been solved somehow?

**Comment by Fuseteam** [comment]
what did you see, @JeffRockatansky? what did you see that led you to this issue?
