### ISSUE TITLE
ERROR while loading shared libraries: liblxc.so.1 not found

### ISSUE THREAD

**Issue by Screwitfix** [anbox/anbox#1574]
****
1. Please check that no similar bug is already reported. > **Yes and issue was closed with out solution!**
2. Make sure you are running the latest version of Anbox > **Issue is with  `snap refresh --devmode --edge anbox`**
3. Make sure you have debug logs enabled: > I**nstall Log / crash report [here]**(https://raw.githubusercontent.com/Screwitfix/logs/master/_usr_bin_anbox.1000.crash)
****
Installing "snap install --devmode --edge anbox" on a fresh UBUNTU 20.04 returned several errors.

**I managed to fix the first 3 issues:**
1. Kernel Module not loaded
2. SSE Support from CPU

**missing liblxc.so.1. I tried this so fare:** 
Setting the Path:
 `~$ LD_LIBRARY_PATH=/usr/lib,/usr/local/lib,/usr/lib/x86_64-linux-gnu`
Linking the libs: 
`~$  sudo ln -s /usr/lib/x86_64-linux-gnu/liblxc.so.1  /usr/lib/liblxc.so.1`
`~$ sudo ln -s /usr/lib/x86_64-linux-gnu/liblxc.so.1 /usr/lib/liblxc.so.1.4.0`

I got the same ERROR on two Computer both running the latest Ubuntu 20.04
Please advice how to fix this error.

**Comment by GizmoChicken** [comment]
Regarding:
>missing liblxc.so.1. I tried this so fare:
>Setting the Path:
>~$ LD_LIBRARY_PATH=/usr/lib,/usr/local/lib,/usr/lib/x86_64-linux-gnu
>Linking the libs:
>~$ sudo ln -s /usr/lib/x86_64-linux-gnu/liblxc.so.1 /usr/lib/liblxc.so.1
>~$ sudo ln -s /usr/lib/x86_64-linux-gnu/liblxc.so.1 /usr/lib/liblxc.so.1.4.0

I doubt that I'll be able to fully resolve your issue, but I hope the following helps:

***BEFORE*** installing Anbox on my freshly installed Ubuntu 20.04.1 system, "**liblxc.so.1**" was nowhere to be found on my system (or at least I can't find it).

However, ***AFTER*** installing Anbox (using "snap install --devmode --beta anbox"), Anbox started and ran, and "**liblxc.so.1**" could to be found at the following locations:

      snap/anbox/186/lib
      snap/anbox/195/usr/lib

Moreover, near as I can tell, liblxc.so.1 could still not be found anywhere in my /usr directory, even after Anbox was installed and started.

So, I'm not sure what went wrong for you, but I'd suggest that you revert/remove everything that you've done related to installing Anbox on Ubuntu 20.04.1, and then try again.   Better still, try again starting from a *clean* installation of Ubuntu 20.04.1.

Regarding the following:
>I managed to fix the first 3 issues:
>
>   Kernel Module not loaded
>    /dev/binderfs not found
>   SSE Support from CPU

I'm not sure about the details of these three issues you encountered, or what you've done to resolve them.  But with regard to any necessary kernel modules, when installing Anbox on **Ubuntu 20.04.1**, you do ***not*** need to add any PPAs.  The necessary kernel modules are already available in the kernel that ships with Ubuntu 20.04.1.  For me, the kernel modules start on their own after Anbox is installed.  But maybe I'm just lucky.  On *your* system, *maybe* you'll need to use modprobe to start them. 

Also, although this probably isn't related to your issue, I'll just note that, if Secure Boot is enabled on your system, you'll need to add another (simple) step.  But I recommend *disabling* Secure Boot, at least until you figure out the other issues.

**Comment by Screwitfix** [comment]
Thank you - your replay helped a lot. 
As a fact "liblxc.so.1" is a kind of dummy linked to "/usr/lib/x86_64-linux-gnu/liblxc.so.1.7.0". 
I tried to make symbolic links but none of them worked because I placed the links into the wrong directory.

`sudo ln -s /usr/lib/x86_64-linux-gnu/liblxc.so.1.7.0 snap/anbox/195/usr/lib/liblxc.so.1
`
That may do the trick - I will try it once I have time, later today.
I then will give a feedback and also provide the other "fix" that I used.

**Comment by GizmoChicken** [comment]
>I'm installing ANBOX on a fresh / clean UBUNTU 20.04.01 on two computer.
>
>Computer(A) Intel Core i5-4590 @ 3.30Ghz, 16gb RAM
>
>      Install of "snap install --devmode --beta anbox": success
>
>      Install of "snap install --devmode --edge anbox": failed with missing liblxc.so.1
>
>Computer(B) AMD G-T56N Dual CoreDuo @ 1.6GHz and 4gb RAM
>
>      Install of "snap install --devmode --beta anbox": failed with missing SSE 4.x support
>
>      Install of "snap install --devmode --edge anbox": failed with missing SSE2/SSE3 support & missing liblxc.so.1
>
>During preparation I discovered that Ubuntu 20.04 was not loading the required Kernel Modules by default.
>      sudo lsmod | grep -e ashmem_linux -e binder_linux


Interesting.

For comparison, I'll note that I've had success installing/starting Anbox on Ubuntu 20.04.1 running on an Asus Q504UA laptop, which uses UEFI and runs an Intel Core i5-6200U @ 2.30GHz×4.

In contrast, if I recall correctly (it's been a long time since I tried), I couldn't start Anbox on an earlier version of Ubuntu (can't recall which version) running on a very old HP Pavilion dv7, which uses BIOS (not UEFI) and an AMD Turion processor.

I'm not sure what about the old HP system that Anbox didn't like (old Ubuntu? BIOS? old AMD? other?), but at least for me, Anbox is much happier on my newish Intel-based computer that uses UEFI.

**Regarding the missing liblxc.so.1 for Computer(B):**

>so I created a symbolic link.
>
>       sudo ln -s /usr/lib/x86_64-linux-gnu/liblxc.so.1.7.0 /snap/anbox/198/usr/lib/liblxc.so.1

I know *very little* about snapd.  But I do know that *isolation* is among the goals of Snap.  So, I wouldn't be surprised if snapd ignores (by design) the type of symbolic link that you've created.  But again, I know *very little* about snapd, so I could be entirely wrong about this. I'm be curious what others have to say about this.

**Regarding the following for Computer(A)**:

>      Install of "snap install --devmode --beta anbox": success

**QUESTION**:  Out of curiosity, were you able to start Anbox on **Computer(A)** after installing from the "beta" channel (but before attempting to upgrade to the "edge" channel)?

**Comment by GizmoChicken** [comment]
Here's some additional information:

**Installation of Anbox "beta" channel on Ubuntu 20.04.1 that had no previous Anbox installation**
On an installation of Ubuntu 20.04.1 that had no previous Anbox installation, I successfully installed and Anbox using:

```
sudo snap install --devmode --beta anbox
```

After rebooting and successfully starting Anbox, I found the following installed:

```
/snap/anbox/186/lib/liblxc.so.1
/snap/anbox/186/lib/liblxc.so.1.4.0
```

Note that:

1.  The above liblxc.so.1 links to the above liblxc.so.1.4.0, and 
2.  Aside from in the "/snap/anbox/186/lib/" directory, I can't find any other instance of liblxc.so.* anywhere else on my system (including in /usr/*).

**Installation of Anbox "edge" channel on Ubuntu 20.04.1 that had no previous Anbox installation**
On an installation of Ubuntu 20.04.1 that had no previous Anbox installation, I attempted (and failed) to install and Anbox using:

```
sudo snap install --devmode --edge anbox
```
I saw the following:

```
error: cannot perform the following tasks:
- Run install hook of "anbox" snap if present (run hook "install": 
-----
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
/snap/anbox/198/usr/bin/anbox: error while loading shared libraries: liblxc.so.1: cannot open shared object file: No such file or directory
-----)
```
Immediately after trying (and failing) to install Anbox from the "edge" channel, I tried again to install Anbox from the "edge" channel on the same system, and the installation failed again.

**Installation of Anbox "beta" channel on the system on which the Anbox "edge" channel failed to install**

Immediately after my second attempt (and failure) to install Anbox from the "edge" channel, on that same system, I tried installing Anbox from the "beta" channel again using:

```
sudo snap install --devmode --beta anbox
```

Success!  Anbox both installed and started.

As before, I found the following installed:

```
/snap/anbox/186/lib/liblxc.so.1
/snap/anbox/186/lib/liblxc.so.1.4.0

```
Note that, as before:

1.  The above liblxc.so.1 links to the above liblxc.so.1.4.0, and 
2.  Aside from in the "/snap/anbox/186/lib/" directory, I can't find any other instance of liblxc.so.* anywhere else on my system (including in /usr/*).

After the installation from the "beta" channel, I ran:
```
 snap info anbox
```
Which yielded:
```
name:      anbox
summary:   Android in a Box
publisher: morphis
store-url: https://snapcraft.io/anbox
contact:   https://anbox.io
license:   unset
description: |
  Runtime for Android applications which runs a full Android system
  in a container using Linux namespaces (user, ipc, net, mount) to
  separate the Android system fully from the host.
  
  You can find further details in our documentation at
  https://github.com/anbox/anbox/blob/master/README.md
commands:
  - anbox
  - anbox.android-settings
  - anbox.appmgr
  - anbox.collect-bug-info
  - anbox.shell
services:
  anbox.container-manager: simple, enabled, active
snap-id:      [redacted]
tracking:     latest/beta
refresh-date: today at 19:21 EDT
channels:
  latest/stable:    –                                    
  latest/candidate: –                                    
  latest/beta:      4-56c25f1     2020-01-02 (186) 391MB devmode
  latest/edge:      4+gitr5ab92ef 2020-08-20 (198) 406MB devmode
installed:          4-56c25f1                (186) 391MB devmode
```
Then, although I could not *install* from "edge" I checked whether I could upgrade (refresh) to the "edge" channel, using the following:

```
sudo snap refresh --edge --devmode anbox
```
After "refresh" to the edge channed, I again ran:
```
snap info anbox
```
Which yielded:
```
name:      anbox
summary:   Android in a Box
publisher: morphis
store-url: https://snapcraft.io/anbox
contact:   https://anbox.io
license:   unset
description: |
  Runtime for Android applications which runs a full Android system
  in a container using Linux namespaces (user, ipc, net, mount) to
  separate the Android system fully from the host.
  
  You can find further details in our documentation at
  https://github.com/anbox/anbox/blob/master/README.md
commands:
  - anbox
  - anbox.android-settings
  - anbox.appmgr
  - anbox.collect-bug-info
  - anbox.shell
services:
  anbox.container-manager: simple, enabled, active
snap-id:      [redacted]
tracking:     latest/edge
refresh-date: today at 19:39 EDT
channels:
  latest/stable:    –                                    
  latest/candidate: –                                    
  latest/beta:      4-56c25f1     2020-01-02 (186) 391MB devmode
  latest/edge:     4+gitr5ab92ef 2020-08-20 (198) 406MB devmode
installed:          4+gitr5ab92ef            (198) 406MB devmode
```
So, yep, I could upgrade (refresh) from the "beta" channel to the "edge" channel.  And once installed, it strated just fine.

Also, after upgrading to the Anbox "edge" channel, I found:

```
/snap/anbox/186/lib/liblxc.so.1
/snap/anbox/186/lib/liblxc.so.1.4.0

/snap/anbox/198/usr/lib/liblxc.so.1
/snap/anbox/198/usr/lib/liblxc.so.1.4.0
```
Note that:
1.  The liblxc.so.1 and liblxc.so.1.4.0 found in /snap/anbox/186/lib/ were installed when Anbox was installed from the "beta" channel.
2.  The liblxc.so.1 and liblxc.so.1.4.0 found in /snap/anbox/198/usr/lib/ were installed when Anbox was upgraded (refreshed) from the "beta" channel to the "edge" channel.
3.  Aside from in the /snap/anbox/186/lib/ and /snap/anbox/198/usr/lib/ directories, I can't find any other instance of liblxc.so.* anywhere else on my system (including in /usr/*).
