### ISSUE TITLE
Run install hook of "anbox" snap if present (run hook "install"

### ISSUE THREAD

**Issue by TERMINALCO** [anbox/anbox#1582]
HI, I tried to install Anbox through the beta channel and after downloading I got this:

error: cannot perform the following tasks:
- Run install hook of "anbox" snap if present (run hook "install": 
-----
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
The CPU of your computer (Intel(R) Core(TM)2 Duo CPU     E4600  @ 2.40GHz) does not support all
features Anbox requires.
It is missing support for the following features: SSE 4.1, SSE 4.2, SSSE 3
You can for example find more information about SSE
here https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions
-----)

Thank You in Advance

**Comment by necessarily-equal** [comment]
I'm not sure about the snap magic part, but this means you can't run Android (and so Anbox) on your CPU:

```
The CPU of your computer (Intel(R) Core(TM)2 Duo CPU E4600 @ 2.40GHz) does not support all features Anbox requires.
```

That means in your case, you would need emulation, or another CPU.
