### ISSUE TITLE
Cannot install DKMS modules on Manjaro 

### ISSUE THREAD

**Issue by yoshi-x** [anbox/anbox#1583]
Hi, I recently tried installing Anbox on my manjaro machine and came across this error when installing the DKMS modules. This was the log output:

  1 DKMS make.log for anbox-modules-binder-r1240.c1e7550 for kernel 5.8.0-2-MANJARO (x86_64)
  2 Mon 24 Aug 2020 01:02:02 AM EDT
  3 make -C /lib/modules/5.8.0-2-MANJARO/build V=0 M=$PWD
  4 make[1]: Entering directory '/usr/lib/modules/5.8.0-2-MANJARO/build'
  5   AR      /var/lib/dkms/anbox-modules-binder/r1240.c1e7550/build/built-in.a
  6   CC [M]  /var/lib/dkms/anbox-modules-binder/r1240.c1e7550/build/deps.o
  7   CC [M]  /var/lib/dkms/anbox-modules-binder/r1240.c1e7550/build/binder.o
  8 /var/lib/dkms/anbox-modules-binder/r1240.c1e7550/build/binder.c: In function ‘binder_update_page_range’:
  9 /var/lib/dkms/anbox-modules-binder/r1240.c1e7550/build/binder.c:633:19: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you
 10   633 |   down_write(&mm->mmap_sem);
 11       |                   ^~~~~~~~
 12       |                   mmap_base
 13 /var/lib/dkms/anbox-modules-binder/r1240.c1e7550/build/binder.c:683:17: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you
 14   683 |   up_write(&mm->mmap_sem);
 15       |                 ^~~~~~~~
 16       |                 mmap_base
 17 /var/lib/dkms/anbox-modules-binder/r1240.c1e7550/build/binder.c:710:17: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you
 18   710 |   up_write(&mm->mmap_sem);
 19       |                 ^~~~~~~~
 20       |                 mmap_base
 21 make[2]: *** [scripts/Makefile.build:280: /var/lib/dkms/anbox-modules-binder/r1240.c1e7550/build/binder.o] Error 1
 22 make[1]: *** [Makefile:1756: /var/lib/dkms/anbox-modules-binder/r1240.c1e7550/build] Error 2
 23 make[1]: Leaving directory '/usr/lib/modules/5.8.0-2-MANJARO/build'
 24 make: *** [Makefile:8: all] Error 2
~                                            
Thank you for any help

**Comment by jnnksdev** [comment]
Hi,

the kernel modules needed by anbox are part of the Linux Kernel since 5.3 afaik.
You do not need to install anything else if kernel version is >=5.3.

Could you paste the result of `find /lib/modules/$(uname -r) -type f -name '*.ko' | grep -E "ashmem|binder"`?
`find /lib/modules/$(uname -r) -type f -name '*.ko'` lists all kernel modules and filters them for ashmem and binder. 
Let's see, if you got them already.

**Comment by xX-Yoshi-Xx** [comment]
So, I just ran those commands and they both returned empty, which I'm assuming means I don't have them. I tried to compile the kernel with:

CONFIG_ASHMEM=y
CONFIG_ANDROID=y
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"

as per the Arch wiki. However, upon booting the kernel, a new error appeared during compilation, which was:   
1 DKMS make.log for anbox-modules-ashmem-r1240.c1e7550 for kernel 5.8.3-MANJARO (x86_64)
  2 Mon 24 Aug 2020 02:40:41 AM EDT
  3 make -C /lib/modules/5.8.3-MANJARO/build V=0 M=$PWD
  4 make[1]: Entering directory '/home/raleigh/build/linux-5.8.3'
  5   AR      /var/lib/dkms/anbox-modules-ashmem/r1240.c1e7550/build/built-in.a
  6   CC [M]  /var/lib/dkms/anbox-modules-ashmem/r1240.c1e7550/build/ashmem.o
  7   CC [M]  /var/lib/dkms/anbox-modules-ashmem/r1240.c1e7550/build/deps.o
  8   LD [M]  /var/lib/dkms/anbox-modules-ashmem/r1240.c1e7550/build/ashmem_linux.o
  9   MODPOST /var/lib/dkms/anbox-modules-ashmem/r1240.c1e7550/build/Module.symvers
 10 ERROR: modpost: "kallsyms_lookup_name" [/var/lib/dkms/anbox-modules-ashmem/r1240.c1e7550/build/ashmem_linux.ko] undefined!
 11 make[2]: *** [scripts/Makefile.modpost:111: /var/lib/dkms/anbox-modules-ashmem/r1240.c1e7550/build/Module.symvers] Error 1
 12 make[2]: *** Deleting file '/var/lib/dkms/anbox-modules-ashmem/r1240.c1e7550/build/Module.symvers'
 13 make[1]: *** [Makefile:1669: modules] Error 2
 14 make[1]: Leaving directory '/home/raleigh/build/linux-5.8.3'
 15 make: *** [Makefile:12: all] Error 2

I am currently compiling the kernel again with this reverted: https://github.com/torvalds/linux/commit/0bd476e6c67190b5eb7b6e105c8db8ff61103281#diff-2d25d71e9adc19c068350ae630bd4fd7
~                                                                                                                              
~                                                                                                                              
~                                                                                                                              
~                                                                                                                              
~                                                                                                                              
~

**Comment by GizmoChicken** [comment]
I can't be of much help regarding compiling a kernel for Manjaro/Arch.  (Maybe a Manjaro/Arch forum would be better for that?)  But I'm happy to provide some info from my Ubuntu 20.04 system (on which I can install and run Anbox) that may be of some help.

Here's the output after applying the suggested commands on my system:
```
$ find /lib/modules/$(uname -r) -type f -name '*.ko' | grep -E "ashmem|binder"?
/lib/modules/5.4.0-42-generic/kernel/drivers/android/binder_linux.ko
/lib/modules/5.4.0-42-generic/kernel/drivers/staging/android/ashmem_linux.ko
```
And here are some (maybe not all) relevant snippets from my `/boot/config-5.4.0-42-generic` file:
```
# Android
#
CONFIG_ANDROID=y
CONFIG_ANDROID_BINDER_IPC=m
CONFIG_ANDROID_BINDERFS=m
CONFIG_ANDROID_BINDER_DEVICES=""
# CONFIG_ANDROID_BINDER_IPC_SELFTEST is not set
# end of Android

# Android
#
CONFIG_ASHMEM=m
# CONFIG_ANDROID_VSOC is not set
# CONFIG_ION is not set
# end of Android
```

**Comment by jnnksdev** [comment]
@xX-Yoshi-Xx it seems like you are still trying to build the anbox specific modules:   
```
...
6 CC [M] /var/lib/dkms/anbox-modules-ashmem/r1240.c1e7550/build/ashmem.o
7 CC [M] /var/lib/dkms/anbox-modules-ashmem/r1240.c1e7550/build/deps.o
...
```
I think you're running into compatibility issues, as they are meant to be used with older kernels.
Could you remove all modules that have an `anbox-` prefix and try compiling again?

Note: please post log entries enclosed with three grave accents ``` in a separate line before and after the text.
Alternatively, select the text in the comment box and click on < > (insert code) in the menu bar.

**Comment by necessarily-equal** [comment]
If you build the modules in your kernel, you don't need the (now broken and unmaintaned) external modules. Skip that step
