### ISSUE TITLE
Cannot connect to dbus

### ISSUE THREAD

**Issue by JonasVautherin** [anbox/anbox#1589]
I managed to install Anbox on Ubuntu 20.04 (with SecureBoot enabled, thanks to @GizmoChicken). But I can't figure out how to start Anbox now. Whatever I run ends up on `Failed to connect to DBus`:

```
% sudo anbox launch  --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity                                          [1]
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
[ 2020-08-28 17:49:06] [daemon.cpp:61@Run] Failed to connect to DBus
```

How am I supposed to run Anbox?

**Comment by GizmoChicken** [comment]
While it's possible to start Anbox using the command line, I recommend using [system search](https://help.ubuntu.com/stable/ubuntu-help/gs-use-system-search.html.en) (or equivalent) to locate the icon for the Anbox Application Manager, and clicking on the icon.  Or at least that works for me.

**Comment by JonasVautherin** [comment]
I'm using i3wm, I don't have the system search there. I have `/root/snap/anbox`, though.

**Comment by GizmoChicken** [comment]
To start Anbox, I simply click the icon for the Anbox Application Manager, and so I'm not sure what terminal command is preferred.  I'd also appreciate input from others.

The above in mind, the following starts Anbox for me:
```
anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity 
```
Note that the above is what you tried, minus the "sudo" command.  Note also that I haven't tested Anbox thoroughly after starting using the above, but all seems to work as well as when started using the icon.

For another (possibly right, possibly wrong) approach, have a look toward the bottom of the page found [here](https://techpiezo.com/linux/install-anbox-in-ubuntu-20-04-lts/).

**Comment by JonasVautherin** [comment]
I tried their suggestions (install `dbus-x11` and `export $(dbus-launch)`), but it doesn't change anything. I already had `dbus-x11`, by the way.

What's weird to me is that I cannot run `anbox` without `sudo` at all, and all the instructions seem to do it. Though I think I install it like everybody, with `sudo snap install --devmode --beta anbox`...

**Comment by GizmoChicken** [comment]
Maybe not of much help, but I thought I'd mention here that I can start Anbox using the following terminal command:
```
anbox.appmgr
```
Again, for me, no need to use the `sudo` command for starting Anbox.

**Comment by JonasVautherin** [comment]
Thanks for the info! So it seems like my issue is that I can't run it without `sudo` :confused:.

**Comment by GizmoChicken** [comment]
Are you certain that the `binder` and `ashmem` modules loaded before you attempted to start Anbox?

You can confirm whether the `binder` and `ashmem` modules loaded using:
```
lsmod | grep -e ashmem_linux -e binder_linux
```
If one or both modules failed to load, try loading them using:
```
sudo modprobe ashmem_linux

sudo modprobe binder_linux
```
And then, try again to start Anbox using:
```
anbox.appmgr
```

**Comment by JonasVautherin** [comment]
The modules are loaded:

```
% lsmod | grep -e ashmem_linux -e binder_linux
ashmem_linux           20480  0
binder_linux          180224  0
```

I cannot run Anbox without `sudo`:

```
% anbox.appmgr
zsh: command not found: anbox.appmgr
```

I get the dbus issue with `sudo`:

```
% sudo anbox.appmgr
[sudo] password for jones: 
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
[ 2020-09-01 10:52:15] [daemon.cpp:61@Run] Failed to connect to DBus
```

**Comment by JonasVautherin** [comment]
Actually, I just realized that it gets installed in `/snap/bin`, which is not in my PATH. But I still get the dbus error:

```
% /snap/bin/anbox.appmgr
[ 2020-09-01 10:55:23] [daemon.cpp:61@Run] Failed to connect to DBus
```

**Comment by Fuseteam** [comment]
huh weird
