### ISSUE TITLE
Bug in snapcraft code.

### ISSUE THREAD

**Issue by vijahatali** [anbox/anbox#159]
Hello,

i m using anbox 0.1.0.

Oprating system is Ubanu 16.10

When i install the anbox and run command snapcraft i have seen this error.
"E:The repository 'http://ppa.launchpad.net/ubuntu-wine/ppa/ubuntu yakkety Release' does not have a Release file."

Please provide me solution.

Thanks & Regards
Vijahat Ali

**Comment by pizzadude** [comment]
That has nothing to do with Anbox.

**Comment by morphis** [comment]
@vijahatali you have a failing ppa (http://ppa.launchpad.net/ubuntu-wine/ppa/ubuntu) on your system which isn't something the anbox-installer put in place. As @pizzadude says, this isn't a bug.
