### ISSUE TITLE
current version of anbox?

### ISSUE THREAD

**Issue by Golddouble** [anbox/anbox#1591]
I have found in my package manager version 20190124-1 .
So I was interested, if this is really the latest version of anbox. To find out, what the current version of anbox is at the moment, I had a look at this site:
https://github.com/anbox/anbox

My expectation was, that I will find the version on this site. But I did.

So my question is:
Where did you hide the information about the current version.
Isn't this a important information, that we should find easily on 
https://github.com/anbox/anbox ?

Thank you.

**Comment by GizmoChicken** [comment]
The latest beta and edge versions of Anbox (which can be installed as snap packages) are listed here:
https://snapcraft.io/anbox

> I have found in my package manager version 20190124-1.

I'm not sure to what package you are referring.  But Anbox can be installed as a snap package using the following:
```
sudo snap install --devmode --beta anbox
```
If you installed Anbox as a snap package, you can determine:

1. the latest beta version, 
2. the latest edge version, and
3. the installed version,

using the following:
```
snap info anbox
```
To upgrade (refresh) to the latest beta version of Anbox, you can use:
```
sudo snap refresh --beta --devmode anbox
```

To upgrade (refresh) to the latest edge version of Anbox, you can use:
```
sudo snap refresh --edge --devmode anbox
```

**Comment by Golddouble** [comment]
But this would not work with systemd? Does it?
