### ISSUE TITLE
Update installer to run with new Kernel on Ubuntu (fix included)

### ISSUE THREAD

**Issue by DennisHeine** [anbox/anbox#1592]
self compiled binder module from anobox github repo can't be installed because it would overwrite the module which has been compiled into the kernel. this state won't allow anbox to run, as the module provided by kernel 5something+ does only use binderfs, but no /dev/binder

workaround:

mkdir /dev/binderfs
mount -t binder binder /dev/binderfs

mkdir /dev/binder
mount -t binder binder /dev/binder

either one of both, or both together did do the trick.

also, i updated the snap version to the latest beta.
afterwards, anbox ran on (x)ubuntu 20.04

thus, the installer should be updated to create the mountpoint(s) and one or more fstab entry(s) automatically.

**Comment by GizmoChicken** [comment]
>self compiled binder module from anobox github repo can't be installed because it would overwrite the module which has been compiled into the kernel. 

In my experience, the binder module (and ashmem module) included with the kernel that ships with Ubuntu 20.04 works without issue.

Please forgive me if I'm overlooking something important, but if I may ask:

Why would you prefer to use the (unmaintaned) external modules instead of using the binder and ashmem modules included with the kernel that ships with Ubuntu 20.04 (and flavors thereof)?  Are you experiencing any particular problems with the modules included with the kernel?

**Comment by DennisHeine** [comment]
Well - it does not :) Please read the issues, about 30% of them are problems with /dev/binder missing (even though the kernel module is loaded)
Several people have suggested changing to the kernel implemented version, but it is something that for some reason or another did not get changed.

**Comment by GizmoChicken** [comment]
> others have reported it with ubuntu

I suspect that many who attempt to install Anbox don't realize that the external modules are not needed when installing onto 20.04.  Have a look [here](https://github.com/anbox/anbox/issues/1581).

>Please read the issues, about 30% of them are problems with /dev/binder missing

According to the [installation page](https://github.com/anbox/anbox/blob/master/docs/install.md):
>In Ubuntu 19.10 the binder driver doesn't create /dev/binder when loaded. ***That is intentional.*** Instead it provides support for binderfs

Emphasis added. The above is also true for 20.04.  Have a look [here](https://github.com/anbox/anbox/issues/1569).

**Comment by DennisHeine** [comment]
> > others have reported it with ubuntu
> 
> I suspect that many who attempt to install Anbox don't realize that the external modules are not needed when installing onto 20.04. Have a look [here](https://github.com/anbox/anbox/issues/1581).
it does not start! there will be an error message that clearly says that /dev/binder is missing. and it is missing, unless you create it. i have tested it.

> > Please read the issues, about 30% of them are problems with /dev/binder missing
> 
> According to the [installation page](https://github.com/anbox/anbox/blob/master/docs/install.md):
> 
> > In Ubuntu 19.10 the binder driver doesn't create /dev/binder when loaded. _**That is intentional.**_ Instead it provides support for binderfs
that's simply wrong.

> Emphasis added. The above is also true for 20.04. Have a look [here](https://github.com/anbox/anbox/issues/1569).

**Comment by GizmoChicken** [comment]
Works for me.  Good luck.

**Comment by DennisHeine** [comment]
Thanks :)
Two more with eventually the same problem:

https://github.com/anbox/anbox/issues/1431
https://github.com/anbox/anbox/issues/1421

**Comment by ramma1** [comment]
Hi, i just got Ubuntu about a day ago just to run Anbox. Anbox for me also stuck on starting so I'm assuming that i have the same issue which this solution is trying to address. I have no idea how to implement the solution. I have used the following command to install anbox. $ sudo snap install --devmode --beta anbox
after using the first command you mentioned, i get this: $ mkdir /dev/binderfs
mkdir: cannot create directory ‘/dev/binderfs’: File exists
second command gives me: mount -t binder binder /dev/binderfs
mount: only root can use "--types" option
sudo mount -t binder binder /dev/binderfs gives me nothing
3rd one gives me: mkdir /dev/binder
mkdir: cannot create directory ‘/dev/binder’: File exists
4th one: mount -t binder binder /dev/binder
mount: only root can use "--types" option

How can I fix this?
Thanks

**Comment by GizmoChicken** [comment]
@ramma1 

I imagine that @DennisHeine is better equipped to answer your questions related to `mkdir`, so I'll leave those to him.

But in the meantime, if I may ask:

1.  Are you attempting to install Anbox on Ubuntu 20.04?  (Installing on older Ubuntu versions may require additional steps.)

2.  After installing Anbox, did try `lsmod | grep -e ashmem_linux -e binder_linux` to confirm whether the `ashmem` and `binder` modules loaded?

3.  And if the `ashmem` and/or `binder` modules failed to load, did you attempt to manually load them using `sudo modprobe ashmem_linux` and/or `sudo modprobe binder_linux`?  (After attempting to manually load them, again try `lsmod | grep -e ashmem_linux -e binder_linux` to confirm whether they loaded.)

**Comment by ramma1** [comment]
Hi, 
1)my kernel is:
uname -r
5.4.0-42-generic
2) I am unable to tell of they are loaded or not so:
lsmod | grep -e ashmem_linux -e binder_linux
binder_linux          180224  0
3)
sudo modprobe ashmem_linux
modprobe: ERROR: could not insert 'ashmem_linux': Operation not permitted

and nothing happens when i paste: sudo modprobe binder_linux
This is after running these 2 commands:
lsmod | grep -e ashmem_linux -e binder_linux
binder_linux          180224  0
Hope this helps in you helping me

**Comment by GizmoChicken** [comment]
```
lsmod | grep -e ashmem_linux -e binder_linux
binder_linux 180224 0
```
The above indicates that `binder` successfully loaded, but that that `ashmem` did _not_ load.  If _both_ had loaded, you would have seen something like this:
```
lsmod | grep -e ashmem_linux -e binder_linux
ashmem_linux          [number]   0
binder_linux          [number]   0
```
Regarding the following:
```
sudo modprobe ashmem_linux
modprobe: ERROR: could not insert 'ashmem_linux': Operation not permitted
```
Among other possible causes for the above error, that error can be seen when Secure Boot is enabled and `ashmem` has _not_ been signed.

I'm curious: do you have **Secure Boot** enabled?  If so, then:
1.  disable Secure Boot, 
2.  reboot your system, 
3.  try again to load `ashmem` and `binder` using (a) `sudo modprobe ashmem_linux` and (b) `sudo modprobe binder_linux`,
4.  check again whether both `ashmem` and `binder` loaded using `lsmod | grep -e ashmem_linux -e binder_linux`, and
5. try again to start Anbox.

If Anbox still doesn't work, sorry, but I can't help.  :)

NOTE:  Provided disabling Secure Boot solved the problem, if wanting to run Anbox on Ubuntu 20.04 with Secure Boot enabled (which is possible on my system), you can try using “kmodsign” for the “ashmem” module, as described [here](https://github.com/anbox/anbox/issues/1570).
