### ISSUE TITLE
Where is anbox folder?

### ISSUE THREAD

**Issue by Mistero5050** [anbox/anbox#160]
Please see this https://askubuntu.com/questions/903977/how-do-i-add-a-shared-folder-in-anbox

**Comment by morphis** [comment]
There is no shared folder with the Android container yet. We will implement support for a [Document Provider](https://developer.android.com/reference/android/provider/DocumentsProvider.html) in the future which will allow you to access certain parts of your host file system.

**Comment by Mistero5050** [comment]
OK, thanks

**Comment by furqon** [comment]
im looking also for this answer, is there any folder in OS that is mounted so that can be accessed from anbox?
