### ISSUE TITLE
Shared Anbox

### ISSUE THREAD

**Issue by Ammarulhaq** [anbox/anbox#1601]
Hello Sir, I've anbox installed on one computer and developing android code on other machines.Now i want to share anbox as emulator among these machines.How can i scale anbox (instance) to run for every machines separately?

**Comment by jnnksdev** [comment]
Anbox is not meant to be used as a development or debugging tool for Android applications. It does support app installation via [Android debug Bridge}(https://developer.android.com/studio/command-line/adb) but you will probably be happier with official tools from Google.

If you really want to use Anbox, maybe this is the right thing for you: https://github.com/aind-containers/aind. Aind uses Anbox, inside a Docker container. You could use that for individual instances for each development client.

**Comment by Ammarulhaq** [comment]
Thanks for the assistance. Yes this Image is useful but it wrapped VNC around anbox.But hope i will make this image up according to my needs.
