### ISSUE TITLE
New Anbox Interface Support

### ISSUE THREAD

**Issue by bin-souei** [anbox/anbox#1605]
It's not a bug but a suggestion, is it in any way possible to make a search function for the Anbox Catalog for Apps, and make it a list type instead of grids? Since it's a desktop Interface I just thought that it would be a better UI in the way that I envision.

**Comment by jnnksdev** [comment]
Well technically the Anbox Application Manager is an Android App running inside the container :)

I'm not sure how well the app integration is handled in various distros, but Ubuntu lists all the installed apps in the system application menu.
