### ISSUE TITLE
Ejecutar App android desde linux en forma directa

### ISSUE THREAD

**Issue by emobilia** [anbox/anbox#1607]
Buenas tardes,  me disculpo por mi ignorancia,  mire el proyecto y fue de mi agrado, observé que al ser una caja cerrada, no podía instalar un acceso directo de la aplicación a mo escritorio,  o al dock mismo, no hablamos de Anbox, pero si de X Android app, por lo que me llevo a pensar, si se pudiese en forma remota y a través de un clic, ejecutar esa app, de la misma forma que se realiza cuando uno ejecuta una app a través de team viewer, a modo de ejemplo,  en este caso, anbox, tiene salida a la red.
La pregunta es, se podrá crear un acceso directo en el escritorio a cada una de las app instaladas y al hacer doble clic, esta llama vía web a la instalada, ejecutándose en la misma pc?, con respecto al icono del acceso para identificar, tengo una idea también,  pero es menos compleja de resolver.
Espero haber sido claro con mi idea y haberla transmitido correctamente. 
"Un acceso directo vía web a X app Android de Anbox y esta se ejecute en el entorno "
Gracias.  Saludos cordiales

**Comment by morphis** [comment]
As most people are speaking English it would be great if you can reopen your issue in that language. Thanks!
