### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by jeffroz20034** [anbox/anbox#1609]
u.1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**

Hi my anbox install has no internet win the rest of my computer  does and I can find anyone else with that same problem  online please help thank
**What were you expecting?:**
Help get it work right please 

**Additional info:**
I dont no

**Comment by kevinp2000** [comment]
Try downloading and running [anbox-bridge.sh](https://raw.githubusercontent.com/anbox/anbox/master/scripts/anbox-bridge.sh). It should setup the anbox0 network interface, which Anbox uses. The script needs to be rerun after your computer restarts in order to set the interface back up.
