### ISSUE TITLE
Anbox isn't working on ubuntu 20.04

### ISSUE THREAD

**Issue by mehak1404** [anbox/anbox#1610]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[sudo /snap/bin/anbox.collect-bug-info ]
```
</details>

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by jnnksdev** [comment]
Please provide more information about your problem.

**Comment by J-Cake** [comment]
The PPA doesn't work anyway - I'm on 20.04 as well and can't find the repository

**Comment by jnnksdev** [comment]
Which PPA? 

We use snap to distribute the software. It's even included in the issue template.

**Comment by J-Cake** [comment]
Yes, that's my point. The repository I'm talking about is this one: ppa:morphis/anbox-support. I get 404s and then a complete failure.

**Comment by jnnksdev** [comment]
You do not need that repo as your Kernel already has the necessary modules. I am working on an updated version for the documentation.

In the meantime you can use:
```
# modprobe ashmem_linux binder_linux
# mkdir /dev/binderfs
# mount -t binder binder /dev/binderfs  
```
to enable them and mount `binderfs`.

**Comment by J-Cake** [comment]
Hmm, that hasn't done anything:

```
modprobe: ERROR: could not insert 'ashmem_linux': Operation not permitted
```
*directory created*
```
mount: /dev/binderfs: unknown filesystem type 'binder'.
```

Each command's output

**Comment by jnnksdev** [comment]
Oh, excuse me, you need `sudo`, like so:
```
sudo modprobe ashmem_linux binder_linux
sudo mkdir /dev/binderfs (you can leave this one, since the directory exists already)
sudo mount -t binder binder /dev/binderfs
```
In shell script snippets the `#` indicates necessary elevation, while the `$` is a normal command.

**Comment by J-Cake** [comment]
Hmm, still nothing...

**Comment by suyashmahar** [comment]
I'm also on 20.04 and creating a binderfs directory doesn't work for me either.
```
ls -lah /dev/binderfs /dev/ashmem
crw------- 1 root root 10, 37 Sep 21 10:48 /dev/ashmem

/dev/binderfs:
total 0
drwxr-xr-x  2 root root      0 Sep 21 10:49 .
drwxr-xr-x 23 root root   5.1K Sep 21 10:48 ..
crw-------  1 root root 234, 1 Sep 21 10:49 binder-control
```

**Comment by suyashmahar** [comment]
@jnnksdev maybe you meant `/dev/binder` instead of `/dev/binderfs`? If I do that, I get hit with another error:
```
$ anbox session-manager  
[ 2020-09-21 06:04:22] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to create node for device /dev/binder: Operation not permitted
[ 2020-09-21 06:04:22] [session_manager.cpp:148@operator()] Lost connection to container manager, terminating.
[ 2020-09-21 06:04:23] [daemon.cpp:61@Run] Container is not runnin
```
Though the container service seems to be running:
```
$ systemctl status anbox-container-manager.service
● anbox-container-manager.service - Anbox Container Manager
     Loaded: loaded (/lib/systemd/system/anbox-container-manager.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2020-09-21 11:29:12 IST; 7min ago
       Docs: man:anbox(1)
    Process: 1015 ExecStartPre=/sbin/modprobe ashmem_linux (code=exited, status=0/SUCCESS)
    Process: 1059 ExecStartPre=/sbin/modprobe binder_linux (code=exited, status=0/SUCCESS)
    Process: 1068 ExecStartPre=/usr/share/anbox/anbox-bridge.sh start (code=exited, status=0/SUCCESS)
   Main PID: 1168 (anbox)
      Tasks: 9 (limit: 18813)
     Memory: 12.8M
     CGroup: /system.slice/anbox-container-manager.service
             └─1168 /usr/bin/anbox container-manager --daemon --privileged --data-path=/var/lib/anbox

Sep 21 11:29:12 m systemd[1]: Starting Anbox Container Manager...
Sep 21 11:29:12 m systemd[1]: Started Anbox Container Manager.
```

I also had to manually  download and copy the android.img to /var/lib/anbox

**Comment by J-Cake** [comment]
@suyashmahar Did you run that under Sudo? I believe @jnnksdev was saying that that's almost a necessity 🤷

**Comment by suyashmahar** [comment]
Commands for /dev/binderfs? Yes

**Comment by J-Cake** [comment]
So to clarify, you ran with root?

**Comment by suyashmahar** [comment]
Yes

**Comment by jnnksdev** [comment]
I just checked on a fresh Ubuntu 20.04 VM.
You do not need to manually mount `binderfs` if you install Anbox via snap. It is required when compiling from source. Nevertheless mounting it should not break anything.

@J-Cake do you have Secure Boot enabled by chance? You can check witch `sudo mokutil --sb-state`. If so, please check out the solution suggested in the [installation guide](https://github.com/anbox/anbox/blob/master/docs/install.md#on-ubuntu-1904-and-later).

**Comment by J-Cake** [comment]
I have secure boot enabled and am hoping a method exists where I don't have to change this as I'm not entirely comfortable messing with the low level system concerning booting and operating systems

**Comment by suyashmahar** [comment]
@jnnksdev I'm using snap and have secure boot disabled. Maybe I messed something up earlier on my Ubuntu install? I'll try in a VM and see if it works. Though, I have seen couple of threads with the same problem with binderfs, I believe something has changed since kernel v5 and now the binder device is not automatically created.

https://github.com/anbox/anbox/issues/1118#issuecomment-508015685

**Comment by J-Cake** [comment]
An interesting point, I vaguely remember reading somewhere that the new kernel update brings major changes to certain modules, maybe that has something to do with it?

**Comment by suyashmahar** [comment]
Update on the situation: Seems like I had multiple versions of anbox installed, both snap and from apt. Running `snap run anbox session-manager` to force run snap version fixed the issue. Thanks @jnnksdev for all the help and sorry for the confusion.

**Comment by jnnksdev** [comment]
@suyashmahar I was wondering, because Anbox should not be registered as a system service.
```
...
CGroup: /system.slice/anbox-container-manager.service
             └─1168 /usr/bin/anbox container-manager --daemon --privileged --data-path=/var/lib/anbox
...
```
It even points to a non snap executable. It should at least be `/snap/bin/anbox`. To further debug you could find out, wether container-manager and session-manager are actually the same `anbox` executable. Maybe one is snap, the other is not and they cannot communicate.

**Comment by jnnksdev** [comment]
@J-Cake well the easiest solution would be to disable secure boot.
Anbox is a complex piece of software by nature. We are working on improvements for the end user, but some form of complexity will remain for now.

**Comment by J-Cake** [comment]
Understood, I might try a virtual machine or a spare PC first and let you know how I go

**Comment by J-Cake** [comment]
So so far I haven't had much luck; my VM was too low-spec to work at all and my spare laptop also had secure boot issues. I'm honestly not familiar enough with Linux and their respective systems yet to debug this on my own, so if you have any other suggestions, that'd be fantastic

Jake

**Comment by jnnksdev** [comment]
You can turn off secure boot in your laptops BIOS. Maybe give this a try with the spare device.

**Comment by luciodeco** [comment]
I have just installed (through snap) Anbox on an Asus laptop running ubuntu 20.04 and it doesn't work.
It opens a window, says it's starting and after a minute or two the window closes and that' s all.

**Comment by jnnksdev** [comment]
@luciodeco please open another ticket with more details. A minute or two is too long for a kernel module failure and I suspect something else.

**Comment by J-Cake** [comment]
I've just gone through some thorough analysis and have confirmed secure boot is **not** the issue - It persists.

**Comment by succeedmr123** [comment]
Definitely confirming the issue on Ubuntu 20.04.2 LTS

**Comment by succeedmr123** [comment]
> I just checked on a fresh Ubuntu 20.04 VM.
> You do not need to manually mount `binderfs` if you install Anbox via snap. It is required when compiling from source. Nevertheless mounting it should not break anything.
> 
> @J-Cake do you have Secure Boot enabled by chance? You can check witch `sudo mokutil --sb-state`. If so, please check out the solution suggested in the [installation guide](https://github.com/anbox/anbox/blob/master/docs/install.md#on-ubuntu-1904-and-later).
> 
> @suyashmahar
> 
> > I also had to manually download and copy the android.img to /var/lib/anbox
> 
> That should be done by snap on install. If you're not using snap I would suggest to open a separate ticket.

Confirming unrelated to any Secure boot issue

OS I am trying to run has ashmem activated under dev

binderfs is mounted manually after leaning to differentiate and try all that is it  binder kernel 5.8 issue / does it need to be mounted, or DKMS compiled y/n / vs buinderfs game in the scattered documentation between three sources (it's pretty unnecessary and confusing to keep outdated docs online under the main webpage while the users are sifting through that while trying to make the system work at all, I have to confess)

Anyway, it runs for 6 sec with opened window with logo only and it shuts down without any error message

Yes snap edge installation

Ubuntu 20.04.2, kernel supported etc.

for those interested, got all the logs, ,precise versions and am willing to experiment more than 3 screens of cmdline logs I can copy paste + zips of anbox diag data

Best,

**Comment by andregans** [comment]
How to fix sign in don't have connection Google Playstore ?

**Comment by stanleygarland** [comment]
> You do not need that repo as your Kernel already has the necessary modules. I am working on an updated version for the documentation.
> 
> In the meantime you can use:
> 
> ```
> # modprobe ashmem_linux binder_linux
> # mkdir /dev/binderfs
> ```
> 
> to enable them and mount `binderfs`.

It will not let me > # mount -t binder binder /dev/binderfs  as it says that can only be done at root.

**Comment by stanleygarland** [comment]
Here is what I get when I run 

$ anbox session-manager
[ 2021-08-30 16:53:59] [daemon.cpp:61@Run] Software rendering is enabled, but SwiftShader library directory is not found.

**Comment by Fuseteam** [comment]
@stanleygarland disable software rendering
