### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by Innomenatus** [anbox/anbox#1616]
make[2]: *** No rule to make target 'gmock/lib/libgmock.a', needed by 'tests/anbox/android/intent_tests'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:2215: tests/anbox/android/CMakeFiles/intent_tests.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by jnnksdev** [comment]
On some distros you need to install `libgmock-dev`.
I would highly recommend to use the provided Docker container to build Anbox. You can start a build with `scripts/build-with-docker.sh`. Be aware that the script will hard reset your git tree (for now, change is on the way).

**Comment by Innomenatus** [comment]
I installed libgmock-dev already. How do you start a build with scripts/build-with-docker.sh? I'm new here.

**Comment by jnnksdev** [comment]
When you clone the repository there is a folder called `scripts`. In this folder you will find a shell script called `build-with-docker.sh` that builds and starts a docker container. Anbox will be compiled inside the container where all dependencies are present without having to install anything.

You need to be in the root folder of the repository and execute `scripts/build-with-docker.sh` in a shell window.

May I ask why you want to compile the code?

**Comment by necessarily-equal** [comment]
This might help https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/testing/anbox/fix-gtest-use.patch though it doesn't seem to touch the same part of the code.
