### ISSUE TITLE
Allow building without systemd

### ISSUE THREAD

**Issue by xbjfk** [anbox/anbox#1621]
**Please describe your problem:**
anbox requires systemd to build

**What were you expecting?:**
builds successfully without systemd

Is there any way to build without systemd? Thanks in advance.

**Comment by jnnksdev** [comment]
As far as I can see, [`sdbus-cpp`](https://github.com/Kistler-Group/sdbus-cpp) needs systemd. You might want to ask there.

Alternatively you can use the provided [docker image](https://github.com/anbox/anbox/blob/master/Dockerfile) with `scripts/build-with-docker.sh`

**Comment by xbjfk** [comment]
Ok thanks, I will open an issue there :)

**Comment by Niek** [comment]
It's possible to build sdbus-cpp with `-DBUILD_LIBSYSTEMD:BOOL=ON`, but it requires some additional steps:
* Remove libsystemd from `CMakeLists.txt`
* Install mason/ninja-build/gperf tools
* Set the systemd include and library path to the systemd included in sdbus-cpp
