### ISSUE TITLE
Missing installation files.

### ISSUE THREAD

**Issue by robert-pearson** [anbox/anbox#1623]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**
when I try to do the installation I get the following error messages 

Err:15 https://dl.bintray.com/resin-io/debian stable Release                   
  404  Not Found [IP: 35.161.162.245 443]

E: The repository 'https://dl.bintray.com/resin-io/debian stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

E: The repository 'https://dl.bintray.com/resin-io/debian stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Can't load /var/lib/shim-signed/mok/.rnd into RNG
140214989283328:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/var/lib/shim-signed/mok/.rnd
Generating a RSA private key

It is a C-ite tradition to leave at least one file out of each distribution.
In addition: to file a bug report you ask me to take certain steps without actually telling me HOW to do it.
i.e. Please paste the result of `anbox system-info` below:
**What were you expecting?:**
All the files to actually be in the distribution.

**Additional info:**

**Comment by jnnksdev** [comment]
I think you have the wrong repo.

**Comment by robert-pearson** [comment]
Stale means no one is actually willing to do anything about bugs.
