### ISSUE TITLE
[bug] openSUSE 15.1 [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name org.anbox was not provided by any .service files

### ISSUE THREAD

**Issue by sakunix** [anbox/anbox#1625]
saku@openSUSE:~> env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/anbox_appmgr.desktop /snap/bin/anbox.appmgr %U
[ 2020-09-30 06:53:57] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name org.anbox was not provided by any .service files
saku@openSUSE:~>

NOTE: that is the command that has installed the icon of the menu that I install snap

**Comment by necessarily-equal** [comment]
can you try to open the session-manager manually and report on the result? `anbox session-manager`

**Comment by Chen-Hongji** [comment]
I had the same problem in arm64. 
> [org.freedesktop.DBus.Error.ServiceUnknown] The name org.anbox was not provided by any .service files

I run `anbox session-manager` and I get
> [ 2021-01-15 06:27:08] [daemon.cpp:61@Run] No runtime directory specified

this is` anbox system-info`:
> version: local-165db5c
> cpu:
>   arch:
>   brand:
>   features:
> os:
>   name: Ubuntu
>   version: 20.04.1 LTS (Focal Fossa)
>   snap-based: false
> kernel:
>   version: Linux version 5.4.0-60-generic (buildd@bos02-arm64-031) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #67-Ubuntu SMP Tue Jan 5 18:24:57 UTC 2021
>   binder: true
>   ashmem: true
> graphics:
>   egl:
>     vendor: Mesa Project
>     version: 1.4
>     extensions:
>       - EGL_ANDROID_blob_cache
>       - EGL_EXT_buffer_age
>       - EGL_KHR_cl_event2
>       - EGL_KHR_config_attribs
>       - EGL_KHR_create_context
>       - EGL_KHR_create_context_no_error
>       - EGL_KHR_fence_sync
>       - EGL_KHR_get_all_proc_addresses
>       - EGL_KHR_gl_colorspace
>       - EGL_KHR_gl_renderbuffer_image
>       - EGL_KHR_gl_texture_2D_image
>       - EGL_KHR_gl_texture_3D_image
>       - EGL_KHR_gl_texture_cubemap_image
>       - EGL_KHR_image
>       - EGL_KHR_image_base
>       - EGL_KHR_image_pixmap
>       - EGL_KHR_no_config_context
>       - EGL_KHR_reusable_sync
>       - EGL_KHR_surfaceless_context
>       - EGL_EXT_pixel_format_float
>       - EGL_KHR_wait_sync
>       - EGL_MESA_configless_context
>       - EGL_MESA_image_dma_buf_export
>       - EGL_MESA_query_driver
>   gles2:
>     vendor: n/a
>     vendor: n/a
>     extensions: []

**Comment by MrRafsan** [comment]
i get this whin i run this:
~$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[ 2021-02-15 10:50:59] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name org.anbox was not provided by any .service files
this is anbox system-info:
version: 0.0~git20210106-1-Debian
cpu:
  arch:  x86
  brand:       Intel(R) Celeron(R) CPU  N2806  @ 1.60GHz
  features: 
    - sse4_1
    - sse4_2
os:
  name: Kali GNU/Linux
  version: 2020.4
  snap-based: false
kernel:
  version: Linux version 5.9.0-kali5-amd64 (devel@kali.org) (gcc-10 (Debian 10.2.1-1) 10.2.1 20201207, GNU ld (GNU Binutils for Debian) 2.35.1) #1 SMP Debian 5.9.15-1kali1 (2020-12-18)
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_EXT_swap_buffers_with_damage
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_swap_buffers_with_damage
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.0 Mesa 20.2.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_rgtc
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_texture_3D
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
      - GL_EXT_draw_instanced
      - GL_EXT_texture_sRGB_decode
      - GL_OES_EGL_image
      - GL_OES_depth_texture
      - GL_OES_packed_depth_stencil
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_NV_conditional_render
      - GL_OES_get_program_binary
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_EXT_frag_depth
      - GL_NV_fbo_color_attachments
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_robustness
      - GL_EXT_texture_rg
      - GL_EXT_unpack_subimage
      - GL_NV_draw_buffers
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_EXT_draw_buffers
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_KHR_robustness
      - GL_NV_pixel_buffer_object
      - GL_OES_depth_texture_cube_map
      - GL_OES_required_internalformat
      - GL_OES_surfaceless_context
      - GL_EXT_color_buffer_float
      - GL_EXT_sRGB_write_control
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_group_vote
      - GL_EXT_shader_integer_mix
      - GL_INTEL_performance_query
      - GL_EXT_base_instance
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_texture_border_clamp
      - GL_KHR_blend_equation_advanced
      - GL_KHR_context_flush_control
      - GL_KHR_robust_buffer_access_behavior
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_multisample_interpolation
      - GL_OES_texture_border_clamp
      - GL_EXT_blend_func_extended
      - GL_EXT_float_blend
      - GL_KHR_no_error
      - GL_OES_EGL_image_external_essl3
      - GL_EXT_clip_cull_distance
      - GL_EXT_disjoint_timer_query
      - GL_EXT_texture_compression_s3tc_srgb
      - GL_MESA_shader_integer_functions
      - GL_EXT_clip_control
      - GL_EXT_texture_compression_bptc
      - GL_KHR_parallel_shader_compile
      - GL_EXT_EGL_image_storage
      - GL_EXT_shader_framebuffer_fetch_non_coherent
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_texture_shadow_lod
      - GL_INTEL_blackhole_render
      - GL_MESA_framebuffer_flip_y
      - GL_EXT_demote_to_helper_invocation
      - GL_EXT_depth_clamp
      - GL_EXT_texture_query_lod

**Comment by atom7890** [comment]
same problem
 
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
VMware: No 3D enabled (0, Success).
version: local-ad377ff
snap-revision: 213
cpu:
  arch:  x86
  brand: AMD Ryzen 5 3600 6-Core Processor              
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
os:
  name: Kali GNU/Linux
  version: 2021.2
  snap-based: true
kernel:
  version: Linux version 5.10.0-kali3-amd64 (devel@kali.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.1) #1 SMP Debian 5.10.13-1kali1 (2021-02-08)
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

**Comment by harshetmaruff** [comment]
I have that same problem in my computer linux mint 

anbox system-info output:

version: local-ad377ff
snap-revision: 213
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i5 CPU         650  @ 3.20GHz
  features: 
    - aes
os:
  name: Linux Mint
  version: 20.2 (Uma)
  snap-based: true
kernel:
  version: Linux version 5.4.0-74-generic (buildd@lgw01-amd64-038) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

The problem is that the .service are not included while downloaded through snap, how do i get it
installed 

when i tried to run this command which could start the service

sudo systemctl start anbox-container-manager.service

it says :
ailed to start anbox-container-manager.service: Unit anbox-container-manager.service not found.

**Comment by harshetmaruff** [comment]
I have tried this command in the terminal 
sudo systemctl start snap.anbox.container-manager.service

and then i launch it through anbox.appmgr but now it gives different error 
 2021-07-22 21:58:30] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.Timeout] Connection timed out

**Comment by harshetmaruff** [comment]
II 

- [ ]

**Comment by Kushagra-Srivastava** [comment]
can't we move .service files from snap/anbox to org.anbox
