### ISSUE TITLE
Anbox is not working - Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by luciodeco** [anbox/anbox#1626]
@luciodeco please open another ticket with more details. A minute or two is too long for a kernel module failure and I suspect something else.

_Originally posted by @jnnksdev in https://github.com/anbox/anbox/issues/1610#issuecomment-702774922_

**Comment by luciodeco** [comment]
@jnnksdev please tell me what other details can I mention here to help

**Comment by jnnksdev** [comment]
The output of `anbox system-info` would be interesting. We've had issues with devices too old to support LXC virtualization.

**Comment by luciodeco** [comment]
Thank you for your answer.
Here is the output of anbox system-info

version: 0.0~git20191115-1build1-Ubuntu
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 20.04.1 LTS (Focal Fossa)
  snap-based: false
kernel:
  version: Linux version 5.4.0-49-generic (buildd@lgw01-amd64-038) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) #53-Ubuntu SMP Fri Sep 18 09:54:57 UTC 2020
  binder: false
  ashmem: false
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel
    vendor: OpenGL ES 3.2 Mesa 20.0.8
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_rgtc
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_texture_3D
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
      - GL_EXT_texture_sRGB_decode
      - GL_OES_EGL_image
      - GL_OES_depth_texture
      - GL_AMD_performance_monitor
      - GL_OES_packed_depth_stencil
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_NV_conditional_render
      - GL_OES_get_program_binary
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_EXT_frag_depth
      - GL_NV_fbo_color_attachments
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_OES_viewport_array
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_robustness
      - GL_EXT_texture_rg
      - GL_EXT_unpack_subimage
      - GL_NV_draw_buffers
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_EXT_draw_buffers
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_OES_depth_texture_cube_map
      - GL_OES_required_internalformat
      - GL_OES_surfaceless_context
      - GL_EXT_color_buffer_float
      - GL_EXT_sRGB_write_control
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_framebuffer_fetch
      - GL_EXT_shader_implicit_conversions
      - GL_EXT_shader_integer_mix
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_INTEL_conservative_rasterization
      - GL_INTEL_performance_query
      - GL_ANDROID_extension_pack_es31a
      - GL_EXT_base_instance
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_gpu_shader5
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_render_snorm
      - GL_EXT_shader_io_blocks
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_norm16
      - GL_EXT_texture_view
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_KHR_context_flush_control
      - GL_KHR_robust_buffer_access_behavior
      - GL_NV_image_formats
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_gpu_shader5
      - GL_OES_primitive_bounding_box
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_texture_view
      - GL_EXT_blend_func_extended
      - GL_EXT_buffer_storage
      - GL_EXT_float_blend
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_shader_samples_identical
      - GL_KHR_no_error
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_NV_fragment_shader_interlock
      - GL_OES_EGL_image_external_essl3
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_shader_image_atomic
      - GL_EXT_clip_cull_distance
      - GL_EXT_disjoint_timer_query
      - GL_EXT_texture_compression_s3tc_srgb
      - GL_MESA_shader_integer_functions
      - GL_EXT_clip_control
      - GL_EXT_texture_compression_bptc
      - GL_KHR_parallel_shader_compile
      - GL_EXT_EGL_image_storage
      - GL_EXT_shader_framebuffer_fetch_non_coherent
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_texture_shadow_lod
      - GL_MESA_framebuffer_flip_y
      - GL_NV_compute_shader_derivatives
      - GL_EXT_demote_to_helper_invocation
      - GL_EXT_depth_clamp
      - GL_EXT_texture_query_lod

**Comment by luciodeco** [comment]
I run anbox check-features
and this is the output:
Your computer does meet all requirements to run Anbox

**Comment by davidbaumann** [comment]
Seems to be a general problem: https://bugs.launchpad.net/ubuntu/+source/anbox/+bug/1884810

**Comment by davidbaumann** [comment]
```
he anbox-installer is deprecated. Please find updated installation
instructions here https://github.com/anbox/anbox/blob/master/docs/install.md

For any further questions please ask on the #anbox IRC channel on the
FreeNode network or in the Anbox telegram group (https://t.me/anbox).

```
Actually you can install the beta now, it worked on my Ubuntu 20.04. Just read the installation instructions: https://github.com/anbox/anbox/blob/master/docs/install.md#verify-that-kernel-modules-are-loaded

**Comment by vrichomme** [comment]
It's really complicated to make it work when building from sources and not using snap.
I have followed the documentation and now I am stuck, I am lauching the anbox like this:

anbox.sh
----------

f [ ! -d "/dev/binderfs" ] ; then
  sudo modprobe ashmem_linux
  sudo modprobe binder_linux

  sudo mkdir /dev/binderfs
  sudo mount -t binder binder /dev/binderfs
fi

sudo anbox container-manager \
    --daemon \
    --android-image=/home/vincent/Projects/android-images/android_amd64.img \
    --data-path=/home/vincent/anbox-data

and after that what am I supposed to do ? The documentation does not tell...

`
vincent@ubuntu:~/Projects$ losetup
NAME        SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                                               DIO LOG-SEC
/dev/loop1          0      0         1  1 /var/lib/snapd/snaps/core_10185.snap                      0     512
/dev/loop8          0      0         1  1 /var/lib/snapd/snaps/snapd_8542.snap                      0     512
/dev/loop6          0      0         1  1 /var/lib/snapd/snaps/snap-store_467.snap                  0     512
/dev/loop4          0      0         1  1 /var/lib/snapd/snaps/core18_1880.snap                     0     512
/dev/loop11         0      0         0  1 /home/vincent/Projects/android-images/android_amd64.img   0     512
/dev/loop2          0      0         1  1 /var/lib/snapd/snaps/gnome-3-34-1804_36.snap              0     512
/dev/loop0          0      0         1  1 /var/lib/snapd/snaps/chromium_1382.snap                   0     512
/dev/loop9          0      0         1  1 /var/lib/snapd/snaps/core18_1932.snap                     0     512
/dev/loop7          0      0         1  1 /var/lib/snapd/snaps/snap-store_481.snap                  0     512
/dev/loop5          0      0         1  1 /var/lib/snapd/snaps/gtk-common-themes_1506.snap          0     512
/dev/loop3          0      0         1  1 /var/lib/snapd/snaps/gnome-3-34-1804_60.snap              0     512
/dev/loop10         0      0         1  1 /var/lib/snapd/snaps/snapd_9721.snap                      0     512
`

/dev/loop11 points to my android rom image so it seems ok, 

`
vincent@ubuntu:~/Projects$ ls -la /dev/binderfs/
total 0
drwxr-xr-x  2 root root      0 Nov  7 07:40 .
drwxr-xr-x 19 root root   4220 Nov  7 07:40 ..
crw-------  1 root root 240, 0 Nov  7 07:40 binder-control
`

`
vincent@ubuntu:~/Projects$ lsmod | grep 'ashmem\|binder'
binder_linux          180224  0
ashmem_linux           20480  0
`

Maybe I am supposed to start anbox session-manager but when I try I get this:

vincent@ubuntu:~/Projects$ anbox session-manager
[ 2020-11-07 15:46:14] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[ 2020-11-07 15:46:14] [session_manager.cpp:161@operator()] Lost connection to container manager, terminating.
[ 2020-11-07 15:46:15] [daemon.cpp:61@Run] Container is not running
[ 2020-11-07 15:46:15] [session_manager.cpp:161@operator()] Lost connection to container manager, terminating.
Segmentation fault (core dumped)

And on the terminal where I had started anbox.sh
[ 2020-11-07 15:46:14] [lxc_container.cpp:152@setup_network] Anbox bridge interface 'anbox0' doesn't exist. Network functionality will not be available

**Comment by jnnksdev** [comment]
I think you have the wrong ticket, but yes, I agree. 'Manual' startup is too complicated and the docs don't help. For the latter there is a PR open, starting to address this problem.

This is how you start after building from source:
```
bind modules > start bridge > container-manager > session-manager
```
```
if [ ! -d "/dev/binderfs" ] ; then
  # load modules
  sudo modprobe ashmem_linux
  sudo modprobe binder_linux

  # mount binder
  sudo mkdir /dev/binderfs
  sudo mount -t binder binder /dev/binderfs
fi

# enable networking
sudo scripts/anbox-bridge.sh start

sudo build/src/anbox container-manager \
    --daemon \
    --android-image=${PWD}/android_amd64.img \
    --data-path=${PWD}/anbox-data
```
```
anbox/build/src/anbox session-manager
```

**Comment by vrichomme** [comment]
No I am in the right PR, I am using Ubuntu 20.04 LTS and it does not work.
Once I enter the anbox container-manager the shell is stuck, I don't know if I am supposed to open a new terminal or tab (I mean a new shell) to be able to enter the last line ?

**Comment by tommytran732** [comment]
The beta snap package works fine. For whatever reason, ashmem is not signed by default on 20.04... so you just gotta run these 2 commands to fix it:

sudo kmodsign sha512 /var/lib/shim-signed/mok/MOK.priv /var/lib/shim-signed/mok/MOK.der /lib/modules/\`uname -r`/kernel/drivers/staging/android/ashmem_linux.ko

sudo modprobe ashmem_linux

**Comment by raulperezalejo** [comment]
> The beta snap package works fine. For whatever reason, ashmem is not signed by default on 20.04... so you just gotta run these 2 commands to fix it:
> 
> sudo kmodsign sha512 /var/lib/shim-signed/mok/MOK.priv /var/lib/shim-signed/mok/MOK.der /lib/modules/`uname -r`/kernel/drivers/staging/android/ashmem_linux.ko
> 
> sudo modprobe ashmem_linux

this one did not worked for me. After manually signing the modeule and checkin it is signed and rebooting the PC i have having `modprobe: ERROR: could not insert 'ashmem_linux': Operation not permitted`

i am at ubuntu 20.04
