### ISSUE TITLE
multiple anbox instances running on one linux machines?

### ISSUE THREAD

**Issue by wangyuanhong2** [anbox/anbox#1630]
not sure if it is possible? It so, pls let me know the instruction or the link . Thanks verymuch!

**Comment by jnnksdev** [comment]
No, out of the box Anbox only suppports one instance.
You might want to look into https://github.com/aind-containers/aind. It's a Docker container running nested Anbox, maybe that works for you.

**Comment by wangyuanhong2** [comment]
Thanks！@jnnksdev
