### ISSUE TITLE
Failed to connect to socket /run/anbox-container.socket: No such file or directory

### ISSUE THREAD

**Issue by valdinei7** [anbox/anbox#1642]
This happened right after installing the  ashmem and binder modules: ok
So I ran ...
:~$ env ANBOX_LOG_LEVEL=debug anbox session-manager
[ 2020-10-21 03:26:11] [daemon.cpp:61@Run] Failed to connect to socket /run/anbox-container.socket: No such file or directory

**Comment by jnnksdev** [comment]
You do not need to install any kernel modules anymore, unless your distro actively did not include them. Even Ubuntu 18.04 has them by now.

As for the error message, you need to start `container-manager` before `session-manager`.
For example:
```
if [ ! -d "/dev/binderfs" ] ; then
  # load modules
  sudo modprobe ashmem_linux
  sudo modprobe binder_linux

  # mount binder
  sudo mkdir /dev/binderfs
  sudo mount -t binder binder /dev/binderfs
fi

sudo anbox/build/src/anbox container-manager \
    --daemon \
    --android-image=${PWD}/android_amd64.img \
    --data-path=${PWD}/anbox-data
```

```
anbox/build/src/anbox session-manager
```

```
anbox/build/src/anbox launch \
    --package=org.anbox.appmgr \
    --component=org.anbox.appmgr.AppViewActivity
```

Outside of  snap you will also have to modify your `/etc/subuid`and `/etc/subgid`. Assuming that your current user id is `1000`, append the following lines:
```
root:100000:999
root:1000:1
root:101001:99999
```

I just created a PR to include this in the docs.
