### ISSUE TITLE
i cant add the andbox kernel repos on linux mint

### ISSUE THREAD

**Issue by arydevy** [anbox/anbox#1648]
i get this error when running ```sudo add-apt-repository ppa:morphis/anbox-support```
the error is ```Cannot add PPA: ''This PPA does not support focal''.```

please help me

**Comment by toby63** [comment]
https://github.com/anbox/anbox/blob/master/docs/install.md

In short: Focal > 19.04

So you:
1. check for modules
2. install it via snap

**Comment by arydevy** [comment]
nvm i compiled them

**Comment by toby63** [comment]
@arydevy Could you then close this?
