### ISSUE TITLE
Compiling on Raspbian 32bits

### ISSUE THREAD

**Issue by vrichomme** [anbox/anbox#1656]
I am compiling on raspberry pi OS 32 bits ie raspbian GNU/linux 10 (buster) and I have the following error:

/usr/bin/c++  -DSTACK_LINE_READER_BUFFER_SIZE=1024 -I/home/pi/Projects/raspi/anbox/anbox/build/src -I/home/pi/Projects/raspi/anbox/anbox/src -I/usr/include/dbus-1.0 -I/usr/lib/arm-linux-gnueabihf/dbus-1.0/include -I/usr/local/include/SDL2 -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -I/home/pi/Projects/raspi/anbox/anbox -I/home/pi/Projects/raspi/anbox/anbox/external -I/home/pi/Projects/raspi/anbox/anbox/external/process-cpp-minimal/include -I/home/pi/Projects/raspi/anbox/anbox/external/android-emugl/shared -I/home/pi/Projects/raspi/anbox/anbox/external/android-emugl/host/include -I/home/pi/Projects/raspi/anbox/anbox/build/external/android-emugl/host/include -I/home/pi/Projects/raspi/anbox/anbox/external/android-emugl/shared/OpenglCodecCommon -I/home/pi/Projects/raspi/anbox/anbox/external/android-emugl/host/libs -I/home/pi/Projects/raspi/anbox/anbox/external/android-emugl/host/include/libOpenglRender -I/home/pi/Projects/raspi/anbox/anbox/external/android-emugl/host/libs/GLESv1_dec -I/home/pi/Projects/raspi/anbox/anbox/build/external/android-emugl/host/libs/GLESv1_dec -I/home/pi/Projects/raspi/anbox/anbox/external/android-emugl/host/libs/GLESv2_dec -I/home/pi/Projects/raspi/anbox/anbox/build/external/android-emugl/host/libs/GLESv2_dec -I/home/pi/Projects/raspi/anbox/anbox/external/android-emugl/host/libs/renderControl_dec -I/home/pi/Projects/raspi/anbox/anbox/build/external/android-emugl/host/libs/renderControl_dec -I/home/pi/Projects/raspi/anbox/anbox/external/cpu_features/include -I/home/pi/Projects/raspi/anbox/anbox/external/sdbus-cpp/include  -fvisibility=default -std=c++17    -fno-permissive -DX11_SUPPORT -DEGL_NO_X11 -std=c++17 -fPIC -DBINDERFS_PATH="\"/dev/binderfs\"" -O2 -g -DNDEBUG   -o CMakeFiles/anbox-core.dir/anbox/platform/sdl/window.cpp.o -c /home/pi/Projects/raspi/anbox/anbox/src/anbox/platform/sdl/window.cpp
/home/pi/Projects/raspi/anbox/anbox/src/anbox/platform/sdl/window.cpp: In constructor ‘anbox::platform::sdl::Window::Window(const std::shared_ptr<Renderer>&, const Id&, const Id&, const std::shared_ptr<anbox::platform::sdl::Window::Observer>&, const anbox::graphics::Rect&, const string&, bool, bool)’:
/home/pi/Projects/raspi/anbox/anbox/src/anbox/platform/sdl/window.cpp:92:77: error: invalid static_cast from type ‘Window’ {aka ‘long unsigned int’} to type ‘EGLNativeWindowType’ {aka ‘void*’}
       native_window_ = static_cast<EGLNativeWindowType>(info.info.x11.window);

What am I doing wrong ?
I am following this guide https://www.techiebouncer.com/2020/07/install-anbox-on-raspbian-raspberry-pi-4.html and fixing some errors.
It is mentioned to replace two 64bits variable by 32 bits inside struct CompatEvent, (I don't even know why and if it's necessary what about having a #ifdef ?
Thanks

**Comment by vrichomme** [comment]
Ok I am starting to understand how it works. So for now I have added the following cast, dont know if it will crash but for now my goal is to go throught the whole compilation process:
`
native_window_ = static_cast<EGLNativeWindowType>((void*)(std::uintptr_t)info.info.x11.window);
`
Then I had some errors about gmock:
make[2]: *** No rule to make target 'gmock/lib/libgmock.a', needed by 'tests/anbox/android/intent_tests'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:2216: tests/anbox/android/CMakeFiles/intent_tests.dir/all] Error 2

The problem comes from the fact that inside cmake/FindGMock.cmake the libraries are supposed to be inside lib folders but t doesn't seem to be the case so I have modified like this:

`
--- FindGMock.cmake	2020-10-30 19:50:20.922515496 +0100
+++ FindGMock.cmake.OK	2020-10-30 19:59:03.263137376 +0100
@@ -54,10 +54,10 @@
     set(findgmock_cxx_flags "${CMAKE_CXX_FLAGS} -g -Wno-old-style-cast -Wno-missing-field-initializers -Wno-ctor-dtor-privacy -Wno-switch-default")
 
     set(findgmock_bin_dir "${CMAKE_CURRENT_BINARY_DIR}/gmock")
-    set(findgmock_gtest_lib "${findgmock_bin_dir}/lib/libgtest.a")
-    set(findgmock_gtest_main_lib "${findgmock_bin_dir}/lib/libgtest_main.a")
-    set(findgmock_gmock_lib "${findgmock_bin_dir}/lib/libgmock.a")
-    set(findgmock_gmock_main_lib "${findgmock_bin_dir}/lib/libgmock_main.a")
+    set(findgmock_gtest_lib "${findgmock_bin_dir}/gtest/libgtest.a")
+    set(findgmock_gtest_main_lib "${findgmock_bin_dir}/gtest/libgtest_main.a")
+    set(findgmock_gmock_lib "${findgmock_bin_dir}/libgmock.a")
+    set(findgmock_gmock_main_lib "${findgmock_bin_dir}/libgmock_main.a")
 
     include(ExternalProject)
     ExternalProject_Add(GMock SOURCE_DIR "${GMOCK_SOURCE_DIR}"
@@ -81,7 +81,7 @@
     add_library(gmock INTERFACE)
     target_include_directories(gmock INTERFACE ${GMOCK_INCLUDE_DIRS})
     target_link_libraries(gmock INTERFACE ${findgmock_gmock_lib} gtest)
-
+    
     add_library(gmock_main INTERFACE)
     target_include_directories(gmock_main INTERFACE ${GMOCK_INCLUDE_DIRS})
     target_link_libraries(gmock_main INTERFACE ${findgmock_gmock_main_lib} gmock gtest_main)
`
Another approach would be to generate the gmock/gtest libraries inside those lib folders...

Then I can enter the make install command:

`
pi@jarvis2:~/Projects/raspi/anbox/anbox/build $ sudo make install
[  3%] Built target GMock
[  6%] Built target sdbus-cpp
[ 12%] Built target process-cpp
[ 15%] Built target emugen
[ 16%] Built target OpenglCodecCommon
[ 18%] Built target renderControl_dec
[ 20%] Built target GLESv2_dec
[ 22%] Built target GLESv1_dec
[ 27%] Built target emugl_common
[ 30%] Built target OpenGLESDispatch
[ 31%] Built target xdg
[ 32%] Built target xdg_test
[ 32%] Built target backward
[ 33%] Built target backward_object
[ 34%] Built target utils
[ 35%] Built target unix_based_hardware_detection
[ 36%] Built target cpu_features
[ 37%] Built target list_cpu_features
[ 40%] Built target anbox-protobuf
[ 89%] Built target anbox-core
[ 90%] Built target anbox
[ 91%] Built target intent_tests
[ 92%] Built target restricted_manager_tests
[ 93%] Built target at_parser_tests
[ 94%] Built target scope_ptr_tests
[ 95%] Built target message_channel_tests
[ 96%] Built target type_traits_tests
[ 96%] Built target binary_writer_tests
[ 96%] Built target small_vector_tests
[ 97%] Built target buffered_io_stream_tests
[ 98%] Built target buffer_queue_tests
[ 98%] Built target layer_composer_tests
[ 98%] Built target render_control_tests
[100%] Built target lxc_container_tests
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Up-to-date: /usr/local/share/anbox/ui/loading-screen.png
-- Up-to-date: /usr/local/include/backward.hpp
-- Up-to-date: /usr/local/lib/backward/BackwardConfig.cmake
-- Up-to-date: /usr/local/lib/libcpu_features.a
-- Up-to-date: /usr/local/include/cpu_features/cpu_features_macros.h
-- Up-to-date: /usr/local/include/cpu_features/cpu_features_cache_info.h
-- Up-to-date: /usr/local/include/cpu_features/cpuinfo_arm.h
-- Up-to-date: /usr/local/bin/list_cpu_features
-- Up-to-date: /usr/local/lib/cmake/CpuFeatures/CpuFeaturesTargets.cmake
-- Installing: /usr/local/lib/cmake/CpuFeatures/CpuFeaturesTargets-relwithdebinfo.cmake
-- Up-to-date: /usr/local/lib/cmake/CpuFeatures/CpuFeaturesConfig.cmake
-- Up-to-date: /usr/local/lib/cmake/CpuFeatures/CpuFeaturesConfigVersion.cmake
-- Installing: /usr/local/bin/anbox
-- Set runtime path of "/usr/local/bin/anbox" to ""
`
However the last line seems a bit weird but let's ignore it for now.
But at the end when I am trying some commands it doesn't work for now:

pi@jarvis2:~/Projects/raspi/anbox/anbox/build $ anbox check-features
You're running Anbox on a not yet supported architecture

pi@jarvis2:~/Projects/raspi/anbox/anbox/build $ anbox session-manager
[ 2020-10-30 19:06:08] [daemon.cpp:61@Run] Failed to connect to socket /run/anbox-container.socket: No such file or directory

**Comment by jnnksdev** [comment]
```
[ 2020-10-30 19:06:08] [daemon.cpp:61@Run] Failed to connect to socket /run/anbox-container.socket: No such file or directory
```
You need to run `container-manager` before starting `session-manager`. Like so:

<details>
<summary>anbox container-manager</summary>

```sh
# daemon: Mark service as being started as systemd daemon
# privileged: "Run Android container in privileged mode
# android-image: Path to the Android rootfs image file if not stored in the data path
# data-path: Path where the container and its data is stored

# NOTE: unprivileged containers
#       the file /etc/subuid and /etc/subgid need to be modified,
#       to allow the root user to impoersonate the uids needed in the container:
# root:100000:999
# root:1000:1
# root:101001:99999

if [ ! -d "/dev/binderfs" ] ; then
  # load modules
  sudo modprobe ashmem_linux
  sudo modprobe binder_linux

  # mount binder
  sudo mkdir /dev/binderfs
  sudo mount -t binder binder /dev/binderfs
fi

sudo anbox container-manager \
    --daemon \
    --android-image=${PWD}/android_amd64.img \
    --data-path=${PWD}/anbox-data
```
</details>

**Comment by vrichomme** [comment]
Thanks a lot.
Now I have this

`
pi@jarvis2:~/Projects/raspi/anbox $ ./anbox.sh 
mount: /dev/binderfs: unknown filesystem type 'binder'.
`
and from what I understand I have to recompile my raspberry kernel ...

**Comment by jnnksdev** [comment]
Anbox works by using what is called a container, in this case [LXC](https://en.wikipedia.org/wiki/LXC). Containers simulate an environment in which you can run programs, that can not see outside of the environment boundaries. This is similar to a virtual machine, but with a key difference: A container and it's host share the same kernel.

> and from what I understand I have to recompile my raspberry kernel ...

Yes, that is correct. Your kernel does not have the necessary modules and you will likely need to compile your own Kernel. You can use the unmaintainted modules from https://github.com/anbox/anbox-modules first and see wether they work for you.

Usually modprobe fails, if it cannot find a module, was that the case? 
I'm asking because the error message is related to the mount command, but it should have failed earlier.

**Comment by vrichomme** [comment]
at then I have recompiled the kernel and included ashmem and binder but still doesn't work. I give up for now.

pi@jarvis2:~/Projects/raspi/anbox $ ls -la /dev/binderfs/
total 0
drwxr-xr-x  2 root root      0 Nov  1 21:56 .
drwxr-xr-x 18 root root   3860 Nov  1 21:56 ..
crw-------  1 root root 241, 1 Nov  1 21:56 binder
crw-------  1 root root 241, 0 Nov  1 21:56 binder-control
crw-------  1 root root 241, 2 Nov  1 21:56 hwbinder
crw-------  1 root root 241, 3 Nov  1 21:56 vndbinder

`
pi@jarvis2:~/Projects/raspi/anbox $ sudo anbox container-manager --daemon --android-image=${PWD}/android-images/android.img --data-path=${PWD}/anbox-data
[ 2020-11-01 20:58:57] [container_manager.cpp:171@setup_mounts] Failed to attach Android rootfs image to loopback device
`

**Comment by vrichomme** [comment]
Still progressing actually, now the problem is due to the fact that I cannot open a file bigger than 2Gb...

`
int main()
{
    std::string file_path = "/home/pi/Projects/raspi/anbox/android-images/android.img";
    int file_fd = ::open(file_path.c_str(), O_RDONLY);
    if (file_fd < 1) {
        printf("open failed with errno: %d\n", errno);
    }
    return 0;
}
`
and I get the following:

`
pi@jarvis2:~/Projects $ g++ -O0 -g3 -ggdb test-open.cpp -o test-open
pi@jarvis2:~/Projects $ ./test-open 
open failed with errno: 75
`

**Comment by jnnksdev** [comment]
So how did you resolve the loopback error?

Some sources I found suggest a 2GB hard limit, but the threads were 4 years old.
**Solution 1**: Anbox Android image is 3.5Gb. Maybe you  can find a minimal custom ROM somewhere and compile it yourself.

**Solution 2**: Try mounting the image like this:
```sh
mkdir /tmp/android
sudo mount --source=android.img --target=/tmp/android --types=squashfs --options=loop
```
Maybe [mount](https://man7.org/linux/man-pages/man8/mount.8.html) has a clever way around the 2Gb limit. If that works I would consider an in code fix.

**Comment by vrichomme** [comment]
I asked on raspberry pi forums and here is the answer:
Yes, it's normal on an OS where the userland is 32-bit. Adding "-D_FILE_OFFSET_BITS=64" to your g++ invocation should have the desired effect.
Maybe I will create a patch for people who wants to compile anbox on raspberry pi.

**Comment by vrichomme** [comment]
I am doomed now I cannot mount squashfs:

`
#include <sys/mount.h>
#include <string.h>

#include <string>

#define ERROR_HELPER(fmt, ...) printf(fmt "\n%s", __VA_ARGS__)
#define ERROR(...) ERROR_HELPER(__VA_ARGS__, "")

int main()
{
  std::string src, target, fs_type;
  unsigned long flags = MS_MGC_VAL | MS_RDONLY | MS_PRIVATE; //0xc0ed0001

  const void *mount_data = nullptr;
  src = "/dev/loop1";
  target = "/home/pi/Projects/raspi/anbox/anbox-data/rootfs";
  fs_type = "squashfs";
    
  if (::mount(src.c_str(), target.c_str(), !fs_type.empty() ? fs_type.c_str() : nullptr, flags, mount_data) < 0) {
    ERROR("Failed to mount %s: %s", target.c_str(), strerror(errno));
    return errno;
  }
 
  return 0;
}

pi@jarvis2 :~/Projects/raspi/anbox/anbox-debug $ sudo ./mount-squashfs 
Failed to mount /home/pi/Projects/raspi/anbox/anbox-data/rootfs: Invalid argument

Don't know what is wrong now...
squashfs is a kernel module and it seems loaded:

pi@jarvis2: ~/Projects/raspi/anbox/anbox-debug $ lsmod | grep squashfs
squashfs               40960  1`

pi@jarvis2: ~/Projects/raspi/anbox/anbox-debug $ ls -la /dev/loop*
brw-rw---- 1 root disk  7,   0 Nov  1 22:00 /dev/loop0
brw-rw---- 1 root disk  7,   1 Nov  5 21:48 /dev/loop1
brw-rw---- 1 root disk  7,   2 Nov  5 21:56 /dev/loop2
brw-rw---- 1 root disk  7,   3 Nov  5 21:58 /dev/loop3
brw-rw---- 1 root disk  7,   4 Nov  1 22:00 /dev/loop4
brw-rw---- 1 root disk  7,   5 Nov  1 22:00 /dev/loop5
brw-rw---- 1 root disk  7,   6 Nov  1 22:00 /dev/loop6
brw-rw---- 1 root disk  7,   7 Nov  1 22:00 /dev/loop7
crw-rw---- 1 root disk 10, 237 Nov  1 22:00 /dev/loop-control

**Comment by vrichomme** [comment]
> Some sources I found suggest a 2GB hard limit, but the threads were 4 years old.
> **Solution 1**: Anbox Android image is 3.5Gb. Maybe you can find a minimal custom ROM somewhere and compile it yourself.
> 
> **Solution 2**: Try mounting the image like this:
> 
> ```shell
> mkdir /tmp/android
> sudo mount --source=android.img --target=/tmp/android --types=squashfs --options=loop
> ```
> 
> Maybe [mount](https://man7.org/linux/man-pages/man8/mount.8.html) has a clever way around the 2Gb limit. If that works I would consider an in code fix.
