### ISSUE TITLE
Single window mode by default

### ISSUE THREAD

**Issue by thekobbyist** [anbox/anbox#1657]
Anbox can be run in single window mode by passing the --single-window and optionally the --window-size=x,y command line variables to session-manager.
This comes with a couple of advantages
    - fixes a lot of issues with a apps that don't have support for free form windows
    - allow accessing the recent apps view as well as notifications with apps like [one shade](https://play.google.com/store/apps/details?id=com.treydev.ons&hl=en_US&gl=US) and [easy app switcher](https://play.google.com/store/apps/details?id=com.echoff.easyswitch)
    - also this allows floating apps and provides support for pip and many others
As far as I can see the only trade offs are the window size being fixed and yes the single-window

The question is, is there a way to make this the default behavior of anbox. possible through setting the arguments of the session manager in a config file?

**Comment by jnnksdev** [comment]
There is an implementation for other options that can be managed via `snapctl get` and `snapctl set`.
I'll see what I can do.

**Comment by aiamkobby** [comment]
I'm using the version from the aur. For now I just created a desktop file desktop file to launch in single window mode

**Comment by jnnksdev** [comment]
Ah, ok. That would be your best option.
