### ISSUE TITLE
Anbox won't launch in newly installed Ubuntu 17.04 on hp notebook

### ISSUE THREAD

**Issue by uttam2707** [anbox/anbox#167]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the
list of open bugs at https://github.com/anbox/anbox/issues

**Anbox release (`anbox version`) and system info (`anbox system-info`):**
anbox 0.1.0
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.10.0-19-generic (buildd@lcy01-13) (gcc version 6.3.0 20170321 (Ubuntu 6.3.0-10ubuntu1) ) #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

**Description of the problem:**
Anbox is not running from the dash nor from the command using Alt+F2.

**Expected:**

**Additional info:**
While installation it said that secure boot will be disabled and so to select a password. But during restart it didn't ask for any password or didn't enter into the bios or anything. Just rebooted normally. However, ubuntu already boots in insecure mode because I need to install realtek wifi drivers. 
ubuntu 17.04 is newly installed and is dual booting with windows. Grub is the default boot loader.

**Comment by dr3adl04d** [comment]
I have exactly the same problem. Clean 17.04 install. Anbox doesn't start. The icon is pulsating for 10-15 seconds, then disappears.

**Comment by dr3adl04d** [comment]
I found out that if I run the anbox session-manager & first, then anbox it actually works. It's extremely unstable though.

**Comment by srayhunter** [comment]
Running into the same issues on ubuntu 17.04 running under virtualbox. The session-manager is not started, but manually needs to be started. I have been able to keep it up and running. Here are some of the logs of the session-manager:

[EE 2017-04-25 05:05:31] [runtime.cpp:41@exception_safe_run] write: Broken pipe
[EE 2017-04-25 05:05:31] [runtime.cpp:41@exception_safe_run] write: Broken pipe

those 2 appear after starting **anbox**.  Like dr3adl04d mentioned, there is a lot of instability and session-manager needs to be started and restarted with use.

**Comment by adstanciu** [comment]
Ubuntu 17.04

user@user-anbox:~$ anbox session-manager
[EE 2017-04-26 07:17:01] [session_manager.cpp:119@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded

**Comment by jwhipp** [comment]
Confirmed that doing an andbox session-manger & gets Andbox running, but most apps appear with a blank screen, some of the built-ins seem to work like Calendar, Settings, Files, erc.  Non of my apps will load beyond a blank window.
Ubuntu 17.04
Linux 4.10.0-20-generic #22-Ubuntu SMP Thu Apr 20 09:22:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by wayneward** [comment]
i get the same as above i tried from source as well 

also tried to fix this ..
wayneward@shanghai:~$ sudo dkms remove anbox-modules-binder/4 --all
Error! Could not locate dkms.conf file.
File:  does not exist.
wayneward@shanghai:~$ sudo dkms install -m anbox-modules-ashmem -v 4
Error! Could not locate dkms.conf file.
File:  does not exist.

**Comment by whmak** [comment]
Same here. Anbox can't run in fresh installed 64 bit Ubuntu 17.04. Doesn't it means Ubuntu 17.04 can't support Anbox?

**Comment by wayneward** [comment]
no i have a fresh install of ubuntu gnome 17.04 i just had uefi install and enabled and disabled secure boot and works fine

**Comment by stralytic** [comment]
`[michael:~] 1 % anbox system-info
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.10.0-20-generic (buildd@lcy01-05) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) ) #22-Ubuntu SMP Thu Apr 20 09:22:42 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
[michael:~] % anbox session-manager
[EE 2017-05-08 22:52:38] [Renderer.cpp:100@initialize] Failed to Initialize backend EGL display
[1]    6966 segmentation fault (core dumped)  anbox session-manager
[michael:~] 2s 139 % 
`
I have nvidia gtx780 with nvidia drivers.

**Comment by gkovacs** [comment]
@stralytic I think the issue you're having is a different one due to anbox incompatibility with nvidia drivers, see https://github.com/anbox/anbox/issues/72
