### ISSUE TITLE
The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release' does not have a Release file.

### ISSUE THREAD

**Issue by stevensko** [anbox/anbox#1673]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**
I go to install anbox using the steps for previous versions of ubuntu because anbox doesn't start after installing it on 2004. but then it gives this error 

The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release' does not have a Release file.

**What were you expecting?:**
for it to install

**Additional info:**

**Comment by jnnksdev** [comment]
The ppa is unmaintained and should not be used. You can `snap install anbox --beta --devmode` instead.

**Comment by stevensko** [comment]
error: cannot communicate with server: Post http://localhost/v2/snaps/anbox: dial unix /run/snapd.socket: connect: no such file or directory

**Comment by RandoNandoz** [comment]
@stevensko Are you on WSL? If not, try `sudo systemctl enable --now snapd.socket`

**Comment by stevensko** [comment]
I am on WSL2, what should I try instead?

**Comment by RandoNandoz** [comment]
The Windows Subsystem for Linux kernel does not ship with ashmem or binder, which means you will have to recompile the Linux kernel for WSL. It is practically impossible to run Anbox on WSL.

**Comment by stevensko** [comment]
why can't I install ashmem and binder without recompiling?

**Comment by RandoNandoz** [comment]
It's been a while since I've used WSL2 - but I think Microsoft does not ship any other kernel modules than the bare necessities, and that WSL2 is not built with ashmem and binder support.
If you want to check, try doing `ls -R /lib/modules` and seeing whether there is anything there.

**Comment by stevensko** [comment]
nothing

**Comment by RandoNandoz** [comment]
Yes, to run Anbox the way it's meant to be is to use it on a Linux distro, not on WSL. That's a shame. However, you could hack around it to run Anbox on WSL.

**Comment by stevensko** [comment]
where would I start with hacking it?
________________________________

**Comment by EldwshlUaran** [comment]
Ign: http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal InRelease
Err:11 http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by Fuseteam** [comment]
the ppa is deprecated you no longer need it for newer versions of ubuntu
