### ISSUE TITLE
repoisitory “http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release” does not have a Release file

### ISSUE THREAD

**Issue by joiyah** [anbox/anbox#1685]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by joiyah** [comment]
hi,
I wanna to install anbox on my ubuntu 20.04 (the qnap ubuntu linuxstation),see the system information foollowing:
                          ./+o+-       admin@ubuntu2004
                  yyyyy- -yyyyyy+      OS: Ubuntu 20.04 focal
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 4.14.24-qnap
           .++ .:/++++++/-.+sss/`      Uptime: 6h 52m
         .:++o:  /++++++++/:--:/-      Packages: 2144
        o:+o+:++.`..```.-/oo+++++/     Shell: bash
       .:+o:+o/.          `+sssoo+/    Resolution: 1280x720
  .++/+:+oo+o:`             /sssooo.   DE: GNOME 3.36.4
 /+++//+:`oo+o               /::--:.   WM: Mutter
 \+/+o+++`o++o               ++////.   WM Theme: vimix-laptop-doder
  .++.o+++oo+:`             /dddhhh.   GTK Theme: vimix-laptop-doder [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: Yaru
        \+.++o+o``-````.:ohdhhhhh+     Font: Ubuntu 11
         `:o+++ `ohhhhhhhhyo++os:      Disk: 226G / 3.6T (7%)
           .o:`.syhhhhhhh/.oo++o`      CPU: Intel Celeron J1900 @ 4x 1.993GHz
               /osyyyyyyo++ooo+++/     GPU: Mesa DRI Intel(R) HD Graphics (BYT)
                   ````` +oo+++o\:     RAM: 5342MiB / 15906MiB

but when I install the Kernel Modules for anbox,i always get a error.

admin@ubuntu2004:~$ sudo add-apt-repository ppa:morphis/anbox-support
[sudo] admin 的密码： 
 
 更多信息： https://launchpad.net/~morphis/+archive/ubuntu/anbox-support
按 [ENTER] 继续或 Ctrl-c 取消安装。

获取:1 file:/.share/CACHEDEV1_DATA/.qpkg/ubuntu-hd/packages/focal stable InRelease [1,784 B]
获取:1 file:/.share/CACHEDEV1_DATA/.qpkg/ubuntu-hd/packages/focal stable InRelease [1,784 B]
命中:2 http://mirrors.aliyun.com/ubuntu focal InRelease
命中:3 http://dl.google.com/linux/chrome/deb stable InRelease                  
命中:4 http://mirrors.aliyun.com/ubuntu focal-security InRelease               
命中:5 http://mirrors.aliyun.com/ubuntu focal-updates InRelease                
命中:6 http://mirrors.aliyun.com/ubuntu focal-proposed InRelease               
命中:7 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal InRelease             
命中:8 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates InRelease     
命中:9 http://mirrors.aliyun.com/ubuntu focal-backports InRelease              
命中:10 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-backports InRelease  
命中:11 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security InRelease   
命中:12 http://cn.archive.ubuntu.com/ubuntu focal InRelease                    
忽略:13 http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal InRelease  
命中:14 http://cn.archive.ubuntu.com/ubuntu focal-updates InRelease            
命中:15 https://linux.teamviewer.com/deb stable InRelease                      
忽略:16 https://deepin-wine.i-m.dev  InRelease                                 
命中:17 http://cn.archive.ubuntu.com/ubuntu focal-backports InRelease
命中:18 http://ppa.launchpad.net/team-xbmc/ppa/ubuntu focal InRelease
命中:19 https://deepin-wine.i-m.dev  Release                                   
命中:20 http://cn.archive.ubuntu.com/ubuntu focal-security InRelease           
忽略:21 https://deepin-wine.i-m.dev  Release.gpg                       
错误:22 http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release
  404  Not Found [IP: 91.189.95.83 80]
正在读取软件包列表... 完成
E: 仓库 “http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。

How can i sovle the probelm ? please help me ,thks!

**Comment by jnnksdev** [comment]
The easiest solution is to use snap, the apt-get repository is not maintained anymore

**Comment by joiyah** [comment]
> The easiest solution is to use snap, the apt-get repository is not maintained anymore

https://docs.anbox.io/userguide/install.html 
The official documentation tells me to install the necessary kernel modules first, Then install the Anbox snap.
When I installed AnBox directly, everything was OK.
However, Anbox Application Manager and Android Setting cannot be launched in the end.
I think this is caused by the failure of the previous necessary Kernel Modulest (Binder or Ashmem kernel drivers) installation.
So, the question comes back to the original point, how can I successfully install kernel modules.
please give me some guidance,thanks a lot ！

[ $ sudo add-apt-repository **ppa:morphis/anbox-support** ]
[ $ sudo apt update ]
[ $ sudo apt install **linux-headers-generic anbox-modules-dkms** ]
---------------------------------------------------------------------------------------------------------
admin@ubuntu2004:~$ **snap install --devmode --beta anbox**
anbox (beta) 4-56c25f1 from Simon Fels (morphis) installed
admin@ubuntu2004:~$ sudo snap install --devmode --beta anbox
snap "anbox" is already installed, see 'snap help refresh'
admin@ubuntu2004:~$ **snap refresh --beta --devmode anbox**
snap "anbox" has no updates available
admin@ubuntu2004:~$ **snap info anbox**
name:      anbox
summary:   Android in a Box
publisher: Simon Fels (morphis)
store-url: https://snapcraft.io/anbox
contact:   https://anbox.io
license:   unset
description: |
  Runtime for Android applications which runs a full Android system
  in a container using Linux namespaces (user, ipc, net, mount) to
  separate the Android system fully from the host.
  
  You can find further details in our documentation at
  https://github.com/anbox/anbox/blob/master/README.md
commands:
  - anbox
  - anbox.android-settings
  - anbox.appmgr
  - anbox.collect-bug-info
  - anbox.shell
services:
  anbox.container-manager: simple, enabled, inactive
snap-id:      Nr9K6UJaIOD8wHpDEQl16nabFFt9LLEQ
tracking:     latest/beta
refresh-date: today at 10:49 HKT
channels:
  latest/stable:    –                                    
  latest/candidate: –                                    
  latest/beta:      4-56c25f1     2020-01-02 (186) 391MB devmode
  latest/edge:      4+gitr3fa48f9 2020-11-20 (205) 410MB devmode
installed:          4-56c25f1                (186) 391MB devmode

admin@ubuntu2004:~$ **anbox session-manager**
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
[ 2020-11-25 03:02:32] [session_manager.cpp:133@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded

admin@ubuntu2004:~$ **anbox.appmgr**
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
[ 2020-11-25 03:04:33] [daemon.cpp:61@Run] Application manager service is not running yet

-------------------------------------------------------------------------------------------------------------

**Comment by joiyah** [comment]
How do I install anbox-modules-dkms in ubuntu20.04 ？

admin@ubuntu2004:~$ **sudo apt install linux-headers-generic**
[sudo] password for admin: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
linux-headers-generic is already the newest version (5.4.0.55.58).
linux-headers-generic set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.

admin@ubuntu2004:~$ **sudo apt install anbox-modules-dkms**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package anbox-modules-dkms is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'anbox-modules-dkms' has no installation candidate

admin@ubuntu2004:~$ **sudo snap install anbox-modules-dkms**
error: snap "anbox-modules-dkms" not found
admin@ubuntu2004:~$

**Comment by jnnksdev** [comment]
> How do I install anbox-modules-dkms in ubuntu20.04?

Not at all, you already have them.

> The official documentation tells me to install the necessary kernel modules first,

The websites documentation is horribly outdated, check https://github.com/anbox/anbox/blob/master/docs/install.md.

Anbox works with snap out of the box on Ubunut 20.04, no additional installation of kernel modules necessary.

**Comment by joiyah** [comment]
> The websites documentation is horribly outdated, check https://github.com/anbox/anbox/blob/master/docs/install.md.
> 
> Anbox works with snap out of the box on Ubunut 20.04, no additional installation of kernel modules necessary.

OK,thank you !
According to the latest documentation,I get the following reults:

admin@ubuntu2004:~$ ls -1 /dev/{ashmem,binder}
ls: cannot access '/dev/ashmem': No such file or directory
ls: cannot access '/dev/binder': No such file or directory
admin@ubuntu2004:~$ sudo modprobe ashmem_linux
[sudo] password for admin: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    26    0     0  100    26      0     17  0:00:01  0:00:01 --:--:--    17

admin@ubuntu2004:~$ sudo mokutil --sb-state
EFI variables are not supported on this system

what should i do ?

**Comment by jnnksdev** [comment]
I don't have any experience with qnap and why modprobe is downloading something is unlear as well.

The installation is not as straight forward compared to a normal desktop system I'm afraid. 
You will have to experiment.

**Comment by joiyah** [comment]
> I don't have any experience with qnap and why modprobe is downloading something is unlear as well.
> 
> The installation is not as straight forward compared to a normal desktop system I'm afraid.
> You will have to experiment.

thanks a lot jnnksdev! maybe I should consult the qnap company.
