### ISSUE TITLE
Xubuntu 20.04: Anbox apps do not open

### ISSUE THREAD

**Issue by EternalFlameIV** [anbox/anbox#1698]
Logs attached:
[anbox-system-diagnostics-2020-12-06.zip](https://github.com/anbox/anbox/files/5649202/anbox-system-diagnostics-2020-12-06.zip)
<details>
<summary>anbox system-info output</summary>

```
$ anbox system-info
pci id for fd 5: 8086:9b41, driver (null)
pci id for fd 5: 8086:9b41, driver (null)
version: 4
snap-revision: 186
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 20.04.1 LTS (Focal Fossa)
  snap-based: true
kernel:
  version: Linux version 5.4.0-56-generic (buildd@lgw01-amd64-025) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_context_flush_control
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image_base
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES 3.0 Mesa 18.0.5
    extensions:
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_read_format_bgra
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
```
</details>

**Please describe your problem:**
Neither anbox.appmgr nor the included Settings app open visibly: although they appear in the task bar, their windows are transparent. On the first attempt to open anbox.appmgr after a fresh reboot, a "Starting..." screen opens for roughly 15 seconds, then disappears. 

**What were you expecting?:**
The App Manager and Settings app to open

**Additional info:**
All kernel modules appear to be installed and started properly:
```
$ ls -1 /dev/ashmem /dev/binder
/dev/ashmem
/dev/binder
```

When running `anbox session-manager`, some LibGL errors appear: 
 ```
$ anbox session-manager
libGL error: pci id for fd 11: 8086:9b41, driver (null)
libGL error: No driver found
libGL error: failed to load driver: (null)
libGL error: pci id for fd 11: 8086:9b41, driver (null)
libGL error: unable to load driver: iris_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: iris
pci id for fd 20: 8086:9b41, driver (null)
pci id for fd 20: 8086:9b41, driver (null)
```

Please let me know if more information is needed. Thanks!

**Comment by Camofelix** [comment]
Have the same issue, tho in my case it's for the radeonSI driver-makes me think this is driver agnostic. 
I'm running anbox V4 from the latest snap build as of december 17 2020

anbox.appmgr produces the same behavious as the initial report from EternalFlameIV, where in it will anitially launch, then go invisible. when trying to re-execute terminal will return `[ 2020-12-17 18:04:44] [launch.cpp:214@operator()] Session manager failed to become ready
`
I've attached 3 logs. the first is the return from anbox system-info > [filename].txt , the seocnd is the return of anbox session-manager and the third is the return of anbox check-features > [name].txt

[session_log.txt](https://github.com/anbox/anbox/files/5711321/session_log.txt)
[anbox_confirm_system_requirements.txt](https://github.com/anbox/anbox/files/5711322/anbox_confirm_system_requirements.txt)
[anbox_log_dec_17_2020_popsOS_ubuntu_20.04LTS_Kernel_5.8x.txt](https://github.com/anbox/anbox/files/5711323/anbox_log_dec_17_2020_popsOS_ubuntu_20.04LTS_Kernel_5.8x.txt)

**Comment by EternalFlameIV** [comment]
@Camofelix I'm not able to get the `[ 2020-12-17 18:04:44] [launch.cpp:214@operator()] Session manager failed to become ready` output, what steps did you take to get it?

**Comment by Camofelix** [comment]
> @Camofelix I'm not able to get the `[launch.cpp:214@operator()] Session manager failed to become ready` output, what steps did you take to get it?

Method to reproduce consistently was to attempt to rerun anbox.appmgr. This survived reboots, general apt update && apt upgrades etc.

**Comment by EternalFlameIV** [comment]
This line showed up in an attempt to run `anbox.appmgr` after a fresh reboot: `[splash_screen.cpp:56@SplashScreen] Window has no associated renderer yet, creating one ...` I searched this up and there was a result that gave this workaround:
```
# snap set anbox software-rendering.enable=true
# snap restart anbox.container-manager
```
This did work for me (the App Manager is no longer transparent) but the comment with the workaround noted that using software rendering like this might cause lag. Is there a better/more permanent solution?

**Comment by Camofelix** [comment]
I've removed anbox from my system for now- can you post the auto complete options of anbox? I remember one of them being something along the lines of "wait[blah blah]"

IIRC it's supposed to ensure that the cointainer is running properly

**Comment by EternalFlameIV** [comment]
```
$ anbox
NAME:
    anbox - anbox

USAGE:
    anbox [command options] [arguments...]

COMMANDS:
    wait-ready                     Wait until the Android system has successfully booted                                               
    help                           prints a short help message                                                                         
    check-features                 Check that the host system supports all necessary features                                          
    system-info                    Print various information about the system we're running on                                         
    version                        print the version of the daemon                                                                     
    session-manager                Run the the anbox session manager                                                                   
    launch                         Launch an Activity by sending an intent                                                             
```
The wait-ready command doesn't do much, even if I try to launch an instance of `anbox.appmgr` after it finishes.

**Comment by Camofelix** [comment]
[Writing this while debugging each step and using it to catalogue different steps directly as they happen]


So after a clean install via snap of both android studio and anbox I'm running into the exact same issue of `[launch.cpp:214@operator()] Session manager failed to become ready`
probing with adb devices -l returns 
```
List of devices attached
emulator-5558          device product:anbox_x86_64 model:Anbox device:x86_64 transport_id:1

```
to me this means that anbox is in fact installed and properly communicating with adb 

further trying to probe using `anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity`

yields a terminal that waits for a few moments and the STILL returns the `Session manager failed to become ready` message

Killing and restarting the server via adb kill and adb start and then running adb devices -l yields the same results as above, listing the anbox device

. trying to debug more, I found that, it does seem that anbox is responsive, since doing killall anbox, followed by adb devices -l shows that the device is no longer running.

following this up by running anbox wait-ready returns `Application manger service is not running yet` which is expected behaviour. 
 
then running anbox session-manager returns `failed to connect to socket [...] Connection refused ` this is expected behaviour 
 
restarting the service via snap and then checking adb -device showed that a device had not been created on launch. 

following that up with `anbox.appmgr` yielded the same result as every time before with failed to become ready

**Comment by EternalFlameIV** [comment]
Your session-manager service is completely refusing to start? Mine would start but not render the windows. Is the app manager coming up in your taskbar?

**Comment by Camofelix** [comment]
it has the same behaviour as yours, where I get a loading screen the first time and then nothing afterwards. The service is running and is show in adb devices list, but I can't do any more than that

**Comment by Camofelix** [comment]
Continuing to pock and prod, I tried to install an app via adb install and found that it returned `[...]Can't find service: package`

which just seems strange to me

**Comment by Camofelix** [comment]
> Your session-manager service is completely refusing to start? Mine would start but not render the windows. Is the app manager coming up in your taskbar?

out of curiosity, are you running on wayland/kde or on xorg?

**Comment by I-Rinka** [comment]
Same issue on my PopOS 20.04 (based on Ubuntu 20.04, Kernel vesion 5.10, Surface pro7 i5-1035G7).
It cannot take the advanadvantage of Gpu acceleration. The graphic UI (anbox.appmgr) only starts when I set '--software-rendering'. Wayland and Xorg both have the same issue of libGL error of driver.

**Comment by Eveldee** [comment]
I have the same exact issue as @I-Rinka , I can only run anbox apps using the software rendering on a Surface Pro 7 i5-1035G7

**Comment by EternalFlameIV** [comment]
The problem has resolved itself at some point within the past 6 months - this issue is no longer needed

**Comment by Etaash-mathamsetty** [comment]
I am still having this issue with beta and edge version of anbox 
what logs should i provide for help to diagnose the issue?

**Comment by Fuseteam** [comment]
that sounds like #1031

**Comment by Etaash-mathamsetty** [comment]
> that sounds like #1031
I tried the solution given this is my new error after running this command
`~/rs-unsquashed/usr/lib/x86_64-linux-gnu$ LD_LIBRARY_PATH=$(pwd):$(pwd)/pulseaudio:$(pwd)/dri ../../bin/anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity`

```
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  2
  Serial number of failed request:  107
  Current serial number in output stream:  108
```
