### ISSUE TITLE
Anbox looks for an outdated version of libboost.log.so

### ISSUE THREAD

**Issue by DrBanana419** [anbox/anbox#1701]
**Please describe your problem:**
When I try to run `sudo systemctl start anbox-container-manager.service` I get this error:
`● anbox-container-manager.service - Anbox Container Manager
  2      Loaded: loaded (/usr/lib/systemd/system/anbox-container-manager.service; disabled; vendor preset: disabled)
  3      Active: failed (Result: exit-code) since Thu 2020-12-10 14:51:50 +06; 42min ago
  4     Process: 1835 ExecStart=/usr/bin/anbox container-manager --daemon --privileged --data-path=/var/lib/anbox (code=exited, status=1
    27)
  5    Main PID: 1835 (code=exited, status=127)
  6
  7 Dec 10 14:51:50 This-Linux-PC systemd[1]: Started Anbox Container Manager.
  8 Dec 10 14:51:50 This-Linux-PC anbox[1835]: /usr/bin/anbox: error while loading shared libraries: libboost_log.so.1.72.0: cannot open
     shared object file: No such file or directory
  9 Dec 10 14:51:50 This-Linux-PC systemd[1]: anbox-container-manager.service: Main process exited, code=exited, status=127/n/a
 10 Dec 10 14:51:50 This-Linux-PC systemd[1]: anbox-container-manager.service: Failed with result 'exit-code'.`

**What were you expecting?:**
I was expecting the service to start successfully.

**Additional info:**
I use arch linux. I think this is happening because my version of boost-libs is 1.74.0-2. I understand that there is a [script](https://github.com/anbox/anbox/pull/783) to make anbox use a libboost_log of my choosing, but it's for the snap package. I'm not usings snaps. Now I understand that non-snaps anbox installations are unsupported, and I don't want to inconvenience anyone here, but I would greatly appreciate it if someone would guide me a way to use a similar script for non-snaps installs (if that's possible).

**Comment by AlphaXexia** [comment]
Same Issue here, also using arch-based distro(Garuda)

**Comment by DrBanana419** [comment]
Ok, I just installed the snaps package, it works.

**Comment by AlphaXexia** [comment]
> Ok, I just installed the snaps package, it works.

"The snap anbox-installer was published using classic confinement.
It thus may perform arbitrary system changes outside of the security sandbox that snaps are usually confined to, which may put your system at risk.
Install anbox-installer anyway ?"

did this prompt also show for you?

**Comment by nan-af** [comment]
I was having the same problem after having installed it from AUR. Fixed by recompiling + reinstalling it.

**Comment by nan-af** [comment]
> > Ok, I just installed the snaps package, it works.
> 
> "The snap anbox-installer was published using classic confinement.
> It thus may perform arbitrary system changes outside of the security sandbox that snaps are usually confined to, which may put your system at risk.
> Install anbox-installer anyway ?"
> 
> did this prompt also show for you?

https://docs.anbox.io/userguide/install.html#install-the-anbox-snap

**Comment by Qwart376** [comment]
Are you on zen kernel with dev-bindersfs, or zen-anbox? Anbox needs things that zen kernel and Debian has by default, which is why it won't start. You should also enable the service first, it seems disabled

**Comment by poly000** [comment]
This issue seems outdated.
Now anbox will looks for `libboost_log.so.1.75.0`, but in arch, it's 1.76.0
