### ISSUE TITLE
Feature request: please, add not-snap package :(  

### ISSUE THREAD

**Issue by snowyurik** [anbox/anbox#1705]
I can't use snap because of it's auto-update feature. I'm freelancer, so I travel a lot and I need to control my internet traffic.
"Update 4 times a day" is absolutely inacceptibooool for me. :(((((((

**Comment by nan-af** [comment]
You can compile it yourself though. It doesn't take too long, unlike some other pieces of software.

**Comment by ShadowJonathan** [comment]
Please see #62 for more discussion on this, duplicate?
