### ISSUE TITLE
Anbox PPA does not support Ubuntu bionic beaver and 

### ISSUE THREAD

**Issue by untitledgoos** [anbox/anbox#1706]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**
Anbox kernel PPA does not support focal and bionic

**What were you expecting?:**
apt update succeeds 

**Additional info:**
I use Pop!_OS 20.04

**Comment by tjssoldier** [comment]
The kernel modules are not necessary to install if you are on Ubuntu 19.04 or later check the documentation: https://github.com/anbox/anbox/blob/master/docs/install.md#install-necessary-kernel-modules

if you are using Ubuntu 18.04 the documentation says that is not necessary too, if you have hwe enable you will have the same kernel as the 20.04 has at this moment. 

So just run these commands to enable the modules:

$ sudo modprobe ashmem_linux
$ sudo modprobe binder_linux

and ls -1 /dev/{ashmem,binder} to see if they are loaded.
