### ISSUE TITLE
Failed to build Anbox: gmock

### ISSUE THREAD

**Issue by Chaosdave33** [anbox/anbox#1707]
I've get an error while building anbox:
`pi@raspberrypi:~/Workspace/anbox/build $ make
[ 90%] Built target GMock
[ 90%] Built target sdbus-cpp
[ 90%] Built target process-cpp
[ 90%] Built target emugen
[ 90%] Built target OpenglCodecCommon
[ 90%] Built target GLESv2_dec
[ 90%] Built target GLESv1_dec
[ 90%] Built target emugl_common
[ 90%] Built target OpenGLESDispatch
[ 90%] Built target renderControl_dec
[ 90%] Built target xdg
[ 90%] Built target xdg_test
[ 90%] Built target backward_object
[ 90%] Built target backward
[ 90%] Built target unix_based_hardware_detection
[ 90%] Built target utils
[ 90%] Built target cpu_features
[ 90%] Built target list_cpu_features
[ 90%] Built target anbox-protobuf
[ 90%] Built target anbox-core
[ 90%] Built target anbox
make[2]: *** Keine Regel vorhanden, um das Ziel „gmock/lib/libgmock.a“, 
  benötigt von „tests/anbox/android/intent_tests“, zu erstellen.  Schluss.
make[1]: *** [CMakeFiles/Makefile2:2216: tests/anbox/android/CMakeFiles/intent_tests.dir/all] Fehler 2
make: *** [Makefile:141: all] Fehler 2
`
Building on aarch64 with libgmock-dev installed.

**Comment by linux0ne-su** [comment]
make[2]: *** 没有规则可制作目标“gmock/lib/libgmock.a”，由“tests/anbox/android/intent_tests” 需求。 停止。
CMakeFiles/Makefile2:2045: recipe for target 'tests/anbox/android/CMakeFiles/intent_tests.dir/all' failed
make[1]: *** [tests/anbox/android/CMakeFiles/intent_tests.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2

我也遇到这样的问题，请问这该怎么解决 ？
