### ISSUE TITLE
Anbox Does Not Running On Arch Linux

### ISSUE THREAD

**Issue by LinArcX** [anbox/anbox#171]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the
list of open bugs at https://github.com/anbox/anbox/issues

**Anbox release (`anbox version`) and system info (`anbox system-info`):**
 ❯ anbox version                                                     [10:26:47]
anbox 0.1.0
 ❯ anbox system-info                                                 [10:27:06]
[1]    30845 segmentation fault (core dumped)  anbox system-info

**Description of the problem:**
I install android image from [AUR](https://aur.archlinux.org/packages/anbox-image/).
I install [Anbox Package](https://aur.archlinux.org/packages/anbox-git/) from Aur too.(install [anbox modules dkms](https://aur.archlinux.org/packages/anbox-modules-dkms-git/) as dependency)
every thing done ok.
i enable anbox-container-manager.service with:
`sudo systemctl status anbox-container-manager.service`
and run:
` anbox session-manager `
but after 5 second i face with this error message:
`[2]    20719 segmentation fault (core dumped)  anbox session-manager`
and this is journalctl Log:
[PasteBin](https://pastebin.com/kSR7pGLY)

**Expected:**

**Additional info:**
Distro:Arch Linux
DE:Cinnamon
Kernel:4.9.22-1 LTS

**Comment by xuelongqy** [comment]
start ANBOX_LOG_LEVEL=debug primusrun anbox session-manager in a terminal, then launch the .desktop file.

**Comment by LinArcX** [comment]
```
 ❯ ANBOX_LOG_LEVEL=debug anbox session-manager                                                                        [14:50:04]
[DD 2017-04-25 10:20:04] [gl_renderer_server.cpp:82@GLRendererServer] Using GLES-to-GL translator for rendering
[DD 2017-04-25 10:20:04] [Renderer.cpp:113@initialize] EGL doesn't support surfaceless context
[DD 2017-04-25 10:20:04] [Renderer.cpp:249@initialize] Successfully initialized EGL
[1]    7071 segmentation fault (core dumped)  ANBOX_LOG_LEVEL=debug anbox session-manager

```

**Comment by namoo4u** [comment]
@LinArcX try "anbox session-manager --gles-driver=host"

**Comment by Omar007** [comment]
@namoo4u For me that does indeed allow me to run anbox normally on Arch.

**Comment by morphis** [comment]
The core dump shows that things are crashing down in the i965_dri.so library which is part of Mesa. Looks more like there is something wrong with the system setup but that is still to be proven. As I don't have an Arch system it is hard for me to reproduce and fix this problem. Any help is appreciated.

**Comment by Omar007** [comment]
My laptop does also use an integrated Intel GPU. If it is indeed a system problem I suspect it would have to be a problem with the Arch package or a bug within the driver since I've made no changes or config files for anything related to Mesa or video drivers.
I am running a Wayland sessions as opposed to Xorg sessions, not sure if that may be relevant or not so I thought I'd mention it.

I'll give it a shot on my desktop system later, which is using the proprietary nVidia drivers. I would also like to test it with nouveau but those drivers do not work properly with my GPUs.

**Comment by Omar007** [comment]
It works normally with the nVidia drivers on my desktop system but from what I can see in the logs it is forcing use of the host EGL driver.
This means using the nVidia driver basically implies the use of "--gles-driver=host" right? I do not see a difference when I explicitly set it.

I've also tried to get nouveau running once more, sadly that is still a no-go so I can't test the Mesa/Gallium stack using a different driver.

**Comment by morphis** [comment]
> I am running a Wayland sessions as opposed to Xorg sessions, not sure if that may be relevant or not so I thought I'd mention it.

We don't support wayland yet.

> This means using the nVidia driver basically implies the use of "--gles-driver=host" right? I do not see a difference when I explicitly set it.

Not necessarily. The --gles-driver option allows you to change if Anbox should use libGL.so from your host or libGLES.so. If --gles-driver=translator is selected libGL.so will be used and Anbox will use its GL-to-GLES translator to provide the necessary GLES functionality to Android.

> I'll give it a shot on my desktop system later, which is using the proprietary nVidia drivers. I would also like to test it with nouveau but those drivers do not work properly with my GPUs.

The nvidia drivers generally should work we just had a problem with the snap that it couldn't load the libraries from the host system. https://github.com/anbox/anbox/pull/158 helps a bit with that problem but we're not fully there yet.

**Comment by GNOME-IS-LIFE** [comment]
> We don't support wayland yet.

thats sad :frowning_face: 
one day you will have to though, because Wayland is the future..

**Comment by morphis** [comment]
> one day you will have to though, because Wayland is the future..

Sure but one step after another. Contributions from your side to help with this are always welcome :-)

**Comment by Lymia** [comment]
I can confirm that this issue occurs on X11 on Arch too.

**Comment by foi** [comment]
Hi! Have issue too
`
Linux foi-pc 4.13.0-1-MANJARO #1 SMP PREEMPT Mon Aug 21 06:29:36 UTC 2017 x86_64 GNU/Linux

systemctl start snapd.socket

systemctl enable snapd.socket
Created symlink /etc/systemd/system/sockets.target.wants/snapd.socket → /usr/lib/systemd/system/snapd.socket.

sudo  snap install --classic anbox-installer && anbox-installer
anbox-installer 1 from 'morphis' installed
bash: anbox-installer: command not found
`

**Comment by hsc-root** [comment]
@foi you have to run 
    /snap/bin/anbox-installer

But then I have this error : 
    execv failed: No such file or directory

**Comment by sarangnemo** [comment]
For me, anbox runs well with kernel 4.9 (from Manjaro/Arch), but with kernel 4.14 I have the same issue as @Lymia above. Running `anbox system-info`, I noticed that there's one MESA extension present in 4.14 that's not there in 4.9: `EGL_ANDROID_native_fence_sync`. I suspect this is a major part of the problem. Is it possible to disable that particular extension?

**Comment by LinArcX** [comment]
any update or good news?

**Comment by LinArcX** [comment]
I follow this instructions:
https://github.com/anbox/anbox/issues/305#issuecomment-306465578
And finally i can run anbox sucessfully!
