### ISSUE TITLE
when loading session-manager Failed to start as either binder or ashmem kernel drivers are not loaded

### ISSUE THREAD

**Issue by powens7713** [anbox/anbox#1717]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by sevu** [comment]
Where's the bug report?

**Comment by nikp123** [comment]
I believe it's an issue with kernels that have ashmem and binder built into the kernel as opposed to being loadable modules

One notable example is the ZEN kernel used in ArchLinux.

When running ``anbox session-manager`` the command will fail by falsely notifying that those modules aren't loading into the system. Please fix this by checking /proc/config.gz or other locations for CONFIG_ASHMEM or similar.

**Comment by nikp123** [comment]
And yes I am running the latest git version, which means the bug is still present.

**Comment by nikp123** [comment]
Apologies for no updates. This has been fixed by the ArchLinux community via a custom udev config.
