### ISSUE TITLE
Mailing List

### ISSUE THREAD

**Issue by amorenew** [anbox/anbox#172]
Hi
Is there a mailing list so I can subscribe to know about anbox news ?

**Comment by hub2git** [comment]
None the moment. You can tap the ”watch” button on the upper right. Mind
you, you will get a deluge of emails.

**Comment by amorenew** [comment]
I hope they use any free mailing service it's really a nice tool

**Comment by hub2git** [comment]
I think their priority is to work on Anbox. Managing a mailing list is not
a priority, I think.

**Comment by amorenew** [comment]
but I can't have a a lot of emails on every commit and mailing is just for a new feature or at least an rss in the website or google + page.

**Comment by davidelang** [comment]
I would also like to see a mailing list. deciphering what's happening from the flood of commit messages is no-trivial, and while the github issue tracker is good for tracking bugs, it's not really good for people having simple getting started issues (it takes significant effort to hunt through all prior, closed issues to see if your question is there, few people will bother)

**Comment by hub2git** [comment]
@davidelang & @amorenew, anbox is alpha. This means it's not ready yet for
delivery. It's not even in beta stage. You're asking the developers to take
time away from working out the kinks in the software. Would you rather them
spend time creating a mailing list with no news to share?
Why not check anbox.io or
https://github.com/anbox/anbox/blob/master/README.md every month to see if
there are any major changes?

**Comment by amorenew** [comment]
no need for mailing list just a google plus page or facebook page in 5 minutes
simple right?

**Comment by hub2git** [comment]
amorenew, why don't you create an unofficial google+ or FB page then?

**Comment by amorenew** [comment]
in genymotion I get a new update one time a month or every 2 months.
I need them to do their work well without any distraction.

**Comment by amorenew** [comment]
https://plus.google.com/u/0/communities/115294955210949301040
UnOfficial Page on Google Plus I hope any repo member add it in Project Get in Touch section in project description here until they be able to manage their own official mailing list

**Comment by hub2git** [comment]
I suggest stating on your GooglePlus page that it is an UNofficial page.

**Comment by amorenew** [comment]
ok
