### ISSUE TITLE
Feature request : ibus support for anbox

### ISSUE THREAD

**Issue by hellojaccc** [anbox/anbox#1720]
ibus / or any typing method support would be great.
it would be useful especially on onenote, word, note taking apps.

**Comment by bpint** [comment]
+1
very important feature for non-english apps, since input methods within android not available either.

**Comment by AnterCreeper** [comment]
Because the clipboard is available, I think it may be workable.
very important feature!
+1

**Comment by Fuseteam** [comment]
uh fairly certain you can type just fine in anbox apps
