### ISSUE TITLE
Unable to install Anbox on Pop!_OS

### ISSUE THREAD

**Issue by AMoonRabbit** [anbox/anbox#1725]
Hi, I've tried to install Anbox on my Surface Pro running Pop! OS but ran into issues. I have installed it from the Pop store, and then used the Install.sh to try and make the ashmem file.

Make log:
DKMS make.log for anbox-ashmem-1 for kernel 5.10.5-surface (x86_64)
Fri  8 Jan 18:33:44 GMT 2021
make -C /lib/modules/5.10.5-surface/build V=0 M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-5.10.5-surface'
  CC [M]  /var/lib/dkms/anbox-ashmem/1/build/deps.o
  CC [M]  /var/lib/dkms/anbox-ashmem/1/build/ashmem.o
  LD [M]  /var/lib/dkms/anbox-ashmem/1/build/ashmem_linux.o
  MODPOST /var/lib/dkms/anbox-ashmem/1/build/Module.symvers
ERROR: modpost: "kallsyms_lookup_name" [/var/lib/dkms/anbox-ashmem/1/build/ashmem_linux.ko] undefined!
make[2]: *** [scripts/Makefile.modpost:111: /var/lib/dkms/anbox-ashmem/1/build/Module.symvers] Error 1
make[2]: *** Deleting file '/var/lib/dkms/anbox-ashmem/1/build/Module.symvers'
make[1]: *** [Makefile:1709: modules] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.5-surface'
make: *** [Makefile:12: all] Error 2

Output of the Install.sh when run:

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.10.2-surface all KERNEL_SRC=/lib/modules/5.10.2-surface/build...(bad exit status: 2)
ERROR (dkms apport): binary package for anbox-ashmem: 1 not found
Error! Bad return status for module build on kernel: 5.10.2-surface (x86_64)
Consult /var/lib/dkms/anbox-ashmem/1/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.10.2-surface all KERNEL_SRC=/lib/modules/5.10.2-surface/build...(bad exit status: 2)
ERROR (dkms apport): binary package for anbox-binder: 1 not found
Error! Bad return status for module build on kernel: 5.10.2-surface (x86_64)
Consult /var/lib/dkms/anbox-binder/1/build/make.log for more information.
binder_linux          184320  0
ashmem_linux           20480  0
crw------- 1 root root 10, 58 Jan  8 18:30 /dev/ashmem
crw------- 1 root root 10, 57 Jan  8 18:30 /dev/binder

**Comment by arifcelik56** [comment]
Hi, i cant install to on Pop!_OS. Were you able to install?

**Comment by ElnuDev** [comment]
Please explain your fix before closing your issue, thanks.

**Comment by AMoonRabbit** [comment]
Sorry, I gave up in the end and an no longer on any Linux distro at the
moment.
