### ISSUE TITLE
Arch-based Linux: Voice Chat in Xbox App Does Not Connect/Work

### ISSUE THREAD

**Issue by ThisNekoGuy** [anbox/anbox#1726]
<details>
<summary>Issue Template</summary>
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
</details>

<details>
<summary>Anbox System-Info output</summary>

```
https://gist.github.com/ThisNekoGuy/9cbee1d70cfe88544326abfa1e8089d6
```
</details>

**Please describe your problem:**
I installed Anbox [via the AUR](https://aur.archlinux.org/packages/anbox-image-gapps/), as suggested via the [Arch Wiki](https://wiki.archlinux.org/index.php/Anbox), and tried to install the Xbox app (formerly known Xbox Smartglass) so I can talk to friends, [via the Play Store](https://aur.archlinux.org/packages/anbox-image-gapps/), but it kept hanging on pending.
So, instead, I installed the Xbox manually with an apk by using adb and the app works but Anbox isn't capturing my voice when I try to talk in a party voice chat.

According to my friend who's on Xbox, he stated that I appeared as "connecting" which leads me to understand that, for whatever reason, it seemed that attempting to connect to the voice chat with Anbox wasn't working at all (I never fully entered that voice chat room to speak in the first place).

(Also not sure how to set and get debug info from a compiled build.)

**What were you expecting?:**
Joining the voice chat room should have connected properly and I should have been able to hear and talk to other participants.

**Comment by edgar-vincent** [comment]
There's no mic support ATM: https://github.com/anbox/anbox/issues/1446
