### ISSUE TITLE
Not working with snapd (Arch, Manjaro etc)

### ISSUE THREAD

**Issue by mitcoes** [anbox/anbox#174]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the
list of open bugs at https://github.com/anbox/anbox/issues

**Anbox release (`anbox version`) and system info (`anbox system-info`):**
I was able to install anbox with snapd, but with no known way of start it up

**Description of the problem:**
It does not work with snapd, Arch, Manajro, and similars

**Expected:**
To work

**Additional info:**
I suppose as snap should be cross platform, you will solve this soon with next upgrades, and please make a link to the menu / desktop that would make easy to start the container.

**Comment by zhsj** [comment]
I think arch users should go with https://aur.archlinux.org/packages/anbox-git/
It was not snap based but with a good PKGBUILD.

**Comment by morphis** [comment]
> It does not work with snapd, Arch, Manajro, and similars

I don't see the real problem. Can you please elaborate more in detail what exactly you do, what went wrong or does not work? This is far to general in order to allow us to help getting it to work on Arch or Manajro. With this a minimal set of developers we can't have all distributions around and test things everywhere.

**Comment by morphis** [comment]
Please reopen with more details.

**Comment by mitcoes** [comment]
Previously installing anbox-git from AUR it failed because there was not
configured to install anbox-image, after installing anbox-image, it appears
on the menu, but it does not run

I think the installer PKGBUILD must add the anbox image download, plus a
configuration for the missing socket.

I cannot help you more, and thanks a lot for your work, as I think this
will be a must have for every distro once it works well, that it hopefully
will.

$ anbox session-manager
[EE 2017-05-01 12:53:54] [daemon.cpp:58@Run] Failed to connect to socket
/run/anbox-container.socket: No such file or directory


$ anbox system-info
version: 0.1.0
os:
  name: Manjaro Linux
  version:
  snap-based: false
kernel:
  version: Linux version 4.10.12-1-MANJARO (builduser@manjaro) (gcc version
6.3.1 20170306 (GCC) ) #1 SMP PREEMPT Fri Apr 21 08:19:46 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.4
    extensions:
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_output_base
      - EGL_EXT_stream_acquire_mode
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context_no_error
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_partial_update
      - EGL_KHR_swap_buffers_with_damage
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_stream
      - EGL_KHR_stream_consumer_gltexture
      - EGL_KHR_stream_cross_process_fd
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_surfaceless_context
      - EGL_NV_post_sub_buffer
      - EGL_NV_stream_metadata
      - EGL_NV_stream_sync
      - EGL_NV_stream_consumer_gltexture_yuv
      - EGL_NV_stream_attrib
      - EGL_NV_sync
      - EGL_NV_system_time
      - EGL_NV_output_drm_flip_event
      - EGL_WL_bind_wayland_display
      - EGL_WL_wayland_eglstream
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 1.1 NVIDIA 375.39
    extensions:
      - GL_EXT_debug_label
      - GL_EXT_map_buffer_range
      - GL_EXT_robustness
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_format_BGRA8888
      - GL_KHR_debug
      - GL_NV_texture_compression_s3tc
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_compressed_paletted_texture
      - GL_OES_draw_texture
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_extended_matrix_palette
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_matrix_get
      - GL_OES_matrix_palette
      - GL_OES_packed_depth_stencil
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_OES_rgb8_rgba8
      - GL_OES_read_format
      - GL_OES_stencil8
      - GL_OES_texture_cube_map
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float





2017-04-29 11:06 GMT+02:00 Simon Fels <notifications@github.com>:

**Comment by morphis** [comment]
> $ anbox session-manager
[EE 2017-05-01 12:53:54] [daemon.cpp:58@Run] Failed to connect to socket
/run/anbox-container.socket: No such file or directory

That shows that the container-manager service isn't running. As I don't have an overview of what the unofficial anbox package for Arch does I can't tell you why the container-manager isn't starting. The best is if you talk with the maintainer of the Anbox package in Arch to see if there is something broken with the packaging.

**Comment by mitcoes** [comment]
Thanks

2017-05-01 15:32 GMT+02:00 Simon Fels <notifications@github.com>:
