### ISSUE TITLE
Anbox doesn't start after successful installation.

### ISSUE THREAD

**Issue by AravindhStanley** [anbox/anbox#175]
System Info:
Pentium B950 dual core (Sandy Bridge)
2 GB RAM
OS: Elementary OS Loki based on Ubuntu 16.04 LTS

The installer successfully installs it and prompts for a reboot. After the reboot, on opening anbox it appears for a brief time and then vanishes. No crash or whatsoever.

**Comment by AravindhStanley** [comment]
Seems like this is causing issue
anbox system-info

binder: false
ashmem: false

**Comment by davidelang** [comment]
this sounds like the anbox-install process was not able to install those 
packages. does it end with some error? On my system I had a couple repos 
configured that were not up to date, and apt-get update complained about them. 
This was enough to make the anbox-install fail and not install those packaGES

**Comment by AravindhStanley** [comment]
Here is what happened
echo 'Installing application launcher detection for X11 ..'
Installing application launcher detection for X11 ..
sudo tee /etc/X11/Xsession.d/68anbox
mkdir -p /home/zerra/.config/upstart
echo 'Installing upstart session job ..'
Installing upstart session job ..
cat
initctl start anbox
initctl: Name "com.ubuntu.Upstart" does not exist
true
mkdir -p /home/zerra/.config/systemd/user
echo 'Installing systemd user session service ..'
Installing systemd user session service ..
cat
systemctl --user daemon-reload
Failed to execute operation: Process org.freedesktop.systemd1 exited with status 1
true
systemctl --user enable --now anbox
Failed to execute operation: Process org.freedesktop.systemd1 exited with status 1
true
set +x

**Comment by AravindhStanley** [comment]
I did have some indexing problems with some ppa but I removed them before installing anbox

**Comment by AravindhStanley** [comment]
Edit: seems like a reinstall and "exec /snap/bin/anbox session-manager" did the job. FYI it took a long time to execute the command

**Comment by hoseinit** [comment]
I have the same problem with LinuxMint 18.1 and Linux 4.4.0-72
I have installed it and now I can't uninstall, how to unistall the anbox? 
and then do "exec /snap/bin/anbox session-manager"  as you said.
@AravindhStanley

**Comment by AravindhStanley** [comment]
Run "anbox-installer" in terminal. Enter 2 to uninstall.

**Comment by hoseinit** [comment]
@AravindhStanley thanks so much, It ran after reinstalling.
But when I closed it it doesn't run again. so it may be buggy

**Comment by AravindhStanley** [comment]
That's weird. But I have to run "exec /snap/bin/anbox session-manager" every time I boot and keep the terminal open. So maybe try that.
