### ISSUE TITLE
[Feature Request] Add support to add custom bind mount entry from host to anbox.

### ISSUE THREAD

**Issue by ahmubashshir** [anbox/anbox#1754]
As this is a feature request, I'm not following the template.

I'd like to bind mount `/mnt/Mount/SomeDir` to `data/media/0/SomeDir`. And afaik, lxc supports this with `lxc.mount.entry` directive.

But when I add `lxc.mount.entry = /mnt/Mount/SomeDir data/media/0/SomeDir none bind 0 0` in `/var/lib/anbox/containers/default/config`, anbox container manager just overwrites it with default.

I want to override this config somewhere...

**Comment by cdfa** [comment]
Hey I tried to do the same thing more than half a year ago! I don't know much about android, so the best I could come up with was a patch that hardcoded it in the configuration, but your approach seems much better. Sadly, I can't figure out how to use it just by looking at the code. Could you add some documentation maybe?

**Comment by ahmubashshir** [comment]
Ok... I'll upload my bindtab.
	Mubashshir

**Comment by ahmubashshir** [comment]
@cdfa , format of `bindtab` file is like `fstab`. Each line not starting with `#` describes a `lxc.mount.entry` entry and bindtab file doesn't support inline comment.
```fstab
# bindtab file doesn't support inline comment
# and it requires absolute path for host directory

# host-path mount-point type mount-options dump pass
/src dst none bind,create=dir,optional 0 0
```

[lxc config file doc](https://linuxcontainers.org/lxc/manpages/man5/lxc.container.conf.5.html)
[bindtab.gz](https://github.com/anbox/anbox/files/6183484/bindtab.gz)

**Comment by ahmubashshir** [comment]
> Hey I tried to do the same thing more than half a year ago! I don't know much about android, so the best I could come up with was a patch that hardcoded it in the configuration, but your approach seems much better. Sadly, I can't figure out how to use it just by looking at the code. Could you add some documentation maybe?

BTW, any idea where can I write a doc or can you write one ? :3 I don't have confidence in my doc writing skill.

**Comment by cdfa** [comment]
Thank you for your fast response! I think I understand enough to try it now. For documentation, there is https://docs.anbox.io/index.html for which I believer the sources are [here](https://github.com/anbox/docs). English isn't my first language either, but I can give it a go.

I'm out of time for today, but I'll give it a try tomorrow!

**Comment by cdfa** [comment]
Got around to it tonight after all :). It works well, but I have one more question. I want only my user to be able to read and write files in the directory I'm binding, but it seems like the applications can not access it if I set the permissions this way.
Have you figured out a way to do this perhaps?

I'm not sure if this has anything to do with it, but I do have an `/etc/subuid` and `/etc/subgid` that look something like this (I think the last line is from something different):

```
root:100000:999
root:1000:1
root:101001:99000

cdfa:200000:65536
```

**Comment by ahmubashshir** [comment]
I just created a group named anbox_media with id 1023, and added my 
user to that group :3
	Mubashshir

**Comment by cdfa** [comment]
And then the files would be owned by anbox_media? I guess it would work, but it's a little ugly. Perhaps @morphis knows a better solution?
