### ISSUE TITLE
A downstream project

### ISSUE THREAD

**Issue by ChenYifei21** [anbox/anbox#1756]
There is a Android container project in China. Its name's "Deepin Android Box(Kbox)" It's a closed source project.But it quoted anbox's code.And it didn't hide it.
root@orangepi3:~# apt search "Deepin Android Вox
kbox/eagle,now 1.0.11.6+dde arm64 
Deepin Android Вох
root@orangepi3:~# Kbox:
anbox - anbox
USAGE:
anbox [command options] [arguments...]
......

**Comment by nghuyy** [comment]
Is this work on armv7 ?

**Comment by ChenYifei21** [comment]
No ,only on arm64

**Comment by nghuyy** [comment]
I can install anbox on arm or arm64 but cant compile modules. Recomplie dkms too hard and many bugs

**Comment by ChenYifei21** [comment]
> I can install anbox on arm or arm64 but cant compile modules. Recomplie dkms too hard and many bugs

You can complie modules with out dkms.Debian has kernel source patch,it can help you compile ashmem&binder modules.Load it and then run anbox.
(But official image for arm can't work.You must recompile the android image)

**Comment by nghuyy** [comment]
I Found office image here :
https://build.anbox.io/android-images/2017/06/12/ (32 bit arm)
or
https://build.anbox.io/android-images/2017/08/04/

**Comment by nar2634** [comment]
@ChenYifei21 

I think you can get the source package [here](https://mirror.zetup.net/deepin/pool/contrib/a/anbox/)?
