### ISSUE TITLE
Ubuntu Groovy Release PPA?

### ISSUE THREAD

**Issue by elsiehupp** [anbox/anbox#1757]
Note: I was able to install Anbox on another computer running an earlier version of Ubuntu.

When I tried adding the Anbox PPA [in order to install the kernel extensions](https://docs.anbox.io/userguide/install_kernel_modules.html), I got the following error:
```
Err:9 http://ppa.launchpad.net/morphis/anbox-support/ubuntu groovy Release     
  404  Not Found [IP: 91.189.95.85 80]
...
E: The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu groovy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```
Do you have any idea when a Release PPA for Ubuntu Groovy might become available? Thanks!

**Comment by tjssoldier** [comment]
It is not necessary install kernel modules in Groovy they are already installed:
`Starting with Ubuntu 19.04 binder and ashmem are now build with the standard Ubuntu kernel (>= 5.0) and you don’t have to install the modules from the PPA anymore.`

Just install Anbox and will work.

**Comment by elsiehupp** [comment]
Thanks! Wow, I skimmed right over that!
