### ISSUE TITLE
Wifi emulator ?

### ISSUE THREAD

**Issue by stuaxo** [anbox/anbox#1770]
The Android emulator has a Wifi emulator [1]

This might be a good feature for anbox.

In Anbox I can connect to the network, but some apps think I am not connected, including most of the Denon remote control apps by D+M, e.g.
https://play.google.com/store/apps/details?id=com.dmholdings.denonremoteapp

[1]
https://developer.android.com/studio/run/emulator#wifi

**Comment by Fuseteam** [comment]
well it has "stale" for almost a year :p
jokes aside, anbox is not an emulator, it's a container. it's "network connection" is a virtual bridge it can connect to

**Comment by stuaxo** [comment]
True.  TBH I'm not sure what these apps are doing to check the network is WiFi, I imagine they don't need WiFi at all and if we could work it out something could be fudged.

Apologies for the frustrated joke, probably need a bit of time off :)

**Comment by Fuseteam** [comment]
yeah these apps seem to assume tis a smartphone so __surely__ it has wifi right? xd

**Comment by stuaxo** [comment]
I mean.. I run them on a laptop so there is actually WIFI but it would be good even if running on a desktop.

**Comment by Fuseteam** [comment]
in the case of anbox it is seen as an ethernet connection, cause it's an network bridge xd
