### ISSUE TITLE
Anbox Install Error Using $ make

### ISSUE THREAD

**Issue by johnsunxu** [anbox/anbox#1773]
**Please describe your problem:**
I am unable to install anbox. 

**What were you expecting?:**
Being able to build anbox after "$ cmake .." and "$ make"

**Additional info:**
After running $ make it errors at 89% or 90% on "Linking CXX executable intent_tests."

Here is what terminal spits out.

`
[ 89%] Linking CXX executable intent_tests
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o: In function `Intent_IsValid_Test::TestBody()':
/home/user/anbox/tests/anbox/android/intent_tests.cpp:24: undefined reference to `testing::Message::Message()'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:24: undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:24: undefined reference to `testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:24: undefined reference to `testing::internal::AssertHelper::operator=(testing::Message const&) const'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:24: undefined reference to `testing::internal::AssertHelper::~AssertHelper()'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o: In function `Intent_IsValid_Test::TestBody()':
/usr/include/gtest/internal/gtest-port.h:1134: undefined reference to `testing::internal::IsTrue(bool)'
/usr/include/gtest/internal/gtest-port.h:1134: undefined reference to `testing::internal::IsTrue(bool)'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o: In function `Intent_IsValid_Test::TestBody()':
/home/user/anbox/tests/anbox/android/intent_tests.cpp:26: undefined reference to `testing::Message::Message()'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:26: undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:26: undefined reference to `testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:26: undefined reference to `testing::internal::AssertHelper::operator=(testing::Message const&) const'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:26: undefined reference to `testing::internal::AssertHelper::~AssertHelper()'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o: In function `Intent_IsValid_Test::TestBody()':
/usr/include/gtest/internal/gtest-port.h:1134: undefined reference to `testing::internal::IsTrue(bool)'
/usr/include/gtest/internal/gtest-port.h:1134: undefined reference to `testing::internal::IsTrue(bool)'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o: In function `Intent_IsValid_Test::TestBody()':
/home/user/anbox/tests/anbox/android/intent_tests.cpp:30: undefined reference to `testing::Message::Message()'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:30: undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:30: undefined reference to `testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:30: undefined reference to `testing::internal::AssertHelper::operator=(testing::Message const&) const'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:30: undefined reference to `testing::internal::AssertHelper::~AssertHelper()'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o: In function `Intent_IsValid_Test::TestBody()':
/usr/include/gtest/internal/gtest-port.h:1134: undefined reference to `testing::internal::IsTrue(bool)'
/usr/include/gtest/internal/gtest-port.h:1134: undefined reference to `testing::internal::IsTrue(bool)'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o: In function `Intent_IsValid_Test::TestBody()':
/home/user/anbox/tests/anbox/android/intent_tests.cpp:28: undefined reference to `testing::Message::Message()'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:28: undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:28: undefined reference to `testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:28: undefined reference to `testing::internal::AssertHelper::operator=(testing::Message const&) const'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:28: undefined reference to `testing::internal::AssertHelper::~AssertHelper()'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o: In function `Intent_IsValid_Test::TestBody()':
/usr/include/gtest/internal/gtest-port.h:1134: undefined reference to `testing::internal::IsTrue(bool)'
/usr/include/gtest/internal/gtest-port.h:1134: undefined reference to `testing::internal::IsTrue(bool)'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o: In function `Intent_IsValid_Test::TestBody()':
/home/user/anbox/tests/anbox/android/intent_tests.cpp:24: undefined reference to `testing::internal::AssertHelper::~AssertHelper()'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:26: undefined reference to `testing::internal::AssertHelper::~AssertHelper()'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:30: undefined reference to `testing::internal::AssertHelper::~AssertHelper()'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:28: undefined reference to `testing::internal::AssertHelper::~AssertHelper()'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o: In function `Intent_IsValid_Test::~Intent_IsValid_Test()':
/home/user/anbox/tests/anbox/android/intent_tests.cpp:22: undefined reference to `testing::Test::~Test()'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o: In function `Intent_IsValid_Test::~Intent_IsValid_Test()':
/home/user/anbox/tests/anbox/android/intent_tests.cpp:22: undefined reference to `testing::Test::~Test()'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o: In function `testing::internal::TestFactoryImpl<Intent_IsValid_Test>::CreateTest()':
/home/user/anbox/tests/anbox/android/intent_tests.cpp:22: undefined reference to `testing::Test::Test()'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o: In function `testing::internal::scoped_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::reset(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) [clone .part.20] [clone .constprop.37]':
/usr/include/gtest/internal/gtest-port.h:1134: undefined reference to `testing::internal::IsTrue(bool)'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o: In function `testing::internal::scoped_ptr<std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > >::reset(std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >*) [clone .part.11] [clone .constprop.38]':
/usr/include/gtest/internal/gtest-port.h:1134: undefined reference to `testing::internal::IsTrue(bool)'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o: In function `__static_initialization_and_destruction_0':
/home/user/anbox/tests/anbox/android/intent_tests.cpp:22: undefined reference to `testing::internal::GetTestTypeId()'
/home/user/anbox/tests/anbox/android/intent_tests.cpp:22: undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o:(.data.rel.ro._ZTI19Intent_IsValid_Test[_ZTI19Intent_IsValid_Test]+0x10): undefined reference to `typeinfo for testing::Test'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o:(.data.rel.ro._ZTV19Intent_IsValid_Test[_ZTV19Intent_IsValid_Test]+0x20): undefined reference to `testing::Test::SetUp()'
CMakeFiles/intent_tests.dir/intent_tests.cpp.o:(.data.rel.ro._ZTV19Intent_IsValid_Test[_ZTV19Intent_IsValid_Test]+0x28): undefined reference to `testing::Test::TearDown()'
collect2: error: ld returned 1 exit status
tests/anbox/android/CMakeFiles/intent_tests.dir/build.make:124: recipe for target 'tests/anbox/android/intent_tests' failed
make[2]: *** [tests/anbox/android/intent_tests] Error 1
CMakeFiles/Makefile2:1877: recipe for target 'tests/anbox/android/CMakeFiles/intent_tests.dir/all' failed
make[1]: *** [tests/anbox/android/CMakeFiles/intent_tests.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error `

**Comment by stealthgun** [comment]
I have the excact same issue a work aroud is:

I found that with GCC 10+ the tests break so what you can do is after step 2 is do
code:
` nano -w CMakeLists.txt`

And then Comment line 141
`#add_subdirectory(tests)`

I think Anbox at the moment is not compatible with every gcc

Can you do
`gcc --version`

and post the outcome?
Mine is
```
gcc (Gentoo 10.2.0-r5 p6) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by soviet1942** [comment]
same issue on ubuntu, both amdx86_64 and arm64

**Comment by ruoyu2000** [comment]
I have the same issue on Linux Mint 20.1.

**Comment by johnsunxu** [comment]
> Can you do
> `gcc --version`
> 
> and post the outcome?
My output is this. 
```gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.```

**Comment by ruoyu2000** [comment]
> > Can you do
> > `gcc --version`
> > and post the outcome?
> > My output is this.
> 
> ```
> Copyright (C) 2017 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.```
> ```

gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by liuson945** [comment]
卡在百分之90的是缺少依赖你可以试试：sudo apt install build-essential cmake cmake-data debhelper dbus google-mock \
 libboost-thread-dev libcap-dev libexpat1-dev libsystemd-dev libegl1-mesa-dev \
 libgles2-mesa-dev libglm-dev libgtest-dev liblxc1 \
 libproperties-cpp-dev libprotobuf-dev libsdl2-dev libsdl2-image-dev lxc-dev \
 pkg-config protobuf-compiler python3-minimal cmake-extras libelf-dev libdwarf-dev
 pkg-config protobuf-compiler python3-minimal cmake-extras libelf-dev libdwarf-dev binutils-dev libdw-dev

**Comment by lzyang1985** [comment]
> 卡在百分之90的是缺少依赖你可以试试：sudo apt install build-essential cmake cmake-data debhelper dbus google-mock
> libboost-thread-dev libcap-dev libexpat1-dev libsystemd-dev libegl1-mesa-dev
> libgles2-mesa-dev libglm-dev libgtest-dev liblxc1
> libproperties-cpp-dev libprotobuf-dev libsdl2-dev libsdl2-image-dev lxc-dev
> pkg-config protobuf-compiler python3-minimal cmake-extras libelf-dev libdwarf-dev
> pkg-config protobuf-compiler python3-minimal cmake-extras libelf-dev libdwarf-dev binutils-dev libdw-dev



It's done. Thank you.
