### ISSUE TITLE
cannot start anbox WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement

### ISSUE THREAD

**Issue by 4joey1** [anbox/anbox#1780]
[anbox-system-diagnostics-2021-03-30.zip](https://github.com/anbox/anbox/files/6231670/anbox-system-diagnostics-2021-03-30.zip)
[anbox-system-diagnostics-2021-03-30.zip](https://github.com/anbox/anbox/files/6231673/anbox-system-diagnostics-2021-03-30.zip)

I was able to start anbox but when I updated my debian bullyseye/sid today,when I start anbox as below I get messages shown

```
$ anbox.appmgr
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
[ 2021-03-30 19:14:30] [launch.cpp:168@operator()] Session manager is not yet running, trying to start it
[ 2021-03-30 19:14:30] [launch.cpp:117@launch_session_manager] Started session manager, will now try to connect ..
[ 2021-03-30 19:14:30] [splash_screen.cpp:55@SplashScreen] Window has no associated renderer yet, creating one ...
[ 2021-03-30 19:14:35] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name org.anbox was not provided by any .service files
```
Kindly note I also followed steps below to diagnose my problem and for the steps below that I have effected,I have stated "This I have done"

1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. **_Update snap to latest: `snap refresh --devmode --edge anbox`----This I have done_**
3. Make sure you have debug logs enabled:
**_`sudo snap set anbox debug.enable=true` ----This I have done_**
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
**_`sudo /snap/bin/anbox.collect-bug-info ` ----This I have done_**

The tar file is as attached

**Comment by psysteph** [comment]
hello guys i have to probleme mi too..plz helpppp

**Comment by Fuseteam** [comment]
how are you launching anbox?
