### ISSUE TITLE
Segmentation fault (Address not mapped to object [(nil)])

### ISSUE THREAD

**Issue by manohar199** [anbox/anbox#1784]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**

$ anbox.appmgr
[ 2021-04-08 01:40:43] [launch.cpp:182@operator()] Session manager is not yet running, trying to start it
[ 2021-04-08 01:40:43] [launch.cpp:116@launch_session_manager] Started session manager, will now try to connect ..
Stack trace (most recent call last):
#25   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#24   Object "/snap/anbox/186/usr/bin/anbox", at 0x4aa008, in _start
#23   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fd36365083f, in __libc_start_main
#22   Object "/snap/anbox/186/usr/bin/anbox", at 0x4a524e, in main
#21   Object "/snap/anbox/186/usr/bin/anbox", at 0x4bc337, in anbox::Daemon::Run(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
#20   Object "/snap/anbox/186/usr/bin/anbox", at 0x4b153f, in anbox::cli::CommandWithSubcommands::run(anbox::cli::Command::Context const&)
#19   Object "/snap/anbox/186/usr/bin/anbox", at 0x4b1001, in anbox::cli::CommandWithFlagsAndAction::run(anbox::cli::Command::Context const&)
#18   Object "/snap/anbox/186/usr/bin/anbox", at 0x4da37c, in 
#17   Object "/snap/anbox/186/usr/bin/anbox", at 0x52be77, in anbox::ui::SplashScreen::SplashScreen()
#16   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fd364ee83e6, in 
#15   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fd364f810c0, in 
#14   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fd364f9499c, in 
#13   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fd364f933a0, in 
#12   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fd364f82102, in 
#11   Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fd3645dffa0, in dlopen
#10   Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fd3645e0570, in 
#9    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fd365b8c5a3, in 
#8    Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fd3645dff08, in 
#7    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fd365b90de8, in 
#6    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fd365b8c5a3, in 
#5    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fd365b91921, in 
#4    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fd365b8c80a, in 
#3    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fd365b8c6f9, in 
#2    Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3", at 0x7fd35a538408, in 
#1    Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9", at 0x7fd3643bc832, in google::protobuf::internal::OnShutdown(void (*)())
#0    Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9", at 0x7fd3643bc516, in google::protobuf::internal::Mutex::Lock()
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault

[please paste printout of `anbox system-info` here]
```
<pre>nbox system-info
version: 4
snap-revision: 186
cpu:
  arch:  x86
  brand: AMD A8-6410 APU with AMD Radeon R5 Graphics    
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
os:
  name: Ubuntu
  version: 20.04.2 LTS (Focal Fossa)
  snap-based: true
kernel:
  version: Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020
  binder: false
  ashmem: false
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions:
      - n/a
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

**Comment by Glasses8448** [comment]
version: local-ad377ff
snap-revision: 213
cpu:
  arch:  x86
  brand: Intel(R) Celeron(R) CPU N3450 @ 1.10GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
os:
  name: Ubuntu
  version: 20.04.2 LTS (Focal Fossa)
  snap-based: true
kernel:
  version: Linux version 5.8.0-55-generic (buildd@lgw01-amd64-050) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
[anbox-system-diagnostics-2021-06-25.zip](https://github.com/anbox/anbox/files/6716955/anbox-system-diagnostics-2021-06-25.zip)

**Comment by Fuseteam** [comment]
note that both "binder" and "ashmem" should be true or it won't work

**Comment by CauaTheKing** [comment]
> note that both "binder" and "ashmem" should be true or it won't work

What if i already havw both on my pc

**Comment by Fuseteam** [comment]
@CauaTheKing then you have separate issue, what does `anbox session-manager` say?

**Comment by CauaTheKing** [comment]
> @CauaTheKing then you have separate issue, what does `anbox session-manager` say?

This:

```
caua@caua-HP-Stream-Laptop-11-y0XX:~$ anbox session-manager
[ 2021-12-13 17:33:09] [Renderer.cpp:128@initialize] Failed to select EGL configuration
Stack trace (most recent call last) in thread 2582:
#7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f2f519c5292, in clone
#5    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7f2f51d36608, in 
#4    Object "/snap/anbox/213/usr/bin/anbox", at 0x56411d01b314, in emugl::Thread::thread_main(void*)
#3    Object "/snap/anbox/213/usr/bin/anbox", at 0x56411cf27358, in RenderThread::main()
#2    Object "/snap/anbox/213/usr/bin/anbox", at 0x56411d016060, in renderControl_decoder_context_t::decode(void*, unsigned long, IOStream*)
#1    Object "/snap/anbox/213/usr/bin/anbox", at 0x56411cf95562, in 
#0    Object "/snap/anbox/213/usr/bin/anbox", at 0x56411cf98429, in RendererConfigList::getPackInfo(int*, int*) const
Segmentation fault (Address not mapped to object [(nil)])
Falha de segmentação (imagem do núcleo gravada)
```

**Comment by Fuseteam** [comment]
That's basically #1943
