### ISSUE TITLE
Error MAKE anbox - POP-OS 20.04 LTS

### ISSUE THREAD

**Issue by tdp157** [anbox/anbox#1789]
**Please Help me**
**Error create make File ANBOX**:
```
[ 90%] Linking CXX executable intent_tests
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: na função "_start":
(.text+0x24): referência não definida para "main"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "Intent_IsValid_Test::TestBody()":
/home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:26: referência não definida para "testing::Message::Message()"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:26: referência não definida para "testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:26: referência não definida para "testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:26: referência não definida para "testing::internal::AssertHelper::operator=(testing::Message const&) const"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:30: referência não definida para "testing::internal::AssertHelper::~AssertHelper()"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:24: referência não definida para "testing::Message::Message()"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:24: referência não definida para "testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:24: referência não definida para "testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:24: referência não definida para "testing::internal::AssertHelper::operator=(testing::Message const&) const"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:30: referência não definida para "testing::Message::Message()"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:30: referência não definida para "testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:30: referência não definida para "testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:30: referência não definida para "testing::internal::AssertHelper::operator=(testing::Message const&) const"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:28: referência não definida para "testing::Message::Message()"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:28: referência não definida para "testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:28: referência não definida para "testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:28: referência não definida para "testing::internal::AssertHelper::operator=(testing::Message const&) const"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "Intent_IsValid_Test::~Intent_IsValid_Test()":
/home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:22: referência não definida para "testing::Test::~Test()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "Intent_IsValid_Test::~Intent_IsValid_Test()":
/home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:22: referência não definida para "testing::Test::~Test()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "Intent_IsValid_Test::Intent_IsValid_Test()":
/home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:22: referência não definida para "testing::Test::Test()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "Intent_IsValid_Test::TestBody()":
/home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:24: referência não definida para "testing::internal::AssertHelper::~AssertHelper()"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:26: referência não definida para "testing::internal::AssertHelper::~AssertHelper()"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:30: referência não definida para "testing::internal::AssertHelper::~AssertHelper()"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:28: referência não definida para "testing::internal::AssertHelper::~AssertHelper()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "testing::internal::SuiteApiResolver<testing::Test>::GetSetUpCaseOrSuite(char const*, int)":
/usr/include/gtest/internal/gtest-internal.h:516: referência não definida para "testing::internal::GTestLog::~GTestLog()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "testing::internal::SuiteApiResolver<testing::Test>::GetTearDownCaseOrSuite(char const*, int)":
/usr/include/gtest/internal/gtest-internal.h:531: referência não definida para "testing::internal::GTestLog::~GTestLog()"
/usr/bin/ld: /usr/include/gtest/internal/gtest-internal.h:531: referência não definida para "testing::internal::IsTrue(bool)"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "testing::internal::SuiteApiResolver<testing::Test>::GetSetUpCaseOrSuite(char const*, int)":
/usr/include/gtest/internal/gtest-internal.h:516: referência não definida para "testing::internal::IsTrue(bool)"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "_GLOBAL__sub_I_intent_tests.cpp":
/home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:22: referência não definida para "testing::internal::GetTestTypeId()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "__static_initialization_and_destruction_0":
/home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:22: referência não definida para "testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "testing::internal::SuiteApiResolver<testing::Test>::GetSetUpCaseOrSuite(char const*, int)":
/usr/include/gtest/internal/gtest-internal.h:516: referência não definida para "testing::internal::GTestLog::GTestLog(testing::internal::GTestLogSeverity, char const*, int)"
/usr/bin/ld: /usr/include/gtest/internal/gtest-internal.h:516: referência não definida para "testing::internal::GTestLog::~GTestLog()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "testing::internal::SuiteApiResolver<testing::Test>::GetTearDownCaseOrSuite(char const*, int)":
/usr/include/gtest/internal/gtest-internal.h:531: referência não definida para "testing::internal::GTestLog::GTestLog(testing::internal::GTestLogSeverity, char const*, int)"
/usr/bin/ld: /usr/include/gtest/internal/gtest-internal.h:531: referência não definida para "testing::internal::GTestLog::~GTestLog()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o:(.data.rel.ro._ZTI19Intent_IsValid_Test[_ZTI19Intent_IsValid_Test]+0x10): referência não definida para "typeinfo for testing::Test"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o:(.data.rel.ro._ZTV19Intent_IsValid_Test[_ZTV19Intent_IsValid_Test]+0x20): referência não definida para "testing::Test::SetUp()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o:(.data.rel.ro._ZTV19Intent_IsValid_Test[_ZTV19Intent_IsValid_Test]+0x28): referência não definida para "testing::Test::TearDown()"
collect2: error: ld returned 1 exit status
make[2]: *** [tests/anbox/android/CMakeFiles/intent_tests.dir/build.make:110: tests/anbox/android/intent_tests] Erro 1
make[1]: *** [CMakeFiles/Makefile2:1995: tests/anbox/android/CMakeFiles/intent_tests.dir/all] Erro 2
make: *** [Makefile:141: all] Erro 2
```

```
tportugal@pop-os:~/anbox/build$ **gcc --version**
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

```
tportugal@pop-os:~/anbox/build$ uname -a
Linux pop-os 5.11.0-7612-generic #13~1617215757~20.04~97a8d1a-Ubuntu SMP Thu Apr 1 21:15:20 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by StormFeng** [comment]
me to,someone help us please!

**Comment by Andr35** [comment]
I had the same issue on Linux Mint.
The error does not occur if the project is built from commit 41f7df7278d3e8f7f212243f2c2f2ffc90d58eff
```sh
git checkout 41f7df7278d3e8f7f212243f2c2f2ffc90d58eff
```

**Comment by liuson945** [comment]
缺少依赖：sudo apt install build-essential cmake cmake-data debhelper dbus google-mock \libboost-thread-dev libcap-dev libexpat1-dev libsystemd-dev libegl1-mesa-dev \libgles2-mesa-dev libglm-dev libgtest-dev liblxc1 \libproperties-cpp-dev libprotobuf-dev libsdl2-dev libsdl2-image-dev lxc-dev \pkg-config protobuf-compiler python3-minimal cmake-extras libelf-dev libdwarf-devpkg-config protobuf-compiler python3-minimal cmake-extras libelf-dev libdwarf-dev binutils-dev libdw-dev

**Comment by tdp157** [comment]
> libdwarf-devpkg-config

**Comment by tdp157** [comment]
> 缺少依赖：sudo apt install build-essential cmake cmake-data debhelper dbus google-mock \libboost-thread-dev libcap-dev libexpat1-dev libsystemd-dev libegl1-mesa-dev \libgles2-mesa-dev libglm-dev libgtest-dev liblxc1 \libproperties-cpp-dev libprotobuf-dev libsdl2-dev libsdl2-image-dev lxc-dev \pkg-config protobuf-compiler python3-minimal cmake-extras libelf-dev libdwarf-devpkg-config protobuf-compiler python3-minimal cmake-extras libelf-dev libdwarf-dev binutils-dev libdw-dev

tportugal@ac046563:~/anbox/build$ sudo apt install libdwarf-devpkg-config
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
E: Impossível encontrar o pacote libdwarf-devpkg-config

ERROR MAKE: 89%] Linking CXX executable intent_tests
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: na função "_start":
(.text+0x24): referência não definida para "main"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "Intent_IsValid_Test::TestBody()":
/home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:26: referência não definida para "testing::Message::Message()"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:26: referência não definida para "testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:26: referência não definida para "testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:26: referência não definida para "testing::internal::AssertHelper::operator=(testing::Message const&) const"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:30: referência não definida para "testing::internal::AssertHelper::~AssertHelper()"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:24: referência não definida para "testing::Message::Message()"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:24: referência não definida para "testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:24: referência não definida para "testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:24: referência não definida para "testing::internal::AssertHelper::operator=(testing::Message const&) const"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:30: referência não definida para "testing::Message::Message()"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:30: referência não definida para "testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:30: referência não definida para "testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:30: referência não definida para "testing::internal::AssertHelper::operator=(testing::Message const&) const"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:28: referência não definida para "testing::Message::Message()"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:28: referência não definida para "testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:28: referência não definida para "testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:28: referência não definida para "testing::internal::AssertHelper::operator=(testing::Message const&) const"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "Intent_IsValid_Test::~Intent_IsValid_Test()":
/home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:22: referência não definida para "testing::Test::~Test()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "Intent_IsValid_Test::~Intent_IsValid_Test()":
/home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:22: referência não definida para "testing::Test::~Test()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "Intent_IsValid_Test::Intent_IsValid_Test()":
/home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:22: referência não definida para "testing::Test::Test()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "Intent_IsValid_Test::TestBody()":
/home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:24: referência não definida para "testing::internal::AssertHelper::~AssertHelper()"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:26: referência não definida para "testing::internal::AssertHelper::~AssertHelper()"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:30: referência não definida para "testing::internal::AssertHelper::~AssertHelper()"
/usr/bin/ld: /home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:28: referência não definida para "testing::internal::AssertHelper::~AssertHelper()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "testing::internal::SuiteApiResolver<testing::Test>::GetSetUpCaseOrSuite(char const*, int)":
/usr/include/gtest/internal/gtest-internal.h:516: referência não definida para "testing::internal::GTestLog::~GTestLog()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "testing::internal::SuiteApiResolver<testing::Test>::GetTearDownCaseOrSuite(char const*, int)":
/usr/include/gtest/internal/gtest-internal.h:531: referência não definida para "testing::internal::GTestLog::~GTestLog()"
/usr/bin/ld: /usr/include/gtest/internal/gtest-internal.h:531: referência não definida para "testing::internal::IsTrue(bool)"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "testing::internal::SuiteApiResolver<testing::Test>::GetSetUpCaseOrSuite(char const*, int)":
/usr/include/gtest/internal/gtest-internal.h:516: referência não definida para "testing::internal::IsTrue(bool)"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "_GLOBAL__sub_I_intent_tests.cpp":
/home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:22: referência não definida para "testing::internal::GetTestTypeId()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "__static_initialization_and_destruction_0":
/home/tportugal/anbox/tests/anbox/android/intent_tests.cpp:22: referência não definida para "testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "testing::internal::SuiteApiResolver<testing::Test>::GetSetUpCaseOrSuite(char const*, int)":
/usr/include/gtest/internal/gtest-internal.h:516: referência não definida para "testing::internal::GTestLog::GTestLog(testing::internal::GTestLogSeverity, char const*, int)"
/usr/bin/ld: /usr/include/gtest/internal/gtest-internal.h:516: referência não definida para "testing::internal::GTestLog::~GTestLog()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o: na função "testing::internal::SuiteApiResolver<testing::Test>::GetTearDownCaseOrSuite(char const*, int)":
/usr/include/gtest/internal/gtest-internal.h:531: referência não definida para "testing::internal::GTestLog::GTestLog(testing::internal::GTestLogSeverity, char const*, int)"
/usr/bin/ld: /usr/include/gtest/internal/gtest-internal.h:531: referência não definida para "testing::internal::GTestLog::~GTestLog()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o:(.data.rel.ro._ZTI19Intent_IsValid_Test[_ZTI19Intent_IsValid_Test]+0x10): referência não definida para "typeinfo for testing::Test"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o:(.data.rel.ro._ZTV19Intent_IsValid_Test[_ZTV19Intent_IsValid_Test]+0x20): referência não definida para "testing::Test::SetUp()"
/usr/bin/ld: CMakeFiles/intent_tests.dir/intent_tests.cpp.o:(.data.rel.ro._ZTV19Intent_IsValid_Test[_ZTV19Intent_IsValid_Test]+0x28): referência não definida para "testing::Test::TearDown()"
collect2: error: ld returned 1 exit status
make[2]: *** [tests/anbox/android/CMakeFiles/intent_tests.dir/build.make:110: tests/anbox/android/intent_tests] Erro 1
make[1]: *** [CMakeFiles/Makefile2:1995: tests/anbox/android/CMakeFiles/intent_tests.dir/all] Erro 2
make: *** [Makefile:141: all] Erro 2

**Comment by D-EVE-R** [comment]
`sudo apt install build-essential cmake cmake-data cmake-extras debhelper dbus google-mock libboost-dev libboost-filesystem-dev libboost-log-dev libboost-iostreams-dev libboost-program-options-dev libboost-system-dev libboost-test-dev libboost-thread-dev libcap-dev libexpat1-dev libsystemd-dev libegl1-mesa-dev libgles2-mesa-dev libglm-dev libgtest-dev liblxc1 libproperties-cpp-dev libprotobuf-dev libsdl2-dev libsdl2-image-dev lxc-dev pkg-config protobuf-compiler python3-minimal libelf-dev libdwarf-dev pkg-config protobuf-compiler binutils-dev libdw-dev`.

@tdp157 you are trying to install a package name `libdwarf-devpkg-config` which does not exist as you can see from the CML they are 2 packages `libdwarf-dev pkg-config` not 1.

@theo-brown am on LM 20 too and the problem solved by installing some extra dependencies `cmake-extras libelf-dev libdwarf-dev pkg-config protobuf-compiler python3-minimal binutils-dev libdw-dev` which are not mentioned in the requirements.

**Comment by ray-pH** [comment]
You can download [FindGmock.cmake](https://github.com/anbox/anbox/blob/77877519e942554264c69c5adfa4b1aeea58e1d3/cmake/FindGMock.cmake) and put it into `/cmake/FindGmock.cmake`, and it will build normally

The error is because the file `/cmake/FindGmock.cmake` was removed in [#1764 ](https://github.com/anbox/anbox/pull/1764),

> Since we already require cmake-extras to build both docker and snap, lets
use FindGMock from there also.

But that unfortunately breaks the make process when docker isn't being used

**Comment by BenjaminWegener** [comment]
> You can download [FindGmock.cmake](https://github.com/anbox/anbox/blob/77877519e942554264c69c5adfa4b1aeea58e1d3/cmake/FindGMock.cmake) and put it into `/cmake/FindGmock.cmake`, and it will build normally
> 
> The error is because the file `/cmake/FindGmock.cmake` was removed in [#1764 ](https://github.com/anbox/anbox/pull/1764),
> 
> > Since we already require cmake-extras to build both docker and snap, lets
> > use FindGMock from there also.
> 
> But that unfortunately breaks the make process when docker isn't being used

the link isnt correct, use `wget https://raw.githubusercontent.com/anbox/anbox/77877519e942554264c69c5adfa4b1aeea58e1d3/cmake/FindGMock.cmake` inside `anbox/cmake/` dir

**Comment by BruceXSK** [comment]
> > You can download [FindGmock.cmake](https://github.com/anbox/anbox/blob/77877519e942554264c69c5adfa4b1aeea58e1d3/cmake/FindGMock.cmake) and put it into `/cmake/FindGmock.cmake`, and it will build normally
> > The error is because the file `/cmake/FindGmock.cmake` was removed in [#1764 ](https://github.com/anbox/anbox/pull/1764),
> > > Since we already require cmake-extras to build both docker and snap, lets
> > > use FindGMock from there also.
> > 
> > 
> > But that unfortunately breaks the make process when docker isn't being used
> 
> for commandline users: use `wget https://raw.githubusercontent.com/anbox/anbox/77877519e942554264c69c5adfa4b1aeea58e1d3/cmake/FindGMock.cmake` inside `anbox/cmake/` dir

Thanks, it works for me
