### ISSUE TITLE
prebuilt Android image?

### ISSUE THREAD

**Issue by davidelang** [anbox/anbox#179]
I spent 8+ hours downloading the Android source and ran out of space (at 38GB downloaded)

Is it possible to host a pre-built Android image rather than requiring that everyone download and compile it themselves?

**Comment by morphis** [comment]
Sure and we already do that. Have a look at https://github.com/anbox/anbox/blob/master/snapcraft.yaml#L24

The file is available at http://build.anbox.io/android-images/2017/04/12/android_1_amd64.img

**Comment by davidelang** [comment]
Please add this to the readme or the runtime setup docs, they only talk about 
building your own.

k

**Comment by TiberiumN** [comment]
@morphis why the process of downloading this file is SO slow?

**Comment by TiberiumN** [comment]
@morphis 50kb/sec

**Comment by hub2git** [comment]
@TiberiumN that was my experience too in downloading
http://build.anbox.io/android-images/2017/04/12/android_1_amd64.img

**Comment by TiberiumN** [comment]
@hub2git maybe they should add some mirrors (or use some CDN)
@morphis can you please host this file on some CDN for faster downloading?

**Comment by hub2git** [comment]
@TiberiumN yes, hosting on a faster mirror would be good. I tried uploading
the android.img to my forked anbox repository but github's max file size is
25MB.

**Comment by TiberiumN** [comment]
@hub2git you can use github lfs

**Comment by TiberiumN** [comment]
@hug2git ah, probably not. But can you upload it to mega or Google drive please?

**Comment by hub2git** [comment]
* TiberiumN <https://github.com/TiberiumN> *I'm uploading the android.img
to my Mega account, but expected completion time is 2 hours and 50 minutes
from now. Upload speed is a slow 30 KB/s.

**Comment by morphis** [comment]
Why don't you guys simply download the snap from the Ubuntu store? That is the official distribution of Anbox. The image hosted on build.anbox.io is just there for convenience of us developers but not meant for regular users. 

That snap is signed and can be trusted. If you start distributing images through private channels there is no way to trust any of these. Please keep in mind that the Android bits will get some kind of access to your system and your data so you want trust what you execute if you didn't build it yourself.

build.anbox.io is currently hosted on a scaleway server which is located in Frankfurt (DE). Depending on where you are you may get different download speeds.

At a future point we may improve the infrastructure but that is what we have today.

The Ubuntu store uses a proper CDN and you can just download the snap from there and extract the android.img:

```
$ snap download --edge anbox
$ unsquashfs anbox*.snap
```

**Comment by hub2git** [comment]
@TiberiumN, upload is finished. Please try this link:
https://mega.nz/#!hdljXIyD!ZHzpsUxwwNzL6Ou8HNaJRbIHZB8UHxXR2pStXRQslMI

**Comment by TiberiumN** [comment]
@morphis for me downloading speed of image is the same even if using snap

**Comment by Fmstrat** [comment]
Is the above link still the one to use, or https://build.anbox.io/android-images/2018/07/19/android_amd64.img ?

**Comment by DUOLabs333** [comment]
Just my two cents, for arm64 at least, you may be able to use the `system.img` and `ramdisk.img` provided for Pixel phones (they provide direct downloads) and call `create-package.sh` with that. For amd64, I believe they provide it in their emulator kit (again, available to download), but I'm not sure how much different is it from pure compiled AOSP.
