### ISSUE TITLE
andbox snapcraft error:Failed to load plugin: properties failed to load for lxc: Additional properties are not allowed ('autotools-configure-parameters' was unexpected)

### ISSUE THREAD

**Issue by leidamingdavid** [anbox/anbox#1791]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**

/anbox$ anbox info
Unknown command 'info'
NAME:
    anbox - anbox

USAGE:
    anbox [command options] [arguments...]

COMMANDS:
    wait-ready                     Wait until the Android system has successfully booted                                               
    check-features                 Check that the host system supports all necessary features                                          
    version                        Print the version of the daemon                                                                     
    help                           Print a short help message                                                                          
    launch                         Launch an Activity by sending an intent                                                             
    session-manager                Run the the anbox session manager                                                                   
    system-info                    Print various information about the system we're running on  
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
@Vostro-3671:~/anbox$ anbox system-info
version: local-9de4e87
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 18.04.5 LTS (Bionic Beaver)
  snap-based: false
kernel:
  version: Linux version 5.4.0-70-generic (buildd@lgw01-amd64-039) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #78~18.04.1-Ubuntu SMP Sat Mar 20 14:10:07 UTC 2021
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions:
      - n/a
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

**Please describe your problem:**

snapcraft error: 

~/anbox$ snapcraft
Failed to load plugin: properties failed to load for lxc: Additional properties are not allowed ('autotools-configure-parameters' was unex

**What were you expecting?:**

**Additional info:**

**Comment by crazy-shawn-liu** [comment]
I have the same problem

**Comment by Fuseteam** [comment]
i don't get it are you guys trying to build the snap?
