### ISSUE TITLE
Emulate ashmem and binder

### ISSUE THREAD

**Issue by jackghg** [anbox/anbox#1807]
The most annoying thing to run anbox is the need of the ashmem and binder kernel modules. Why not to emulate them ?
Emulate in anbox or in snap may be ?

**Comment by Fuseteam** [comment]
because anbox is not an emulator, it makes use of lxc containers not a virtual machine

**Comment by jackghg** [comment]
oh sorry I used the forbidden word! But when using android arm, it emulates the kernel ?
Maybe only the modules could be emulated ? would be much better and easyer.

**Comment by Fuseteam** [comment]
@jackghg anbox isn't emulating anything at all. arm binaries do not work on anbox on top of x86. if you can "emulate" the kernel modules on top of your kernel and make it available to your system anbox would just work too

in short anbox is not emulating anything, its just making use of what is available on the host

**Comment by jackghg** [comment]
Well maybe it should... you could make a version where it emulates the kernel and/or hardware... would be much more compatible and safer! Plus I heard rumors that some app detects anbox and stop working (not for a bug).

**Comment by Fuseteam** [comment]
@jackghg that's called a virtual machine, you can already do that with kvm and android-x86

**Comment by yurenchen000** [comment]
maybe @jackghg means the possibility to implement / emulate it in user space,
to get rid of the dependence of kernel module.

**Comment by Fuseteam** [comment]
@yurenchen000 it comes down to virtual machine really, its a kernel module that android requires which is related to memory and hardware, you know kernel stuff. it's not a dependency of anbox, its a dependency of an android. if you're gonna do kernel stuff in userspace you're better off doing it with kvm(kernel virtual machine). even android itself uses a light weight virtual machine to handle kernel stuff in the userspace on android devices

**Comment by jackghg** [comment]
great! lets do this kvm!

**Comment by Fuseteam** [comment]
@jackghg checkout the android-x86 project then, they have instructions on setting up a kvm with android-x86

**Comment by jackghg** [comment]
Ok anbox is perfect but 2 problems remains: 
1 its complex to set up those modules
2 weak isolation

**Comment by Fuseteam** [comment]
1. those modules are shipped in the default debian and ubuntu kernel's these days you don't need to set them up at all on those distros or distros based on them unless they explicitely turned it off
2 no idea what you mean with that, android is run in an lxc container isolated from the rest of the system, unless you mean the snap; which indeed needs work still
