### ISSUE TITLE
binder or ashmem kernel drivers are not loaded

### ISSUE THREAD

**Issue by zielony12** [anbox/anbox#1808]
```
$ anbox session-manager
```

```
[ 2021-05-10 14:11:21] [session_manager.cpp:149@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded
```
how to install binder and ashmem on Linux Generic 5.12?

**Comment by sevu** [comment]
By installing a Linux kernel for which these two modules were compiled as well. Many are compiled without them.
Maybe there is a kernel in your distribution which has them. I. e. the default Auch Linux kernel is compiled without them, but the one from the Zen package has them enabled specifically for Anbox.

**Comment by zielony12** [comment]
@sevu so.. should i install Linux Zen?

**Comment by jackghg** [comment]
Does arch have a package containing these mod, so one dont need the zen kernel ?

**Comment by kebugcheckex** [comment]
> Does arch have a package containing these mod, so one dont need the zen kernel ?

@jackghg  Arch does have a package [`linux-zen`](https://archlinux.org/packages/extra/x86_64/linux-zen/) for the zen kernel. However, you'll still need to install and boot from the zen kernel. It is not possible to simply install a package on standard kernel to make things work.

**Comment by jackghg** [comment]
> 
> 
> > Does arch have a package containing these mod, so one dont need the zen kernel ?
> 
> @jackghg Arch does have a package [`linux-zen`](https://archlinux.org/packages/extra/x86_64/linux-zen/) for the zen kernel. However, you'll still need to install and boot from the zen kernel. It is not possible to simply install a package on standard kernel to make things work.

I dont want to use the zen kernel normally.
Maybe a kernel module ?

**Comment by kebugcheckex** [comment]
[Arch Linux wiki](https://wiki.archlinux.org/title/Anbox) says DKMS no longer works on kernel >= 5.7. It didn't say why though. That means you'll have to statically build those modules into the kernel.
