### ISSUE TITLE
How do I enable rootfs-overlay when I have not installed the snap

### ISSUE THREAD

**Issue by saligari** [anbox/anbox#1809]
**Please describe your problem:**

Anbox says that "location storage not configured" and I cannot access a filesystem with the android apps. I would like to be able to have that ability to send a few files to the anbox apps.

**What were you expecting?:**

In the anbox docs there is only info on enabling rootfs-overlay when using anbox via snap, how to enable rootfs-overlay when I don't have it as a snap?

**Comment by farmerbobathan** [comment]
By using the `--use-rootfs-overlay` argument in the container manager.
