### ISSUE TITLE
Navigation buttons

### ISSUE THREAD

**Issue by rx112358** [anbox/anbox#1815]
Any way to Enable Native Navigation Keys or add a Back Button in Anbox?

**Comment by swwind** [comment]
Maybe you can press Esc as the back button

**Comment by rx112358** [comment]
Testing certain apps would require more than a back button. So enabling navigation keys ( next,back,home ) would be a good addition.

**Comment by ChristophSchmidpeter** [comment]
Related issue (only discussing adding a back button): #331
