### ISSUE TITLE
Unable to Launch Anbox on Fedora 34

### ISSUE THREAD

**Issue by Happy-Kunal** [anbox/anbox#1819]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
####-> No Similar Bug Found (For Fedora 34)

2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
####-> Installed Today via "sudo snap install anbox --beta --devmode"

3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
####-> Enabled 

4. Reproduce the error while debug logs enabled.

[KunalSharma@fedora ~]$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
[ 2021-05-27 04:37:01] [launch.cpp:182@operator()] Session manager is not yet running, trying to start it
[ 2021-05-27 04:37:01] [launch.cpp:116@launch_session_manager] Started session manager, will now try to connect ..
libGL error: pci id for fd 7: 1002:15d8, driver (null)
libGL error: No driver found
libGL error: failed to load driver: (null)
[ 2021-05-27 04:37:01] [splash_screen.cpp:56@SplashScreen] Window has no associated renderer yet, creating one ...
[ 2021-05-27 04:37:51] [daemon.cpp:61@Run] Application manager service is not running yet

5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `
[anbox-system-diagnostics-2021-05-27.zip](https://github.com/anbox/anbox/files/6551149/anbox-system-diagnostics-2021-05-27.zip)

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[KunalSharma@fedora ~]$ anbox system-info
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
pci id for fd 5: 1002:15d8, driver (null)
version: 4
snap-revision: 186
cpu:
  arch:  x86
  brand: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Fedora
  version: 34 (Workstation Edition)
  snap-based: true
kernel:
  version: Linux version 5.11.21-300.fc34.x86_64 (mockbuild@bkernel01.iad2.fedoraproject.org) (gcc (GCC) 11.1.1 20210428 (Red Hat 11.1.1-1), GNU ld version 2.35.1-41.fc34) #1 SMP Fri May 14 17:43:38 UTC 2021
  binder: false
  ashmem: false
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_context_flush_control
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image_base
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES 3.0 Mesa 18.0.5
    extensions:
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_read_format_bgra
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
[KunalSharma@fedora ~]$ 

```
</details>

**Please describe your problem:**
###Today i installed anbox while i was launching it via gui its screen comes but only android like icon is visible and after some time it terminates itself then i tried to launch it via terminal still the same problem
![image](https://user-images.githubusercontent.com/67647806/119767805-33b8e980-bed5-11eb-9660-9df1192f80e0.png)

**What were you expecting?:**
###I was expecting that anbox should launch properly and can run my .apk files on my pc

**Additional info:**

**Comment by maxreuben** [comment]
I face the same issue on the same OS.

**Comment by TimInLasVegas** [comment]
I saw this issue and decided to test it for myself on a Fedora34 install on a Intel i7 desktop x86_64. At first I had a SELinux issue pop up on SELinux Troubleshooter and then I resolved that. Now it just launches an icon for a moment and then crashes as above.

I'll be looking into the issue deeper and see if I can get some good information on what's happening here. It seems that every Fedora system I can get my hands on his having the same issue.

**Comment by TimInLasVegas** [comment]
> 1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
>    ####-> No Similar Bug Found (For Fedora 34)
> 2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
>    ####-> Installed Today via "sudo snap install anbox --beta --devmode"
> 3. Make sure you have debug logs enabled:
>    `sudo snap set anbox debug.enable=true`
>    ####-> Enabled
> 4. Reproduce the error while debug logs enabled.
> 
> [KunalSharma@fedora ~]$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
> WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
> [ 2021-05-27 04:37:01] [launch.cpp:182@operator()] Session manager is not yet running, trying to start it
> [ 2021-05-27 04:37:01] [launch.cpp:116@launch_session_manager] Started session manager, will now try to connect ..
> libGL error: pci id for fd 7: 1002:15d8, driver (null)
> libGL error: No driver found
> libGL error: failed to load driver: (null)
> [ 2021-05-27 04:37:01] [splash_screen.cpp:56@SplashScreen] Window has no associated renderer yet, creating one ...
> [ 2021-05-27 04:37:51] [daemon.cpp:61@Run] Application manager service is not running yet
> 
> 1. Run the anbox logs collection utility and attach the tar file.
>    `sudo /snap/bin/anbox.collect-bug-info `
>    [anbox-system-diagnostics-2021-05-27.zip](https://github.com/anbox/anbox/files/6551149/anbox-system-diagnostics-2021-05-27.zip)
> 2. ** Please paste the result of `anbox system-info` below:**
> 
> anbox system-info output
> **Please describe your problem:**
> ###Today i installed anbox while i was launching it via gui its screen comes but only android like icon is visible and after some time it terminates itself then i tried to launch it via terminal still the same problem
> ![image](https://user-images.githubusercontent.com/67647806/119767805-33b8e980-bed5-11eb-9660-9df1192f80e0.png)
> 
> **What were you expecting?:**
> ###I was expecting that anbox should launch properly and can run my .apk files on my pc
> 
> **Additional info:**

Are you running Wayland or X11? ( echo $XDG_SESSION_TYPE )

Mine failed while in X11 and I'm wondering if the window manager might have something to do with it.

**Comment by maxreuben** [comment]
I'm running Wayland. I'm not able to install it even.

**Comment by Happy-Kunal** [comment]
> > 1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
> >    ####-> No Similar Bug Found (For Fedora 34)
> > 2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
> >    ####-> Installed Today via "sudo snap install anbox --beta --devmode"
> > 3. Make sure you have debug logs enabled:
> >    `sudo snap set anbox debug.enable=true`
> >    ####-> Enabled
> > 4. Reproduce the error while debug logs enabled.
> > 
> > [KunalSharma@fedora ~]$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
> > WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
> > [ 2021-05-27 04:37:01] [launch.cpp:182@operator()] Session manager is not yet running, trying to start it
> > [ 2021-05-27 04:37:01] [launch.cpp:116@launch_session_manager] Started session manager, will now try to connect ..
> > libGL error: pci id for fd 7: 1002:15d8, driver (null)
> > libGL error: No driver found
> > libGL error: failed to load driver: (null)
> > [ 2021-05-27 04:37:01] [splash_screen.cpp:56@SplashScreen] Window has no associated renderer yet, creating one ...
> > [ 2021-05-27 04:37:51] [daemon.cpp:61@Run] Application manager service is not running yet
> > 
> > 1. Run the anbox logs collection utility and attach the tar file.
> >    `sudo /snap/bin/anbox.collect-bug-info `
> >    [anbox-system-diagnostics-2021-05-27.zip](https://github.com/anbox/anbox/files/6551149/anbox-system-diagnostics-2021-05-27.zip)
> > 2. ** Please paste the result of `anbox system-info` below:**
> > 
> > anbox system-info output
> > **Please describe your problem:**
> > ###Today i installed anbox while i was launching it via gui its screen comes but only android like icon is visible and after some time it terminates itself then i tried to launch it via terminal still the same problem
> > ![image](https://user-images.githubusercontent.com/67647806/119767805-33b8e980-bed5-11eb-9660-9df1192f80e0.png)
> > **What were you expecting?:**
> > ###I was expecting that anbox should launch properly and can run my .apk files on my pc
> > **Additional info:**
> 
> Are you running Wayland or X11? ( echo $XDG_SESSION_TYPE )
> 
> Mine failed while in X11 and I'm wondering if the window manager might have something to do with it.


I am running Wayland.

**Comment by Happy-Kunal** [comment]
> I'm running Wayland. I'm not able to install it even.

**Did you followed steps mentioned in https://snapcraft.io/install/anbox/fedora ?**
Because I followed the above link to install mine.

**Comment by maxreuben** [comment]
Yes, I'm able to install it.

**Comment by NyllRE** [comment]
this issue still persists with me
