### ISSUE TITLE
sudo anbox session-manager failed to initialize SDL: No available video device

### ISSUE THREAD

**Issue by kidfrom** [anbox/anbox#1833]
<details>
<summary>anbox system-info output</summary>

```
root@ubuntu-1cpu-1gb-sg-sin1:~# sudo anbox system-info
pci id for fd 3: 1234:1111, driver (null)
MESA-LOADER: failed to open bochs-drm (search paths /snap/anbox/213/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: bochs-drm
version: local-ad377ff
snap-revision: 213
cpu:
  arch:  x86
  brand: AMD EPYC 7542 32-Core Processor                
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 20.04.2 LTS (Focal Fossa)
  snap-based: true
kernel:
  version: Linux version 5.8.0-50-generic (buildd@lgw01-amd64-030) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_EXT_buffer_age
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```
</details>

**Please describe your problem:**

I can not run `sudo anbox session-manager`. I host the Ubuntu 20.04 on UpCloud. I installed the GUI XFCE4 and then install the anbox. But, I can't find the `Anbox` in the Application Finder. I am assuming `sudo anbox session-manager` equals to clicking the `Anbox` in the Application Finder.

**What were you expecting?:**

Can run `sudo anbox session-manager`.

**Additional info:**

I change the OS to Ubuntu 18 and install the kernel manually. The binder is not set to false anymore. However, it throws "segmentation error" after running "sudo anbox session-manager".

Updating it to the latest/edge version and running the "sudo anbox session-manager" will throws "No available video device".

**Comment by kidfrom** [comment]
I change the OS to Ubuntu 18 and install the kernel manually. The binder is not set to false anymore. However, it throws "segmentation error" after running "sudo anbox session-manager".

Updating it to the latest/edge version and running the "sudo anbox session-manager" will throws "No available video device".

**Comment by sevu** [comment]
That command should be run as the regular user. Does that resolve it?
