### ISSUE TITLE
Is an app only compiled for arm architecture executable through anbox?

### ISSUE THREAD

**Issue by jjangga0214** [anbox/anbox#1847]
Hi!

Is an app only compiled for arm architecture executable through anbox?

Thanks.

_P.S. Sorry if a question is not suitable as an issue._

**Comment by patrakov** [comment]
You would need to create a custom Android image for that. Arch Linux includes a [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=anbox-image-houdini), but on other distributions you would have to unpack the provided image, add Houdini, and repack it again, manually.

In other words: if you have enough skills, you can follow the build() function from the PKGBUILD manually. If not, then this functionality is not available.

**Comment by Fuseteam** [comment]
uh no only apps compiled for your architecture, the architecture of the computer you're running anbox on, is executable
