### ISSUE TITLE
Newer version of android? like android 10 

### ISSUE THREAD

**Issue by vidux** [anbox/anbox#1849]
Hi , I thank you deep in my heart for for this awesome software.  I just tried to install some apps  by using play store, but some apps not visible in play store listing. I think the issue is incompatible of OS version.. any plans to upgrade inner OS? or is there any way to upgrade OS ourselves ?  Thank You again.

**Comment by TheBricktop** [comment]
As far as I know there is a way to build the AOSP android yourself using the provided method

**Comment by rzr** [comment]
It looks like related project waydroid uses recent LinageOS on android 10 hope both will align somehow and avoid duplication of effort.

**Comment by Fuseteam** [comment]
waydroid is a different approach to android in an lxc container, the main blocker to updating to android 10 is breaking changes android makes, making anbox incompatible. someone should adapt anbox and fix the issues that arise when updating to android 10

**Comment by TheBricktop** [comment]
> 
> 
> It looks like related project waydroid uses recent LinageOS on android 10 hope both will align somehow and avoid duplication of effort.

thank you for providing me that vital information

**Comment by sevku** [comment]
Got the same question. :) Are there any resources available for an Android Verson upgrade in the near future?

**Comment by Fuseteam** [comment]
anbox is a project not a company, it very much depends on the volunteers that are able to do the upgrade

**Comment by kebugcheckex** [comment]
> the main blocker to updating to android 10 is breaking changes android makes, making anbox incompatible. someone should adapt anbox and fix the issues that arise when updating to android 10

Are there any discussions/documentations on the general procedures of building newer versions of Android, or what are the incompatible issues? I assume simply bumping the version number in the platform_manifest won't work.

**Comment by sevku** [comment]
> > the main blocker to updating to android 10 is breaking changes android makes, making anbox incompatible. someone should adapt anbox and fix the issues that arise when updating to android 10
> 
> Are there any discussions/documentations on the general procedures of building newer versions of Android, or what are the incompatible issues? I assume simply bumping the version number in the platform_manifest won't work.

I doubt it's simple enough to put it in a reusable documentation. It's (probably) different for every version.

**Comment by Fuseteam** [comment]
this repo does contain some docs fwiw: https://github.com/anbox/anbox/blob/master/docs/build-android.md

**Comment by zhouziyang** [comment]
Try https://github.com/remote-android
It supports modern Android (12 / 11 / 10 / 9 / 8.1 currently), with `arm` and `x86` supported.
You can boot many instances at the same time.

**Comment by TheBricktop** [comment]
Whoa, that looks really cool.

**Comment by zhouziyang** [comment]
yes, it works on `arm64` server by native (instead of via native bridge)
