### ISSUE TITLE
Requires integration partnership

### ISSUE THREAD

**Issue by PMatThunderData** [anbox/anbox#1862]
Hi,

This is Thunder Data Co. Ltd.
We are looking for a solution that can run Android application on Raspberry Pi 4 Model B (with ArchLinux system), these Android application includes some streaming music and streaming video such as: Tidal Music, Amazon Music, Qobuz Music, KKBox, YouTube Music, YouTube, Netflix, ..., and so on. And we need to use our mobile application to connect to this Raspberry Pi 4 Model B and use the interface of these Android application running on Raspberry Pi 4 Model B.

We plan to integrate this to our product. please check out our web site: http://www.silent-angel-audio.com/

Could we discuss if Anbox can provide this kind of solution for us?
Thank you!

**Comment by lnee94** [comment]
I think the best way to go 
.a anbox-cloud
.b xdotool and some shell scripts

**Comment by Fuseteam** [comment]
anbox is running running the regular android apps, to interface with it would be like trying to interface from one android phone to another if i understand correctly
