### ISSUE TITLE
Grammar mistake in documentation

### ISSUE THREAD

**Issue by LeiAdair** [anbox/anbox#1884]
https://docs.anbox.io/userguide/install.html
`If you didn’t logged into the Ubuntu Store yet, the snap command will ask you to use sudo snap … in order to install the snap:`
Correct version would be:
`If you haven’t logged into the Ubuntu Store yet, the snap command will ask you to use sudo snap … in order to install the snap:`

**Comment by Fuseteam** [comment]
this feels like spot the difference lol

iirc the source for that text is at https://github.com/anbox/anbox/blob/master/docs/install.md feel free to file an pull request
