### ISSUE TITLE
not opening

### ISSUE THREAD

**Issue by TypeHrishi** [anbox/anbox#1890]
**Please describe your problem:**
it stays on the staring screen for 20-30 second
then it gets closed

I use ubuntu 21.04

**What were you expecting?:**
it should open 

**Additional info:**
nothing

**Comment by Fuseteam** [comment]
can you run `anbox session-manager` and post the output? please surround it with three ` on both side so that it can be more readable

**Comment by TypeHrishi** [comment]
![image](https://user-images.githubusercontent.com/88428357/130755399-6d1f8d96-7faf-4e6e-b736-3fa1da6a3c26.png)
It shows this

**Comment by rounk-ctrl** [comment]
> but i see different error here

did you do 
```sudo modprobe ashmem_linux
sudo modprobe binder_linux```

**Comment by Fuseteam** [comment]
@TypeHrishi can you run `grep binder /proc/filesystems` and `grep ashmem /proc/misc`?

**Comment by Fuseteam** [comment]
@Key-Snapper bind-address already in use means that the session-manager is already running, can make sure you made no syntax errors?

**Comment by TypeHrishi** [comment]
> @TypeHrishi can you run `grep binder /proc/filesystems` and `grep ashmem /proc/misc`?
`grep binder /proc/filesystems`:
![image](https://user-images.githubusercontent.com/88428357/131261197-ca22f083-afd7-48a0-b14b-5d0ef9e8cba4.png)

`grep ashmem /proc/misc`:
cant see anything, again see the $ sign

**Comment by Kushagra-Srivastava** [comment]
i need help too

**Comment by Fuseteam** [comment]
@Kushagra-Srivastava please don't crosspost i'm not 100% sure this is a duplicate of your issue

**Comment by Kushagra-Srivastava** [comment]
i have the same issue, sir

**Comment by TypeHrishi** [comment]
> @TypeHrishi sounds like ashmem is not loaded, do you have secureboot enabled?

I have secure-boot enabled and cannot disable it,
But when I installed Ubuntu I did that key thing I remember...

**Comment by Fuseteam** [comment]
@TypeHrishi then you'll have to sign it, or ask debian to fix ashmem for secureboot
i don't remember how to sign it atm
@Kushagra-Srivastava then your issue is a duplicate, but given i'm reading multiple issues it becomes confusing to have two conversation with one person about one issue
