### ISSUE TITLE
Play store or another app store

### ISSUE THREAD

**Issue by Kushagra-Srivastava** [anbox/anbox#1893]
so how can i install play store or another application store on anbox?
Version--Ubuntu 20.04 LTS

**Comment by Fuseteam** [comment]
yes you can install playstore and/or f-droid just fine
there is a script floating around to install playstore and for f-droid you can just download the apk file and install it with adb

**Comment by genesis-kbm** [comment]
https://github.com/geeks-r-us/anbox-playstore-installer/
https://www.linuxuprising.com/2018/07/anbox-how-to-install-google-play-store.html

**Comment by Kushagra-Srivastava** [comment]
how can i install fdroid
???

**Comment by Fuseteam** [comment]
download the fdroid apk from fdroid.org and install it with `adb install fdroid.apk` or whatever the fdroid apk filename is

**Comment by Kushagra-Srivastava** [comment]
ok
