### ISSUE TITLE
snap is unusable due to missing files

### ISSUE THREAD

**Issue by raffaem** [anbox/anbox#1895]
I have compiled a vanilla 5.14 kernel with ashmem and binder modules enabled.

I then uninstalled the anbox snap and now I am trying to reinstall it.

But I keep getting this error:

```
$ snap install --devmode --edge anbox
error: cannot perform the following tasks:
- Mount snap "core20" (1081) (snap is unusable due to missing files; contact developer)
```

**Comment by raffaem** [comment]
I'm still getting this error:

```
error: cannot perform the following tasks:
- Mount snap "anbox" (186) (snap is unusable due to missing files; contact developer)
```

can somebody help?

**Comment by raffaem** [comment]
It looks like a problem with snapd and squashfs.

Look at [this topic](https://forum.snapcraft.io/t/cannot-install-snap-file-snap-is-unusable-due-to-missing-files/25719) and [this snapd PR](https://github.com/snapcore/snapd/pull/10567)

**Comment by Fuseteam** [comment]
uh yes core20 is snapd not anbox
