### ISSUE TITLE
ls: cannot access '/dev/binder': No such file or directory

### ISSUE THREAD

**Issue by altilunium** [anbox/anbox#1896]
I haven't installed Anbox yet. But i found a problem while installing kernel modules. My OS is Ubuntu 20.04 LTS.

sudo apt install linux-headers-generic anbox-modules-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package anbox-modules-dkms

sudo modprobe ashmem_linux
sudo modprobe binder_linux
ls -1 /dev/{ashmem,binder}
ls: cannot access '/dev/binder': No such file or directory

"Starting with Ubuntu 19.04 binder and ashmem are now build with the standard Ubuntu kernel (>= 5.0) and you don’t have to install the modules from the PPA anymore."
Can i continue the installation, even though there is no /dev/binder directory on my OS?

**Comment by Fuseteam** [comment]
you do not need to install the modules on ubuntu 20.04 it is shipped by default
you can check with `grep binder /proc/filesystems` and `grep ashmem /proc/misc` if either isn't installed the respective command will not return anything

**Comment by umegbewe** [comment]
> grep binder /proc/filesystems

I am in this same situation, any work around?

**Comment by umegbewe** [comment]
> you do not need to install the modules on ubuntu 20.04 it is shipped by default
> you can check with `grep binder /proc/filesystems` and `grep ashmem /proc/misc` if either isn't installed the respective command will not return anything

I am in this same situation, doesn't return anything. Any work around?

**Comment by Fuseteam** [comment]
@umegbewe do neither of the two commands return anything? what distro are you running?

**Comment by xdien** [comment]
I also had the same problem finding binder
- Distro: gentoo
- Custom kernel: 5.10.61
- Steps have been taken to enable loading binder https://wiki.archlinux.org/title/Anbox
```
scripts/config --module CONFIG_ASHMEM
scripts/config --enable CONFIG_ANDROID
scripts/config --enable CONFIG_ANDROID_BINDER_IPC
scripts/config --enable CONFIG_ANDROID_BINDERFS
scripts/config --set-str CONFIG_ANDROID_BINDER_DEVICES ""
```

Info 
```
$ grep binder /proc/filesystems
nodev binder
$ grep ashmem /proc/misc
60 ashmem
```
i have mount /dev/binderfs
```
ls -l /dev/binderfs/
crw------- 1 root root 249, 0 Sep 12 10:51 binder-control
```

**Comment by Fuseteam** [comment]
eh? only binder-control? hmmmm

**Comment by xdien** [comment]
Yes it only has binder-control.
But I tried CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"
Currently it is:
```
$ ls -l /dev/binderfs/
crw------- 1 root root 249, 1 Sep 13 07:52 binder
crw------- 1 root root 249, 0 Sep 13 07:52 binder-control
crw------- 1 root root 249, 2 Sep 13 07:52 hwbinder
crw------- 1 root root 249, 3 Sep 13 07:52 vndbinder
```

But I can't start
```
$ anbox session-manager
[ 2021-09-13 11:43:26] [client.cpp:48@start] Failed to start container: Failed to start container: Failed to set config item lxc.group.devices.deny
...
```

I tried to find out the problem and build from the source code
change in file src/anbox/container/lxc_container.cpp:346 `lxc.group.devices.deny` to `lxc.cgroup.devices.deny`
but I still can't start, still the error `Failed to start container`
Can you guide me to debug?

**Comment by Fuseteam** [comment]
that sounds like the container-manager is not starting how did you install anbox?

**Comment by xdien** [comment]
I also think the container hasn't started yet. i checked systemctl. i found it to be running and no problem:

```
$ systemctl status anbox-container-manager.service
● anbox-container-manager.service - Anbox Container Manager
      Loaded: loaded (/lib/systemd/system/anbox-container-manager.service; enabled; vendor preset: disabled)
      Active: active (running) since Mon 2021-09-13 07:52:32 +07; 11 hours ago
    Main PID: 406 (anbox)
       Tasks: 9 (limit: 38436)
      Memory: 17.9M
      CGroup: /system.slice/anbox-container-manager.service
              └─406 /usr/bin/anbox container-manager --daemon --data-path=/var/lib/anbox 
```

**Comment by xdien** [comment]
I'll be back in 30 minutes

**Comment by Fuseteam** [comment]
huh it is running but it complaining it's not running? odd :thinking: what else could it be hmm
i would suggest trying to start session-manager with systemd but i'm unsure that will work, i have a working user service here: github.com/fuseteam/systemd-service-files

**Comment by xdien** [comment]
I found that after running the command `anbox session-manager` the modules were loaded and started via `dmesg`
```
[40998.604956] cgroup: cgroup: disabling cgroup2 socket matching due to net_prio or net_cls activation
[40998.621787] anbox0: port 1(vetha97DkL) entered blocking state
[40998.621793] anbox0: port 1(vetha97DkL) entered disabled state
[40998.621931] device vetha97DkL entered promiscuous mode
[40998.622271] anbox0: port 1(vetha97DkL) entered blocking state
[40998.622275] anbox0: port 1(vetha97DkL) entered forwarding state
[40998.622678] anbox0: port 1(vetha97DkL) entered disabled state
[40998.623350] eth0: renamed from vethfxvJDt
[40998.664507] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[40998.664599] IPv6: ADDRCONF(NETDEV_CHANGE): vetha97DkL: link becomes ready
[40998.664749] anbox0: port 1(vetha97DkL) entered blocking state
[40998.664754] anbox0: port 1(vetha97DkL) entered forwarding state
[40998.664973] IPv6: ADDRCONF(NETDEV_CHANGE): anbox0: link becomes ready
[40998.763917] anbox0: port 1(vetha97DkL) entered disabled state
[40998.765227] device vetha97DkL left promiscuous mode
[40998.765233] anbox0: port 1(vetha97DkL) entered disabled state
```

**Comment by Fuseteam** [comment]
oh that's good, it does make the error session-manager gives even more confusing

**Comment by xdien** [comment]
> huh it is running but it complaining it's not running? odd thinking what else could it be hmm
> i would suggest trying to start session-manager with systemd but i'm unsure that will work, i have a working user service here: https://github.com/fuseteam/systemd-service-files

I cannot install from snap. snap doesn't tell me what's wrong with it. In the file anbox-session-manager.service I change `/snap/bin/anbox session-manager` to `/usr/bin/anbox session-manager`
I run it using both systemd and the command line.

**Comment by Fuseteam** [comment]
yes you can adapt that for your needs, tho i don't know what you mean with "snap doesn't tell me what's wrong with it`

**Comment by xdien** [comment]
I installed according to the instructions here https://github.com/anbox/anbox/blob/master/docs/install.md
```
# snap install --devmode --edge anbox
error: cannot perform the following tasks:
- Mount snap "snapd" (12883) (snap is unusable due to missing files; contact developer)
```
And be notified as above. I don't know what to do with it.

**Comment by Fuseteam** [comment]
oh that sounds like an issue with snapd, i feel like i saw this before

**Comment by Fuseteam** [comment]
oh right try `systemctl restart snapd` for that, it might not have been initialized properly

**Comment by xdien** [comment]
Still can't solve the problem here is information from `journalctl -u snapd.service` 
```
Sep 13 19:48:17 localhost.localdomain systemd[1]: Started Snap Daemon.
Sep 13 19:48:17 localhost.localdomain snapd[51072]: api_snaps.go:299: Installing snap "anbox" revision unset
Sep 13 19:48:25 localhost.localdomain snapd[51072]: store_download.go:482: Download size for https://api.snapcraft.io/api/v1/snaps/download/PMrrV4ml8uWuEUDBT8dSGnKUYbevVhc4_12883.snap: 33869824
Sep 13 19:48:49 localhost.localdomain snapd[51072]: container.go:215: in snap "snapd": path "." does not exist
Sep 13 19:48:49 localhost.localdomain snapd[51072]: container.go:215: in snap "snapd": path "meta" does not exist
Sep 13 19:48:49 localhost.localdomain snapd[51072]: container.go:215: in snap "snapd": path "meta/snap.yaml" does not exist
Sep 13 19:48:49 localhost.localdomain snapd[51072]: taskrunner.go:271: [change 9 "Mount snap \"snapd\" (12883)" task] failed: snap is unusable due to missing files; contact developer
Sep 13 19:48:49 localhost.localdomain snapd[51072]: handlers.go:511: Reported install problem for "snapd" as already-reported
```

**Comment by xdien** [comment]
I'm trying to debug it.
I see it running fine but after the line lxc_container.cpp:480 if everything is fine can I see the directory that lxc has mounted at `/var/lib/anbox/rootfs/dev/binder` ? 
![Screenshot from 2021-09-13 20-48-18](https://user-images.githubusercontent.com/3887577/133096124-5d7ade6a-a077-4590-8234-0d5e4e176d1b.png)

**Comment by Fuseteam** [comment]
oh i think i know the solution hold on lemme fetch it

**Comment by Fuseteam** [comment]
try these commands:
```
sudo mount -t binder binder /dev/binderfs
sudo ln -s /dev/binderfs/binder /dev
```

**Comment by xdien** [comment]
1. To make sure I'm doing it right. I changed https://github.com/anbox/anbox/blob/31d584e13d24b1889566ae77e7cabc88e6414ebf/src/anbox/container/lxc_container.cpp#L346 to `lxc.cgroup.devices.deny` is it correct?

2. I have just done with the command line you sent, it still doesn't resolve, should I restart the machine?

**Comment by Fuseteam** [comment]
it __doesn't__ resolve it? eh? weird, did the session-manager error not change at all?
i dunno much about lxc saidly tho

**Comment by xdien** [comment]
I look in the lxc log when container start has the same problem here [Operation not permitted - Failed to mount "(null)" onto "/var/lib/lxc/rootfs/sys/devices/virtual/net"](/lxc/lxc/issues/3964)

Try changing 
https://github.com/anbox/anbox/blob/31d584e13d24b1889566ae77e7cabc88e6414ebf/src/anbox/container/lxc_container.cpp#L339
to
```
set_config_item("lxc.mount.auto", "cgroup:mixed proc:mixed sys:rw");
```
And it worked fine. I'm not sure that change is correct

**Comment by xdien** [comment]
After test run and everything is fine without the /dev/binder interface. But the binder module must be loaded in the kernel!

**Comment by Fuseteam** [comment]
oh interesting
