### ISSUE TITLE
INSTALL_FAILED_NO_MATCHING_ABIS

### ISSUE THREAD

**Issue by altilunium** [anbox/anbox#1897]
adb install com.miHoYo.GenshinImpact_2021-07-09.apk 
adb: failed to install com.miHoYo.GenshinImpact_2021-07-09.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

What should i do?

**Comment by Fuseteam** [comment]
this mean that the apk you downloaded is not made for your cpu architecture, if you're on a desktop this means you'll have to find a x86 version, if such a version exists
