### ISSUE TITLE
Stuck at "Successfully initialized EGL"

### ISSUE THREAD

**Issue by raffaem** [anbox/anbox#1898]
> 1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

#885 is closed and #754 just suggested to update anbox and I did

>2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`

yes I am

> 3. Make sure you have debug logs enabled:
> `sudo snap set anbox debug.enable=true` 

I have

> 4. Reproduce the error while debug logs enabled.

I did

> 5. Run the anbox logs collection utility and attach the tar file.

[anbox-system-diagnostics-2021-09-03.zip](https://github.com/anbox/anbox/files/7106665/anbox-system-diagnostics-2021-09-03.zip)

> 6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
$ anbox system-info
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
version: local-ad377ff
snap-revision: 213
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Fedora
  version: 34 (Workstation Edition)
  snap-based: true
kernel:
  version: Linux version 5.14.0 (raffaele@fedora) (gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1), GNU ld version 2.35.2-5.fc34) #1 SMP Wed Sep 1 10:22:29 CEST 2021
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```
</details>

**Please describe your problem:**

When I try to start `anbox.appmgr ` the window "Starting" is shown, but after that it crashes with the message "The name is not activatable"

**What were you expecting?:**

That the app manager would start

**Additional info:**

```
$ anbox.appmgr 
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
[ 2021-09-03 14:37:10] [launch.cpp:168@operator()] Session manager is not yet running, trying to start it
[ 2021-09-03 14:37:10] [launch.cpp:117@launch_session_manager] Started session manager, will now try to connect ..
[ 2021-09-03 14:37:10] [splash_screen.cpp:55@SplashScreen] Window has no associated renderer yet, creating one ...
[ 2021-09-03 14:38:01] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name is not activatable
```

When I try to start the seesion manager manually:

```
$ anbox session-manager
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
[ 2021-09-03 14:44:59] [daemon.cpp:61@Run] Failed to connect to socket /var/snap/anbox/common/sockets/anbox-container.socket: Connection refused
```

**Comment by Fuseteam** [comment]
try restarting your anbox with `sudo snap disable anbox && sudo snap enable anbox`

**Comment by raffaem** [comment]
> try restarting your anbox with `sudo snap disable anbox && sudo snap enable anbox`

Thanks but it didn't work:

```
$ sudo snap disable anbox && sudo snap enable anbox
anbox disabled
anbox enabled
```

```
$ anbox.appmgr 
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
[ 2021-09-03 17:23:05] [launch.cpp:168@operator()] Session manager is not yet running, trying to start it
[ 2021-09-03 17:23:05] [launch.cpp:117@launch_session_manager] Started session manager, will now try to connect ..
[ 2021-09-03 17:23:06] [splash_screen.cpp:55@SplashScreen] Window has no associated renderer yet, creating one ...
[ 2021-09-03 17:23:56] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name is not activatable
```

**Comment by Fuseteam** [comment]
can you run `anbox session-manager` again? and perhaps `anbox system-info|grep -1 binder`

**Comment by raffaem** [comment]
I was on a kernel without ashmem and binder before (5.13.13). Now I am on a kernel with those modules (5.14).

The output is as follows:
```
$ sudo snap disable anbox && sudo snap enable anbox
[sudo] password for raffaele: 
anbox disabled
anbox enabled
[raffaele@fedora ~]$ anbox session-manager
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
[ 2021-09-03 18:29:04] [Renderer.cpp:128@initialize] Failed to select EGL configuration
Stack trace (most recent call last) in thread 5378:
#7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f143fa48292, in clone
#5    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7f143fdb9608, in 
#4    Object "/snap/anbox/213/usr/bin/anbox", at 0x555cecdc2314, in emugl::Thread::thread_main(void*)
#3    Object "/snap/anbox/213/usr/bin/anbox", at 0x555ceccce358, in RenderThread::main()
#2    Object "/snap/anbox/213/usr/bin/anbox", at 0x555cecdbd060, in renderControl_decoder_context_t::decode(void*, unsigned long, IOStream*)
#1    Object "/snap/anbox/213/usr/bin/anbox", at 0x555cecd3c562, in 
#0    Object "/snap/anbox/213/usr/bin/anbox", at 0x555cecd3f429, in RendererConfigList::getPackInfo(int*, int*) const
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault (core dumped)
```

and

```
$ anbox system-info|grep -1 binder
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
  version: Linux version 5.14.0 (raffaele@fedora) (gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1), GNU ld version 2.35.2-5.fc34) #1 SMP Wed Sep 1 10:22:29 CEST 2021
  binder: false
  ashmem: true
```

**Comment by raffaem** [comment]
I should have binder builtin on this kernel:

![image](https://user-images.githubusercontent.com/54762742/132051463-a53e4a67-e5a8-48aa-a7df-eb510366b661.png)

**Comment by Fuseteam** [comment]
> I was on a kernel without ashmem and binder before (5.13.13). Now I am on a kernel with those modules (5.14).
> 
> The output is as follows:
> 
> ```
> $ sudo snap disable anbox && sudo snap enable anbox
> [sudo] password for raffaele: 
> anbox disabled
> anbox enabled
> [raffaele@fedora ~]$ anbox session-manager
> WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
> [ 2021-09-03 18:29:04] [Renderer.cpp:128@initialize] Failed to select EGL configuration
> Stack trace (most recent call last) in thread 5378:
> #7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
> #6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f143fa48292, in clone
> #5    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7f143fdb9608, in 
> #4    Object "/snap/anbox/213/usr/bin/anbox", at 0x555cecdc2314, in emugl::Thread::thread_main(void*)
> #3    Object "/snap/anbox/213/usr/bin/anbox", at 0x555ceccce358, in RenderThread::main()
> #2    Object "/snap/anbox/213/usr/bin/anbox", at 0x555cecdbd060, in renderControl_decoder_context_t::decode(void*, unsigned long, IOStream*)
> #1    Object "/snap/anbox/213/usr/bin/anbox", at 0x555cecd3c562, in 
> #0    Object "/snap/anbox/213/usr/bin/anbox", at 0x555cecd3f429, in RendererConfigList::getPackInfo(int*, int*) const
> Segmentation fault (Address not mapped to object [(nil)])
> Segmentation fault (core dumped)
> ```
> 
> and
> 
> ```
> $ anbox system-info|grep -1 binder
> WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
>   version: Linux version 5.14.0 (raffaele@fedora) (gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1), GNU ld version 2.35.2-5.fc34) #1 SMP Wed Sep 1 10:22:29 CEST 2021
>   binder: false
>   ashmem: true
> ```

yes this looks better
running `EGL_PLATFORM=x11 anbox session-manager` if you get no output, try launching anbox normally

**Comment by raffaem** [comment]
1. I am now on Wayland. Do I still need x11 as EGL platform?

2. I tried running it and this is the output:
```
$ EGL_PLATFORM=x11 anbox session-manager
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
[ 2021-09-04 17:18:18] [Renderer.cpp:165@initialize] Using a surfaceless EGL context
[ 2021-09-04 17:18:18] [Renderer.cpp:248@initialize] Successfully initialized EGL
```

then it get stuck. There is no further output and the program do not return to the terminal

**Comment by raffaem** [comment]
I have run:

```
sudo mkdir /dev/binderfs
sudo mount -t binder binder /dev/binderfs
ln -s /dev/binderfs/binder /dev/
```

At least now `system-info` shows binder as true:
```
$ anbox system-info|grep -1 binder
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
  version: Linux version 5.14.0 (raffaele@fedora) (gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1), GNU ld version 2.35.2-5.fc34) #1 SMP Wed Sep 1 10:22:29 CEST 2021
  binder: true
  ashmem: true
```

But it still gets stuck here:
```
$ EGL_PLATFORM=x11 anbox session-manager
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
[ 2021-09-04 17:34:22] [Renderer.cpp:165@initialize] Using a surfaceless EGL context
[ 2021-09-04 17:34:22] [Renderer.cpp:248@initialize] Successfully initialized EGL
```

**Comment by raffaem** [comment]
Possibly related #1199

**Comment by Fuseteam** [comment]
hmmm not sure if anbox can work wayland sorry, for wayland https://github.com/waydroid/waydroid might be a better option

**Comment by raffaem** [comment]
> hmmm not sure if anbox can work wayland sorry, for wayland https://github.com/waydroid/waydroid might be a better option

Are there no pans to move it to Wayland?

**Comment by Fuseteam** [comment]
@raffaem no idea the main dev seems extremely busy these days
