### ISSUE TITLE
Anbox does not install with Secure Boot enabled

### ISSUE THREAD

**Issue by userj** [anbox/anbox#19]
Make sure you are running the latest version of Anbox before reporting an issue.

**Anbox release (`anbox version`) and system info (`anbox system-info`):**

Ubuntu 16.04

**Description of the problem:**
During installation, the UEFI secure boot setup appears and asks to continue or disable secure boot. You don't disable secure boot, then the following error occurs:

Anbox cannot install with secure boot enabled:
+ sudo apt install -y anbox-modules-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
anbox-modules-dkms is already the newest version (4~xenial1).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
+ '[' '!' -e /etc/modules-load.d/anbox.conf ']'
+ sudo modprobe binder_linux
modprobe: ERROR: could not insert 'binder_linux': Required key not available

You will not be prompted again to disable secure boot. I'm not sure how to change the setting.

**Expected:**

Be prompted to disable secure boot if required each time, or find a way around secure boot.

**Additional info:**

**Comment by Nbsaw** [comment]
Uninstall it  and reinstall can prompted again to disable secure boot.

But, then the following error occurs yet :joy: 

modprobe: ERROR: could not insert 'binder_linux': Required key not available

**Comment by userj** [comment]
Uninstalling the snap and re-installing did not give me the prompt to disable.

On a fresh install of Ubuntu 17.04, I disabled secure boot and was able to install successfully. It also launches once "anbox session-manager" is running in a terminal.

**Comment by Crisdmc** [comment]
I have the same problem with a fresh install of ubuntu 18.04, can I fix it keeping secure boot enabled?

```
sudo modprobe ashmem_linux
modprobe: ERROR: could not insert 'ashmem_linux': Required key not available
sudo modprobe binder_linux
modprobe: ERROR: could not insert 'binder_linux': Required key not available
```

**Comment by msangel** [comment]
Xubuntu (bionic Ubuntu 18.04.1 LTS) 
same problem here (see the output message above)

**Comment by Sunspawn** [comment]
Anyone have a fix for this?

**Comment by userj** [comment]
I think you have to first disable secure boot manually:
https://askubuntu.com/questions/891248/ubuntu-16-04-how-can-i-disable-secure-boot

**Comment by alexandrebarbaruiva** [comment]
same on ubuntu 18.10
