### ISSUE TITLE
add a script to anbox to make installing of apps esaer (script allredity made)

### ISSUE THREAD

**Issue by lnee94** [anbox/anbox#1903]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>
NA
```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**
so i would like this script to added to the /snap/anbox/current/bin/ of anbox

script title is axdb

#!/bin/bash
adb -s "$(adb devices -l | grep model:Anbox | awk '{print $1}')" $@

**What were you expecting?:**
NA

**Additional info:**
NA

**Comment by Fuseteam** [comment]
maybe make a PR? how is the script different from `adb install name.apk`

**Comment by lnee94** [comment]
if you have muliltable devices

**Comment by lnee94** [comment]
it will use anbox insted of giving you a error

**Comment by Fuseteam** [comment]
ah i see try filing pull request if you know where it should go, the maintainer will take a look at it when he has a chance

**Comment by lnee94** [comment]
it will use anbox instead of giving you a error

**Comment by lnee94** [comment]
where do i put the script then

**Comment by Fuseteam** [comment]
@lnee94 i thought you suggested /snap/anbox/current/bin- oh i misunderstood hmm 🤔

**Comment by Fuseteam** [comment]
i just found this: https://github.com/anbox/anbox/blob/31d584e13d24b1889566ae77e7cabc88e6414ebf/snap/snapcraft.yaml#L220

**Comment by lnee94** [comment]
not where i wont it to go

**Comment by Fuseteam** [comment]
i don't know where you _want_ it to go i simply shared where i found the existing scripts are being included

**Comment by lnee94** [comment]
ok thos are build scripts not bin scripts

**Comment by Fuseteam** [comment]
no @lnee94 those are bin scripts that get shipped with the snap
