### ISSUE TITLE
Install instructions for raspberry pi OS with 64-bit kernel needed

### ISSUE THREAD

**Issue by mgrouch** [anbox/anbox#1905]
Install instructions for raspberry pi OS with 64-bit kernel needed.
It comes with binder and ashmem

```
user@lysmarine:~/slogo $ grep binder /proc/filesystems
nodev	binder
user@lysmarine:~/slogo $ grep ashmem /proc/misc
 61 ashmem

```

How can I run anbox on it? Where can I download it for pi OS?

Thanks,

**Comment by mgrouch** [comment]
I'm trying to follow https://www.raspberrypi.org/forums/viewtopic.php?p=1880314
on latest armhf raspberry pi OS with arm64 bit kernel 

Linux version 5.10.60-v8+ (dom@buildbot) (aarch64-linux-gnu-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld 
(GNU Binutils for Ubuntu) 2.34) #1449 SMP PREEMPT Wed Aug 25 15:01:33 BST 2021

Here are my steps:

`
#!/bin/bash -e

# See: https://www.raspberrypi.org/forums/viewtopic.php?p=1880314

sudo apt install build-essential cmake cmake-data debhelper dbus google-mock \
    libboost-dev libboost-filesystem-dev libboost-log-dev libboost-iostreams-dev \
    libboost-program-options-dev libboost-system-dev libboost-test-dev \
    libboost-thread-dev libcap-dev libexpat1-dev libsystemd-dev libegl1-mesa-dev \
    libgles2-mesa-dev libglm-dev libgtest-dev liblxc1 \
    libproperties-cpp-dev libprotobuf-dev libsdl2-dev libsdl2-image-dev lxc-dev \
    libdw-dev libdwarf-dev binutils-dev \
    pkg-config protobuf-compiler python3-minimal
    
git clone --recurse-submodules -j8  https://github.com/anbox/anbox.git
cd anbox
#git submodule init
git reset --hard 31d584e13d24b1889566ae77e7cabc88e6414ebf
wget -O anbox-patch.zip "https://www.raspberrypi.org/forums/download/file.php?id=47177&sid=6efa5aaef4401f0bc981550e9a3dd499"
unzip anbox-patch.zip
#git apply anbox-patch.diff
git apply anbox-patch-latest.diff

mkdir build
cd build
cmake ..
make

sudo make install

sudo mkdir /var/lib/anbox
wget https://anbox.postmarketos.org/android-7.1.2_r39.1-anbox_armv7a_neon-userdebug.img
sudo cp android-7.1.2_r39.1-anbox_armv7a_neon-userdebug.img /var/lib/anbox/android.img

sudo mkdir /dev/binderfs
sudo mount -t binder binder /dev/binderfs
sudo ./scripts/anbox-bridge.sh start
sudo ANBOX_LOG_LEVEL=debug anbox container-manager --daemon --privileged --data-path=/var/lib/anbox
anbox session-manager --single-window
`

However I get an error:

[ 36%] Building C object external/cpu_features/CMakeFiles/cpu_features.dir/src/cpuinfo_aarch64.c.o
In file included from /home/user/TMP3/anbox/external/cpu_features/src/cpuinfo_aarch64.c:15:
/home/user/TMP3/anbox/external/cpu_features/include/cpuinfo_aarch64.h:67:2: error: #error "Including cpuinfo_aarch64.h from a non-aarch64 target."
 #error "Including cpuinfo_aarch64.h from a non-aarch64 target."
  ^~~~~

Thanks

**Comment by Fuseteam** [comment]
that particular error is due to it not compiling for the right architecture afaict

**Comment by Fuseteam** [comment]
btw someone in the @anbox telegram did manage to install it however when running it they encountered ```[ 2021-08-27 13:09:56] [Renderer.cpp:190@initialize] Failed: Missing egl_image related extension(s)```

**Comment by mgrouch** [comment]
> that particular error is due to it not compiling for the right architecture afaict

processor is arm64, kernel is arm64, 
(kernel has to be arm64 because only that one has binder and ashmem compiled in)

user space programs are armhf
It is building armhf executables (which seems correct to me):

user@lysmarine:~/TMP3/anbox $ file ./build/src/CMakeFiles/anbox-protobuf.dir/anbox_container.pb.cc.o
./build/src/CMakeFiles/anbox-protobuf.dir/anbox_container.pb.cc.o: ELF 32-bit LSB relocatable, ARM, EABI5 version 1 (SYSV), with debug_info, not stripped

**Comment by Fuseteam** [comment]
the error is saying `error: #error "Including cpuinfo_aarch64.h from a non-aarch64 target."` why it is saying that i do not know but afaict it means your not building for the correct architechture that's all i all i know

if i had to guess it has to do with your processor and kernel being arm64 and using space program being armhf
it is trying to include arm64 code while compiling for armhf and thus it is complaining.
i might be because cpuinfo is trying to be build. cpuinfo is a program that checks if your cpu has all the instructions android needs

**Comment by mgrouch** [comment]
> the error is saying `error: #error "Including cpuinfo_aarch64.h from a non-aarch64 target."` why it is saying that i do not know but afaict it means your not building for the correct architechture that's all i all i know
> 
> if i had to guess it has to do with your processor and kernel being arm64 and using space program being armhf
> it is trying to include arm64 code while compiling for armhf and thus it is complaining.
> i might be because cpuinfo is trying to be build. cpuinfo is a program that checks if your cpu has all the instructions android needs

It’s a bug here https://github.com/google/cpu_features/issues/148
