### ISSUE TITLE
compile error, use ... and __VA_ARGS__ instead

### ISSUE THREAD

**Issue by mgrouch** [anbox/anbox#1906]
/opt/vc/include/interface/vcos/vcos_logging.h:234:39: error: ISO C++ does not permit named variadic macros [-Werror=variadic-macros]
 #  define _VCOS_LOG_X(cat, _level, fmt...)   do { if (vcos_is_log_enabled(cat,_level)) vcos_log_impl(cat,_level,fmt); } while (0)
                                       ^~~

**Comment by Fuseteam** [comment]
uh that sounds like an issue with your compiler itself

**Comment by mgrouch** [comment]
No. It doesn't. Compiler is supposed to produce this error.
It's an issue with the code. Look at it. In same file in other places code uses __VA_ARGS__

**Comment by mgrouch** [comment]
it is an issue with the code

**Comment by Fuseteam** [comment]
insisting your view will not resolve it, if you think its an issue with the code, while it is not, then fix the issue and open a PR

again plently of people are compiling abox from souce
