### ISSUE TITLE
ashmem_linux and binder_linux are not compiled with the liquorix kernel

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [anbox/anbox#1910]
I have finally gotten anbox to work using ubuntu's default kernel, but this kernel dosen't have f-sync so I got the liquorix kernel. The problem is that the ashmem_linux and binder_linux are completely missing from the /lib/modules. The generic kernel has these modules, how can I install them to the liquorix kernel so that I don't have to keep switching kernel versions in grub.
also I am using ubuntu 21.04 which means that the ppa to install them won't work, and the INSTALL.sh from the anbox-modules github dosen't work

**Comment by Luciogi** [comment]
Try this https://github.com/Frogging-Family/linux-tkg#Anbox-usage

**Comment by Etaash-mathamsetty** [comment]
I don't think it helped...
ExecStartPre=/sbin/modprobe binder_linux (code=exited, status=1/FAILURE)

**Comment by Etaash-mathamsetty** [comment]
both modules are loaded since they are there in /dev/bindefs and /dev/ashmem (I am using tkg kernel now just in case)

**Comment by clebercasali** [comment]
Anbox used to crash with liquorix kernel up to the 5.13 series, but not anymore.
I'm using '5.14.0-6.4-liquorix-amd64' and it just works.
The modules are already included.

**Comment by Etaash-mathamsetty** [comment]
> Anbox used to crash with liquorix kernel up to the 5.13 series, but not anymore. I'm using '5.14.0-6.4-liquorix-amd64' and it just works. The modules are already included.

you are right
