### ISSUE TITLE
anbox does not support my device

### ISSUE THREAD

**Issue by zhoutianzuo** [anbox/anbox#1914]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox has not been enabled for this device.please consult device maintainer</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:I installed Ubuntu touch on my Meizu Pro5. When I tried to install anbox on the device, it showed that anbox has not been enabled for this device. Please consult device maintainer.

**What were you expecting?:Adapt to my device as soon as possible.

**Additional info:Equipment: Meizu Pro5
                  System version: Ubuntu touch16.04 (W36/2)

eicqfwq@163.com

**Comment by Fuseteam** [comment]
uh this is more appropiate to github.com/ubports/anbox __but__ the ubports community is moving on to supporting android apps on newer devices
