### ISSUE TITLE
Overlay no enabled ! Please check error messages!

### ISSUE THREAD

**Issue by user1123342** [anbox/anbox#1917]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**

<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**
$ ./install-playstore.sh
/var/lib/anbox/rootfs-overlay
Overlay no enabled ! Please check error messages!

**What were you expecting?:**

**Additional info:**

**Comment by user1123342** [comment]
can someone help me pls

**Comment by Fuseteam** [comment]
um not enough information

**Comment by user1123342** [comment]
what information you want
