### ISSUE TITLE
What is the size of Android source code?

### ISSUE THREAD

**Issue by GNUfan42** [anbox/anbox#1919]
I built anbox for aarch64 architecture. However, It seems that there is no prebuilt Android image for aarch64. So I decided to build Android myself from scratch. I have been downloading the code and according to `docs/build-android.md`, "......AOSP recommends at least 100GB of free disk space.", this should only take 100GB of disk space. But after `repo` spent that much of space, it's still downloading and does not seem to stop.

  So how much space do I need exactly?

**Comment by Fuseteam** [comment]
it says __at least__ 100GB for a reason, i have heard of a rt can be over 150GB
