### ISSUE TITLE
Anbox on OpenSuSE Tumbleweed

### ISSUE THREAD

**Issue by MlCHEL1234** [anbox/anbox#1927]
"Anbox is currently only distributed as a snap as snaps makes the life for us developers pretty easy."

It's nice that you think of yourself first. But do you sometimes think about the users? For example, the users of rpm-based systems? I know only very few Linux users who let their system be worked on by X different installers, because in case of errors debugging is almost impossible.

Hence the question, if rpm packages are also planned or if for the users as mentioned above Anbox still remains no alternative.

Bye
Michael

**Comment by Fuseteam** [comment]
after 20 years experience with Linux, you really expect one maintainer to package in the myriads of rpm formats? really? how fun
