### ISSUE TITLE
did not start - linuxmint 18.1

### ISSUE THREAD

**Issue by portuguesehh** [anbox/anbox#193]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the
list of open bugs at https://github.com/anbox/anbox/issues

**Anbox release (`anbox version`) and system info (`anbox system-info`):**

**Description of the problem:**

**Expected:**

**Additional info:**

**Comment by morphis** [comment]
We need more information in order to be able to help you with the problem you're facing. Please describe in detail what you did, which errors you received etc. Closing for now but please reopen with additional information.
