### ISSUE TITLE
segmentation fault when trying to open settings application

### ISSUE THREAD

**Issue by PeterKW** [anbox/anbox#1941]
Seems to often crash when I open the android settings application? Is there anything else that I could try? 
It seems to be running Android 7.7.1? Do I need a newer version of Android to emulate?
```
anbox session-manager                                                                                                        1 ✘ 
Stack trace (most recent call last) in thread 38868:
#12   Object "", at 0xffffffffffffffff, in 
#11   Object "/usr/lib/libc-2.33.so", at 0x7fd4df7d25e2, in __clone
#10   Object "/usr/lib/libpthread-2.33.so", at 0x7fd4dfbf3258, in start_thread
#9    Source "/build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc", line 82, in execute_native_thread_routine [0x7fd4df98e3c3]
#8    Object "/usr/bin/anbox", at 0x55797c785a2d, in anbox::platform::sdl::Platform::process_events()
#7    Object "/usr/lib/libSDL2-2.0.so.0.16.0", at 0x7fd4dfe53d73, in 
#6    Object "/usr/lib/libSDL2-2.0.so.0.16.0", at 0x7fd4dfefc426, in 
#5    Object "/usr/lib/libSDL2-2.0.so.0.16.0", at 0x7fd4dfefab12, in 
#4    Object "/usr/lib/libSDL2-2.0.so.0.16.0", at 0x7fd4dff08b0e, in 
#3    Object "/usr/lib/libSDL2-2.0.so.0.16.0", at 0x7fd4dfe57d17, in 
#2    Object "/usr/lib/libSDL2-2.0.so.0.16.0", at 0x7fd4dfe53ff5, in 
#1    Object "/usr/lib/libSDL2-2.0.so.0.16.0", at 0x7fd4dfe53254, in 
#0    Object "/usr/lib/libSDL2-2.0.so.0.16.0", at 0x7fd4dfefc2c2, in 
Segmentation fault (Address not mapped to object [0x8])
zsh: segmentation fault (core dumped)  anbox session-manager

```

**Comment by Fuseteam** [comment]
you could try to enable debugging mode as described in the template so see if you can get more info on why it is segfaulting

**Comment by Fuseteam** [comment]
the steps in question for debug logs are:


3. Make sure you have debug logs enabled:
sudo snap set anbox debug.enable=true

4. Reproduce the error while debug logs enabled.

5. Run the anbox logs collection utility and attach the tar file.
sudo /snap/bin/anbox.collect-bug-info

**Comment by PeterKW** [comment]
Yeah, I'm not sure how to do that?

![image](https://user-images.githubusercontent.com/13779157/141233987-64f13c54-b374-480b-9c45-96ba7f05d184.png)

I normally run Manjaro Linux so my packages come from their repositories or from the AUR. I haven't come across using snap set before and unfortunately don't know the equivalent?

**Comment by Fuseteam** [comment]
snap set only works if you're using the snap package unfortunately
there's is a way to do that manually but that escapes me atm. i think i saw it in one of the other issues, don't ask me which tho

**Comment by Fuseteam** [comment]
phew sure glad github search works well, and that i remember just enough to search it:
i found someone who managed to do it without snap set here: https://github.com/anbox/anbox/issues/1879#issuecomment-898829906

**Comment by PeterKW** [comment]
ANBOX_LOG_LEVEL=debug
I'm not quite sure how to replicate modifying collect-bug-info.sh?

> after learning that "snap set anbox debug.enable=true" translates to adding ANBOX_LOG_LEVEL=debug to environment, and modifying collect-bug-info.sh to collect from non-snap path's, logs attached
> anbox-system-diagnostics-2021-08-14.zip

**Comment by Fuseteam** [comment]
i guess we'll have to ask @yorambh what his modifications are

**Comment by yorambh** [comment]
I switched to Mobian long ago so I no longer have the file, but it was just some PATH values as far as I remember.

**Comment by Fuseteam** [comment]
guess these lines: https://github.com/anbox/anbox/blob/master/scripts/collect-bug-info.sh#L24-L30
