### ISSUE TITLE
start anbox failed : cannot change profile for the next exec call

### ISSUE THREAD

**Issue by cok3307788** [anbox/anbox#1944]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
no similar report found.

2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
yes , latest. I use 'snap refresh --devmode --beta anbox'

3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
got this:  
$sudo snap set anbox debug.enable=true
error: cannot perform the following tasks:
- Run configure hook of "anbox" snap (run hook "configure": 
-----
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
cannot change profile for the next exec call: No such file or directory
snap-update-ns failed with code 1
-----)

4. Reproduce the error while debug logs enabled.
just like 3. or 6.

5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `
got this : 
$sudo /snap/bin/anbox.collect-bug-info                                                    1 ⨯
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
cannot change profile for the next exec call: No such file or directory
snap-update-ns failed with code 1

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
cannot change profile for the next exec call: No such file or directory
snap-update-ns failed with code 1
```
</details>

**Please describe your problem:**
I have try to use “sudo snap start anbox” or just type "anbox.appmgr" , but anbox can't start.
When I use snap to install anbox , no error report. ashmem and binder is always in /dev. 

**What were you expecting?:**
I hope it can start .

**Additional info:**
no more.

**Comment by Fuseteam** [comment]
what distro is this, it sounds like anbox was not installed correctly

**Comment by cok3307788** [comment]
> what distro is this, it sounds like anbox was not installed correctly

kali-rolling, apt upgrade finished yesterday.

**Comment by Fuseteam** [comment]
hmmm not sure if kali even supports snaps :thinking:

**Comment by cok3307788** [comment]
> hmmm not sure if kali even supports snaps thinking

yes ,you are right. I change to use manjaro ,then work well.
