### ISSUE TITLE
Can't install Anbox on Toshiba T110-10z via Snap

### ISSUE THREAD

**Issue by pro1mantis** [anbox/anbox#1961]
I can't install Anbox via snap. Output is: 

error: cannot perform the following tasks:
- Run install hook of "anbox" snap if present (run hook "install":
-----
WARNING: cgroup v2 is not fully supported yet, proceeding with partial
confinement
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
The CPU of your computer (Genuine Intel(R) CPU           U2700  @
1.30GHz) does not support all
features Anbox requires.
It is missing support for the following features: SSE 4.1, SSE 4.2
You can for example find more information about SSE
here https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions
-----)

I tried with and without sudo, and with edge and with bet, but it's not working.

**Comment by Fuseteam** [comment]
sorry but your answer is buried in the error message:
```
The CPU of your computer (Genuine Intel(R) CPU U2700 @
1.30GHz) does not support all
features Anbox requires.
It is missing support for the following features: SSE 4.1, SSE 4.2
```
long story short; your cpu is too old, sorry

**Comment by pro1mantis** [comment]
Okay. Thanks for helping.
