### ISSUE TITLE
anbox-modules-dkms not found bec can't update from the repository

### ISSUE THREAD

**Issue by villandra** [anbox/anbox#1964]
I tried both adding ppa:morphis/anbox-support and installing software-properties-common.  After adding the repository and when trying to update i got the error message, 

E: The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Then sudo modprobe ashem_linux doesnät work because the  module is not found in -lib-modules-5.4.0-91 because it didn't install because you didn't put the necessary files in the repository.   

I am running Ubuntu 20.04.   

When the ppa won't work without a release file, what is WRONG with you that you don't have a release file.   I don't understand how you could have neglected such a thing.   USELESS.

**Comment by Fuseteam** [comment]
the ppa hasn't been needed since april if 2019, just skip that step
