### ISSUE TITLE
insmod: ERROR: could not insert module binder_linux.ko: Operation not permitted

### ISSUE THREAD

**Issue by Interesting993** [anbox/anbox#1965]
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

# uname -sr
Linux 4.19.165-0419165-generic

# insmod ashmem_linux.ko
insmod: ERROR: could not insert module ashmem_linux.ko: File exists

# ls /dev/ashmem
/dev/ashmem

# insmod binder_linux.ko
insmod: ERROR: could not insert module binder_linux.ko: Operation not permitted

ashmem is successful ， but binder not。How should  solve the problem?

**Comment by Fuseteam** [comment]
> File exists
sounds like it already exists?
