### ISSUE TITLE
anbox failed to launch activity: connection timed out

### ISSUE THREAD

**Issue by CauaTheKing** [anbox/anbox#1967]
anbox failed to launch activity: connection timed out

**Comment by Fuseteam** [comment]
what does `anbox session-manager` say?

**Comment by CauaTheKing** [comment]
> what does `anbox session-manager` say?

It says theres already an open session manager, the error happens with app manager

**Comment by CauaTheKing** [comment]
> what does `anbox session-manager` say?

The error started to happen after i installed google play by following this video https://youtu.be/h9p42kiid9o

**Comment by Fuseteam** [comment]
You did not answer my question tho :x

**Comment by CauaTheKing** [comment]
> what does `anbox session-manager` say?

$ anbox session-manager                                                                                                                                    
[ 2021-12-20 13:18:00] [daemon.cpp:61@Run] bind: Address already in use

**Comment by CauaTheKing** [comment]
> what does `anbox session-manager` say?

Sometimes that happens instead:

$ anbox.appmgr                                                                                                                                                                                                     
[ 2021-12-20 13:20:37] [daemon.cpp:61@Run] Failed to retrieve ready property from application manager

**Comment by Fuseteam** [comment]
cool, so it is actually running like you said, good eye.
how did you install anbox? snap, deb or something else?

**Comment by CauaTheKing** [comment]
> cool, so it is actually running like you said, good eye. how did you install anbox? snap, deb or something else?for some reasonvi could resolve the problem tho im having some connection issues, if i cant resolve it i'll open a new issue e send it here

**Comment by CauaTheKing** [comment]
All done connection issue resolved

**Comment by MichaelKapustey** [comment]
@CauaTheKing, Could you share the way you solved an issue? I have same problem. After installing google play from the tutorial anbox app manager fails to start
