### ISSUE TITLE
Error compiling on Ubuntu 16.04

### ISSUE THREAD

**Issue by tinterking** [anbox/anbox#197]
tinterking@bingo:~/anbox/build$ make
[  3%] Built target GMock
[ 10%] Built target process-cpp
[ 13%] Built target emugen
[ 15%] Built target OpenglCodecCommon
[ 17%] Built target GLESv1_dec
[ 19%] Built target GLESv2_dec
[ 24%] Built target emugl_common
[ 26%] Built target OpenGLESDispatch
[ 29%] Built target renderControl_dec
[ 34%] Built target GLcommon
[ 39%] Built target EGL_translator
[ 41%] Built target GLES_CM_translator
[ 44%] Built target GLES_V2_translator
[ 45%] Built target xdg
[ 46%] Built target xdg_test
[ 49%] Built target anbox-protobuf
[ 50%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/ubuntu/window.cpp.o
/home/tinterking/anbox/src/anbox/ubuntu/window.cpp: In constructor ‘anbox::ubuntu::Window::Window(const std::shared_ptr<Renderer>&, const Id&, const Id&, const std::shared_ptr<anbox::ubuntu::Window::Observer>&, const anbox::graphics::Rect&, const string&, bool)’:
/home/tinterking/anbox/src/anbox/ubuntu/window.cpp:80:107: error: ‘union SDL_SysWMinfo::<anonymous>’ has no member named ‘mir’
 LNativeDisplayType>(mir_connection_get_egl_native_display(info.info.mir.connect
                                                                     ^
/home/tinterking/anbox/src/anbox/ubuntu/window.cpp:81:68: error: ‘union SDL_SysWMinfo::<anonymous>’ has no member named ‘mir’
       auto buffer_stream = mir_surface_get_buffer_stream(info.info.mir.surface)
                                                                    ^
src/CMakeFiles/anbox-core.dir/build.make:2198: recipe for target 'src/CMakeFiles/anbox-core.dir/anbox/ubuntu/window.cpp.o' failed
make[2]: *** [src/CMakeFiles/anbox-core.dir/anbox/ubuntu/window.cpp.o] Error 1
CMakeFiles/Makefile2:2028: recipe for target 'src/CMakeFiles/anbox-core.dir/all' failed
make[1]: *** [src/CMakeFiles/anbox-core.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by morphis** [comment]
Which SDL2 version are you using? Building with `2.0.4+dfsg1-2ubuntu2` from xenial should just work fine.

**Comment by andrew-oko-odion** [comment]
I am having the same issue how was this resolved
