### ISSUE TITLE
I hate Anbox. Here's why...

### ISSUE THREAD

**Issue by qaqak** [anbox/anbox#1976]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**
I tried to install the DKMS modules because Anbox wasn't loading. I get this error
```
Package anbox-modules-dkms is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'anbox-modules-dkms' has no installation candidate
```
Also, the Anbox Launchpad repo has no Release file

**What were you expecting?:**
The DKMS would install without errors

**Additional info:**

I have Pop!_OS Impish Indri

**Comment by hui1601** [comment]
you don't need to install it anymore.
Pop!OS 21.10 is based on Ubuntu 21.10.

[Install DKMS package from PPA](https://docs.anbox.io/userguide/install_kernel_modules.html#install-dkms-package-from-ppa)
> Starting with Ubuntu 19.04 binder and ashmem are now build with the standard Ubuntu kernel (>= 5.0) and you don’t have to install the modules from the PPA anymore.

**Comment by qaqak** [comment]
So say `ls`
It reports that the modules aren't install

**Comment by hui1601** [comment]
> You can use `grep binder /proc/filesystems || echo "binderfs support is missing"` To check for binderfs support.
https://github.com/anbox/anbox/blob/master/docs/install.md#verify-that-kernel-modules-are-loaded

> sudo mkdir /dev/binder
> sudo mount -t binder binder /dev/binder
https://github.com/anbox/anbox/pull/1309

this worked for me.

**Comment by qaqak** [comment]
![image](https://user-images.githubusercontent.com/49075348/147852930-441e3f6a-6f7f-4eb7-bd0b-a1f0947e5480.png)

**Comment by hui1601** [comment]
> ![image](https://user-images.githubusercontent.com/49075348/147852930-441e3f6a-6f7f-4eb7-bd0b-a1f0947e5480.png)

tried `sudo modprobe binder_linux`?

**Comment by Fuseteam** [comment]
So "i hate anbox because i can't install kernel
modules that are required by android and are shipped by default with the ubuntu kernel but perhaps popos ships their own kernel so it's not installed"

This is a duplicate of #1305 btw

**Comment by qaqak** [comment]
That is true

**Comment by qaqak** [comment]
This issue tastes stale. No one has talked, so I'm closing it
