### ISSUE TITLE
Pull #195 causes cmake to fail

### ISSUE THREAD

**Issue by gasinvein** [anbox/anbox#199]
Fedora and openSUSE (and maybe others) doesn't provide full gmock/gtest sources packaged, so using `/usr/src/gmock` as in #195 just causes cmake to fail.
Seems like only contents of `src` directory of original source are provided:
```
usr/src/gmock/gmock-all.cc
usr/src/gmock/gmock-cardinalities.cc
usr/src/gmock/gmock-internal-utils.cc
usr/src/gmock/gmock-matchers.cc
usr/src/gmock/gmock-spec-builders.cc
usr/src/gmock/gmock.cc
usr/src/gmock/gmock_main.cc
```

**Comment by morphis** [comment]
That sounds more like a problem with the packaging of gmock/gtest on openSUSE and Fedora for me rather than a bug in Anbox. Can you provide some guidance of what we need to improve on top of #195 to make cmake happy on these systems?

**Comment by gasinvein** [comment]
@morphis, seems like Arch doesn't ship full gmock source with CMakeLists.txi too.
Is gmock source (that in `/usr/src/gmock`) actually needed to use it, aren't headers enough?

**Comment by morphis** [comment]
> Is gmock source (that in /usr/src/gmock) actually needed to use it, aren't headers enough?

Please give it a try. Happy to accept pull-requests to get things building on Arch.
