### ISSUE TITLE
Linux Mint - Unable to locate anbox-common

### ISSUE THREAD

**Issue by Ikazine** [anbox/anbox#200]
I am currently using Linux Mint 18.1 which is based on Ubuntu 16.04.2 Xenial. I have installed snapd and ran the installer. The installer fails with the final message being `E: Unable to locate package anbox-common`. I am using the latest version of anbox that I can achieve besides compiling from source. The repository is added successfully, and everything else works fine besides the fact it cannot find anbox-common.

**Comment by hub2git** [comment]
lkazine, welcome to Anbox alpha!  I also am using Linux Mint 18.1 (xfce). 

To get help, please follow the instructions that show up after clicking the green "New Issue" button. 
1. Open Terminal.
2. Type `anbox system-info`.
3. Paste result here, but do so as code. (See https://guides.github.com/features/mastering-markdown/ and click "Code" for details. If you had followed the instructions, it would have been easier for you. 😛  )

**Comment by Ikazine** [comment]
I'm sorry, hub2git, but the application never successfully installed. Therefore, running anbox with any option brings up a 'anbox: command not found' error. That is why I didn't put any system-information in the original issue.

**Comment by hub2git** [comment]
lkazine, ah, I understand. Sorry about your the installation failing. You can wait for other people to reply to this issue.

**Comment by Ikazine** [comment]
Please close this. I have compiled from source and installed it and it seems the issue doesn't exist anymore. I do have another issue, but I will be looking for the solution before posting another issue.

**Comment by hub2git** [comment]
Please close the issue yourself. That way, the devs could spend their time
on other issues.
