### ISSUE TITLE
Cant install anbox on Debian

### ISSUE THREAD

**Issue by Timtaran** [anbox/anbox#2012]
<details>
Debian 11
</details>

**Please describe your problem:**

Snap Installing:
```bash
timtaran@TimTarAn-PC:~$ sudo snap install anbox-installer
error: cannot install "anbox-installer": cannot query the store for updates:
       got unexpected HTTP status code 408 via POST to
       "https://api.snapcraft.io/v2/snaps/refresh"

```
Adding Repository:
RU(original):
```bash
sudo add-apt-repository ppa:morphis/anbox-support
 
 More info: https://launchpad.net/~morphis/+archive/ubuntu/anbox-support
Press [ENTER] to continue or ctrl-c to cancel adding it
gpg: создан щит с ключами '/tmp/tmpgba3kdic/pubring.gpg'
gpg: /tmp/tmpgba3kdic/trustdb.gpg: создана таблица доверия
gpg: ключ 21C6044A875B67B7: импортирован открытый ключ "Launchpad PPA for morphis"
gpg: Всего обработано: 1
gpg:                  импортировано: 1
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: не найдено данных формата OpenPGP.
```
ENG(translated)
```bash
sudo add-apt-repository ppa:morphis/inbox-support
 
 More info: https://launchpad.net/~morphis/+archive/ubuntu/anbox-support
Press [ENTER] to continue or ctrl-c to cancel adding it
gpg: created a shield with the keys '/tmp/tmpgba3kdic/pubring.gpg'
gpg: /tmp/tmpgba3kdic/trustdb.gpg: a trust table has been created
gpg: key 21C6044A875B67B7: imported public key "Launchpad PPA for morphis"
gpg: Total processed: 1
gpg: imported: 1
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: no OpenPGP format data found.
```

**Comment by Timtaran** [comment]
```
[ 2022-03-07 17:49:05] [launch.cpp:155@operator()] The intent you provided is invalid. Please provide a correct launch intent.
[ 2022-03-07 17:49:05] [launch.cpp:156@operator()] For example to launch the application manager, run:
[ 2022-03-07 17:49:05] [launch.cpp:157@operator()] $ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity

```
command - `snap run anbox launch`

**Comment by Fuseteam** [comment]
you can launch it from the desktop menu

**Comment by Timtaran** [comment]
where

**Comment by Timtaran** [comment]
also... I use xfce

**Comment by Fuseteam** [comment]
the same way you launch firefox and the bunch :thinking:

**Comment by Timtaran** [comment]
um... I don't have anbox at this window

**Comment by Timtaran** [comment]
![изображение](https://user-images.githubusercontent.com/60805088/157161781-a680b8aa-0c34-4351-9982-e5db772dd851.png)
![изображение](https://user-images.githubusercontent.com/60805088/157161846-1e217d75-a5f0-4741-a10c-03c48c27ef11.png)
![изображение](https://user-images.githubusercontent.com/60805088/157161879-6876c44b-dfbe-43ef-b063-3a5576d6a9c0.png)
![изображение](https://user-images.githubusercontent.com/60805088/157161917-a9b9484c-82cf-4b32-870d-d6c482edaca2.png)
![изображение](https://user-images.githubusercontent.com/60805088/157161940-2fd8ecff-c23b-4384-a205-59272dc4fdb6.png)
![изображение](https://user-images.githubusercontent.com/60805088/157161966-627110f4-2b2d-4d73-9d4e-5f188ef20e9d.png)
![изображение](https://user-images.githubusercontent.com/60805088/157161992-8de4b1dd-1ed2-4145-a760-34ab8decb2ed.png)
![изображение](https://user-images.githubusercontent.com/60805088/157162013-487fb06d-8fe3-4c7b-9512-07c1eef1827a.png)
![изображение](https://user-images.githubusercontent.com/60805088/157162039-14b8d157-31d6-4b9d-aa1f-1324c5a020bd.png)
![изображение](https://user-images.githubusercontent.com/60805088/157162060-66d6518f-a1db-488b-bb85-0ec54669b6cd.png)

**Comment by macandchief** [comment]
For me install worked on Debian (using snap).

Start: `snap run anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity`

At the moment it works but crashes for me. Not sure yet why.

**Comment by Fuseteam** [comment]
> For me install worked on Debian (using snap).
> 
> Start: `snap run anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity`
> 
> At the moment it works but crashes for me. Not sure yet why.

Is session-manager running?
