### ISSUE TITLE
Providing description for project

### ISSUE THREAD

**Issue by ziyaddin** [anbox/anbox#203]
Maybe it is not in your plan but providing a small description at the top of the repo page would be great for users who see the project for the first time.

![image](https://cloud.githubusercontent.com/assets/1016523/25530857/d7c8aa80-2c38-11e7-9005-eb84fc32b014.png)

**Comment by hub2git** [comment]
@ziyaddin good idea. First-timers shouldn't need to scroll to the bottom. But then again, since this is alpha, I am guessing that the devs have enough participants and bugs at the moment.

**Comment by morphis** [comment]
Added a description and website link.

**Comment by ziyaddin** [comment]
Thanks!
