### ISSUE TITLE
APK install fails

### ISSUE THREAD

**Issue by pccobbler** [anbox/anbox#2032]
I could not figure out how to install and run Anbox on Jammy, so I created a new Beaver system, which enabled me to install and run Anbox.

However, while trying to install an APK, I got the below error message. I tried an earlier version of the APK, but I got the same error message. ABIS files are used by Android apps, with native libraries  required for the processor being used, but given that apps are built for smartphones, not AMD64 processors, do any apps run on PCs?

~$ adb install Downloads/someapp.apk
adb: failed to install Downloads/someapp.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

I won't attach the tar file because it has info I do not want to share. I tried to include console.log, but it was too long.

**Comment by Fuseteam** [comment]
Yes that's an arm apk your trying to install on amd64. You need to look for an x86 apk, yes those exist android x86 is a thing xd

**Comment by pccobbler** [comment]
Maybe this is a dumb question, but don't the app developers have to specifically build on AMD64 for there to be an AMD64 libraries? I asked customer support for this app and was told that they will never release on anything other than smartphones, so there's no point in continuing, right?

**Comment by Fuseteam** [comment]
@pccobbler yes the app devs have to release on AMD64/x86, that said there are x86 tablets out there

**Comment by pccobbler** [comment]
Unfortunately, customer support for the app I want specifically told me the only available libraries are for smartphones.
