### ISSUE TITLE
segfault at start session-manager, opensuse tumbleweed

### ISSUE THREAD

**Issue by two-dogs** [anbox/anbox#205]
Information for package anbox:
------------------------------
Repository     : Anbox (openSUSE_Tumbleweed)            
Name           : anbox                                  
Version        : 0.0.1.git20170427-42.2                 
Arch           : x86_64                                 
Vendor         : obs://build.opensuse.org/home:gasinvein
Installed Size : 3.7 MiB                                
Installed      : Yes                                    
Status         : up-to-date                             
Source package : anbox-0.0.1.git20170427-42.2.src       
Summary        : Android In a Box                       

anbox system-info https://gist.github.com/anonymous/47877faef279c6358895999f7bf1f19d

systemctl status anbox-container-manager.service https://gist.github.com/anonymous/c433994acb39dfcc209348ee3d9d7b16

systemctl --user status anbox-session-manager.service https://gist.github.com/anonymous/1e66ea9726ff4ecd369f1f7c52102c7d

journalctl from start of anbox-session-manager.service https://gist.github.com/anonymous/4af88044f0fc9ac6273336370bd383fb

i am clueless to what where the segfault occurs

**Comment by two-dogs** [comment]
i dont see segfault anylonger, i do see session manager closing still
Apr 29 09:05:15 linux-s4s1 anbox[14018]: [DD 2017-04-29 16:05:10] [Renderer.cpp:249@initialize] Successfully initialized EGL
Apr 29 09:05:15 linux-s4s1 anbox[14018]: [EE 2017-04-29 16:05:15] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
Apr 29 09:05:15 linux-s4s1 anbox[14018]: [WW 2017-04-29 16:05:15] [session_manager.cpp:140@operator()] Lost connection to container manager, terminating.
Apr 29 09:05:15 linux-s4s1 anbox[14018]: [EE 2017-04-29 16:05:15] [daemon.cpp:58@Run] Container is not running
Apr 29 09:05:15 linux-s4s1 systemd[1352]: anbox-session-manager.service: Main process exited, code=exited, status=1/FAILURE
Apr 29 09:05:15 linux-s4s1 systemd[1352]: anbox-session-manager.service: Unit entered failed state.
Apr 29 09:05:15 linux-s4s1 systemd[1352]: anbox-session-manager.service: Failed with result 'exit-code'.

**Comment by two-dogs** [comment]
is segfault after all, maybe a dup issue https://github.com/anbox/anbox/issues/28 referenced 
@linux-s4s1:~> ANBOX_LOG_LEVEL=debug anbox session-manager
[DD 2017-04-29 16:21:39] [gl_renderer_server.cpp:82@GLRendererServer] Using GLES-to-GL translator for rendering
[DD 2017-04-29 16:21:40] [Renderer.cpp:113@initialize] EGL doesn't support surfaceless context
[DD 2017-04-29 16:21:40] [Renderer.cpp:249@initialize] Successfully initialized EGL
[EE 2017-04-29 16:21:45] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[WW 2017-04-29 16:21:45] [session_manager.cpp:140@operator()] Lost connection to container manager, terminating.
[WW 2017-04-29 16:21:45] [session_manager.cpp:140@operator()] Lost connection to container manager, terminating.
Segmentation fault (core dumped)

**Comment by gasinvein** [comment]
Maybe errors in lxc? Take a look at `/var/lib/anbox/logs/container.log`

**Comment by two-dogs** [comment]
Will do, this

**Comment by comicfans** [comment]
I've also notice segfault when trying to run anbox , and  seems segfault happen in mesa while calling eglImageTargetTexture2DOES , I've created a bug in mesa bug [here](https://bugs.freedesktop.org/show_bug.cgi?id=100882)
