### ISSUE TITLE
Please use memfd kernel module - ashmem was removed from kernel 5.18

### ISSUE THREAD

**Issue by pini-gh** [anbox/anbox#2057]
See: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=721412ed3d819e767cac2b06646bf03aa158aaec
> The mainline replacement for ashmem is memfd, so remove the legacy
> code from drivers/staging/

Thanks in advance.

**Comment by Fuseteam** [comment]
this may not be feasible given anbox still uses an old android 7 image, see the discussion in #2042
