### ISSUE TITLE
Any chance to support kernel 5.18 on any conceivable future?

### ISSUE THREAD

**Issue by rizzini** [anbox/anbox#2064]
I'm aware 5.18 don't have bind or ashmem. Using [anbox-modules](https://github.com/anbox/anbox-modules) leads me to kernel panic.

**Comment by Fuseteam** [comment]
5.18 does have binder, it is now binderfs. please see #2042 for the discussion surrounding ashmem missing

**Comment by rizzini** [comment]
Mentioning bind was a mistake. I just saw it doesn't have ashmem anymore. I'll close this issue since there's another one going on.
