### ISSUE TITLE
Status of the project ?

### ISSUE THREAD

**Issue by jhay06** [anbox/anbox#2068]
Is the project dead? 

per checking on the last commit it was more than 10 months ago

**Comment by Fuseteam** [comment]
not another one of these unhelpful issues :/
at least check the current active issues such as #2042

**Comment by SoulInfernoDE** [comment]
you still can reverse patch the kernel sources and build the kernel with ashmem included i guess. I am running kernel version 6 and patched the kernel sources to include ashmem again.

**Comment by Fuseteam** [comment]
Sure but that's yet another technical hurdle for users; then again the only way to fix that is to upgrade the android image, which is not exactly trivial

**Comment by SoulInfernoDE** [comment]
That is true and i wish also a easier way for it. Fingers crossed someone can revive anbox for newer android versions...
I do not have wayland and no nvidia gpu which makes waydroid not really useable for some people. There are some points why people using anbox instead including me yet.

**Comment by Fuseteam** [comment]
I've had my fingers crossed for yeara for years, i wouldn't hold me breath for it xd

That said, iirc nvidia gpus have issues wiith both anbox and waydroid 🤔
