### ISSUE TITLE
Grammatical error on website

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [anbox/anbox#207]
it says 

> Performant
Runs Android without hardware virtualization and seamlessly bridges over hardware acceleration features.

 as a description. All other words are adjectives. Maybe it should say Performance?

**Comment by flipflop97** [comment]
Performant (although not in a dictionary) is also an adjective and used to describe good performing software: https://en.wiktionary.org/wiki/performant

So I don't think it is an error

**Comment by ThinkDigitalRepair** [comment]
I found the definition in the dictionary when I looked it up. But thanks
for that link, I didn't know it was used that way. So you think it's a
weird work to put there anyway? Especially since most people haven't heard
of this word?

**Comment by morphis** [comment]
"performant" is a valid work to use in this context.
