### ISSUE TITLE
Cannot install anbox kernel modules

### ISSUE THREAD

**Issue by SkyfallWasTaken** [anbox/anbox#2076]
1. Please check that no similar bug is already reported. Have a look at the list of open bugs at https://github.com/anbox/anbox/issues: I did find an issue, but it's from April and has no fix.

_2-6 are irrelevant_

**Please describe your problem:**
I can't install `anbox-modules-dkms` because of this error:
```
E: The repository 'https://ppa.launchpadcontent.net/morphis/anbox-support/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**What were you expecting?:**
The APT repository update to work, allowing me to install the kernel modules.

**Additional info:**
N/A

**Comment by Fuseteam** [comment]
> 2-6 are irrelevant
this issue is irrelevant because #1532 exists xD

jokes aside the ppa hasn't been needed since 19.04

**Comment by SkyfallWasTaken** [comment]
@Fuseteam That's the issue I'm talking about on point #1. However:
- @mullerivan's script fails with this output:
```
skyfall@hypex-pc:~/anbox-modules$ git clone https://github.com/anbox/anbox-modules.git && cd anbox-modules && sh INSTALL.sh && sudo modprobe ashmem_linux && sudo modprobe binder_linux
Cloning into 'anbox-modules'...
remote: Enumerating objects: 132, done.
remote: Total 132 (delta 0), reused 0 (delta 0), pack-reused 132
Receiving objects: 100% (132/132), 68.65 KiB | 1.60 MiB/s, done.
Resolving deltas: 100% (48/48), done.

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.18.10-76051810-generic all KERNEL_SRC=/lib/modules/5.18.10-76051810-generic/build...(bad exit status: 2)
ERROR (dkms apport): binary package for anbox-ashmem: 1 not found
Error! Bad return status for module build on kernel: 5.18.10-76051810-generic (x86_64)
Consult /var/lib/dkms/anbox-ashmem/1/build/make.log for more information.

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.18.10-76051810-generic all KERNEL_SRC=/lib/modules/5.18.10-76051810-generic/build...(bad exit status: 2)
ERROR (dkms apport): binary package for anbox-binder: 1 not found
Error! Bad return status for module build on kernel: 5.18.10-76051810-generic (x86_64)
Consult /var/lib/dkms/anbox-binder/1/build/make.log for more information.
modprobe: FATAL: Module ashmem_linux not found in directory /lib/modules/5.18.10-76051810-generic
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.18.10-76051810-generic
ls: cannot access '/dev/binder': No such file or directory
ls: cannot access '/dev/ashmem': No such file or directory
```
- `ls -1 /dev/{ashmem,binder}` fails with this (on Pop!_OS 22.04 LTS)
```
skyfall@hypex-pc:~/anbox-modules/anbox-modules$ ls -1 /dev/{ashmem,binder}
ls: cannot access '/dev/ashmem': No such file or directory
ls: cannot access '/dev/binder': No such file or directory
```
- `lsmod | grep -e ashmem_linux -e binder_linux` is completely empty

**Comment by Fuseteam** [comment]
you do not need to install the modules on jammy at all, they have been build in since ubuntu 19.04

if memory serves you can see this for yourself with
```
grep binder /proc/filesystems
grep ashmem /proc/misc
```

**Comment by SkyfallWasTaken** [comment]
They aren't installed though, that's the thing.
![image](https://user-images.githubusercontent.com/55807755/185909250-9805206f-4a79-4229-9da0-d77324a9b943.png)

**Comment by MinGW32-2006** [comment]
Try to edit the /etc/apt/sources.list.d/morphis-anbox-support.list (or a similar name), and change
'jammy' to 'bionic'.
Maybe it works. But due to the difference of the kernel version, there may be errors.

**Comment by Fuseteam** [comment]
> They aren't installed though, that's the thing. ![image](https://user-images.githubusercontent.com/55807755/185909250-9805206f-4a79-4229-9da0-d77324a9b943.png)
```
modprobe binder-linux
modprobe ashmem-linux
```
or `_` instead of `-` don't remember

**Comment by MinGW32-2006** [comment]
@Fuseteam @SkyfallWasTaken I just took a careful look at you terminal output. You are running Ubuntu on linux 5.18. But in linux-5.18 ashmem was removed from mainline. See issue #2042.

**Comment by SkyfallWasTaken** [comment]
> > They aren't installed though, that's the thing. ![image](https://user-images.githubusercontent.com/55807755/185909250-9805206f-4a79-4229-9da0-d77324a9b943.png)
> 
> ```
> modprobe binder-linux
> modprobe ashmem-linux
> ```
> 
> or `_` instead of `-` don't remember

No dice

**Comment by Fuseteam** [comment]
wait 5.18 on jammy? did you install a custom kernel or something?
tho even then binder should show up

**Comment by SkyfallWasTaken** [comment]
> wait 5.18 on jammy? did you install a custom kernel or something? tho even then binder should show up

Pop!_OS installs 5.18 I'm pretty sure. And yeah, I'm pretty sure binder's meant to be there at the very least.

**Comment by SkyfallWasTaken** [comment]
Update: so after a software update, I apparently now have 5.19 for some reason???

![image](https://user-images.githubusercontent.com/55807755/186104483-e44a14d6-e696-4ca4-a26e-ca17be2365f0.png)

**Comment by MinGW32-2006** [comment]
AFAIK the binder module can't be built on newer linux kernels. You will meet failure.
Pop!_OS don't integrate 'binder' into its kernel package.

**Comment by SkyfallWasTaken** [comment]
> AFAIK the binder module can't be built on newer linux kernels. You will meet failure. Pop!_OS doesn't integrate 'binder' into its kernel package.

Oof.

Is there any way to use Anbox without binder / ashmem?

**Comment by MinGW32-2006** [comment]
@SkyfallWasTaken Nope. Rebuild Linux kernel?

**Comment by MinGW32-2006** [comment]
But ashmem is removed. There may be no solution. Anbox doesn't support memfd.

**Comment by SkyfallWasTaken** [comment]
> But ashmem is removed. There may be no solution. Anbox doesn't support memfd.

=(

Well, thanks to you and @Fuseteam for all the help. I'll try and get binder at least so I can use waydroid.

**Comment by Fuseteam** [comment]
> ![image](https://user-images.githubusercontent.com/55807755/186104483-e44a14d6-e696-4ca4-a26e-ca17be2365f0.png)

sorry @SkyfallWasTaken if had shown me this earlier, i would've told you a different story see **Ubuntu** 22.04 ships both binder and ashmem out of the box, but [Pop_OS! does not](https://github.com/pop-os/linux/issues/113). I think the best route will be to poke the pop os maintainers to ship at least binder, tho i'm honestly not sure if they ship memfd.

this is why `anbox system-info` would've helped as it would've shown that you are on Pop OS not ubuntu, but that's on me; i should've asked for it

**Comment by SkyfallWasTaken** [comment]
@Fuseteam don't worry about it, and thanks for the help! I'll try to get the maintainers to ship binder and ashmem.

**Comment by profimedica** [comment]
Try WayDroid because ashmem is not available.

As @bwhacks said...

"In Debian we've been building our kernel packages with ashmem and binder as modules, as expected by Anbox.
However, in 5.18 ashmem has been removed upstream (https://github.com/torvalds/linux/commit/721412ed3d819e767cac2b06646bf03aa158aaec) and is supposed to be replaced with memfd. So far as I can see, Anbox isn't ready for this.
For now we'll keep building kernel packages with binder as a module. If you would prefer to have users build both ashmem and binder from your out-of-tree version then we can stop doing that."

https://github.com/anbox/anbox/issues/2042
