### ISSUE TITLE
PPA dependency kills the purpose of using snap

### ISSUE THREAD

**Issue by hoshi411** [anbox/anbox#208]
Please end PPA dependency as this defeats the purpose of using snap.

**Comment by gasinvein** [comment]
It's not possible due to kernel modules, which, as far as I know, cannot be packaged with snap. Also, because of this I don't see any advantage in using snap at all.

**Comment by morphis** [comment]
> Please end PPA dependency as this defeats the purpose of using snap.

That is simply not true. If you still think it is, please elaborate why this is true.

> It's not possible due to kernel modules, which, as far as I know, cannot be packaged with snap. Also, because of this I don't see any advantage in using snap at all.

There is a clear advantage of using a snap as it allows us to easily distribute exactly the same software to all our users regardless of the distribution and other available software. Snaps are for multiple reasons  better than debs and ppa's. See https://snapcraft.io for more details.

There are two reasons why we still have to use a PPA for additional things:

 1. Kernel modules for binder and ashmem: Both are not available in the default kernel of any distribution. Also both can't be compiled as optional modules without further upstream kernel changes. Long term we plan to submit patches to the upstream Linux kernel to allow the build of both ashmem and binder as modules so distributions can enable both in their default kernel configuration.
 2. User session services and other system configuration files: Both are not yet supported by the snap format but there are upcoming changes which will allow us to drop these from the PPA. Mid term those things will be dropped from the anbox-common debian package.
