### ISSUE TITLE
Mint 21 error "Cannot add PPA - This PPA does not support Jammy"

### ISSUE THREAD

**Issue by pbtn6** [anbox/anbox#2088]
I have successfully installed snaps and then Anbox in Mint 21 following the instructions in 
     docs.anbox.io/userguide/install.html.   
It runs, and some of the pre-installed apps will launch but often hang and I cannot exit from them.
This may well be because I was not able to install the two kernel modules as described in 
    docs.anbox.io/userguide/install_kernel_modules.html
This command in the instructions worked:
    $ sudo apt install software-properties-common
The next did not:
   $ sudo add-apt-repository ppa:morphis/anbox-support
It returned:
   Cannot add PPA: ' ' this PPA does not support jammy ' '

I don't recall seeing any specific claims that Anbox runs under Mint, so I would accept a response that I have encountered a feature rather than a bug.  However if you intend to make Anbox install in Mint 21 in the near future could you please let me know, also if there is a workaround for the issue I have come across.

**Comment by Fuseteam** [comment]
you do not need the modules for mint based on ubuntu newer than ubuntu 19.04, jammy is 22.04.

there's likely a different issue that's causing certain apps to fail

**Comment by pbtn6** [comment]
Thanks.  I will try to gather more information about the problem I am experiencing and report separately if there is something specify you might want to investigate.
