### ISSUE TITLE
My anbox cannot  make any SOUND!

### ISSUE THREAD

**Issue by FortiterInRe** [anbox/anbox#2089]
</details>

**Please describe your problem:**
I just found my anbox cannot make any sound.Moreover, I could not use the default Music app, because it crashed. I have also tried use the Web and the Clock.However, they were both silent.
But everything except the sound is fine. 
The anbox can use the arm apps. I followed this article: https://github.com/geeks-r-us/anbox-playstore-installer/blob/master/install-playstore.sh

**What were you expecting?:**
I wonder how to fix this bug.

**Additional info:**
[system-info.log](https://github.com/anbox/anbox/files/9593048/system-info.log)
[system.log](https://github.com/anbox/anbox/files/9593049/system.log)
[kernel.log](https://github.com/anbox/anbox/files/9593050/kernel.log)
[container-manager.log](https://github.com/anbox/anbox/files/9593051/container-manager.log)
[container.log](https://github.com/anbox/anbox/files/9593052/container.log)

**Comment by Fuseteam** [comment]
please see https://github.com/anbox/anbox/issues/904

**Comment by FortiterInRe** [comment]
> please see #904
Thanks!I'm sorry that I haven't seen the issue.The sound has been fixed by your [solution](https://github.com/anbox/anbox/issues/904#issuecomment-586740315). But the Music app still crashed. It crashed quickly, and then, my anbox would crash too. There seemed not to be any issues mentioned the same bug like mine.
I am still thankful for the solution at last! :)

**Comment by Fuseteam** [comment]
the music app crashing seems like a different issue, feel free to update the title to describe the issue

sadly i don't know why the music app fails

**Comment by FortiterInRe** [comment]
OK, though the sound is not robust enough (In fact, I cannot use it today), I will try some other ways to fix it. Thanks and I think this issue may be able to closed.
