### ISSUE TITLE
arm64 for snap package

### ISSUE THREAD

**Issue by tigercoding56** [anbox/anbox#2096]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**
currently anbox's snap package supports armhf and amd64 
so if you try to install it on a raspberry pi running a 64 bit OS like manjaro (because repo package does not work since it still tries to find libboost 1.79 when the latest libboost is 1.80) then it will not install 

**What were you expecting?:**
anbox to get installed

**Comment by Fuseteam** [comment]
no need to leave the steps to follow in the template, but please do follow the steps

this issue is already tracked in #1043 #1044 and #1888 ;)

**Comment by tigercoding56** [comment]
> no need to leave the steps to follow in the template, but please do follow the steps
> 
> this issue is already tracked in #1043 #1044 and #1888 ;)

aight im closing then
