### ISSUE TITLE
Can we say Anbox is no longer developed?

### ISSUE THREAD

**Issue by austinrojers** [anbox/anbox#2116]
Since ashmem was removed from the Linux kernel, getting Anbox to run is proving to be more challenging as days pass. And the last time the project was active was four months ago.

On the other hand, Waydroid is being actively developed and has hardware acceleration.

Can we conclude that Anbox’s development has stopped and Waydroid is the natural successor of Anbox? (Tell me if I am wrong)

It would be nice if Anbox developers now contributed to Waydroid instead of Anbox.

It would be great to see Anbox developers sharing their knowledge of creating containerised Snap or flatpak packages with Waydroid developers, among others they have gained in the journey of developing Anbox.

It would be nice to see an official comment from the Anbox developers.
It can prevent several futile attempts of people trying to run Anbox.

**Comment by Fuseteam** [comment]
> It would be nice if Anbox developers now contributed to Waydroid instead of Anbox.

It should've been the other way around but alas the architecture is way too different

> It would be great to see Anbox developers sharing their knowledge of creating containerised Snap or flatpak packages with Waydroid developers, among others they have gained in the journey of developing Anbox.

Flatpak packaging is not technically feasible as the format wasn't made for this usecase. Flatpak is made for the regular desktop usecase. Snap would be possible but it is too dang polarizing, for every comment mentioning snap you get 10 people demanding a flatpak despite the technical infeasiblity. You won't believe how many people blame snap for the current state of this project despite anbox being in the debian repos

> It would be nice to see an official comment from the Anbox developers. It can prevent several futile attempts of people trying to run Anbox.

The maintainer seems to be maintaining the project whenver they have free time, which appearently isn't a lot

**Comment by Kusoneko** [comment]
> It would be nice if Anbox developers now contributed to Waydroid instead of Anbox.

I've tried using waydroid as an alternative but so far it's not working for me personally as it requires wayland. I've followed instructions to make it run on xorg using some sort of wayland-on-xorg thing and it didn't work either, so as far as I'm concerned, waydroid isn't a successor.

**Comment by morphis** [comment]
Thanks for bringing this up. It's only fair from my side to mark Anbox as deprecated as its development has stalled and there are other alternatives with Waydroid (for desktop use) and Anbox Cloud (for cloud).

I will work towards making this explicit in the Anbox messaging and reference alternatives.

**Comment by austinrojers** [comment]
Hey there @morphis,
Thanks for the acknowledgement.

**Comment by raphaelchinchilla** [comment]
@morphis thank you for your hard work over the years.

**Comment by morphis** [comment]
For completeness: There is now a warning on https://github.com/anbox, https://anbox.io redirects there. This should provide people with an indication what to do next if they were looking for Anbox.

**Comment by Fuseteam** [comment]
thanks for inspiring Android containers on Linux @morphis :heart:

**Comment by necessarily-equal** [comment]
Thank you for making this official

**Comment by raphaelchinchilla** [comment]
Honestly, this is such a sad goodbye to such a good project. The major GNU/Linux distributions should step up and make Android apps on Linux happen in a sameless and fully working way. But, alas, division is a constant in the GNU/Linux sphere.

**Comment by Fuseteam** [comment]
@raphaelchinchilla there's still [waydroid](https://github.com/waydroid) which just got accepted into fedora's repos. it has quite a way to go for a "seamless" integration in a linux distro but it is much closer to android apps "fully working"
