### ISSUE TITLE
Failed to insert 'ashmem_linux': Exec format error

### ISSUE THREAD

**Issue by andrirooki** [anbox/anbox#216]
andri@andri-K52N:~$ systemctl status systemd-modules-load.service
● systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/lib/systemd/system/systemd-modules-load.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2017-05-03 08:36:33 EEST; 3h 5min ago
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
 Main PID: 603 (code=exited, status=1/FAILURE)
      CPU: 5ms

03 08:36:33 andri-K52N systemd[1]: Starting Load Kernel Modules...
03 08:36:33 andri-K52N systemd-modules-load[603]: Failed to insert 'ashmem_linux': Exec format error
03 08:36:33 andri-K52N systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
03 08:36:33 andri-K52N systemd[1]: Failed to start Load Kernel Modules.
03 08:36:33 andri-K52N systemd[1]: systemd-modules-load.service: Unit entered failed state.
03 08:36:33 andri-K52N systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.

P.S. Is that known issue? How can I fix it?

**Comment by mvvvv** [comment]
same problem with ubuntu 17.04. What I have in journalctl -p4 : 

`systemd[1]: cgmanager.service: Cannot add dependency job, ignoring: Unit cgmanager.service is masked.
mai 03 08:33:16 matthieu-i56400 systemd[1]: cgproxy.service: Cannot add dependency job, ignoring: Unit cgproxy.service is masked.
mai 03 08:33:16 matthieu-i56400 kernel: ashmem_linux: version magic '4.10.0-19-generic SMP mod_unload ' should be '4.10.0-20-generic SMP mod_unload '
mai 03 08:33:16 matthieu-i56400 kernel: binder_linux: version magic '4.10.0-19-generic SMP mod_unload ' should be '4.10.0-20-generic SMP mod_unload '
mai 03 08:33:16 matthieu-i56400 systemd-modules-load[250]: Failed to insert 'ashmem_linux': Exec format error
mai 03 08:33:16 matthieu-i56400 systemd-modules-load[250]: Failed to insert 'binder_linux': Exec format error
mai 03 08:33:16 matthieu-i56400 systemd[1]: Failed to start Load Kernel Modules.
mai 03 08:33:16 matthieu-i56400 systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.
mai 03 08:33:19 matthieu-i56400 `

**Comment by Mistero5050** [comment]
Same problem

```
 systemctl status systemd-modules-load.service
● systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/lib/systemd/system/systemd-modules-load.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2017-05-13 09:29:46 CEST; 1h 25min ago
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
 Main PID: 581 (code=exited, status=1/FAILURE)

mag 13 09:29:46 archimede systemd[1]: Starting Load Kernel Modules...
mag 13 09:29:46 archimede systemd-modules-load[581]: Failed to insert 'ashmem_linux': Exec format error
mag 13 09:29:46 archimede systemd-modules-load[581]: Failed to insert 'binder_linux': Exec format error
mag 13 09:29:46 archimede systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
mag 13 09:29:46 archimede systemd[1]: Failed to start Load Kernel Modules.
mag 13 09:29:46 archimede systemd[1]: systemd-modules-load.service: Unit entered failed state.
mag 13 09:29:46 archimede systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.

```

**Comment by fathulkirom22** [comment]
My problem too

`● systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/lib/systemd/system/systemd-modules-load.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sab 2017-05-27 11:24:54 WIB; 9min ago
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
  Process: 572 ExecStart=/lib/systemd/systemd-modules-load (code=exited, status=1/FAILURE)
 Main PID: 572 (code=exited, status=1/FAILURE)

Mei 27 11:24:54 bahwell systemd[1]: Starting Load Kernel Modules...
Mei 27 11:24:54 bahwell systemd-modules-load[572]: Failed to insert 'ashmem_linux': Exec format error
Mei 27 11:24:54 bahwell systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
Mei 27 11:24:54 bahwell systemd[1]: Failed to start Load Kernel Modules.
Mei 27 11:24:54 bahwell systemd[1]: systemd-modules-load.service: Unit entered failed state.
Mei 27 11:24:54 bahwell systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.`

**Comment by hexboy** [comment]
me to have same problem (#216) , and after unistall anbox, it's not solved!
```terminal
ubuntu@ubuntu:~$ sudo systemctl status systemd-modules-load.service


● systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/lib/systemd/system/systemd-modules-load.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-06-12 00:32:37 +0430; 7min ago
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
 Main PID: 550 (code=exited, status=1/FAILURE)
      CPU: 2ms

jun 12 00:32:37 ubuntu systemd[1]: Starting Load Kernel Modules...
jun 12 00:32:37 ubuntu systemd-modules-load[550]: Failed to insert 'ashmem_linux': Exec format error
jun 12 00:32:37 ubuntu systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
jun 12 00:32:37 ubuntu systemd[1]: Failed to start Load Kernel Modules.
jun 12 00:32:37 ubuntu systemd[1]: systemd-modules-load.service: Unit entered failed state.
jun 12 00:32:37 ubuntu systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.
```

**Comment by viggy96** [comment]
Same problem. I suspect that this problem is causing me to be unable to boot other updated kernels.
This is a serious issue, and it needs to be resolved.

**Comment by S0litaire** [comment]
This had been bugging me for a while.

Found a solution : 
In Ubuntu I ran 
sudo apt-get purge anbox* -y

It removes all anbox files and let's me boot.

**Comment by cryptism** [comment]
Purging anbox from apt didn't do it for me, so I ended up having to remove /etc/modules-load.d/anbox.conf directly

**Comment by mohajer1373** [comment]
Thanks..

**Comment by overclockedllama** [comment]
+1 this issue but arch linux 4.14.8-1. I have the matching linux-headers and want to use anbox but it wont load the ashmem linux module, even if i try to do so manually

**Comment by damko** [comment]
this happened to me because my kernel was too old. After installing a more recent kernel and its own headers package I've got the issue solved.

**Comment by morphis** [comment]
This issue should be solved with the latest updated DKMS package in the PPA.
