### ISSUE TITLE
Suggestion: use QtADB as the basis of a GUI for Anbox

### ISSUE THREAD

**Issue by JLIT0** [anbox/anbox#219]
Currently, installation and management of applications has to be conducted through the terminal using adb.
In order to save time writing a GUI, [QtADB](https://qtadb.wordpress.com/features/), an open-source ADB frontend for Linux could be used as the basis for Anbox's GUI.

Also, suggest adding a compatibility database along the lines of WineHQ's AppDB.

Thanks!

**Comment by morphis** [comment]
> Currently, installation and management of applications has to be conducted through the terminal using adb. In order to save time writing a GUI, QtADB, an open-source ADB frontend for Linux could be used as the basis for Anbox's GUI.

If you want you can use QtADB as is with Anbox but we don't have any plan to provide any GUI functionality for adb with Anbox.

> Also, suggest adding a compatibility database along the lines of WineHQ's AppDB.

This may come in the future.
