### ISSUE TITLE
CANNOT found/deal the LOOP device when Install in the ubuntu 14.04 on OpenVZ

### ISSUE THREAD

**Issue by DoraemonYu** [anbox/anbox#220]
Hello,dears.
I am trying to install the latest version of anbox on Ubuntu 14.04, on OpenVZ.

The command of  `snap install --classic anbox-installer`  shows the error messages as below: 
```
error: cannot perform the following tasks:  
Mount snap "core" (1689) ([start snap-core-1689.mount] failed with exit status 1: Job for snap-core-1689.mount failed. See **systemctl status snap-core-1689.mount** and **journalctl -xn** for details.)
```

Then I try to get more informations from these two commands: 

*  `systemctl status snap-core-1689.mount`   :  
```
Loaded: loaded (/etc/systemd/system/snap-core-1689.mount; enabled)  
Active: failed (Result: exit-code) since 四 2017-05-04 14:20:15 CST; 24min ago  
Where: /snap/core/1689  
What: /var/lib/snapd/snaps/core_1689.snap  
Process: 22471 ExecMount=/bin/mount /var/lib/snapd/snaps/core_1689.snap /snap/core/1689 -t squashfs -o nodev (code=exited, status=2)  
```

* `journalctl -xn`
```
-- Logs begin at 五 2017-04-28 15:23:37 CST, end at 四 2017-05-04 14:20:15 CST. --
 5月 02 22:11:08 fk3drt5c04 snapd[4931]: 2017/05/02 22:11:08.866803 snapmgr.go:450: No snaps to auto-refresh found
 5月 03 05:56:08 fk3drt5c04 snapd[4931]: 2017/05/03 05:56:08.855743 snapmgr.go:450: No snaps to auto-refresh found
 5月 03 13:41:09 fk3drt5c04 snapd[4931]: 2017/05/03 13:41:09.196797 snapmgr.go:450: No snaps to auto-refresh found
 5月 03 21:26:08 fk3drt5c04 snapd[4931]: 2017/05/03 21:26:08.891940 snapmgr.go:450: No snaps to auto-refresh found
 5月 04 05:11:08 fk3drt5c04 snapd[4931]: 2017/05/04 05:11:08.872309 snapmgr.go:450: No snaps to auto-refresh found
 5月 04 12:56:09 fk3drt5c04 snapd[4931]: 2017/05/04 12:56:09.116718 snapmgr.go:450: No snaps to auto-refresh found
 5月 04 14:20:06 fk3drt5c04 snapd[4931]: 2017/05/04 14:20:06.905751 api.go:913: Installing snap "anbox-installer" revision unset
 5月 04 14:20:15 fk3drt5c04 mount[22471]: mount: 找不到任何 loop 设备。可能内核无法处理 loop 设备。
 5月 04 14:20:15 fk3drt5c04 mount[22471]: (如果是这样，重新编译内核或输入`modprobe loop'。)
 5月 04 14:20:15 fk3drt5c04 snapd[4931]: 2017/05/04 14:20:15.979764 handlers.go:203: Reported install problem for "core" as bce8e434-3091-11e7-806e-fa163
lines 1-11/11 (END)
```
( Sorry, my environment settings is zh-cn, so there are some Chinese text above. It primarily means that CANNOT found/deal the LOOP device  )

**So my problem is I can not install it on my Ubuntu 14.04.** 

I hope to known, is it the **Installer** and Anbox must use the LOOP device?  Is there something I can make it continue to run and use anbox ?

I have already ask my VPS Provider and they tell me the  LOOP module and FUSE module is disabled. Maybe this is the key, but I am not completely sure. So I commit a issus here and hope to got answer.

Thanks so much.

**Comment by gasinvein** [comment]
I'm pretty curious why would someone want Android applications on a VPS.

**Comment by DoraemonYu** [comment]
@gasinvein 
Thanks for your reply.  
:)  Mmm...  Just because of different people own different requirement.

Shashlik project, which is anther solution to run android app on linux as well, can be installed and run on Ubuntu on Vps.
I known maybe anbox is focus on desktop users, but also hope it will not loss other users that run linux on some platform.

**Comment by gasinvein** [comment]
Ok then.
To your question - missing loop module is definitely the key. Also, as anbox relies on two custom kernel modules, you need a fully-virtualized VPS anyway.

**Comment by morphis** [comment]
If you don't have loop support in your kernel we can't really help.

**Comment by DoraemonYu** [comment]
@morphis
:smiley:    Okay, thanks all of you. I understand it now.
