### ISSUE TITLE
kernel patch usage about binder

### ISSUE THREAD

**Issue by xinghua** [anbox/anbox#228]
hi,  I notice some kernel patch about binder namespace has been added to the master branch，but how to use it? patch it to the anbox binder module,  and ubuntu kernel module?  anbox has patched it successfully?  has it be meged into anbox-modules-dkms? thanks

**Comment by oleid** [comment]
As an alternative to the source provided here, you could also use binder and ashmen from mainline linux. Using it on linux 4.11.

**Comment by xinghua** [comment]
@oleid   I mean this patch https://github.com/anbox/anbox/blob/master/kernel/patches/0002-binder-implement-namepsace-support-for-Android-binde.patch,   make android binder support namespace，so different container can become context manager at the same time.   I notice this patch has to beed merge into anbox master branch,  so anbox how to use this patch?

**Comment by morphis** [comment]
> hi, I notice some kernel patch about binder namespace has been added to the master branch，but how to use it? patch it to the anbox binder module, and ubuntu kernel module? anbox has patched it successfully? has it be meged into anbox-modules-dkms? thanks

These two patches just enable namespace support for binder. If you run Anbox on a system where nothing else uses binder, then you don't need these patches. If you run Anbox on a device with Ubuntu Touch or Sailfish you need those as then you have two different and independent systems using the binder kernel system. Also these patches are interesting when you want to run multiple instances of the Anbox container.

Both patches are not part of the anbox-modules-dkms package as they affect a whole kernel tree and there is no easy way yet to get those things applied to available distribution kernels.

If you just want to run Anbox on your system you don't need them.
