### ISSUE TITLE
Fix GLM include

### ISSUE THREAD

**Issue by Yukariin** [anbox/anbox#234]
Currently I'm trying to build anbox on my Gentoo Linux and got:
`In file included from anbox/src/anbox/graphics/emugl/Renderer.h:26:0,
                 from anbox/src/anbox/graphics/gl_renderer_server.cpp:21:
anbox/src/anbox/graphics/emugl/Renderable.h:27:23: fatal error: glm/glm.hpp: No such file or directory`
After some googling I figure out that GLM is not part nor OpenGL nor Mesa, it's C++ math lib that has much of the same syntax as GLSL. So in order to use it we need to install it first.
And because GLM is important compile-time dependency for anbox I think we should add it into CMake files as REQUIRED.

**Comment by morphis** [comment]
Please feel free to send a PR to get this corrected.

**Comment by morphis** [comment]
This fixed in latest master with us importing our own GLM copy for the time being.
