### ISSUE TITLE
Suggestion: Have anbox automatically update itself

### ISSUE THREAD

**Issue by hub2git** [anbox/anbox#238]
Dear devs,

May I humbly suggest that every time we run anbox (whether my terminal or GUI/menu), Anbox would automatically check if our computer has the latest anbox version. And if our computer doesn't, Anbox will automatically download latest version

If this is not easy or possible, I'd like to know what is the __manual__ way of updating Anbox? Is it, as some in github suggest, to uninstall and then re-install Anbox/Anbox-Installer?

**Comment by morphis** [comment]
> May I humbly suggest that every time we run anbox (whether my terminal or GUI/menu), Anbox would automatically check if our computer has the latest anbox version. And if our computer doesn't, Anbox will automatically download latest version

That is what snaps are doing for us. There is no need to implement extra support for this into Anbox. See https://snapcraft.io/docs/core/updates for details

Please note that master isn't automatically landed into the edge channel today. We will start doing this in the near future and will then use the beta channel for a bit more stable updates.

> If this is not easy or possible, I'd like to know what is the manual way of updating Anbox? Is it, as some in github suggest, to uninstall and then re-install Anbox/Anbox-Installer?

See https://snapcraft.io/docs/core/updates

**Comment by hub2git** [comment]
Thanks for clearing up how snaps works. In my trying to get Anbox working
on my Linux, I'm learning about snaps too. :) Thanks for all your work on
Anbox. :)

**Comment by davidelang** [comment]
are there new snaps being built? it looks to me like the snaps are still showing 
as version 0.1.0

**Comment by hub2git** [comment]
@davidelang, I just ran `sudo snap refresh anbox` and got "snap "anbox" has
no updates available". I ran `sudo snap refresh anbox-installer` and got
"snap "anbox-installer" has no updates available".

**Comment by davidelang** [comment]
That's my point, not having done an update since I initially installed it a 
couple weeks ago, there were no updates reported, but when I did an 
uninstall/install things worked differently, so something was changed in the 
meantime.

If the snap process is what we should be doing to get updates, the version of 
the snap needs to change as development progresses. Otherwise you end up with a 
bunch of people fighting issues you've already fixed.

**Comment by hub2git** [comment]
@davidelang I'm sorry i wasn't clear in my previous message. I do realize
that that was your point. All I wanted to express is that I too am in your
situation. Based on @morphis's message, it sounds like we can expect an
update to version 0.1.0 "in the near future".
