### ISSUE TITLE
Installing FireFox or Opera

### ISSUE THREAD

**Issue by nitemn** [anbox/anbox#24]
Make sure you are running the latest version of Anbox before reporting an issue.

**Anbox release (`anbox version`) and system info (`anbox system-info`):**
Ubuntu 16.04 Anbox 7.1.1

**Description of the problem:**
When trying to install Firefox or Opera browser I get this Error:
37080 KB/s (43707218 bytes in 1.151s)
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

**Expected:**
Application to install

**Additional info:**

**Comment by morphis** [comment]
The error

```
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```

means that there are native binaries include in the apk file which are not supported on your current architecture. There is nothing Anbox can do to fix this as it depends on the apk vendor to ship compatible software for the architecture you want to run this on.

**Comment by nboisteault** [comment]
To install Firefox mobile I have downloaded the x86 version in [Mozilla's FTP](https://ftp.mozilla.org/pub/mobile/).
