### ISSUE TITLE
yocto

### ISSUE THREAD

**Issue by covadis** [anbox/anbox#243]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**
I want to test it on the embedded system. 
Do you have yocto build files??

**What were you expecting?:**

**Additional info:**

**Comment by hub2git** [comment]
@covadis there's a list of supported systems. I couldn't find the nice-looking list. But found it in the code: 
https://github.com/anbox/anbox-installer/blob/7be97c7e3c65f6f3174a40b706e453b1d6b29de3/installer.sh#L33:
"Ubuntu" "LinuxMint" "neon" "elementary"

**Comment by morphis** [comment]
The issue title doesn't really say what you want. "yocto" doesn't say much at all. Can you please describe in detail what you want us to get out of your bug report? Thanks. Feel free to reopen.
