### ISSUE TITLE
O anbox não inicia no ubuntu 17.04

### ISSUE THREAD

**Issue by felipesousa331** [anbox/anbox#249]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by morphis** [comment]
Please describe what you want in English as that is the language used by this project and reopen the bug. Thanks.
