### ISSUE TITLE
uninstall anbox

### ISSUE THREAD

**Issue by romicacell** [anbox/anbox#260]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```how to uninstall anbox
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**
don't work

**What were you expecting?:**

**Additional info:**

**Comment by JLIT0** [comment]
Did you follow these instructions?

> In the terminal: [/snap/bin/anbox-installer](url)
> 
> Select option 2: uninstall Anbox
>

**Comment by morphis** [comment]
@JLIT0 explained how uninstall works.
