### ISSUE TITLE
Ashmem and Binder not installed and cant be installed

### ISSUE THREAD

**Issue by 1Guardian** [anbox/anbox#264]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**

libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19)
  binder: false
  ashmem: false
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_create_context
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_MESA_configless_context
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

```

I have anbox installed, but I am unable to start it, I think it is due to the ashmem and binder not being found. I have tried re running the installer with no results. 


It to run


I just need to know if there is any way to install anbox on debian other then the installer for starters or if there is a way to install ashmem or binder

**Comment by polszanski** [comment]
From what I know, binder and ashmem are kernel modules, so you have to either compile or find a custom kernel with them enabled.

**Comment by 1Guardian** [comment]
do you know where I could find them to compile them?

**Comment by pieniek** [comment]
I guess you need to compile your own kernel with these settings added: 
CONFIG_ANDROID=y
CONFIG_ANDROID_LOW_MEMORY_KILLER=n
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDER_DEVICES="binder"
CONFIG_ASHMEM=y
CONFIG_ION=n
So you need kernel sources (kernel.org), cd into it, then copy your current kernel config (should be on /boot/config-<linux_version>) to .config inside of the kernel sources, add these options (or use make xconfig for beginner friendly GUI) and compile it. 
I recommend searching for some more detailed instructions if it's your first time compiling a custom kernel, it's not that difficult, just a bit complicated.

**Comment by ryanleesipes** [comment]
I'm also running into this Ubuntu GNOME 17.04. Is there a more permanent/easier fix that we can put in place to avoid having to compile a kernel? (You know, for adoption's sake) :smile:

**Comment by Acromonkey** [comment]
I have the same problem. Starting "anbox session-manager" brings the error message 

[EE 2017-05-22 21:47:50] [session_manager.cpp:130@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded

**Comment by ryanleesipes** [comment]
Yup, that un' @Acromonkey - what are you running it on?

**Comment by Acromonkey** [comment]
Linux Mint Mate 18.1 64-bit
Kernel 4.8.0-52
MATE 1.16.1
AMD Athlon II X2 250

**Comment by johnothwolo** [comment]
This worked for me:
 `sudo apt install anbox-modules-dkms`

  but I after that i got this error

 `libGL error: No matching fbConfigs or visuals found
  libGL error: failed to load driver: swrast
  libGL error: No matching fbConfigs or visuals found
  libGL error: failed to load driver: swrast
  [EE 2017-05-27 17:22:32] [Renderer.cpp:138@initialize] Failed to create context: error=0x3005
  Segmentation fault (core dumped)
`

**Comment by 1Guardian** [comment]
I have finally gotten to the point that I can install the anbox-modules-dkms, but I get these two errors when they are trying to make, can anyone shed light on this? 

binder----------------------------------------------------------------------
DKMS make.log for anbox-modules-binder-6~zesty1 for kernel 3.16.0-4-amd64 (amd64)
Mon May 29 14:55:19 EDT 2017
make -C /lib/modules/3.16.0-4-amd64/build V=0 M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-3.16.0-4-amd64'
make[1]: Entering directory `/usr/src/linux-headers-3.16.0-4-amd64'
  LD      /var/lib/dkms/anbox-modules-binder/6~zesty1/build/built-in.o
  CC [M]  /var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.o
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c: In function ‘get_vm_area’:
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c:29:19: warning: assignment makes pointer from integer without a cast [enabled by default]
   get_vm_area_ptr = kallsyms_lookup_name("get_vm_area");
                   ^
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c: In function ‘zap_page_range’:
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c:36:22: warning: assignment makes pointer from integer without a cast [enabled by default]
   zap_page_range_ptr = kallsyms_lookup_name("zap_page_range");
                      ^
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c: In function ‘map_kernel_range_noflush’:
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c:43:32: warning: assignment makes pointer from integer without a cast [enabled by default]
   map_kernel_range_noflush_ptr = kallsyms_lookup_name("map_kernel_range_noflush");
                                ^
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c: In function ‘unmap_kernel_range’:
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c:50:26: warning: assignment makes pointer from integer without a cast [enabled by default]
   unmap_kernel_range_ptr = kallsyms_lookup_name("unmap_kernel_range");
                          ^
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c: In function ‘get_files_struct’:
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c:57:24: warning: assignment makes pointer from integer without a cast [enabled by default]
   get_files_struct_ptr = kallsyms_lookup_name("get_files_struct");
                        ^
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c: In function ‘put_files_struct’:
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c:64:24: warning: assignment makes pointer from integer without a cast [enabled by default]
   put_files_struct_ptr = kallsyms_lookup_name("put_files_struct");
                        ^
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c: In function ‘__lock_task_sighand’:
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c:71:27: warning: assignment makes pointer from integer without a cast [enabled by default]
   __lock_task_sighand_ptr = kallsyms_lookup_name("__lock_task_sighand");
                           ^
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c: In function ‘__alloc_fd’:
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c:78:18: warning: assignment makes pointer from integer without a cast [enabled by default]
   __alloc_fd_ptr = kallsyms_lookup_name("__alloc_fd");
                  ^
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c: In function ‘__fd_install’:
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c:85:20: warning: assignment makes pointer from integer without a cast [enabled by default]
   __fd_install_ptr = kallsyms_lookup_name("__fd_install");
                    ^
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c: In function ‘__close_fd’:
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c:92:18: warning: assignment makes pointer from integer without a cast [enabled by default]
   __close_fd_ptr = kallsyms_lookup_name("__close_fd_ptr");
                  ^
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c: In function ‘can_nice’:
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c:99:16: warning: assignment makes pointer from integer without a cast [enabled by default]
   can_nice_ptr = kallsyms_lookup_name("can_nice");
                ^
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c: In function ‘security_binder_set_context_mgr’:
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c:106:39: warning: assignment makes pointer from integer without a cast [enabled by default]
   security_binder_set_context_mgr_ptr = kallsyms_lookup_name("security_binder_set_context_mgr");
                                       ^
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c: In function ‘security_binder_transaction’:
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c:113:35: warning: assignment makes pointer from integer without a cast [enabled by default]
   security_binder_transaction_ptr = kallsyms_lookup_name("security_binder_transaction");
                                   ^
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c: In function ‘security_binder_transfer_binder’:
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c:120:39: warning: assignment makes pointer from integer without a cast [enabled by default]
   security_binder_transfer_binder_ptr = kallsyms_lookup_name("security_binder_transfer_binder");
                                       ^
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c: In function ‘security_binder_transfer_file’:
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c:127:37: warning: assignment makes pointer from integer without a cast [enabled by default]
   security_binder_transfer_file_ptr = kallsyms_lookup_name("security_binder_transfer_file");
                                     ^
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/deps.c: At top level:
cc1: warning: unrecognized command line option "-Wno-int-conversion" [enabled by default]
  CC [M]  /var/lib/dkms/anbox-modules-binder/6~zesty1/build/binder.o
/var/lib/dkms/anbox-modules-binder/6~zesty1/build/binder.c:46:39: fatal error: uapi/linux/android/binder.h: No such file or directory
 #include <uapi/linux/android/binder.h>
                                       ^
compilation terminated.
/usr/src/linux-headers-3.16.0-4-common/scripts/Makefile.build:262: recipe for target '/var/lib/dkms/anbox-modules-binder/6~zesty1/build/binder.o' failed
make[4]: *** [/var/lib/dkms/anbox-modules-binder/6~zesty1/build/binder.o] Error 1
/usr/src/linux-headers-3.16.0-4-common/Makefile:1354: recipe for target '_module_/var/lib/dkms/anbox-modules-binder/6~zesty1/build' failed
make[3]: *** [_module_/var/lib/dkms/anbox-modules-binder/6~zesty1/build] Error 2
Makefile:181: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.16.0-4-amd64'
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2

asmem--------------------------------------------------------------------------------

DKMS make.log for anbox-modules-ashmem-6~zesty1 for kernel 3.16.0-4-amd64 (amd64)
Mon May 29 14:55:13 EDT 2017
make -C /lib/modules/3.16.0-4-amd64/build V=0 M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-3.16.0-4-amd64'
make[1]: Entering directory `/usr/src/linux-headers-3.16.0-4-amd64'
  LD      /var/lib/dkms/anbox-modules-ashmem/6~zesty1/build/built-in.o
  CC [M]  /var/lib/dkms/anbox-modules-ashmem/6~zesty1/build/deps.o
/var/lib/dkms/anbox-modules-ashmem/6~zesty1/build/deps.c: In function ‘shmem_zero_setup’:
/var/lib/dkms/anbox-modules-ashmem/6~zesty1/build/deps.c:9:24: warning: assignment makes pointer from integer without a cast [enabled by default]
   shmem_zero_setup_ptr = kallsyms_lookup_name("shmem_zero_setup");
                        ^
/var/lib/dkms/anbox-modules-ashmem/6~zesty1/build/deps.c: At top level:
cc1: warning: unrecognized command line option "-Wno-int-conversion" [enabled by default]
  CC [M]  /var/lib/dkms/anbox-modules-ashmem/6~zesty1/build/ashmem.o
/var/lib/dkms/anbox-modules-ashmem/6~zesty1/build/ashmem.c: In function ‘ashmem_read’:
/var/lib/dkms/anbox-modules-ashmem/6~zesty1/build/ashmem.c:316:2: error: implicit declaration of function ‘__vfs_read’ [-Werror=implicit-function-declaration]
  ret = __vfs_read(asma->file, buf, len, pos);
  ^
/var/lib/dkms/anbox-modules-ashmem/6~zesty1/build/ashmem.c: In function ‘ashmem_shrink_scan’:
/var/lib/dkms/anbox-modules-ashmem/6~zesty1/build/ashmem.c:456:3: error: implicit declaration of function ‘vfs_fallocate’ [-Werror=implicit-function-declaration]
   vfs_fallocate(range->asma->file,
   ^
/var/lib/dkms/anbox-modules-ashmem/6~zesty1/build/ashmem.c: At top level:
cc1: warning: unrecognized command line option "-Wno-int-conversion" [enabled by default]
cc1: some warnings being treated as errors
/usr/src/linux-headers-3.16.0-4-common/scripts/Makefile.build:262: recipe for target '/var/lib/dkms/anbox-modules-ashmem/6~zesty1/build/ashmem.o' failed
make[4]: *** [/var/lib/dkms/anbox-modules-ashmem/6~zesty1/build/ashmem.o] Error 1
/usr/src/linux-headers-3.16.0-4-common/Makefile:1354: recipe for target '_module_/var/lib/dkms/anbox-modules-ashmem/6~zesty1/build' failed
make[3]: *** [_module_/var/lib/dkms/anbox-modules-ashmem/6~zesty1/build] Error 2
Makefile:181: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.16.0-4-amd64'
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by simon1tan** [comment]
Just a note for those who are having trouble with the modules, here is what I did to get these compiled and installed on linux kernel 4.15. 
1. Download anbox from github so that you have the ashmem and binder directories. 
2. Extract ashmem and biinder into /usr/src
3. Rename the folders to anbox-ashmem-1 and anbox-binder-1 (the 1 is the version number in dkms.conf)
4. install dkms if not already installed(sudo aptitude install dkms)
5. sudo dkms add -m anbox-binder -v 1
6. sudo dkms build -m anbox-binder -v 1
7. sudo dkms install -m anbox-binder -v 1
8. sudo modprobe ashmem-linux binder-linux

**Comment by anysz** [comment]
@simon1tan 
the `sudo aptitude install dkms` is removing my apt :(
but that method is working :D 
I still curious why its removing my apt :/

**Comment by thanasxda** [comment]
same issue. manually running make & make install works for ashmem but not for binder (compilation issue, changes makeflags with -Wno-error but persisted). tried all the above but still am having the binder issue. currently running latest stable mainline kernel anbox-modules-dkms doesn't install either.

**Comment by ChrisRoald** [comment]
instruction 8: sudo modprobe ashmem-linux binder-linux
produces ' modprobe: ERROR: could not insert 'ashmem_linux': Operation not permitted '

**Comment by thanasxda** [comment]
https://github.com/thanasxda/anbox-modules-fix try this

**Comment by rrakso** [comment]
On `Ubuntu 20.10` i needed to do https://github.com/anbox/anbox/issues/1570#issue-680639349 and ANBOX works for me! :tada: 

#### Reference 
  - [Install Anbox >> Have necessary kernel support >> On current Debian (from Buster) or Ubuntu (from 18.04)](https://github.com/anbox/anbox/blob/master/docs/install.md#on-current-debian-from-buster-or-ubuntu-from-1804)
