### ISSUE TITLE
cannot communicate with server: Post http://localhost/v2/snaps/anbox-installer: dial unix /run/snapd.socket: connect: connection refused

### ISSUE THREAD

**Issue by saranyaproz** [anbox/anbox#265]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by saranyaproz** [comment]
I am using linux 16.04. Am try to install anbox installer via snapd but am getting an error.cannot communicate with server: err:Post http://localhost/v2/snaps/anbox-installer: dial unix /run/snapd.socket: connect: connection refused.
so how can i solve this.if knows anyone help me plz

**Comment by morphis** [comment]
This isn't really a problem with Anbox but with the snapd project. Can you ask at https://forum.snapcraft.io/ for help? Thanks!

**Comment by gsagar4145** [comment]
Type this first
## systemctl restart snapd.service
then your snap command.

**Comment by Frankjnr** [comment]
It worked for me thanks.

**Comment by malwareoverflow** [comment]
worked for me too thanks alot

**Comment by muhammadtalhaqamar** [comment]
can not working

**Comment by Onebigbera** [comment]
yea it worked! thanks a lot

**Comment by pankajyoctal** [comment]
Try this.. hope it works
sudo apt-get purge snapd
sudo apt-get install snapd

**Comment by yuri-lisboa** [comment]
Restart snap works for me

`sudo systemctl restart snapd.service`

**Comment by Igordio** [comment]
Thanks!! It worked

**Comment by katesinclari91** [comment]
It worked. i am using kali linux 2020.1

**Comment by Chaguala** [comment]
This commands didn't work for me
sudo apt-get purge snapd
sudo apt-get install snapd
sudo systemctl restart snapd.service

**Comment by Chaguala** [comment]
Any another soluction?

**Comment by rmogusu** [comment]
Thank you they worked for me
sudo apt-get purge snapd
sudo apt-get install snapd

**Comment by wptechprodigy** [comment]
I am using Ubuntu on WSL2 and each time I tried:
 `systemctl restart snapd.service` or `sudo  systemctl restart snapd.service`

I get this message:
```
System has not been booted with systemd as init system (PID 1). Can't operate.
```

I am trying to install hub on Ubuntu and I cannot run the command: 

```
sudo snap install hub --classic
```
successfully.

Any help?

**Comment by alaminshakeel** [comment]
@pankajyoctal it worked !! thanks

**Comment by ahmedmahershaaban** [comment]
> Type this first
> ## systemctl restart snapd.service
> 
> then your snap command.

It worked for me thanks.

**Comment by ft-hero** [comment]
Thank you they worked for me

**Comment by activeliang** [comment]
**Does anyone run ubuntu with docker like me?**
The problem I encountered was that systemctl started abnormally.

command:
```
/etc/init.d/dbus start
systemctl status
```
output logs: `Failed to list units: Launch helper exited with unknown return code 1`
**Resolve:**
restart docker container like this:
```
docker run -tid --user root --name test_2 --privileged=true ubuntu:16.04 /sbin/init
docker exec -it test_2 /bin/bash
```
it works for me!
referens: [https://blog.csdn.net/f_zyj/article/details/93378737]( https://blog.csdn.net/f_zyj/article/details/93378737)

**Comment by AnwarKamel** [comment]
Try this command:
`systemctl restart snapd.service`

**Comment by Fuseteam** [comment]
@wptechprodigy seems wsl is missing systemd so the snap won't work, you might want to contact the wsl developers about it

**Comment by waseem602** [comment]
> Try this.. hope it works
> sudo apt-get purge snapd
> sudo apt-get install snapd

thanks a lot and love
it worked very exact for me

**Comment by mshahrin** [comment]
> Type this first
> 
> ## systemctl restart snapd.service
> then your snap command.

Thank you so much <3 <3 <3 <3 <3

**Comment by SheyiB** [comment]
Thanks <3 worked for me

**Comment by sakurawald** [comment]
> Try this command: `systemctl restart snapd.service`

This works.
