### ISSUE TITLE
Loop devices after uninstall

### ISSUE THREAD

**Issue by jhivan** [anbox/anbox#267]
Hey. I've uninstalled anbox (a couple of times) but 4 Loop devices are still there. How do i get rid of them?

**Comment by PurpleBlurr** [comment]
@jhivan  Please kindly guide me on how you uninstalled anbox. I would like to uninstall and re-install with the current version. Thank you

**Comment by helloray** [comment]
If you mean loop device in mount, you can remove them by snap.
/dev/loop0         83456     83456         0  100% /snap/core/2844
/dev/loop1           128       128         0  100% /snap/anbox-installer/17

~$ snap list
Name             Version    Rev   Developer  Notes
anbox-installer  1          17    morphis    classic
core             16-2.27.6  2844  canonical  core
~$ sudo snap remove anbox-installer
anbox-installer removed
~$ snap list
Name  Version    Rev   Developer  Notes
core  16-2.27.6  2844  canonical  core

**Comment by imknown** [comment]
![screenshot_2017-09-19_09-11-01](https://user-images.githubusercontent.com/5681447/30571464-882f073c-9d1a-11e7-80cf-2b0f326392ae.png)

@helloray Just like these.

**Comment by helloray** [comment]
It seems snap core can not be removed. Try to find some help on https://snapcraft.io/
