### ISSUE TITLE
Secure boot enabled

### ISSUE THREAD

**Issue by ArmeF97** [anbox/anbox#268]
**Please describe your problem:**
It tells me to disable secure boot. But the secure boot is ALREADY disabled! So the installer can't detect it.

**What were you expecting?:**
That the anbox-installer detects if the system is already in boot secure disabled

Or maybe the installer just removed it. I don't know. Someone please explain

**Comment by gasinvein** [comment]
Wait a sec... Anbox tells you to disable secure boot?

**Comment by Mistero5050** [comment]
Anbox-installer
