### ISSUE TITLE
Ship microG GmsCore

### ISSUE THREAD

**Issue by h4ndshake** [anbox/anbox#27]
"microG GmsCore is a FLOSS (Free/Libre Open Source Software) framework to allow applications designed for Google Play Services to run on systems, where Play Services is not available."

I guess that is a good alternative to Google Play Services on Anbox, you should take a look

[microG](https://github.com/microg/android_packages_apps_GmsCore)

**Comment by M1cha** [comment]
Another option would be a port of TWRP so we can just install opengapps.

**Comment by morphis** [comment]
I didn't knew about microG before. Quite interesting project.

However, for Anbox as a project the best option is to not ship any store by default for now. The project is still in its early phase and shipping a store will also have impact on the legal side of things. That said we will try to make it easy for users to install additional software like Fdroid or microG. Fdroid only requires installation of an APK and microG looks similar. You can install both already today with adb and there is a plan to make this easier by implementing support for apk installation directly into the `anbox` command line utility.

**Comment by rugk** [comment]
In this case this is not a "wontfix", but a "will be fixed in the future", is not it?

**Comment by kennethso168** [comment]
While I understand the contributors of not including any store, I would like to clarify a bit.
"Google Play Services" <> "Google Play”. Google Play Services (and microG) is NOT a store. As defined by Wikipedia, "Google Play Services is a proprietary background service and API package for Android devices." It includes APIs such as the Maps and Locations API. It just happens that Google Play depends on the services and so the confusion arises. A lot of apps that depend on the services may break without the services installed. And that's a reason why microG exists to provide an FOSS replacement to the services.
I think microG might need something more than installing an apk from adb (such as signature spoofing), but I'm not sure as I haven't tried it. Anyway, such integration would be great, not for easy installation of apps, but better compatibility of apps.

**Comment by M1cha** [comment]
@morphis why don't you/we just make it easy to install gapps? That's exactly how custom ROM's like lineageOS do it and you won't have any legal issues.

**Comment by Silent-Hunter** [comment]
Does Google care if end users install gapps without a license? I wouldn't imagine there would be any issues with providing instructions to get them from Google.

**Comment by rugk** [comment]
No Google does not care. Every Custom ROM does it. Just go to http://opengapps.org/, grap your ZIP and flash it. That's the way it could also be used in Anbox.

**Comment by morphis** [comment]
@kennethso168 Don't get me wrong. I am not against anyone using microg or other things like fdroid but we as the Anbox project don't want to dictate our users what they should use. We want to ship clean AOSP with necessary enhancements to make the installation of things like microg or fdroid easy on the users choice once Anbox is installed on a system. That's it.

**Comment by h4ndshake** [comment]
@morphis Custom ROM devs doesn't ship GApps due to legal issues, YOU are choosing to make this changes, no one is responsible for what YOU does. But.. if a ROM ship GApps, they're responsible for it.

**Comment by h4ndshake** [comment]
and @morphis while it's true that microG only need a few apk installations, it's true that it need a system patch too, to enable signature spoofing..

but this is a security issue, am i right?

**Comment by rugk** [comment]
@h4ndshake Yes, that's what I said. I just described the process how _you_ can do it… :smiley:

**Comment by Null-Senpai** [comment]
> necessary enhancements to make the installation of things like microg or fdroid easy on the users choice once Anbox is installed on a system

Just a question here, while I completely understand the 'vanilla' approach, I wondering how end-users would go about installing microg. Specifically the 'signature spoofing' part.
On actual android, end users can patch framework.jar. If one tries patching that file from Anbox however, the patcher ([tingle](https://github.com/ale5000-git/tingle) in my case) throws an error about the ROM possibly being 'odexed' as no 'dex' files are found.
I would be very grateful for any info as to how to proceed. 

PS: I would suggest including signature spoofing support into the actual image. While you could do it in a 'it's just enabled' way, which might be a security issue, there should be a better way to do it so not all apps automatically get permission to spoof signatures. Some ROMs have implemented it in such a way that apps first ask, like they would to access your storage (or if they do not, the user has to grant them permission using ADB).

**Comment by uudruid74** [comment]
It wouldn't help with microG, but the goal is to get SOME sort of play services working.  Method 1 = Find a way to manually copy the files into the android image and set permissions.  Method 2 = Implement signature spoofing and lots of custom coding ... and this means having a custom android image to maintain (not likely to happen), or method 3 = have the Anbox installer give an option to root the image so we can install flashfire and then flash Play services or any of the countless other mods available ourselves (substratum, xposed, etc).  Method 4 would be to port the updater language that twrp uses (I forget the name, but its open source) and make a stand-alone for linux that would allow flashing to an image file from the command line ... I'm surprised this doesn't exist already!

So ... your option requires the most work and targets only a subset of users

**Comment by null-von-sushi** [comment]
Hmm, I agree that having some sort of easy root method is the first step to anything. While a ported TWRP would probably be very useful for other projects too, it's probably too much effort and would take away resources from the actual Anbox software?

Personally I'd suggested going wit Method 3, but also ship the rom de-odexed. This should not be too much effort and shouldn't require any custom code I imagine, but would allow the end user to use the root access to patch the framework themselves with [tingle](https://github.com/ale5000-git/tingle) or similar.

**Comment by awaken1ng** [comment]
I have tried applying [microG provided signature spoofing patch](https://github.com/microg/android_packages_apps_GmsCore/tree/master/patches), it seem to work just fine


<details>
  <summary>And it does ask for permission</summary>

  ![Picture](https://user-images.githubusercontent.com/20689137/56050120-3bf54f80-5d75-11e9-8476-5884bde01238.png)

</details>
<details>
  <summary>Doesn't seem to show up in application info though</summary>

  ![Picture](https://user-images.githubusercontent.com/20689137/56050349-d8b7ed00-5d75-11e9-8a1e-2d7a97d58cb2.png)

</details>
<details>
  <summary>microG works</summary>

  ![Picture](https://user-images.githubusercontent.com/20689137/56050494-46fcaf80-5d76-11e9-80e9-45f97bbf43f3.png)

</details>

*^ Those are folded screenshots*

[Fake Store](https://github.com/microg/android_packages_apps_FakeStore) didn't ask for permission though, need to manually grant it with adb:
`adb shell pm grant com.android.vending android.permission.FAKE_PACKAGE_SIGNATURE`
For the sake of completion, to revoke:
`adb shell pm revoke com.android.vending android.permission.FAKE_PACKAGE_SIGNATURE`

**Comment by rugk** [comment]
@awaken1ng Great! :tada: So given that tests, it should possibly be easy to ship it by default like this or at least as an option… (in case someone wants 100% without Google or "original" Play Services)

**Comment by A-Shahbazi** [comment]
@morphis 
According to what @awaken1ng said it doesn't seem much of a security issue as user is asked for the permission. Are you going to add signature spoofing in android.img?
If you still find it unacceptable contrary to what is said, can you at least build the android.img deodexed so that one is able to patch the neccasary .jar file using [Tingle](https://github.com/ale5000-git/tingle) and use it with --use-rootfs-overlay?
It's not currently possible to use the project for odexed roms and it will be rather a pain to implement(deodex->patch->odex).

**Comment by DeepAQ** [comment]
Actually it is not that difficult to patch the framework. The only file that needs to be patched is `/system/framework/services.jar`, and it can be patched with the following steps:

1. Copy jar file `/system/framework/services.jar` and odex file `/system/framework/oat/x86_64/services.odex` from Anbox system image.
2. Use [smali](https://github.com/JesusFreke/smali) to deodex and assemble `classes.dex`, then zip it into `services.jar`.
3. Use a patching tool (I used [haystack](https://github.com/Lanchon/haystack)) to apply patches to the `services.jar`.
4. Enable rootfs-overlay and replace `/system/framework/services.jar` with the patched one.

After these steps, signature spoofing should be enabled and microG should be working.

Here is a link of my patched file: https://drive.google.com/file/d/13bx6I3TJoyCgb6ck2dwhrHTiOpcnj-YR/view?usp=sharing . **Please note that I do not guarantee that it will work on every system.**

**Comment by c0nn0r** [comment]
I'm trying to get microG setup on my anbox install and after reading this thread it looks to be possible.

For those that have successfully patched the correct files - could you list the steps you took to make it happen?

eg. where to find the file that needs to be patch, and what tool you used to patch.


<pre-apologises for potentially dumb questions>

**Comment by okias** [comment]
@morphis would be nice to have Signature spoofing patch inside ANBOX, since soon it'll be distributed together with linux phones ( Librem 5 and PinePhone). On these open-source phones will be microG often used, so this feature would be really appriciated

**Comment by dnut** [comment]
I agree with @morphis's conclusion that installing microG or Google Play Services is the user's responsibility. It would be inappropriate to force users to accept one solution.

> not ship any store ... microg or other things like fdroid 

I'm not sure if you read @kennethso168's comment. Google Play Services and microG are not stores. They are implementations of APIs that most popular apps will not work without. These libraries are fundamental to a fully functioning Android OS.

Since these libraries are so important, Anbox should enable users to install them. If I were in charge of this project, I would dedicate resources to test compatibility. Plus I would look into developing tools (or compatibility with pre-existing tools) that can aid the installation process.

**Comment by baptx** [comment]
> @morphis why don't you/we just make it easy to install gapps? That's exactly how custom ROM's like lineageOS do it and you won't have any legal issues.

There is an easy solution to install Google Play Store / Services with this script: https://github.com/geeks-r-us/anbox-playstore-installer

**Comment by baptx** [comment]
@M1cha There is an easy solution to install Google Play Store / Services with this script: https://github.com/geeks-r-us/anbox-playstore-installer

**Comment by eudoxos** [comment]
> Actually it is not that difficult to patch the framework. The only file that needs to be patched is `/system/framework/services.jar`, and it can be patched with the following steps:
>   […]
>   2. Use smali to deodex and assemble classes.dex, then zip it into services.jar.
>   3. Use a patching tool (I used haystack) to apply patches to the services.jar.

@DeepAQ, would you mind writing out the commands for step 2 and 3? I can run this (it includes download of smali, baksmali and dex-tools, unpacking android.img and running those):
```sh
#!/bin/bash
sudo rm -rf squashfs-root
sudo unsquashfs /snap/anbox/current/android.img
ln -s -f squashfs-root/system/framework/x86_64/*.oat . # these must be in classpath which can't be set when running java -jar
wget -c https://bitbucket.org/JesusFreke/smali/downloads/smali-2.5.2.jar https://bitbucket.org/JesusFreke/smali/downloads/baksmali-2.5.2.jar https://github.com/pxb1988/dex2jar/releases/download/2.0/dex-tools-2.0.zip
unzip -o dex-tools-2.0.zip
chmod a+x dex2jar-2.0/d2j_invoke.sh
java -jar baksmali-2.5.2.jar deodex squashfs-root/system/framework/oat/x86_64/services.odex -o services.out
java -jar smali-2.5.2.jar -o services.dex assemble services.out
bash dex2jar-2.0/d2j-dex2jar.sh services.dex --force -o services.jar
```
which gets me `services.dex`. Is that correct? And then, how did you patch with haystack? It looks like a mighty tool and I don't know which end to take.
