### ISSUE TITLE
segfault at start session-manager, opensuse tumbleweed

### ISSUE THREAD

**Issue by luizlinux** [anbox/anbox#278]
# Information for package anbox:
Repository : Anbox (openSUSE_Tumbleweed)
Name        : anbox
Version     : 0.0.1.git20170515
Release     : 15.1
Architecture: x86_64
Size        : 3915240
Vendor      : obs://build.opensuse.org/home:gasinvein

anbox system-info: https://gist.github.com/luizlinux/707f60a3aa6833f502509baef22223e4

systemctl status anbox-container-manager.service: https://gist.github.com/luizlinux/31d2c478bfde4a5b40187a0fdacb7e7f

journalctl from start of anbox-container-manager.service: https://gist.github.com/luizlinux/19699ec4470c43a43f515efe6a8617e0

Debug messages from starting anbox session-manager: https://gist.github.com/luizlinux/20497a69cc983ccb0c02999295710b8f

Strace messages from starting anbox session-manager: https://gist.github.com/luizlinux/ab94382f5fe69a31aa6402e5f82f750e

Given that issue #205 is related to an earlier build anbox (0.0.1.git20170427-42.2) and that the issue reporter, two-dogs, stated that the segfault issue went away for him, I decided to open a new issue as it might be unrelated.

Although anbox session-manager says core dumped after segfaulting, I couldn't find the core on the working directory I was at. If the core is dumped to a specific path and if its useful let me know and I'll upload it to this issue.

**Comment by gasinvein** [comment]
I updated the repo to current git master, it should build packages soon. Can you check if the segfault still occurs with latest version?
Also, maybe #279 and/or #280 are related?

**Comment by luizlinux** [comment]
Will do. I'll post the results as soon as I do. Thanks.

**Comment by luizlinux** [comment]
Updated packages to the following:

- anbox-modules-dkms-0.0.1.git20170517-21.1.noarch
- anbox-0.0.1.git20170517-21.1.x86_64

zypper update output: https://gist.github.com/luizlinux/cf7676f870d40e091df3c0659a95dc7c

Unfortunatelly, I'm still getting segfaults at starting anbox session-manager:
```
[DD 2017-05-21 18:03:18] [gl_renderer_server.cpp:82@GLRendererServer] Using GLES-to-GL translator for rendering
[DD 2017-05-21 18:03:18] [Renderer.cpp:113@initialize] EGL doesn't support surfaceless context
[DD 2017-05-21 18:03:18] [Renderer.cpp:249@initialize] Successfully initialized EGL
Floating point exception (core dumped)
```
Let me know if you need any additional info.
Thanks.

**Comment by Mistero5050** [comment]
Same output. Floating point exception (core dumped) not yet because it's still stuck, but I think this is the issue.
Maybe, @luizlinux  you are right. What can I do? Reinstall? It can't be XFCE because it worked 2 weeks ago.

**Comment by Mistero5050** [comment]
Same output as @luizlinux

**Comment by luizlinux** [comment]
Updated packages to the following:

- anbox-modules-dkms-0.0.1.git20170523-23.1.noarch
- anbox-0.0.1.git20170523-23.1.x86_64

Unfortunatelly, I'm still getting segfaults at starting anbox session-manager:
```
[DD 2017-05-23 19:56:10] [gl_renderer_server.cpp:82@GLRendererServer] Using GLES-to-GL translator for rendering                                      
[DD 2017-05-23 19:56:10] [Renderer.cpp:112@initialize] EGL doesn't support surfaceless context                                                       
[DD 2017-05-23 19:56:10] [Renderer.cpp:248@initialize] Successfully initialized EGL                                                                  
Floating point exception (core dumped)
```
@gasinvein Please let me know if there is anything else I could help you with.

**Comment by gasinvein** [comment]
@luizlinux, did you try official snap-based build? I guess the problem is not in my build, but who knows.

**Comment by luizlinux** [comment]
@gasinvein Trying that now. Will post results shortly.

**Comment by luizlinux** [comment]
@gasinvein Sorry for the delay, I had to figure out how to get it all working with the snap build.
Anyways, no segfault on the snap anbox session-manager.
Maybe there's something funky going on with your build. :(

**Insmoding _your_ build kernel modules - ok:**
```
# insmod /lib/modules/4.4.62-18.6-default/updates/ashmem_linux.ko
# insmod /lib/modules/4.4.62-18.6-default/updates/binder_linux.ko
# lsmod | grep _linux
ashmem_linux           16384  0 
binder_linux          106496  2
#
```
**Starting snap's anbox container manager - ok:**
```
/snap/bin/anbox container-manager --data-path=/var/lib/anbox --android-image=/snap/anbox/current/android.img --privileged
[WW 2017-05-24 01:50:04] [container_manager.cpp:58@operator()] You are running the container manager manually which is most likely not
[WW 2017-05-24 01:50:04] [container_manager.cpp:59@operator()] what you want. The container manager is normally started by systemd or
[WW 2017-05-24 01:50:04] [container_manager.cpp:60@operator()] another init system. If you still want to run the container-manager
[WW 2017-05-24 01:50:04] [container_manager.cpp:61@operator()] you can get rid of this warning by starting with the --daemon option.
[WW 2017-05-24 01:50:04] [container_manager.cpp:62@operator()] 
[WW 2017-05-24 01:50:16] [lxc_container.cpp:90@setup_network] Anbox bridge interface 'anbox0' doesn't exist. Network functionality will not be available
```
***Starting snap's anbox session-manager - ok:***
```
$ ANBOX_LOG_LEVEL=debug /snap/bin/anbox session-manager
[DD 2017-05-24 01:52:08] [gl_renderer_server.cpp:82@GLRendererServer] Using GLES-to-GL translator for rendering
[DD 2017-05-24 01:52:08] [Renderer.cpp:112@initialize] EGL doesn't support surfaceless context
[DD 2017-05-24 01:52:08] [Renderer.cpp:248@initialize] Successfully initialized EGL
```
***Starting snap' anbox launch - ok [sort of]:***
```
$ ANBOX_LOG_LEVEL=debug /snap/bin/anbox launch
[DD 2017-05-24 01:56:57] [launch.cpp:175@operator()] Android hasn't fully booted yet. Waiting a bit ..
[WW 2017-05-24 02:00:57] [launch.cpp:189@operator()] Stopped waiting as we've already waited for too long. Something
[WW 2017-05-24 02:00:57] [launch.cpp:190@operator()] is wrong with your setup or the container has failed to boot.
[WW 2017-05-24 02:00:57] [launch.cpp:191@operator()] If you think you found a bug please don't hesitate to file on
[WW 2017-05-24 02:00:57] [launch.cpp:192@operator()] at https://github.com/anbox/anbox/issues/new
```
Maybe anbox launch didn't work all the way because of the missing bridge interface anbox0 which I haven't [yet] figure out how to start.

**Comment by gasinvein** [comment]
@luizlinux, I just installed older kernel and tried my build of Anbox, and everything seem fine. Do yo have any C++-related repositories enabled or anything else may be related?
Also, to enable core dump saving for user, run `ulimit -c unlimited`, *then* launch session-manager, and then find anbox's dumps in `/var/lib/systemd/coredump`

**Comment by luizlinux** [comment]
_Do you have any C++-related repositories enabled or anything else which may be related?_
As a matter of fact I do:
```
# zypper repos
Repository priorities are without effect. All enabled repositories share the same priority.

#  | Alias                               | Name                                    | Enabled | GPG Check | Refresh
---+-------------------------------------+-----------------------------------------+---------+-----------+--------
 1 | GNOME:Apps                          | GNOME:Apps                              | Yes     | (r ) Yes  | Yes    
 2 | GNOME:Factory                       | GNOME:Factory                           | No      | ----      | ----   
 3 | dvd                                 | dvd                                     | No      | ----      | ----   
 4 | google-chrome                       | google-chrome                           | Yes     | (r ) Yes  | Yes    
 5 | http-download.opensuse.org-1bbda624 | home:cornelisbb                         | Yes     | (r ) Yes  | Yes    
 6 | http-download.opensuse.org-22e6d674 | devel:languages:perl                    | Yes     | (r ) Yes  | Yes    
 7 | http-download.opensuse.org-354ceccd | games:tools                             | Yes     | (r ) Yes  | Yes    
 8 | http-download.opensuse.org-41ab39e8 | Virtualization                          | Yes     | (r ) Yes  | Yes    
 9 | http-download.opensuse.org-4cfe0c02 | devel:languages:ocaml                   | Yes     | (r ) Yes  | Yes    
10 | http-download.opensuse.org-696e0183 | home:ecsos                              | Yes     | (r ) Yes  | Yes    
11 | http-download.opensuse.org-6f52e256 | home:Lazy_Kent                          | Yes     | (r ) Yes  | Yes    
12 | http-download.opensuse.org-86a98220 | devel:libraries:c_c++                   | Yes     | (r ) Yes  | Yes
13 | http-download.opensuse.org-b8423f7b | artwork:wallpapers                      | Yes     | (r ) Yes  | Yes    
14 | http-download.opensuse.org-bf210241 | home:gasinvein:anbox                    | Yes     | (r ) Yes  | Yes    
15 | http-download.opensuse.org-ccf9beb4 | home:MargueriteSu                       | Yes     | (r ) Yes  | Yes    
16 | http-download.opensuse.org-d634939c | devel:tools                             | Yes     | (r ) Yes  | Yes    
17 | http-download.opensuse.org-dfaf3200 | home:psifidotos                         | Yes     | (r ) Yes  | Yes    
18 | opera                               | Opera packages                          | Yes     | (r ) Yes  | Yes    
19 | packman                             | packman                                 | Yes     | (r ) Yes  | Yes    
20 | repo-debug                          | openSUSE-Leap-42.2-Debug                | No      | ----      | ----   
21 | repo-debug-non-oss                  | openSUSE-Leap-42.2-Debug-Non-Oss        | No      | ----      | ----   
22 | repo-debug-update                   | openSUSE-Leap-42.2-Update-Debug         | No      | ----      | ----   
23 | repo-debug-update-non-oss           | openSUSE-Leap-42.2-Update-Debug-Non-Oss | No      | ----      | ----   
24 | repo-non-oss                        | openSUSE-Leap-42.2-Non-Oss              | Yes     | (r ) Yes  | Yes    
25 | repo-oss                            | openSUSE-Leap-42.2-Oss                  | Yes     | (r ) Yes  | Yes    
26 | repo-source                         | openSUSE-Leap-42.2-Source               | No      | ----      | ----   
27 | repo-source-non-oss                 | openSUSE-Leap-42.2-Source-Non-Oss       | No      | ----      | ----   
28 | repo-update                         | openSUSE-Leap-42.2-Update               | Yes     | (r ) Yes  | Yes    
29 | repo-update-non-oss                 | openSUSE-Leap-42.2-Update-Non-Oss       | Yes     | (r ) Yes  | Yes    
30 | snappy                              | snappy                                  | Yes     | (r ) Yes  | No
# 
```
This is what I currently have installed from there:
```
# zypper search -i -r devel:libraries:c_c++
Loading repository data...
Reading installed packages...

S | Name                           | Summary                              | Type   
--+--------------------------------+--------------------------------------+--------
i | boost-license1_64_0            | Boost License                        | package
i | libboost_filesystem1_64_0      | Boost.Filesystem Runtime Libraries   | package
i | libboost_iostreams1_64_0       | Boost.IOStreams Runtime Libraries    | package
i | libboost_log1_64_0             | Boost.Log runtime Run-Time library   | package
i | libboost_program_options1_64_0 | Boost.ProgramOptions runtime library | package
i | libboost_regex1_64_0           | Boost.Regex runtime library          | package
i | libboost_system1_64_0          | Boost.System runtime library         | package
i | libboost_thread1_64_0          | Boost.Thread runtime libraries       | package
# 
```

**Comment by gasinvein** [comment]
Try disabling devel:libraries:c_c++ and downgrading boost libraries to ones from default repo.

**Comment by luizlinux** [comment]
Did it, anbox won't install as it requires boost versions 1.64 and the opensuse repos only provide 1.54:
```
# zypper in anbox
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libboost_filesystem.so.1.64.0()(64bit) needed by anbox-0.0.1.git20170523-29.1.x86_64
 Solution 1: do not install anbox-0.0.1.git20170523-29.1.x86_64
 Solution 2: break anbox-0.0.1.git20170523-29.1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c): c
# 
```
**Currently installed downgraded boost libs:**
```
# zypper search -i | grep boost
i  | boost-license1_54_0                        | Boost License                                                                         | package    
i  | libboost_date_time1_54_0                   | Boost::Date.Time Runtime libraries                                                    | package    
i  | libboost_filesystem1_54_0                  | Boost::Filesystem Runtime Libraries                                                   | package    
i  | libboost_iostreams1_54_0                   | Boost::IOStreams Runtime Libraries                                                    | package    
i  | libboost_system1_54_0                      | Boost::System Runtime Libraries                                                       | package    
i  | libboost_thread1_54_0                      | Boost::Thread Runtime Libraries                                                       | package    
i  | openSUSE-2017-367                          | Recommended update for boost                                                          | patch      
# 
```

**Comment by luizlinux** [comment]
Core Dump from last attempt of running anbox session-manager using 1.64 boost libs
[core.anbox.1000.2b6629d22f084b0a8173715fb8356fba.29410.1495648829000000.zip](https://github.com/anbox/anbox/files/1026610/core.anbox.1000.2b6629d22f084b0a8173715fb8356fba.29410.1495648829000000.zip)

**Comment by gasinvein** [comment]
> opensuse repos only provide 1.54

Are you sure you are using tumbleweed? It actually [provides 1.64](https://build.opensuse.org/package/binaries/openSUSE:Factory/boost?repository=snapshot).

**Comment by luizlinux** [comment]
I most certainly am a very special kind of stupid. I'm sorry, I'm running Leap 42.2.

**Comment by gasinvein** [comment]
@luizlinux, then seems like you have installed tumbleweed's build of Anbox over Leap 42.2.

Anyway, I just tried my build of Anbox in fresh install of opensuse Leap 42.2 in a VM and found that anbox session-manager segfaults in very similar way as yours, while in the same VM updated to tumbleweed no segfault occurs. Seems like either libboost in devel:libraries:c_c++ for Leap 42.2 is broken or it triggers some bug in Anbox.
Sadly, Anbox requires at least boost 1.58, so I can't do anything about the problem.

**Comment by luizlinux** [comment]
**Update:**
Got anbox from snap [--edge --devmode] running on Open Suse 42.2, using @gasinvein kernel modules,  [this script](https://github.com/anbox/anbox/blob/master/scripts/anbox-bridge.sh) and lib boost from devel:libraries:c_c++ repository.

There apears to be some composite misbehaviour between anbox and KDE producing black areas and removing transparencies. But all in all it works pretty well performance wise.

Here you see my desktop running KDE in all of its composite glory [notice the shadows and transparencies]:
![screenshot_20170525_151120](https://cloud.githubusercontent.com/assets/10618435/26464046/ca56b02a-415c-11e7-89a1-55b7af690a48.png)
You can also see from the above screenshot that as I'm about to launch the org.anbox.appmgr package:
- I got the kernel modules loaded.
- The devices are writeable.
- Anbox bridge is running.
- Anbox container manager is running.
- Anbox session manager is running.

Once the org.anbox.appmgr package is running all composite eye candy is gone and the app window is partially blacked out:
![screenshot_20170525_151138](https://cloud.githubusercontent.com/assets/10618435/26464044/ca537068-415c-11e7-86a3-6a8133233f30.png)

I figured out that if a drag the app window the balck area stays in place, so dragging it to the left side of the screen reveals all of the window contents:
![screenshot_20170525_151216](https://cloud.githubusercontent.com/assets/10618435/26464047/ca56d7da-415c-11e7-8dc4-26373c734c7e.png)

![screenshot_20170525_151244](https://cloud.githubusercontent.com/assets/10618435/26464045/ca547d46-415c-11e7-94c9-7be1237845c9.png)

Aside from the compositing issues, anbox appears to run just fine using lib boost from the devel:libraries:c_c++ repository.
Perhaps we shoud investigate further.

**Comment by gasinvein** [comment]
@luizlinux if you run snap-based Anbox, it does *not* use your system libraries, so any problem related to boost from this repo will not affect Anbox.
And turning off compositing in kwin looks more like a feature than a bug. Some games also do so to improve performance.

**Comment by luizlinux** [comment]
Oh, I see, thanks for the clarifications @gasinvein.

**Comment by Mistero5050** [comment]
if this is solved, would you mind help me with my error? It's similar to this. https://github.com/anbox/anbox/issues/275

**Comment by gasinvein** [comment]
@Mistero5050 no, this is not solved. What's your distro and boost version?

**Comment by Mistero5050** [comment]
Xubuntu, what do you mean with boost version? Do you mind come to my issue to help, too? Thanks :)

**Comment by gasinvein** [comment]
>what do you mean with boost version
Libboost. Never mind, what Ubuntu version?

**Comment by Mistero5050** [comment]
I don't know how, but now `anbox session-manager` and `env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/anbox_anbox.desktop /snap/bin/anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity`
 gives no output... only running forever...

**Comment by david2896482** [comment]
@Mistero5050  maybe you can use adb logcat to see what happening inside the Android OS

**Comment by ferbar** [comment]
Change the title of this issue to SIGFPE or floating point exception, please. Your problem is not an segv.

The reason for the sigfpe is probably that dbus-cpp was compiled with gcc 4.8 and anbox with gcc 5.3.
