### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by ewoks** [anbox/anbox#284]
Hi,

any plans for MacOS support?

**Comment by JLIT0** [comment]
As far as I know, that's impossible as Anbox uses the native Linux kernel to run the Android runtime.  The Darwin kernel would not be able to execute the runtime without serious modifications.

**Comment by ewoks** [comment]
Thanks for answer.. Supposed there are limitation

**Comment by morphis** [comment]
This is definitely not going to happen with Anbox due to various limiations. Running Anbox inside a Linux VM on Mac OS is possible though ..

**Comment by velo** [comment]
@morphis what about using docker to run anbox on mac?
That would probably also enable the project to be executed on Windows too

**Comment by elliott-wen** [comment]
Technically anbox is still relying on linux kernel, especially ashmem and binder modules. Therefore, I highly suspect that one can run android using docker in Mac and windows. At least a qemu is required. Correct me if I am wrong

**Comment by hiberabyss** [comment]
@elliott-wen In fact, docker for mac runs on a Linux kernel.

**Comment by elliott-wen** [comment]
I reckon the kernel is then run in a virtual machine?

**Comment by nmrshll** [comment]
it is run in a virtual machine called xhyve (it's hyper-v on windows and hyperkit on mac)
Basically you have one virtual machine that runs linux and hosts your docker daemon and all your docker containers
But it's all done automatically for you with docker-for-mac / docker-for-windows

So it does open the possibility of running anbox on mac/windows, but it's surely going to need some serious work and testing anyways.

**Comment by Adyan424** [comment]
u can run it under Noah something like wsl Darwin subsystems for Linux but i personally don't know weather the project is active or not.
