### ISSUE TITLE
anbox not launching, entries in syslog

### ISSUE THREAD

**Issue by locovich** [anbox/anbox#285]
Make sure you are running the latest version of Anbox before reporting an issue.

:~$ snap list
Name   Version  Rev   Developer  Notes
anbox  2        18    morphis    devmode
[...]

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

I see one [similar issue](https://github.com/anbox/anbox/issues/224), but with NO response, not sure why so I'm opening a new one.

** Please paste the result of `anbox system-info` below:**
```
:~$ anbox system-info
libEGL warning: DRI2: failed to authenticate
version: 2
os:
  name: Ubuntu
  version: 16.04.2 LTS (Xenial Xerus)
  snap-based: false
kernel:
  version: Linux version 4.4.0-78-generic (buildd@lgw01-11) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_create_context
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_MESA_configless_context
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
```

**Please describe your problem:**
Anbox is not launching, it returns an error message:
:~$ anbox launch
[WW 2017-05-22 13:58:04] [launch.cpp:185@operator()] Stopped waiting as we've already waited for too long. Something
[WW 2017-05-22 13:58:04] [launch.cpp:186@operator()] is wrong with your setup or the container has failed to boot.
[WW 2017-05-22 13:58:04] [launch.cpp:187@operator()] If you think you found a bug please don't hesitate to file on
[WW 2017-05-22 13:58:04] [launch.cpp:188@operator()] at https://github.com/anbox/anbox/issues/new

I see the container manager and session manager services running.
:~$ ps ax | grep anbox
 1171 ?        Ssl    0:00 /snap/anbox/18/usr/bin/anbox container-manager --data-path=/var/snap/anbox/common/ --android-image=/snap/anbox/18/android.img --daemon
12420 ?        Ssl    0:09 /snap/anbox/18/usr/bin/anbox session-manager
12440 ?        Ss     0:00 [lxc monitor] /var/snap/anbox/common/containers default
12452 ?        Ss     0:00 /system/bin/sh /anbox-init.sh
12498 ?        Sl     0:00 /system/bin/anboxd
13229 pts/0    S+     0:00 grep --color=auto anbox

**What were you expecting?:**
The app manager window, as seen here: https://cloud.githubusercontent.com/assets/5918526/25043018/ea5c590c-211c-11e7-90e4-3da2ebede398.png

**Additional info:**
I do see this entries in syslog, related to anbox, but I'm not familiar with what they mean.

[...]
box.anbox" pid=12436 comm="anbox" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
May 22 10:44:14 ubuntu kernel: [13027.670537] audit: type=1400 audit(1495460654.003:26321): apparmor="ALLOWED" operation="connect" profile="snap.anbox.anbox" pid=12436 comm="anbox" family="inet" sock_type="stream" protocol=6 requested_mask="connect" denied_mask="connect"
May 22 10:44:15 ubuntu kernel: [13028.671333] audit: type=1400 audit(1495460655.007:26322): apparmor="ALLOWED" operation="create" profile="snap.anbox.anbox" pid=12429 comm="anbox" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
May 22 10:44:15 ubuntu kernel: [13028.671763] audit: type=1400 audit(1495460655.007:26323): apparmor="ALLOWED" operation="connect" profile="snap.anbox.anbox" pid=12429 comm="anbox" family="inet" sock_type="stream" protocol=6 requested_mask="connect" denied_mask="connect"
May 22 10:44:16 ubuntu kernel: [13029.672530] audit: type=1400 audit(1495460656.007:26324): apparmor="ALLOWED" operation="create" profile="snap.anbox.anbox" pid=12435 comm="anbox" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
May 22 10:44:16 ubuntu kernel: [13029.672878] audit: type=1400 audit(1495460656.007:26325): apparmor="ALLOWED" operation="connect" profile="snap.anbox.anbox" pid=12435 comm="anbox" family="inet" sock_type="stream" protocol=6 requested_mask="connect" denied_mask="connect"
[...]

**Comment by locovich** [comment]
I just tried running the version 3 of anbox, as suggested in another issue report. Without luck.

~$ snap refresh --devmode --edge anbox

~$ anbox launch
[EE 2017-05-31 21:09:53] [launch.cpp:48@try_launch_activity] Failed to launch activity: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

Would it help if I move from Ubuntu 16.04 to 17.04?

**Comment by supaplextor** [comment]
~$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity

This is how I launch it. I have a pull request featuring an alias added to .bashrc.  E.g.,

alias android='anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity'

HTH

**Comment by tuxutku** [comment]
i have the same issue and i think its coused by apparmor
after installing apparmor notify via
sudo apt-get install apparmor-notify
i got tons of messages about apparmor blocking anbox
here is my issue
https://github.com/anbox/anbox/issues/370

**Comment by 512yottabytes** [comment]
Same issue on Ubuntu 22.04 x86_64

**Comment by Fuseteam** [comment]
seriously stop commenting on multiple issues
