### ISSUE TITLE
Anbox 23 windows have a black border to the right

### ISSUE THREAD

**Issue by alkisg** [anbox/anbox#287]
Running Anbox beta 15, all is fine. Then I update to the latest edge version 23:
`sudo snap refresh --edge --devmode anbox`

I logout, login again, and now all the Anbox windows have a black border to the right:
https://pasteboard.co/9Gl6KNxqu.png

This border happens at the 900something pixel of the host screen; I mean that if I move the Anbox windows enough to the left, the black border disappears, while if I move them more to the right, the black border grows larger.

It's like Anbox can't draw past the 900th column of pixels in my host screen.

**Comment by morphis** [comment]
Looks like a regression of https://github.com/anbox/anbox/pull/254
