### ISSUE TITLE
Unknown issue Ubuntu MATE 16.04 

### ISSUE THREAD

**Issue by doriandimov** [anbox/anbox#288]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
Segmentation fault (core dumped)

```
 

**Please describe your problem:**

I think my system is not compatible? 
Adb doesn't detect any devies either.
**What were you expecting?:**

To be able to install a simple app and also test some point&click games.
**Additional info:**

**Comment by david2896482** [comment]
Please run the command `anbox system-info`, and paste the result here

**Comment by morphis** [comment]
Closing as not further input from reporter supplied.
