### ISSUE TITLE
Session manager issue

### ISSUE THREAD

**Issue by doriandimov** [anbox/anbox#289]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
My previous issue could have a kernel-version relation so I downgraded a couple of versions. Now I get this:
[EE 2017-05-25 07:03:21] [launch.cpp:161@operator()] Couldn't get a connection with the session manager

```

**Please describe your problem:**
Anbox does launch now. Loads for a minute, turns off.

**What were you expecting?:**
I was expecting more.

**Additional info:**

**Comment by edgarmirandasilva** [comment]
Hi, run "anbox session-manager first" from terminal.

**Comment by morphis** [comment]
@doriandimov Can you please provide the output of `anbox system-info` and describe a bit more which exacts steps you did to install Anbox? Thanks.

**Comment by morphis** [comment]
Closing as no further input from reporter supplied.
