### ISSUE TITLE
compiling on kali

### ISSUE THREAD

**Issue by oyekanwahab** [anbox/anbox#293]
since kali is based on debian decided to give it a try when ever i cmake i do get 
checking for module 'mirclient'
--   package 'mirclient' not found
CMake Error at cmake/FindGMock.cmake:68 (add_dependencies):
  add_dependencies Cannot add target-level dependencies to INTERFACE library
  target "gtest"

and kali is based on x11, is there any way one can run anbox on x11

**Comment by morphis** [comment]
`mirclient` is an optional dependency. You're missing the gtest library on your system. Please have a look at https://github.com/anbox/anbox/blob/master/README.md for a list of required build dependencies.

**Comment by oyekanwahab** [comment]
i have tried to install all dependency
but i don't know the package which contain mirclient
my serach on google says mir is an ubuntu dispaly manager
and kali uses x11 as dispaly manager

**Comment by oyekanwahab** [comment]
i have tried to install all dependency
but i don't know the package which contain mirclient
my search on google says `mir` is an ubuntu display manager and kali uses `x11` as display manager

**Comment by morphis** [comment]
As I said above:

> mirclient is an optional dependency. 

So you don't have to install mirclient if you don't want to use it.

**Comment by oyekanwahab** [comment]
`checking for module 'sdl2'
--   package 'sdl2' not found
CMake Error at /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:341 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:395 (_pkg_check_modules_internal)
  CMakeLists.txt:66 (pkg_check_modules)


-- checking for module 'SDL2_image'
--   package 'SDL2_image' not found
CMake Error at /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:341 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:395 (_pkg_check_modules_internal)
  CMakeLists.txt:67 (pkg_check_modules)


-- checking for module 'dbus-cpp'
--   package 'dbus-cpp' not found
CMake Error at /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:341 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:395 (_pkg_check_modules_internal)
  CMakeLists.txt:68 (pkg_check_modules)


-- checking for module 'dbus-1'
--   found dbus-1, version 1.8.18
-- checking for module 'lxc'
--   package 'lxc' not found
CMake Error at /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:341 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:395 (_pkg_check_modules_internal)
  CMakeLists.txt:70 (pkg_check_modules)


-- checking for module 'properties-cpp'
--   package 'properties-cpp' not found
CMake Error at /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:341 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:395 (_pkg_check_modules_internal)
  CMakeLists.txt:71 (pkg_check_modules)


-- checking for module 'mirclient'
--   package 'mirclient' not found
CMake Error at cmake/FindGMock.cmake:68 (add_dependencies):
  add_dependencies Cannot add target-level dependencies to INTERFACE library
  target "gtest".

Call Stack (most recent call first):
  CMakeLists.txt:92 (find_package)


-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   iostreams
--   system
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   filesystem
--   system
--   unit_test_framework
-- Configuring incomplete, errors occurred!
See also "/root/Downloads/anbox-master/build/CMakeFiles/CMakeOutput.log".
See also "/root/Downloads/anbox-master/build/CMakeFiles/CMakeError.log".`
ok this is the error i get how can i fix it

**Comment by P0oOOOo0YA** [comment]
Any update on this issue? I'm also interested in using anbox on Kali. It would be great to have a wiki about anbox installation on Kali.
