### ISSUE TITLE
binder and ashmem fail to build Ubuntu 17.04

### ISSUE THREAD

**Issue by the-mentor** [anbox/anbox#303]
Both binder and ashmem fail to build when "sudo apt-get install anbox-modules-dkms" installes it fails with the following information:

DKMS make.log for anbox-modules-ashmem-6~zesty1 for kernel 4.10.0-21-generic (x86_64)
Wed May 31 15:21:57 PDT 2017
make -C /lib/modules/4.10.0-21-generic/build V=0 M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-4.10.0-21-generic'
Makefile:660: arch/x86/Makefile: No such file or directory
make[1]: *** No rule to make target 'arch/x86/Makefile'.  Stop.
make[1]: Leaving directory '/usr/src/linux-headers-4.10.0-21-generic'
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2
~                                                

DKMS make.log for anbox-modules-binder-6~zesty1 for kernel 4.10.0-21-generic (x86_64)
Wed May 31 15:21:59 PDT 2017
make -C /lib/modules/4.10.0-21-generic/build V=0 M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-4.10.0-21-generic'
Makefile:660: arch/x86/Makefile: No such file or directory
make[1]: *** No rule to make target 'arch/x86/Makefile'.  Stop.
make[1]: Leaving directory '/usr/src/linux-headers-4.10.0-21-generic'
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2

** Please paste the result of `anbox system-info` below:**
me@system:~$ anbox system-info
version: 2
snap-revision: 25
os:
  name: Ubuntu
  version: 17.04 (Zesty Zapus)
  snap-based: true
kernel:
  version: Linux version 4.10.0-21-generic (buildd@lgw01-12) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) ) #23-Ubuntu SMP Fri Apr 28 16:14:22 UTC 2017
  binder: false
  ashmem: false
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
       

**Please describe your problem:**
Due to this failing i cant use anbox.

Thank you !

**Comment by JoseBarakat** [comment]
Same here:

``~$ anbox session-manager``
``[EE 2017-06-02 19:51:06] [session_manager.cpp:135@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded``

**Comment by supaplextor** [comment]
I ran into something similar and rebuilt these modules. The previous build (from a week old install?) were laying around. file -k didn't show anything significant between this and upstream modules like ipv6. Here's how I fixed this,

  447  apt-get install --reinstall anbox-modules-dkms
  448  history 
  449  history  | grep mod
  450  insmod updates/dkms/binder_linux.ko 
  451  insmod updates/dkms/ashmem_linux.ko 
  452  history | tail
root@hydrogen:/lib/modules/4.8.0-52-generic# lsmod | grep linux
ashmem_linux           16384  0
binder_linux           98304  0

**Comment by JoseBarakat** [comment]
@supaplextor Seems like right now anbox is only working with kernel 4.8.x

**Comment by ryanleesipes** [comment]
Is there any way to address this for newer kernels? I think this definitely stifles adoption of Anbox.

**Comment by JoseBarakat** [comment]
Now it works with at least Linux kernel 4.10.0-22-generic. See #40 for more info. Don't forget to upgrade Anbox to the latest version.

**Comment by morphis** [comment]
Duplicates https://github.com/anbox/anbox/issues/223
