### ISSUE TITLE
anbox-installer stops when apt-get returns warnings and errors on other PPA repositories

### ISSUE THREAD

**Issue by TrevorThaManiac69** [anbox/anbox#304]
I cannot install Anbox properly. The installer stops when apt-get can't find release files and, fails to fetch updates and verify repo signatures.

Is there anyway to force the installation, ignoring the GPG and offline repos?
`W: GPG error: https://repo.skype.com/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1F3045A5DF7587C3
W: The repository 'https://repo.skype.com/deb stable InRelease' is not signed.
W: The repository 'http://ppa.launchpad.net/nesthib/weechat/ubuntu xenial Release' does not have a Release file.
W: The repository 'http://ppa.launchpad.net/visualblocks/mcedit-linux/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/nesthib/weechat/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/visualblocks/mcedit-linux/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Warning:  apt-get update failed for some reason
`
(Encountered on Ubuntu 16.04.2 with all security updates installed)

**Comment by hydargos123** [comment]
Hi,

I got this problem too... how have you solved this ?
thanks

**Comment by TrevorThaManiac69** [comment]
I...I cannot solve it. I decided to set this issue 'closed' because no one commented in this issue.

**Comment by morphis** [comment]
This is actually the wrong repository to track this issue. The problem was fixed with https://github.com/anbox/anbox-installer/pull/35

**Comment by TrevorThaManiac69** [comment]
OK. thnx.
