### ISSUE TITLE
How to install on archlinux or manjaro pls help me??

### ISSUE THREAD

**Issue by hamzamg** [anbox/anbox#305]

**Comment by Object905** [comment]
There is aur packages: [anbox](https://aur.archlinux.org/packages/anbox-git/) and [DKMS modules](https://aur.archlinux.org/packages/anbox-modules-dkms-git/)

**Comment by Object905** [comment]
By the way you may need lts kernel. And even with lts it fails to build sometimes.

**Comment by nickecalifornia** [comment]
Para rodar no arch (usei o yaourt) primeiro instalei os headers da kernel do sistema para o DKMS.
- "yaourt -s linux-headers" (achei a versão compatível com a minha minha kernel - 4.10.12-1-MANJARO)

Depois compilei o anbox com os seguintes pacotes

- "aur/anbox-git"
- "aur/anbox-image"
- "aur/anbox-modules-dkms-git"

I started systemd networks services (for internet to work in apps)
- "sudo systemctl start systemd-resolved.service"
- "sudo systemctl start systemd-networkd.service"

And started the container-manager service
- "sudo systemctl start anbox-container-manager.service"

I added the host driver in /usr/lib/systemd/user/anbox-session-manager.service by changing the line:
- From "ExecStart=/usr/bin/anbox session-manager"
- To "ExecStart=/usr/bin/anbox session-manager --gles-driver=host"

I started the user service:
- "systemctl --user start anbox-session-manager.service" 

Then it worked!

**Comment by morphis** [comment]
The initial question seems to be answered. Closing. If there any other issues please open a new bug with a good description of what fails or start a discussion on our forum at https://discourse.anbox.io/

**Comment by hamzamg** [comment]
thenk you it's work

**Comment by sujaataarya** [comment]
[sergey@p43es3g Загрузки]$ sudo pacman -U *.*
[sudo] пароль для sergey: 
загрузка пакетов...
предупреждение: откат версии пакета boost (1.65.1-1 => 1.64.0-4)
предупреждение: откат версии пакета boost-libs (1.65.1-1 => 1.64.0-4)
разрешение зависимостей...
проверка конфликтов...

Пакеты (2) boost-1.64.0-4  boost-libs-1.64.0-4

Будет установлено:  160,90 MiB
Изменение размера:    1,58 MiB

:: Приступить к установке? [Y/n] y
(2/2) проверка ключей                              [######################] 100%
(2/2) проверяется целостность пакета               [######################] 100%
(2/2) загрузка файлов пакетов                      [######################] 100%
(2/2) проверка конфликтов файлов                   [######################] 100%
(2/2) проверяется доступное место                  [######################] 100%
:: Обработка изменений пакета...
(1/2) откат версии boost-libs                      [######################] 100%
(2/2) откат версии boost                           [######################] 100%
:: Работа послеоперационных перехватов...
(1/1) Arming ConditionNeedsUpdate...
[sergey@p43es3g Загрузки]$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
anbox: error while loading shared libraries: libboost_log.so.1.65.1: cannot open shared object file: No such file or directory
[sergey@p43es3g Загрузки]$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
anbox: error while loading shared libraries: libboost_log.so.1.65.1: cannot open shared object file: No such file or directory
[sergey@p43es3g Загрузки]$ sudo pacman -U *.*
загрузка пакетов...
разрешение зависимостей...
проверка конфликтов...

Пакеты (2) boost-1.65.1-1  boost-libs-1.65.1-1

Будет установлено:  159,33 MiB
Изменение размера:   -1,58 MiB

:: Приступить к установке? [Y/n] y
(2/2) проверка ключей                                                                                                                          [#######################################################################################] 100%
(2/2) проверяется целостность пакета                                                                                                           [#######################################################################################] 100%
(2/2) загрузка файлов пакетов                                                                                                                  [#######################################################################################] 100%
(2/2) проверка конфликтов файлов                                                                                                               [#######################################################################################] 100%
(2/2) проверяется доступное место                                                                                                              [#######################################################################################] 100%
:: Обработка изменений пакета...
(1/2) обновление boost-libs                                                                                                                    [#######################################################################################] 100%
(2/2) обновление boost                                                                                                                         [#######################################################################################] 100%
:: Работа послеоперационных перехватов...
(1/1) Arming ConditionNeedsUpdate...
[sergey@p43es3g Загрузки]$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
anbox: error while loading shared libraries: libboost_filesystem.so.1.64.0: cannot open shared object file: No such file or directory
[sergey@p43es3g Загрузки]$

**Comment by KevOBrien** [comment]
I have followed the exact process given by @nickecalifornia above, but am still getting the following error:

`anbox session-manager --gles-driver=host                                                                                         
[ 2017-12-30 18:29:12] [session_manager.cpp:147@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded`

I am running kernel 4.15 on Manjaro and have installed the corresponding 4.15 `linux-headers`.

**Comment by ibilux** [comment]
I have followed the exact process given by @nickecalifornia above, but when i run :
`anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity`
i get error :
`[launch.cpp:134@operator()] Anbox session manager service isn't running, trying to start it.`

when i run :

`sudo anbox container-manager --data-path=/var/lib/anbox ---android-image=/snap/anbox/x1/android.img`

i get error :
`[container_manager.cpp:98@operator()] bind: Address already in use`

infromation using :
`anbox system-info`

os:
  name: Manjaro Linux
  version: 
  snap-based: false
kernel:
  version: Linux version 4.14.11-3-MANJARO (builduser@manjaro) (gcc version 7.2.1 20171128 (GCC)) #1 SMP PREEMPT
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.3.1
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_required_internalformat
      - GL_OES_surfaceless_context
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_polygon_offset_clamp
      - GL_KHR_no_error

**Comment by ShapeShifter499** [comment]
@nickecalifornia This is great, this should be added to setup tips for Arch Linux users.   I have it working here.   

One tip for people coming here, please double check your aliases, specifically ~/.bashrc.aliases I don't run vanilla Arch Linux, I use Antergos and they have added for whatever reason some "helpful" aliases for some utilities like systemctl. This was screwing up my use of "systemctl --user" as it wasn't being ran as my local user but as root instead.

**Comment by hyurl** [comment]
The solution @nickecalifornia posted works, but to those still cannot start anbox, must reboot the system first, and may need to 'enable` all the services so that after reboot, they can be auto-started.

**Comment by iczc** [comment]
By the way you have to enable the kernel modules you just installed:
`sudo modprobe ashmem_linux`
`sudo modprobe binder_linux`

https://forum.manjaro.org/t/running-android-applications-on-arch-using-anbox/53332
I hope that'll be helpful
