### ISSUE TITLE
Too aggressive reliance on apt-get update status

### ISSUE THREAD

**Issue by olewolf** [anbox/anbox#314]
When anbox-installer updates the repository info with apt-get, the installer fails if one of the repositories report an error such as not being properly signed. Specifically, I have Skype installed, which yields a GPG error stating that the public key isn't available. This causes anbox-installer to think that something went wrong and the installer aborts:

```
$ anbox-installer`
 [...]
W: GPG-fejl: https://repo.skype.com/deb stable InRelease: Følgende signaturer kunne ikke verificeret, da den offentlige nøgle ikke er tilgængelig: NO_PUBKEY 1F3045A5DF7587C3
E: Arkivet »https://repo.skype.com/deb stable InRelease« er ikke underskrevet.
N: Opdatering, fra et sådant arkiv, kan ikke udføres sikkert og er derfor deaktiveret som standard.
N: Se apt-secure(8)-manualsiden for detaljer om arkivoprettelse og brugerkonfiguration.
+ cleanup
+ local err=100
+ trap - EXIT
+ echo 'ERROR: Installation failed. Removing all parts of Anbox again.'
ERROR: Installation failed. Removing all parts of Anbox again.
+ uninstall
+ set -x
+ sudo snap remove anbox
snap "anbox" is not installed
+ '[' -e /etc/apt/sources.list.d/morphis-ubuntu-anbox-support-xenial.list ']'
+ set +x
```

Temporarily disabling the skype repository (or any other repository that causes an error) allows anbox-installer to complete but I'm not sure it makes sense to abort simply because apt-get update complains.

**Comment by morphis** [comment]
Doing something like `apt update || true` sounds ok to me. Can you provide a PR to fix this? Thanks!
