### ISSUE TITLE
missing /usr/share/anbox/ui/loading-screen.png ?

### ISSUE THREAD

**Issue by supaplextor** [anbox/anbox#319]
** Please paste the result of `anbox system-info` below:**
```
See #317
```

**Please describe your problem:**

open("/usr/share/anbox/ui/loading-screen.png", O_RDONLY) = -1 ENOENT (No such file or directory)
close(7)                                = 0
close(8)                                = 0
close(6)                                = 0
write(1, "[EE 2017-06-12 03:46:49] [daemon"..., 114[EE 2017-06-12 03:46:49] [daemon.cpp:58@Run] Failed to create texture from /usr/share/anbox/ui/loading-screen.png
) = 114
exit_group(1)                           = ?
+++ exited with 1 +++
supaplex@hydrogen:~$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[WW 2017-06-12 03:47:10] [launch.cpp:116@operator()] Anbox session manager service isn't running, trying to start it.
[EE 2017-06-12 03:47:10] [daemon.cpp:58@Run] Failed to create texture from /usr/share/anbox/ui/loading-screen.png

**What were you expecting?:**

**Additional info:**

**Comment by morphis** [comment]
Looks like you're running your self build Anbox version and not the one from the snap, right? Can you please paste the output of `anbox system-info` as the bug report template requests?

**Comment by supaplextor** [comment]
supaplex@hydrogen:~$ anbox system-info
version: local-18a7930
os:
  name: Ubuntu
  version: 16.04.2 LTS (Xenial Xerus)
  snap-based: false
kernel:
  version: Linux version 4.8.0-54-generic (buildd@lgw01-13) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #57~16.04.1-Ubuntu SMP Wed May 24 16:22:28 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_create_context
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_MESA_configless_context
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

Resolved. I nuked that install and went with bare metal.
