### ISSUE TITLE
Anbox stops Google Chrome for working

### ISSUE THREAD

**Issue by ghost** [anbox/anbox#321]
**Please describe your problem:**
Whenever I install anbox, Google Chrome won't open.
**What were you expecting?:**
I was expecting anbox to not make a difference to Chrome.
**Additional info:**
If I try to open Chrome while anbox is installed, and then remove anbox, Chrome opens as soon as anbox is removed.
I am using Ubuntu 16.04 LTS.

**Comment by navedcoded** [comment]
Running firefox nightly (56), any tabs I had before launching `anbox session-manager` stop functioning and show a white background with spinning wheel. Any new tabs I open function normally, maybe slightly slower than usual.

**Comment by yamboy1** [comment]
@navedcoded You should create a new issue about this.

**Comment by navedcoded** [comment]
@yamboy1 Thanks I'll make one now 👍
