### ISSUE TITLE
Installing anbox from sources on LinuxMint 17.3 (Ubuntu 14.04) : cmake cannot find gmock

### ISSUE THREAD

**Issue by frallain** [anbox/anbox#329]
What I did : 
```
sudo apt install build-essential cmake cmake-data debhelper dbus google-mock \
    libboost-dev libboost-filesystem-dev libboost-log-dev libboost-iostreams-dev \
    libboost-program-options-dev libboost-system-dev libboost-test-dev \
    libboost-thread-dev libcap-dev libdbus-1-dev libdbus-cpp-dev libegl1-mesa-dev \
    libgles2-mesa-dev libglib2.0-dev libglm-dev libgtest-dev liblxc1 \
    libproperties-cpp-dev libprotobuf-dev libsdl2-dev libsdl2-image-dev lxc-dev \
    pkg-config protobuf-compiler ```

$ git clone https://github.com/anbox/anbox.git
$ cd anbox
$ mkdir build
$ cd build
$ cmake ..
```

which outputs 
```
$ cmake ..
-- No build type selected, default to release
-- Treat warnings as errors
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   filesystem
--   log
--   serialization
--   system
--   thread
--   program_options
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   iostreams
--   system
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   filesystem
--   system
--   unit_test_framework
-- Configuring done
CMake Error at cmake/FindGMock.cmake:74 (add_library):
  Cannot find source file:

    INTERFACE

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  CMakeLists.txt:94 (find_package)


-- Build files have been written to: /home/frallain/workspace/anbox/build
```

**Please describe your problem:**
I seems that cmake does not find gmock on the system although it has been installed with apt-get and resides at `/usr/include/gmock` (headers) and `/usr/src/gmock/src` (sourcecode). 

I also tried to cmake after compiling gmock's sourcecode into `/usr/src/gmock/libgmock.a` and `libgmock_main.a` by following https://abodeofcode.wordpress.com/2015/01/31/setup-google-mock-google-test-in-ubuntu-14-04/ . 

I also tried to play with `CMAKE_PREFIX_PATH` and `CMAKE_INSTALL_PREFIX` without success ( https://blogs.kde.org/2008/12/12/how-get-cmake-find-what-you-want-it ).

**What were you expecting?:**
cmake to end successfully 

**Additional info:**

```
$ dpkg-query --show build-essential cmake cmake-data debhelper dbus google-mock \
    libboost-dev libboost-filesystem-dev libboost-log-dev libboost-iostreams-dev \
    libboost-program-options-dev libboost-system-dev libboost-test-dev \
    libboost-thread-dev libcap-dev libdbus-1-dev libdbus-cpp-dev libegl1-mesa-dev \
    libgles2-mesa-dev libglib2.0-dev libglm-dev libgtest-dev liblxc1 \
    libproperties-cpp-dev libprotobuf-dev libsdl2-dev libsdl2-image-dev lxc-dev \
    pkg-config protobuf-compiler
build-essential	11.6ubuntu6
cmake	2.8.12.2-0ubuntu3
cmake-data	2.8.12.2-0ubuntu3
dbus	1.6.18-0ubuntu4.5
debhelper	9.20131227ubuntu1
google-mock:amd64	1.6.0+svn437-0ubuntu5
libboost-dev	1.54.0.1ubuntu1
libboost-filesystem-dev:amd64	1.54.0.1ubuntu1
libboost-iostreams-dev:amd64	1.54.0.1ubuntu1
libboost-log-dev	1.54.0.1ubuntu1
libboost-program-options-dev:amd64	1.54.0.1ubuntu1
libboost-system-dev:amd64	1.54.0.1ubuntu1
libboost-test-dev:amd64	1.54.0.1ubuntu1
libboost-thread-dev:amd64	1.54.0.1ubuntu1
libcap-dev:amd64	1:2.24-0ubuntu2
libdbus-1-dev:amd64	1.6.18-0ubuntu4.5
libdbus-cpp-dev:amd64	2.0.0+14.04.20140326-0ubuntu1
libegl1-mesa-dev	10.1.3-0ubuntu0.6
libgles2-mesa-dev	10.1.3-0ubuntu0.6
libglib2.0-dev	2.40.2-0ubuntu1
libglm-dev	0.9.5.1-1
libgtest-dev	1.6.0-1ubuntu6
liblxc1	1.0.9-0ubuntu3
libproperties-cpp-dev:amd64	0.0.1+14.04.20140220-0ubuntu1
libprotobuf-dev:amd64	2.5.0-9ubuntu1
libsdl2-dev	2.0.2+dfsg1-3ubuntu1.1
libsdl2-image-dev:amd64	2.0.0+dfsg-3build2
lxc-dev	1.0.9-0ubuntu3
pkg-config	0.26-1ubuntu4
protobuf-compiler	2.5.0-9ubuntu1
```

**Comment by morphis** [comment]
FindGMock.cmake is packaged on Ubuntu in `cmake-extras`. When you install this package cmake should be happy. Interested in proposing a PR to add `cmake-extras` to the list of necessary packages in the README.md?

**Comment by chr15m** [comment]
@morphis `make-extras` is not available on 14.04 so it's not only a matter of adding to README.md

**Comment by morphis** [comment]
@chr15m Hm, you're right. Actual you can help in that case a submit the missing cmake extension as part of this repository so that we don't have to depend on `cmake-extras` anymore. All in all I've never tested building Anbox on 14.04 so I can't guarantee that you're aren't running into any further issues. Would love to merge any fixes when needed while you work through this.

**Comment by zeerd** [comment]
i tried to install the extras from git://anongit.kde.org/extra-cmake-modules , and remove the cmake/FindGMock.cmake from anbox.

the cmake could success, but the gcc still be a problem. c++14 is painful for ubuntu 14.04.

so i upgraded the gcc to 5.4.1  , and seems anbox start to compiling till the following error comes:
/home/user/anbox/src/anbox/dbus/interface.h:21:30: fatal error: core/dbus/macros.h: No such file or directory

this is a new file in dbus-cpp 5.0.0(which is 2.0.0 in ubuntu 14.04). i am not sure what would happen if i upgrade the dbus-cpp into higher version. 

so i decide to give up today...

Refers:
https://askubuntu.com/questions/859824/how-can-i-install-extra-cmake-modules-on-ubuntu-14-04-trusty
https://askubuntu.com/questions/618474/how-to-install-the-latest-gcurrently-5-1-in-ubuntucurrently-14-04
https://www.apt-browse.org/browse/ubuntu/xenial/main/amd64/libdbus-cpp-dev/5.0.0+15.10.20151022.1-0ubuntu1/file/usr/include/core/dbus/macros.h

**Comment by morphis** [comment]
@zeerd Why aren't you simply using the snap? Or do you want to participate in development? If that is the case please use a container for that.

**Comment by zeerd** [comment]
yeah, i'd like to try some develop-things.  maybe,  someday , i could upgrade the ubuntu to a higher version.

**Comment by morphis** [comment]
@zeerd Then the easiest, and supported way, is to use a container (docker, LXD) for that.

**Comment by xsellier** [comment]
For those, like me, who are looking for a working answer. Here a guy who compiled anbox for debian:
https://ftp.ustclug.org/%7Ezsj/anbox/
