### ISSUE TITLE
INSTALL_FAILED_NO_MATCHING_ABIS

### ISSUE THREAD

**Issue by dsdmsa** [anbox/anbox#33]
adb install 5_temnyj_rycar_vozrozhdenie.apk       dsdmsa@hp
24725 KB/s (14714026 bytes in 0.581s)
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

in this [answer](http://stackoverflow.com/questions/24572052/install-failed-no-matching-abis-when-install-apk) is explained the issue, but is something what can be done?

**Comment by morphis** [comment]
This is nothing Anbox can help with. If the apk doesn't support the architecture of the device Anbox is running on then we're off. I don't think we ever want to try to do some kind of emulation or so that is hard to implement and performance wise not very useful.

**Comment by x8BitRain** [comment]
So is it not possible to implement the ARM compatibility mode that Android x86 has? Or is that something that out of the question?

**Comment by michaeldyl520** [comment]
x86 application is too little, when can support the arm system app installation, or anbox feel too tasteless.
