### ISSUE TITLE
What I'd expect from this Solution?

### ISSUE THREAD

**Issue by konkor** [anbox/anbox#34]
Make sure you are running the latest version of Anbox before reporting an issue.

**Anbox release (`anbox version`) and system info (`anbox system-info`):**
Latest

**Description of the problem:**
I can't understand this project. What benefits are there? Is it like Wine or it's like other qemu Android emulator?

**Expected:**
I expect like Wine solution for Android apps with winecfg or at least running in my desktop environment at Fullscreen or fixed screen window with integrated filesystem, devices etc. Ideally it has to run apps like RemixOS in my DE. I don't need any  Android launcher or market for this.

**Additional info:**
So I think it must be a custom OS anyways which just can run Android apps and use my system hardware and software much as possible.

**Comment by morphis** [comment]
There is a fundamental difference to wine. Wine does emulation. We don't do emulation but directly execute all Android bits on the CPU. The target is to have Android apps natively integrated into existing Linux desktops so you don't see any difference between them and native Linux applications.

**Comment by oleid** [comment]
Well, wine doesn't do any (CPU) emulation either. It's more like a port of the windows libs to a posix API. Running a win32 OpenGL-based application  on Linux, there is hardly and overhead and given the same drivers, it's as fast as native.

**Comment by morphis** [comment]
That is true but lets call the windows API layer a kind of "emulation" as it has to model certain aspects of the windows API. For anbox there is nothing like this other than that we, for a high portability, forward certain things like OpenGL ES to a process running on the host and not inside the container. There is "emulation" layer between bionic and the kernel. Bionic calls into the kernel and that's it.

**Comment by konkor** [comment]
WINE Is Not Emulator! Lol.  This app is an emulator which run whole Android machine in virtual container using system Linux kernel.
OK good luck with your project.
