### ISSUE TITLE
INSTALLATION OF ANBOX ON NOT SUPPORTED DISTRIBUTION(deepin OS)

### ISSUE THREAD

**Issue by jingle0927** [anbox/anbox#35]
root@jingle:/home/jingle/anbox# ./anbox-installer 
Android in a Box - Installer

IMPORTANT: THIS IS ALPHA LEVEL SOFTWARE. EXPECT INSTABILITY AND
           BUGS !!!!!

IMPORTANT: ALSO PLEASE BE AWARE THAT WE DON'T PROVIDE FULL
           CONFINEMENT FOR THE SNAP YET !!!!

PLEASE NOTE: This script will require root access on your system
to install all necessary things. It will prompt you to enter your
password when required.

ERROR: You are running the installer on a not support distribution.
       At the moment we only support Ubuntu.

**Comment by Pillar1989** [comment]
哇,deepin os速度这么快,一下子就抓到这个项目.赶紧支持吧

**Comment by rickysarraf** [comment]
Yes. For wider user base, please consider extending support to other Linux distributions too (start with Debian, at least).

**Comment by GizmoChicken** [comment]
I'm currently having trouble getting Anbox (which is still pre-alpha) to work on bare metal.  But to my surprise and delight, at least for me, Anbox seems to work pretty well in an Ubuntu 16.04.2 VM running under QEMU/KVM.

Of course, running Anbox in an Ubuntu 16.04.2 VM defeats one of the primary advantages of Anbox, namely being able to run Android in a container, without need for a VM.  But for the purposes of initial testing and development, being able to run Anbox in an Ubuntu 16.04.2 VM may be of some use.

**Comment by rekols** [comment]
哈哈哈，惊了。

**Comment by snyh** [comment]
There has a patch can install anbox in deepin 
  https://gist.github.com/snyh/01e6c9d555d82c778eff3a7acb95f02d

**Comment by LightPaper** [comment]
good item

**Comment by diegudias** [comment]
Try this: https://ftp.ustclug.org/~zsj/anbox/
