### ISSUE TITLE
README.md build typo

### ISSUE THREAD

**Issue by generalram** [anbox/anbox#357]
Just a typo I noticed when trying to build the source code from the Git Clone.

The README.md file:

The:
''''
$ cmake ..
''''

Should be:

''''
$ cmake ../
''''

Without the Slash after the dots, it won't run the cmake command. Remember the user is in the build subdirectory and needs to go back a directory for the cmake info.

Regards,
Norman King

**Comment by morphis** [comment]
The slash doesn't really matter. A `cmake ..` is really enough. Which shell are you using?
