### ISSUE TITLE
error: cannot install "anbox": ... connection refused

### ISSUE THREAD

**Issue by meshwara** [anbox/anbox#36]
Today I try to install anbox using anbox-installer script. Everything is OK until it fail to install anbox using snap package.

depmod....

DKMS: install completed.
+ '[' '!' -e /etc/modules-load.d/anbox.conf ']'
+ sudo tee /etc/modules-load.d/anbox.conf
+ sudo modprobe binder_linux
+ sudo modprobe ashmem_linux
+ snap list anbox
+ sudo snap install --edge --devmode anbox
error: cannot install "anbox": Get https://search.apps.ubuntu.com/api/v1/snaps/details/anbox?channel=edge&fields=anon_download_url%2Carchitecture%2Cchannel%2Cdownload_sha3_384%2Csummary%2Cdescription%2Cdeltas%2Cbinary_filesize%2Cdownload_url%2Cepoch%2Cicon_url%2Clast_update
d%2Cpackage_name%2Cprices%2Cpublisher%2Cratings_average%2Crevision%2Cscreenshot_urls%2Csnap_id%2Csupport_url%2Ccontact%2Ctitle%2Ccontent%2Cversion%2Corigin%2Cdeveloper_id%2Cprivate%2Cconfinement: dial tcp: lookup search.apps.ubuntu.com on [::1]:53: read udp [::1]:34224->[::
1]:53: read: connection refused

It is snap problem or ?

NOTE:
I'm using Ubuntu 16.04 64bit

**Comment by morphis** [comment]
Looks very much like an issue with the Store. Can you retry?

**Comment by meshwara** [comment]
I just retry and unfortunately it still error

**Comment by meshwara** [comment]
Today I retry it and it's works !!!
