### ISSUE TITLE
always need to download android.img when build anbox snap?

### ISSUE THREAD

**Issue by jackwish** [anbox/anbox#368]
I have a self-built android.img with which i'd like to build anbox snap. However, with the command below under anbox root dir, snapcraft always wants to download android.img.
```
$ mkdir android-images
$ cp /path/to/android.img android-images/android.img
$ snapcraft
```

I checked the configuration @ https://github.com/anbox/anbox/blob/master/snapcraft.yaml#L69

```
      wget http://build.anbox.io/android-images/$IMAGE_PATH/$IMAGE_NAME.img
      mv $IMAGE_NAME.img $SNAPCRAFT_PART_INSTALL/android.img
```

Looks like this behavior is intended?

**Comment by jackwish** [comment]
btw, when downloading, what about let server handles the image file mapping (android.img -> path/to/android.img) rather than hard code (https://github.com/anbox/anbox/blob/master/snapcraft.yaml#L53) the image path in `snapcraft.yaml`?

**Comment by supaplextor** [comment]
If you browse http://build.anbox.io/android-images/2017 you can find numerous images. Some for amd64 and one for armhf. I'll let devs comment further.

**Comment by david2896482** [comment]
You can edit snapcraft.yaml
Let snapcraft using your own image

**Comment by jackwish** [comment]
PR as https://github.com/anbox/anbox/pull/385

**Comment by lemrm** [comment]
Could somebody explain in detail, how to build a snap with my own android.img
