### ISSUE TITLE
All latest ubuntu updates break Anbox again, not recoverable X16 Y16 Z17 AA17

### ISSUE THREAD

**Issue by cbennett912** [anbox/anbox#377]
Make sure you are running the latest version of Anbox before reporting an issue.

The platform is just sooo fragile.  AL ubuntu version broke

this is the looping log now
07-21 18:57:00.463  1081  1081 D MDnsDS  : MDnsSdListener::Hander starting up
07-21 18:57:00.463  1081  1088 D MDnsDS  : MDnsSdListener starting to monitor
07-21 18:57:00.463  1081  1088 D MDnsDS  : Going to poll with pollCount 1
07-21 18:57:03.431    33    33 I ServiceManager: service 'netd' died
07-21 18:57:05.491  1104  1104 I Netd    : Netd 1.0 starting
07-21 18:57:05.491  1104  1104 D TetherController: Setting IP forward enable = 0
07-21 18:57:05.513  1104  1104 E Netd    : cannot find interface dummy0
07-21 18:57:05.517  1104  1104 E Netd    : Unable to create netlink socket: Protocol not supported
07-21 18:57:05.518  1104  1104 W Netd    : Unable to open qlog quota socket, check if xt_quota2 can send via UeventHandler
07-21 18:57:05.518  1104  1104 D MDnsDS  : MDnsSdListener::Hander starting up
07-21 18:57:05.518  1104  1111 D MDnsDS  : MDnsSdListener starting to monitor
07-21 18:57:05.518  1104  1111 D MDnsDS  : Going to poll with pollCount 1
07-21 18:57:08.485    33    33 I ServiceManager: service 'netd' died
07-21 18:57:10.546  1126  1126 I Netd    : Netd 1.0 starting
07-21 18:57:10.546  1126  1126 D TetherController: Setting IP forward enable = 0
07-21 18:57:10.569  1126  1126 E Netd    : cannot find interface dummy0
07-21 18:57:10.572  1126  1126 E Netd    : Unable to create netlink socket: Protocol not supported
07-21 18:57:10.572  1126  1126 W Netd    : Unable to open qlog quota socket, check if xt_quota2 can send via UeventHandler
07-21 18:57:10.573  1126  1126 D MDnsDS  : MDnsSdListener::Hander starting up
07-21 18:57:10.573  1126  1133 D MDnsDS  : MDnsSdListener starting to monitor
07-21 18:57:10.573  1126  1133 D MDnsDS  : Going to poll with pollCount 1
---repeat

** Please paste the result of `anbox system-info` below:**
```
user@User-PC:~$ anbox system-info
version: 3
snap-revision: 44
os:
  name: Ubuntu
  version: 17.04 (Zesty Zapus)
  snap-based: true
kernel:
  version: Linux version 4.10.0-28-generic (buildd@lgw01-11) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) ) #32-Ubuntu SMP Fri Jun 30 05:32:18 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: X.Org
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

**Please describe your problem:**
I can find nothing in any log file that points to the issue.  I have spent over 200 hours trying various combinations of dependencies, video, kernels, desktop env, and now all version end up in this state using only the STOCK ubuntu updates.  Tried all kernels from 4.4.0-83 to 4.10.0.58 and compiled 4.12.x latest.  = Broke

This is nothing more than install ubuntu, run it's updates that it recommends, install snapd, then anbox.
=Broke

**What were you expecting?:**
Help!  :)  Point me in the right direction, I have to be missing something...

Same results non Intel, nvidia, and AMD graphics, and same result on Intel and AMD cpus.

I have tried installing all the Anbox build dep and anything related to it.

Even a full compile from source of both runtime, and snapcraft stock android.img = Broke

Snap Core pack 2312 seemed better than Core 2381

Stuck.... Thanks

**Comment by cbennett912** [comment]
I have a  PC in this state, online with teamviewer if someone want to take a look

**Comment by cbennett912** [comment]
Here is a working combo
Lubuntu 16.04.2
Kernel 4.4.0-83
Snapd core 2312
anbox-common and anbox-modules-dkms ~7xenial

use snapd revert core , and hold the snapd package in apt
then load the stock updates

**Comment by morphis** [comment]
Charlie Bennett <notifications@github.com> schrieb am Jul 22, 2017:
>Here is a working combo
>Lubuntu 16.04.2
>Kernel 4.4.0-83
>Snapd core 2312
>anbox-common and anbox-modules-dkms ~7xenial
>
>use snapd revert core , and hold the snapd package in apt
>then load the stock updates

-- Diese Nachricht wurde mit K-@ Mail gesendet.
