### ISSUE TITLE
errer install zorin os 12 lite

### ISSUE THREAD

**Issue by ramzydoni** [anbox/anbox#388]
i can t install anbox wtich ubuntu:zorin os lite 12

http://i.imgur.com/Fl0iQd0.png
thx

**Comment by morphis** [comment]
> i can t install anbox wtich ubuntu:zorin os lite 12

You're welcome to help us to add support for Zorin inside the installer. You will find the source code at https://github.com/anbox/anbox-installer

Contributions are always welcome :-)

Personally I will not have the time to enable Zorin OS but as it's Ubuntu based and should be able to run snaps you should have an easy play to get it enabled.

**Comment by ramzydoni** [comment]
morphis  Thank you very much is working now
