### ISSUE TITLE
Run anbox with custom android kernel

### ISSUE THREAD

**Issue by pshp25** [anbox/anbox#389]
Can run anbox with custom kernel? (like Android SDK emulator that can run it with custom kernel with 
`-kernel [path to kernel image]` add to `./emulator`)

**Comment by morphis** [comment]
You can use whatever kernel on your host system you like to but it has to support all necessary features for LXC and needs to be able to build & load the binder/ashmem dkms modules.

Only starting the container with another kernel isn't possible as a container is a very lightweight way of virtualization where everything inside the container will continue to use the host system kernel.

**Comment by pshp25** [comment]
I khnow that "Only starting the container with another kernel isn't possible", What i mean is can we run anbox with android virtual device that uses our custom kernel? ( it means, that avd (android virtual device) use our custom kernel instead of its kernel like: ./emualtor -avd my_avd -kernel path-to-custom-kernel)

**Comment by pshp25** [comment]
@morphis

**Comment by jackwish** [comment]
i think that's out of the intention of anbox.

**Comment by morphis** [comment]
> What i mean is can we run anbox with android virtual device that uses our custom kernel? 

What are you intending to do here?

**Comment by pshp25** [comment]
I want to develope kernel of Android!
@morphis

**Comment by morphis** [comment]
> I want to develope kernel of Android!

Why do you care about Anbox then and not use AVD directly? Anbox is using lightweight containers so it can't give you any option to use a specific kernel just for the container.
