### ISSUE TITLE
 mount --rbind /var/tmp /tmp/snap.rootfs_SPNfJf//var/tmp: Permission denied

### ISSUE THREAD

**Issue by kollokollo** [anbox/anbox#399]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[mount --rbind /var/tmp /tmp/snap.rootfs_SPNfJf//var/tmp: Permission denied]
```

**Please describe your problem:**
Anbox installed but does not run. Ubuntu 17.04 64 bit

**What were you expecting?:**

**Additional info:**

**Comment by morphis** [comment]
@kollokollo Which snapd version are you running with? `snap --version` will tell you which one it is.

**Comment by kollokollo** [comment]
`snap    2.26.14
snapd   2.26.14
series  16
ubuntu  17.04
kernel  4.10.0-30-generic`

**Comment by morphis** [comment]
This very much looks like a regression with snapd itself and nothing Anbox can fix for you. Can you please ask at https://forum.snapcraft.io for help? Thanks.

**Comment by AmrIKhudair** [comment]
Got the same problem

**Comment by elopio** [comment]
Do you have your home in a non-default directory?
This could be https://bugs.launchpad.net/snapcraft/+bug/1620771
