### ISSUE TITLE
/ not root-owned

### ISSUE THREAD

**Issue by Aidoboy** [anbox/anbox#400]
```
anbox not installed
```

**Please describe your problem:**
When trying to run `anbox-installer` or `sudo anbox-installer`, I get `/ not root-owned 1000:1000`

**What were you expecting?:**
anbox to isntall

**Additional info:**
```
            .-/+oossssoo+/-.               aidan@viselik 
        `:+ssssssssssssssssss+:`           ------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 17.04 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Kernel: 4.10.0-28-generic 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 24 mins 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 2642 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: bash 4.4.7 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Resolution: 3440x1440 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   DE: GNOME 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: GNOME Shell 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM Theme: Adwaita-tweaks-dark 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Adwaita-tweaks-dark [GTK2/3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Papirus [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: gnome-terminal 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: Intel i7-6700 (8) @ 4.0GHz 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: Intel Integrated Graphics 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce GTX 1070 
      -+sssssssssssssssssyyyssss+-         Memory: 4646MiB / 32053MiB 
        `:+ssssssssssssssssss+:` 
            .-/+oossssoo+/-.                                       

```

**Comment by david2896482** [comment]
Hi, Could you attach the full installation log?

**Comment by Aidoboy** [comment]
That is the full installation log.

**Comment by morphis** [comment]
That really seems to a problem with your system and not with Anbox. Can you do a  `ls -alh /`. That should give something like
```
$ ls -alh /
total 5,2G
drwxr-xr-x  27 root root 4,0K Aug  8 10:40 .
[...]
```

The important point is that / is owned by root:root which doesn't seem to be the case on your system (for whatever reason).

**Comment by shubhzgang** [comment]
same problem here.
![terminal](https://user-images.githubusercontent.com/18749160/29120962-2d5d3e9c-7d2a-11e7-8c3c-c2c5a1751ab2.png)

**Comment by shubhzgang** [comment]
found the solution! Try: `sudo chown root:root /`

**Comment by Aidoboy** [comment]
Woohoo, @shubhzgang was right!
Now I get this though:
```
$ anbox-installer 
cannot create user data directory: /home/aidan/snap/anbox-installer/17: Permission denied
```

**Comment by morphis** [comment]
> cannot create user data directory: /home/aidan/snap/anbox-installer/17: Permission denied

As which user are you executing the anbox-installer?

**Comment by Aidoboy** [comment]
@morphis I'm running it as `aidan`.

**Comment by morphis** [comment]
@Aidoboy This is not really an issue with Anbox but more an issue with your system and snaps in general. Can you please go to https://forum.snapcraft.io and ask for help? This is nothing we can fix here. Thanks!

**Comment by morizbebenk** [comment]
change group on /var to root

**Comment by macbroadcast** [comment]
Seems like i have a problem with the repository / security ?
`E: Das Depot »http://ppa.launchpad.net/morphis/anbox-support/ubuntu bionic Release« enthält keine Release-Datei.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
+ cleanup
+ local err=100
+ trap - EXIT
+ echo 'ERROR: Installation failed. Removing all parts of Anbox again.'
ERROR: Installation failed. Removing all parts of Anbox again.
+ uninstall
+ set -x
+ sudo snap remove anbox
anbox entfernt
+ '[' -e /etc/apt/sources.list.d/morphis-ubuntu-anbox-support-xenial.list ']'
+ set +x
`
