### ISSUE TITLE
Error compiling on LinuxMint18

### ISSUE THREAD

**Issue by TFAssKID** [anbox/anbox#402]
Scanning dependencies of target anbox-core
[ 47%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/logger.cpp.o
[ 48%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/utils.cpp.o
[ 48%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/cli.cpp.o
[ 48%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/runtime.cpp.o
[ 49%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/daemon.cpp.o
[ 49%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/config.cpp.o
[ 50%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/not_reachable.cpp.o
[ 50%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/android/intent.cpp.o
[ 50%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/android/ip_config_builder.cpp.o
[ 51%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/common/fd.cpp.o
[ 51%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/common/wait_handle.cpp.o
[ 51%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/common/dispatcher.cpp.o
[ 52%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/common/message_channel.cpp.o
[ 52%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/common/loop_device.cpp.o
[ 53%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/common/loop_device_allocator.cpp.o
[ 53%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/common/mount_entry.cpp.o
[ 53%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/common/binary_writer.cpp.o
[ 54%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/container/service.cpp.o
[ 54%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/container/client.cpp.o
[ 54%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/container/container.cpp.o
[ 55%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/container/lxc_container.cpp.o
[ 55%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/container/management_api_stub.cpp.o
[ 55%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/container/management_api_skeleton.cpp.o
[ 56%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/container/management_api_message_processor.cpp.o
[ 56%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/network/credentials.cpp.o
[ 58%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/network/published_socket_connector.cpp.o
[ 58%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/network/socket_connection.cpp.o
[ 58%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/network/socket_messenger.cpp.o
[ 59%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/network/delegate_message_processor.cpp.o
[ 59%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/network/base_socket_messenger.cpp.o
[ 59%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/network/local_socket_messenger.cpp.o
[ 60%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/network/tcp_socket_messenger.cpp.o
[ 60%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/network/socket_helper.cpp.o
[ 61%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/network/tcp_socket_connector.cpp.o
[ 61%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/rpc/channel.cpp.o
[ 61%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/rpc/pending_call_cache.cpp.o
[ 62%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/rpc/connection_creator.cpp.o
[ 62%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/rpc/message_processor.cpp.o
[ 62%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/opengles_message_processor.cpp.o
[ 63%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/buffer_queue.cpp.o
[ 63%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/buffered_io_stream.cpp.o
[ 64%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/gl_renderer_server.cpp.o
[ 64%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/rect.cpp.o
[ 64%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/layer_composer.cpp.o
[ 65%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/multi_window_composer_strategy.cpp.o
[ 65%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/single_window_composer_strategy.cpp.o
[ 65%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/program_family.cpp.o
[ 66%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/emugl/ColorBuffer.cpp.o
[ 66%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/emugl/DisplayManager.cpp.o
[ 66%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/emugl/RendererConfig.cpp.o
[ 67%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/emugl/Renderable.cpp.o
[ 67%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/emugl/Renderer.cpp.o
[ 68%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/emugl/ReadBuffer.cpp.o
[ 68%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/emugl/RenderApi.cpp.o
[ 68%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/emugl/RenderContext.cpp.o
[ 69%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/emugl/RenderControl.cpp.o
[ 69%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/emugl/RenderThread.cpp.o
[ 69%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/emugl/RenderThreadInfo.cpp.o
[ 70%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/emugl/TextureDraw.cpp.o
[ 70%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/emugl/TextureResize.cpp.o
[ 72%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/emugl/TimeUtils.cpp.o
[ 72%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/graphics/emugl/WindowSurface.cpp.o
[ 72%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/audio/server.cpp.o
[ 73%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/wm/display.cpp.o
[ 73%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/wm/task.cpp.o
[ 73%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/wm/stack.cpp.o
[ 74%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/wm/manager.cpp.o
[ 74%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/wm/single_window_manager.cpp.o
[ 75%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/wm/multi_window_manager.cpp.o
[ 75%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/wm/window_state.cpp.o
[ 75%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/wm/window.cpp.o
[ 76%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/platform/base_platform.cpp.o
[ 76%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/platform/null/platform.cpp.o
[ 76%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/platform/sdl/window.cpp.o
[ 77%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/platform/sdl/keycode_converter.cpp.o
[ 77%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/platform/sdl/platform.cpp.o
[ 77%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/platform/sdl/audio_sink.cpp.o
[ 78%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/input/manager.cpp.o
[ 78%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/input/device.cpp.o
[ 79%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/qemu/pipe_connection_creator.cpp.o
[ 79%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/qemu/null_message_processor.cpp.o
[ 79%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/qemu/qemud_message_processor.cpp.o
[ 80%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/qemu/boot_properties_message_processor.cpp.o
[ 80%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/qemu/hwcontrol_message_processor.cpp.o
[ 80%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/qemu/sensors_message_processor.cpp.o
[ 81%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/qemu/camera_message_processor.cpp.o
[ 81%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/qemu/fingerprint_message_processor.cpp.o
[ 82%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/qemu/gsm_message_processor.cpp.o
[ 82%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/qemu/at_parser.cpp.o
[ 82%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/qemu/bootanimation_message_processor.cpp.o
[ 83%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/qemu/adb_message_processor.cpp.o
[ 83%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/bridge/platform_message_processor.cpp.o
[ 83%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/bridge/platform_api_skeleton.cpp.o
[ 84%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/bridge/android_api_stub.cpp.o
[ 84%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/dbus/skeleton/service.cpp.o
[ 86%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/dbus/skeleton/application_manager.cpp.o
[ 86%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/dbus/stub/application_manager.cpp.o
[ 86%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/application/launcher_storage.cpp.o
[ 87%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/application/database.cpp.o
[ 87%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/cmds/version.cpp.o
In file included from /mnt/6271E35F5404EDE2/Install/Linux/anbox-master/src/anbox/cmds/version.cpp:21:0:
/mnt/6271E35F5404EDE2/Install/Linux/anbox-master/src/anbox/build/version.h:29:38: error: missing terminating " character [-Werror]
 static constexpr const char *version{"local-fatal: Not a git repository (or any parent up to mount point /mnt/6271E35F5404EDE2)
                                      ^
/mnt/6271E35F5404EDE2/Install/Linux/anbox-master/src/anbox/build/version.h:29:1: error: missing terminating " character
 static constexpr const char *version{"local-fatal: Not a git repository (or any parent up to mount point /mnt/6271E35F5404EDE2)
 ^
In file included from /mnt/6271E35F5404EDE2/Install/Linux/anbox-master/src/anbox/cmds/version.cpp:21:0:
/mnt/6271E35F5404EDE2/Install/Linux/anbox-master/src/anbox/build/version.h:30:75: error: missing terminating " character [-Werror]
 Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)."};
                                                                           ^
/mnt/6271E35F5404EDE2/Install/Linux/anbox-master/src/anbox/build/version.h:30:1: error: missing terminating " character
 Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)."};
 ^
/mnt/6271E35F5404EDE2/Install/Linux/anbox-master/src/anbox/build/version.h:30:1: error: ‘Stopping’ was not declared in this scope
/mnt/6271E35F5404EDE2/Install/Linux/anbox-master/src/anbox/build/version.h:30:10: error: expected ‘}’ before ‘at’
 Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)."};
          ^
/mnt/6271E35F5404EDE2/Install/Linux/anbox-master/src/anbox/build/version.h:30:10: error: expected ‘,’ or ‘;’ before ‘at’
cc1plus: all warnings being treated as errors
src/CMakeFiles/anbox-core.dir/build.make:2438: recipe for target 'src/CMakeFiles/anbox-core.dir/anbox/cmds/version.cpp.o' failed
make[2]: *** [src/CMakeFiles/anbox-core.dir/anbox/cmds/version.cpp.o] Error 1
CMakeFiles/Makefile2:2028: recipe for target 'src/CMakeFiles/anbox-core.dir/all' failed
make[1]: *** [src/CMakeFiles/anbox-core.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by morphis** [comment]
You're not building within a git tree. That isn't supported yet and is what the build error indicates. Please build from within a git tree and the error will go away.
