### ISSUE TITLE
Is it possible to run two separate android containers in parallel?

### ISSUE THREAD

**Issue by gat3way** [anbox/anbox#406]
Hello,

I am interested in running more than one Android container and so I tried to run different container-manager instances operating on different data paths and different images. I also tried it using the --experimental and --standalone options, but that did not work as they want to create an unix domain socket at the same location that is not configurable but more like hardcoded in the source.

Would it be enough if I just patch the code so that it properly handles different sockets (depending on an environment variable or something like that)? I have concerns that even if I do that, it is not guaranteed that the communication with the binder/ashmem kernel modules would work properly with more than one android instance. Or the GL proxy would not be able to handle more than one client. 

Would just patching the container manager to allow for user-provided socket be enough?

Thanks in advance.

Regards,
Milen Rangelov

**Comment by jackwish** [comment]
to me, namespace must to be introduced to binder to support multiple instances - which seems not included in kernel mainline.

**Comment by bo-liu** [comment]
And there also dbus name "org.anbox" conflict.  
It would be great if anbox can support multi containers officially.

**Comment by gat3way** [comment]
Hello,
Looks like it won't be a straightforward change, unfortunately :(

Is multi container support planned on the roadmap?

Regarding introducing namespace support to binder kernel module - are there some recent efforts/patches already available? I think I noticed a patch for drivers/android/binder code committed somewhere in the source tree, but apparently it was done against a rather old kernel version :( I think it would require some good amount of effort and time to apply to a current (say 4.x) kernel code - I had a quick look and some structs have changed and I think even some APIs changed somewhat in the meanwhile :(

Regards,
Milen Rangelov

**Comment by morphis** [comment]
We have a set of patches to allow namespacing of the binder driver. See https://github.com/anbox/anbox/tree/master/kernel/patches

However this comes with the cost of that you have to rebuild your entire kernel and not just the DKMS package we provide. The better way to go without a kernel rebuild is by using the recently introduced `devices` parameter of the binder kernel module. This allows you to create multiple independent binder nodes inside /dev. Try with `modprobe binder_linux devices=binder,binder1,binder2` and you will see /dev/binder, /dev/binder1, /dev/binder2.

The Anbox container-manager will most likely not see support for multiple containers. But what you can do quite easily (and this will also help you with the dbus address problem) is that you can put both the anbox session manager and the container manager into a container and use nested containerization to spawn up the Android container inside the container.

Can you give a few examples of what your use case is?

**Comment by bo-liu** [comment]
Does Anbox container-manager have plan to native support multiple containers?
The nested containerization solution looks like not very elegant.

**Comment by morphis** [comment]
@bo-liu Why do you think it's not elegant?

**Comment by gat3way** [comment]
Hello,

My ultimate goal is to run two android instances on top of linux on two displays using different input devices, but I am still very far from that, still trying to figure out just how to run two anrdoid instances.

Apparently the multi-devices support in binder module solves the kernelspace issue, thus I'd just mknod them inside the container-manager containers. Then from what I understand, I would also need the session-manager inside the container? 

Regards,
Milen Rangelov

**Comment by morphis** [comment]
> Then from what I understand, I would also need the session-manager inside the container?

If you create multiple binder devices, lets say /dev/binder1 and /dev/binder2 you can instruct the session manager to pass the right ones to the container manager in the container configuration. See https://github.com/anbox/anbox/blob/master/src/anbox/cmds/session_manager.cpp#L243

If you're going for nested containerization you can easily let docker or LXD do the job. Just tell them to map /dev/binder1 to /dev/binder inside the outer container and then you can use the session-manager inside the container as before. The only thing you would have to solve in this case is how you pass the X11 connection into the container.

For multi container support inside the container-manager, I said never no, but that is nothing I am going to start working on but happy to review and accept any PRs for that!

**Comment by bo-liu** [comment]
@morphis   For nested containerization, people have to start four containers instead of two.

By the way, put "anbox session manager and the container manager into a container " means the "translator" libraries have to run inside the container.
Then how can the "translator" libraries(inside a container) access the host system glx/gl2.0 libraries?

**Comment by bo-liu** [comment]
I tried to run anbox session-manager inside an container, and got segment fault:
((Still prefer to non nested  containerization, could you please kindly point out:
 what should be done? which files/functions should be modified?))

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff63ea516 in google::protobuf::internal::Mutex::Lock() () from /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9
(gdb) bt
#0  0x00007ffff63ea516 in google::protobuf::internal::Mutex::Lock() () from /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9
#1  0x00007ffff63ea833 in google::protobuf::internal::OnShutdown(void (*)()) () from /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9
#2  0x00007fffec941409 in ?? () from /usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3
#3  0x00007ffff7de76ba in call_init (l=<optimized out>, argc=argc@entry=2, argv=argv@entry=0x7fffffffece8, env=env@entry=0x7fffffffed00) at dl-init.c:72
#4  0x00007ffff7de77cb in call_init (env=0x7fffffffed00, argv=0x7fffffffece8, argc=2, l=<optimized out>) at dl-init.c:30
#5  _dl_init (main_map=main_map@entry=0xd3c9c0, argc=2, argv=0x7fffffffece8, env=0x7fffffffed00) at dl-init.c:120
#6  0x00007ffff7dec8e2 in dl_open_worker (a=a@entry=0x7fffffffd130) at dl-open.c:575
#7  0x00007ffff7de7564 in _dl_catch_error (objname=objname@entry=0x7fffffffd120, errstring=errstring@entry=0x7fffffffd128, mallocedp=mallocedp@entry=0x7fffffffd11f, 
    operate=operate@entry=0x7ffff7dec4d0 <dl_open_worker>, args=args@entry=0x7fffffffd130) at dl-error.c:187
#8  0x00007ffff7debda9 in _dl_open (file=0x7ffff6fc0ce4 "libmirclient.so.9", mode=-2147483646, caller_dlopen=0x7ffff6f94f23, nsid=-2, argc=<optimized out>, 
    argv=<optimized out>, env=0x7fffffffed00) at dl-open.c:660
#9  0x00007ffff660df09 in dlopen_doit (a=a@entry=0x7fffffffd360) at dlopen.c:66
#10 0x00007ffff7de7564 in _dl_catch_error (objname=0xd3b4a0, errstring=0xd3b4a8, mallocedp=0xd3b498, operate=0x7ffff660deb0 <dlopen_doit>, args=0x7fffffffd360) at dl-error.c:187
#11 0x00007ffff660e571 in _dlerror_run (operate=operate@entry=0x7ffff660deb0 <dlopen_doit>, args=args@entry=0x7fffffffd360) at dlerror.c:163
#12 0x00007ffff660dfa1 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#13 0x00007ffff6f94f23 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#14 0x00007ffff6fa61d1 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#15 0x00007ffff6fa77cd in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#16 0x00007ffff6f93ee1 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#17 0x00007ffff6efb397 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#18 0x00000000008e7a97 in anbox::platform::sdl::Platform::Platform (this=0xd3aff0, input_manager=std::shared_ptr (count 2, weak 0) 0xd3acc0, static_display_frame=..., 
    single_window=false) at /home/bob/anbox/src/anbox/platform/sdl/platform.cpp:45
#19 0x00000000008e5530 in __gnu_cxx::new_allocator<anbox::platform::sdl::Platform>::construct<anbox::platform::sdl::Platform, std::shared_ptr<anbox::input::Manager> const&, anbox::graphics::Rect const&, bool&> (this=0x7fffffffd717, __p=0xd3aff0) at /usr/include/c++/5/ext/new_allocator.h:120
#20 0x00000000008e52a4 in std::allocator_traits<std::allocator<anbox::platform::sdl::Platform> >::construct<anbox::platform::sdl::Platform, std::shared_ptr<anbox::input::Manager> const&, anbox::graphics::Rect const&, bool&> (__a=..., __p=0xd3aff0) at /usr/include/c++/5/bits/alloc_traits.h:530
#21 0x00000000008e4f29 in std::_Sp_counted_ptr_inplace<anbox::platform::sdl::Platform, std::allocator<anbox::platform::sdl::Platform>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<std::shared_ptr<anbox::input::Manager> const&, anbox::graphics::Rect const&, bool&> (this=0xd3afe0, __a=...) at /usr/include/c++/5/bits/shared_ptr_base.h:522
#22 0x00000000008e4a07 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<anbox::platform::sdl::Platform, std::allocator<anbox::platform::sdl::Platform>, std::shared_ptr<anbox::input::Manager> const&, anbox::graphics::Rect const&, bool&> (this=0x7fffffffd998, __a=...) at /usr/include/c++/5/bits/shared_ptr_base.h:617
#23 0x00000000008e4715 in std::__shared_ptr<anbox::platform::sdl::Platform, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<anbox::platform::sdl::Platform>, std::shared_ptr<anbox::input::Manager> const&, anbox::graphics::Rect const&, bool&> (this=0x7fffffffd990, __tag=..., __a=...) at /usr/include/c++/5/bits/shared_ptr_base.h:1097
#24 0x00000000008e45f2 in std::shared_ptr<anbox::platform::sdl::Platform>::shared_ptr<std::allocator<anbox::platform::sdl::Platform>, std::shared_ptr<anbox::input::Manager> const&, anbox::graphics::Rect const&, bool&> (this=0x7fffffffd990, __tag=..., __a=...) at /usr/include/c++/5/bits/shared_ptr.h:319
#25 0x00000000008e44a8 in std::allocate_shared<anbox::platform::sdl::Platform, std::allocator<anbox::platform::sdl::Platform>, std::shared_ptr<anbox::input::Manager> const&, anbox::graphics::Rect const&, bool&> (__a=...) at /usr/include/c++/5/bits/shared_ptr.h:620
#26 0x00000000008e4289 in std::make_shared<anbox::platform::sdl::Platform, std::shared_ptr<anbox::input::Manager> const&, anbox::graphics::Rect const&, bool&> ()
    at /usr/include/c++/5/bits/shared_ptr.h:636
#27 0x00000000008e3d76 in anbox::platform::create (name="sdl", input_manager=std::shared_ptr (count 2, weak 0) 0xd3acc0, display_frame=..., single_window=false)
    at /home/bob/anbox/src/anbox/platform/base_platform.cpp:33
#28 0x00000000008280f1 in anbox::cmds::SessionManager::SessionManager()::{lambda(anbox::cli::Command::Context const&)#1}::operator()(anbox::cli::Command::Context const&) const
    () at /home/bob/anbox/src/anbox/cmds/session_manager.cpp:169
#29 0x000000000082af5d in std::_Function_handler<int(const anbox::cli::Command::Context&), anbox::cmds::SessionManager::SessionManager()::<lambda(const anbox::cli::Command::Context&)> >::_M_invoke(const std::_Any_data &, const anbox::cli::Command::Context &) (__functor=..., __args#0=...) at /usr/include/c++/5/functional:1857
#30 0x0000000000819eb3 in std::function<int (anbox::cli::Command::Context const&)>::operator()(anbox::cli::Command::Context const&) const (this=0xd351d0, __args#0=...)
    at /usr/include/c++/5/functional:2267
#31 0x0000000000817641 in anbox::cli::CommandWithFlagsAndAction::run (this=0xd35130, ctxt=...) at /home/bob/anbox/src/anbox/cli.cpp:214
#32 0x00000000008170b4 in anbox::cli::CommandWithSubcommands::run (this=0x7fffffffeb08, ctxt=...) at /home/bob/anbox/src/anbox/cli.cpp:162
#33 0x0000000000821bf1 in anbox::Daemon::Run (this=0x7fffffffeb00, arguments=std::vector of length 1, capacity 1 = {...}) at /home/bob/anbox/src/anbox/daemon.cpp:56
#34 0x00000000008022d1 in main (argc=2, argv=0x7fffffffece8) at /home/bob/anbox/src/main.cpp:23
(gdb)

**Comment by gmistick** [comment]
Hi guys, Is this issue still active?
I need to run multiple android devices and i thought a docker containing anbox can be solution (Nested containerization ) 
Any ideas?

**Comment by ss14** [comment]
I came across a blog from Simon demonstrating multiple android containers in aws using anbox. https://ubuntu.com/blog/running-android-in-the-cloud-with-amazon-ec2-a1-instances

How was this done? Is latest anbox supporting multiple containers? Any detail on the demo implementation will be a great help.

Thanks!

**Comment by markknit** [comment]
I have the same requirement. I'm supporting multiple users on a Linux (Ubuntu) server. The users need to access Android apps. 

Is there a way to do this now?

**Comment by lygstate** [comment]
> We have a set of patches to allow namespacing of the binder driver. See https://github.com/anbox/anbox/tree/master/kernel/patches
> 
> However this comes with the cost of that you have to rebuild your entire kernel and not just the DKMS package we provide. The better way to go without a kernel rebuild is by using the recently introduced `devices` parameter of the binder kernel module. This allows you to create multiple independent binder nodes inside /dev. Try with `modprobe binder_linux devices=binder,binder1,binder2` and you will see /dev/binder, /dev/binder1, /dev/binder2.
> 
> The Anbox container-manager will most likely not see support for multiple containers. But what you can do quite easily (and this will also help you with the dbus address problem) is that you can put both the anbox session manager and the container manager into a container and use nested containerization to spawn up the Android container inside the container.
How to do nested containerization with anbox？
> 
> Can you give a few examples of what your use case is?
