### ISSUE TITLE
Can't run on archlinux because that Failed to initialize EGL

### ISSUE THREAD

**Issue by Ailick** [anbox/anbox#414]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
[ailick@Ailick_Mj ~]$ anbox system-info[ailick@Ailick_Mj ~]$ ANBOX_LOG_LEVEL=debug anbox system-info
segmentation fault (core dumped) 

**Please describe your problem:**
ailick@Ailick_Mj ~]$ ANBOX_LOG_LEVEL=debug anbox session-manager
[EE 2017-08-20 13:18:57] [Renderer.cpp:104@initialize] Failed to initialize EGL
segmentation fault (core dumped) 

**What were you expecting?:**
Why did I see that Failed to initialize EGL?
I'm useing IntelHD4600 and NvidiaGTX 760M with bumblebee on archlinux..And I just installed it from AUR.


I need help please.
**Additional info:**

**Comment by morphis** [comment]
If you're taking Anbox for AUR I can't really comment. Not sure which version of Anbox that is using or how it was built.  Any reason you're not using the snap as officially recommended?

**Comment by Ailick** [comment]
Snap is not working well on ArchLinux when installing Anbox. It told me sucess but nothing on my desktop

**Comment by morphis** [comment]
@Ailick These are problems with snapd itself. Please head over to https://forum.snapcraft.io to get help with snaps in general on ArchLinux. Nothing we can fix here. Thanks.
