### ISSUE TITLE
Anbox fails to initialize on Ubuntu 16.04 with nvidia 384

### ISSUE THREAD

**Issue by jontis** [anbox/anbox#417]
$ ANBOX_LOG_LEVEL=debug anbox session-manager
[II 2017-08-22 11:51:40] [session_manager.cpp:139@operator()] Detected properietary nvidia driver; forcing use of the host EGL driver.
[EE 2017-08-22 11:51:40] [Renderer.cpp:99@initialize] Failed to Initialize backend EGL display
Segmentation fault

** Please paste the result of `anbox system-info` below:**
$ anbox system-info
version: 3
snap-revision: 52
os:
  name: Linux Mint
  version: 18.1 (Serena)
  snap-based: true
kernel:
  version: Linux version 4.11.0-14-generic (buildd@lcy01-08) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #20~16.04.1-Ubuntu SMP Wed Aug 9 09:06:22 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

**Please describe your problem:**
anbox fails to start

**What were you expecting?:**

**Additional info:**
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 384.59
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

**Comment by StchaoL** [comment]
Yes, I got this problem, too.
