### ISSUE TITLE
anbox-installer : permission denied

### ISSUE THREAD

**Issue by ajabref** [anbox/anbox#418]
I just tried to install anbox on ubuntu 16.04.3 64bits.
The installer fails because of a problem of permission.
It seems similar to the issue reported here: https://www.bountysource.com/issues/47998352-not-root-owned

Here is a short log of what I did:
`mypc:~ $ sudo  snap install --classic anbox-installer`
`2017-08-23T09:50:35+02:00 INFO Waiting for restart...`
`anbox-installer 1 from 'morphis' installed`
`mypc:~ $ whoami`
`myusername`
`mypc:~ $ ls -alh ~/snap/*`
`total 16K`
`drwxr-xr-x 4 myusername myusergroup 4,0K août  23 09:50 .`
`drwxr-xr-x 3 myusername myusergroup 4,0K août  23 09:50 ..`
`drwxr-xr-x 2 myusername myusergroup 4,0K août  23 09:50 17`
`drwxr-xr-x 2 myusername myusergroup 4,0K août  23 09:50 common`
`lrwxrwxrwx 1 myusername myusergroup    2 août  23 09:50 current -> 17`
`mypc:~ $  anbox-installer`
`cannot create user data directory: /home/myusername/snap/anbox-installer/17: Permission denied
`mypc:~ $ `

**Comment by morphis** [comment]
This is not really an issue with Anbox but more an issue with your system and snaps in general. Can you please go to https://forum.snapcraft.io and ask for help? This is nothing we can fix here. Thanks!

**Comment by ajabref** [comment]
OK, I'll go and ask.
But it seems to be somehow specific to Anbox, as I can install other snaps without any problem:
`mypc:~ $ sudo snap install freecad`
`freecad 0.17 from 'vejmarie' installed`

**Comment by ajabref** [comment]
OK, I found something.
I have both:
`~/snap/andbox-installer` and `/snap/andbox-installer` on my system.
Running `/snap/anbox-installer/17/installer.sh` works!

**Comment by ajabref** [comment]
It's indeed a snap known bug with NFS home directory:

https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1662552

**Comment by dimonic** [comment]
Also occurred on my system where home is secured by likewise (now pbis) open. I was able to run the install from the /snap directory thanks to +ajabref.
