### ISSUE TITLE
Fedora 28: cannot install "anbox-installer": classic confinement is not yet supported

### ISSUE THREAD

**Issue by jayvdb** [anbox/anbox#427]
```
$ snap version
snap    2.27.2-2.fc28
snapd   2.27.2-2.fc28
series  16
fedora  28
kernel  4.13.0-0.rc6.git3.1.fc28.x86_64
```

```
$ snap install --classic anbox-installer
error: cannot install "anbox-installer": classic confinement is not yet supported on your
       distribution
$ snap install anbox-installer
error: This revision of snap "anbox-installer" was published using classic confinement and thus may
       perform arbitrary system changes outside of the security sandbox that snaps are usually
       confined to, which may put your system at risk.

       If you understand and want to proceed repeat the command including --classic.
$ snap install --devmode anbox-installer
error: This revision of snap "anbox-installer" was published using classic confinement and thus may
       perform arbitrary system changes outside of the security sandbox that snaps are usually
       confined to, which may put your system at risk.

       If you understand and want to proceed repeat the command including --classic.
```

**Please describe your problem:**
`--classic` doesnt work with Fedora snap (see https://github.com/snapcore/snapd/wiki/Distributions), and `--devmode` also complains.

**What were you expecting?:**
As anbox is using a packaging system which is designed to support multiple distros, it would be nice if the instructions for anbox worked on multiple distro, and indicated which GNU/Linux systems it works on.

**Additional info:**

**Comment by jayvdb** [comment]
Following https://discourse.anbox.io/t/error-when-trying-to-install-on-fedora/82 , the following worked for me:

```
$ snap install --devmode --edge anbox
$ /var/lib/snapd/snap/bin/anbox session-manager
[ 2017-08-27 06:02:52] [session_manager.cpp:147@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded
```

I assume that error is an unrelated problem.
So maybe that command should be included in the README?

**Comment by moceap** [comment]
@jayvdb https://bugzilla.redhat.com/show_bug.cgi?id=1455411

**Comment by Crazily** [comment]
Issue still happens.

**Comment by archesys** [comment]
@jayvdb  Thank you..
snap install --devmode --edge anbox
works for me on archlinux (manjaro) where I had the same error..
