### ISSUE TITLE
cannot create user data directory: Bad file descriptor

### ISSUE THREAD

**Issue by CODeRUS** [anbox/anbox#43]
**Anbox release (`anbox version`) and system info (`anbox system-info`):**
can't get version, anbox not starting

**Description of the problem:**
anbox not starting, calling `anbox` from terminal gives:
```cannot create user data directory: /home/OMP/a.kozhevnikov/snap/anbox/15: Bad file descriptor```

**Expected:**
anbox should start :)

**Additional info:**
Ubuntu 16.10
Linux inp1wst011 4.8.0-46-generic #49-Ubuntu SMP Fri Mar 31 13:57:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
anbox installed from https://github.com/anbox/anbox-installer

**Comment by vosst** [comment]
Do you use any special mount options for your home directories? Could you try to manually create that directory for testing purposes?

**Comment by CODeRUS** [comment]
it exists. stat says following:
```  File: '/home/OMP/a.kozhevnikov/snap/anbox/15'
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 10302h/66306d   Inode: 10243455    Links: 2
Access: (0755/drwxr-xr-x)  Uid: (10047/a.kozhevnikov)   Gid: (10007/domain users)
Access: 2017-04-12 13:40:14.650251371 +0300
Modify: 2017-04-12 13:23:32.132261978 +0300
Change: 2017-04-12 13:23:32.132261978 +0300
 Birth: -```

**Comment by anibyl** [comment]
I have this issue too. My home dir is linked via `ln` from other drive.

**Comment by Kirupakaran** [comment]
Facing the same problem. Directory exists. Tried to chown that directory. Didn't make a difference.

cannot create user data directory: snap/anbox-installer/10: Bad file descriptor

**Comment by benmichael** [comment]
Same issue as above, this on the installer:

```
$ sudo snap install --classic anbox-installer
anbox-installer 1 from 'morphis' installed

$ anbox-installer 
cannot create user data directory: /home/local/ANT/jonapage/snap/anbox-installer/10: Bad file descriptor

$ stat /home/local/ANT/jonapage/snap/anbox-installer/10
  File: '/home/local/ANT/jonapage/snap/anbox-installer/10'
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fc01h/64513d    Inode: 11671795    Links: 2
Access: (0755/drwxr-xr-x)  Uid: (1420008642/jonapage)   Gid: (1419772417/domain^users)
Access: 2017-04-13 11:25:45.328569304 +0200
Modify: 2017-04-13 11:21:28.145014489 +0200
Change: 2017-04-13 11:21:28.145014489 +0200
 Birth: -
```

**Comment by Meroje** [comment]
I was able to fix this error by reconfiguring apparmor HOMEDIRS using `sudo dpkg-reconfigure apparmor`

For example here, @benmichael would set `/home/local/ANT` in the dpkg prompt

**Comment by CODeRUS** [comment]
after apparmor reconfigure i'm detting other error: `cannot create user data directory: /home/OMP/a.kozhevnikov/snap/anbox/15: Permission denied`
stat is same as above

**Comment by CODeRUS** [comment]
Reconfiguring apparmor helped, but now i have different problem: https://github.com/anbox/anbox/issues/138
