### ISSUE TITLE
Some discussions of the code

### ISSUE THREAD

**Issue by jackwish** [anbox/anbox#431]
Hi, I am enhancing something here and have some questions of the code, please help to give a hint.

**Comment by jackwish** [comment]
for the function  https://github.com/anbox/anbox/blob/17f6c8cd8b15eab91a5d6274232b5ab351fefe46/src/anbox/utils.cpp#L45, you inteded to read file and stop when encoutered a "black"? I am thinking read whole file (which is expected to be small) to a string...

**Comment by morphis** [comment]
@jackwish Can you create a topic for this over at https://discourse.anbox.io/ ? That is the more appropriate place for these discussions.
