### ISSUE TITLE
anbox android compiler error when build android opengl libraries

### ISSUE THREAD

**Issue by Vichardw** [anbox/anbox#449]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**
cann't find "emugl/common/logging.h" file in below head files
android/opengl/system/GLESv1_enc/gl_client_proc.h
android/opengl/system/GLESv2_enc/gl2_client_proc.h
android/opengl/system/renderControl_enc/renderControl_client_proc.h

**What were you expecting?:**

**Additional info:**

**Comment by PierrotIV** [comment]
Hi,

I had the same error and finally get a successful build by entering each directory (cd vendor/anbox/android/opengl/system/GLESv1_enc/ and so on) and creating a symlink to emugl (ln -s ../../../../external/android-emugl/shared/emugl/ .).

Hope that helps.

Regards
