### ISSUE TITLE
Change Screen Size

### ISSUE THREAD

**Issue by putraxor** [anbox/anbox#45]
Hi, is it possible to change default screen size of Anbox?

**Comment by morphis** [comment]
@putraxor What screen size do you want to change? Anbox takes the entire screen of your device by default and maps that to Android so Android really things it has the entire screen. What we don't support yet is hotplugged displays. For that you need to restart the anbox session-manager service.

**Comment by putraxor** [comment]
I want to change the default screen size to hdpi screen 480x800
is there any configuration?

**Comment by morphis** [comment]
@putraxor You want to change the screen size of a single app window? That size is pretty dynamic and you can just resize the window as you would resize any normal window on your desktop.

**Comment by putraxor** [comment]
Actually I want to set default screen size for every installed Apps.
I test Anbox for app development purpose, so it makes sense to set screen size of Anbox match with screen size in IDE

**Comment by morphis** [comment]
Please respect that Anbox operates Anbox in the freeform mode of Android (see https://developer.android.com/guide/topics/ui/multi-window.html for details). That way there is no real default size of a window or something you can set statically. The default size depends on the actual monitor, resolution and dpi.

That said you can still get what you want with a small trick:

```
$ initctl stop anbox # on Ubuntu 16.04
$ systemctl --user stop anbox # On others
$ anbox session-manager --single-window --window-size=1024,768
```

That will give you Android running in a single window. You will loose the multi-window feature which Anbox offers by default though.

**Comment by putraxor** [comment]
Thank you very much. It seems better to use `wmctrl` in my case

**Comment by CreatorB** [comment]
> Thank you very much. It seems better to use `wmctrl` in my case

@putraxor can you provide the details? maybe will be beneficial to someone else
