### ISSUE TITLE
Not able to install whatapp/ hike messenger

### ISSUE THREAD

**Issue by Ajinkz** [anbox/anbox#456]
$ adb install hike506.apk

**following message was display**
35934 KB/s (30779919 bytes in 0.836s)
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

How to fix this isuue.
kindly help me to resolve this issue

**Comment by yahe** [comment]
Hey @Ajinkz have a look here in [Wiki/Common Problems](https://github.com/anbox/anbox/wiki/Common-Problems#apk-installation-and-install_failed_no_matching_abis). In particular, to the best of my knowledge Hike only supports ARM.

**Comment by zhiquan-yu** [comment]
I also encountered this problem, when install WeChat.
I've read the [Wiki/Common Problems](https://github.com/anbox/anbox/wiki/Common-Problems#apk-installation-and-install_failed_no_matching_abis)

> Most apks are made especially for armhf and are not prepared to run on amd64. There is nothing Anbox can do here as its totally up to the apk vendor to ship a apk supporting all necessary architectures.

Now I think Anbox‘s role is very small.
