### ISSUE TITLE
Onenote installed and working but not network connection! Ubuntu 16.04

### ISSUE THREAD

**Issue by majordoobie** [anbox/anbox#466]
Was able to successfully install Anbox and install onenote and it works awesome. Super fast, without any lag. First time go too, this blows WINE + Onenote 2013 out of the water. Only issue is that it cannot make a network connection. I assumed that maybe it's because of Google Play Store but to verify that theory I tried to use the browser that is included and still could not make a network connection. My only thought is that maybe this isn't configured to make network connections yet?

![image](https://user-images.githubusercontent.com/18517902/30480094-0c6d0e96-99e6-11e7-81b1-750089ac9cf8.png)
![image](https://user-images.githubusercontent.com/18517902/30480125-3d3545c0-99e6-11e7-9917-49006b75a36f.png)
![image](https://user-images.githubusercontent.com/18517902/30480134-4ed5ea8c-99e6-11e7-805a-454b1ad66087.png)

**Comment by Antisound** [comment]
Do you have android-bridge.sh script used to build a network connection?

**Comment by ducklin5** [comment]
what and where is the android-bridge.sh script ?
