### ISSUE TITLE
device offline

### ISSUE THREAD

**Issue by SwapnilSpectra** [anbox/anbox#468]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```$ adb install SefferyMerchant-release.apk
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
error: device offline
- waiting for device -

[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by ShmingMaster** [comment]
I'm getting the exact same thing, 95% sure it's just me being an idiot, but still, anybody know what I'm doing wrong?
