### ISSUE TITLE
execv failed: No such file or directory

### ISSUE THREAD

**Issue by dwedaz** [anbox/anbox#47]
**Anbox release (`anbox version`) and system info (`anbox system-info`):**
name:      anbox-installer
summary:   "Installer for the Android in a Box runtime environment"
publisher: morphis
description: |
  A classic snap which will install the Android in a Box runtime
  environment on an Ubuntu system.
  
commands:
  - anbox-installer
tracking:    stable
installed:   1 (9) 4kB classic
refreshed:   2017-04-12 16:09:37 +0700 WIB
channels:          
  stable:    1 (9) 4kB classic
  candidate: 1 (9) 4kB classic
  beta:      1 (9) 4kB classic
  edge:      1 (9) 4kB classic

**Description of the problem:**

i got this error after when runing anbox-installer:
**"execv failed: No such file or directory"**

**Additional info:**
I am using arch linux.

**Comment by kevinarefunny** [comment]
I'm getting this same issue on Ubuntu 17.04

λ kevin [~] → sudo snap install --classic anbox-installer && anbox-installer
anbox-installer 1 from 'morphis' installed
cannot change profile for the next exec call: No such file or directory

**Comment by enetarch** [comment]
snap install --classic anbox-installer && anbox-installer
2017-04-12T13:20:05-07:00 INFO Waiting for restart...
anbox-installer 1 from 'morphis' installed
execv failed: No such file or directory

Linux localhost.localdomain 4.10.8-200.fc25.x86_64 #1 SMP Fri Mar 31 13:20:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by StefanBeyer** [comment]
Same here on Fedora 25:

sudo snap install --classic anbox-installer && anbox-installer
anbox-installer 1 from 'morphis' installed
execv failed: No such file or directory

**Comment by jdsmit60** [comment]
First, please be aware that all that anbox-installer does is download the anbox installer bash script. This script checks your distro before doing anything, and if you're not running one of a few Ubuntu based distros it will refuse to install.

Second, on Arch your snap executable files will be located in /var/lib/snapd/snap/bin. Check there for the files that you downloaded when you installed the anbox-installer snap.

**Comment by jdsmit60** [comment]
Also, if you really want to run anbox on Arch (like me) despite Arch not being supported, there's an AUR package: anbox-git. You'll have to install boost and doxygen before installing anbox-git, since those two packages are missing dependencies for a package that anbox-git pulls in.

**Comment by dwedaz** [comment]
> Also, if you really want to run anbox on Arch (like me) despite Arch not being supported, there's an AUR package: anbox-git. You'll have to install boost and doxygen before installing anbox-git, since those two packages are missing dependencies for a package that anbox-git pulls in.

Thanks. 
to install anbox in arch linux 

pacman -S boost
pacman -S doxygen
yaourt process-cpp #its broken use this instead https://privatebin.net/?f58fb2de2393b776#2QJeNJ8f2rWJbRRSXwlyElzUijbKN2mevk7lwBFNl1w=
yaourt -S anbox-git

**Comment by kevinarefunny** [comment]
@dwedaz this shouldn't be closed because there are other users not on Arch experiencing the same issue. Please open it again.

**Comment by dwedaz** [comment]
@kevinarefunny reopened

**Comment by kevinarefunny** [comment]
@dwedaz Thank you.

**Comment by Kwaadpepper** [comment]
I have this problem on Ubuntu 16.04.2.

**Comment by tuxflo** [comment]
Same here, running KDE Neon which is based on Ubuntu 16.04.

**Comment by sergiomb2** [comment]
+1 in Fedora 26

**Comment by kawache** [comment]
Fixed on Fedora 26 and 27 with :

ln -s /usr/libexec/snapd /usr/lib/

**Comment by sergiomb2** [comment]
and at least 

    ln -s /var/lib/snapd/snap /
