### ISSUE TITLE
Segmentation fault (core dumped) when running anbox system-info

### ISSUE THREAD

**Issue by Pectojin** [anbox/anbox#475]
** Please paste the result of `anbox system-info` below:**
```
$ anbox system-info
Segmentation fault (core dumped)

$ ANBOX_LOG_LEVEL=debug anbox system-info
Segmentation fault (core dumped)
```

**Please describe your problem:**
Anbox crashes with segmentation fault any time I call it with argument "system-info" or "session-manager". 

It provides no other output and it does not create any logs in /var/log/anbox/ or /var/log/snap/

The only trace I can find of it even attempting to run is in my syslog:
```
kernel: [  497.737230] audit: type=1400 audit(1506276334.040:405): apparmor="ALLOWED" operation="open" profile="snap.anbox.anbox" name="/proc/4705/cgroup" pid=4705 comm="anbox" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
```

**What were you expecting?:**
Some kind of stack trace that would help in troubleshooting why session-manager won't run ;)

**Additional info:**
I've done several reinstalls and the installer output never seems to throw any errors or warnings.
Running Ubuntu 16.04.03 with 4.4.0-96-generic x86_64 kernel with anbox "version 3". 
Snap does not appear to populate ~/snap/anbox/ with files. Only /snap/anbox/ has files within the folder, no idea if this is relevant.

**Comment by PowerInside** [comment]
Type `ulimit -c unlimited` and then run the command that gives you seg fault, and do `coredumpctl gdb` to open gdb for the last coredump. Once gdb is open, type "bt" to get the stacktrace.

**Comment by Pectojin** [comment]
Thanks for the tip

I'm getting the following stack trace with `anbox system-info`:
<img width="1440" alt="screen shot 2017-10-04 at 16 32 40" src="https://user-images.githubusercontent.com/1561484/31181489-be79ee20-a921-11e7-85bd-89db0b60abdd.png">

And this stack trace with `anbox session-manager`:
<img width="1440" alt="screen shot 2017-10-04 at 16 33 09" src="https://user-images.githubusercontent.com/1561484/31181521-dd08d838-a921-11e7-9844-27fac2fc0087.png">

I must admit, I'm not very well versed C++, so I don't know entirely what to look for.

**Comment by Pectojin** [comment]
Actually, I was just able to run both `anbox system-info` and `anbox session-manager` on a clean install of Ubuntu on a different machine. 

So odds are that this is just a messed up Ubuntu install and isn't worth investing dev time into.

**Comment by CedricDC** [comment]
I get the same error running Linux Mint 18.2 (Sonya) when I enable the onboard Intel graphics card. With the NVidia card, the session manager does not start, but system-info works (#72 solves the segfault, but nothing happens):
version: 3
snap-revision: 64
os:
  name: Linux Mint
  version: 18.2 (Sonya)
  snap-based: true
kernel:
  version: Linux version 4.10.0-37-generic (buildd@lgw01-amd64-037) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.4
    extensions:
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_output_base
      - EGL_EXT_stream_acquire_mode
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context_no_error
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_partial_update
      - EGL_KHR_swap_buffers_with_damage
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_stream
      - EGL_KHR_stream_consumer_gltexture
      - EGL_KHR_stream_cross_process_fd
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_surfaceless_context
      - EGL_NV_post_sub_buffer
      - EGL_NV_stream_metadata
      - EGL_NV_stream_sync
      - EGL_NV_stream_consumer_gltexture_yuv
      - EGL_NV_stream_attrib
      - EGL_NV_sync
      - EGL_NV_system_time
      - EGL_NV_output_drm_flip_event
      - EGL_WL_bind_wayland_display
      - EGL_WL_wayland_eglstream
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 1.1 NVIDIA 375.66
    extensions:
      - GL_EXT_debug_label
      - GL_EXT_map_buffer_range
      - GL_EXT_robustness
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_format_BGRA8888
      - GL_KHR_debug
      - GL_NV_texture_compression_s3tc
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_compressed_paletted_texture
      - GL_OES_draw_texture
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_extended_matrix_palette
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_matrix_get
      - GL_OES_matrix_palette
      - GL_OES_packed_depth_stencil
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_OES_rgb8_rgba8
      - GL_OES_read_format
      - GL_OES_stencil8
      - GL_OES_texture_cube_map
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float

**Comment by GrigorievNick** [comment]
Same
For $ anbox system-info
version: 3
snap-revision: 65
os:
  name: Ubuntu
  version: 17.10 (Artful Aardvark)
  snap-based: true
kernel:
  version: Linux version 4.13.0-17-generic (buildd@lcy01-amd64-011) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)) #20-Ubuntu SMP Mon Nov 6 10:04:08 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.4
    extensions:
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_output_base
      - EGL_EXT_stream_acquire_mode
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context_no_error
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_partial_update
      - EGL_KHR_swap_buffers_with_damage
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_stream
      - EGL_KHR_stream_consumer_gltexture
      - EGL_KHR_stream_cross_process_fd
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_surfaceless_context
      - EGL_NV_post_sub_buffer
      - EGL_NV_stream_metadata
      - EGL_NV_stream_sync
      - EGL_NV_stream_consumer_gltexture_yuv
      - EGL_NV_stream_attrib
      - EGL_NV_sync
      - EGL_NV_system_time
      - EGL_NV_output_drm_flip_event
      - EGL_WL_bind_wayland_display
      - EGL_WL_wayland_eglstream
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 1.1 NVIDIA 375.82
    extensions:
      - GL_EXT_debug_label
      - GL_EXT_map_buffer_range
      - GL_EXT_robustness
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_format_BGRA8888
      - GL_KHR_debug
      - GL_NV_texture_compression_s3tc
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_compressed_paletted_texture
      - GL_OES_draw_texture
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_extended_matrix_palette
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_matrix_get
      - GL_OES_matrix_palette
      - GL_OES_packed_depth_stencil
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_OES_rgb8_rgba8
      - GL_OES_read_format
      - GL_OES_stencil8
      - GL_OES_texture_cube_map
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float

anbox session-manager
Segmentation fault (core dumped)

**Comment by volkerbradley** [comment]
I also see segmentation fault (core dumped) when trying to run anbox system-info. Here is the output using the commands suggested above:
warning: Could not load shared library symbols for 5 libraries, e.g. /var/lib/snapd/lib/gl/libEGL.so.1.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/snap/anbox/65/usr/bin/anbox system-info'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00000000004e4c32 in anbox::cmds::SystemInfo::SystemInfo()::{lambda(anbox::cli::Command::Context const&)#1}::operator()(anbox::cli::Command::Context const&) const [clone .isra.76] ()
#2  0x00000000004c58f6 in anbox::cli::CommandWithFlagsAndAction::run(anbox::cli::Command::Context const&) ()
#3  0x00000000004c53b3 in anbox::cli::CommandWithSubcommands::run(anbox::cli::Command::Context const&) ()
#4  0x00000000004c9e16 in anbox::Daemon::Run(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#5  0x00000000004af72f in main ()
(gdb)

Do you have any suggestions?

**Comment by Pectojin** [comment]
It seems I wasn't the only one who experienced this. I've reopened the issue due to the above 3 comments reporting the same.

**Comment by volkerbradley** [comment]
Thanks.  I am using Ubuntu 16.04 with a Nvidia GeForce GTX 285M Graphics
Card with 1GB GDDR3 Video Memory.

**Comment by PeterMX** [comment]
i got this:
![image](https://user-images.githubusercontent.com/9899682/34245828-6cc8a60e-e5f1-11e7-8739-49ce4c4a812a.png)

**Comment by Jedarc** [comment]
+1

**Comment by gmistick** [comment]
I think this was solved in the latest snap.
@morphis

**Comment by YangKeao** [comment]
I got this:

```
Stack trace (most recent call last):
#8    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#7    Object "/snap/anbox/92/usr/bin/anbox", at 0x4a4898, in _start
#6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f41c984582f, in __libc_start_main
#5    Object "/snap/anbox/92/usr/bin/anbox", at 0x4a030e, in main
#4    Object "/snap/anbox/92/usr/bin/anbox", at 0x4bb587, in anbox::Daemon::Run(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
#3    Object "/snap/anbox/92/usr/bin/anbox", at 0x4b76af, in anbox::cli::CommandWithSubcommands::run(anbox::cli::Command::Context const&)
#2    Object "/snap/anbox/92/usr/bin/anbox", at 0x4b7171, in anbox::cli::CommandWithFlagsAndAction::run(anbox::cli::Command::Context const&)
#1    Object "/snap/anbox/92/usr/bin/anbox", at 0x4d4e92, in 
#0    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f41c98b0746, in strlen
Segmentation fault (Address not mapped to object [(nil)])
[1]    7018 segmentation fault (core dumped)  anbox system-info
