### ISSUE TITLE
Anbox doesn't launch

### ISSUE THREAD

**Issue by grenadecx** [anbox/anbox#48]
Make sure you are running the latest version of Anbox before reporting an issue.

**Anbox release (`anbox version`) and system info (`anbox system-info`):**

anbox version: anbox 0.1.0

anbox system-info:

version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.4.0-72-generic (buildd@lcy01-17) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.4
    extensions:
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_output_base
      - EGL_EXT_stream_acquire_mode
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context_no_error
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_partial_update
      - EGL_KHR_swap_buffers_with_damage
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_stream
      - EGL_KHR_stream_consumer_gltexture
      - EGL_KHR_stream_cross_process_fd
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_surfaceless_context
      - EGL_NV_post_sub_buffer
      - EGL_NV_stream_metadata
      - EGL_NV_stream_sync
      - EGL_NV_stream_consumer_gltexture_yuv
      - EGL_NV_sync
      - EGL_NV_system_time
      - EGL_NV_output_drm_flip_event
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 1.1 NVIDIA 364.19
    extensions:
      - GL_EXT_debug_label
      - GL_EXT_map_buffer_range
      - GL_EXT_robustness
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_format_BGRA8888
      - GL_KHR_debug
      - GL_NV_texture_compression_s3tc
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_compressed_paletted_texture
      - GL_OES_draw_texture
      - GL_OES_EGL_image
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_extended_matrix_palette
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_matrix_get
      - GL_OES_matrix_palette
      - GL_OES_packed_depth_stencil
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_OES_rgb8_rgba8
      - GL_OES_read_format
      - GL_OES_stencil8
      - GL_OES_texture_cube_map
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float

**Description of the problem:**
Anbox doesn't start at all.

**Expected:**
Anbox to startup.

**Additional info:**
Not sure what else I can do or provide.

I tried:
grenadecx@dakara:~$ anbox launch
[EE 2017-04-12 14:08:42] [launch.cpp:76@operator()] Anbox session manager service isn't running!
grenadecx@dakara:~$ anbox session-manager
Segmentation fault (core dumped)

**Comment by IamR3m** [comment]
Same to me, but some different. I can't launch session-manager. When I run `anbox session-manager` command line output is empty, even after some time. I need to Ctrl+C to abort task.
```
r3m@r3m-desktop:~$ anbox version
anbox 0.1.0
r3m@r3m-desktop:~$ anbox system-info
Ошибка сегментирования (сделан дамп памяти)
```
In English it says same, that **grenadecx** have running session-manager: Segmentation fault

Host: Ubuntu 14.04.1 x64
kernel: 4.4.0-75-generic #96~14.04.1-Ubuntu

**Comment by netjedi** [comment]
Same to me, but run **anbox session-manager** report:
[EE 2017-04-28 01:30:55] [session_manager.cpp:119@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded

**Comment by orlando-antonino** [comment]
hello, maybe a kernel update? you can try the command in this gist to recompile and reinstall the modules:
https://gist.github.com/orlando-antonino/ad11928782f6c8c6d07ada58183b467c
