### ISSUE TITLE
ANBOX doesn't open on Ubuntu 16.04

### ISSUE THREAD

**Issue by TomTerrific1** [anbox/anbox#485]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```[sudo] password for tom: 
[ 2017-10-09 20:33:02] [daemon.cpp:58@Run] org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
tom@tom-desktop:~$ anbox session-manager

[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**
installed snap
sudo snap install --classic anbox-installer && anbox-installer  anbox 
anbox session-manager in a terminal

when it didn't open on my desktop loaded these....

sudo add-apt-repository -y ppa:morphis/anbox-support
sudo apt update
sudo apt install -y anbox-modules-dkms

still does not open on my desktop.
Ubuntu 16.04 LTS

**What were you expecting?:**
never opened the window with ANBOX.
Icon blinks and then stops... nothing..

**Additional info:**

**Comment by oopen** [comment]
Ubuntu 17.04 (zesty)
Same problem, Anbox lastest snap version.
looked on splash: Starting ... 
then exit
![anbox-fail-start](https://user-images.githubusercontent.com/7348132/31442479-e0314c0a-ae96-11e7-94b6-ed605479fe75.png)

**Comment by boospy** [comment]
Yes same problem here on 16.04 with KDE-Neon.
