### ISSUE TITLE
Anbox on Windows (via WSL; tracking issue)

### ISSUE THREAD

**Issue by lostmsu** [anbox/anbox#487]
Looks like it should be possible to run Android in LXC on Windows Subsystem for Linux. There are even docker images of Android for Windows. Seems like Anbox driver wrappers could run directly on Windows (to get access to OpenGL), or at least inside WSL with graphics emulation layer.

**Comment by krystinalynn** [comment]
Correct me if I'm wrong, but isn't Fortnite for Android limited to select devices? I remember it was exclusive to Samsung users, but I believe it's since opened up to more devices. Perhaps it's a hardcoded hardware check?

Source: https://www.epicgames.com/fortnite/en-US/faq#android

> How can I play Fortnite on my Android device?
> Visit Fortnite.com on your Android device to sign up for the Android Beta. Players on Samsung Galaxy devices will be able to drop in immediately and we'll begin rolling out access in waves for other compatible Android devices over the next few days!
> 
> What Android devices are compatible with Fortnite on mobile?
> Android Beta initially will work on the following devices:
> -- Samsung Galaxy: S7 / S7 Edge , S8 / S8+, S9 / S9+, Note 8, Note 9, Tab S3, Tab S4
> -- Google: Pixel / Pixel XL, Pixel 2 / Pixel 2 XL
> -- Asus: ROG Phone, Zenfone 4 Pro, 5Z, V
> -- Essential: PH-1
> -- Huawei: Honor 10, Honor Play, Mate 10 / Pro, Mate RS, Nova 3, P20 / Pro, V10
> -- LG: G5, G6, G7 ThinQ, V20, V30 / V30+
> -- Nokia: 8
> -- OnePlus: 5 / 5T, 6
> -- Razer: Phone
> -- Xiaomi: Blackshark, Mi 5 / 5S / 5S Plus, 6 / 6 Plus, Mi 8 / 8 Explorer / 8SE, Mi Mix, Mi Mix 2, Mi Mix 2S, Mi Note 2
> -- ZTE: Axon 7 / 7s, Axon M, Nubia / Z17 / Z17s, Nubia Z11
> 
> Currently unsupported, working on fixes in the near term:
> -- HTC: 10, U Ultra, U11 / U11+, U12+
> -- Lenovo: Moto Z / Z Droid, Moto Z2 Force
> -- Sony: Xperia: XZ/ XZs, XZ1, XZ2
> 
> If your phone is not on this list, it might still work assuming if you have the following specs:
> -- OS: 64 bit Android, 5.0 or higher
> -- RAM: 3GB or higher
> -- GPU: Adreno 530 or higher, Mali-G71 MP20, Mali-G72 MP12 or higher

**Comment by AmitKKhanchandani** [comment]
Can we run this on windows 10?

**Comment by Rob9889** [comment]
Any tutorial on how to do this?

**Comment by ilkersigirci** [comment]
I am also wondering this.

**Comment by AmitKKhanchandani** [comment]
> Looks like it should be possible to run Android in LXC on Windows Subsystem for Linux. There are even docker images of Android for Windows. Seems like Anbox driver wrappers could run directly on Windows (to get access to OpenGL), or at least inside WSL with graphics emulation layer.

Can you share, how we can run this?
