### ISSUE TITLE
mount: 'none'->'/proc/sys/fs/binfmt_misc': Operation not permitted

### ISSUE THREAD

**Issue by ipfgao** [anbox/anbox#490]
i try install houdini in anbox to suport arm apks.
but when i run enable_nativebridge, an error occurred. 
`mount: 'none'->'/proc/sys/fs/binfmt_misc': Operation not permitted`
i try to mount binfmt_misc manually with:
` mount -t binfmt_misc none /proc/sys/fs/binfmt_misc`
same error.

**Comment by ipfgao** [comment]
发现是anbox容器运行的安卓系统是使用uidmap伪装的root用户，没有权限。修改源码重新编译anbox后，能正常启动，houdini也能启动，不过微信还是无法运行。

**Comment by WqyJh** [comment]
How did you get root privilege and install houdini?

**Comment by Blackcorns** [comment]
How to install houdini?

**Comment by ipfgao** [comment]
@WqyJh @Blackcorns 
houdini的安装
Install houdini
1、下载 houdini.sfs文件
Download houdini.sfs
32bit：
[](http://dl.android-x86.org/houdini/7_x/houdini.sfs)
32bit lib for 64bit OS：
[](http://dl.android-x86.org/houdini/7_y/houdini.sfs)
64bit lib for 64bit OS：
[](http://dl.android-x86.org/houdini/7_z/houdini.sfs)

2、以64位系统为例，32位的（7_y/houdini.sfs）使用houdini.sfs的文件名，64位的（7_z/houdini.sfs）重命名为houdini64.sfs
Take 64 bit system as an example：Keep 7_y/houdini.sfs as houdini.sfs.Rename 7_z/houdini.sfs to houdini64.sfs.

houdini.sfs和houdini64.sfs都复制到/var/snap/anbox/common/data/arm下
Copy houdini.sfs and houdini64.sfs to /var/snap/anbox/common/data/arm

```
sudo mkdir /var/snap/anbox/common/data/arm
cp houdini.sfs houdini64.sfs /var/snap/anbox/common/data/arm
```

3、新建一个enable_nativebridge文件，内容如下：
make a new executable file named enable_nativebridge

```
#!/system/bin/sh

PATH=/system/bin:/system/xbin

houdini_bin=0
dest_dir=/system/lib$1/arm$1
binfmt_misc_dir=/proc/sys/fs/binfmt_misc

cd /data/arm
if [ -e /system/lib$1/libhoudini.so ]; then
log -pi -thoudini "found /system/lib$1/libhoudini.so"
elif [ -e /system/etc/houdini$1.sfs ]; then
busybox mount /system/etc/houdini$1.sfs $dest_dir
else
if mountpoint -q $dest_dir; then
# kill -9 `fuser -m $dest_dir`
umount -f $dest_dir
fi
busybox mount houdini$1.sfs $dest_dir
fi


# if you don't see the files 'register' and 'status' in /proc/sys/fs/binfmt_misc
# then run the following command:
# mount -t binfmt_misc none /proc/sys/fs/binfmt_misc

# this is to add the supported binary formats via binfmt_misc

if [ ! -e $binfmt_misc_dir/register ]; then
mount -t binfmt_misc none $binfmt_misc_dir
fi

cd $binfmt_misc_dir
if [ -e register ]; then
[ -e /system/bin/houdini$1 ] && dest_dir=/system/bin
# register Houdini for arm binaries
if [ -z "$1" ]; then
echo ':arm_exe:M::\\x7f\\x45\\x4c\\x46\\x01\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\x28::'"$dest_dir/houdini:P" > register
echo ':arm_dyn:M::\\x7f\\x45\\x4c\\x46\\x01\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x03\\x00\\x28::'"$dest_dir/houdini:P" > register
else
echo ':arm64_exe:M::\\x7f\\x45\\x4c\\x46\\x02\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\xb7::'"$dest_dir/houdini64:P" > register
echo ':arm64_dyn:M::\\x7f\\x45\\x4c\\x46\\x02\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x03\\x00\\xb7::'"$dest_dir/houdini64:P" > register
fi
if [ -e arm${1}_exe ]; then
houdini_bin=1
fi
else
log -pe -thoudini "No binfmt_misc support"
fi

if [ $houdini_bin -eq 0 ]; then
log -pe -thoudini "houdini$1 enabling failed!"
else
log -pi -thoudini "houdini$1 enabled"
fi

[ "$(getprop ro.zygote)" = "zygote64_32" -a -z "$1" ] && exec $0 64

exit 0
```

4、把enable_nativebridge也复制到/var/snap/anbox/common/data/arm下并赋予可执行权限
Copy  enable_nativebridge to /var/snap/anbox/common/data/arm

```
cp enable_nativebridge /var/snap/anbox/common/data/arm
cd /var/snap/anbox/common/data/arm
chmod +x enable_nativebridge
```

5、
```
$ adb shell
x86_64:/ $ su
x86_64:/ # cd /data/arm
x86_64:/ # sh enable_nativebridge
```

**Comment by ipfgao** [comment]
@WqyJh 真正的root权限要重新编译anbox实现，anbox的root只是伪装的root。

**Comment by Blackcorns** [comment]
你改的是哪个文件？ @ipfgao

**Comment by ipfgao** [comment]
anbox是使用uidmap伪装的root，实际上没有root权限，我重新编译了anbox的image文件，没再使用uidmap。不过这样不太安全。具体的我回办公室再发给你。发自我的华为手机-------- 原始邮件 --------主题：Re: [anbox/anbox] mount: 'none'->'/proc/sys/fs/binfmt_misc': Operation not permitted (#490)发件人：Blackcorns 收件人：anbox/anbox 抄送：ipfgao ,Mention 你改的是哪个文件？ @ipfgao

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/anbox/anbox","title":"anbox/anbox","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/anbox/anbox"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Blackcorns in #490: 你改的是哪个文件？ @ipfgao "}],"action":{"name":"View Issue","url":"https://github.com/anbox/anbox/issues/490#issuecomment-369918435"}}}

**Comment by ipfgao** [comment]
修改anbox/src/anbox/container/lxc_container.cpp 
注释掉 
```
if (!privileged_) 
  setup_id_maps(); 
```
重新编译即可。
重新打包android.img， 
解包： 
`$ unsquashfs android.img`
 利用acl工具备份文件权限，owner都减去100000，然后恢复 
重新打包 
`$ mksquashfs squashfs-root/ android.img -comp x`

**Comment by Blackcorns** [comment]
编译完之后要打包snap吗？@ipfgao

**Comment by Blackcorns** [comment]
[ 2018-04-23 10:00:14] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to configure LXC container
[ 2018-04-23 10:00:14] [session_manager.cpp:162@operator()] Lost connection to container manager, terminating.
[ 2018-04-23 10:00:14] [daemon.cpp:58@Run] Container is not running
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::log::v2_mt_posix::system_error> >'
  what():  Failed to set TLS value: Invalid argument
已放弃 (核心已转储)

**Comment by ipfgao** [comment]
@Blackcorns 打成snap包比较好

**Comment by Blackcorns** [comment]
@ipfgao 可不可以发一下你编译用的源代码，我这边即使啥都不改直接下下来解压都编译不通过

**Comment by kode54** [comment]
It should be possible to insert this stuff into the rootfs via rootfs-overlay. I still can't get it to load binfmt_misc, though.

**Comment by kode54** [comment]
I am posting again, to point out that binfmt_misc can't work anyway, because the mount command refuses to work, because there's no /etc/fstab.

**Comment by kastixx** [comment]
Could it be caused by AppArmor? I see an audit message appears in dmesg each time the mount command is run inside Anbox:

```
[38155.556954] audit: type=1326 audit(1551601616.206:143109): auid=4294967295 uid=100000 gid=100000 ses=4294967295 pid=20751 comm="mount" exe="/system/bin/toybox" sig=0 arch=c000003e syscall=165 compat=0 ip=0x7fd22669a0ca code=0x7ffc0000
```

**Comment by ipfgao** [comment]
> Could it be caused by AppArmor? I see an audit message appears in dmesg each time the mount command is run inside Anbox:
> 
> ```
> [38155.556954] audit: type=1326 audit(1551601616.206:143109): auid=4294967295 uid=100000 gid=100000 ses=4294967295 pid=20751 comm="mount" exe="/system/bin/toybox" sig=0 arch=c000003e syscall=165 compat=0 ip=0x7fd22669a0ca code=0x7ffc0000
> ```

They used uidmap ,giving  anbox a fake root environmen.But you need the real root permission  to run enable_nativebridge

**Comment by ipfgao** [comment]
> Could it be caused by AppArmor? I see an audit message appears in dmesg each time the mount command is run inside Anbox:
> 
> ```
> [38155.556954] audit: type=1326 audit(1551601616.206:143109): auid=4294967295 uid=100000 gid=100000 ses=4294967295 pid=20751 comm="mount" exe="/system/bin/toybox" sig=0 arch=c000003e syscall=165 compat=0 ip=0x7fd22669a0ca code=0x7ffc0000
> ```

I rebuild anbox and android.img with out uidmap.enable_nativebridge works,but unfortunately houdini not.

**Comment by kastixx** [comment]
@ipfgao by the way, have you ever had any success running apps with native ARM code on x86 android? I don't mean anbox only, *any* x86 android system.

I suppose this is not possible at all because one cannot mix binary modules built for different architectures in the same process. We need the Dalvik VM binary and all libraries it depends on to be built for ARM (the kernel and other system components may still be x86 though), otherwise it won't be able to load ARM dynamic .so libraries in its address space, even with Houdini.

**Comment by ipfgao** [comment]
@kastixx native arm apps work well with houdini on android x86 system.

**Comment by ipfgao** [comment]
> @ipfgao by the way, have you ever had any success running apps with native ARM code on x86 android? I don't mean anbox only, I mean _any_ x86 android system.
> 
> I suppose this is not possible at all because one cannot mix binary modules built for different architectures in the same process. We need the Dalvik VM binary and all libraries it depends on to be built for ARM (the kernel and other system components may still be x86 though), otherwise it won't be able to load ARM dynamic .so libraries in its address space, even with Houdini.

Houdini works on anbox now. you can try to set  ro.dalvik.vm.native.bridge=libhoudini.so in /default.prop
