### ISSUE TITLE
what happened to this project? why the forks and stars go away?

### ISSUE THREAD

**Issue by jackwish** [anbox/anbox#496]
I notice my fork `jackwish/anbox` displays as originating from `bpd1069/anbox` while it should be `anbox/anbox`. And, the stars and forks of this project looks very strange (see below). What happened? ownership transferred? Or it's a github bug?

![snip20171022_2](https://user-images.githubusercontent.com/4936589/31857673-1d992c14-b6aa-11e7-94cc-032d8a3fd638.png)

**Comment by jackwish** [comment]
@morphis

**Comment by morphis** [comment]
That was accidentally my fault. I am sorry for any inconveniences.

"黎明灰烬" <notifications@github.com> schrieb am 22.10.2017:
>I notice my fork `jackwish/anbox` displays as originating from
>`bpd1069/anbox` while it should be `anbox/anbox`. And, the stars and
>forks of this project looks very strange (see below). What happened?
>Someone cracked it?
>
>![snip20171022_2](https://user-images.githubusercontent.com/4936589/31857673-1d992c14-b6aa-11e7-94cc-032d8a3fd638.png)

-- Diese Nachricht wurde mit K-@ Mail gesendet.

**Comment by jackwish** [comment]
ok then...
