### ISSUE TITLE
Zorin OS 

### ISSUE THREAD

**Issue by infernoofihw** [anbox/anbox#498]
Contact: infernoofihw@gmail.com

** Please paste the result of `anbox system-info` below:**
```
anbox: command not found
```

**Please describe your problem:**
I was trying to install is on ZorinOS. I understand that its not officially supported but id like to know if there is a work around to force install it. 

**What were you expecting?:**
Installation 

**Additional info:**

**Comment by zerocoolll** [comment]
up, same problem ,up
