### ISSUE TITLE
not starting

### ISSUE THREAD

**Issue by kronosGR** [anbox/anbox#502]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```
version: 3
snap-revision: 64
os:
  name: Ubuntu
  version: 17.04 (Zesty Zapus)
  snap-based: true
kernel:
  version: Linux version 4.10.0-37-generic (buildd@lgw01-amd64-021) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) ) #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

**Please describe your problem:**
anbox do not start

**What were you expecting?:**

**Additional info:**

**Comment by mrpew** [comment]
run `anbox session-manager` to start the session-manager manually - this way youll also see the error that is preventing it to start. (Adding that to your issue may improve the chance to fix it)

**Comment by mrpew** [comment]
run `anbox session-manager` to start the session-manager manually - this way youll also see the error that is preventing it to start. (Adding that to your issue may improve the chance to fix it)

**Comment by michaelzhang917** [comment]
[ 2017-11-10 06:55:27] [Renderer.cpp:99@initialize] Failed to Initialize backend EGL display
Segmentation fault (core dumped)
