### ISSUE TITLE
No internet in Android / spurious veth devices created

### ISSUE THREAD

**Issue by msbentley** [anbox/anbox#51]
Make sure you are running the latest version of Anbox before reporting an issue.

**Anbox release (`anbox version`) and system info (`anbox system-info`):**

anbox 0.1.0

system info see: https://hastebin.com/qenaxoyoki

**Description of the problem:**

Android has no internet connectivity. 

**Expected:**

Android has internet connectivity

**Additional info:**

Container manager log: https://hastebin.com/wezodejune

When the container manager starts, the anboxbr0 network interface is created and when the session manager is started, a second (veth) interface is created:

```
anboxbr0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::fc3d:d9ff:fe66:6263  prefixlen 64  scopeid 0x20<link>
        ether fe:3d:d9:66:62:63  txqueuelen 1000  (Ethernet)
        RX packets 2951  bytes 151180 (151.1 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 248  bytes 33037 (33.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 193.171.196.86  netmask 255.255.255.0  broadcast 193.171.196.255
        inet6 fe80::baca:3aff:feb1:bb2e  prefixlen 64  scopeid 0x20<link>
        ether b8:ca:3a:b1:bb:2e  txqueuelen 1000  (Ethernet)
        RX packets 21452791  bytes 4442021276 (4.4 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 26591180  bytes 4441696371 (4.4 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xf7f00000-f7f20000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 462460  bytes 107192751 (107.1 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 462460  bytes 107192751 (107.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth0J4DCK: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::fc3d:d9ff:fe66:6263  prefixlen 64  scopeid 0x20<link>
        ether fe:3d:d9:66:62:63  txqueuelen 1000  (Ethernet)
        RX packets 2958  bytes 193008 (193.0 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 241  bytes 30394 (30.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```

Internet connection is fine on one machine, but doesn't work on the other. Both configurations are very similar.

**Comment by gcala** [comment]
I confirm the issue: no internet connection but also no new network interface (just the default ones)

version: master
os:
name: Archlinux
version: 
snap-based: false
kernel version: Linux tuxbox 4.10.9-1-ARCH #1 SMP PREEMPT Sat Apr 8 12:39:59 CEST 2017 x86_64 GNU/Linux
binder: true
ashmem: true

**Comment by namoo4u** [comment]
I also confirm this issue.
In Archlinux there are no network interface like anboxbr0 and vethxxxxx

**Comment by msbentley** [comment]
This sounds like a different bug, then - I would raise it separately. First check the container manager log to see if it started up OK - chances are it didn't, if no new interfaces are created. You can see the log with:

`sudo journalctl --no-pager -u snap.anbox.container-manager`

**Comment by msbentley** [comment]
(FWIW I also had the problem that container-manager was not starting correctly, and it was related to my dnsmasq configuration)

**Comment by guzzard** [comment]
Same as @gcala. Also on Arch Linux. No network/internet available in Anbox. No network interfaces created in the host.

**Comment by cra0zy** [comment]
> No network interfaces created in the host.

You need systemd-networkd started to get network interfaces created.

**Comment by mvaloor-altair** [comment]
@gcala @guzzard I had the same issue.  Apparently, it was a conflict with BIND.  The following fixed it:

sudo service bind9 stop
sudo systemctl restart snap.anbox.container-manager.service

**Comment by ThinkDigitalRepair** [comment]
I have internet connectivity with the webview app, but not any others. I tried to stop bind, but it said it wasn't running.

**Comment by mstuckless** [comment]
sudo service bind9 stop
sudo systemctl restart snap.anbox.container-manager.service

Worked for me after Linux Mint 18.1 upgrade to 18.2

**Comment by ThinkDigitalRepair** [comment]
Still having this issue. Now running Ubuntu 17.10 artful

**Comment by ELJOKER77** [comment]
i have this issue , i can't work with anbox please help

**Comment by ascendgermany** [comment]
Hi,
same here. No Internet Access.

username@host:~/Downloads$ adb shell ip a l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
20: eth0@if21: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 7e:24:6a:7a:a3:45 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.250.2/24 brd 192.168.250.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::7c24:6aff:fe7a:a345/64 scope link 
       valid_lft forever preferred_lft forever

user@host:~/Downloads$ adb shell
x86_64:/ $ ping 8.8.8.8
connect: Network is unreachable
2|x86_64:/ $

**Comment by B4rabbas** [comment]
Same problem for me, thanks in advance.
```
barabbas@PepperChuwi:~$ anbox system-info
version: 3
snap-revision: 70
os:
  name: Ubuntu
  version: 17.10 (Artful Aardvark)
  snap-based: true
kernel:
  version: Linux version 4.13.0-32-generic (buildd@lgw01-amd64-016) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)) #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018
  binder: true
```
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.2.4
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_polygon_offset_clamp
      - GL_KHR_no_error
barabbas@PepperChuwi:~$

**Comment by jounishida** [comment]
The same problem!
any solution about this?
