### ISSUE TITLE
INSTALL_FAILED_NO_MATCHING_ABIS Linux Mint

### ISSUE THREAD

**Issue by vincenzopalazzo** [anbox/anbox#511]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

During installation of the command line instagram apk, I gave the following error:
**_sudo adb install com.instagram.android_v12.0.0.7.91-69950867_Android-4.1.apk_ 
55706 KB/s (26708135 bytes in 0.468s)
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]**

also tried with previous versions and later.
With later version returns the following error:
**_adb install instagram.apk_ 53183 KB/s (18980407 bytes in 0.348s) Failure [INSTALL_FAILED_VERSION_DOWNGRADE]**

**Comment by ipfgao** [comment]
Just suport original x86 apk now.

**Comment by vincenzopalazzo** [comment]
Thanks

**Comment by hub2git** [comment]
> Just suport original x86 apk now.

This helps me too when itcomes to installing instagram. 
(The only reason I'm installing Instagram in Anbox is because Instagram on the Web doesn't have direct messaging, and I type much faster than I swipe)
