### ISSUE TITLE
anbox does not open in ubuntu 16.04 x64

### ISSUE THREAD

**Issue by hubbert0** [anbox/anbox#513]
Information hw sw : 
- http://pastebin.ubuntu.com/25925806/
- https://imgur.com/a/AeO3F
- http://pastebin.ubuntu.com/25926082/
- http://pastebin.ubuntu.com/25928186/
- http://pastebin.ubuntu.com/25929959/
______________________
Anbox does not run in Ubuntu 16.04.3 64-bit GNOME (run a background but it doesn't open the Anbox window).

When I start the app it's loading for 5-10 minutes, after that close window. System Monitor shows anbox is running, but hours later nothing happens after 1-2 hours.

I try install unity, but not solved , same problem. I try two different Ubuntu 16.04 64-bit GNOME PC, same problem.

**Comment by SaadeMotion** [comment]
Same here too

```
ubuntu@server1:~$ anbox session-manager
Segmentation fault (core dumped)
```

**Comment by ivanrojasorg** [comment]
Me Too, some idea how fix it?

**Comment by hubbert0** [comment]
unfortunately I did not find a solution, I gave up :/
