### ISSUE TITLE
Deezer music playback does not start

### ISSUE THREAD

**Issue by sobantu** [anbox/anbox#520]
Hi guys,

I hope everyone at the Anbox team is having a fantastic week thus far. Also, a big thank you for all of the hard work put into Anbox and for innovative revolutionary thinking. You are all legendary.

I had an issue with Deezer and all of the details are below:

[please paste printout of `anbox system-info` here]
> version: 3
> snap-revision: 61
> os:
>   name: Linux Mint
>   version: 18.1 (Serena)
>   snap-based: true
> kernel:
>   version: Linux version 4.4.0-53-generic (buildd@lcy01-28) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016
>   binder: true
>   ashmem: true
> graphics:
>   egl:
>     vendor: Mesa Project
>     version: 1.4 (DRI2)
>     extensions:
>       - EGL_CHROMIUM_sync_control
>       - EGL_EXT_create_context_robustness
>       - EGL_EXT_image_dma_buf_import
>       - EGL_KHR_config_attribs
>       - EGL_KHR_create_context
>       - EGL_KHR_fence_sync
>       - EGL_KHR_get_all_proc_addresses
>       - EGL_KHR_gl_renderbuffer_image
>       - EGL_KHR_gl_texture_2D_image
>       - EGL_KHR_gl_texture_3D_image
>       - EGL_KHR_gl_texture_cubemap_image
>       - EGL_KHR_image
>       - EGL_KHR_image_base
>       - EGL_KHR_image_pixmap
>       - EGL_KHR_no_config_context
>       - EGL_KHR_reusable_sync
>       - EGL_KHR_surfaceless_context
>       - EGL_KHR_wait_sync
>       - EGL_MESA_configless_context
>       - EGL_MESA_drm_image
>       - EGL_MESA_image_dma_buf_export
>       - EGL_NOK_swap_region
>       - EGL_NOK_texture_from_pixmap
>       - EGL_NV_post_sub_buffer
>       - EGL_WL_bind_wayland_display
>   gles2:
>     vendor: Intel Open Source Technology Center
>     vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
>     extensions:
>       - GL_EXT_blend_minmax
>       - GL_EXT_multi_draw_arrays
>       - GL_EXT_texture_filter_anisotropic
>       - GL_EXT_texture_lod_bias
>       - GL_OES_byte_coordinates
>       - GL_OES_fixed_point
>       - GL_OES_stencil_wrap
>       - GL_OES_compressed_paletted_texture
>       - GL_OES_query_matrix
>       - GL_OES_read_format
>       - GL_OES_single_precision
>       - GL_EXT_texture_compression_dxt1
>       - GL_OES_draw_texture
>       - GL_OES_point_size_array
>       - GL_OES_point_sprite
>       - GL_EXT_texture_format_BGRA8888
>       - GL_OES_compressed_ETC1_RGB8_texture
>       - GL_OES_depth24
>       - GL_OES_element_index_uint
>       - GL_OES_fbo_render_mipmap
>       - GL_OES_framebuffer_object
>       - GL_OES_mapbuffer
>       - GL_OES_rgb8_rgba8
>       - GL_OES_stencil8
>       - GL_OES_texture_env_crossbar
>       - GL_OES_texture_mirrored_repeat
>       - GL_OES_texture_npot
>       - GL_OES_EGL_image
>       - GL_OES_packed_depth_stencil
>       - GL_OES_texture_cube_map
>       - GL_APPLE_texture_max_level
>       - GL_EXT_discard_framebuffer
>       - GL_EXT_read_format_bgra
>       - GL_OES_blend_equation_separate
>       - GL_OES_blend_func_separate
>       - GL_OES_blend_subtract
>       - GL_OES_EGL_image_external
>       - GL_OES_EGL_sync
>       - GL_OES_vertex_array_object
>       - GL_ANGLE_texture_compression_dxt3
>       - GL_ANGLE_texture_compression_dxt5
>       - GL_EXT_map_buffer_range
>       - GL_KHR_debug
>       - GL_OES_surfaceless_context
>       - GL_EXT_polygon_offset_clamp

**Please describe your problem:**
![deezer issue](https://user-images.githubusercontent.com/26255902/32929057-7c91fb9e-cb66-11e7-94c7-bb28a852a0c6.png)

When trying to play a song, either online or downloaded offline, it shows a _Loading_ dialogue and does not disappear nor play the song.

**What were you expecting?:**
For a song to play and for sound to come out of the default output device.

**Additional info:**
* The APK for Deezer used was: _deezer.android.app-5.4.13.62.apk_.
* The profile used has a _Deezer Premium+_ subscription.
* In terms of network, it was possible to sign in, search for songs and seemingly download songs, so it may not precisely be a network issue by itself.
* I am not sure how Anbox handles audio codecs, but I have all of the _good, bad and ugly_ Gstreamer plugins installed on my system

Thanks again and have an awesome day!
Tsikitsiky lava (always smile)

**Comment by daxid** [comment]
Same here. When I run `adb shell logcat`, the following is repeatedly showing up : 
`12-31 14:12:21.775  2844  2844 W ResourceType: Invalid package identifier when getting bag for resource number 0x00004001
`
That's frustrating, it feels so damn close !

Best regards and happy new year !
