### ISSUE TITLE
Anbox don't work Ubuntu 16.04.3 x86_64

### ISSUE THREAD

**Issue by olevenets2** [anbox/anbox#524]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```
Segmentation fault
**Please describe your problem:**
Anbox does not start up Ubuntu 16.04.3 x86_64: there is a window with the inscription "starting", after nothing happens and after a while everything disappears. anbox system-info Segmentation fault. I use the proprietary nvidia driver, but it also does not work with nouveau-driver. Please, any tips how can I make it work?

**What were you expecting?:**

**Additional info:**

**Comment by Lin-Buo-Ren** [comment]
I have similar symptoms, also I noticed that the kernel messages are flooded with `binder_linux: <PID> RLIMIT_NICE not set`
