### ISSUE TITLE
 File "scripts/gen-emugl-entries.py", line 131 invalid syntax

### ISSUE THREAD

**Issue by Gooberpatrol66** [anbox/anbox#527]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**
build error

**What were you expecting?:**
build completion

**Additional info:**
Scanning dependencies of target GMock
[  0%] Creating directories for 'GMock'
[  1%] No download step for 'GMock'
[  2%] No patch step for 'GMock'
[  2%] No update step for 'GMock'
[  2%] Performing configure step for 'GMock'
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0/c++
-- Check for working CXX compiler: /usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0/gcc
-- Check for working C compiler: /usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /usr/bin/python (found version "3.4.5") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nathan/Downloads/anbox/anbox/build/gmock
[  2%] Performing build step for 'GMock'
Scanning dependencies of target gmock_main
[  9%] Building CXX object CMakeFiles/gmock_main.dir/gtest/src/gtest-all.cc.o
[ 18%] Building CXX object CMakeFiles/gmock_main.dir/src/gmock-all.cc.o
[ 27%] Building CXX object CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
[ 36%] Linking CXX static library libgmock_main.a
[ 36%] Built target gmock_main
Scanning dependencies of target gmock
[ 45%] Building CXX object CMakeFiles/gmock.dir/gtest/src/gtest-all.cc.o
[ 54%] Building CXX object CMakeFiles/gmock.dir/src/gmock-all.cc.o
[ 63%] Linking CXX static library libgmock.a
[ 63%] Built target gmock
Scanning dependencies of target gtest
[ 72%] Building CXX object gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 81%] Linking CXX static library libgtest.a
[ 81%] Built target gtest
Scanning dependencies of target gtest_main
[ 90%] Building CXX object gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[100%] Linking CXX static library libgtest_main.a
[100%] Built target gtest_main
[  2%] No install step for 'GMock'
[  3%] Completed 'GMock'
[  3%] Built target GMock
Scanning dependencies of target process-cpp
[  4%] Building CXX object external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/posix/backtrace.cpp.o
[  4%] Building CXX object external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/posix/child_process.cpp.o
[  4%] Building CXX object external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/posix/exec.cpp.o
[  5%] Building CXX object external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/posix/fork.cpp.o
[  5%] Building CXX object external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/posix/process.cpp.o
[  5%] Building CXX object external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/posix/process_group.cpp.o
[  6%] Building CXX object external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/posix/signal.cpp.o
[  6%] Building CXX object external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/posix/signalable.cpp.o
[  7%] Building CXX object external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/posix/standard_stream.cpp.o
[  7%] Building CXX object external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/posix/wait.cpp.o
[  7%] Building CXX object external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/posix/this_process.cpp.o
[  8%] Building CXX object external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/posix/linux/proc/process/oom_adj.cpp.o
[  8%] Building CXX object external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/posix/linux/proc/process/oom_score.cpp.o
[  8%] Building CXX object external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/posix/linux/proc/process/oom_score_adj.cpp.o
[  9%] Building CXX object external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/posix/linux/proc/process/stat.cpp.o
[  9%] Building CXX object external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/testing/cross_process_sync.cpp.o
[  9%] Building CXX object external/process-cpp-minimal/src/CMakeFiles/process-cpp.dir/core/testing/fork_and_run.cpp.o
[ 10%] Linking CXX static library libprocess-cpp.a
[ 10%] Built target process-cpp
Scanning dependencies of target emugen
[ 11%] Building CXX object external/android-emugl/host/tools/emugen/CMakeFiles/emugen.dir/ApiGen.cpp.o
/home/nathan/Downloads/anbox/anbox/external/android-emugl/host/tools/emugen/ApiGen.cpp: In member function ‘int ApiGen::genDecoderImpl(const string&)’:
/home/nathan/Downloads/anbox/anbox/external/android-emugl/host/tools/emugen/ApiGen.cpp:1119:25: warning: too many arguments for format [-Wformat-extra-args]
                         );
                         ^
[ 11%] Building CXX object external/android-emugl/host/tools/emugen/CMakeFiles/emugen.dir/EntryPoint.cpp.o
/home/nathan/Downloads/anbox/anbox/external/android-emugl/host/tools/emugen/EntryPoint.cpp: In member function ‘bool EntryPoint::parse(unsigned int, const string&)’:
/home/nathan/Downloads/anbox/anbox/external/android-emugl/host/tools/emugen/EntryPoint.cpp:105:34: warning: too many arguments for format [-Wformat-extra-args]
                     error.c_str());
                                  ^
[ 12%] Building CXX object external/android-emugl/host/tools/emugen/CMakeFiles/emugen.dir/main.cpp.o
[ 12%] Building CXX object external/android-emugl/host/tools/emugen/CMakeFiles/emugen.dir/Parser.cpp.o
[ 12%] Building CXX object external/android-emugl/host/tools/emugen/CMakeFiles/emugen.dir/strUtils.cpp.o
[ 13%] Building CXX object external/android-emugl/host/tools/emugen/CMakeFiles/emugen.dir/TypeFactory.cpp.o
[ 13%] Linking CXX executable emugen
[ 13%] Built target emugen
Scanning dependencies of target OpenglCodecCommon
[ 13%] Building CXX object external/android-emugl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon.dir/ChecksumCalculator.cpp.o
[ 13%] Building CXX object external/android-emugl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon.dir/ChecksumCalculatorThreadInfo.cpp.o
[ 15%] Building CXX object external/android-emugl/shared/OpenglCodecCommon/CMakeFiles/OpenglCodecCommon.dir/glUtils.cpp.o
[ 15%] Linking CXX static library libOpenglCodecCommon.a
[ 15%] Built target OpenglCodecCommon
Scanning dependencies of target GLHeaders
Generating /home/nathan/Downloads/anbox/anbox/build/external/android-emugl/host/include/OpenGLESDispatch/RenderEGL_functions.h
  File "scripts/gen-emugl-entries.py", line 131
    print "// Auto-generated with: %s" % banner_command(sys.argv)
                                     ^
SyntaxError: invalid syntax
make[2]: *** [external/android-emugl/host/libs/CMakeFiles/GLHeaders.dir/build.make:57: GLHeaders] Error 1
make[1]: *** [CMakeFiles/Makefile2:1276: external/android-emugl/host/libs/CMakeFiles/GLHeaders.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by fpemud** [comment]
It is because you are using python3. "scripts/gen-emugl-entries.py" is a python2 script.
#512 fixes this problem.

**Comment by Thaodan** [comment]
Is there a reason for still using python3?
