### ISSUE TITLE
Not able to run anbox in my ubuntu

### ISSUE THREAD

**Issue by arpithpathange** [anbox/anbox#53]
Make sure you are running the latest version of Anbox before reporting an issue.

**Anbox release (`anbox version`) and system info (`anbox system-info`):**

**Description of the problem:**
Ubuntu version:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety

error:
anbox launch 
[EE 2017-04-12 16:10:30] [launch.cpp:105@operator()] Failed to launch activity: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Expected:**
Expecting the application to run.

**Additional info:**

**Comment by Ayshasiddiqua** [comment]
Same problem bro

**Comment by JobayerAhmedMickey** [comment]
Same Problem bro

**Comment by acetheultimate** [comment]
you might want to see [issue#4](https://github.com/anbox/anbox/issues/4#issuecomment-293790456)
