### ISSUE TITLE
anbox dont start linux mint 18.3 

### ISSUE THREAD

**Issue by eltijubolive** [anbox/anbox#534]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by Justin00015** [comment]
I'm experiencing the same thing on Ubuntu 17.10
