### ISSUE TITLE
Adapt deepin operating system?

### ISSUE THREAD

**Issue by michaeldyl520** [anbox/anbox#539]
Adapt deepin operating system?Thank you very much.

**Comment by ipfgao** [comment]
安装snapd / Install snapd
sudo apt install snapd

下载anbox-common_9_all.deb、anbox-modules-dkms_9_all.deb
Download anbox-common_9_all.deb & anbox-modules-dkms_9_all.deb
wget http://ppa.launchpad.net/morphis/anbox-support/ubuntu/pool/main/a/anbox/anbox-common_9_all.deb
wget http://ppa.launchpad.net/morphis/anbox-support/ubuntu/pool/main/a/anbox/anbox-modules-dkms_9_all.deb

安装这两个deb包
Install these two deb package
dpkg -i anbox-common_9_all.deb
dpkg -i anbox-modules-dkms_9_all.deb

安装anbox
Install anbox
sudo snap install --edge --devmode anbox

重启 / Reboot

完成安装，可以用了。
All done!

**Comment by michaeldyl520** [comment]
Can`t use arm app?Where may I find x86 apps?

**Comment by ipfgao** [comment]
if you are using arm cpu ,you can run arm apps. X86 cpus,no.

**Comment by timofonic** [comment]
@ipfgao That's not entirely true. I remember there are ARM emulations for Android X86. Even the Genymotion software has it, for example

**Comment by ipfgao** [comment]
@timofonic yes,it's called houdini. i try install houdini in anbox to suport arm apks.but failed.
