### ISSUE TITLE
anbox-installer does not remove dkms-module on uninstall

### ISSUE THREAD

**Issue by Scrumplex** [anbox/anbox#547]
This issue is based on [this askubuntu question](https://askubuntu.com/questions/919083/dkms-does-not-automatically-rebuild-after-kernel-upgrade).

After running `sudo anbox-installer` and selecting to uninstall, it breaks the dkms system on ubuntu. The uninstaller _forgets_ to remove the anbox modules from `/var/lib/dkms`.

**Comment by mvvvv** [comment]
This is a real problem, because it breaks "sudo dkms status" and for each new kernel I had to re-install nvidia-* driver.

You have to remove manually the two anbox-modules-* directories from /var/lib/dkms and check that "sudo dkms status" works

**Comment by ValkiryXDA** [comment]
If you look at https://github.com/anbox/anbox-installer/blob/master/installer.sh (lines 77 to 92)
you will see the uninstall section doesn't follow any proper uninstall of dkms modules, id suggest:
$ dkms remove ashmem* --all
$ dkms remove binder* --all
(ive manually installed the modules so it might be different for pre-packaged installs)
to combat any issues or just disable the modules with:
$ sudo modprobe -r ashmem*
$ sudo modprobe -r binder*

kind of pick you poison scenario

**Comment by thenewnano** [comment]
the star didn't work for me . 
`ls /usr/src/
anbox-modules-ashmem-9
anbox-modules-binder-9
`
then the code to remove them was 
`dkms remove anbox-modules-ashmem/9 --all
dkms remove anbox-modules-binder/9 --all
`
after that I removed the source for both modules from /usr/src 
`rm -r anbox-modules-ashmem-9/
rm -r anbox-modules-binder-9/
`

**Comment by peeter-t2** [comment]
Hi, I have the same problem. anbox-modules-dkms does not uninstall, and is causing 'system problem' on startup. Any help uninstalling? System problem and how I tried to uninstall below. I tried everything in this thread. Thanks!

![image](https://user-images.githubusercontent.com/4077432/74220947-96bf4680-4cb9-11ea-9786-536234da6e15.png)


`dpkg -l | grep anbox
rc  anbox-modules-dkms                                          13                                              all          Android kernel driver (binder, ashmem) in DKMS format.

sudo dkms remove anbox-modules-dkms/13 --all 
Error! There are no instances of module: anbox-modules-dkms`

**Comment by Bfaschat** [comment]
> the star didn't work for me .
> `ls /usr/src/ `
> `anbox-modules-ashmem-9 `
> `anbox-modules-binder-9 `
> 
> then the code to remove them was
> 
> `dkms remove anbox-modules-ashmem/9 --all `
> `dkms remove anbox-modules-binder/9 --all `
> 
> after that I removed the source for both modules from /usr/src
> `rm -r anbox-modules-ashmem-9/ `
> `rm -r anbox-modules-binder-9/ `

You did well by mentioning the steps. To further help out, did as follows

```
$ sudo apt install ppa-purge
$ sudo apt autoremove --purge
```
Then I now proceeded to run the following 

`$ ls /usr/src/ `

Which displayed
 ```
anbox-1       
anbox-ashmem-1
anbox-binder-1 
```
then the code to remove them was

```
$ sudo dkms remove anbox/1 --all
$ sudo dkms remove anbox-ashmem/1 --all
$ sudo dkms remove anbox-binder/1 --all 

```
after that I removed the source for both modules from **/usr/src**

`$ cd /usr/src`

Now to avoid **Permission denied** error when trying to remove the modules, we will run the command as root

```
$ sudo rm -r -f anbox-1/
$ sudo rm -r -f anbox-ashmem-1/
$ sudo rm -r -f anbox-binder-1/
```
That is the only way to make it work.

> Do remember that: Make sure to replace the numbers with yours. Have a nice day. 

#Bfaschat, #Bfas237Blog

**Comment by UOElite** [comment]
> > the star didn't work for me .
> > `ls /usr/src/ `
> > `anbox-modules-ashmem-9 `
> > `anbox-modules-binder-9 `
> > then the code to remove them was
> > `dkms remove anbox-modules-ashmem/9 --all `
> > `dkms remove anbox-modules-binder/9 --all `
> > after that I removed the source for both modules from /usr/src
> > `rm -r anbox-modules-ashmem-9/ `
> > `rm -r anbox-modules-binder-9/ `
> 
> You did well by mentioning the steps. To further help out, I did as follows
> 
> ```
> $ sudo apt install ppa-purge
> $ sudo apt autoremove --purge
> ```
> 
> Then I now proceeded to run the following
> 
> `$ ls /usr/src/ `
> 
> Which displayed
> 
> ```
> anbox-1       
> anbox-ashmem-1
> anbox-binder-1 
> ```
> 
> then the code to remove them was
> 
> ```
> $ sudo dkms remove anbox/1 --all
> $ sudo dkms remove anbox-ashmem/1 --all
> $ sudo dkms remove anbox-binder/1 --all 
> ```
> 
> after that I removed the source for both modules from **/usr/src**
> 
> `$ cd /usr/src`
> 
> Now to avoid **Permission denied** error when trying to remove the modules, we will run the command as root
> 
> ```
> $ sudo rm -r -f anbox-1/
> $ sudo rm -r -f anbox-ashmem-1/
> $ sudo rm -r -f anbox-binder-1/
> ```
> 
> That is the only way to make it work.
> 
> > Do remember that: Make sure to replace the numbers with yours. Have a nice day.
> 
> #Bfaschat, #Bfas237Blog

This resolved the issue for me. Thank you for posting this.

Any time I tried to update my drivers I received the following error message:
`dpkg: error processing package anbox-modules-dkms (--configure):
 installed anbox-modules-dkms package post-installation script subprocess return
ed error exit status 10
Errors were encountered while processing:
 anbox-modules-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)`

After following your steps I was able to successfully remove anbox, adb, and update my drivers successfully.

Thanks again!
