### ISSUE TITLE
Hangs on starting Ubuntu 16.04

### ISSUE THREAD

**Issue by happysmack** [anbox/anbox#563]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
anbox system-info
Segmentation fault (core dumped)
```

**Please describe your problem:**

Hangs on "starting....".   I went to bed and awoke to the same.

**What were you expecting?:**

**Additional info:**
[lshwOutput.txt](https://github.com/anbox/anbox/files/1589716/lshwOutput.txt)

**Comment by lddd** [comment]
Same here.

**Comment by Jedarc** [comment]
Same here.
