### ISSUE TITLE
Please add support to Ubuntu 18.04 LTS (Bionic Beaver)

### ISSUE THREAD

**Issue by wellington1993** [anbox/anbox#565]
**Please describe your problem:**
Please add repository to Ubuntu 18.04 LTS (Bionic Beaver)

See the problem:
```
Err:20 http://ppa.launchpad.net/morphis/anbox-support/ubuntu bionic Release
  404  Not Found
Err:21 http://ppa.launchpad.net/qemu/ppa/ubuntu bionic Release
  404  Not Found
```
**What were you expecting?:**
Ways to test this project and install from repository.

**Additional info:**
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu Bionic Beaver (development branch)"
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu Bionic Beaver (development branch)"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by BlueKenny** [comment]
Change your distro to zesty in this ppa and it works, i'm on bionic too

**Comment by anibyl** [comment]
I switched this PPA to `zesty` but `anbox-installer` just adds new entry to PPA list.

**Comment by tristan-k** [comment]
Same for me. I cant change the destro because anbox-installer removes `/etc/apt/sources.list.d/morphis-ubuntu-anbox-support-xenial.list` because of the misssing support for bionic.

**Comment by BlueKenny** [comment]
Good question im on Fedora Now, it know that it change it every time but with the installer script, it was posible to change it manualy but i Dosen t remember how... I think i run the script  it failed the i change the repo.. And install it without anbox -installer ? Or try to change it on the fly

**Comment by Safeuq** [comment]
Same issue. Hope it is resolved

**Comment by Sphinxs** [comment]
Same here

**Comment by anysz** [comment]
Same here..

**Comment by pmrelvas** [comment]
same here, I'd really like be able to run anbox on the newer ubuntu version, thank you :)

**Comment by anysz** [comment]
Hmm, yea "changing" distro name and some repo might temporary solve this issue...
I use Ubuntu 18.04 Beta 2 Bionic Beaven btw..
[[http://api.ntcorp.us/storage/get/src_0|alt=bbshow]]

**Comment by sirredbeard** [comment]
I would appreciate support too. Thank you.

**Comment by UtkarshVerma** [comment]
It would be great if there was a ppa for `bionic beaver` as well.

**Comment by gaba41** [comment]
+1

**Comment by maszynka** [comment]
+1

**Comment by UtkarshVerma** [comment]
+1

**Comment by Spyderon** [comment]
+1

**Comment by vuanhlevis** [comment]
how can i fix it ??
same err

**Comment by lechum2** [comment]
+1

**Comment by stuaxo** [comment]
This distro is properly released now, so any chance of the ppa adding bionic ?

**Comment by tsis2k** [comment]
hello
exist a solutión? or nothings

regards

**Comment by Windstep** [comment]
Hello, +1 for adding 18.04 release.

**Comment by morphis** [comment]
It's not just the PPA which needs changes. Stay tuned fixes are being worked on.

**Comment by diegofernandesp** [comment]
+1

**Comment by tsis2k** [comment]
ok the Edge , Play the blues!

**Comment by maulanasatyaadi** [comment]
+1

**Comment by foneazmi** [comment]
+1

**Comment by stnight** [comment]
+1

**Comment by slimelia** [comment]
+1

**Comment by cra0zy** [comment]
/2+3-1+335=

**Comment by stuaxo** [comment]
Further work needs doing than just updating the PPA.

There are other ways to help the project in the meantime, such as triaging bugs.

**Comment by astronom35** [comment]
+1

**Comment by c4syner** [comment]
+1

**Comment by al3Co** [comment]
+1

**Comment by h4xw4r** [comment]
please support 18.04 soon :+1:

**Comment by marlid91** [comment]
+1

**Comment by morphis** [comment]
The PPA is now updated with new DKMS packages for xenial and bionic (see https://launchpad.net/~morphis/+archive/ubuntu/anbox-support). Additional mandatory snap changes are coming soon.

**Comment by mgliewe** [comment]
> The PPA is now updated with new DKMS packages for xenial and bionic (see https://launchpad.net/~morphis/+archive/ubuntu/anbox-support). Additional mandatory snap changes are coming soon.

nice!

alas, anbox-common is missing for bionic..

```
E: Unable to locate package anbox-common
+ cleanup
+ local err=100
+ trap - EXIT
+ echo 'ERROR: Installation failed. Removing all parts of Anbox again.'
```

**Comment by morphis** [comment]
@mgliewe It's not, the installer is outdated and will be dropped soon. As said, there are further changes mandatory before everything works. I will give an update here once everything is ready.

**Comment by mgliewe** [comment]
THX!

**Comment by stuaxo** [comment]
Awesome :) I guess   anbox-modules-dkms    for bionic is going up soon ?

**Comment by brulaz** [comment]
Just installed anbox-modules-dkms in Bio Beav today.
Waiting for anbox-common.

**Comment by morphis** [comment]
> Waiting for anbox-common.

The `anbox-common` package is gone but the installer awaits changes to not try to install it anymore.

**Comment by morphis** [comment]
If anyone is keen to try the latest Anbox snap (supports 18.04), it's now available in the beta channel.

The anbox-installer is now deprecated! Updated installation instructions are available at https://github.com/anbox/anbox/blob/master/docs/install.md

**Comment by morphis** [comment]
@mgliewe Glad to hear that :-)

**Comment by cra0zy** [comment]
The resize edges for the new CSD look are way too big, I feel like they are around 20 pixels in size (talking about the area you can grab to start the resize).

Otherwise works awesome.

**Comment by morphis** [comment]
@cra0zy Can you file a separate bug for that?

**Comment by morphis** [comment]
I am closing this bug now as the main enablement for 18.04 is done. If any further problems are found please open separate bugs.

**Comment by stuaxo** [comment]
Thanks for all the work :)

**Comment by zanedb** [comment]
silly question: how do you install apks?

**Comment by cra0zy** [comment]
Alternatively follow instructions at https://github.com/anbox/anbox/issues/118 to get play store working:

![anbox](https://user-images.githubusercontent.com/6773302/40549659-6033176e-6038-11e8-8ede-9b47ac9862ca.png)
