### ISSUE TITLE
anbox doesn't start, could not connect to session-manager,

### ISSUE THREAD

**Issue by 250burgman** [anbox/anbox#569]
** Please paste the result of `anbox system-info` below:**
# anbox system-info 
version: local-7266fe2
os:
  name: Arch Linux
  version: 
  snap-based: false
kernel:
  version: Linux version 4.14.9-1-ARCH (builduser@heftig-13854) (gcc version 7.2.1 20171128 (GCC)) #1 SMP PREEMPT Tue Dec 26 00:18:37 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.3.1
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_required_internalformat
      - GL_OES_surfaceless_context
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_polygon_offset_clamp
      - GL_KHR_no_error

Linux 4.14.9-1-ARCH #1 SMP PREEMPT Tue Dec 26 00:18:37 UTC 2017 x86_64 GNU/Linux

# ifconfig
anbox0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.250.1  netmask 255.255.255.0  broadcast 192.168.250.255

# lsmod
ashmem_linux           16384  0
binder_linux          114688  0

# ps -ef | grep anb
root       472     1  0 10:44 ?        00:00:00 /usr/bin/anbox container-manager --daemon --privileged --data-path=/var/lib/anbox
nobody     604   480  0 10:44 ?        00:00:00 /usr/bin/dnsmasq --conf-file --no-hosts --keep-in-foreground --bind-interfaces --except-interface=lo --clear-on-reload --strict-order --listen-address=192.168.250.1 --dhcp-range=192.168.250.10,192.168.250.254,60m --dhcp-lease-max=50 --pid-file=/run/nm-dnsmasq-anbox0.pid --conf-dir=/etc/NetworkManager/dnsmasq-shared.d

**Please describe your problem:**
$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[ 2017-12-31 09:53:48] [launch.cpp:134@operator()] Anbox session manager service isn't running, trying to start it.
[ 2017-12-31 09:57:54] [launch.cpp:234@operator()] Stopped waiting as we've already waited for too long. Something
[ 2017-12-31 09:57:54] [launch.cpp:235@operator()] is wrong with your setup or the container has failed to boot.
[ 2017-12-31 09:57:54] [launch.cpp:236@operator()] If you think you found a bug please don't hesitate to file on
[ 2017-12-31 09:57:54] [launch.cpp:237@operator()] at https://github.com/anbox/anbox/issues/new
dbus[1574]: Attempted to unregister path (path[0] = null path[1] = null) which isn't registered

# grep ERR container.log 
            lxc 20171226100612.147 ERROR    lxc_network - network.c:lxc_setup_network_in_child_namespaces:2987 - WARNING: using "lxc.network.*" keys to define networks is DEPRECATED, please switch to using "lxc.net.[i].* keys"

but ps shows container running: andreas   1577     1  0 10:53 ?        00:00:00 /usr/bin/anbox session-manager

why could not connect to session-manager?  the only Error i found is lxc.network. What could i do ?

**Comment by limited1010** [comment]
why  debian not't running
