### ISSUE TITLE
anbox-installer not found after snap install on GalliumOS

### ISSUE THREAD

**Issue by insomnea** [anbox/anbox#572]
**Please describe your problem:**

The snap 'anbox-installer' installs seamlessly, but then i can't run it.

$ snap install anbox-installer && anbox-installer
snap "anbox-installer" is already installed, see "snap refresh --help"
bash: anbox-installer: command not found

**What were you expecting?:**

For the Installer to start.

**Additional info:**

Running a freshly installed Xubuntu variant (GalliumOS)

**Comment by maoyibo** [comment]
The Real Path of anbox-installer is /snap/bin/anbox-installer .
Run it with real path and do not use root.
