### ISSUE TITLE
error: snap "anbox-installer" not found

### ISSUE THREAD

**Issue by bmartinezga** [anbox/anbox#575]
I've just installed snap
these are my versions

snap    2.30
snapd   2.30
series  16
ubuntu  16.04
kernel  4.4.0-104-generic

I've installed "hello-world 6.3" and it 's listed

but I get an error when trying to get the anbox-installer

Please help, I want to try Android apps on my linux

**Comment by UntouchedWagons** [comment]
>sudo snap install --edge --classic anbox-installer

Worked for me, then I found out anbox doesn't support ARM.

**Comment by ArisNeander** [comment]
If you just installed snap, you need to open a new bash (or logout and login again) to have the proper path settings.

**Comment by alexhagen** [comment]
Happens for me to, even after using '--edge' option, and even after restarting my computer.

**Comment by UntouchedWagons** [comment]
@ArisNeander If Snap is unable to find anbox-installer in its repository then it not being in $PATH isn't the problem. Additionally if snap isn't automatically in one of the directories listed in $PATH then that should be adjusted.

@alexhagen What OS did you use? I used Lubuntu 16.04

**Comment by alexhagen** [comment]
@UntouchedWagons I'm on Ubuntu 16.04.3 LTS on a rig with an old Xeon (E5504).  I was able to install with the installer script, but then ran into problems when running anbox - so I'm going to forgo using it until it's a little more mature.  Let me know if you want to see any logs from the snap install.

**Comment by UntouchedWagons** [comment]
Oh I'm not a dev or anything I'm just a random guy who tried to use Anbox to run Android apps on my Raspberry Pi 3.

**Comment by bmartinezga** [comment]
sorry, nothing worked.
Maybe the thing is I'm under 32 bit system?

**Comment by fcex** [comment]
Actually, I got the same problem. I am using Linux Mint 18.3 and when I try to start anbox or anbox-installer, I just simply can't

**Comment by Kogam22** [comment]
@bmartinezga 
So, 32 Has Problems Then ?
