### ISSUE TITLE
Anbox Ignores Mouse Input

### ISSUE THREAD

**Issue by thebombzen** [anbox/anbox#582]
**Please paste the result of `anbox system-info` below:**
[https://0x0.st/sZye.txt](https://0x0.st/sZye.txt)

**Please describe your problem:**
Anbox ignores all mouse input in any android application and also in the session manager.

**What were you expecting?:**
I was expected Anbox to respond to the mouse in the calculator, settings, or session manager.

**Additional info:**
Anbox is the version from Git Master, with this patch added so it'll run on 4.14: https://github.com/sarangnemo/anbox/commit/f633d641c21f45e46aa9585fc38389da033c0212

**Comment by angsar** [comment]
I'm actually having the same issue. Mouse input not working, attached is my system info.
[anbox-system-info.txt](https://github.com/anbox/anbox/files/1669727/anbox-system-info.txt)

**Comment by Yamimono** [comment]
Actually you need to resize the window to see its changes. The app content isn't updated in the window until you resize it.

**Comment by thebombzen** [comment]
Resizing the window does not help. Anbox still ignores mouse input.

**Comment by thebombzen** [comment]
I did a test and it's not a repainting issue. For example if you load the "clock" app then it'll update the time displayed when it repaints if you wait a minute, but nothing happens when you use the mouse at all, even if you force a repaint.

**Comment by NiceneNerd** [comment]
I'm having the same issue. System info:
`version: 3
snap-revision: 72
os:
  name: Ubuntu
  version: 17.10 (Artful Aardvark)
  snap-based: true
kernel:
  version: Linux version 4.13.0-37-generic (buildd@lcy01-amd64-026) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3.2)) #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.2.8
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_polygon_offset_clamp
      - GL_KHR_no_error`

**Comment by burtonator** [comment]
same issue.. double click to launch an app won't ork.

**Comment by thebombzen** [comment]
This is not fixed as of Git Master. Please reopen it. The window repaints when you resize it, thanks to the fix, but it still doesn't respond to mouse input.

**Comment by plygrnd** [comment]
Seeing the same issue; I've uploaded [anbox-system-diagnostics-2018-07-22.zip](https://github.com/anbox/anbox/files/2216981/anbox-system-diagnostics-2018-07-22.zip) with more information.

**Comment by ncdduy** [comment]
[https://pastebin.com/raw/tNvvgCrW](anbox-system-info)
Anbox ignored all mouse input in com.igg.android.lordsmobile, can't do click on any button.
It should be clickable on all button and object in that app.

**Comment by Afsalmc** [comment]
**For Non Snap users :_)**
Apparently the issue is still present in latest version . You can start session manager with `--no-touch-emulation` to avoid the issue .
After starting container-manager service run `anbox session-manager --no-touch-emulation&` and wait some time to fully load the system . Then launch Anbox from menu icon shortcut .
