### ISSUE TITLE
"Getting Started Page" instructions are incorrect. 

### ISSUE THREAD

**Issue by nicciniamh** [anbox/anbox#588]
The Getting Started section on https://anbox.io states: 

> When you're ready to install Anbox on your system everything you need is the following command line. The installer will tell you about everything it is doing and will prompt for any further necessary input from your side:
$ snap install --classic anbox-installer && anbox-installer

But this does the snap installation for anbox-installer however the second part of the pipeline "anbox-installer" fails because the command is not on the path. 

To correcf this I used 
`snap install --classic anbox-installer && snap run anbox-installer`

While this is not a bug in the software this mis-print, at least when using this under Linux Mint 18.3 produces a failed result.

**Comment by SashaGelert** [comment]
Gonna bump this as I just installed in Linux Mint 18.2 today to test. Install failed to run several times until I came across this post.
