### ISSUE TITLE
Can Anbox license type change to MIT instead of GPL?

### ISSUE THREAD

**Issue by Raj2032** [anbox/anbox#607]
Reason why I suggest is cause so that the end user can have even more ownership of the software after he downloads it.

**Comment by dannycolin** [comment]
> Reason why I suggest is cause so that the end user can have even more ownership of the software after he downloads it.

Actually, the GPL ensure a better protect from a user point-of-view.

**Comment by Raj2032** [comment]
How does GPL exactly protect users?

**Comment by dannycolin** [comment]
@Raj2032 https://en.wikipedia.org/wiki/GNU_General_Public_License#Copyleft

**Comment by Raj2032** [comment]
But GPL does ruin Freeness (as in freedom, not beer). MIT pretty much gives
Freedom to do whatever the person wants to.

**Comment by dannycolin** [comment]
> @Raj2032 But GPL does ruin Freeness (as in freedom, not beer). MIT pretty much gives Freedom to do whatever the person wants to.

So in your logic, giving  the freedom to use free software (under MIT-like license) without giving back your modifications would create more freedom?

**Comment by Raj2032** [comment]
Well if there are less restrictions which allow users to do what they want
to do with the copy, then yes off course this increases freedom. By placing
restrictions by legally forcing users to report any modifications that they
do back to the repository, that reduces the freedom, therefore this
software can't be classified as truly free software (take a look at this
article)

https://vaporsoft.net/gpl-sucks/

**Comment by dannycolin** [comment]
@Raj2032 Well if there are less restrictions which allow users to do what they want to do with the copy, then yes off course this increases freedom. By placing restrictions by legally forcing users to report any modifications that they do back to the repository

First, you don't need to report anything to the repository where you take it. You only need to put your modificationd under the same license to ensure the same liberty to your users (if you and only if you distribute your software). Second, if you don't you definitely limit the freedom of other users that will use your half-free software.

Free Software isn't about the freedom of your own little person. It's about the freedom of the society. What you describe is Open Source. 

NB.: I know that article and frankly that's pure bullshit. That person argue that GPL don't let you create proprietary software with GPL code and that because of that GPL isn't free software. Sincerely, what the heck is that argument. I mean, of course, you can use free software code to make proprietary software that would be a non sense since the final product would not be free...

**Comment by Raj2032** [comment]
My apologies for the lack of knowledge. I thought you had to report back to
the repository.

I am surprised you even read that article before I have brought it up to
you. When did you read it may I ask?

I thought Free software meant that individual users that get a hold of the
software could do anything they wanted to, including making it proprietary
and redistribute it if they pleased.

In your opinion, don't you think users should have the rights to do
whatever they want to do to it, which includes making their own distro and
making it closed source if they wanted to?

**Comment by dannycolin** [comment]
> My apologies for the lack of knowledge. I thought you had to report back to the repository.

No problem. It isn't an easy topic and there's a lot of information. Even me I'm not an expert on license.

> I am surprised you even read that article before I have brought it up to you. When did you read it may I ask?

I don't remember when exactly but IIRC someone posted it on a reddit thread.

> In your opinion, don't you think users should have the rights to do whatever they want to do to it, which includes making their own distro and making it closed source if they wanted to?

IMHO, I think a user can do whatever s/he please as long as s/he doesn't break the chain of freedom. For me, it's a give and take game. If you do not give back, you enjoy the work of other contributors for free (and it really sounds like free as in free beer to me). So the user liberties should be greater than the users (the collective) liberties.

I think it's really a matter of how you see the concept of freedom in the first place. As you can see, there's two school of thought 1) User freedom should always be greater than the collective. 2) User freedom should never be greater than the collective. The first one is influenced by the [liberal](https://en.wikipedia.org/wiki/Liberalism) philosophy and it is predominant in the USA. The second is influenced by the [socialist](https://en.wikipedia.org/wiki/Socialism) point of view.

**Comment by Raj2032** [comment]
Thanks man :)

In my opinion I would say true freedom is where the user can do whatever
he/she may want and redistribute it however they please to, whether it'd be
open source, closed source etc. But that's just me.

So are you the head of this project?

**Comment by dannycolin** [comment]
> So are you the head of this project?

Nope. I'm just a user of Anbox.

**Comment by Raj2032** [comment]
Is it in Beta?

**Comment by dannycolin** [comment]
From the README.md

> NOTE: Anbox is currently in a pre-alpha development state. Don't expect a fully working system for a production system with all features you need. You will for sure see bugs and crashes. If you do so, please don't hestitate and report them!

**Comment by Raj2032** [comment]
Cool, thanks man.

**Comment by morphis** [comment]
We're not going to change the license. GPLv3 will stay for various reasons.
