### ISSUE TITLE
Shows starting then exit

### ISSUE THREAD

**Issue by jaywizzy** [anbox/anbox#610]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**
just shows starting.... then after a while it stops

**What were you expecting?:**
atleast, to show something after that...

**Additional info:**

**Comment by Dinoprof** [comment]
My new Anbox install (think most current) into Linuxmint 18.3 Cinnamon seems to load correctly but after rebooting and clicking on the new Anbox icon in the menu, a screen opens and displays the android icon with the message "starting...." but it does not proceed.  

The Terminal Command/s: anbox version, or anbox session-manager, or anbox info, 
all give 

ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored

And an "uninstall" indicates "no package associated with..."

Any references to ld.so.preload, as above, that I can find in my directory all point/link to my virus package ESET Nod32 - So it seems to me there is a mis-direction going on - and in any case something is not quite right.

Any help appreciated.
