### ISSUE TITLE
Anbox stalls on starting screen

### ISSUE THREAD

**Issue by YerongLi** [anbox/anbox#615]
My Anbox stalls on **starting** screen, any idea on how to fix this?
![anbox](https://user-images.githubusercontent.com/13112023/36190535-85cb0b12-111e-11e8-9b21-a7356ff1b611.png)

**Comment by kkapka** [comment]
I had the same issue. Does anbox work with nvidia driver?

**Comment by MajorDeity** [comment]
I'm running an R6450 Radeon and it's the same as above for me as well.

**Comment by qweer85** [comment]
1. check out "alive" Lee "anbox" should be a lot of processes that depend on process "anbox" 
2 reboot the computer or close all programs and open "anbox" and wait can be "anbox" closes and opens

**Comment by pwwiur** [comment]
i have the same issue

**Comment by kkapka** [comment]
On newest Elementary OS version I installed anbox and in the same terminal, i typed reboot. After a restart, anbox works

**Comment by LaurentGoderre** [comment]
Can you try this: https://github.com/anbox/anbox/issues/650#issuecomment-375022493
