### ISSUE TITLE
Unknown symbol __x86_indirect_thunk_rax

### ISSUE THREAD

**Issue by bodqhrohro** [anbox/anbox#625]
**Please describe your problem:**
I've built the latest `ashmem` module from `master` and installed it with `dkms`. But it does not probe successfully.

**What were you expecting?:**
Successfully probing the module on my system.

**Additional info:**
```
$ sudo modprobe ashmem_linux
modprobe: ERROR: could not insert 'ashmem_linux': Unknown symbol in module, or unknown parameter (see dmesg)
$ sudo dmesg|tail -n 1
[211693.017734] ashmem_linux: Unknown symbol __x86_indirect_thunk_rax (err 0)
$ uname -a
Linux localhost.localdomain 4.14.0-3-amd64 #1 SMP Debian 4.14.13-1 (2018-01-14) x86_64 GNU/Linux
```

**Comment by EdwardBetts** [comment]
@bodqhrohro Try rebooting so you're running the latest kernel.

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890999 for more discussion about this problem.

**Comment by bodqhrohro** [comment]
Yes, the module probes successfully now.
