### ISSUE TITLE
Can't open Anbox after install on Ubuntu 17.10 (libpulsecommon-8.0.so missing)

### ISSUE THREAD

**Issue by Victoralm** [anbox/anbox#626]
Trying to open from terminal with `~$ anbox` or `~$ anbox system-info` results in the same output:
`/snap/anbox/71/usr/bin/anbox: error while loading shared libraries: libpulsecommon-8.0.so: cannot open shared object file: No such file or directory`

I'd try to reinstall `libpulse0`, but the problem persists.

**Comment by jeffebido** [comment]
Same problem here

**Comment by harrycode** [comment]
We all have the same problem.

**Comment by DaMatrix** [comment]
can reproduce on fresh mint 18.3 install

**Comment by vallerydelexy** [comment]
why every damn ubuntu update developer have to working hard to make it working.
this is sucksss

im using 17.10

**Comment by harrycode** [comment]
> im using 17.10
Same here. I think that's one of the reasons why it doesn't work.

**Comment by jacksondm33** [comment]
Same here. This has to be an error caused by recent changes.

Whenever I searched on google for this problem, only other anbox issues came up. I only happened to come across others who are having the same issue when I went on the issues tab on github. That was the worst experience with google I have ever had. I guess it's because these issues are too new.

**Comment by geiziry** [comment]
same with me

**Comment by mhsenpc** [comment]
same error with ubuntu 16.4 mate

**Comment by hoehermann** [comment]
I copied my system's `libpulsecommon-8.0.so` into – if I understood this right – the user-specific anbox snap overlay filesystem tree.

    cp /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so ~/snap/anbox/71/lib/x86_64-linux-gnu/pulseaudio/

Then I changed the working directory to that very directory:

    cd ~/snap/anbox/71/lib/x86_64-linux-gnu/pulseaudio/

anbox starts there.

**Comment by Victoralm** [comment]
On my instalation, there is no `libpulsecommon-8.0.so` on `/usr/lib/x86_64-linux-gnu/pulseaudio/` directory, only `libpulsecommon-10.0.so`. So, following hoehermann tip, I did a symbolic link to `libpulsecommon-10.0.so` (renamed to `libpulsecommon-8.0.so`) on `~/snap/anbox/71/lib/x86_64-linux-gnu/pulseaudio/`. I try to copy and rename the lib itself and end up with the same result as follows.
While trying to run `anbox` from  `~/snap/anbox/71/lib/x86_64-linux-gnu/pulseaudio/` directory, I'm getting this message:

> Unknown command 'run'
> 
> NAME:
>     anbox - anbox
> 
> USAGE:
>     anbox [command options] [arguments...]
> 
> COMMANDS:
>     help                 prints a short help message                                                                         
>     system-info          Print various information about the system we're running on                                         
>     version              print the version of the daemon                                                                     
>     session-manager      Run the the anbox session manager                                                                   
>     launch               Launch an Activity by sending an intent

But now I can run `anbox system-info`:

> /usr/share/libdrm/amdgpu.ids: No such file or directory
> amdgpu_device_initialize: Cannot parse ASIC IDs, 0xffffffea.version: 3
> snap-revision: 71
> os:
>   name: Ubuntu
>   version: 17.10 (Artful Aardvark)
>   snap-based: true
> kernel:
>   version: Linux version 4.13.0-36-generic (buildd@lcy01-amd64-017) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3.2)) #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018
>   binder: true
>   ashmem: true
> graphics:
>   egl:
>     vendor: Mesa Project
>     version: 1.5 (DRI2)
>     extensions:
>       - EGL_CHROMIUM_sync_control
>       - EGL_EXT_buffer_age
>       - EGL_EXT_create_context_robustness
>       - EGL_EXT_image_dma_buf_import
>       - EGL_KHR_cl_event2
>       - EGL_KHR_config_attribs
>       - EGL_KHR_create_context
>       - EGL_KHR_create_context_no_error
>       - EGL_KHR_fence_sync
>       - EGL_KHR_get_all_proc_addresses
>       - EGL_KHR_gl_colorspace
>       - EGL_KHR_gl_renderbuffer_image
>       - EGL_KHR_gl_texture_2D_image
>       - EGL_KHR_gl_texture_3D_image
>       - EGL_KHR_gl_texture_cubemap_image
>       - EGL_KHR_image
>       - EGL_KHR_image_base
>       - EGL_KHR_image_pixmap
>       - EGL_KHR_no_config_context
>       - EGL_KHR_reusable_sync
>       - EGL_KHR_surfaceless_context
>       - EGL_KHR_wait_sync
>       - EGL_MESA_configless_context
>       - EGL_MESA_drm_image
>       - EGL_MESA_image_dma_buf_export
>       - EGL_NOK_texture_from_pixmap
>       - EGL_WL_bind_wayland_display
>   gles2:
>     vendor: X.Org
>     vendor: OpenGL ES-CM 1.1 Mesa 17.2.8
>     extensions:
>       - GL_EXT_blend_minmax
>       - GL_EXT_multi_draw_arrays
>       - GL_EXT_texture_filter_anisotropic
>       - GL_EXT_texture_lod_bias
>       - GL_OES_byte_coordinates
>       - GL_OES_fixed_point
>       - GL_OES_stencil_wrap
>       - GL_OES_compressed_paletted_texture
>       - GL_OES_query_matrix
>       - GL_OES_read_format
>       - GL_OES_single_precision
>       - GL_OES_draw_texture
>       - GL_OES_point_size_array
>       - GL_OES_point_sprite
>       - GL_EXT_texture_format_BGRA8888
>       - GL_OES_compressed_ETC1_RGB8_texture
>       - GL_OES_depth24
>       - GL_OES_element_index_uint
>       - GL_OES_fbo_render_mipmap
>       - GL_OES_framebuffer_object
>       - GL_OES_mapbuffer
>       - GL_OES_rgb8_rgba8
>       - GL_OES_stencil8
>       - GL_OES_texture_env_crossbar
>       - GL_OES_texture_mirrored_repeat
>       - GL_OES_texture_npot
>       - GL_OES_EGL_image
>       - GL_OES_packed_depth_stencil
>       - GL_OES_texture_cube_map
>       - GL_APPLE_texture_max_level
>       - GL_EXT_discard_framebuffer
>       - GL_EXT_read_format_bgra
>       - GL_OES_blend_equation_separate
>       - GL_OES_blend_func_separate
>       - GL_OES_blend_subtract
>       - GL_OES_EGL_image_external
>       - GL_OES_EGL_sync
>       - GL_OES_vertex_array_object
>       - GL_EXT_map_buffer_range
>       - GL_KHR_debug
>       - GL_OES_surfaceless_context
>       - GL_EXT_compressed_ETC1_RGB8_sub_texture
>       - GL_EXT_polygon_offset_clamp
>       - GL_KHR_no_error

**Comment by Mahdi321** [comment]
I have same problem in version:
  beta:      4-558d646 (92)  389MB devmode
  edge:      4-bc2cf30 (127) 391MB devmode
installed:   4-558d646 (92)  389MB devmode
