### ISSUE TITLE
Anbox does not open due to missing library

### ISSUE THREAD

**Issue by JORGETECH** [anbox/anbox#627]
I tried to open anbox after installing it under Kubuntu 17.10 but there seems to be a problem with a missing library. The next error appears after launching anbox:

`/snap/anbox/71/usr/bin/anbox: error while loading shared libraries: libpulsecommon-8.0.so: cannot open shared object file: No such file or directory`

I can't even provide a log of "anbox system-info" because of the missing library.

**Comment by jeffebido** [comment]
Same problem here

**Comment by harrycode** [comment]
Same

**Comment by DaMatrix** [comment]
can reproduce on fresh mint 18.3 install

**Comment by jacksondm33** [comment]
This should be fixed now.

**Comment by harrycode** [comment]
uh oh

**Comment by harrycode** [comment]
oh well
