### ISSUE TITLE
anbox doesn't make a volume mount. 

### ISSUE THREAD

**Issue by githubboy1** [anbox/anbox#633]
i have tried to install anbox on linux mint 18.
```
- sudo apt install snapd
- restart pc
- terminal: snap install --classic anbox-installer && anbox-installer 
- restart pc. 
```
But after i restart te pc for the second time the program doesn't start. 
Then i notice that the install not have making a volume mount of 326mb. 
After uninstall anbox and snaps en re-install all over again i have got the same problems. 

I see a lot of topics here from another people saying that anbox doesnt start. 
well maybe is this the problem, the installation doesn't make a volume mount. 

how to fix this? is anbox installer not good anymore?

**Comment by purchagent** [comment]
I think you are right. The installer is stopping during installation. If you look at the folder contents, they are not complete. For me the 71 folder is empty. I fetched the installer script but wasn't able to get it to run. Cloning the repository and building worked fine but I do not know if the application can be run from that build or how to run it from that location.

**Comment by ShneekeyTheLost** [comment]
That's because the line you copied from their website is incorrect. The terminal code should be:

snap install --classic anbox-installer && snap run anbox-installer
