### ISSUE TITLE
Fails to build on Arch linux

### ISSUE THREAD

**Issue by Lite5h4dow** [anbox/anbox#637]
**Please describe your problem:**
Installing anbox Via AUR. It fails to build.

**What were you expecting?:**
It to install

**Additional info:**
```In file included from /home/lotus/.cache/pacaur/anbox-git/src/anbox/src/anbox/cmds/session_manager.cpp:56:0:
/usr/include/core/dbus/asio/executor.h:29:7: error: using typedef-name ‘boost::asio::io_service’ after ‘class’
 class io_service;
       ^~~~~~~~~~
In file included from /usr/include/boost/asio.hpp:69:0,
                 from /home/lotus/.cache/pacaur/anbox-git/src/anbox/src/anbox/runtime.h:21,
                 from /home/lotus/.cache/pacaur/anbox-git/src/anbox/src/anbox/audio/server.h:21,
                 from /home/lotus/.cache/pacaur/anbox-git/src/anbox/src/anbox/cmds/session_manager.cpp:26:
/usr/include/boost/asio/io_service.hpp:27:20: note: ‘boost::asio::io_service’ has a previous declaration here
 typedef io_context io_service;
                    ^~~~~~~~~~
make[2]: *** [src/CMakeFiles/anbox-core.dir/build.make:2463: src/CMakeFiles/anbox-core.dir/anbox/cmds/session_manager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2023: src/CMakeFiles/anbox-core.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
:: failed to build anbox-git package(s)```

**Comment by KetanM94** [comment]
Edit this file "/usr/include/core/dbus/asio/executor.h" and comment out "class io_service;" and then try rebuild. It builds without error. But I'm yet to make it work fully on Manjaro Linux.

**Comment by Lite5h4dow** [comment]
I'm installing from the AUR, I've never built anything from GitHub except some Nim programs so i don't know how to do that.

**Comment by KetanM94** [comment]
@Lite5h4dow well, you just have to edit the file executor.h and install Anbox from AUR as you normally do.
Do as follow:
`sudo nano /usr/include/core/dbus/asio/executor.h`
Just add '//' this before 'class io_service;' => "//class io_service;
then save it. And install Anbox as normal.

**Comment by tmn505** [comment]
According to this http://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/net_ts.html
io_service was replaced with io_contetx.
For dbus-cpp use https://ptpb.pw/5E35.patch and for anbox use https://ptpb.pw/SMOr.patch
Should compile, didn't test if it's running properly.

**Comment by a-andreyev** [comment]
@tmn505, worked for me, thank you! (at least I could get apps list and launch calc app). could not interact with the apps though (probably other not related bug).
could you comment, is it make sense to add a code depending on `BOOST_VERSION` for both projects or pkgbuild patches are enough?

**Comment by dvzrv** [comment]
@KetanM94: you should really stop giving people advice to modify their system files, because an arbitrary build process is misbehaving.

**Comment by tmn505** [comment]
@dvzrv KetanM94 had a good hunch, just slightly different approach would be better. Whipped a patch using his pointer https://ptpb.pw/lBv1.patch, and it compiles properly, didn't test if it's running.

@a-andreyev You can't modify easily the dbus-cpp and that wouldn't make sense, with anbox that's feasible. Better use the patch in this comment.

**Comment by KetanM94** [comment]
@dvzrv Thank you for your kind advice. I'll be more careful next time.
The reversal (just uncommenting, in this case) of what I suggested, is not that hard.
Also, the dbus-cpp was just a dependency not a system file AFAIK.

**Comment by a-andreyev** [comment]
@tmn505, thanks!
sent your patch to package maintaner:
https://aur.archlinux.org/packages/dbus-cpp
