### ISSUE TITLE
Failed to install the snap package (error: cannot communicate with server)

### ISSUE THREAD

**Issue by EazyErwin** [anbox/anbox#641]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

Hi guys, so I´ve tried to install anbox as it was described in the wiki. However, this is what i got in response.
snap install --edge --devmode anbox
error: cannot communicate with server: Post http://localhost/v2/snaps/anbox: dial unix /run/snapd.socket: connect: no such file or directory

I am running Ubuntu 16.04.03 LTS on my chromebook with crouton (Xenial, Xfce). I imagine the problem lies with snap (hope that someone around here still might be able to help me :) 
This is what "snap --version" shows me
snap    2.29.4.2
snapd   unavailable
series  -

Anyway, thanks in advance!

**What were you expecting?:**

**Additional info:**

**Comment by EazyErwin** [comment]
Did some more digging, perhaps this helps with the solution
entered in terminal: systemctl status snapd
Failed to get properties: Launch helper exited with unknown return code 1

**Comment by cuppajoeman** [comment]
Restarting seemed to help me .
`sudo systemctl restart snapd.service`
