### ISSUE TITLE
Does not work on Kubuntu 17.10

### ISSUE THREAD

**Issue by lautiamkok** [anbox/anbox#649]
I managed to download and install it on my Kubuntu 17.10. I have reboot my machine and I can find Anbox icon on my launcher. But when I click on it, I just get a black screen cover my entire my monitor screen. After a few second, the black screen goes away. 

I have tried a few times, but no luck at all.

Have you guys tested on Kubuntu/ Ubuntu 17.10?

**Comment by LaurentGoderre** [comment]
https://github.com/anbox/anbox/issues/650#issuecomment-375022493

**Comment by Krishnawa** [comment]
No now I'm upgrade my system into Ubuntu 16.04:smile:
