### ISSUE TITLE
How to run Anbox?

### ISSUE THREAD

**Issue by lddd** [anbox/anbox#652]
Hello there,

I would like to know how to run Anbox. The installation process according to the docs provides here was successfully and i can see a Anbox Launch Icon under Applications -> Other -> Anbox

However by click on it nothing happens, also i get the following error on a terminal 

> ubuntu@ip-172-31-29-147:~$ anbox session-manager
> No protocol specified
> Segmentation fault (core dumped)

> ubuntu@ip-172-31-29-147:~$ anbox system-info
> Segmentation fault (core dumped)

```
ubuntu@ip-172-31-29-147:~$ cat /proc/version
Linux version 4.4.0-1052-aws (buildd@lgw01-amd64-031) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) ) #61-Ubuntu SMP Mon Feb 12 23:05:58 UTC 2018
```

**Comment by WPFilmmaker** [comment]
@lddd If you are on ubuntu this #650  worked for my (lubuntu 16.04).
