### ISSUE TITLE
Add F-droid in the default installation?

### ISSUE THREAD

**Issue by WPFilmmaker** [anbox/anbox#654]
Seems that anbox devs are not interested and cannot ship google store by default, but what about F-droid? It is open source and hosts opensource apps. It would be very useful as it could provide an immedate way to download apps on anbox and try them and see if/how they work, report bugs here etc.

**Comment by Bubu** [comment]
(I'm an F-Droid contributor)

I just tried Anbox today and of course the first thing I installed was F-Droid ;-). It worked out of the box and I think it would fit pretty well as an app store component for anbox.

There's also [F-Droid Privileged Extension](https://gitlab.com/fdroid/privileged-extension) which could very well be integrated in anbox, this way f-droid can do automatic updates and one-click installs of apps.

**Comment by grote** [comment]
Plus, people can add extra repositories to F-Droid (and even make their own) to add additional apps to it while receiving updates automatically. Since this works within the GUI, I think it would be easier for most people than using adb.

**Comment by WPFilmmaker** [comment]
News on this? (let's not make this tread closed due to inactivity)

**Comment by WPFilmmaker** [comment]
Keeping this ticket open and hopefully this will be implemented.

**Comment by WPFilmmaker** [comment]
Keeping this ticket open and hopefully this will be implemented.

**Comment by WPFilmmaker** [comment]
Keeping this ticket open and hopefully this will be implemented.

**Comment by Bubu** [comment]
Still would be happy to help to make this happen :).
