### ISSUE TITLE
"Command not found" after installing the snap and trying to run anbox-installer on Manjaro

### ISSUE THREAD

**Issue by ghost** [anbox/anbox#657]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

**Please describe your problem:**
Trying to run anbox-installer after installing the snap

**What were you expecting?:**
At least the anbox-installer run. It displays as "command not found"

**Additional info:**
I'm running Manjaro GNOME. Kernel is 4.14.27 LTS

**Comment by markstock** [comment]
Hi! Same problem on Fedora (latest snap, latest anbox). But the solution won't help you (or me). The anbox-installer can be run at:
`/var/lib/snapd/snap/bin/anbox-installer`
but will immediately tell you
```
ERROR: You are running the installer on an unsupported distribution.
       At the moment we only support the following distributions:

Ubuntu, LinuxMint, neon, elementary
```
