### ISSUE TITLE
Create a wiki page with a list of apps that anbox is capable of running

### ISSUE THREAD

**Issue by WPFilmmaker** [anbox/anbox#658]
I am one of the maintainers of such list for Lightspark project (an open source flash player).

Having such list where compatibilties and notes for each app that anbox can/can't run would be great.

ps: If  am given editing rights I am happy to test some of the most popular apps.

**Comment by morphis** [comment]
WPFilmmaker <notifications@github.com> schrieb am 25.03.2018:
>I am one of the maintainers of such list for Lightspark project (an
>open source flash player).
>
>Having such list where compatibilties and notes for each app that anbox
>can/can't run would be great.
>
>ps: If  am given editing rights I am happy to test some of the most
>popular apps.

-- Diese Nachricht wurde mit K-@ Mail gesendet.

**Comment by morphis** [comment]
Check https://discourse.anbox.io/t/app-compatibility-list/38

**Comment by WPFilmmaker** [comment]
@morphis Thanks. What I meant was something simple and easy to edit like this: https://github.com/lightspark/lightspark/wiki/Site-Support
