### ISSUE TITLE
Cannot install successfully in Ubuntu Server 18.04

### ISSUE THREAD

**Issue by yasenstar** [anbox/anbox#663]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**
Installer error screen in terminal:
Err:20 http://ppa.launchpad.net/morphis/anbox-support/ubuntu bionic Release    
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                       
E: The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
+ cleanup
+ local err=100
+ trap - EXIT
+ echo 'ERROR: Installation failed. Removing all parts of Anbox again.'
ERROR: Installation failed. Removing all parts of Anbox again.
+ uninstall
+ set -x
+ sudo snap remove anbox
snap "anbox" is not installed
+ '[' -e /etc/apt/sources.list.d/morphis-ubuntu-anbox-support-xenial.list ']'
+ set +x

**What were you expecting?:**

**Additional info:**

**Comment by SNEKBOI** [comment]
+1
