### ISSUE TITLE
SFOS

### ISSUE THREAD

**Issue by nkrapivin** [anbox/anbox#678]
How to install anbox on Sailfish OS?

**Comment by Astaoth** [comment]
Hi,
Same question here : is Sailfish OS supported ??

**Comment by baptx** [comment]
Any advice? Some people worked on it but it looks like the network is not working:
https://www.youtube.com/watch?v=xu8x0x1X9OM&lc=UgxxzpuL6ETwhlly8Ed4AaABAg
