### ISSUE TITLE
Complete system freeze

### ISSUE THREAD

**Issue by RikudouSage** [anbox/anbox#681]
After installing my computer froze, I don't know at what point exactly, I was doing something else while the installation progressed in terminal. I was following the official installation via `snap`.

After the freeze I had to force restart via the power off button.

After boot during login screen the system froze again, I tried it multiple times, nothing worked, system wasn't responding at all, after I booted to text mode, I got a bunch of these errors:

- `Watchdog detected hard LOCKUP on cpu 0` (also on CPU 1, 2 and 3)
- `BUG: soft lockup - CPU stuck for 23s`

The system was unresponsive the whole time and more of these errors showed up after some time.

**My system info**

- OS: `Linux Mint 18.3 Sylvia`
- Linux version: `4.13.0-38-generic`
- Architecture: `x86_64`
- CPU: `Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz`
- GPU: `NVIDIA GM107M [GeForce GTX 950M]`
- CPU driver: `intel-microcode (version 3.20180312.0-ubuntu16.04.1)`
- GPU driver: `nvidia-384 (version 384.111-0ubuntu0.16.04.1)`

I'm not so skilled with all the kernel things so I don't know where the logs are, if you tell me where they could be, I'll upload them.

**Comment by Thomas830** [comment]
Same thing here with Linux Mint 18.3 and same Kernel
After anbox-installer went ok and asks me to reboot, the system froze and I'm now unable to boot in Linux Mint.

**Comment by RikudouSage** [comment]
@Thomas830 I can help you with restoring your system if you want.

**Comment by Thomas830** [comment]
I already wipe and reinstalled my system... But I'm sure it would be appreciated that you share your solution

-------- Message d'origine --------
