### ISSUE TITLE
anbox Failed to configure LXC container with lxc 3.0

### ISSUE THREAD

**Issue by bert-il** [anbox/anbox#684]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```** Please paste the result of anbox system-info below:**
anbox system-info
version: local-03f69c8
os:
name: Antergos Linux
version: 18.3-ISO-Rolling
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by Bertil-100** [comment]
How do I patch according
https://github.com/anbox/anbox/issues/669

say name of patch file is patchanbox669 starting with
diff --git a/src/anbox/container/lxc_container.cpp b/src/anbox/container/lxc_container.cpp
index 962832b..6c5d3b9 100644
--- a/src/anbox/container/lxc_container.cpp
+++ b/src/anbox/container/lxc_container.cpp
@@ -65,24 +65,24 @@ void LxcContainer::setup_id_maps() {
   const auto base_id = unprivileged_user_id;
   const auto max_id = 65536;
......
ending with
   if (!privileged_)

Can somebody comment this.
I am new in patching source files !

Help is very much appreciated, thank you.
This is related to newest arch linux using 
Antergos Linux
version: 18.3-ISO-Rolling

THANK YOU.

**Comment by bert-il** [comment]
Can somebody make the binary (executabale) for newest anbox under arch linux with lxc 3.0 make available for download.
![anbox-git](https://user-images.githubusercontent.com/34073898/39033486-88213328-4472-11e8-9fe9-dbdabc5cc72c.png)

**Comment by garyvdm** [comment]
@Bertil-100 run `git apply PATHTOPATCH`. Make sure you are in the root directory of the source when you run this.

**Comment by Ygarr** [comment]
So need to install from git directly - no yaourt? to apply patch?

**Comment by bert-il** [comment]
I saw that Feng was succeeded to get anbox with lxc3 running.
Can you provide the binaries 
properties-cpp
anbox-git
anbox-image .....
to install it on antergos up-to-date. 
I create normally packages with
git clone ...
cd ....
makepkg -si
This would be phantastic and extremely nice. Or detailed build instructions:
Highly appreciated ! Thank you in advance. Binaries can be uploaded to .... should be no problem right?
Enjoy your day.  Thank you!

**Comment by morphis** [comment]
Duplicates #669
