### ISSUE TITLE
Ubuntu hangs after reboot

### ISSUE THREAD

**Issue by DerKnerd** [anbox/anbox#688]
Make sure you are running the latest version of Anbox before reporting an issue.

**Please describe your problem:**
After installing anbox my Ubuntu 17.10 stops responding and every input is ignored by the laptop.

**What were you expecting?:**
That my Ubuntu would respond

**Additional info:**

**Comment by morphis** [comment]
@DerKnerd @tmoulder Can you guys remove the snap first, try if everything works again and then remove the anbox-modules-dkms Debian package from the system? To diagnose this more we need further details on what happened. Also archive `/snap/bin/anbox.collect-bug-info` would be helpful here.

**Comment by tmoulder** [comment]
morphis, i wish I could be of more help, but I have since upgraded to 18.04, and honestly, after that scare I am reluctant to risk my system.  I would need to see alot of 18.04 happy user posts before I would risk it again.  Pity too, because I love the idea behind it.

**Comment by tmoulder** [comment]
https://github.com/anbox/anbox/issues/681

Seems like a duplicate

**Comment by DerKnerd** [comment]
I attached the output of lshw -html to this comment.
[System.txt](https://github.com/anbox/anbox/files/2066020/System.txt)
