### ISSUE TITLE
Syntax error on line 26

### ISSUE THREAD

**Issue by ayfati01** [anbox/anbox#69]
**Description of the problem:**
    Throwing a syntax error on line 26 with the message: *Syntax error: "(" unexpected*

**Expected:**
    Run without an error.

**Additional info:**
    I didn't run the file with 'sudo' just like what the instructions stated.

**Comment by sudopluto** [comment]
this happens when you run the program with sh. when changing to executable and running this doesn't happen

**Comment by ayfati01** [comment]
I have tried running it without the sh and without the sudo command and terminal the threw a permission denied error. Any suggestions ??
