### ISSUE TITLE
Anbox on Kali linux not working despite compiling from source

### ISSUE THREAD

**Issue by andrew-oko-odion** [anbox/anbox#691]
Anbox not starting on KALI which is a Debian fork  despite  all the hard work of compiling from source

 `anbox system-info` 
```
[libEGL warning: DRI2: failed to open i965 (search paths /usr/lib/x86_64-linux-gnu/dri:${ORIGIN}/dri:/usr/lib/dri)
libEGL warning: DRI2: failed to open i965 (search paths /usr/lib/x86_64-linux-gnu/dri:${ORIGIN}/dri:/usr/lib/dri)
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:${ORIGIN}/dri:/usr/lib/dri)
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:${ORIGIN}/dri:/usr/lib/dri)
Segmentation fault]
```
 `sudo systemctl start anbox-container-manager.service ` 

```[Failed to start anbox-container-manager.service: Unit anbox-container-manager.service is masked.]```

What were you expecting?:
I am expecting the container to just start

**Comment by andrew-oko-odion** [comment]
Hi Anbox team

Please I need you to take a look at this issue

**Comment by supercityway** [comment]
Still can't fix it.



add-apt-repository ppa:morphis/anbox-support
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Kali/kali-rolling
