### ISSUE TITLE
Add support for Arch Linux based distros such as Manjaro

### ISSUE THREAD

**Issue by zanedb** [anbox/anbox#693]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

**Please paste the result of `anbox system-info` below:**
```
bash: anbox: command not found
```

**Please describe your problem:**
Anbox will not install. When I attempt to install, I'm getting the following error:
```
Anbox (Android in a Box) - Installer


IMPORTANT: THIS IS ALPHA LEVEL SOFTWARE. EXPECT INSTABILITY AND
           BUGS !!!!!

IMPORTANT: ALSO PLEASE BE AWARE THAT WE DON'T PROVIDE FULL
           CONFINEMENT FOR THE SNAP YET !!!!


PLEASE NOTE: This script will require root access on your system
to install all necessary things. It will prompt you to enter your
password when required.


ERROR: You are running the installer on an unsupported distribution.
       At the moment we only support the following distributions:

Ubuntu, LinuxMint, neon, elementary

If your distribution is in the list but you still see this message, open
an issue here: https://github.com/anbox/anbox-installer

```

**What were you expecting?:**
I was expecting it to run, as nowhere on [the website](https://anbox.io) does it state the supported distros. I now understand that Arch Linux (and therefore Manjaro) is not supported. However, I am creating this issue as I would like support to be expanded. 

**Additional info:**
Is there any way I can force it to run on my OS, regardless of how buggy it may be? Also, if you don't mind me asking, what is the issue preventing support?

I understand I am a newbie here and I do not wish to bother any contributors. Thank you in advance!

**Comment by mitcoes** [comment]
Great project guys, thanks a lot

I tried it when it started and did not work even in my Ubuntu (Manjaro is my default one)
Today continues to give me this ERROR

"snap install --classic anbox-installer && anbox-installer
error: cannot communicate with server: Post http://localhost/v2/snaps/anbox-installer: dial unix /run/snapd.socket: connect: no such file or directory"

I suppose you watched also MS WOS's Bluestacks that I think uses qemu to configure its virtual ARM machine and works well.

Waiting to test your beta without this issues soon.

Thanks in advance for thinking in archers too,

PS: flatpaks work great in arch (also in Ubuntu), and I did not found any snap that does, even in Ubuntu.

**Comment by Abracakebabra** [comment]
I have the same problem with the snap installation.

**Comment by aimileus** [comment]
@mitcoes and @Abracakebabra, I did not manage to get anbox working using the snap package either. However, to get snapd working at all you need to enable/start `snapd.socket `, e.g. `systemctl enable --now snapd.socket'.

**Comment by mitcoes** [comment]
I had snap working, and i even was able to install the anbox kernel modules BUT it never worked.
FLATPAKS work better than snaps in my experience and even more in not Ubuntu based distributions.

As ANBOX is still in alpha, it would be nice for the project to migrate to flatpaks, and arrive to archers, and rpm distributions, better than with snap, or at all.

It si a great idea yo use LXC containers, to run other OSs, as Android, and perhaps ReactOS and Freedos containers in flatpak would also be nice to have, and it seems it will not be as hard as setting up a LXC container with qemu emulating ARM.
