### ISSUE TITLE
Fails to install on Elementary Loki (debian/ubuntu-based)

### ISSUE THREAD

**Issue by apgodshall** [anbox/anbox#697]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
$ anbox system-info
anbox: command not found
```

**Please describe your problem:**

$ anbox-installer
anbox-installer: command not found

$ /snap/bin/anbox-installer 
Anbox (Android in a Box) - Installer
...
What do you want to do?

 1. Install Anbox
 2. Uninstall Anbox

Please enter your choice [1-2]: 
1
...
or type anything else to abort:
I AGREE
...

Starting installation process ...

+ sudo add-apt-repository -y ppa:morphis/anbox-support
sudo: add-apt-repository: command not found

**What were you expecting?:**

I was expecting it to install.

**Additional info:**

$ grep . /etc/issue
elementary OS Loki \n \l

$ uname -a
... 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by apgodshall** [comment]
Aha!

Solved by:

$ sudo apt install software-properties-common

Please add to the installation script.

**Comment by morphis** [comment]
The anbox-installer snap is deprecated now. Please see 
https://github.com/anbox/anbox/blob/master/docs/install.md for updated installation instructions
