### ISSUE TITLE
Binder Patch Unnecessary If Only One Container Is Running?

### ISSUE THREAD

**Issue by elliott-wen** [anbox/anbox#699]
Hi Folks,

I am trying to port Anbox to Ubuntu 18.04, the first problem I have to handle is how to port the binder module. I am wondering whether we still need the binder patch if we can ensure only one LXC container is running?

Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by morphis** [comment]
If you mean https://github.com/anbox/anbox/tree/master/kernel/patches then those two patches are not needed. The binder/ashmem DKMS modules are all you need.

**Comment by elliott-wen** [comment]
I am thinking about migrating  the binder module to the user space, which may be a first step to get rid of DKMS

**Comment by morphis** [comment]
@elliott-wen That isn't really easy as it sounds. I am working on a better way to get rid of the DKMS module.
