### ISSUE TITLE
README Links Broken.

### ISSUE THREAD

**Issue by DWiechert** [anbox/anbox#7]
Make sure you are running the latest version of Anbox before reporting an issue.

**Anbox release (`anbox version`) and system info (`anbox system-info`):**
N/A.

**Description of the problem:**
The design links on the README are broken.
- https://android.googlesource.com/platform/external/qemu/emu-master-dev/distrib/android-emugl/DESIGN
- https://android.googlesource.com/platform/external/qemu/+/emu-master-dev/docs/ANDROID-QEMU-PIPE.TXT
- https://android.googlesource.com/platform/external/qemu/+/emu-master-dev/docs/ANDROID-QEMUD.TXT
- https://android.googlesource.com/platform/external/qemu/+/emu-master-dev/docs/ANDROID-QEMUD-SERVICES.TXT

**Expected:**
Links redirect to proper diagrams.

**Additional info:**
N/A.

**Comment by morphis** [comment]
Looks like the upstream project has moved things around. @DWiechert Interested in doing your first PR and fixing those links? :-)

 * https://android.googlesource.com/platform/external/qemu/+/emu-master-dev/android/android-emugl/DESIGN
 * https://android.googlesource.com/platform/external/qemu/+/emu-master-dev/android/docs/

are the new locations for these docs as it seems.
