### ISSUE TITLE
Hoping for loosing restriction of installation on unsupported distributions

### ISSUE THREAD

**Issue by NobodyXu** [anbox/anbox#704]
I'm using Debian 9.4, linux kernel 4.9, gcc 6.3 x86-64 intel i7 Q720 computer.

First I tried using ```snap```, but the bash printed that ```anbox-installer``` can't be found on my system.

Then I tried to use [installer script](https://raw.githubusercontent.com/anbox/anbox-installer/master/installer.sh). But it didn't allow me to install on my computer, saying that it's running on an unsupported distribution and exited.

I knew that debian hasn't been offically supported yet, but can't you guys loose this a bit by allowing us to try to install it on a different distribution easily, using ```snap``` or ```installer script```. We are eager to give it a try, and loosing it will probably help finding bugs on running on another distribution.

Instead of exiting, I hope the ```installer``` can just print a warning to ```stderr``` and ask usr whether to continue or not, since at the end of the day, it's the usrs' choice to decide whether they should have a try on their unsupported distributions.

**Comment by sirredbeard** [comment]
There appears to be several issues across several distros.

Ubuntu 18.04 https://github.com/anbox/anbox/issues/565
Debian Testing https://github.com/anbox/anbox/issues/710
Debian Stretch https://github.com/anbox/anbox/issues/704
Elementary Loki https://github.com/anbox/anbox/issues/704
Arch https://github.com/anbox/anbox/issues/693
Kali https://github.com/anbox/anbox/issues/691
Solus https://github.com/anbox/anbox/issues/689
Fedora 27 https://github.com/anbox/anbox/issues/687

The developer has responded here.

> There is no clear roadmap or such alike for Anbox. The last year was pretty busy for me with a lot of other things so I didn't had enough time to pay the needed attention to Anbox. However as things have changed a bit I am trying to catch up now with what was left and trying to make Anbox more stable and make it working better.

https://github.com/anbox/anbox/issues/707#issuecomment-388950086

> It's not just the PPA which needs changes. Stay tuned fixes are being worked on.

https://github.com/anbox/anbox/issues/565#issuecomment-389290013

Please see bug ticket opened here where we ask the developer what we can do to support his work. https://github.com/anbox/anbox/issues/711

**Comment by morphis** [comment]
The installer is deprecated now. The `anbox` snap can be installed everywhere where snaps are supported, only the kernel modules need packaging on each distribution.
