### ISSUE TITLE
Anbox Status and planned activities

### ISSUE THREAD

**Issue by TomFreudenberg** [anbox/anbox#707]
Dear Simon ( @morphis )

as far as we all can see you are doing a lot of work on Anbox and comitting new changes. My question is, if you are more interested in feature testing than letting people already use Anbox. In the issue tracker are a number of request to support Anbox for newer distros like Ubuntu 18.04 - but none is answered by you yet.

I tried the "compile procedure" by myself but in case of missing parts for a "self doing walkthru" I gave up after a few hours.

So I would like to get your next plans and decisions about the future of Anbox. Maybe the simpliest one would be a good "hot to build it completely by yourself" documentation.

Thanks for your work and some feedback
Tom

**Comment by sirredbeard** [comment]
It looks like Anbox needs to be updated for updated versions of big distros like Debian Testing, Ubuntu 18.04, and Fedora 28. It also needs to be made available on popular distros like Arch and Solus.

There is also a big opportunity for Anbox on the upcoming Purism Librem 5, particularly if Android app functionality can be included on a Linux phone.

Please set up a Patreon and let us financially support development of Anbox.
