### ISSUE TITLE
snap.anbox.anbox additional lines required

### ISSUE THREAD

**Issue by KarlHegbloom** [anbox/anbox#71]
I was not able to make the session-manager run without editting /var/lib/snapd/apparmor/profiles/snap.anbox.anbox to add the following lines, then running sudo service apparmor force-reload. I did not figure out how to make the new lines be in there after a restart, but I do know that the anbox window won't show up until I do this.

Angry birds x86 works though, and it's almost fast enough! Nice job. Mad props. Keep at it. This is worth it.

  @{PROC}/[0-9]*/cgroup r,
  @{PROC}/[0-9]*/mountinfo r,
  /run/udev/data/* r,
  /etc/drirc r,
  network unix stream,
  network inet stream,
  network inet6 stream,
  @{PROC}/[0-9]*/net/if_inet6 r,
  @{PROC}/[0-9]*/net/ipv6_route r,
  @{PROC}/[0-9]*/net/dev r,
  @{PROC}/[0-9]*/net/unix r,
  @{PROC}/[0-9]*/net/wireless r,
  owner @{HOME}/.Xauthority r,
  /run/user/*/pulse/native wr,
  /dev/shm/pulse-shm-[0-9]* wr,
  /etc/pulse/client.conf r,
  /run/user/[0-9]*/bus wr,
  /run/anbox-container.socket wr,

**Comment by morphis** [comment]
This is interesting. Did you install the anbox snap not in devmode? As the anbox-installer does this there should be not confinement at all for anbox. Did you see any denials in the output from the `dmesg` command?

**Comment by KarlHegbloom** [comment]
Hmm. I see now that they were in audit mode.
