### ISSUE TITLE
Please support Debian Testing

### ISSUE THREAD

**Issue by gerroon** [anbox/anbox#710]
Hi

it looks like Debian testing is not supported. It would be nice if I could run this on my system.

4.15.0-3-amd64 #1 SMP Debian 4.15.17-1 (2018-04-19) x86_64 GNU/Linux

**Comment by sirredbeard** [comment]
There appears to be several issues across several distros.

Ubuntu 18.04 https://github.com/anbox/anbox/issues/565
Debian Testing https://github.com/anbox/anbox/issues/710
Debian Stretch https://github.com/anbox/anbox/issues/704
Elementary Loki https://github.com/anbox/anbox/issues/704
Arch https://github.com/anbox/anbox/issues/693
Kali https://github.com/anbox/anbox/issues/691
Solus https://github.com/anbox/anbox/issues/689
Fedora 27 https://github.com/anbox/anbox/issues/687


The developer has responded here.

> There is no clear roadmap or such alike for Anbox. The last year was pretty busy for me with a lot of other things so I didn't had enough time to pay the needed attention to Anbox. However as things have changed a bit I am trying to catch up now with what was left and trying to make Anbox more stable and make it working better.

https://github.com/anbox/anbox/issues/707#issuecomment-388950086

> It's not just the PPA which needs changes. Stay tuned fixes are being worked on.

https://github.com/anbox/anbox/issues/565#issuecomment-389290013

**Comment by morphis** [comment]
@gerroon Help is always welcome to get the `anbox-modules-dkms` package into the Debian archive. If you want to help with that or know people who can, please do so.

**Comment by gerroon** [comment]
@morphis thanks I am not so skilled but I will try to contact couple friends about it.

**Comment by morphis** [comment]
@gerroon Thanks.

**Comment by zhsj** [comment]
This issue can be closed, the kernel on Debian testing(buster) now has the in-tree Android modules, which means you don't need to install the dkms modules manually.
