### ISSUE TITLE
Anbox with xvfb

### ISSUE THREAD

**Issue by v1nc** [anbox/anbox#714]
I tried to run anbox with xvfb today.
Neither xvfb-run nor changing the display env var to the xvfb display worked.
If you try `xvfb-run anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity`, you will see the appmgr launching on your display.
I think the display env does not apply because the anbox launch command does not start the applications with the terminal display env. How can i change the display server of anbox ?

**Comment by lag-linaro** [comment]
Forgive me if I'm wrong, but I believe you have to start the Session Manager on the specified FB, not the Launcher.

**Comment by morphis** [comment]
@lag-linaro is correct. The session manager is what talks to the X11 display server. The `anbox launch` command only sends a dbus call to the session manager to start a specific application (which is then owned by the session manager). There is an edge case where the `anbox launch` command spawns the session manager but I would recommend that in your case you start the session manager always manually.

**Comment by v1nc** [comment]
Why is this closed ? I never got anbox running with xvfb or xpra/xdummy, did you ? Starting the session manager manually does not fix it.

**Comment by lag-linaro** [comment]
Probably because it's not broken.  #worksforme

Please provide exact steps to recreate and maybe we can see what's going wrong.

**Comment by imShara** [comment]
@morphis How to run anbox in specific X? Like:

```DISPLAY=:1 anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity```

This not works, anbox runs in DISPLAY=:0

And what you mean about starting session manager manually? I'm trying to run:

```
Xvfb :0 -screen 0 1024x768x16 &
DISPLAY=:0 dbus-launch
DISPLAY=:0 openbox-session
DISPLAY=:0 anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
```

But anbox not works
```
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
[ 2020-01-26 01:13:39] [daemon.cpp:61@Run] Failed to connect to DBus
```
Where is mistake?

**Comment by baptx** [comment]
Isn't Anbox using X11 isolation by default? Otherwise is there a way to do use Xephyr with Anbox like it can be done with firejail? This would improve the security to prevent an Android app using a spyware to track the host OS (keylogger, screenshots, clipboard).

**Comment by imShara** [comment]
Is there changes since last comment?
