### ISSUE TITLE
not install on 18.04 . repo "artful" not help

### ISSUE THREAD

**Issue by WArYagTwar** [anbox/anbox#715]
snap install --classic anbox-installer && anbox-installer
snap "anbox-installer" is already installed, see "snap refresh --help"
Anbox (Android in a Box) - Installer

IMPORTANT: THIS IS ALPHA LEVEL SOFTWARE. EXPECT INSTABILITY AND
           BUGS !!!!!

IMPORTANT: ALSO PLEASE BE AWARE THAT WE DON'T PROVIDE FULL
           CONFINEMENT FOR THE SNAP YET !!!!

PLEASE NOTE: This script will require root access on your system
to install all necessary things. It will prompt you to enter your
password when required.

What do you want to do?

 1. Install Anbox
 2. Uninstall Anbox

Please enter your choice [1-2]: 
1

This is the installer for the anbox runtime environment. It will
install certain things on your system to ensure all requirements
are available for anbox to work correctly.

In summary we will install the following things:

 * Add the anbox-support ppa ppa:morphis/anbox-support to the
   host system
 * Install the anbox-modules-dkms deb package from the ppa
   which will add kernel modules for ashmem and binder which are
   required for the Android container to work.
 * Configure binder and ashmem kernel modules to be loaded
   automatically on boot.
 * Install the anbox-common package from the ppa which will
   - Add an upstart job for the current user waryag which will
     start the anbox runtime on login.
   - Add a X11 session configuration file to allow the system
     application launcher (Unity7, Gnome Shell, ..) to find
     available Android applications.

Please type 'I AGREE' followed by pressing ENTER to continue
or type anything else to abort:
I AGREE

Starting installation process ...

+ sudo add-apt-repository -y ppa:morphis/anbox-support
Сущ:1 http://ru.archive.ubuntu.com/ubuntu bionic InRelease
Сущ:2 http://ru.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                       
Сущ:3 http://ru.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                                     
Сущ:4 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                                        
Сущ:5 http://ru.archive.ubuntu.com/ubuntu bionic-proposed InRelease                                                                      
Сущ:6 http://ppa.launchpad.net/morphis/anbox-support/ubuntu artful InRelease                                                             
Игн:7 http://ppa.launchpad.net/morphis/anbox-support/ubuntu bionic InRelease                                                             
Сущ:8 https://dl.winehq.org/wine-builds/ubuntu artful InRelease                                                                        
Сущ:9 http://archive.canonical.com/ubuntu bionic InRelease                                                                     
Ошк:10 http://ppa.launchpad.net/morphis/anbox-support/ubuntu bionic Release       
  404  Not Found [IP: 91.189.95.83 80]
Чтение списков пакетов… Готово                                       
E: Репозиторий «http://ppa.launchpad.net/morphis/anbox-support/ubuntu bionic Release» не содержит файла Release.
N: Обновление из этого репозитория нельзя выполнить безопасным способом, и поэтому по умолчанию он отключён.
N: Смотрите справочную страницу apt-secure(8) о создании репозитория и настройке пользователя.
+ cleanup
+ local err=100
+ trap - EXIT
+ echo 'ERROR: Installation failed. Removing all parts of Anbox again.'
ERROR: Installation failed. Removing all parts of Anbox again.
+ uninstall
+ set -x
+ sudo snap remove anbox
snap "anbox" is not installed
+ '[' -e /etc/apt/sources.list.d/morphis-ubuntu-anbox-support-xenial.list ']'

**Comment by finanalyst** [comment]
I ran into the same problem with ubuntu 18.04. Here is an extract on my box, which has English as a locale language. Exactly same error (I read both English and Russian):
```
E: The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
+ cleanup
+ local err=100
+ trap - EXIT
+ echo 'ERROR: Installation failed. Removing all parts of Anbox again.'
ERROR: Installation failed. Removing all parts of Anbox again.
```

**Comment by morphis** [comment]
Duplicates #565
