### ISSUE TITLE
x86 build

### ISSUE THREAD

**Issue by IlyaBizyaev** [anbox/anbox#716]
Hello! :D
Is it possible to build Anbox for x86? And how difficult would it be?

**Comment by morphis** [comment]
You mean x86 as in i386? If yes, there is no interest in building Anbox and with that the included Android for i386. I am not even sure if you can build Android for i386 without quite a few code changes.

Why do you want Anbox for i386? Most systems should be x86_64 these days.

**Comment by IlyaBizyaev** [comment]
Code changes is what I was expecting.
I have an x86 phone where I could use Anbox.

**Comment by morphis** [comment]
@IlyaBizyaev Ok. However we don't have any plans to support i386 hence closing this.

**Comment by IlyaBizyaev** [comment]
Wow, that was fast.
I see that you don't have such plans, that's understandable, but the question was if it is actually difficult to do. Are there really so many places where architecture is specified explicitly?
