### ISSUE TITLE
18.04 ERROE language Chinese

### ISSUE THREAD

**Issue by Ambitie** [anbox/anbox#723]
ERROR CODE:

+ cleanup
+ local err=100
+ trap - EXIT
+ echo 'ERROR: Installation failed. Removing all parts of Anbox again.'
ERROR: Installation failed. Removing all parts of Anbox again.
+ uninstall
+ set -x
+ sudo snap remove anbox
snap "anbox" is not installed
+ '[' -e /etc/apt/sources.list.d/morphis-ubuntu-anbox-support-xenial.list ']'
+ set +x

**Comment by morphis** [comment]
@Ambitie I don't really understand what you want you're doing or what kind of error you're reporting here. Please clarify or I need to close this issue.
