### ISSUE TITLE
error: snap "anbox" not found

### ISSUE THREAD

**Issue by rouelibre** [anbox/anbox#731]
Hi,

I'm trying to install Anbox, but the "anbox" snap doesn't seem to be available:

    $ sudo snap install --devmode --beta anbox
    error: snap "anbox" not found (at least in channel "beta")

    $ sudo snap install --devmode anbox
    error: snap "anbox" not found

    $ snap info anbox
    error: no snap found for "anbox"

    $ snap find anbox
    Name             Version  Developer  Notes    Summary
    anbox-installer  1        morphis    classic  Installer for the Android in a Box runtime environment

Best regards,
Olivier

**Comment by rouelibre** [comment]
P.S.

My distro is Lubuntu 16.04.

**Comment by Compuuuter** [comment]
Maybe you use 32 bit system?

**Comment by rouelibre** [comment]
Yes, I use a 32 bit system. Is it not compatible with Anbox?

**Comment by morphis** [comment]
@rouelibre Yes, Anbox does not support i386 (32-bit only systems). You need to have a 64 bit system.

**Comment by ndlarsen** [comment]
Same problem on 64bit.
You sure it hasn't benn pulled from the snap store?

**Comment by jmevel** [comment]
Actually it also doesn't work on the ARM 64 bit architecture. So only x64 seems to be supported
