### ISSUE TITLE
Anbox hangs when started

### ISSUE THREAD

**Issue by ndlarsen** [anbox/anbox#741]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

Possible duplication of: Anbox is not running after install. #738

2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`

Done

3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`

Done

4. Reproduce the error while debug logs enabled.

Done

5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info

[container.log](https://github.com/anbox/anbox/files/2064741/container.log)
[container-manager.log](https://github.com/anbox/anbox/files/2064742/container-manager.log)
[kernel.log](https://github.com/anbox/anbox/files/2064743/kernel.log)
[lxc-monitord.log](https://github.com/anbox/anbox/files/2064744/lxc-monitord.log)
[system.log](https://github.com/anbox/anbox/files/2064745/system.log)
[system-info.log](https://github.com/anbox/anbox/files/2064746/system-info.log)

6. ** Please paste the result of `anbox system-info` below:**

Attached as file above.

**Please describe your problem:**

When launching the application it hangs at the splash screen for a bit and the exits. The application cannot be launched afterwards. Processes are left in a sleeping state

**What were you expecting?:**

**Additional info:**

**Comment by morphis** [comment]
From system.log

```
06-02 06:32:27.398  7442  7442 F ProcessState: Binder driver could not be opened.  Terminating.
06-02 06:32:27.398  7447  7447 W /system/bin/mediaextractor: libminijail: allowing syscall: socketcall
06-02 06:32:27.398  7447  7447 W /system/bin/mediaextractor: libminijail: allowing syscall: writev
06-02 06:32:27.398  7447  7447 W /system/bin/mediaextractor: libminijail: allowing syscall: fcntl64
06-02 06:32:27.398  7447  7447 W /system/bin/mediaextractor: libminijail: logging seccomp filter failures
06-02 06:32:27.398  7447  7447 W ProcessState: Opening '/dev/binder' failed: Permission denied
06-02 06:32:27.398  7447  7447 F ProcessState: Binder driver could not be opened.  Terminating.
06-02 06:32:27.398  7447  7447 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 7447 (mediaextractor)
```

This is interesting. Can you double check that /dev/binder hash the mode `0666` on your host system?

Also, how large is the disk you have in your system and your rootfs is on?

**Comment by ndlarsen** [comment]
`ndlarsen@master:~$ ls -l /dev/binder 
crw-rw-rw- 1 root root 511, 0 Jun  4 15:37 /dev/binder

ndlarsen@master:~$ stat -c "%a %n" /dev/binder 
666 /dev/binder

ndlarsen@master:~$ df -h | grep /dev/sdb
/dev/sdb1       229G   50G  167G  23% /`

**Comment by morphis** [comment]
@ndlarsen Thanks. Need to read a bit more in detail through the logs to see if I find another reason why it fails to boot.

**Comment by morphis** [comment]
I think I found one problem which is eventually the cause of this bug and others. Will write a summary once I know more.

**Comment by morphis** [comment]
PR #747 might help fix this. I am testing it right now and once merged I will let you know so you can give this another try.

**Comment by morphis** [comment]
@ndlarsen Please try again with the latest snap from the edge channel. To ensure that everything is correctly setup do the following:

```
$ snap remove anbox
$ sudo rmmod binder_linux
$ sudo modprobe binder_linux
$ snap install --edge --devmode anbox
```

**Comment by morphis** [comment]
@ndlarsen I've added another new version of the snap to the edge channel (revision 108) which adds additional logging functionality at early container startup. Please try again and collect log files afterwards with `$ sudo anbox.collect-bug-info`

**Comment by ndlarsen** [comment]
Anbox seems to be starting fine now.

[console.log](https://github.com/anbox/anbox/files/2094006/console.log)
[container.log](https://github.com/anbox/anbox/files/2094007/container.log)
[container-manager.log](https://github.com/anbox/anbox/files/2094008/container-manager.log)
[kernel.log](https://github.com/anbox/anbox/files/2094009/kernel.log)
[system.log](https://github.com/anbox/anbox/files/2094010/system.log)
[system-info.log](https://github.com/anbox/anbox/files/2094011/system-info.log)

**Comment by hydrocat** [comment]
Shoud this issue be closed ?

**Comment by ndlarsen** [comment]
Closing as I am not using anbox anymore and due to inactivity on issue.
