### ISSUE TITLE
Failed to parse error while installing apk app via adb

### ISSUE THREAD

**Issue by hrvoojex** [anbox/anbox#76]
**Anbox release (`anbox version`) and system info (`anbox system-info`):**
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.8.0-46-generic (buildd@lcy01-16) (gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12) ) #49-Ubuntu SMP Fri Mar 31 13:57:14 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)

**Description of the problem:**
I tried to install apk file and got the error:
adb install GermaniaAndroid.apk
16585 KB/s (1709812 bytes in 0.100s)
Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl846309917.tmp/base.apk: AndroidManifest.xml]

**Expected:**
To be able to install an app

**Additional info:**

**Comment by PhoenixGR** [comment]
I tried to install few apps some works some doesnt with different error messages . I guess its cause anbox is in alpha state yet its natural.
