### ISSUE TITLE
Gives error when running $ sudo snap install --devmode --beta anbox

### ISSUE THREAD

**Issue by DAMSurvivor** [anbox/anbox#768]
I ran -- $ sudo snap install --devmode --beta anbox
And got this error -- 

error: cannot perform the following tasks:
- Setup snap "anbox" (92) security profiles (cannot setup apparmor for snap "anbox": cannot load apparmor profile "snap-update-ns.anbox": cannot load apparmor profile: exit status 1
apparmor_parser output:
AppArmor parser error for /var/lib/snapd/apparmor/profiles/snap-update-ns.anbox in /etc/apparmor.d/tunables/multiarch at line 17: Could not open 'tunables/multiarch.d'
)
- Setup snap "anbox" (92) security profiles (cannot load apparmor profile "snap-update-ns.anbox": cannot load apparmor profile: exit status 1
apparmor_parser output:
AppArmor parser error for /var/lib/snapd/apparmor/profiles/snap-update-ns.anbox in /etc/apparmor.d/tunables/multiarch at line 17: Could not open 'tunables/multiarch.d'
)

**Comment by morphis** [comment]
@DAMSurvivor That is not really a problem with Anbox itself but with snaps. Please ask for help on https://forum.snapcraft.io/ or report a bug on https://bugs.launchpad.net/snapd/+bugs

Thanks!
