### ISSUE TITLE
Trouble installing kernel modules

### ISSUE THREAD

**Issue by AliaYoung** [anbox/anbox#779]
I am trying to install Anbox kernel modules, and fail to get past installation on Ubuntu 18.04
via these command instructions: 

```
 $ sudo add-apt-repository ppa:morphis/anbox-support
 $ sudo apt update
 $ sudo apt install anbox-modules-dkms
```

It is stuck here, and just hangs:

```
$ sudo apt install anbox-modules-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
anbox-modules-dkms is already the newest version (10.1~20180523.2.bionic.c36965f).
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up anbox-modules-dkms (10.1~20180523.2.bionic.c36965f) ...
Removing old anbox-modules-ashmem-10.1~20180523.2.bionic.c36965f DKMS files...

-------- Uninstall Beginning --------
Module:  anbox-modules-ashmem
Version: 10.1~20180523.2.bionic.c36965f
Kernel:  4.15.0-23-generic (x86_64)
-------------------------------------

Status: This module version was INACTIVE for this kernel.
depmod...

DKMS: uninstall completed.

------------------------------
Deleting module version: 10.1~20180523.2.bionic.c36965f
completely from the DKMS tree.
------------------------------
Done.
Loading new anbox-modules-ashmem-10.1~20180523.2.bionic.c36965f DKMS files...
Building for 4.15.0-23-generic
Building for architecture x86_64
Building initial module for 4.15.0-23-generic
```

I read somewhere that I just need to enter my secure boot password and hit enter twice.  That didn't do it for me.  

Any help is appreciated!

Thanks!

**Comment by morphis** [comment]
@AliaYoung can you follow https://askubuntu.com/a/883359 to find out if secure boot is enabled in your case?

**Comment by morphis** [comment]
Also you can a manual `$ sudo dkms install anbox-modules-ashmem/10.1~20180523.2.bionic.c36965f` which may give you a bit better error message.

**Comment by AliaYoung** [comment]
Secure boot is enabled.  Still having this issue even when using suggested command.

**Comment by morphis** [comment]
I am not sure if enabled secure boot already gives problems for just building the DKMS modules. As you have to disable secure boot anyway to load the build modules can you do that (**its your decision though and be sure you know about the consequences before you do this!!**) and then try again installing the package?

**Comment by AliaYoung** [comment]
Secure boot was the culprit in the broken kernels.  I disabled secure boot to load & run the modules.  Perhaps this is obvious, but I'm a new user.  Thank you for your help.

**Comment by morphis** [comment]
You're welcome!
