### ISSUE TITLE
anbox: command not found (Arch Linux)

### ISSUE THREAD

**Issue by CalebQ42** [anbox/anbox#784]
I really want to use anbox from Arch Linux, but after I installed the snap, anbox won't run. When I manually run anbox or anbox.appmgr, the result is: `bash: anbox: command not found`

When I run sudo /snap/bin/anbox.collect-bug-info I get: `cannot locate the core or legacy core snap (current symlink missing?): No such file or directory`

It seems that anbox installed correctly and gets mounted properly, but won't work at all. I have installed the anbox dkms (from this aur: https://aur.archlinux.org/packages/anbox-modules-dkms-git/ ) and running `ls -1 /dev/{ashmem,binder}` returns properly. It really seems like everything is installed properly, things just aren't symlink or the executable location isn't added to PATH properly.

Running lsblk shows that the snap does get mounted: `loop1    7:1    0 371.7M  1 loop /snap/anbox/92`

**Comment by morphis** [comment]
@CalebQ42 This is really a problem with `snapd` rather than Anbox. Can you ask for help at `https://forum.snapcraft.io`?
