### ISSUE TITLE
why i can't install nbox on ubuntu 18.04?

### ISSUE THREAD

**Issue by ali-aryan** [anbox/anbox#785]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by morphis** [comment]
@ali-aryan Without you describe what you're doing or where this error message comes from there is no way we can help you. Please provide further details.

**Comment by livtin** [comment]
I am also having a problem with installation.  I have a desktop launcher BUT it doesn't get past the splash screen before crashing

[anbox-system-diagnostics-2018-07-02.zip](https://github.com/anbox/anbox/files/2156500/anbox-system-diagnostics-2018-07-02.zip)

**Comment by morphis** [comment]
Closing in favor of https://github.com/anbox/anbox/issues/788
