### ISSUE TITLE
What to study to contribute with Anbox?

### ISSUE THREAD

**Issue by Matheus-13** [anbox/anbox#793]
Hello everyone, i am a brazilian student of analysis and development of systems and the experiences that i have in programming are: the CS50 course and a book about python. I'm sorry for asking here. I would like to know everything i must learn to be able to contribute with Anbox, as i am a beginner, there is nothing better than asking more experienced people, thanks! - @morphis

**Comment by Matheus-13** [comment]
@morphis I currently study python, after C++. I'm a little interested in everything, backend and frontend, so I want to know all the areas involved to get an idea of what to learn.

**Comment by morphis** [comment]
@Matheus-13 The first I would look into is how Anbox itself is currently structure. The docs folder (https://github.com/anbox/anbox/tree/master/docs) has a few details about that. Afterwards I would start looking into the code and start working on a particular feature I am interested in. Picking one will give you an easier start as it keeps you quite focused. Any feature you would like to see added to Anbox?

**Comment by Sphinxs** [comment]
Get some [issue](https://github.com/anbox/anbox/issues) and try to fix it. As you already know C++ I assume you know deeply Object Oriented paradigma, how to build modular systens (classes) and how to compile using makefile, if you don't, study it. You can also study about debuging and some [gui](https://en.wikipedia.org/wiki/Graphical_user_interface) to get the concepts. This is what I'm studying to contribute to opensources projects in general (Não desista).

**Comment by Matheus-13** [comment]
Thanks for answers. @morphis It's hard to say why Anbox has not yet worked on my machine, so the best start would be to simply study the code and try to resolve the bugs that find? I still do not know C++, but learning it is enough to begin?
@Sphinxs I still do not know C++, but how will I work with programming, can not give up. I still have a lot to study, so it will take some time to start contributing.
