### ISSUE TITLE
Anobx doesn't start properly in Ubuntu because of illegal CPU instructions

### ISSUE THREAD

**Issue by Martinligabue** [anbox/anbox#802]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
Stack trace (most recent call last):
#2    Object "[", at (nil), in nil
#1    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7f5c7903b38f, in 
#0    Object "/snap/anbox/119/usr/bin/anbox", at 0x4a9985, in backward::SignalHandling::sig_handler(int, siginfo_t*, void*)
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault (core dumped)


```

**Please describe your problem:**
Anbox does not get over startup screen

**What were you expecting?:**
That Anbox would start

**Additional info:**
I can't attach the tar file, I forwarded it via Telegram to t.me/morphis because I didn't know what to do

**Comment by Martinligabue** [comment]
[archive.zip](https://github.com/anbox/anbox/files/2172546/archive.zip)

**Comment by morphis** [comment]
@Martinligabue Which CPU do you have in your computer?

The actual problem here is an instructions which Android uses and which is not supported by your CPU:

`07-06 19:49:33.661    38    38 F libc    : Fatal signal 4 (SIGILL), code 2, fault addr 0xf6f9dea6 in tid 38 (audioserver)`

Unless somebody goes down the road to find out which particular instruction that is and what we need to do to avoid Android using it, there is not much we can do to help you right now.

**Comment by Martinligabue** [comment]
Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz

**Comment by morphis** [comment]
The E8400 is from 2008. See https://ark.intel.com/de/products/33910/Intel-Core2-Duo-Processor-E8400-6M-Cache-3_00-GHz-1333-MHz-FSB

**Comment by morphis** [comment]
Closing this as there is nothing we can do right now. There will be extended warning in Anbox in the near future to make this problem more visible to our users.

**Comment by probonopd** [comment]
> Intel(R) Core(TM)2 Duo CPU E8400 @ 3.00GHz

Is this CPU supported? If not, what is missing? It reports 

```
The CPU of your computer (Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz) does not support all
features Anbox requires.
It is missing support for the following features: SSE 4.2
You can for example find more information about SSE
here https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions
```

Can Anbox be modified so that it will not require SSE 4.2?
