### ISSUE TITLE
anbox-modules-dkms-git build error

### ISSUE THREAD

**Issue by sheldonmaschmeyer** [anbox/anbox#810]
I had uninstalled anbox through AUR to reinstall using snapd after not being able to connect apps to the internet. Now, trying to reinstall anbox-modules-dkms-git, getting an error. Any advice appreciated.
 
/tmp/pamac-build-sheldon/anbox-git/src/anbox/external/backward-cpp/backward.hpp:1483:11: error: switch missing default case [-Werror=switch-default]
    switch (dwarf_tag(die)) {
           ^
/tmp/pamac-build-sheldon/anbox-git/src/anbox/external/backward-cpp/backward.hpp: In static member function ‘static Dwarf_Die* backward::TraceResolverLinuxImpl<backward::trace_resolver_tag::libdw>::find_fundie_by_pc(Dwarf_Die*, Dwarf_Addr, Dwarf_Die*)’:
/tmp/pamac-build-sheldon/anbox-git/src/anbox/external/backward-cpp/backward.hpp:1559:11: error: switch missing default case [-Werror=switch-default]
    switch (dwarf_tag(die)) {
           ^
cc1plus: all warnings being treated as errors
make[2]: *** [external/backward-cpp/CMakeFiles/backward_object.dir/build.make:63: external/backward-cpp/CMakeFiles/backward_object.dir/backward.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1766: external/backward-cpp/CMakeFiles/backward_object.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by morphis** [comment]
@sheldonmaschmeyer You're message is a bit confusing as you say you're building `anbox-modules-dkms-git` but your error message actually comes from building `anbox`. However the build problem for Anbox should be fixed once https://github.com/anbox/anbox/pull/809 goes in.
