### ISSUE TITLE
E: Unable to locate package anbox-modules-dkms

### ISSUE THREAD

**Issue by Fratacchione** [anbox/anbox#812]
No matter what I do, whenever I try to `sudo apt install -y anbox-modules-dkms`, I always get the error:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package anbox-modules-dkms
```
I did `sudo add-apt-repository -y 'ppa:morphis/anbox-support' before`, and `sudo apt update` right after, since someone with my same problem said that this would fix it. But for me the problem remains, and won't let me proceed further. Anbox is installed, but I need these kernel modules to run it, since for now it crashes after showing the "_Starting..._" window, for obvious reasons.

I'm on Xubuntu 17.10 FYI.

**Comment by morphis** [comment]
@Fratacchione The problem here is that the PPA doesn't support 17.10. It only supports Ubuntu 16.04 and 18.04. You have two options:

1. Upgrade to Ubuntu 18.04 (which you should do anyway given the limited support 17.10 gets; expires this month)
2. Manually download the package from the PPA and install it via `sudo dpkg -i ...`

Hope this helps!

**Comment by morphis** [comment]
@Fratacchione You can get the package from https://launchpad.net/~morphis/+archive/ubuntu/anbox-support/+packages

The following steps should get you started:

```
$ wget https://launchpad.net/~morphis/+archive/ubuntu/anbox-support/+files/anbox-modules-dkms_12_all.deb
$ sudo dpkg -i anbox-modules-dkms_12_all.deb
```

**Comment by Navan0** [comment]
@morphis `wget https://launchpad.net/~morphis/+archive/ubuntu/anbox-support/+files/anbox-modules-dkms_12_all.deb
--2019-11-18 15:56:32--  https://launchpad.net/~morphis/+archive/ubuntu/anbox-support/+files/anbox-modules-dkms_12_all.deb
Resolving launchpad.net (launchpad.net)... 91.189.89.223, 91.189.89.222, 2001:67c:1560:8003::8003, ...
Connecting to launchpad.net (launchpad.net)|91.189.89.223|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-11-18 15:56:34 ERROR 404: Not Found.`

**Comment by abhinavsri000** [comment]
--2020-04-27 16:16:51--  https://launchpad.net/~morphis/+archive/ubuntu/anbox-support/+files/anbox-modules-dkms_12_all.deb
Resolving launchpad.net (launchpad.net)... 91.189.89.222, 91.189.89.223, 2001:67c:1560:8003::8003, ...
Connecting to launchpad.net (launchpad.net)|91.189.89.222|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-27 16:16:53 ERROR 404: Not Found.

**Comment by Bennitenni111** [comment]
> --2020-04-27 16:16:51-- https://launchpad.net/~morphis/+archive/ubuntu/anbox-support/+files/anbox-modules-dkms_12_all.deb
> Resolving launchpad.net (launchpad.net)... 91.189.89.222, 91.189.89.223, 2001:67c:1560:8003::8003, ...
> Connecting to launchpad.net (launchpad.net)|91.189.89.222|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2020-04-27 16:16:53 ERROR 404: Not Found.

https://pkgs.org/download/anbox
Just found it
Replace your link from those downloads
TRyna check!

**Comment by Bennitenni111** [comment]
> --2020-04-27 16:16:51-- https://launchpad.net/~morphis/+archive/ubuntu/anbox-support/+files/anbox-modules-dkms_12_all.deb
> Resolving launchpad.net (launchpad.net)... 91.189.89.222, 91.189.89.223, 2001:67c:1560:8003::8003, ...
> Connecting to launchpad.net (launchpad.net)|91.189.89.222|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2020-04-27 16:16:53 ERROR 404: Not FIf cant

> --2020-04-27 16:16:51-- https://launchpad.net/~morphis/+archive/ubuntu/anbox-support/+files/anbox-modules-dkms_12_all.deb
> Resolving launchpad.net (launchpad.net)... 91.189.89.222, 91.189.89.223, 2001:67c:1560:8003::8003, ...
> Connecting to launchpad.net (launchpad.net)|91.189.89.222|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2020-04-27 16:16:53 ERROR 404: Not Found.


http://ftp.br.debian.org/debian/pool/contrib/a/anbox/anbox_0.0~git20190124-1_amd64.deb
If can't find try that
--

**Comment by vikasatverma** [comment]
wget http://ftp.br.debian.org/debian/pool/contrib/a/anbox/anbox_0.0~git20190124-1_amd64.deb
--2020-09-23 10:52:05--  http://ftp.br.debian.org/debian/pool/contrib/a/anbox/anbox_0.0~git20190124-1_amd64.deb
Resolving ftp.br.debian.org (ftp.br.debian.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘ftp.br.debian.org’

**Comment by fortunemadoda** [comment]
i m getting errors when perfoming this step 
sudo dpkg -i anbox_0.0~git20190124-1_amd64.deb 


I am getting this error
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
Errors were encountered while processing: anbox

**Comment by husseinbasha** [comment]
me to @fortunemadoda i hope someone will help us soon

**Comment by alvinbengeorge** [comment]
> i m getting errors when perfoming this step
> sudo dpkg -i anbox_0.0~git20190124-1_amd64.deb
> 
> I am getting this error
> Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
> Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
> Processing triggers for mime-support (3.64ubuntu1) ...
> Processing triggers for man-db (2.9.1-1) ...
> Errors were encountered while processing: anbox

I dont think we have a proper link

**Comment by qwertycody** [comment]
I'm having this same issue - looking for resolution right now but here is what I see so far.

```
sudo apt update 
E: The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

```
sudo apt install linux-headers-generic anbox-modules-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package anbox-modules-dkms
```


![image](https://user-images.githubusercontent.com/4968312/122571442-bb989c00-d01a-11eb-9ccb-2680180aee69.png)

**Comment by qwertycody** [comment]
Just an update back on this - I found a solution that works for me and I submitted it as a issue at the below link for the devs to update the anbox documentation:
- https://github.com/anbox/anbox/issues/1836

In the above link I detail what needs to be done to fix the issue and get the anbox-modules installed - I am also posting them here for convenience.

### **Two Potential Solutions:**
- Solution 1:
  - Revise the "Install Anbox" documentation above to no longer point to the child link and instead directly link to (https://github.com/anbox/anbox-modules#readme) where it contains installation steps to directly clone, build, and install locally
- Solution 2:
  - Revise the "Install Kernel Modules" page to reflect the below commands and add variations for different Linxu Distributions 
  - Example:
    - sudo apt install git / sudo yum install git
    - sudo apt install dkms / sudo yum install dkms
    - sudo apt install linux-headers-generic / sudo yum install kernel-devel
      - Package name for linux-headers varies on different distributions, e.g. linux-headers-generic (Ubuntu), linux-headers-amd64 (Debian), kernel-devel (CentOS, Fedora), kernel-default-devel (openSUSE).
    - mkdir -p "$HOME/Documents/GitHub/anbox-modules"
    - git clone "https://github.com/anbox/anbox-modules.git" "$HOME/Documents/GitHub/anbox-modules"
    - cd "$HOME/Documents/GitHub/anbox-modules"
    - chmod 700 ./INSTALL.sh
    - ./INSTALL.sh

**Comment by GabrielKuka** [comment]
> Just an update back on this - I found a solution that works for me and I submitted it as a issue at the below link for the devs to update the anbox documentation:
> 
> * [Quick Document Revision Fix - Update Kernel Module Documentation #1836](https://github.com/anbox/anbox/issues/1836)
> 
> In the above link I detail what needs to be done to fix the issue and get the anbox-modules installed - I am also posting them here for convenience.
> 
> ### **Two Potential Solutions:**
> * Solution 1:
>   
>   * Revise the "Install Anbox" documentation above to no longer point to the child link and instead directly link to (https://github.com/anbox/anbox-modules#readme) where it contains installation steps to directly clone, build, and install locally
> * Solution 2:
>   
>   * Revise the "Install Kernel Modules" page to reflect the below commands and add variations for different Linxu Distributions
>   * Example:
>     
>     * sudo apt install git / sudo yum install git
>     * sudo apt install dkms / sudo yum install dkms
>     * sudo apt install linux-headers-generic / sudo yum install kernel-devel
>       
>       * Package name for linux-headers varies on different distributions, e.g. linux-headers-generic (Ubuntu), linux-headers-amd64 (Debian), kernel-devel (CentOS, Fedora), kernel-default-devel (openSUSE).
>     * mkdir -p "$HOME/Documents/GitHub/anbox-modules"
>     * git clone "https://github.com/anbox/anbox-modules.git" "$HOME/Documents/GitHub/anbox-modules"
>     * cd "$HOME/Documents/GitHub/anbox-modules"
>     * chmod 700 ./INSTALL.sh
>     * ./INSTALL.sh

I followed all of these steps but in the end I get this:
![image](https://user-images.githubusercontent.com/17888328/157340071-d2fa6c41-950e-4867-85e9-fc49f078c70a.png)

**Comment by Fuseteam** [comment]
You no longer need the modules since 2019 on on debian nor ubuntu

**Comment by Alex-724** [comment]
> > --2020-04-27 16:16:51-- https://launchpad.net/~morphis/+archive/ubuntu/anbox-support/+files/anbox-modules-dkms_12_all.deb
> > Resolving launchpad.net (launchpad.net)... 91.189.89.222, 91.189.89.223, 2001:67c:1560:8003::8003, ...
> > Connecting to launchpad.net (launchpad.net)|91.189.89.222|:443... connected.
> > HTTP request sent, awaiting response... 404 Not Found
> > 2020-04-27 16:16:53 ERROR 404: Not FIf cant
> 
> > --2020-04-27 16:16:51-- https://launchpad.net/~morphis/+archive/ubuntu/anbox-support/+files/anbox-modules-dkms_12_all.deb
> > Resolving launchpad.net (launchpad.net)... 91.189.89.222, 91.189.89.223, 2001:67c:1560:8003::8003, ...
> > Connecting to launchpad.net (launchpad.net)|91.189.89.222|:443... connected.
> > HTTP request sent, awaiting response... 404 Not Found
> > 2020-04-27 16:16:53 ERROR 404: Not Found.
> 
> ## http://ftp.br.debian.org/debian/pool/contrib/a/anbox/anbox_0.0~git20190124-1_amd64.deb
> If can't find try that
> 
> cmd wget http://ftp.br.debian.org/debian/pool/contrib/a/anbox/anbox_0.0~git20190124-1_amd64.deb sudo dpkg -i anbox_0.0~git20190124-1_amd64.deb enjoy budy

Thank you
