### ISSUE TITLE
bug report issue

### ISSUE THREAD

**Issue by raylore2000** [anbox/anbox#818]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug lo
[container.log](https://github.com/anbox/anbox/files/2199650/container.log)
[container-manager.log](https://github.com/anbox/anbox/files/2199651/container-manager.log)
[kernel.log](https://github.com/anbox/anbox/files/2199652/kernel.log)
[lxc-monitord.log](https://github.com/anbox/anbox/files/2199653/lxc-monitord.log)
[system.log](https://github.com/anbox/anbox/files/2199654/system.log)
[system-info.log](https://github.com/anbox/anbox/files/2199655/system-info.log)

gs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by raylore2000** [comment]
i hope i did ok. maybe you guys can help me

**Comment by morphis** [comment]
@raylore2000 You missed to describe your actual problem. Without that there is no way to help. Please answer all questions like "Please describe your problem". Once you did I will reopen the bug.
