### ISSUE TITLE
need to support aarch64

### ISSUE THREAD

**Issue by westlaker** [anbox/anbox#833]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**
root@lcds-mb07:/share/anbox-work# lunch

You're building on Linux

Lunch menu... pick a combo:
     1. aosp_arm-eng
     2. aosp_arm64-eng
     3. aosp_mips-eng
     4. aosp_mips64-eng
     5. aosp_x86-eng
     6. aosp_x86_64-eng
     7. anbox_x86_64-userdebug
     8. anbox_armv7a_neon-userdebug
     9. anbox_arm64-userdebug

Which would you like? [aosp_arm-eng] anbox_arm64-userdebug
build/core/envsetup.mk:89: *** Unable to determine HOST_ARCH from uname -sm: Linux aarch64!.  Stop.

** Don't have a product spec for: 'anbox_arm64'
** Do you have the right repo manifest?

root@lcds-mb07:/share/anbox-work# uname -sm
Linux aarch64

**What were you expecting?:**

aarch64 should be treated as arm64

**Additional info:**

**Comment by morphis** [comment]
Building Android on arm64/aarch64 is not supported by the upstream Android project so nothing we can fix in Anbox. You have to build on x86_64.

**Comment by westlaker** [comment]
ok now I moved to x86 to compile:

lunch

You're building on Linux

Lunch menu... pick a combo:
     1. aosp_arm-eng
     2. aosp_arm64-eng
     3. aosp_mips-eng
     4. aosp_mips64-eng
     5. aosp_x86-eng
     6. aosp_x86_64-eng
     7. anbox_x86_64-userdebug
     8. anbox_armv7a_neon-userdebug
     9. anbox_arm64-userdebug

Which would you like? [aosp_arm-eng] anbox_arm64-userdebug

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=7.1.1
TARGET_PRODUCT=anbox_arm64
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=
TARGET_2ND_ARCH_VARIANT=
TARGET_2ND_CPU_VARIANT=
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.4.0-87-generic-x86_64-with-Ubuntu-16.04-xenial
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=N6F26Q
OUT_DIR=out

then do make -j8, then got the error below.
...

[ 72% 24539/34074] target SharedLib: libstagefright_soft_avcdec (out/target/product/arm64/obj/SHARED_LIBRARIES/libstagefright_soft_avcdec_intermediates/LINKED/libstagefright_soft_avcdec.so)
FAILED: /bin/bash -c "prebuilts/clang/host/linux-x86/clang-2690385/bin/clang++ -nostdlib -Wl,-soname,libstagefright_soft_avcdec.so -Wl,--gc-sections -shared  -Lout/target/product/arm64/obj/lib out/target/product/arm64/obj/lib/crtbegin_so.o      out/target/product/arm64/obj/SHARED_LIBRARIES/libstagefright_soft_avcdec_intermediates/SoftAVCDec.o               -Wl,--whole-archive   -Wl,--no-whole-archive   out/target/product/arm64/obj/STATIC_LIBRARIES/libavcdec_intermediates/libavcdec.a out/target/product/arm64/obj/STATIC_LIBRARIES/libcompiler_rt-extras_intermediates/libcompiler_rt-extras.a   prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/../lib/gcc/aarch64-linux-android/4.9/../../../../aarch64-linux-android/lib/../lib64/libatomic.a prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/../lib/gcc/aarch64-linux-android/4.9/libgcc.a -lstagefright -lstagefright_omx -lstagefright_foundation -lutils -llog -lc++ -ldl -ldl -lc -lm  -o out/target/product/arm64/obj/SHARED_LIBRARIES/libstagefright_soft_avcdec_intermediates/LINKED/libstagefright_soft_avcdec.so   -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--build-id=md5 -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,-maarch64linux -Wl,--hash-style=gnu -Wl,--fix-cortex-a53-843419 -fuse-ld=gold -Wl,--icf=safe -Wl,--no-undefined-version -Wl,--allow-shlib-undefined    -target aarch64-linux-android -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin   -Wl,-Bsymbolic -Wl,--no-undefined out/target/product/arm64/obj/lib/crtend_so.o"
external/libavc/decoder/arm/ih264d_function_selector.c:67: error: undefined reference to 'ih264d_init_function_ptr_av8'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
[ 72% 24539/34074] target  C++: libstagefright_soft_avcenc <= frameworks/av/media/libstagefright/codecs/avcenc/SoftAVCEnc.cpp
ninja: build stopped: subcommand failed.
build/core/ninja.mk:148: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1

#### make failed to build some targets (44:50 (mm:ss)) ####

What I am missing? 

thanks

**Comment by morphis** [comment]
@westlaker Nothing. Nobody really enabled the arm64 build for Anbox yet so build errors like the one above are expected. If you find a solution please provide a PR with the fix.

**Comment by westlaker** [comment]
sure, I have done it with Linaro way for arm64, generating files like system.img and ramdisk.img, how to use those files to generate anbox container?

**Comment by morphis** [comment]
@westlaker You need to stick to the Anbox Android tree to generate a Android image suitable for anbox. Once you have completed the Android build you can generate the squashfs image for Anbox via the create-package.sh script in the Anbox repository. See https://github.com/anbox/anbox/blob/master/docs/build-android.md for details

**Comment by wwhurley** [comment]
Canonical has a [blog post](https://blog.ubuntu.com/2018/11/29/running-android-in-the-cloud-with-amazon-ec2-a1-instances) about running Anbox on an AWS A1 EC2 instance, which are ARM64. They don't provide a whole lot of detail. I've reached out to them to try and get more, but if folks here have suggestions I'd appreciate that, as well.

**Comment by wfchair** [comment]
@wwhurley Did you get more info about running Anbox on ARM64 ? Would you like to share?

**Comment by wwhurley** [comment]
Unfortunately not. I haven't been able to successfully get the project to run on the new AWS ARM EC2 instances. I need to check, but the last time I tried there wasn't a snap for that environment.

**Comment by brianpl** [comment]
I have an ARM64 server that I'll be testing on, but I'm hung up on other projects. Not a great venue for asking this, but what projects do you build to test Anbox? I had planned on using Tensorflow's Demo, but it's been difficult...

**Comment by brianpl** [comment]
s/build/run

**Comment by HarleyPato** [comment]
Is it possible to build on arm64 ubuntu 18.04? I get this error message when trying to cross-compile with the cross-compile-chroot.sh:

Target architecture: arm64
Target machine: aarch64-linux-gnu
Using PKG_CONFIG_PATH: /root/.cache/anbox-arm64-chroot-vivid/usr/lib/pkgconfig:/root/.cache/anbox-arm64-chroot-vivid/usr/lib/aarch64-linux-gnu/pkgconfig
Using PKG_CONFIG_EXECUTABLE: 
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:1 (project):
  The CMAKE_C_COMPILER:

    /usr/bin/aarch64-linux-gnu-gcc-4.9

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:1 (project):
  The CMAKE_CXX_COMPILER:

    /usr/bin/aarch64-linux-gnu-g++-4.9

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!

Any idea? Greetings.

**Comment by wfchair** [comment]
edit build/core/combo/arch/arm64/armv8-a.mk to add the following at beginning:
ARCH_ARM_HAVE_NEON              := true

**Comment by HarleyPato** [comment]
Hi.

I have built an ARM64 WIP anbox snap, so if you guys want to test it:

https://launchpad.net/~patosublime/+snap/anbox-4-arm64/+build/450757

Please, all the issues you have, please, report them and tell me.

Greetings.

**Comment by wwhurley** [comment]
Maybe a silly question, @HarleyPato, but how do you install a snap from Launchpad?

**Comment by HarleyPato** [comment]
@wwhurley use this snap instead:

 https://launchpad.net/~patosublime/+snap/anbox-4-arm64/+build/454315

In this case, you gotta use devmode:

sudo snap install --devmode anbox_4-3e66f96_arm64.snap

If you have any issues please report them, will try to solve them.

If you have any problems, as I said, report them and will try to troubleshoot.

Greetings !

**Comment by wwhurley** [comment]
I installed the snap on a A1 EC2 instance and ran `anbox.appmgr` and received the following error:

```
dbus[7358]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Stack trace (most recent call last):
#0     Object "/lib/aarch64-linux-gnu/libc-2.27.so", at 0xffffad4cd4d8 in raise
Aborted (Signal sent by tkill() 7358 1000)
Aborted (core dumped)
```

**Comment by HarleyPato** [comment]
@wwhurley  aahh...

That's a bug in libSDL2 in Ubuntu 18.04, so nothing I can fix since it's not really my problem (anbox make use of dbus).

You can try this, tho: DBUS_FATAL_WARNINGS=0

That will solve the "aborted (core dumped) issue, but not the former (assertion path != NULL).

Try this snap I just built in Xenial. If it doesn't work in bionic, then you have to downgrade to 16.04:

https://code.launchpad.net/~patosublime/+snap/anbox-2-arm64/+build/455739

As always: sudo snap install --devmode anbox_4-45b6472_arm64.snap 

Greetings !

**Comment by wwhurley** [comment]
I got an error from protobuf:

```
~$ anbox.appmgr 
Stack trace (most recent call last):
#3    Object "/lib/aarch64-linux-gnu/ld-2.23.so", at 0xffffb8f1bb5f, in 
#2    Object "/snap/anbox/x2/usr/lib/aarch64-linux-gnu/libmirprotobuf.so.3", at 0xffffb6de6553, in 
#1    Object "/snap/anbox/x2/usr/lib/aarch64-linux-gnu/libprotobuf-lite.so.9.0.1", at 0xffffb89d7743, in google::protobuf::internal::OnShutdown(void (*)())
#0    Object "/snap/anbox/x2/usr/lib/aarch64-linux-gnu/libprotobuf-lite.so.9.0.1", at 0xffffb89d73f0, in google::protobuf::internal::Mutex::Lock()
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault (core dumped)
```

Let me try with Xenial.

**Comment by HarleyPato** [comment]
@wwhurley You didn't remove the former anbox installation (as I see anbox's version is "x2" instead of "x1").

Try removing the snap (actually remove both):

snap remove anbox

And reinstall the snap again:

snap install --devmode anbox_4-45b6472_arm64.snap

Greetings !

**Comment by wwhurley** [comment]
The link you sent me goes to this project: https://launchpad.net/~patosublime/+snap/anbox-2-arm64. Should I be using https://launchpad.net/~patosublime/+snap/anbox-arm64 or https://launchpad.net/~patosublime/+snap/anbox-4-arm64 instead?

**Comment by HarleyPato** [comment]
Pfff....

Sorry. Use this one: 
https://code.launchpad.net/~patosublime/+snap/anbox-2-arm64/+build/455739

Greetings

**Comment by wwhurley** [comment]
After a bunch of trial and error I finally hit upon a build of Armbian I could get snapd installed and running locally. Unfortunately I got the following error:

```
$ /snap/bin/anbox.appmgr
[2019-02-18 17:16:52] [daemon.ccp:61@Run] Application manager service is not running yet
```
I found references to that error in #781 and some folks saying they're getting the same error, though it is marked as Closed.

**Comment by sshock** [comment]
I tried both of these snaps from HarleyPato:
https://code.launchpad.net/~patosublime/+snap/anbox-2-arm64/+build/455739
https://code.launchpad.net/~patosublime/+snap/anbox-2-arm64/+build/467429

But I ran into https://github.com/anbox/anbox/issues/833#issuecomment-462401216

**Comment by sshock** [comment]
I built the latest code from @HarleyPato 's fork of anbox and am now seeing the libSDL2 bug he mentioned I think:

```
ubuntu@myhost:~$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
Stack trace (most recent call last):
#0    Object "/snap/anbox/x1/usr/lib/aarch64-linux-gnu/libSDL2-2.0.so.0.8.0", at 0xffff8d403608, in 
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault (core dumped)
```

**Comment by totsuan** [comment]
Hi, @HarleyPato

I tried to your some anbox project.
https://github.com/HarleyPato/anbox-arm64
https://code.launchpad.net/~patosublime/+snap/anbox-2-arm64/+build/455739

chose aarch64 machines,
* RaspberryPI 3B+ (bionic only)
* rockpro64
* A1 EC2 instance

bud, I failed to all challenge....

Could you provide an machines or environment example please?

regards

**Comment by kevinatuscn** [comment]
Anyone successfully make anbox working with arm64/aarch64?

**Comment by aiminickwong** [comment]
@westlaker Westlaker

**Add the following content in the first line to solve your problem**

```
diff --git a/build/core/combo/arch/arm64/armv8-a.mk b/build/core/combo/arch/arm64/armv8-a.mk
index 5e27e5a..56c8abe 100644
--- a/build/core/combo/arch/arm64/armv8-a.mk
+++ b/build/core/combo/arch/arm64/armv8-a.mk
@@ -1,3 +1,5 @@
+ARCH_ARM_HAVE_NEON              := true
+
 ifneq (,$(filter cortex-a53,$(TARGET_$(combo_2nd_arch_prefix)CPU_VARIANT)))
        arch_variant_cflags := -mcpu=cortex-a53
 else
```

**Comment by shensjh** [comment]
> ARCH_ARM_HAVE_NEON := true

thanks
 with this change, make anbox_arm64-userdebug  completed successfully

**Comment by Frankdwu** [comment]
I could start anbox on ARM64 devices with anbox_arm64-userdebug option.
But there are some problems:
1. No libmediaplayerservice
Then I added MEDIASERVER_MULTILIB :=64 in the makefile. 
mediaplayer service could be up and running
2. No mediacodec library  in the android.img  (build flavor: anbox_arm64-userdebug ) 
I checked the media codec makefile, it has "LOCAL_32_BIT_ONLY := true"
So does that mean currently mediacodec service could not be supported and running in ARM64 only system, right?
It looks like mediaplayerback service has the similar problem.

Without above libraries, my webview is always crashing when entering one web url.

**Comment by shensjh** [comment]
> I could start anbox on ARM64 devices with anbox_arm64-userdebug option.
> But there are some problems:
> 
> 1. No libmediaplayerservice  in the android.img  (build flavor: anbox_arm64-userdebug )
>    Then I added MEDIASERVER_MULTILIB :=64 in the makefile.
>    mediaplayer service could be up and running
> 2. No mediacodec library  in the android.img  (build flavor: anbox_arm64-userdebug )
>    I checked the media codec makefile, it has "LOCAL_32_BIT_ONLY := true"
>    So does that mean currently mediacodec service could not be supported and running in ARM64 only system, right?
>    It looks like mediaplayerback service has the similar problem.
> 
> Without above libraries, my webview is always crashing when entering one web url.

so, what did you do with this issue:

`-dbus[7358]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Stack trace (most recent call last):
#0     Object "/lib/aarch64-linux-gnu/libc-2.27.so", at 0xffffad4cd4d8 in raise
Aborted (Signal sent by tkill() 7358 1000)
Aborted (core dumped)`

-

**Comment by Frankdwu** [comment]
> > I could start anbox on ARM64 devices with anbox_arm64-userdebug option.
> > But there are some problems:
> > 
> > 1. No libmediaplayerservice  in the android.img  (build flavor: anbox_arm64-userdebug )
> >    Then I added MEDIASERVER_MULTILIB :=64 in the makefile.
> >    mediaplayer service could be up and running
> > 2. No mediacodec library  in the android.img  (build flavor: anbox_arm64-userdebug )
> >    I checked the media codec makefile, it has "LOCAL_32_BIT_ONLY := true"
> >    So does that mean currently mediacodec service could not be supported and running in ARM64 only system, right?
> >    It looks like mediaplayerback service has the similar problem.
> > 
> > Without above libraries, my webview is always crashing when entering one web url.
> 
> so, what did you do with this issue:
> 
> `-dbus[7358]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
> This is normally a bug in some application using the D-Bus library.
> 
> D-Bus not built with -rdynamic so unable to print a backtrace
> Stack trace (most recent call last):
> #0 Object "/lib/aarch64-linux-gnu/libc-2.27.so", at 0xffffad4cd4d8 in raise
> Aborted (Signal sent by tkill() 7358 1000)
> Aborted (core dumped)`

What android.img are you using?
I am using the "android.img" image from https://drive.google.com/open?id=1Hl8mWhVpciMJfNFdOUFqdJMy9owzQ-E0

**Comment by shensjh** [comment]
> > > I could start anbox on ARM64 devices with anbox_arm64-userdebug option.
> > > But there are some problems:
> > > 
> > > 1. No libmediaplayerservice  in the android.img  (build flavor: anbox_arm64-userdebug )
> > >    Then I added MEDIASERVER_MULTILIB :=64 in the makefile.
> > >    mediaplayer service could be up and running
> > > 2. No mediacodec library  in the android.img  (build flavor: anbox_arm64-userdebug )
> > >    I checked the media codec makefile, it has "LOCAL_32_BIT_ONLY := true"
> > >    So does that mean currently mediacodec service could not be supported and running in ARM64 only system, right?
> > >    It looks like mediaplayerback service has the similar problem.
> > > 
> > > Without above libraries, my webview is always crashing when entering one web url.
> > 
> > 
> > so, what did you do with this issue:
> > `-dbus[7358]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
> > This is normally a bug in some application using the D-Bus library.
> > D-Bus not built with -rdynamic so unable to print a backtrace
> > Stack trace (most recent call last):
> > #0 Object "/lib/aarch64-linux-gnu/libc-2.27.so", at 0xffffad4cd4d8 in raise
> > Aborted (Signal sent by tkill() 7358 1000)
> > Aborted (core dumped)`
> 
> What android.img are you using?
> I am using the "android.img" image from https://drive.google.com/open?id=1Hl8mWhVpciMJfNFdOUFqdJMy9owzQ-E0


no, What i used is :https://github.com/anbox/anbox/blob/master/docs/build-android.md

i also found that No libmediaplayerservice & mediaservice & mediacodec in the android.img .
what have you done to this issue?
