### ISSUE TITLE
Anbox connects to Google/Unknown DNS Servers

### ISSUE THREAD

**Issue by LynuxDevz** [anbox/anbox#839]
While browsing the internet with anbox, browserleaks detects that the DNS server leaks (passes trough) Google's servers, today, I updated anbox and ran the test again, and found out that besides Google's servers, the DNS leaked trough some servers in Tulsa, OK, labeled "unknown", this could be a potential privacy/security issue. Is there a way to avoid this, besides from using a VPN?

**Comment by morphis** [comment]
We only hard code the Google DNS server 8..8.8.8 here https://github.com/anbox/anbox/blob/master/src/anbox/container/lxc_container.cpp#L47 at the moment but no other nameserver. If you prefer we can make the DNS server configurable.

**Comment by morphis** [comment]
You know can change the DNS server used by the Android container via

`$ snap set anbox container.network.dns 1.2.3.4`

See https://docs.anbox.io/userguide/advanced/network_configuration.html for more details.

**Comment by tribbloid** [comment]
this is not practical, most net work automatically detect dns server
the more appropriate way is to set up a local dns forwarder that anbox can query
