### ISSUE TITLE
hardcoded network in anbox-bridge.sh script

### ISSUE THREAD

**Issue by htc1977** [anbox/anbox#840]
My network interferes with the hardcoded network in anbox-bridge.sh.
As I'm using snap, changing the script isn't possible, so I'd like to configure this network somewhere else.

**Comment by morphis** [comment]
That is doable. Will propose a change to implement that real soon.Am 01.08.2018 17:12 schrieb htc1977 <notifications@github.com>:My network interferes with the hardcoded network in anbox-bridge.sh.
As I'm using snap, changing the script isn't possible, so I'd like to configure this network somewhere else.

**Comment by morphis** [comment]
Not yet fixed as the bridge configuration can be changed but the Android container is without network access afterwards as it hard codes the configuration still. See https://github.com/anbox/anbox/blob/master/src/anbox/container/lxc_container.cpp#L44

**Comment by htc1977** [comment]
any news or a roadmap, when configuring networks will be fixed/added?

**Comment by morphis** [comment]
@htc1977 Not yet. I have initially code but didn't come yet to the point on finishing it.

**Comment by htc1977** [comment]
ok, ty for the feedback.
Please send me a note, when you did, bc I'd like to use and/or test anbox, which I can't atm. ;-)
