### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by Mieske72** [anbox/anbox#845]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

Won't start on Mint 18.3 or 19. Shows the startup gui, but then disappears after a few moments

**Comment by morphis** [comment]
@Mieske72 Can you please follow the steps given in the bug report and provide all information you're asked for. Without we can't help you.

**Comment by morphis** [comment]
Closing as no further information was provided.
