### ISSUE TITLE
Anbox not starting (cannot perform readlinkat())

### ISSUE THREAD

**Issue by meXc** [anbox/anbox#847]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
```
error: cannot perform the following tasks:
- Run configure hook of "anbox" snap (snap "anbox" has no "configure" hook)
```
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
```
sudo /snap/bin/anbox.collect-bug-info `
```

6. ** Please paste the result of `anbox system-info` below:**
```
cannot perform readlinkat() on the mount namespace file descriptor of the init process: Permission denied

```

**Please describe your problem:**

After installing the kernelmodules (using the ppa on ubuntu bionic )
and anbox itself (using snap) anbox refuses to start up anything.

```
snap    2.34.2+18.04
snapd   2.34.2+18.04
series  16
ubuntu  18.04
kernel  4.15.0-29-generic
```

**What were you expecting?:**

anbox running

**Additional info:**

followed [https://github.com/anbox/anbox/blob/master/docs/install.md](url)

**Comment by morphis** [comment]
Thanks for for reporting the bug. The issue you see is a problem with the snapd component and nothing we can fix in Anbox. Can you ask at https://forum.snapcraft.io for help on this?
