### ISSUE TITLE
Anbox AUR install on Archlinux Error

### ISSUE THREAD

**Issue by emptycpp** [anbox/anbox#848]
To install this package from AUR, i encounter the following error:
warning: cannot resolve "anbox-image", a dependency of "anbox-git"
```
:: warning: cannot resolve "anbox-image", a dependency of "anbox-git"
:: The following package cannot be upgraded due to unresolvable dependencies:
      anbox-git

```

how can i fix this prolem?

**Comment by morphis** [comment]
@emptycpp Best is if you ask on AUR about this issue as we can't give support for any downstream packaging here. The only officially supported packaging of Anbox is the snap package.
