### ISSUE TITLE
Can't Install. Fedora 25.

### ISSUE THREAD

**Issue by dochench** [anbox/anbox#85]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the
list of open bugs at https://github.com/anbox/anbox/issues

**Anbox release (`anbox version`) and system info (`anbox system-info`):**

[root@surface dhench]# snap version
snap    2.23.6-4.fc25
snapd   2.23.6-4.fc25
series  16
fedora  25
kernel  4.10.8-200.fc25.x86_64
There is no "anbox version" version yet, as I can not install.

**Description of the problem:**

Was able to install anbox-installer via snap. (snap install --classic anbox-installer) however, anbox-installer will not execute. /var/lib/snapd/snap/bin/anbox-installer exists, but will not execute. ends with
execv failed: No such file or directory

**Expected:**

**Additional info:**
Output from strace
open("/var/lib/snapd/seccomp/profiles//snap.anbox-installer.anbox-installer", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=7294, ...}) = 0
read(3, "@unrestricted\n\n# Description: Al"..., 4096) = 4096
read(3, "t be needed, but we've seen deni"..., 4096) = 3198
read(3, "", 4096)                       = 0
lseek(3, 0, SEEK_SET)                   = 0
close(3)                                = 0
geteuid()                               = 0
setresgid(-1, 0, -1)                    = 0
setresuid(-1, 0, -1)                    = 0
open("/", O_RDONLY|O_DIRECTORY|O_NOFOLLOW|O_CLOEXEC) = 3
mkdirat(3, "root", 0755)                = -1 EEXIST (File exists)
openat(3, "root", O_RDONLY|O_DIRECTORY|O_NOFOLLOW|O_CLOEXEC) = 4
close(3)                                = 0
mkdirat(4, "snap", 0755)                = -1 EEXIST (File exists)
openat(4, "snap", O_RDONLY|O_DIRECTORY|O_NOFOLLOW|O_CLOEXEC) = 3
close(4)                                = 0
mkdirat(3, "anbox-installer", 0755)     = -1 EEXIST (File exists)
openat(3, "anbox-installer", O_RDONLY|O_DIRECTORY|O_NOFOLLOW|O_CLOEXEC) = 4
close(3)                                = 0
mkdirat(4, "10", 0755)                  = -1 EEXIST (File exists)
openat(4, "10", O_RDONLY|O_DIRECTORY|O_NOFOLLOW|O_CLOEXEC) = 3
close(4)                                = 0
close(3)                                = 0
geteuid()                               = 0
setgid(0)                               = 0
setuid(0)                               = 0
execve("/usr/lib/snapd/snap-exec", ["/usr/lib/snapd/snap-exec", "anbox-installer"], [/* 62 vars */]) = -1 ENOENT (No such file or directory)
dup(2)                                  = 3
fcntl(3, F_GETFL)                       = 0x8402 (flags O_RDWR|O_APPEND|O_LARGEFILE)
fstat(3, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
write(3, "execv failed: No such file or di"..., 40execv failed: No such file or directory
) = 40
close(3)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by DeltaTheWolf** [comment]
i have the same issue. hopefully the developer sees this soon.

**Comment by dochench** [comment]
Looks to be an issue with snap install. Going to try and correct with symlink, will post results.

**Comment by dochench** [comment]
As root:
cd /usr/lib
ln -s ../libexec/snapd .
Then as user:
 snap run anbox-installer
Android in a Box - Installer


IMPORTANT: THIS IS ALPHA LEVEL SOFTWARE. EXPECT INSTABILITY AND
           BUGS !!!!!

IMPORTANT: ALSO PLEASE BE AWARE THAT WE DON'T PROVIDE FULL
           CONFINEMENT FOR THE SNAP YET !!!!


PLEASE NOTE: This script will require root access on your system
to install all necessary things. It will prompt you to enter your
password when required.


ERROR: You are running the installer on an unsupported distribution.
       At the moment we only support the following distributions:

Ubuntu, LinuxMint, neon, elementary

If your distribution is in the list but you still see this message, open
an issue here: https://github.com/anbox/anbox-installer

**Comment by gaurav-nelson** [comment]
Can't get it to work either!

**Comment by x09** [comment]
Can't get it to work either too!

**Comment by maci0** [comment]
+1 would also like to see fedora supported

**Comment by lfarkas** [comment]
+1

**Comment by abtevrythng** [comment]
I tried building from source, but it fails as well.

```
-- Checking for module 'dbus-cpp'
--   No package 'dbus-cpp' found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:424 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:597 (_pkg_check_modules_internal)
  CMakeLists.txt:67 (pkg_check_modules)


-- Configuring incomplete, errors occurred!

```

There is no dbus-cpp available for Fedora but I have installed dbus-c++ which I think is the right one.

**Comment by andyrichardson** [comment]
Yup, no dbus-cpp on Fedora, instead it's dbus-c++. I couldn't manage to make a system link or edit the build files to work on Fedora.

**Comment by maci0** [comment]
maybe this helps 
https://github.com/adobe/webkit/blob/master/Source/cmake/FindDBus.cmake ?

**Comment by ericbets** [comment]
To make it happen, somebody needs to look into how to provide dkms packages for the binder and ashmem kernel modules in a copr repo

**Comment by ericbets** [comment]
It looks like Pedro Arvela got it all working in #58

**Comment by elieobeid7** [comment]
Any update on possible solutions?

**Comment by andyrichardson** [comment]
I modified the dependencies to get dbus-c++ and others detected but Mir was also on there. Given Mir development has been cancelled and Ubuntu is moving to Wayland, I'm assuming the devs will move to Wayland some time soon.

**Comment by peter-manton** [comment]
This problem is still persisting in 2.26.3-3.fc26

**Comment by andyrichardson** [comment]
Again @peter-manton, to get this to work on any distro, you'll need to use _Mir_ which Ubuntu themselves are abandoning (aside for use in IOT). Installing a (arguably legacy) display server for a single application just doesn't make sense. 

Hopefully the devs will move to Wayland - or at the very least, Xorg - soon so that it can be realistically used on a wide range of operating systems other than Ubuntu. At the very least, Ubuntu will be dropping support for Mir by 2018 and Anbox will be forced to support an alternative display server.

**Comment by ericbets** [comment]
RedHat management said no to Anbox in Fedora so if you want it anytime soon changing distros to Ubuntu is the only way.

**Comment by abtevrythng** [comment]
@ericbets 

> RedHat management said no to Anbox in Fedora so if you want it anytime soon changing distros to Ubuntu is the only way.

Is there a discussion somewhere about this?

**Comment by ericbets** [comment]
@abtevrythng  https://bugzilla.redhat.com/show_bug.cgi?id=1455411

**Comment by nerijus** [comment]
You can ask rpmfusion, they do provide kernel modules as dkms.

**Comment by rcmin17** [comment]
@ericbets aside from Ubuntu, what other options are there?

**Comment by sruggier** [comment]
> @ericbets aside from Ubuntu, what other options are there?

Just FYI, as of now there are also anbox packages in Debian, in unstable, buster, and stretch-backports. The kernel modules are available in newer Debian kernels, including the one in stretch-backports.

**Comment by pokitpeng** [comment]
I solved the problem by running `sudo  apt install dbus-cpp-dev`
