### ISSUE TITLE
this is the issue with anbox i get trying to run anbox app manager

### ISSUE THREAD

**Issue by kdogg23gs** [anbox/anbox#853]
kdogg23gs@kdogg23gs-Inspiron-1545:~$ snap refresh --edge --devmode anbox
error: cannot perform the following tasks:
- Download snap "anbox" (134) from channel "edge" (received an unexpected http response code (503) when trying to download https://fastly.cdn.snapcraft.io/download-origin/fastly/Nr9K6UJaIOD8wHpDEQl16nabFFt9LLEQ_134.snap?token=1533744000_638b83155f94a3d54c0b64f6653f22a0bb33ba73)
kdogg23gs@kdogg23gs-Inspiron-1545:~$ 

Is this channel dead? Is there a direct channel to try? Ive been on for 6 hrs. Found the B43 conflict and posted a fix for the wifi issue.....will note I found it on a post from 2 yrs ago. Worked like a charm...posted one here. Plenty of programming background, never made it through linux. Working with family computers and 3 of my own trying to make the best of it. If anyone has an idea please reply. Sorry for sounding so distressed. Im sure everyone is pushing. Ive got a story....right now im just looking for answers to logic. thanks

1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by morphis** [comment]
@kdogg23gs I am sorry, but I can't help you with this. This is a problem with snapd. At best you ask at https://forum.snapcraft.io for help.
