### ISSUE TITLE
Anbox installed perfecly. When I start the Anbox application manager, none of the icons are clickable. Before I sideload any apps, I need to make sure that I can open them. I am using Linux Mint 19 with an Intel I5 8400 with graphics on the chip and 16 GB of RAM. No video card. I am using a wireless Logitech keyboard which I plugged into all of the usb ports. I also used a regular usb keyboard and usb mouse and had the same problem. Would appreciate any help. I feel like I'm so close to getting Anbox to work properly. Thank you.

### ISSUE THREAD

**Issue by sstahl4006** [anbox/anbox#854]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by sstahl4006** [comment]
When I update the snap the latest as in #2 above, I receive this error: error: cannot perform the following tasks:
- Download snap "anbox" (134) from channel "edge" (received an unexpected http response code (503) when trying to download https://fastly.cdn.snapcraft.io/download-origin/fastly/Nr9K6UJaIOD8wHpDEQl16nabFFt9LLEQ_134.snap?token=1533884400_48ebd78bf9c11c4dd13f07e4b06505df09c5ad59)

**Comment by sstahl4006** [comment]
When I perform #3 above (make sure you have debug logs enabled) I get the following error: error: cannot perform the following tasks:
- Run configure hook of "anbox" snap (snap "anbox" has no "configure" hook)

**Comment by sstahl4006** [comment]
Container.manager.log
Journal file /var/log/journal/ef635a010d284bc38d762d2b9f0e65ac/user-1000.journal uses an unsupported feature, ignoring file.
-- No entries --

**Comment by sstahl4006** [comment]
system.info.log
anbox: error while loading shared libraries: libpulsecommon-8.0.so: cannot open shared object file: No such file or directory

**Comment by morphis** [comment]
@sstahl4006 Please install Anbox from the `edge` channel. We will soon push a new version to beta which will fix various bugs including the one you're running into with libpulsecommon-8.0.so. `snap refresh --edge --devmode anbox` gives you the latest Anbox snap.

**Comment by sstahl4006** [comment]
Morphis, I did as you mentioned and the icons are still unclickable.

**Comment by sstahl4006** [comment]
Looks like I'll have to wait for the new beta with fixes. Thanks.

**Comment by morphis** [comment]
@sstahl4006 Thanks. This duplicates #780 then.
