### ISSUE TITLE
Installation failure on non-avx CPUs (with AES3, 4.1, 4.2)

### ISSUE THREAD

**Issue by leewp14** [anbox/anbox#859]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
*this line is not the output. unable to get output due to installation unsuccessful*
```

**Please describe your problem:**
Installation failed due to cpu detection, detects host cpu as unsupported. 

**What were you expecting?:**
Installation finishes without problem. 

**Additional info:**
```
leewp14@CTK942S:~$ snap install --devmode --edge anbox
error: cannot perform the following tasks:
- Run install hook of "anbox" snap if present (run hook "install": 
-----
The CPU of your computer (Intel(R) Core(TM) i7 CPU       M 620  @ 2.67GHz) does not support all
features Anbox requires.
It is missing support for the following features: SSE 4.1, SSE 4.2, SSSE 3
You can for example find more information about SSE
here https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions
-----)
leewp14@CTK942S:~$
```

It is an issue with [list_cpu_features](https://github.com/google/cpu_features). The bug is reported [here](https://github.com/google/cpu_features/issues/4) and [here](https://github.com/google/cpu_features/issues/40)

**Comment by morphis** [comment]
According to http://www.cpu-world.com/CPUs/Core_i7/Intel-Core%20i7%20Mobile%20I7-620M%20CP80617003981AH.html the CPU supports SSE 4.1, SSE 4.2 and SSSE 3. I think this warrants enough for a whitelist entry like we did for qemu (see #850).
