### ISSUE TITLE
[ repo init -u https://github.com/anbox/platform_manifests.git -b anbox] leads to a 404.

### ISSUE THREAD

**Issue by hub2git** [anbox/anbox#87]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the
list of open bugs at https://github.com/anbox/anbox/issues

**Anbox release (`anbox version`) and system info (`anbox system-info`):**
anbox 0.1.0
anbox system-info

> version: 0.1.0
> os:
>   name: Ubuntu Core
>   version: 16
>   snap-based: true
> kernel:
>   version: Linux version 4.4.0-71-generic (buildd@lcy01-05) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017
>   binder: true
>   ashmem: true
> graphics:
>   egl:
>     vendor: Mesa Project
>     version: 1.4 (DRI2)
>     extensions:
>       - EGL_CHROMIUM_sync_control
>       - EGL_EXT_image_dma_buf_import
>       - EGL_KHR_create_context
>       - EGL_KHR_fence_sync
>       - EGL_KHR_get_all_proc_addresses
>       - EGL_KHR_gl_renderbuffer_image
>       - EGL_KHR_gl_texture_2D_image
>       - EGL_KHR_gl_texture_cubemap_image
>       - EGL_KHR_image
>       - EGL_KHR_image_base
>       - EGL_KHR_image_pixmap
>       - EGL_KHR_reusable_sync
>       - EGL_KHR_surfaceless_context
>       - EGL_KHR_wait_sync
>       - EGL_MESA_configless_context
>       - EGL_MESA_drm_image
>       - EGL_MESA_image_dma_buf_export
>       - EGL_NOK_swap_region
>       - EGL_NOK_texture_from_pixmap
>       - EGL_NV_post_sub_buffer
>       - EGL_WL_bind_wayland_display
>   gles2:
>     vendor: Intel Open Source Technology Center
>     vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
>     extensions:
>       - GL_EXT_blend_minmax
>       - GL_EXT_multi_draw_arrays
>       - GL_EXT_texture_filter_anisotropic
>       - GL_EXT_texture_lod_bias
>       - GL_OES_byte_coordinates
>       - GL_OES_fixed_point
>       - GL_OES_stencil_wrap
>       - GL_OES_compressed_paletted_texture
>       - GL_OES_query_matrix
>       - GL_OES_read_format
>       - GL_OES_single_precision
>       - GL_EXT_texture_compression_dxt1
>       - GL_OES_draw_texture
>       - GL_OES_point_size_array
>       - GL_OES_point_sprite
>       - GL_EXT_texture_format_BGRA8888
>       - GL_OES_compressed_ETC1_RGB8_texture
>       - GL_OES_depth24
>       - GL_OES_element_index_uint
>       - GL_OES_fbo_render_mipmap
>       - GL_OES_framebuffer_object
>       - GL_OES_mapbuffer
>       - GL_OES_rgb8_rgba8
>       - GL_OES_stencil8
>       - GL_OES_texture_env_crossbar
>       - GL_OES_texture_mirrored_repeat
>       - GL_OES_texture_npot
>       - GL_OES_EGL_image
>       - GL_OES_packed_depth_stencil
>       - GL_OES_texture_cube_map
>       - GL_APPLE_texture_max_level
>       - GL_EXT_discard_framebuffer
>       - GL_EXT_read_format_bgra
>       - GL_OES_blend_equation_separate
>       - GL_OES_blend_func_separate
>       - GL_OES_blend_subtract
>       - GL_OES_EGL_image_external
>       - GL_OES_EGL_sync
>       - GL_OES_vertex_array_object
>       - GL_ANGLE_texture_compression_dxt3
>       - GL_ANGLE_texture_compression_dxt5
>       - GL_EXT_map_buffer_range
>       - GL_KHR_debug
>       - GL_OES_surfaceless_context
>       - GL_EXT_polygon_offset_clamp
> 

**Description of the problem:**
https://github.com/anbox/anbox/blob/master/docs/build-android.md suggests running
`repo init -u https://github.com/anbox/platform_manifests.git -b anbox`

So that's what I did
https://gist.github.com/hub2git/6f2511df6c7c716c8cd242c64eec0b8e

Line 23 says

> Get https://github.com/anbox/platform_manifests.git

Line 27 says 

> curl: (22) The requested URL returned error: 404 Not Found

**Expected:**
I expected to not see a 404 error.

**Additional info:**
https://gist.github.com/hub2git/6f2511df6c7c716c8cd242c64eec0b8e

**Comment by morphis** [comment]
This more looks like a configuration problem with `repo`. The platform_manifests repository exists and can be cloned. Please have a look at https://source.android.com/source/downloading for a more in detail explanation of how to deal with `repo`.

**Comment by hub2git** [comment]
morphis, thank you for your reply.
someone on the #anbox IRC channel (username is _that) suggested that the problem was related to lines 54-59.

I heed the advice on lines 58 and 59.
**git config --global user.email "hub2git@myemail.net"
git config --global user.name "Hub2Git**"

I then ran the same repo command again
**repo init -u https://github.com/anbox/platform_manifests.git -b anbox**
```
Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
remote: Finding sources: 100% (4/4)
remote: Total 4 (delta 1), reused 4 (delta 1)
Unpacking objects: 100% (4/4), done.
From https://gerrit.googlesource.com/git-repo
   04071c1..ffb4b89  master     -> origin/master
Get https://github.com/anbox/platform_manifests.git
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Server does not provide clone.bundle; ignoring.
remote: Counting objects: 628, done.        
remote: Total 628 (delta 0), reused 0 (delta 0), pack-reused 628        
Receiving objects: 100% (628/628), 125.21 KiB | 153.00 KiB/s, done.
Resolving deltas: 100% (270/270), done.
From https://github.com/anbox/platform_manifests
 * [new branch]      anbox      -> origin/anbox

Your identity is: hub2git <github.9a@9ox.net>
If you want to change this, please re-run 'repo init' with --config-name

Testing colorized output (for 'repo diff', 'repo status'):
  black    red      green    yellow   blue     magenta   cyan     white 
  bold     dim      ul       reverse 
Enable color display in this user account (y/N)? y

repo has been initialized in /home/me

```

**Comment by hub2git** [comment]
now running `repo sync`
