### ISSUE TITLE
Snap package fails to install on Ubuntu 18.04 with kernel 4.18

### ISSUE THREAD

**Issue by Al2Me6** [anbox/anbox#870]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
N/A, Anbox cannot install

**Please describe your problem:**
Attempting to install the snap package produces the following error:
`% sudo snap install --devmode --edge anbox`
`error: cannot perform the following tasks:`
`- Run install hook of "anbox" snap if present (run hook "install": cannot perform readlinkat() on the mount namespace file descriptor of the init process: Permission denied)`

**What were you expecting?:**
For the snap to successfully install

**Additional info:**
I suspect that the issue has to do with the newest kernel, as the application worked and installed fine on kernel 4.17.x. After the upgrade, the application entries disappeared and so did the Android img. Unfortunately, I have not yet had a chance to try an older kernel.

System details:
- Up to date install of Kubuntu 18.04.1
- Running the latest 4.18.1 kernel

**Comment by morphis** [comment]
@Al2Me6 This is an upstream problem with snap packages. Can you report this issue at https://forum.snapcraft.io?
