### ISSUE TITLE
anbox not starting on kubuntu  18.04

### ISSUE THREAD

**Issue by normallinuxuser** [anbox/anbox#877]
*English is not my native language*
every time i try ti open anbox i get this error 
  
cannot perform readlinkat() on the mount namespace file descriptor of the init process: Permission denied
anyone know what to do?

**Comment by Todaug** [comment]
Sounds like a kernel issue. Which kernel version do you use ?

**Comment by normallinuxuser** [comment]
4.18.3

**Comment by abraham** [comment]
I got passed a similar error[ following these instruction](http://thedaneshproject.com/posts/cannot-perform-readlinkat-on-the-mount-namespace-file-descriptor-of-the-init-process-permission-denied/) to use a beta version of snap.
