### ISSUE TITLE
script create-package.sh does not work, due to missing step of copying anbox-init.sh

### ISSUE THREAD

**Issue by maurossi** [anbox/anbox#878]
Hi,
The step of copying anbox-init.sh to temporary $roofts is necessary
prior to chmod +x command.

Working solution to the problem is here:

https://github.com/maurossi/anbox/commit/cbea6acb53fc0b4be5fbb1ed25d157a721fc7b21

NOTE: I have updated the commit, because I had a typo in my Signed-off-by

Cheers
Mauro

**Comment by morphis** [comment]
@maurossi Feel free to submit a PR the next time.

However the installation of the anbox-init.sh script should happen during the Android build itself as it is listed in https://github.com/anbox/anbox/blob/master/products/anbox.mk#L56

Wondering how you setup your build tree and which version of Anbox you're building.

**Comment by maurossi** [comment]
The version is master branch on the date of August, 16th and I just git cloned it and applied two patched to fix the create-package.sh

I'm using the script because I want to try an android.img different from the anbox x86_64 image target,
oreo-x86 image of android-x86 project

You may say it is outside of context of use of anbox, but the script itself is documented in anbox sites contains the  #FIXME tag at the line and the commit I posted is the fix,
if you need it,

if you do not need it sorry for having opened a ticket, I just wanted to help/share and save you some time, not let you lose time.

Just for your information,  I do not do PR on github based on a choice, because even if it may be simple I do not like the spam txt in the commits done via PR, also I am not a github interface user.

Mauro

**Comment by morphis** [comment]
@maurossi If you use a different launch target then a lot of necessary files wont get copied and you will not have success booting the resulting image with Anbox. Anbox depends on its own driver layer which you will miss if not using the right `anbox` build target.
