### ISSUE TITLE
Latest Anbox snap package not installing

### ISSUE THREAD

**Issue by benthehuman256** [anbox/anbox#883]
Problem:
Can't install the latest Anbox snap (sudo snap install --devmode --edge anbox)
 
Terminal output:
`2018-08-26T16:08:35+01:00 INFO Waiting for restart...
error: cannot perform the following tasks:
- Run install hook of "anbox" snap if present (run hook "install": cannot perform readlinkat() on the mount namespace file descriptor of the init process: Permission denied)`

This is a clean install of Ubuntu 18.04

**Comment by trprado** [comment]
Try update core to edge.

**Comment by morphis** [comment]
This is not a problem with Anbox itself but with the upstream snapd project. Please ask for help at https://forum.snapcraft.io
