### ISSUE TITLE
Installation failure Xubuntu 18.04 Intel Celeron N2840

### ISSUE THREAD

**Issue by jbeavis19** [anbox/anbox#889]
~$ sudo snap install --devmode --beta anbox
error: cannot perform the following tasks:
- Run install hook of "anbox" snap if present (run hook "install": 
-----
The CPU of your computer (      Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz) does not support all
features Anbox requires.
It is missing support for the following features: SSE 4.1, SSE 4.2, SSSE 3
You can for example find more information about SSE
here https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions
-----)

Processor specs seem to indicate that these features are supported. Is there something that I'm doing wrong?

**Comment by morphis** [comment]
@jbeavis19 There should be soon a new snap in the edge channel available which allows you to install Anbox on your Intel Celeron N2840.

**Comment by jbeavis19** [comment]
Awesome, Thank you for the assistance.
