### ISSUE TITLE
error while installing 

### ISSUE THREAD

**Issue by badigarjoel** [anbox/anbox#89]
system : ubuntu 14.04 64 bit

sudo snap install --classic anbox-installer && anbox-installer
**ZOE ERROR (from /usr/lib/snap/snap): zoeParseOptions: unknown option (--classic)
ZOE library version 2006-07-28**

can i get a help ?

**Comment by feikname** [comment]
@badigarjoel do `snap install anbox-installer --classic`, it should solve your problem.

**Comment by discapacidad5** [comment]
tengo el mismo problema con debian 8
