### ISSUE TITLE
core i5 m 460 triggers the "sse not supported" error

### ISSUE THREAD

**Issue by friendlycodedealer** [anbox/anbox#903]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
``` error: cannot perform the following tasks: - Run install hook of "anbox" snap if present (run hook "install":  ----- The CPU of your computer (Intel(R) Core(TM) i5 CPU       M 460  @ 2.53GHz) does not support all features Anbox requires. It is missing support for the following features: SSE 4.1, SSE 4.2, SSSE 3 You can for example find more information about SSE here https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions -----) https://en.wikichip.org/wiki/intel/core_i5/i5-460m

**Please describe your problem:**


**What were you expecting?:**
https://en.wikichip.org/wiki/intel/core_i5/i5-460m

**Additional info:**

**Comment by morphis** [comment]
This should be fixed with https://github.com/anbox/anbox/pull/896

A snap with that included should be available in the edge channel. Please let us know if it still doesn't work.
