### ISSUE TITLE
Wrong sse detection

### ISSUE THREAD

**Issue by iillyyaa2033** [anbox/anbox#911]
**Please describe your problem:**
![image](https://user-images.githubusercontent.com/17745136/45345288-98f61080-b5ae-11e8-90a0-838df02fa86d.png)

Same problem on edge channel:
![image](https://user-images.githubusercontent.com/17745136/45346129-0145f180-b5b1-11e8-81bb-a05ee6df69be.png)

**What were you expecting?:**
Regular installation of Anbox

**Comment by morphis** [comment]
This is due to an upstream bug https://github.com/google/cpu_features/issues/4

Until we have a better way to detect missing AVX support you have to add an override for your CPU similar to https://github.com/anbox/anbox/pull/910

**Comment by morphis** [comment]
I've just added https://github.com/anbox/anbox/pull/912 which should help to not grow our whitelist much more. Please have a try with the latest snap from edge once that branch is merged.

**Comment by iillyyaa2033** [comment]
@morphis just started compiling from my fork lol
(I'll try snap later)

**Comment by iillyyaa2033** [comment]
@morphis snap shows same warning. Fork compiled successfully.

**Comment by morphis** [comment]
@iillyyaa2033 A new version of the snap with the PR mentioned above (revision 154) is now available in the edge channel. Please installation via `snap install --edge --devmode anbox`.

**Comment by iillyyaa2033** [comment]
Good. I'll try it one or two hours later.

**Comment by iillyyaa2033** [comment]
@morphis problem solved. Thanks for your help!
