### ISSUE TITLE
'union SDL_SysWMinfo::<unnamed>' has no member named 'wl'

### ISSUE THREAD

**Issue by Gooberpatrol66** [anbox/anbox#915]
**Please describe your problem:**
build error

**Additional info:**
[build.log](https://github.com/anbox/anbox/files/2385939/build.log)

**Comment by Gooberpatrol66** [comment]
Gentoo. 

```
media-libs/libsdl2-2.0.8-r1::gentoo was built with the following:
USE="X alsa dbus joystick opengl pulseaudio sound threads udev video (-altivec) (-custom-cflags) -gles -haptic -libsamplerate -nas -oss -static-libs -tslib -wayland -xinerama -xscreensaver" ABI_X86="(64) -32 (-x32)" CPU_FLAGS_X86="3dnow mmx sse sse2"

```

**Comment by Gooberpatrol66** [comment]
If you're asking what version of anbox I'm building, it's the git master.

**Comment by bassdr** [comment]
I just got it to compile on Gentoo without wayland, just disable it in the cmake option, it is called ENABLE_WAYLAND, it is ON by default.

Another option is to compile libsdl2 with wayland support.

**Comment by harddevelop** [comment]
I have the same issue in a raspbian on raspberry pi 4

![image](https://user-images.githubusercontent.com/15215960/81845830-69e92c80-9551-11ea-956c-5732f3bdc54d.png)

**Comment by JuanDiazCortez** [comment]
For the record: you can add wayland support to sdl with
echo "=media-libs/libsdl2-2.0.14-r1 wayland gles2" >> /etc/portage/package.use/package.use 

in gentoo.
