### ISSUE TITLE
Anbox 

### ISSUE THREAD

**Issue by xanderjara** [anbox/anbox#92]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the
list of open bugs at https://github.com/anbox/anbox/issues

**Anbox release (`anbox version`) and system info (`anbox system-info`):**

**Description of the problem:**

**Expected:**

**Additional info:**

**Comment by morphis** [comment]
No real info about what the issue is in this bug.
