### ISSUE TITLE
The CPU (Intel core 2 duo E6400) does not support (SSE 4.1, SSE 4.2, SSSE 3)

### ISSUE THREAD

**Issue by Nosshadow** [anbox/anbox#920]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```No printout, because I can't install anbox```

**Please describe your problem:**
When I run `$ sudo snap install --devmode --beta anbox` I get an error message saying: 

> error: cannot perform the following tasks:
> Ejecutar el enganche de instalación del snap "anbox" si está presente (run hook "install": 
> The CPU of your computer (Intel(R) Core(TM)2 CPU          6400  @ 2.13GHz) does not support all
> features Anbox requires.
> It is missing support for the following features: SSE 4.1, SSE 4.2, SSSE 3
> You can for example find more information about SSE
> here https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions

**What were you expecting?:**
A correct installation

**Additional info:**
output `$ cat /proc/cpuinfo | grep sse`

> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr **sse sse2** ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 **ssse3** cx16 xtpr pdcm lahf_lm pti tpr_shadow dtherm
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr **sse sse2** ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 **ssse3** cx16 xtpr pdcm lahf_lm pti tpr_shadow dtherm

All Specifications here:
[http://www.cpu-world.com/CPUs/Core_2/Intel-Core%202%20Duo%20E6400%20HH80557PH0462M%20(BX80557E6400).html](url)

**Comment by Petitswood1** [comment]
Also same issue with Intel Core Duo E4500
Have check the Edge Channel snap which does not resolve this issue
(Am newbie to this so if improper comment etc please advise and will open up separate pull request)

**Comment by morphis** [comment]
@Nosshadow According to http://www.cpu-world.com/CPUs/Core_2/Intel-Core%202%20Duo%20E6400%20HH80557PH0462M%20(BX80557E6400).html the E6400 doesn't support SSE 4.x which is mandatory for Anbox. There is not much we can do about that.
