### ISSUE TITLE
[IMPROVEMENT NEEDED] Need a better way to scroll using mouse wheel

### ISSUE THREAD

**Issue by SciFi1818** [anbox/anbox#923]
**Hii,**
I would like to put forward a suggestion,
At the current state, it is a bit difficult to navigate using the mouse wheel... It would be more convenient if you could make the wheel scrolling to something like emulating touch... I am not sure if you got what I mean...I will give you an example...In Tencent Emulator(The PUBG emulator) they made the mouse wheel to emulate just like a swipe gesture on screen..Check this link for the video of it  :  [Click Here](https://streamable.com/69c0d)

**Comment by BobbyWibowo** [comment]
I'm pretty sure mouse wheel is already being "emulated" here. At least it does work on various apps that got some sort of list view (settings, twitter, search results in play store or apkpure). However the performance is rather sad.

**Comment by SciFi1818** [comment]
I am pretty sure that, it isn't emulating the scroll wheel, but is just leaving it for Android to do its job...What i said was to emulate the scroll wheel just as a normal drag gesture.....

**Comment by beanaroo** [comment]
Being able to use two-finger scroll with the laptop touchpad would be great :)

**Comment by mvglasow** [comment]
Same thing here, scroll wheel does not work.

Just noticed (in Settings) that if I use the wheel, then move the mouse, the list does scroll (by an amount that looks like the equivalent of one scroll wheel pulse). If I move the mouse around a bit while scrolling, everything works as expected. So apparently wheel input is held back until the mouse is moved, and at most one wheel operation (the last one) is passed on in that situation (i.e. if you scroll up, then down, then move the mouse, the list will scroll down).

**Comment by Ge-lx** [comment]
I have the same experience on a fresh install in ubuntu. When moving the mouse while scrolling everything seems to work as expected. When not moving the mouse only one scroll event is let through (on the next mouse move). 
This is a HUGE problem when using the anbox with a touchpad, as you cannot move the mouse while scrolling there.

**Comment by mvglasow** [comment]
Thanks, that did in fact solve it! I guess this can be closed once the next stable release is out.

**Comment by Ge-lx** [comment]
@awaken1ng Yes, can confirm. Fixed for me. Thanks for lettings me know and for Anbox :)
