### ISSUE TITLE
(Comptibility?) Anbox snap fails to install: Missing SSE Support from CPU

### ISSUE THREAD

**Issue by TimmSkiller** [anbox/anbox#926]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```N\A
[please paste printout of `anbox system-info` here]
```N\A

**Please describe your problem:**
running **snap install --devmode --beta** tells me: snap install --devmode --beta 

> error: cannot perform the following tasks:
- Run install hook of "anbox" snap if present (run hook "install": 
-----
The CPU of your computer (AMD Turion(tm) X2 Dual-Core Mobile RM-75) does not support all
features Anbox requires.
It is missing support for the following features: SSE 4.1, SSE 4.2, SSSE 3
You can for example find more information about SSE
here https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions
-----)


**What were you expecting?:**
For it to work

**Additional info:**
I just wanted to run apps on this old laptop :(

**Comment by TimmSkiller** [comment]
Seems to support SSE 1,2,3 but no 4
https://www.notebookcheck.net/AMD-Turion-X2-RM-75-Notebook-Processor.35470.0.html

**Comment by morphis** [comment]
Then there is sadly no way to make it work right now.Am 26.09.2018 14:39 schrieb TimmSkiller <notifications@github.com>:Seems to support SSE 1,2,3 but no 4
https://www.notebookcheck.net/AMD-Turion-X2-RM-75-Notebook-Processor.35470.0.html

**Comment by JIGITUP** [comment]
Same.

```
sudo apt update
sudo apt full-upgrade
sudo add-apt-repository ppa:morphis/anbox-support
sudo apt install anbox-modules-dkms
sudo modprobe ashmem_linux
sudo modprobe binder_linux
sudo apt install android-tools-adb android-tools-fastboot
sudo snap install --devmode --beta anbox
```

AND:

> error: cannot perform the following tasks:
> - Run install hook of "anbox" snap if present (run hook "install": 
> -----
> The CPU of your computer (Intel(R) Core(TM)2 Duo CPU     E6550  @ 2.33GHz) does not support all
> features Anbox requires.
> It is missing support for the following features: SSE 4.1, SSE 4.2, SSSE 3
> You can for example find more information about SSE
> here https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions
> -----)

I have all Intel Technology Features turn on.

![image](https://user-images.githubusercontent.com/21994415/46194022-18cdeb80-c2ce-11e8-9269-13eb3504889f.png)

**Comment by morphis** [comment]
You miss support for SSE 4.1 and 4.2 as the error message says.Am 28.09.2018 09:35 schrieb Jean Franco Amoni Rodríguez <notifications@github.com>:Same.
sudo apt update
sudo apt full-upgrade
sudo add-apt-repository ppa:morphis/anbox-support
sudo apt install anbox-modules-dkms
sudo modprobe ashmem_linux
sudo modprobe binder_linux
sudo apt install android-tools-adb android-tools-fastboot
sudo snap install --devmode --beta anbox

AND:

error: cannot perform the following tasks:
Run install hook of "anbox" snap if present (run hook "install":

The CPU of your computer (Intel(R) Core(TM)2 Duo CPU     E6550  @ 2.33GHz) does not support all
features Anbox requires.
It is missing support for the following features: SSE 4.1, SSE 4.2, SSSE 3
You can for example find more information about SSE
here https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions
-----)

I have all Intel Technology Features turn on.

**Comment by anoraktrend** [comment]
Question: why does it *require* those features? Does it really require them?

**Comment by anoraktrend** [comment]
To add to my previous statement: if it is integral to the app, you should include that in the dependencies.

**Comment by dudeofx** [comment]
My PC was ruled out cause of SSE4.2 which are instructions for accelerated string comparisons, accelerated 64bit data comparisons and CRC calculation. I don't see how that is integral part of running Android Apps.

**Comment by morphis** [comment]
@dudeofx Various parts of the Android system use SSE instructions to improve performance. Its not something you can easily turn on and off as its build into the binaries. There is existing work by others, especially by the Android x86 project to be able to run Android without these (see https://sourceforge.net/p/android-x86/misc/3/ for example) but nobody investigate yet what it would take and if it makes sense to bringe these changes to Anbox without decrease performance for those systems having support for the modern versions of SSE.

**Comment by morphis** [comment]
Closing as there is nothing we can change right now.

**Comment by imisrac** [comment]
@morphis There is actually something you can change. You can/should indicate this prerequisite in the docs. I did not find anything about this in the docs.

**Comment by louniss** [comment]
updates..?

**Comment by spider4216** [comment]
The same :(
```
The CPU of your computer (         Intel(R) Atom(TM) CPU N455   @ 1.66GHz) does not support all
features Anbox requires.
It is missing support for the following features: SSE 4.1, SSE 4.2, SSSE 3
You can for example find more information about SSE
```

**Comment by o92** [comment]
Tsk .. should have googled before installing

The CPU of your computer (Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz) does not support all
features Anbox requires.
It is missing support for the following features: SSE 4.2
You can for example find more information about SSE
here https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions

**Comment by VincentKhoo792** [comment]
Yep my pc with an Intel core 2 duo E7400  doesnt support SSE4 and failed to install either...

**Comment by mobagenie** [comment]
There is the best solution for no SSE4. install Android OS from Android x86 Project. its basically same with Anbox but more Native than Anbox since its boot directly from PC bios just like Windows or Linux OS.

here is the ISO based on Adroid PIE (Android 9) fro x86 32 bit CPU link download : https://sourceforge.net/projects/android-x86/files/Release%209.0/android-x86-9.0-r2.iso/download

Andoid Pie (Android 11) as i know is the latest Android OS that support non SSE 4 instruction. here more information from Android Official about x86 Android.

x86

This ABI is for CPUs supporting the instruction set commonly known as "x86", "i386", or "IA-32". Characteristics of this ABI include:

These flags target the Pentium Pro instruction set, along with the the MMX, SSE, SSE2, SSE3, and SSSE3 instruction set extensions. The generated code is an optimization balanced across the top Intel 32-bit CPUs.

i hope this information can help your problem. thx

**Comment by anoraktrend** [comment]
So much wrong with that last comment.

**Comment by Fuseteam** [comment]
It is however true that android x86 is able to boot on hardware that doesn't support sse4
