### ISSUE TITLE
we have a big problem !!

### ISSUE THREAD

**Issue by user000101** [anbox/anbox#929]
Hi everyone
Actually we have a deep problem maybe nobody talk about it 
when we install anbox and we install android apps inside like whatsapp or any messenger apps we can write in international language that is mean there is no language we can write just English so when somebody who can not speak English can not use Anbox 
So please please find a solution for this problem

**Comment by sn99** [comment]
@user000101 You can install a keypad apk or simply copy and paste text if you want

**Comment by dennohpeter** [comment]
> @user000101 You can install a keypad apk or simply copy and paste text if you want

haha

**Comment by robinmetral** [comment]
@user000101 I disagree that the lack of locale keyboard support makes Anbox impossible to use, but it's true that there is an issue here.

Maybe I haven't looked far enough, but as far as I could see Anbox didn't recognize my computer's locale preferences, and the preferences within Android didn't let me change input options.

Did anyone find and test a workaround for this, other than copy-pasting?

Would installing a keypad apk as suggested by @sn99 solve the problem? Input options, I think, are customized in Android's preferences.

**Comment by sim590** [comment]
> simply copy and paste text if you want

Sérieusement ? Mais quel manque de considération pour les autres. C'est irrespectueux.

**Comment by Xebozone** [comment]
Description of issue should be updated to something more useful like "No multiple language support" rather than 'big problem, help!'
