### ISSUE TITLE
Is there any plan to provide the .deb install package that not just the snap package?

### ISSUE THREAD

**Issue by rikonaka** [anbox/anbox#930]
As the beginning I will show the most respected for the development team, you just did a great job.

But, I have read the installation wiki and see the guide and the guide's suggestion of install anbox is use the snap, yes, that's great for the ubuntu users, but as you see, the company canonical is not providing the snap mirror server for other areas' users like China (the download speed is less than 10k/s in this area, I was mad about that).

So, while I download the snap package use the `snap install --devmode --beta anbox` in the [here](https://github.com/anbox/anbox/blob/master/docs/install.md) pages mentioned.

I can not finish the download even use the VPN or something else, also I can not found the snap package location in the https://snapcraft.io/ which I could use the server outside of China to download the snap package then transfer into my local computer.

That's too hard to finish my installation in where I live area.

And now I'm using the source building to install but maybe that is not the best way to use the anbox.

Thanks for you reading.

**Comment by dennohpeter** [comment]
so did you find a better solution or is this project dead

**Comment by oxwivi** [comment]
Anbox as a `deb` package is already available on Debian `contrib` channel of testing and unstable repositories and, in fact, how I'm using it on my Debian unstable box from where I'm typing this comment. IDK if Canonical has any plans to adopt it into Ubuntu's `universe` or `multiverse` channels of 18.10, but it's worth asking around for. Otherwise, you can try adding Debian repo to your `sources.list`.

**Comment by morphis** [comment]
The Anbox upstream project will not provide deb packages. I am sorry that the download speed in your area is poor. At best you ask for help with that on https://forum.snapcraft.io and provide there more information about the slowness of the store. The right people will take a look there and will be able to improve things.

The problem with the deb package is that we can't keep it updated at the same speed as we can update the snap. Given that Anbox is in a development state and doesn't has a stable release yet that makes it even harder to keep up-to-date. A snap package is a perfect fit here as we have synchronized the master git branch directly with the edge snap store channel and will get a new snap there for every merged change.
