### ISSUE TITLE
RFE: Need to be able to use existing Linux bridge not anbox0.

### ISSUE THREAD

**Issue by StevenMercurio** [anbox/anbox#931]
**Please describe your problem:**
I have a br0 bridge already as I run VMs on my system.  I can not move my only NIC eno1 from br0 because that would kill internet connectivity.  Can you please add the ability to have anbox use an existing bridge if one exists rather than create anbox0 and vethOH4VWC

**What were you expecting?:**
Setting up network connectivity but it's not working as  my IP is on a bridge NOT an interface

**Additional info:**
FC28, latest install via snap.  16+ yr exp with Linux (RPM based distros)
HW is Dell Precision M6700, 4 core I7, 32Gb RAM, 3 1Tb HDD in HW RAID 5.

**Comment by kuasha420** [comment]
Any comment on this? I would also love this option.
