### ISSUE TITLE
Support for Ubuntu 18.10 - anbox-modules-dkms from PPA not available

### ISSUE THREAD

**Issue by Stele77** [anbox/anbox#932]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**
Sorry if i miss something here. I am pretty new to Linux, but i checked the docs again and again.
Setup is no problem with the exception, that the "anbox-modules-dkms" can not be installed from the PPA, as there is no package for Ubuntu 18.10, only for 18.04 and prior.

The 18.10 version will be released in about 1-2 weeks AFAIK, and therefore it would be important to support it timely. Plus some ppl like me need to use the beta, because only it works on my Ryzen 5 2400G setup.

If support for 18.10 is still months away, would there be any reasonable way to get the anbox-modules-dkms package installed aside from the PPA?

Anbox would be a great boost of my workflow, so i can substitute some apps that i miss from windows with their android counterparts.. So thanks in advance for any help!

**What were you expecting?:**
PPA with support for 18.10

**Additional info:**
Fehler:20 http://ppa.launchpad.net/morphis/anbox-support/ubuntu cosmic Release   
  404  Not Found [IP: 91.189.95.83 80]

**Comment by Stele77** [comment]
I am new to Github, so i dont know if it is appropriate here, but thank you for assigning the issue!
Really looking forward to use Anbox!
Thanks + All the best!

**Comment by ownchoice** [comment]
Yeah, this is needed.
As a temporal fix, I added:
`deb http://ppa.launchpad.net/morphis/anbox-support/ubuntu bionic main 
deb-src http://ppa.launchpad.net/morphis/anbox-support/ubuntu bionic main `
In `/etc/apt/sources.list` to be able to use it for now.

**Comment by Stele77** [comment]
Well, thank you very very much! It worked! And i got most apks working, only 3 give errors (Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]), but this does not concern this issue!
So thank you again! You help me and i guess many others greatly!

**Comment by morphis** [comment]
I've just uploaded 13~cosmic to the anbox-support PPA. Will take a moment to build but should then be available for everyone interested.
