### ISSUE TITLE
sudo modprobe binder_linux fails

### ISSUE THREAD

**Issue by EnderShadow** [anbox/anbox#936]
It gives this error when I try to do it.
`modprobe: ERROR: could not insert 'binder_linux': Operation not permitted`
I have all the virtualization options enabled in my bios and I know my CPU supports it.

**Comment by morphis** [comment]
@EnderShadow Did you run `modprobe` as root? Try `sudo modprobe binder_linux`

**Comment by EnderShadow** [comment]
Well... It works now so either I was being stupid and forgot to try it with sudo or one of the reboots I've done since then fixed it.

**Comment by tikamchand06** [comment]
Yes I did, but still giving me the same error.

ERROR: could not insert 'binder_linux': Operation not permitted

**Comment by marouaneamqor3** [comment]
you should Disable Secure Boot in shim-signed

1. Open a terminal (Ctrl + Alt + T), and execute `sudo mokutil --disable-validation`.
2. Enter a temporary password between 8 to 16 digits. (For example, 12345678, we will use this password later
3. Enter the same password again to confirm.
4. Reboot the system and press any key when you see the blue screen (MOK management
