### ISSUE TITLE
Andbox Start 

### ISSUE THREAD

**Issue by Hugow28** [anbox/anbox#94]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the
list of open bugs at https://github.com/anbox/anbox/issues

**Anbox release (`anbox version`) and system info (`anbox system-info`):**
I just installed Andbox so I guess I have the latest version
I run on a Asus N551JX 

**Description of the problem:**
Andbox doesn't start

**Expected:**

**Additional info:**

**Comment by WuerfelDev** [comment]
you don't provide much information :smile: 
Give us some information about your system and run `uname -iorsv`
