### ISSUE TITLE
[request] migrate away from sd_bus

### ISSUE THREAD

**Issue by CameronNemo** [anbox/anbox#941]
As far as I can tell, this would eliminate the dependency on libsystemd and allow for using Anbox in environments where libsystemd is not available (e.g. on distros like Void Linux which have first class support for musl libc). ~~Anbox already depends on glib-2.0, so this would not introduce new dependencies.~~ The relevant code is in `src/anbox/dbus`, and it is ~550 lines of C++. Seems doable, although I understand that the project has limited resources.

I'm interested in your thoughts on the prospective change (i.e. would you accept patches).

**Comment by CameronNemo** [comment]
How weird. Perhaps bare libdbus could be used?

**Comment by morphis** [comment]
@CameronNemo libsystemd should be even possible on systems which don't use systemd as init system. It's a more or less standard on modern Linux distributions. Using bare libdbus would require us to bring glib back which doesn't make much sense where we don't need a GLib mainloop for anything else. Also we just migrated away from dbus-cpp and libdbus to use a more modern dbus library to simplify things.

Does libsystemd not compile with musl libc?

**Comment by CameronNemo** [comment]
systemd doesn't compile with musl, so the entire source package is missing from Void. That's too bad about the migration away from dbus-cpp.

**Comment by CameronNemo** [comment]
I am curious why you think glib is necessary for a main loop. Shouldn't we be able to use poll or select?

**Comment by PureTryOut** [comment]
@CameronNemo why did you close this issue? It hasn't been resolved, and there are more people/distros out there who would like to get rid of the libsystemd dependency, for example me from postmarketOS.

**Comment by CameronNemo** [comment]
@PureTryOut elogind has sd-bus, and there are other pains with the build process so I threw in the towel. Reopening but remaining unsubscribed.

Good luck y'all!

**Comment by z3ntu** [comment]
Just to add my 2 cents: I've seen from multiple projects that mentioned that sd-bus is a very well designed API and pretty simple to use compared to most other dbus libraries. So some projects will definitely stay with sd-bus. But I can't comment about how easy it is to get elogind with sd-bus working on non-glibc systems :)

**Comment by PureTryOut** [comment]
elogind nowadays works fine on Musl systems and it's packaged for Alpine Linux, so this isn't an issue anymore for postmarketOS.
