### ISSUE TITLE
Anbox Crashes and Closes Out When Launching Music App From Anbox App Manager

### ISSUE THREAD

**Issue by Jumbotron64** [anbox/anbox#949]
**Additional info:**
This script will collect a few interesting things which developers will
need to have a better insight into the Anbox system when something goes
wrong.

PLEASE NOTE: The collected log files may collect information about your
system. Please have a look before you're sending them to anyone!

Collecting anbox log files ... 
+ cp /var/snap/anbox/common/data/system.log /tmp/tmp.a4iaHtfGuD
+ cp /var/snap/anbox/common/containers/lxc-monitord.log /tmp/tmp.a4iaHtfGuD
cp: cannot stat '/var/snap/anbox/common/containers/lxc-monitord.log': No such file or directory
+ true
+ cp /var/snap/anbox/common/logs/container.log /tmp/tmp.a4iaHtfGuD
+ cp /var/snap/anbox/common/logs/console.log /tmp/tmp.a4iaHtfGuD
+ /snap/anbox/158/command-anbox.wrapper system-info
+ [ -e /etc/systemd/system/snap.anbox.container-manager.service ]
+ sudo journalctl --no-pager -u snap.anbox.container-manager.service
+ set +x

Just installed Anbox on HP Pavilion Desktop with an AMD Bristol Ridge APU Model A12-9800 ( Carrizo refresh)  with 4 cores running at 3.8 GHz with 16 GB of Ram.  The OS is Ubuntu 18.04.1 with Linux Kernel 18.16 with X.Org 1.19 and Mesa 18.2.2.  I checked to see if I was running the latest Anbox Snap and it was confirmed I was on the latest Snap of Anbox.  I have not tried to run any apps yet.  I just simply tried opening all the apps that were pre-installed on Anbox.  All opened successfully with the exception of the Music app.  Upon clicking on that app Anbox would instantly close out completely.  Anbox does successfully relaunch each time it closes out due to the Music app bug, but likewise it ALWAYS closes completely out upon launching the Music App.

**Comment by WPFilmmaker** [comment]
This issue is NOT fixed.
It still happens to me in March 2020 on anbox (beta) 4-56c25f1 on Lubuntu 18.04.1.
