### ISSUE TITLE
Anbox install error in Ubuntu 16.04

### ISSUE THREAD

**Issue by GangsterHyj** [anbox/anbox#95]
**Description of the problem:**
When I run the bash command `sudo snap install --classic anbox-installer && anbox-installer`, I finally get the error below and can't continue:
```
+ '[' '!' -e /etc/modules-load.d/anbox.conf ']'
+ sudo modprobe binder_linux
modprobe: ERROR: could not insert 'binder_linux': Invalid argument
```
I am very confused about that...

**Comment by Mistero5050** [comment]
I use 16.10 and no errors

**Comment by Gazzasore** [comment]
@badigarjoel do snap install anbox-installer --classic, it should solve your problem.

**Comment by Mistero5050** [comment]
Without sudo? He should try

**Comment by accesstech713** [comment]
Same error here using 17.04. The above solution only gave the message that it was already installed. Any other suggestions?

**Comment by yciabaud** [comment]
I have the same problem on 16.10

**Comment by Mistero5050** [comment]
Have you tried reading this?
https://github.com/anbox/anbox/issues/143

**Comment by fcarpenter-spectralink** [comment]
I also encountered this problem with Ubuntu 16.04.  I was able to workaround by running "anbox-installer --classic" and select "2" for "Uninstall Anbox" then rerun "anbox-install --classic" and select "1" for "Install Anbox".  Both modprobe of binder_linux and ashmem_linux work now.

**Comment by yciabaud** [comment]
That did the trick for me too. Thanks.

**Comment by Mistero5050** [comment]
Which one? Mine reference or the other comment here above?

**Comment by yciabaud** [comment]
Sorry I was talking about @fcarpenter-spectralink comment to reinstall anbox fully.
I read #143 but I tried the reinstall solution first. I believe I have updated my kernel between installation and this issue.

Thanks a lot, now I need some space to build the android image...

**Comment by Mistero5050** [comment]
So we don't know if #143  works for you. Ok
