### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ChinyChiu** [anbox/anbox#952]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by Master-Sezer** [comment]
I dont know that. I have do exactly. 
![Bildschirmfoto vom 2019-07-05 09-04-27](https://user-images.githubusercontent.com/43779060/60701276-ea87d700-9f03-11e9-833e-c12751a06eb2.png)

Please help
