### ISSUE TITLE
DNS Problem - I do have connection on anbox but it is not resolving names

### ISSUE THREAD

**Issue by lsevero** [anbox/anbox#954]
I've installed anbox from AUR and it is everthing good so far except the dns that is not resolving names on anbox.

I've tried to add the DNS on the anbox-bridge.network file and enabling the systemd-resolved.service on the host with no success.

Did anyone had a similar problem?

---------------------------------------------------------------
version: local-e1ecd04
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Arch Linux
  version: 
  snap-based: false
kernel:
  version: Linux version 4.18.16-arch1-1-ARCH (builduser@heftig-28760) (gcc version 8.2.1 20180831 (GCC)) #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:

**Comment by aksh1618** [comment]
I got internet working by using [`anbox-bridge.sh`](https://github.com/anbox/anbox/blob/master/scripts/anbox-bridge.sh), following these steps:

```bash
su
cd /usr/lib
mkdir anbox
cd anbox
wget 'https://raw.githubusercontent.com/anbox/anbox/master/scripts/anbox-bridge.sh'
chmod a+x anbox-bridge.sh
exit
killall anbox
sudo /usr/lib/anbox/anbox-bridge.sh start
```
Sources: [1](https://forum.manjaro.org/t/running-android-applications-on-arch-using-anbox/53332) [2](https://forum.manjaro.org/t/errors-compiling-anbox-bridge/59149/15)

**Comment by antonio-petricca** [comment]
Me too on Linux Mint 19.1 (snap package).

**Comment by cmmaster** [comment]
> I got internet working by using [`anbox-bridge.sh`](https://github.com/anbox/anbox/blob/master/scripts/anbox-bridge.sh), following these steps:
> 
> ```shell
> su
> cd /usr/lib
> mkdir anbox
> cd anbox
> wget 'https://raw.githubusercontent.com/anbox/anbox/master/scripts/anbox-bridge.sh'
> chmod a+x anbox-bridge.sh
> exit
> killall anbox
> sudo /usr/lib/anbox/anbox-bridge.sh start
> ```
> 
> Sources: [1](https://forum.manjaro.org/t/running-android-applications-on-arch-using-anbox/53332) [2](https://forum.manjaro.org/t/errors-compiling-anbox-bridge/59149/15)


Thank you ))

**Comment by yauhen-klimovich** [comment]
1. get current DNS list
 `nmcli dev show | grep DNS`
2. set your DNS to anbox property 
`sudo snap set anbox container.network.dns=`
3. restart anbox
`sudo killall -9 anbox`
`snap run anbox.appmgr`

**Comment by tribbloid** [comment]
> 1. get current DNS list
>    `nmcli dev show | grep DNS`
> 2. set your DNS to anbox property
>    `sudo snap set anbox container.network.dns=`
> 3. restart anbox
>    `sudo snap restart anbox.container-manager`
>    `snap run anbox.appmgr`

This is not adaptive, the default DNS on host machine frequently change with wifi connection. Is there a way to use DNS forwarding?

**Comment by tribbloid** [comment]
why is it closed? is there a new ticket for the same DNS problem?

**Comment by monperrus** [comment]
I'm using the Debian package, which is not based on snap.

How to set `container.network.dns=` on Debian/Ubuntu?

**Comment by vsatmydynipnet** [comment]
You ever found that out for Debian? I am in the same situation, all works, but it wants to go to 8.8.8.8 which is not allowed, so i need to set 

container.network.dns

in

anbox lauch 

somewhere.

**Comment by bahhax404** [comment]
> You ever found that out for Debian? I am in the same situation, all works, but it wants to go to 8.8.8.8 which is not allowed, so i need to set
> 
> container.network.dns
> 
> in
> 
> anbox lauch
> 
> somewhere.
I had a similar issue with Debian package. 8.8.8.8 is not working for me. I found out the dns is  hard coded in:
https://github.com/anbox/anbox/blob/master/src/anbox/container/lxc_container.cpp#L47
so cloned anbox repo  then changed dns to a working dns and built anbox, then I replaced anbox binray in /usr/bin/anbox  with the built one, it works. 
it's a hacky solution, I couldn't find any for the packaged debian anbox.

**Comment by nobodysu** [comment]
One of the solutions is to redirect all requests to a local DNS server:
`host# iptables -t nat -A PREROUTING -p udp -d 8.8.8.8 --dport 53 -j DNAT --to 192.168.1.1:53`
`127.0.0.53` from systemd-resolved could work too, but I haven't tested it.

**Comment by sysfu** [comment]
@lsevero Running the commands in this comment corrected DNS resolution for my anbox instance 

https://github.com/anbox/anbox/issues/1567#issuecomment-761565776
