### ISSUE TITLE
Hide title bar

### ISSUE THREAD

**Issue by alxlg** [anbox/anbox#961]
Is there a way to hide title bar and just use the one provided by system window manager (server-side decorations)?

**Comment by morphis** [comment]
Technically this is possible but we switched to client side decorations a while back to reuse features from the Android system for this. There is no plan to make this configurable.

**Comment by alxlg** [comment]
How does Ubuntu Touch hide title bar in screenshots like the following one?

![](https://www.cnx-software.com/wp-content/uploads/2017/12/Ubuntu-Touch-Android-App.jpg)

**Comment by alxlg** [comment]
@morphis can you please reconsider this? In DE/WM using Server-Side Decoration it's really annoying to have a double title bar (see image below). Disabling the system one to use CSD would break all the features provided by the DE (come on, the CSD titlebar just have a "close" button and a maximize one). For example my WM is set hide the decoration for full screen windows, this is impossible with app forcing CSD like Anbox.
![immagine](https://user-images.githubusercontent.com/26327475/59036405-84118980-886f-11e9-94c4-e002388c3aa9.png)

**Comment by PureTryOut** [comment]
Yes please reconsider this @morphis. On postmarketOS devices too we don't Anbox's title bars.

**Comment by Seegras** [comment]
On Window Maker I have the opposite problem. No titlebar from the Window Manger, and in consequence, it's fixed size in fixed position, in the middle of the screen (because, guess what, it doesn't take placing hints from the WM either).
