### ISSUE TITLE
Anbox modules ppa not working on Ubuntu 18.10

### ISSUE THREAD

**Issue by utility02** [anbox/anbox#962]
Something about a release file. Also, if a snap package has all dependencies with it, why do the modules need to be installed separately? Thanks

**Comment by morphis** [comment]
@utility02 Snap packages can't ship kernel modules. That is why we have to package them separately until they are included in the official Ubuntu kernel.

**Comment by morphis** [comment]
I've just uploaded 13~cosmic to the anbox-support PPA. Will take a moment to build but should then be available for everyone interested.
