### ISSUE TITLE
system_key.go:132: cannot determine nfs usage in generateSystemKey

### ISSUE THREAD

**Issue by ProfiGMan** [anbox/anbox#984]
`anbox system-info`:
`2018/11/21 20:59:56.749040 system_key.go:132: cannot determine nfs usage in generateSystemKey: cannot parse /etc/fstab: expected between 3 and 6 fields, found 8
Segmentation fault`

I get this when running Anbox:
`2018/11/21 20:59:56.749040 system_key.go:132: cannot determine nfs usage in generateSystemKey: cannot parse /etc/fstab: expected between 3 and 6 fields, found 8
Segmentation fault`

**Comment by morphis** [comment]
Actually this is a problem with [snapd](https://github.com/snapcore/snapd/) and not with Anbox. Can you ask for help at the official forum for snaps at https://forum.snapcraft.io?
