### ISSUE TITLE
Is there a chance to support gentoo

### ISSUE THREAD

**Issue by oddcoder** [anbox/anbox#986]
anbox depends on snaps which might be a good thing "IF" snaps support given OS, but in my case snaps doesn't support gentoo, Which is my OS of choice, so I hope if there is the slightest chance to have direct support from anbox to gentoo (OpenRC)

Thanks,

**Comment by morphis** [comment]
I am sorry. With the limited number of developers and time we have to develop Anbox further we can't afford to support anything other than snaps. However community maintained packages for Gentoo of Anbox are not a problem.
