### ISSUE TITLE
Anbox settings

### ISSUE THREAD

**Issue by parithy** [anbox/anbox#990]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

This is not an issue but a feature request

2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`

feature is not available as of today

3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
NA

4. Reproduce the error while debug logs enabled.
NA

5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

NA

6. ** Please paste the result of `anbox system-info` below:**
```
NA

[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**
Replace aosp setting with android-x86 settings to make it more relevant in PC

**What were you expecting?:**
no irrelevant settings in the settings app

**Additional info:**

**Comment by farhad-fbm** [comment]
when open Anbox on Ubuntu,
there no Icon clickable.
any apk/ setting can't be click or open
