### ISSUE TITLE
Not install

### ISSUE THREAD

**Issue by gokulEmbedded** [anbox/anbox#991]
Ubuntu 18.04
when i tried to install anbox bellow error came _ 
error: cannot perform the following tasks:
- Setup snap "anbox" (158) security profiles (cannot setup udev for snap "anbox": cannot reload udev rules: exit status 2
udev output:
)
- Setup snap "anbox" (158) security profiles (cannot reload udev rules: exit status 2
udev output:
)
- Connect anbox:opengl to core:opengl (cannot setup udev for snap "anbox": cannot reload udev rules: exit status 2
udev output:
)
- Connect anbox:opengl to core:opengl (cannot reload udev rules: exit status 2
udev output:
)

**Comment by Nikeron** [comment]
also for edge:
error: cannot perform the following tasks:
- Setup snap "anbox" (173) security profiles (cannot setup udev for snap "anbox": cannot reload udev rules: exit status 1
udev output:
)
- Setup snap "anbox" (173) security profiles (cannot reload udev rules: exit status 1
udev output:
)
- Connect anbox:opengl to core:opengl (cannot setup udev for snap "anbox": cannot reload udev rules: exit status 1
udev output:
)
- Connect anbox:opengl to core:opengl (cannot reload udev rules: exit status 1
udev output:
)

**Comment by Nikeron** [comment]
*click* Noice
