### ISSUE TITLE
Unable to install anbox in deepin os

### ISSUE THREAD

**Issue by saileshkush95** [anbox/anbox#995]
I didn't no what going wrong but I'm unable to install anbox in deepin os. Please help me out

**Comment by parithy** [comment]
please fill the details as requested in the issue template

**Comment by saileshkush95** [comment]
When I'm trying to install kernel modules  I'm getting following error
![deepinscreenshot_select-area_20190302205837](https://user-images.githubusercontent.com/28560875/53683865-23cdf180-3d2e-11e9-80a4-f13d411a78b7.png)
