### ISSUE TITLE
App Kill and minimize option - feature request

### ISSUE THREAD

**Issue by parithy** [anbox/anbox#997]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

confirmed

2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
yes
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
NA
4. Reproduce the error while debug logs enabled.
NA
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

NA
6. ** Please paste the result of `anbox system-info` below:**
NA
[please paste printout of `anbox system-info` here]
```NA

**Please describe your problem:**
Feature request: need an option to kill an app

**What were you expecting?:**
if an app hangs for some reason, the only option is to kill the session-manager which means all the running apps get closed along with the one that hung.  Need an option like in actual android to clear a running non responsive app.

**Additional info:**

**Comment by Genxster1998** [comment]
I would better suggest to disable client side decorations

**Comment by david-tamar** [comment]
Please re-open, it's actually a reasonable feature request.
On i3wm you would definitely want to disable client-side decorations and have some access to kill failing apps.
